### ISSUE TITLE
Usage of Viper dependency in Exporters

### ISSUE THREAD

**Issue by ercl** [open-telemetry/opentelemetry-go#1000]
I am working on the [Go SDK Cortex exporter](https://github.com/open-telemetry/opentelemetry-go-contrib/issues/119) and am considering using [Viper](https://github.com/spf13/viper) as a dependency to read a YAML file and create a Config struct. However, Viper has a large footprint size-wise as it includes many features that the exporter will not use such as reading from remote config systems and live watching of config files.

Is Viper an acceptable dependency or should we consider lighter alternatives like [go-yaml](https://github.com/go-yaml/yaml) instead? Looking for OT maintainer recommendations.

cc: @alolita @connorlindsey @ercl

**Comment by bogdandrutu** [comment]
I would suggest every exporter that is not standard to be it's own module (has it's own go.mod), so using a dependency like this will not cause troubles for others.

**Comment by MrAlias** [comment]
From SIG meeting:

> Be sure to create the exporter as a Go module as @bogdandrutu pointed out.
> Use what libraries you think are needed and we can update later on if users think it is too heavy weight. We don't want to block the limited time interns have to work in the project.

One thing to also make clear, the PR for this exporter should be to the https://github.com/open-telemetry/opentelemetry-go-contrib.

Please reopen of there are remaining issues.
