### ISSUE TITLE
RFC to rename global package

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#1009]
[From recent feedback](https://docs.google.com/document/d/1WQ9_KQTAu2cfkh4A0OZFB9DfEtZkBa-1x10JuQJK5mM/edit) and from existing understanding, it is recognized that `global` is not an ideal package name.

> Names such as kv, global and standard can easily overlap with other packages in the language ecosystem. 
Consider giving them more unique names to improve developer productivity. Users shouldn’t stress about importing the name package by constantly checking the import paths or shouldn’t have to rename imports because of an overlap.

Based on the function of this package it seems like an appropriate package, but it would be ideal if we can brainstorm improved names.

**Comment by Aneurysm9** [comment]
I think `global` is a fine package name and I have yet to experience any conflicts with other packages.

**Comment by jmacd** [comment]
I was refactoring some code and noticed that we've moved ErrorHandler to the root of the repository. In the sense that a "root" is global, it might make sense to put everything from the global package into the root of the repository. Then we'd read `otel.SetMeterProvider()` which sounds good, as opposed to `global.SetMeterProvider()`.

**Comment by MrAlias** [comment]
> I was refactoring some code and noticed that we've moved ErrorHandler to the root of the repository. In the sense that a "root" is global, it might make sense to put everything from the global package into the root of the repository. Then we'd read `otel.SetMeterProvider()` which sounds good, as opposed to `global.SetMeterProvider()`.

I like this approach. :+1:

**Comment by MrAlias** [comment]
Looking at this migration our global getter functions (i.e. `MeterProvider`, `TracerProvider`, and `ErrorHandler`) will all clash with their types. Looking at rename options for the getters:

1. `Get*`
2. `Default*`, also switch setter to `SetDefault*`
3. `Global*`, also switch setter to `SetGlobal*`

Leaning towards (1)

**Comment by Aneurysm9** [comment]
> Looking at this migration our global getter functions (i.e. `MeterProvider`, `TracerProvider`, and `ErrorHandler`) will all clash with their types. Looking at rename options for the getters:
> 
> 1. `Get*`
> 2. `Default*`, also switch setter to `SetDefault*`
> 3. `Global*`, also switch setter to `SetGlobal*`
> 
> Leaning towards (1)

+1 for option (1).

**Comment by MrAlias** [comment]
Looking into flattening this out last week and found the initial dependency cycle that likely split the package in the first case.

https://github.com/open-telemetry/opentelemetry-go/blob/b9357d7ee2b37b475521db639f0c738f02ca8e57/api/global/internal/trace.go#L39

And also now,

https://github.com/open-telemetry/opentelemetry-go/blob/b9357d7ee2b37b475521db639f0c738f02ca8e57/api/global/internal/state.go#L25

These import cycles appear to be artifacts of the tight coupling of these packages. A good indicator that they need to be refactored, but it will require a bit more work than just moving this.
