### ISSUE TITLE
RFC to rename kv pacakge

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#1010]
[From recent feedback](https://docs.google.com/document/d/1WQ9_KQTAu2cfkh4A0OZFB9DfEtZkBa-1x10JuQJK5mM/edit) and from existing understanding, it is recognized that `kv` is not an ideal package name.

> Names such as kv, global and standard can easily overlap with other packages in the language ecosystem. 
Consider giving them more unique names to improve developer productivity. Users shouldn’t stress about importing the name package by constantly checking the import paths or shouldn’t have to rename imports because of an overlap.

Based on the function of this package it seems like an appropriate package especially since it makes an attempt to not use `keyvalue`, but it would be ideal if we can brainstorm improved names.

**Comment by Aneurysm9** [comment]
I can't really think of any better package names that don't suffer from the same potential issues.

**Comment by MrAlias** [comment]
Decision from the SIG meeting today was to got with #1052

**Comment by seh** [comment]
This is probably a better place to ask this question: https://github.com/open-telemetry/opentelemetry-go/issues/1052#issuecomment-675459150.
