### ISSUE TITLE
Remove `WithSpan`

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#1013]
The `WithSpan` method of the Tracer interface is a thin wrapper around the `Start` method in the default SDK, and expected to be the same for all SDK implementations. Additionally the function signature has been questioned if the closure will indeed serve users. Instead of trying to make a catch all, we'll remove the method and allow users to implement this in the way that best suits their purpose.

**Comment by MrAlias** [comment]
I'm also considering if this method should just be dropped from the `Tracer` interface.

**Comment by jmacd** [comment]
I support removing `WithSpan`. Anything it does we should be able to accomplish by a `defer span.End()`. The sort of thing you can't do unless you have a `WithSpan`-like function is automatically call the `pprof.Do()`, but users can do that on their own.

**Comment by seh** [comment]
For those of you who belong to the "Honeycomb Pollinators" Slack team, I've brought this up several times before ([here](https://honeycombpollinators.slack.com/archives/CNQ943Q75/p1575470662044200?thread_ts=1575470486.044100&cid=CNQ943Q75) and [here](https://honeycombpollinators.slack.com/archives/CNQ943Q75/p1585500124020900?thread_ts=1575470486.044100&cid=CNQ943Q75)). I too am mystified by the `WithSpan` signature.

**Comment by jmacd** [comment]
There is good support for removing `WithSpan`.

**Comment by jmacd** [comment]
We could introduce a helper, for example.

**Comment by jmacd** [comment]
Perhaps we should specify that `span.End()` should call `recover()` and automatically record an error.

**Comment by MrAlias** [comment]
> Perhaps we should specify that `span.End()` should call `recover()` and automatically record an error.

That seems timely as it seems to be something the spec is looking to add: https://github.com/open-telemetry/opentelemetry-specification/pull/761/files#diff-05dabeeb80a46b2c02de5a02b8151b2cR18
