### ISSUE TITLE
Do not use "ot" to abbreviate "opentelemetry"

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-go#1015]
Here is an example `api/oterror`. Based on the specs https://github.com/open-telemetry/opentelemetry-specification/blob/c33919ea1265081967287a3c3160ba823797bbce/README.md#acronym you should use "otelerror".

**Comment by bogdandrutu** [comment]
I know it is related to https://github.com/open-telemetry/opentelemetry-go/issues/1011 but this is generic and should check all packages like that.

**Comment by MrAlias** [comment]
`oterror` is the only one, it is part of the motivation for #1011 . Closing because this is effectively a duplicate.

**Comment by bogdandrutu** [comment]
Please double check, here is another one:
https://github.com/open-telemetry/opentelemetry-go/tree/master/instrumentation/othttp

**Comment by MrAlias** [comment]
Understood. That is accounted for: https://github.com/open-telemetry/opentelemetry-go/issues/974
