### ISSUE TITLE
Add support for `grpc-trace-bin` propagator

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-go#1018]
See https://github.com/census-instrumentation/opencensus-specs/blob/master/encodings/BinaryEncoding.md

**Comment by jmacd** [comment]
I wonder if someone on the gRPC team would be willing to contribute this support? @mtwo

**Comment by MrAlias** [comment]
possible duplicate of #628

**Comment by MrAlias** [comment]
Closing in favor of #628
