### ISSUE TITLE
Move api/label package to ../internal

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-go#1020]
The api/label package is not a public API and it belongs in ../internal--except that it is likely to be used in the opentelemetry-collector repository and we may wish to move it to some kind of common package that is not internal.

I would propose we move this to a package directory named "common" at the root of the repository. This would help declutter the `/api` package. Even if all contents of the "api" package move up one level (as has been proposed), the current api/label package should end up nested, e.g., common/label to indicate that it is shared code between api, sdk, and collector.

**Comment by MrAlias** [comment]
> The api/label package is not a public API and it belongs in ../internal

+1 for moving to `internal` if this should not be exposed.

> except that it is likely to be used in the opentelemetry-collector repository and we may wish to move it to some kind of common package that is not internal.

Do we have an understanding how the collector will use this? Last I heard there was an aversion to depending on this repo. Has that changed?

> I would propose we move this to a package directory named "common" at the root of the repository. This would help declutter the `/api` package. Even if all contents of the "api" package move up one level (as has been proposed), the current api/label package should end up nested, e.g., common/label to indicate that it is shared code between api, sdk, and collector.

I'm in favor of moving out of the `api` package, but I feel we should avoid a `common` package. The name `common` is overly generic and a catchall. I think moving this to the `internal` package for now and when there is explicit need to depend on parts of it we can expose those parts in an appropriately named package.

I was also wondering if the `labels` package could be merged with the `kv` package? They both seem to provide labeling/key-value objects and functionality.

**Comment by MrAlias** [comment]
Do you still think parts of the `label` package should be moved to an internal package? I'm in favor of not exporting by default if we think things will clutter the API. That said, I wonder if things like `LabelSet` and `Iter` are needed for anyone wanting to test with the project.

**Comment by jmacd** [comment]
I think it's a generally useful class to expose for testing, possibly also for use in exporters.

**Comment by MrAlias** [comment]
I think #1060 addressed the underlying concern here of reorganizing this package. Going to close. Please reopen if there is still work to do.
