### ISSUE TITLE
Integration tests for OTel Collector Attributes

### ISSUE THREAD

**Issue by stefanprisca** [open-telemetry/opentelemetry-go#1035]
Existing integration tests for the OTel Collector ([otel_integration_test](https://github.com/open-telemetry/opentelemetry-go/blob/master/exporters/otlp/otlp_integration_test.go)) only cover integer attributes. 
Maybe it would be interesting to create more use-cases for the attributes by testing the other types (string, bool, array, etc) as well.

The issue was brought up during PR https://github.com/open-telemetry/opentelemetry-go/pull/992#issuecomment-668697443 .

**Comment by MrAlias** [comment]
resolved in #1062
