### ISSUE TITLE
Access to key value pair in tag.Map needs to be thread-safe

### ISSUE THREAD

**Issue by krnowak** [open-telemetry/opentelemetry-go#105]
When calling `Foreach()` on the `tag.Map`, we gain access to every key and value in the map. We can also use `Value()` to get access to a value for a specific key. The keys and values returned should essentially be copies of whatever is contained in the map, and usually they are. There are some troublesome members though. Some of them have the pointer-like semantics, so it is possible to mutate them in the `Foreach` callback or just in the returned object from `Value()`, and thus mutate the contents of the map itself.

Currently that happens for the keys in the map that contain the [BYTES Value](https://github.com/open-telemetry/opentelemetry-go/blob/fafb3daf1efc977851352db36664a1f9ea6edfa3/api/core/key.go#L21-L44). So the map implementation should make a copy of the bytes when giving the access to it.

I'm also wondering if [the `Type` field in `registry.Variable`](https://github.com/open-telemetry/opentelemetry-go/blob/fafb3daf1efc977851352db36664a1f9ea6edfa3/api/registry/registry.go#L25-L30) should also be copied, because it is an interface, so it also could have some pointer-like semantics when doing shallow copy during `Foreach`.

**Comment by jmacd** [comment]
Oops. This is about allowing mutable value data into the SDK.

**Comment by jmacd** [comment]
I'd prefer to remove BYTES than to force a copy.
