### ISSUE TITLE
Tracing http requests

### ISSUE THREAD

**Issue by maxisme** [open-telemetry/opentelemetry-go#1051]
I have written the middleware:
```
func Middleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		ctx := propagation.ExtractHTTP(r.Context(), Propagator, r.Header)
		ctx, span := global.Tracer("").Start(ctx, fmt.Sprintf("%s %s", r.Method, r.URL.Path))
		propagation.InjectHTTP(ctx, propagation.New(propagation.WithInjectors(trace.B3{})), r.Header)
		next.ServeHTTP(w, r)
		span.End()
	})
}
```

Which will create a child span called something like `GET /path` depending on the request. I then want to be able to create a child of this span within a handler so I have done this:
```
r.HandleFunc("/trace", func(w http.ResponseWriter, r *http.Request) {
	ctx := propagation.ExtractHTTP(r.Context(), tracer.Propagator, r.Header)
	_, span := global.Tracer("").Start(ctx, "child span")
	_, _ = w.Write([]byte(fmt.Sprintf("%v", r.Header)))
	span.End()
})
```

I am wondering if this is the correct way to do this as it seems a little bit overkill injecting and then extracting. I feel like there is perhaps a better way to do this just using the `r.Context()`?

**Comment by Aneurysm9** [comment]
Hi!  First, I would suggest looking within the [contrib repo](https://github.com/open-telemetry/opentelemetry-go-contrib) for an instrumentation for your HTTP router of choice.  It looks like you might be using Gorilla Mux, for which we have [an existing instrumentation](https://github.com/open-telemetry/opentelemetry-go-contrib/tree/master/instrumentation/github.com/gorilla/mux) that can be added with a one-liner:

```go
r.Use(muxtrace.Middleware("my-server"))
```

It will handle extracting context from the inbound request, creating a span for the request with a name based on the route name, and ensuring that the span is available in `r.Context()`.  If you are not using Gorilla Mux, most of the other instrumentations follow a similar pattern.  From there you can start a new span in your handler using the `tracer.Start()` method:

```go
r.HandleFunc("/trace", func(w http.ResponseWriter, r *http.Request) {
	_, span := global.Tracer("").Start(r.Context(), "child span")
	_, _ = w.Write([]byte(fmt.Sprintf("%v", r.Header)))
	span.End()
})
```

**Comment by MrAlias** [comment]
Closing based on the last comment looks to have resolved this. If this is in error, please reopen.
