### ISSUE TITLE
Merge the `kv` and `labels` packages

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#1052]
The `kv` package contains definitions for keys, values, and their combined key-values with some functionality around their creation and transformations. The `label` package contains interaction and set functionality around the `kv` package. Merging these packages into a unified `label` package would organize related code into a single import and remove the inherent coupling between the packages.

This would also resolve https://github.com/open-telemetry/opentelemetry-go/issues/1010

**Comment by seh** [comment]
One thing that confuses me—perhaps due to ignorance of the OpenTelemetry specification—is that we now have the word "label" applied to "attributes". Is the label what was previously called the attribute key, or the label a key together with a value? If it's the former, are "key" and "label" synonyms? If it's the latter, are "attribute" and "label" synonyms?

**Comment by MrAlias** [comment]
> One thing that confuses me—perhaps due to ignorance of the OpenTelemetry specification—is that we now have the word "label" applied to "attributes". Is the label what was previously called the attribute key, or the label a key together with a value? If it's the former, are "key" and "label" synonyms? If it's the latter, are "attribute" and "label" synonyms?

It's the latter (a label is a key-value pair), "attribute" and "label" are synonymous. [Attributes](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/common/common.md#attributes) are used in the tracing specification (though have recently been moved to a "common" part of the specification) and [labels](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/metrics/api.md#labels) are used in the metric specification.

I agree this is not ideal.

**Comment by seh** [comment]
Thank you for the clarification. Are you aware of any motion (even rejected) to unify those terms? I recognize that would yield yet more churn in the code. The current state comes after several big moves, but it's still muddled.

**Comment by MrAlias** [comment]
> Thank you for the clarification. Are you aware of any motion (even rejected) to unify those terms? I recognize that would yield yet more churn in the code. The current state comes after several big moves, but it's still muddled.

There was an old conversation in the specification SIG around this issue that was left with the different names being left as is (IIRC this was because no resolution could be reached and it was the default).

However, in this repository I've wondered if we can do better. I have a lot of thoughts on possible approaches, but I think they are better suited for a new issue: https://github.com/open-telemetry/opentelemetry-go/issues/1069
