### ISSUE TITLE
Standardize logging practices within the SDK and plugins

### ISSUE THREAD

**Issue by connorlindsey** [open-telemetry/opentelemetry-go#1068]
I'm working on a Cortex Exporter and noticed that there isn't much consistency as to what logging package is used across the various components (instrumentation plugins, exporters, etc.). As mentioned by @MrAlias on Gitter, this should probably be configurable by the end user. The standard `log` package would probably be a smart default, but I'd like to start a discussion on what the default package should be and how we can make this configurable. Thanks.

**Comment by Aneurysm9** [comment]
A pattern I've had success with in the past is to define a simple interface and provide accessors that fallback to the stdlib `log` package if no implementation is provided.

```go
type Logger interface {
  Print(v ...interface{})
  Printf(format string, v ...interface{})
  // etc., maybe Fatal/Fatalf
}

func FromContext(ctx context.Context) Logger {...}
```

I'd really like to be able to attach labels/fields to a log entry, but I'm not sure there's any consistent interface that could be expected to be common between `log`, `logrus`, `zap`, and any other likely candidate for a `Logger` implementation.

**Comment by cbandy** [comment]
https://github.com/go-logr/logr ?

**Comment by bhautikpip** [comment]
I am writing design/implementation [doc](https://docs.google.com/document/d/1WIHyMyA8ZnKaobJlqvvfzyVBD3HHfU0OC3elOrWKUJs/edit#) to add standardized logging for OTel Go SDK. I am probably planning to discuss this in Thursday's SIG meeting. Feel free to review and post feedback.
