### ISSUE TITLE
Unify Attributes and Labels

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#1069]
Currently `Attribute`s in the tracing portion of this code is synonymous with `label.KeyValue`. This duplicate naming (attribute and label) will lead to confusion for new (and likely existing) users. This duplication comes from the specification itself unfortunately. [Attributes](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/common/common.md#attributes) are used in the tracing and resource specification (and have been unified in the "common" part of the specification) and [labels](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/metrics/api.md#labels) are used in the metric specification. There was a previous attempt to resolve this difference in the specification, but it did not produce a resolution.

Can we do better in this repository?

**Comment by seh** [comment]
Since we are not afraid of renaming packages and moving types, have we considered a package name like "attr"?

**Comment by MrAlias** [comment]
My hope was to unify on the term `label` as it is a complete word and shorter than `attribute`.

It is important that this work does not impact the compatibility of the project. That means that the Spant field will likely need to remain being named `Attributes`. This might also apply to the Resource, but since it is only used in the internal SDK, that might not be as strong a requirement.

**Comment by MrAlias** [comment]
https://github.com/open-telemetry/opentelemetry-specification/issues/948#

This is likely going to be the top issue at the next Specification SIG meeting.

**Comment by MrAlias** [comment]
Specification issue is being tracked here now: https://github.com/open-telemetry/opentelemetry-specification/issues/1113

**Comment by MrAlias** [comment]
Given the `label` package is already used for attributes, we should not be blocked with issues blocking https://github.com/open-telemetry/opentelemetry-specification/issues/1113 and should be able rename the `label` package and metric use of it.

**Comment by MrAlias** [comment]
Let's rename the `label` package to `attr`.
