### ISSUE TITLE
Release plan

### ISSUE THREAD

**Issue by ilyakaznacheev** [open-telemetry/opentelemetry-go#1070]
Hello, where I can find a release plan for Go lib with feature list and dates?

Sorry for the dumb question, but I just can't find it anywhere.

**Comment by MrAlias** [comment]
This is something the community as a whole is outlining: https://github.com/open-telemetry/opentelemetry-specification/pull/828

We'll be sure to include our version when it is a bit more established what those features are.

**Comment by MrAlias** [comment]
We are tracking our GA release with [this project](https://github.com/open-telemetry/opentelemetry-go/projects/1) and [this milestone](https://github.com/open-telemetry/opentelemetry-go/milestone/10). Hopefully, this helps to answer some of the projects timelines.
