### ISSUE TITLE
Adding ForceFlush() to Batch Span Processor

### ISSUE THREAD

**Issue by snehilchopra** [open-telemetry/opentelemetry-go#1072]
The [official OT specs](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#forceflush), mandate the requirement of a `ForceFlush` method in the Batch Processor Interface.

However, per my conversation with @rghetia, it seems that at the time the Batch Span Processor for Golang was implemented, the `ForceFlush` method was not included in the specs. 

I was curious to know if we would like to go ahead with its implementation.

Please let me know your thoughts, thanks!

**Comment by MrAlias** [comment]
Duplicate of https://github.com/open-telemetry/opentelemetry-go/issues/902. Going to track here.

**Comment by MrAlias** [comment]
This needs to also include adding a `Shutdown` Method to the span processors.
