### ISSUE TITLE
Version handling of gRPC / protobuf libs

### ISSUE THREAD

**Issue by wonko** [open-telemetry/opentelemetry-go#1075]
Hi,

when using the opentelemetry-go package to instrument and export data from our projects, we bumped into the dependencies this project has on the grpc and protobuf modules (https://github.com/open-telemetry/opentelemetry-go/blob/master/exporters/otlp/go.mod#L12 & L19). These are at different versions we require, and break compatibility. This is problematic, as with every release of the otel exporters, it seems the proto and grpc libs are bumped to different versions, forcing us to keep adapting these into our stack (which is exactly a grpc/protobuf based service, with many endpoints, messages, etc. We like to keep these base modules stable on our end for certain spans of time.)

For now, we are stuck at an older version of the otel stack, and we can't upgrade unless we refactor some parts of our stack. I guess others will bump into this as well, both in using versions which are too new, or too old, or incompatible in any other way. This might also become true with future inclusions of other modules.

Is there a plan to make the otel exporter modules less intrusive (either by forking/embedding these modules directly into the project, or some other way)? Is there a guideline/roadmap/... on which external libs are included and when version bumps should happen? ...

**Comment by MrAlias** [comment]
@wonko thanks for using OTel and providing some feedback here. I'm not sure I fully understand the issue(s) you are running into.

> when using the opentelemetry-go package to instrument and export data from our projects, we bumped into the dependencies this project has on the grpc and protobuf modules (https://github.com/open-telemetry/opentelemetry-go/blob/master/exporters/otlp/go.mod#L12 & L19).

What version of `go.opentelemetry.io/otel` are you using? Also what other modules are you using?

We recently split the all of the exporters, including the OTLP one you listed, into their own modules to remove the gRPC and protobuf dependencies from the main API.

> with every release of the otel exporters, it seems the proto and grpc libs are bumped to different versions, forcing us to keep adapting these into our stack (which is exactly a grpc/protobuf based service, with many endpoints, messages, etc. We like to keep these base modules stable on our end for certain spans of time.)

We indeed try to stay current with dependencies, especially while in this pre-GA phase we currently in. I'm kind of surprise you are having compatibilities issues here though. The Go module system is designed (AFAIK) to resolve just these issues. What version of Go are you using?

> Is there a guideline/roadmap/... on which external libs are included and when version bumps should happen? ...

We don't have any global and current decision on dependency upgrades. In conversations we have all unofficially seemed to come to the same consensus that our upgrades should be as backward compatible as possible. [As we near GA](https://github.com/open-telemetry/opentelemetry-go/projects/1) I expect us to have a more defined policy in place to address this question.

**Comment by wonko** [comment]
@MrAlias Thanks for looking into this.

The moment we include the otlp exporter as a module, we're forced to use the version of the grpc module defined in the linked go.mod. This clashes with our own version of grpc we need to run our stack ... and you can't include two minor versions of a module (1.3.x (our stack) and 1.4.x (otlp exporter) in this case).

We currently work around this by replacing your version with ours, and we're just lucky it still compiles, but this isn't a guarantee towards the future.

**Comment by Aneurysm9** [comment]
Does the grpc module not adhere to semver?  It seems that it should indeed be a guarantee that a higher minor version can be used in place of a lower one and still compile and function correctly, at least post v1.0.  If the grpc module publishes incompatible changes as minor version increments, I'm not sure there's much we can do about it.  We can test that our code continues to work but we can't test all possible combinations of our library and consumer libraries.  Even freezing the version of grpc that we use wouldn't be very helpful as then consumers who use newer versions of the grpc library may encounter incompatibilities.

**Comment by MrAlias** [comment]
Closing based on @Aneurysm9 comment.
