### ISSUE TITLE
SDK should populate telemetry.sdk.* resource attributes

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-go#1076]
As per the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/resource/semantic_conventions/README.md#telemetry-sdk), the SDK must set the `opentelemetry.sdk.name` to `opentelemetry`. It would be nice if the other `telemetry.sdk.*` values were also set.

**Comment by MrAlias** [comment]
My first thought is this can be setup as a resource detector that sets up all the relevant attributes. Is this in line with what you are envisioning @codeboten

**Comment by codeboten** [comment]
@MrAlias I don't have a clear picture of how resource detectors are used in the Go implementation. In the Python implementation we decided to add those attributes to the Resource itself instead of a resource detector, you can see the discussion that lead us there here: https://github.com/open-telemetry/opentelemetry-python/issues/932#issuecomment-672278737

The implementation was done in this PR: https://github.com/open-telemetry/opentelemetry-python/pull/1053

**Comment by MrAlias** [comment]
> The implementation was done in this PR: [open-telemetry/opentelemetry-python#1053](https://github.com/open-telemetry/opentelemetry-python/pull/1053)

Gotcha. This was the implementation that I was not sure is desired from a user perspective. It makes sense to make it easy to annotate telemetry by including this information in the `Resource`, but I expect having this showup without users configuring it might be bothersome to certain users. Especially users that prioritize optimization by reducing included information to an absolute minimum.

Having this provided by a detector would give the user the choice to include this or not. I'll add this to the SIG meeting agenda for later today to see if I can get more input on this.
