### ISSUE TITLE
Stability Roadmap?

### ISSUE THREAD

**Issue by thequailman** [open-telemetry/opentelemetry-go#1080]
Hello, I am considering using this library but looking at the current master docs vs the latest release (0.10.0), there seems to be a lot of changes pending--labels for instance seems new and the examples are quite different.  What does the roadmap towards 1.0 look like for this library?  When will the API stabilize?

**Comment by Aneurysm9** [comment]
There is indeed a great deal in flux right now.  We have just completed a restructuring of the Go modules in this repository to minimize the footprint of including the API in an instrumented library and the [OTel Spec](https://github.com/open-telemetry/opentelemetry-specification) itself is undergoing rapid change as we try to nail down any final BC-breaking changes for the upcoming trace specification RC.  You can track progress toward that stabilization milestone [here](https://github.com/orgs/open-telemetry/projects/4).  As the specification stabilizes we are attempting to keep up with it in this project, but we will obviously lag somewhat behind.  The issues remaining in this repository that must be completed before a GA release can be tracked with the [`release:required-for-ga` label](https://github.com/open-telemetry/opentelemetry-go/issues?q=is%3Aopen+is%3Aissue+label%3Arelease%3Arequired-for-ga).

**Comment by MrAlias** [comment]
I've added a section to the main README that links to our new [project boards](https://github.com/open-telemetry/opentelemetry-go/projects) and [milestones](https://github.com/open-telemetry/opentelemetry-go/milestones). Hopefully this helps make this journey to stability a bit more visible.

**Comment by thequailman** [comment]
@MrAlias thank you that helps out a lot!
