### ISSUE TITLE
How to properly do context propagation (http & grpc)?

### ISSUE THREAD

**Issue by moorara** [open-telemetry/opentelemetry-go#1091]
With `http` and `grpc` examples removed (and related instrumentation packages) in `v0.11.0`, I see three options for injecting and extracting correlation contexts:

  - `api/trace`: using `Inject` and `Extract` methods available on `B3` (which `B3Encoding` should be used?)
  - `api/correlation`: using `Inject` and `Extract` methods available on `CorrelationContext`
  - `api/propagation`: using `InjectHTTP` and `ExtractHTTP` methods.

How are these three approaches different and which one is recommended?

**Comment by MrAlias** [comment]
The examples and instrumentation has been moved BTW:

* https://github.com/open-telemetry/opentelemetry-go-contrib/tree/master/instrumentation/net/http
* https://github.com/open-telemetry/opentelemetry-go-contrib/tree/master/instrumentation/net/http/example
* https://github.com/open-telemetry/opentelemetry-go-contrib/tree/master/instrumentation/net/http/httptrace
* https://github.com/open-telemetry/opentelemetry-go-contrib/tree/master/instrumentation/net/http/httptrace/example
* https://github.com/open-telemetry/opentelemetry-go-contrib/tree/master/instrumentation/google.golang.org/grpc
* https://github.com/open-telemetry/opentelemetry-go-contrib/tree/master/instrumentation/google.golang.org/grpc/example

To answer the question directly though, nothing has changed an you would still use `propagation.ExtractHTTP` and `propagation.InjectHTTP` with the configured or global propagators.

These will likely change names in an upcoming release as they have been renamed at the specification level.
