### ISSUE TITLE
Reconsider use of singletons

### ISSUE THREAD

**Issue by cep21** [open-telemetry/opentelemetry-go#110]
Hi,

Many people in the Go community disagree with singletons: i.e. Package global state.  A few people have spoken about them in the past, including [this post](https://dave.cheney.net/2017/06/11/go-without-package-scoped-variables) by Dave Cheney and [this post](https://peter.bourgon.org/blog/2017/06/09/theory-of-modern-go.html) by Peter Bourgon, [this talk](https://go-talks.appspot.com/github.com/cep21/go-talks/practical-advice-for-go-library-authors.slide#12) at gophercon 2016, and this medium post about [Aspects of a good Go library](https://medium.com/@cep21/aspects-of-a-good-go-library-7082beabb403).

It is possible to implement the open-telemetry API without package global state.  While singletons are clever ways to avoid explicit dependencies, they make the dependencies of an API less clear by hiding dependencies inside package private code rather than parameters.  [Clear is better than clever](https://www.youtube.com/watch?v=PAAkCSZUG1c&t=14m35s).

Singletons create API lock in by disallowing users from injecting their own solutions to dependent libraries if they decide to move away from open-telemetry in the future.  More about this is talked about in the post [What “accept interfaces, return structs” means in Go](https://medium.com/@cep21/what-accept-interfaces-return-structs-means-in-go-2fe879e25ee8)

Singletons are a viral API design choice.  If a library I depend upon uses Singletons, then I'm forced into their singletons.  On the other hand, if a library does not use Singletons and I want to make it Singletons I can.  Viral APIs are generally discouraged as they limit the ability to refactor code in the long term.

Singletons make it difficult to piecemeal refactor code by pushing all dependent library code along a single code path. Incremental API change is important for large code bases and was the driving factor for [Go's alias proposal](https://go.googlesource.com/proposal/+/master/design/16339-alias-decls.md).

It is possible to implement the open telemetry described API without singletons.  I strongly hope this position can be reconsidered or discussed.

Thanks!

**Comment by rghetia** [comment]
stale issue.
