### ISSUE TITLE
Investigate a RecordException like method for an API Span

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#1104]
[The specification](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#record-exception) has added a `RecordException` method to the API Span. This is to record things like a Go panic as a Span event.

We currently only have a `RecordError` method on the Span. This method is not something specified in the specification and doesn't seem suited to record a [`runtime.Stack`](https://golang.org/pkg/runtime/debug/#Stack).

Should the `RecordError` method be removed?

Should we add a method that helps in panic recovery? Possibly something that can be deferred and adds an event if a panic is occuring.

**Comment by Aneurysm9** [comment]
I think we might want to add an option to `RecordError` to trigger recording of a stack trace, perhaps adding a `RecordException` convenience wrapper that automatically adds that option to a `RecordError` invocation.  

As for panic recovery, I think the existing `RecordError` or proposed `RecordException` would be good candidates for users who are trapping their own panics.  The [`span.End()`](https://github.com/open-telemetry/opentelemetry-go/blob/master/sdk/trace/span.go#L117-L126) method has a panic recovery mechanism built in that adds an event with the error information.  Adding a stack trace as attributes to that event would probably be a good idea.  Perhaps it could wrap the received error before re-`panic`ing with a sentinel error type to avoid recording the same error on an entire stack of spans that are being unwound.

**Comment by MrAlias** [comment]
This can likely be closed. We need to double check, but this is likely in line with the specification.

**Comment by MrAlias** [comment]
Consolidating the conversation in #1491
