### ISSUE TITLE
Remove API Span SetAttribute method

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#1107]
https://github.com/open-telemetry/opentelemetry-go/blob/3b3c263d9a222e307f9fd27274c413d82b8b37a6/api/trace/api.go#L136-L137

This method is redundant and likely a hold over from before the `label.Value` could be inferred from an `interface{}`. This redundancy will only serve to confuse users over which method should be used. Removing will clean up the API and should be done before it reaches GA.

With regards to compliance with the specification, it is [somewhat vaguely defined](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#set-attributes) if one method can suffice:

> A Span MUST have the ability to set Attributes associated with it.
> The Span interface MUST provide:
>   * An API to set a single Attribute where the attribute properties are passed as arguments...

Given `SetAttributes` is variadic it can be used to _set a single Attribute_ as well as has the ability to _set Attribute**s**_ associated with a Span:

https://github.com/open-telemetry/opentelemetry-go/blob/3b3c263d9a222e307f9fd27274c413d82b8b37a6/api/trace/api.go#L133-L134

Therefore, `SetAttribute` should be removed.

**Comment by stanleynguyen** [comment]
Hey @MrAlias can I take this one?
