### ISSUE TITLE
Consider separating out git repository for tracing from metrics

### ISSUE THREAD

**Issue by cep21** [open-telemetry/opentelemetry-go#111]
Hi,

Tracing, logging, and metrics all help observability, but they are very different things.  Companies that do one, may not do another.  Systems that solve one well look very different from systems that solve another well.  There is no clear reason to have them all in one repository, but very compelling reasons to separate them.

# API differences

The API differences between metrics are tracing are very large.  What little they share can be similarly solved with copying.  A little copying is better than a little dependency.

# Repository size and signal to customers

People in the past have complained about the size of this repository's public API.  It is much bigger than similar repositories that do any of those individually. This size carries a signal of bloat that is antithesis to Go's best practices around smaller libraries that focus and do one thing well.  It sends a bad signal to people wanting to evaluate a library's focus.

# Semantic versioning

The standard way to do semantic versioning in Go is modules.  Modules work best with git tags to represent semantic versions.  Because of the differences between metrics and tracing, it is very likely that a change in the metrics API may not require a change in the tracing API.  By putting both in the same repository you potentially force metrics users to do a major version change when tracing updates.

# Potential for flexibility 

Metrics and logging are very old observability patterns that have had time to mature into a somewhat consistent API.  Tracing is much newer and the thoughts around what a good tracing API should look like are currently fragmented.  It is possible that opentelemetry may land on a good solution for metric standardization while failing to make the best possible tracing API.  Or the other way around, doing tracing very well while failing at some aspect of metrics.  By separating these repositories people do not have to feel all in on both or neither.

# Better API design

A well written metrics abstraction should be able to interact with a well written tracing abstraction and a well written logging abstraction.  Being separate, interchangeable, and working  together is proof the API is flexibly designed.

**Comment by jmacd** [comment]
I believe when we reach a point of maturity, it will be feasible to make this separation. Currently, it's the context propagation stuff that binds metrics and tracing. There are a bunch of issues asking for this to be separated from OTel proper (e.g., https://github.com/open-telemetry/opentelemetry-specification/issues/70).  When this is done, we can split the core library into three repos (context, metrics, tracing). We also have discussed eventually moving the exporters out, because they have random dependencies that most users don't want to build (e.g., Jaeger->Thrift).

**Comment by tedsuo** [comment]
Hi @cep21. There is definitely the issue of clean API design. However, as @jmacd mentioned, the observability APIs do end up sharing certain concepts, which we are in the process of separating more decisively. One example include correlations, where independent observations - including those made across  different observability APIs - can be indexed and associated with each other. Another example includes context propagation, where all observability systems use the same subsystem for transmitting their data. 

I can repo separation of core components happening as part of the process of transitioning to a long term support guarantee for the v1.0. But pulling some of what are currently SDK innards out into plugins can happen sooner.

You mentioned the observability APIs, but for me, it's actually moving the context propagation mechanism into its own repo which I would really like to see. Ensuring that context propagation is  cleanly separated into a lower layer will help drive adoption of that mechanism, and will make it easier to share with gRPC and other projects, as we know that some groups would feel odd about depending on an observability project for their context propagation. :)

**Comment by jmacd** [comment]
I will propose we set a date sometime after our Alpha release and sometime before our Beta releases begin, to split the repository into packages along the lines that you suggest. We need to flush our more on context propagation, which binds these two together.

**Comment by jmacd** [comment]
See also #261

**Comment by rghetia** [comment]
closing this unless it is mandated by the specification.
