### ISSUE TITLE
Meter#Register hangs indefinitely if meter not started

### ISSUE THREAD

**Issue by nicks** [open-telemetry/opentelemetry-go#1117]
Given this code:

```
meter := view.NewMeter()
err := meter.Register(views...)
```

the meter.Register call hangs forever waiting on the go channel. I didn't find anything in the documentation that suggested I needed to call Start() before doing any Register calls

**Comment by MrAlias** [comment]
I'm not sure I follow your code example. Is this for OpenTelemetry?

Can you expand to the example to be a minimal and runnable example of the error?  Also, and links to the function/methods you are calling would be helpful.

**Comment by nicks** [comment]
dammit, I'm a dope! I meant to file this under opencensus, and somehow clicked on one of their links to opentelemetry. My apologies!
