### ISSUE TITLE
Add HTTP protocol support to OTLP

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#1122]
Currently the OTLP exporter only export using the [grpc protocol](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/protocol/otlp.md#otlpgrpc). Both the [HTTP protocols](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/protocol/otlp.md#otlphttp) required by the specification, http/json and http/protobuf, need to be supported.

Additionally, having gRPC libraries included in dependencies by default for all use of the OTLP exporter can be problematic for many users. Especially if these uses plan to use one of these HTTP protocols. When splitting out the supported protocols design thought needs to given to how we can possibly support a separated model. Possibly having a sub-module of the OTLP exporter module that contains "drivers", similar to the [`database/sql/driver`](https://golang.org/pkg/database/sql/driver/), can achieve this.

**Comment by huikang** [comment]
Hi, @MrAlias , I am interested in this task. Please assign it to me, if no one has taken it. Thanks.

**Comment by huikang** [comment]
@MrAlias , I setup an oltp collector which receives HTTP/JSON POST request at port `55681`. I was sending the following request with some test span content, which returns http code 200. 

```
curl --location --request POST 'http://localhost:55681/v1/trace' \
--header 'Content-Type: application/json' \
--data-raw '{
    "trace_id":"ZGJhZmU2Yzc4Y2FkNjkwN2RhNTdjZWVlYThhYTFjNjQK",
    "span_id": "YzBmMTM1ZjU3MmNjNGI3ZAo=",
    "name": "test"
}'
```

However, the collector's zpage does not show any received data, so I think there is some wrong with the request body. Could you please provide some advice on how to form a valid http/JSON content of a span. Thanks.

**Comment by huikang** [comment]
I think I found some example at the receiver's test file: https://github.com/open-telemetry/opentelemetry-collector/blob/e7e66939263ccbd99c9ac9352960c263d464263c/receiver/otlpreceiver/otlp_test.go#L101

**Comment by samm02** [comment]
hi @huikang i am also interested in seeing this feature implemented - could you let us know of progress, or would it be possible for me to assist in getting this across the line?

**Comment by huikang** [comment]
@samm02 , feel free to take it. Thanks.

**Comment by MrAlias** [comment]
From this ticket this duplicated:

Implementation on the collector side for reference: https://github.com/open-telemetry/opentelemetry-collector/pull/1021 (issue https://github.com/open-telemetry/opentelemetry-collector/issues/881)

_Originally posted by @nilebox in https://github.com/open-telemetry/opentelemetry-go/issues/860#issuecomment-648512227_

**Comment by punya** [comment]
Does this need to be stable as part of 1.0? The scope seems broader than trace alone (OTLP covers all signals), so I'm wondering if it can be deferred.

**Comment by MrAlias** [comment]
We may not need this for our RC. @punya will confirm if it is needed.

**Comment by punya** [comment]
According to https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/spec-compliance-matrix.md,

> `*` For each type of exporter, OTLP, Zipkin, and Jaeger, implementing at least one of the supported formats is required. Implementing more than one formats is optional.

We already support OTLP/gRPC, so we are compliant. We can defer OTLP/HTTP to post-1.0.

@MrAlias @Aneurysm9 I will remove this issue from the [project](https://github.com/orgs/open-telemetry/projects/5) and I recommend that we remove the `release:required-for-ga` label as well.
