### ISSUE TITLE
Upgrade OTLP to v0.5.0

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#1123]
The OTLP exporter in this repository is still at version v0.3.0 of the OTLP and needs to be upgraded to the latest version (currently [v0.5.0](https://github.com/open-telemetry/opentelemetry-proto/releases/tag/v0.5.0)).  This will require:

1. [x] LastValue aggregation is required: being added in #1165. 
2. [x] Histogram aggregation is required: no open PR

Histogram aggregation is required as an alternative to Summary data points.  Since Summary has no current expression in OTLP v0.5, and at the specification level we are leaning in the direction of Histogram or Histogram-like-Sketch as the default aggregation for ValueRecorder instruments, moving this repository to v0.5 with Histogram implemented for ValueRecorder is the closest we can get to the specification.

After LastValue and Histogram support are added _at the current protocol version_, the exporter can be upgraded to v0.5.

**Comment by jmacd** [comment]
We have histogram aggregation now, so the next step is just to upgrade the protocol, where all we do is swap protocol versions. This will require changing the default for ValueRecorder to Histogram, which is now implemented for OTLP.

**Comment by codeboten** [comment]
I'm happy to help with this one

**Comment by codeboten** [comment]
What's the expected OTLP datapoints for `MinMaxSumCountKind` aggregation now that SummaryDataPoint is gone? @jmacd @MrAlias

**Comment by MrAlias** [comment]
> What's the expected OTLP datapoints for `MinMaxSumCountKind` aggregation now that SummaryDataPoint is gone?

Hmm, I don't know off-hand. I thought it was something the metric SIG is still discussing the best way to add this into the proto IIRC.

**Comment by MrAlias** [comment]
[This](https://github.com/open-telemetry/opentelemetry-go/pull/1230/files#diff-350d737ff3bc7b6473d30f043e6bbd9fR420-R421) seems reasonable for now. @codeboten out of curiosity, did this come from the collectors interpretation of these?

**Comment by codeboten** [comment]
> [This](https://github.com/open-telemetry/opentelemetry-go/pull/1230/files#diff-350d737ff3bc7b6473d30f043e6bbd9fR420-R421) seems reasonable for now. @codeboten out of curiosity, did this come from the collectors interpretation of these?

I ended up following the [java implementation](https://github.com/open-telemetry/opentelemetry-java/blob/master/exporters/otlp/src/main/java/io/opentelemetry/exporters/otlp/MetricAdapter.java#L185)
