### ISSUE TITLE
Is codes package a part of the API?

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-go#1127]
The codes package is living outside of API at the moment but it's a direct dependency to the trace API package. Is there a plan to move codes under api or its current location is intended?

**Comment by MrAlias** [comment]
The goal is to move the API up one package level: https://github.com/open-telemetry/opentelemetry-go/issues/964. This was based on your feedback that the API needed to be more front and center. Moving the codes package was a part of this move.

**Comment by rakyll** [comment]
I can close this issue, looks like #964 is taking care of it!
