### ISSUE TITLE
Find a way to avoid both having tracetest.MockSpan and tracetest.Span

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-go#1129]
It seems like tracetest.Span is a way to test spans whereas Mock* types are utilized for providing mocks for the tracer. Wouldn't it be possible to avoid having both types even though it requires user to create spans via the MockTracer?

Currently, it confuses users that they are two span types. It is also confusing that only one of them is named as a mock which makes the user wonder if the Span is not a mock.

**Comment by matej-g** [comment]
I would take this one. To me it seems same could be applied to `oteltest.Tracer` and `oteltest.MockTracer`, i.e. we could do just with having `oteltest.Tracer`.

**Comment by MrAlias** [comment]
> To me it seems same could be applied to `oteltest.Tracer` and `oteltest.MockTracer`, i.e. we could do just with having `oteltest.Tracer`.

:100:

**Comment by MrAlias** [comment]
resolved with #1306
