### ISSUE TITLE
Moving SpanConfig and TracerConfig to internal

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-go#1130]
Both configuring spans and tracer, there are various types and functions. It's hard for the user to determine which one they should be focused on.

For example, spans work with:
- SpanConfig
- SpanConfigure
- SpanOption

Tracers work with:
- TracerConfig
- TracerConfigure
- TracerOption

If we assume the users won't be engaging with the TracerConfig and SpanConfig directly that much, would it make sense to move SpanConfig, SpanConfigure, TracerConfig and TracerConfigure to the internal package. An example of this pattern can be found at https://godoc.org/google.golang.org/api/option where exported APIs are only options and config is an internal type.

**Comment by rakyll** [comment]
@MrAlias if you are not working on this already, I can also take it!

**Comment by MrAlias** [comment]
@rakyll all yours :+1:
