### ISSUE TITLE
go test ./... and make build fails differently

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-go#1140]
When I run `go test ./...` on the top directory of this repo, it seems to be skipping some packages thus `make build` and `go test` fail differently. 

It confused me as a new contributor. I opened a few PRs after just running go test and the CI failed. I don't have time to investigate this (and don't know if it's a reasonable ask) but it would be great if go test was working as expected.

**Comment by Aneurysm9** [comment]
This seems to relate to [this Go issue](https://github.com/golang/go/issues/27957) which seems to acknowledge that the behavior of `go test ./...` may be unanticipated when multiple modules live in a single repo, but is the intended behavior.  Would additional documentation of the necessity of using `make test` over `go test ./...` in our `CONTRIBUTING.md` help address this issue?

**Comment by rakyll** [comment]
Documenting sounds great, sending a PR.
