### ISSUE TITLE
Update sampling decision names for spec update

### ISSUE THREAD

**Issue by ThomsonTan** [open-telemetry/opentelemetry-go#1180]
OTel trace [SDK spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#sampler) was update with new names for sampling decision.

> * A sampling `Decision`. One of the following enum values:
>   * `DROP` - `IsRecording() == false`, span will not be recorded and all events and attributes
>   will be dropped.
>   * `RECORD_ONLY` - `IsRecording() == true`, but `Sampled` flag MUST NOT be set.
>   * `RECORD_AND_SAMPLE` - `IsRecording() == true` AND `Sampled` flag` MUST be set.

**Comment by arminru** [comment]
There was a follow-up renaming it once again:
https://github.com/open-telemetry/opentelemetry-specification/pull/956/files

**Comment by MrAlias** [comment]
@arminru do you expect this to be "stable" at this point?

**Comment by arminru** [comment]
After consulting my 🔮 I'd say yes, feel free to go ahead!
