### ISSUE TITLE
Reconsider the context keys

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-go#1182]
Based on the conversations at https://github.com/open-telemetry/opentelemetry-specification/issues/948, we may need to reconsider the entries we propagate in the context and whether we will allow two different context keys. I'm filing this issue for visibility because it might be API breaking.

**Comment by punya** [comment]
Does this issue relate to https://github.com/open-telemetry/opentelemetry-go/issues/1069?

**Comment by MrAlias** [comment]
@rakyll can you add a bit more context here. We want to make progress on this for the RC release and want to know if these relate to the remote/local span context keys or some other keys.

**Comment by rakyll** [comment]
The link to the spec issue was incorrect, see https://github.com/open-telemetry/opentelemetry-specification/issues/949 for the earlier discussion.
