### ISSUE TITLE
Update SpanProcessors to be invoked in order they are registered

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#1195]
Currently a TracerProvicer stores known SpanProcessors in a map:

https://github.com/open-telemetry/opentelemetry-go/blob/038f505d12a63d5121e07936981930e20efb0678/sdk/trace/span_processor.go#L46

When a span is started or finished it iterates through the map and invokes the associated method of the SpanProcessor:

https://github.com/open-telemetry/opentelemetry-go/blob/038f505d12a63d5121e07936981930e20efb0678/sdk/trace/tracer.go#L62-L64

https://github.com/open-telemetry/opentelemetry-go/blob/038f505d12a63d5121e07936981930e20efb0678/sdk/trace/span.go#L151-L153

[The specification](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#span-processor) specifies this execution to be ordered:

> Span processors can be registered directly on SDK TracerProvider and they are invoked in the same order as they were registered.

Based on [a recent issue](https://github.com/open-telemetry/opentelemetry-go/issues/1174) it was made clear that this hasn't had any real effect because there is no direct linking between registered SpanProcessors. However, we should update the execution model and conform to the specified behaviour so we are compliant.

This will likely require changing the underlying spanProcessorMap type. It will need to still provide getter/setter functionality as the existing map does so the TracerProvider can correctly unregister any SpanProcessor, but it will need to also track order.

**Comment by huikang** [comment]
Hi, @MrAlias , I'd like to give this a shot. Thanks.
