### ISSUE TITLE
Basic and namedtracer examples do not print traces

### ISSUE THREAD

**Issue by dashpole** [open-telemetry/opentelemetry-go#1197]
Both examples appear to be missing traces.

```bash
example/namedtracer$ go run main.go
```

```bash
example/basic$ go run main.go
[
	{
		"Name": "ex.com.one{instrumentation.name=ex.com/basic,A=1,B=2,C=3,ex.com/lemons=10}",
		"Min": 1,
		"Max": 1,
		"Sum": 1,
		"Count": 1,
		"Quantiles": [
			{
				"Quantile": 0.5,
				"Value": 1
			},
			{
				"Quantile": 0.9,
				"Value": 1
			},
			{
				"Quantile": 0.99,
				"Value": 1
			}
		]
	},
	{
		"Name": "ex.com.two{instrumentation.name=ex.com/basic,A=1,B=2,C=3,ex.com/lemons=10}",
		"Min": 1.3,
		"Max": 2,
		"Sum": 3.3,
		"Count": 2,
		"Quantiles": [
			{
				"Quantile": 0.5,
				"Value": 2
			},
			{
				"Quantile": 0.9,
				"Value": 2
			},
			{
				"Quantile": 0.99,
				"Value": 2
			}
		]
	}
]
```

If I add sdktrace.WithSyncer(exp) as an argument to sdktrace.NewProvider [here](https://github.com/open-telemetry/opentelemetry-go/blob/master/example/namedtracer/main.go#L52), that fixes the problem for the namedtracer.  I can also do the same inside the stdout exporter to fix the basic example.

But looking at the [BatchSpanProcessor](https://github.com/open-telemetry/opentelemetry-go/blob/038f505d12a63d5121e07936981930e20efb0678/sdk/trace/batch_span_processor.go#L86), it looks like the sdktrace.WithBatcher that does exist _should_ cause traces to be printed.

cc @nilebox

**Comment by dashpole** [comment]
Using [WithBatcher](https://github.com/open-telemetry/opentelemetry-go/blob/master/sdk/trace/provider.go#L176) prevents correct handling of shutdown for the batch span processor, and should either return the Shutdown() function, or be removed entirely.

The stdout [NewExportPipeline](https://github.com/open-telemetry/opentelemetry-go/blob/master/exporters/stdout/exporter.go#L53) and [InstallNewPipeline](https://github.com/open-telemetry/opentelemetry-go/blob/master/exporters/stdout/exporter.go#L85) also make it impossible to correctly handle shutdown, as they make use of WithBatcher.  Even if we switched to using WithSpanProcessor directly, we need to return the Shutdown function to ensure it can be correctly handled.

**Comment by MrAlias** [comment]
> The stdout [NewExportPipeline](https://github.com/open-telemetry/opentelemetry-go/blob/master/exporters/stdout/exporter.go#L53) and [InstallNewPipeline](https://github.com/open-telemetry/opentelemetry-go/blob/master/exporters/stdout/exporter.go#L85) also make it impossible to correctly handle shutdown.

This sounds like a good thing to address directly as these are useful convenience functions. We should updated these functions (for all exporters) to support returning a generalized shutdown function or the BSP shutdown function directly.

**Comment by Aneurysm9** [comment]
> > The stdout [NewExportPipeline](https://github.com/open-telemetry/opentelemetry-go/blob/master/exporters/stdout/exporter.go#L53) and [InstallNewPipeline](https://github.com/open-telemetry/opentelemetry-go/blob/master/exporters/stdout/exporter.go#L85) also make it impossible to correctly handle shutdown.
> 
> This sounds like a good thing to address directly as these are useful convenience functions. We should updated these functions (for all exporters) to support returning a generalized shutdown function or the BSP shutdown function directly.

Should the `apitrace.TracerProvider` have a `Shutdown()` method that can invoke the respective `Shutdown()` methods of all configured span processors?

**Comment by MrAlias** [comment]
> Should the `apitrace.TracerProvider` have a `Shutdown()` method that can invoke the respective `Shutdown()` methods of all configured span processors?

This sounds reasonable to me. This is the main thing operators of instrumentation will interact with so it would follow that it would be a useful place to facilitate all this.

**Comment by Aneurysm9** [comment]
> > Should the `apitrace.TracerProvider` have a `Shutdown()` method that can invoke the respective `Shutdown()` methods of all configured span processors?
> 
> This sounds reasonable to me. This is the main thing operators of instrumentation will interact with so it would follow that it would be a useful place to facilitate all this.

Would we need to get a spec update to reflect that new interface?

**Comment by dashpole** [comment]
Should we reopen this to track adding Shutdown(), or open a new issue?

**Comment by Aneurysm9** [comment]
Can you open a new issue?
