### ISSUE TITLE
It should be easy to Shutdown() SpanProcessors

### ISSUE THREAD

**Issue by dashpole** [open-telemetry/opentelemetry-go#1206]
Forked from https://github.com/open-telemetry/opentelemetry-go/issues/1197#issuecomment-697132450.

[SpanProcessor](https://github.com/open-telemetry/opentelemetry-go/blob/master/sdk/trace/span_processor.go#L24) supports a Shutdown() method, which users should call if their program exits to ensure spans are written before shutting down.  Currently, many of our convenience functions, including [WithBatcher](https://github.com/open-telemetry/opentelemetry-go/blob/8c3cc4399245deab10a089024467467f450fe0d4/sdk/trace/provider.go#L193), the stdout [NewExportPipeline](https://github.com/open-telemetry/opentelemetry-go/blob/master/exporters/stdout/exporter.go#L53) and [InstallNewPipeline](https://github.com/open-telemetry/opentelemetry-go/blob/master/exporters/stdout/exporter.go#L85) don't return anything on which shutdown can be called.

One [proposed](https://github.com/open-telemetry/opentelemetry-go/issues/1197#issuecomment-698543704) solution is to add a Shutdown() method to `apitrace.TracerProvider`, which would invoke Shutdown() on all of the span processors.

cc @MrAlias @Aneurysm9

**Comment by huikang** [comment]
@MrAlias , I'd like to take this one if no one has take it.

**Comment by XSAM** [comment]
I raised an issue to specification to reflect the new interface. open-telemetry/opentelemetry-specification#1073
