### ISSUE TITLE
Custom trace IDs?

### ISSUE THREAD

**Issue by csucu** [open-telemetry/opentelemetry-go#1221]
Is there any way to set custom trace IDs for traces? We already have are own trace/request ID's which is propagated across are services, so would be quite useful to use it for the trace. FYI We are using the otel sdk and exporter.

**Comment by Aneurysm9** [comment]
Do you have a system out-of-process that is generating these trace IDs and sending them on to a system using the OTel SDK?  In that case, it sounds like implementing a custom propagator for your propagation format may be what you're looking for.

**Comment by csucu** [comment]
We use a request id coming from haproxy across our systems. Do you have any more details or an example i can take a look at?

**Comment by MrAlias** [comment]
@csucu the recent jager propagator should be a good example to emulate: https://github.com/open-telemetry/opentelemetry-go-contrib/blob/bbc03fa6f1ad325293b5bd5c14f01a46585a5bbe/propagators/jaeger/jaeger_propagator.go#L60-L95
