### ISSUE TITLE
Unify Internal Baggage Map and Label Set

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#1222]
From [this comment](https://github.com/open-telemetry/opentelemetry-go/pull/1217/files/6b4686f6dcb309da624e1618b3e1b5d930378ded#diff-45a1435c9c3424400e487d462d919828R26-R28):

> The underlying [baggage] storage, the Map, shares many of the functional elements of the label.Set. These should be unified so this conversion is unnecessary and there is no performance hit calling this.

A proposed design would be to abstract the `label.Set` into an internal set implementation that supports updates (the Map supports this but the `label.Set` does not (nor should it)). And then the `label.Set` can expose this internal set with the same API and the baggage map can be moved to this internal set.

**Comment by MadVikingGod** [comment]
These datastores have diverged in usage and tradeoffs.  I don't think we should try and unify them.

**Comment by MrAlias** [comment]
> These datastores have diverged in usage and tradeoffs. I don't think we should try and unify them.

Agreed
