### ISSUE TITLE
Update the SpanProcessor Shutdown method

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#1232]
[New changes](https://github.com/open-telemetry/opentelemetry-go/pull/1227/files#diff-e17508b7c9b2ce7e8ba38f9c37c3f113R186) added a `Shutdown` method to the `TracerProvider` to shutdown all `SpanProcessor`s in a unified way.

https://github.com/open-telemetry/opentelemetry-go/blob/bde399bf0d6e971b7cacf1702f980089835dcfe9/sdk/trace/provider.go#L186

This function, however, has a context as a parameter and returns an error. To make these values valid the `SpanProcessor` `Shutdown` method needs to be updated (and the `SpanProcessor`s as well) to match this function signature.  This will also align the implementation with what the specification [specifies](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#shutdown):

> `Shutdown` SHOULD provide a way to let the caller know whether it succeeded, failed or timed out.
> ...
> `Shutdown` SHOULD complete or abort within some timeout.

**Comment by ilyakaznacheev** [comment]
Looks like a good place for me to start contributing to a project that I have been following since the beginning of the year.

May I pick up this, @MrAlias ?

**Comment by ilyakaznacheev** [comment]
@MrAlias should it be a PR to master or to #1227 branch?

**Comment by ilyakaznacheev** [comment]
@MrAlias ready for review
