### ISSUE TITLE
cannot find package "go.opentelemetry.io/otel/api/trace" 

### ISSUE THREAD

**Issue by settys** [open-telemetry/opentelemetry-go#1237]
I use go-redis, which fails,with the error,  

cannot find package "go.opentelemetry.io/otel/api/trace" in any of:
	/usr/local/go/src/go.opentelemetry.io/otel/api/trace (from $GOROOT)
	/go/src/go.opentelemetry.io/otel/api/trace (from $GOPATH)

**Comment by Aneurysm9** [comment]
Are you not using Go modules?  go-redis should be using the [v0.11.0 SDK](https://github.com/go-redis/redis/blob/master/go.mod#L10) according to its `go.mod`.  Building it against `HEAD` is not guaranteed to work and is likely to break intermittently as we work toward 1.0, thus we cannot support it.

**Comment by MrAlias** [comment]
This was moved into the `otel` package on master: https://github.com/open-telemetry/opentelemetry-go/pull/1229

It looks like go-redis uses modules: https://github.com/go-redis/redis/blob/b965d69fc9defa439a46d8178b60fc1d44f8fe29/go.mod#L10

If you make sure you are using a compatible version of Go you should also use modules and not have an issue.

**Comment by louiemiranda** [comment]
Hi @MrAlias If I understand correctly, go-redis should be using the version of go 1.13 and not go 1.11 to run `opentelemetry-go` ?

**Comment by Aneurysm9** [comment]
> Hi @MrAlias If I understand correctly, go-redis should be using the version of go 1.13 and not go 1.11 to run `opentelemetry-go` ?

If you are using Go <1.14 you need to [ensure you are using Go in module mode](https://golang.org/cmd/go/#hdr-Modules__module_versions__and_more).  From 1.14 module mode is the default.  Prior to that you can specify `GO111MODULE=on` as an environment variable to ensure Go operates in module mode.
