### ISSUE TITLE
Support storing Resource on context?

### ISSUE THREAD

**Issue by evankanderson** [open-telemetry/opentelemetry-go#1245]
It would be really handy to be able to say:

```
ctx := otel.WithResource(ctx)

ctx, span := otel.Trace(ctx, "do-my-thing", ...opts)
defer span.End()
otel.Record(ctx, labels, m1.Add(1))
// etc
```

Right now, it seems like this might not be possible because the Measurement is derived from a specific Meter, which means that each Meter may have a separate set of Measurement metadata (description, etc) within the same process.

**Comment by MrAlias** [comment]
This seems like a bit of a mismatch of the layers of OpenTelemetry. A `Resource` is a part of the default OpenTelemetry SDK. They are used to describe the runtime environment an instrumented service is operating in. They are constructed by the person operating the code or using the instrumented library. The included example has the Resource as a known value in the instrumentation, something written with the OpenTelemetry API. This is not something that is possible if the library or code is instrumented outside to the operation of that code. It would mix the OpenTelemetry SDK into the API.

If you would like to make a formal proposal, this type of request would need to be in [the specification](https://github.com/open-telemetry/opentelemetry-specification). Specifically this would require a change to [the context part of the specification](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/context/context.md).
