### ISSUE TITLE
Question: Is OpenTelmetry (De)Serialization Backwards Compatible with OpenTracing Implementations? 

### ISSUE THREAD

**Issue by nchandran3** [open-telemetry/opentelemetry-go#1246]
Is the serialization of `span context` backwards compatible with existing OpenTracing implementations? 

Wondering how we can have an ecosystem of systems / processes that are originally instrumented with OpenTracing implementations, while iteratively introducing OpenTelemetry instrumentation to certain processes. 

For instance, if process A is instrumented using OpenTracing, and sends an HTTP request to process B, which is instrumented with OpenTelemetry, will the deserialization from OpenTracing's representation be compatible with OpenTelemetry? Conversely, if process B sends a span context to process A, will process A be able to deserialize the information as well? Is it a standard serialization format?

**Comment by Aneurysm9** [comment]
This concern is handled by [propagators](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/context/api-propagators.md) in the OpenTelemetry ecosystem.  Interoperability can be achieved as long as both ends of the link are using compatible propagation schemes.  The OTel Go SDK includes support for [the W3C Trace Context format](https://pkg.go.dev/go.opentelemetry.io/otel@v0.13.0/propagators#TraceContext), [the Zipkin B3 formats](https://pkg.go.dev/go.opentelemetry.io/contrib/propagators@v0.13.0/b3), and [the Jaeger format](https://pkg.go.dev/go.opentelemetry.io/contrib/propagators@v0.13.0/jaeger).  It is likely that your existing OpenTracing implementation will utilize one of those formats.  If a non-standard format is used then you can implement the [`TextMapPropagator` interface](https://pkg.go.dev/go.opentelemetry.io/otel@v0.13.0#TextMapPropagator) using one of the existing implementations as a guide.

**Comment by nchandran3** [comment]
If we internally use a binary format in other systems,  is there a recommended way to shoehorn this into a `TextMapPropagator` format?

I saw that binary propagator support was deferred until GA, but is there a way to add this support independently before it is supported by the canonical SDK?

**Comment by MrAlias** [comment]
@nchandran3 the answer will depend on the implementation of your binary format. As an example [the OpenCensus binary propagator](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/master/propagators/opencensus/binary.go) already exists.

If you need more help with this please open a new issue to address this instead of adding to this.
