### ISSUE TITLE
go 1.15.2: cannot find package "go.opentelemetry.io/otel/api/trace" in any of GOROOT or GOPATH

### ISSUE THREAD

**Issue by satvirgrewal** [open-telemetry/opentelemetry-go#1247]
I am using go 1.15.2 for my VSTS pipeline. 

The pipeline was working fine till last week and today it is failing with the issue if not able to find the 'go.opentelemetry.io/otel/api/trace'

Approaches tried based of your responses to similar issues:

1. I have tried using export GO111MODULE=on . No luck

<img width="799" alt="Screen Shot 2020-10-12 at 7 59 34 PM" src="https://user-images.githubusercontent.com/21002217/95803350-7f5faf80-0cc5-11eb-85c0-ee7192a14078.png">

**Comment by MrAlias** [comment]
Are you using the latest version of `github.com/go-redis/redis`? It was updated to support the latest release of `opentelemetry-go` 3 days ago:

https://github.com/go-redis/redis/blob/36223c9349f0c78a386df4a38c00a077cc38cdce/go.mod#L10

Do you have a different version of go.opentelemetry.io/otel installed other than v0.13.0? Is it a version that is compatible with the version of github.com/go-redis/redis you are using?

Please reopen this if you are able to verify these things and are still having an issue.
