### ISSUE TITLE
Add a Meter testing method to the Harness of the `oteltest` package

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#1250]
Currently the Harness in the `oteltest` validates Tracer implementations (and the Spans it produces).

https://github.com/open-telemetry/opentelemetry-go/blob/65044a118bc4a26d40b694c11f142e43fd083544/oteltest/harness.go#L44

A similar method should be added to the Harness to validate the functionality of the Meter API.

**Comment by yeongjukang** [comment]
@MrAlias Hi, Can I participate for this if it is still needed?

**Comment by 979156** [comment]
@MrAlias Hi, Can I participate for this if it is still needed?

**Comment by MrAlias** [comment]
@979156 I would hold off on this. The metric API is expected to change significantly in the near future.
