### ISSUE TITLE
Rename SpanContext to SpanReference

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#1256]
Update needed to track these changes: https://github.com/open-telemetry/opentelemetry-specification/pull/1075#

**Comment by cpackingham** [comment]
@MrAlias Mind if I take this one?

**Comment by cpackingham** [comment]
Definitely going to need some extra eyes on the opentracing bridge and the exporters. Opentracing seems to have its own concepts of SpanReference and SpanContext so renaming is pretty dicey there - same with Zipkin.

**Comment by cpackingham** [comment]
@MrAlias  This issue should be closed - the decision to rename SpanContext was reverted in the spec: https://github.com/open-telemetry/opentelemetry-specification/issues/1126

**Comment by MrAlias** [comment]
@cpackingham thank you for digging into this and sorry it ultimately was wasted time. :disappointed:
