### ISSUE TITLE
(RFC) Rename `NewConfig` in `sdk/resource` to better fit its function

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#1263]
Currently `NewConifg` doesn't return a `config` and there are likely better names for this function. I'm guessing a better name would reflect the `Resource` being returned and the use of `Detectors` to create it. Possibly `NewFromDetectors` to compliment `New`.

We should brainstorm names here, form consensus, and then implement a new name.

_Originally posted by @MrAlias in https://github.com/open-telemetry/opentelemetry-go/pull/1235#discussion_r506771298_

**Comment by jmacd** [comment]
I'd like to fix this in the open PR. I've proposed we replace `New()` with this new method in #1235. How does this sound?

**Comment by jmacd** [comment]
Maybe we could name a new helper with a signature `NewFromAttributes(...label.KeyValue) *Resource` which calls the more-general `New()`?

**Comment by MrAlias** [comment]
> I'd like to fix this in the open PR. I've proposed we replace `New()` with this new method in #1235. How does this sound?

> Maybe we could name a new helper with signature `NewFromAttributes(...label.KeyValue) *Resource` which calls the more-general `New()`?

I am in support of both of these. :+1:

**Comment by Aneurysm9** [comment]
> > I'd like to fix this in the open PR. I've proposed we replace `New()` with this new method in #1235. How does this sound?
> 
> > Maybe we could name a new helper with signature `NewFromAttributes(...label.KeyValue) *Resource` which calls the more-general `New()`?
> 
> I am in support of both of these. 👍

I second that support.

**Comment by MrAlias** [comment]
Fixed in #1235
