### ISSUE TITLE
Named Tracer

### ISSUE THREAD

**Issue by rghetia** [open-telemetry/opentelemetry-go#127]
Add support for named tracer.

```go
trace.SetGlobalProvider(sdkProvider)
tracer := trace.GlobalProvider().Tracer("example/namedtracer/main")
ctx, span := tracer.Start(ctx, "span/foo")
```

**Comment by jmacd** [comment]
Discussion: propose to remove `WithResources`, `WithComponent`, and `WithService` for the time being, while "Named Tracer" questions are resolved.
