### ISSUE TITLE
Update README and documentation to better communicate pre-GA state

### ISSUE THREAD

**Issue by yogo1212** [open-telemetry/opentelemetry-go#1279]
via https://github.com/go-redis/redis/pull/1541

go sees the tag in go.mod as a 'minimum version' [1]. As a consequence, their recommendation is this:

> Packages intended for public use should try to maintain backwards compatibility as they evolve. The Go 1 compatibility guidelines are a good reference here: don’t remove exported names, encourage tagged composite literals, and so on. If different functionality is required, add a new name instead of changing an old one. If a complete break is required, create a new package with a new import path.

The recent move of the tracing API breaks automated setups relying on this very useful go principle.

Please use at least deprecations warnings and keep the old API intact for at least for one version jump to give other projects time to adjust their code.
Even better would be to create a new package otel/v2 - see the section about "semantic import versioning" in the linked document.

[1] https://research.swtch.com/vgo-principles

**Comment by MrAlias** [comment]
This project is still an active work in progress. We are in a pre-GA phase of our lifecycle that will include breaking changes.

With our GA 1.0 release we will be holding our design choices to conform to the methodology you linked, until then we do not make backwards compatibility guarantees. You can track our progress to this stable release on [this project board](https://github.com/orgs/open-telemetry/projects/5)

**Comment by yogo1212** [comment]
@MrAlias i respect that. and i did oversee that section second to last section of the readme - my mistake.

consequentally, the readme should reflect that state better.
prominent projects like go-pg or go-redis and Google Cloud Platform are already using this package - with major versions and many users.

**Comment by MrAlias** [comment]
> ...the readme should reflect that state better.

That is a good point. I'll get a PR together to address that.
