### ISSUE TITLE
Offer defaults for histogram boundaries

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-go#1283]
It would be great to have sane defaults for histogram boundaries.

In Prometheus, histograms are offered default boundaries as a constant one can set explicitly.

https://github.com/prometheus/client_golang/blob/master/prometheus/histogram.go#L63

**Comment by MrAlias** [comment]
Thanks for opening this. I agree sane defaults are helpful.

To better understand the scope here, is this proposing the prometheus exporter incorporate these same default histogram boundaries? Or, something else?

**Comment by atoulme** [comment]
Something like this would be enough?

```
diff --git a/sdk/metric/aggregator/histogram/histogram.go b/sdk/metric/aggregator/histogram/histogram.go
index 2df53a4..bc8c047 100644
--- a/sdk/metric/aggregator/histogram/histogram.go
+++ b/sdk/metric/aggregator/histogram/histogram.go
@@ -25,6 +25,11 @@ import (
        "go.opentelemetry.io/otel/sdk/metric/aggregator"
 )
 
+const(
+       // DefaultBoundaries defines good default boundaries that can be used when defining histogram aggregation.
+       DefaultBoundaries = []float64{.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10}
+)
+
 // Note: This code uses a Mutex to govern access to the exclusive
 // aggregator state.  This is in contrast to a lock-free approach
 // (as in the Go prometheus client) that was reverted here:
```

**Comment by MrAlias** [comment]
Ah, I see. I don't think we should add defaults within the SDK itself. It is impossible to make a recommendation for buckets to cover even the common use cases of histograms. For example, if someone is measuring request latency the recommendations would be different if measured in seconds, milliseconds, microseconds, or nanoseconds. That recommendation, even if you could resolve the unit discrepancy issue, would change for measurements of network throughput, disk I/O, fan speed, temperature, or queue length.

It would make more sense if we wanted to include this in the Prometheus exporter as the default as that matches what Prometheus users expect.

**Comment by atoulme** [comment]
Understood, closing.
