### ISSUE TITLE
*Impl type names are confusing

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-go#1284]
Per spec, https://github.com/open-telemetry/opentelemetry-specification/tree/master/specification/metrics, there are various metrics interfaces that sit in the boundary of the SDK and the API. These types are named as "*Impl" which resembles "implementation" types from other languages. Is there a better way to rename them to avoid the confusion that they are concrete types.

For example, MeterImpl sounds like a concrete type for Meter even though it's not. In Go, *Impl is not a naming convention for concrete types either. So the API surface looks unidiomatic and harder to navigate from the users perspective.

**Comment by MrAlias** [comment]
Resolved by https://github.com/open-telemetry/opentelemetry-go/pull/2587
