### ISSUE TITLE
Arbitrary type aliases?

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-go#1285]
The root package contains type aliases for Meter and Tracer (see https://pkg.go.dev/go.opentelemetry.io/otel#Tracer). It's not clear why these aliases exist. If they exist for backwards compatibility reasons, we should document they are deprecated.

**Comment by MrAlias** [comment]
The soon to be released master branch contains a refactor that removes these. The API has been moved to the top level otel package to make it more prominent and easier for users to understand what they should work with. This is based on feedback we received from you a while ago.

I'm going to close this as it has been resolved on master, but if you can take a look there I would appreciate any feedback you have.
