### ISSUE TITLE
The preferred error handler

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-go#1286]
Currently, there are two global error handlers in the package. 

https://pkg.go.dev/go.opentelemetry.io/otel@v0.13.0/api/global#ErrorHandler
https://pkg.go.dev/go.opentelemetry.io/otel@v0.13.0/#ErrorHandler

It's not clear to the developer which one is the preferred/canonical one. Let's add some docs about deprecation if we cannot remove one or the other due to backwards compatibility.

**Comment by MrAlias** [comment]
The global package `ErrorHandler` is a function that returns the default implementation of the otel `ErrorHandler`. In #1009 I had proposed we change the `ErrorHandler` function to `GetErrorHandler`. This was with the goal of integrating the global package into the otel package and avoiding the name collision, but based on your point @rakyll it sounds like a good move to also make it clear what the purpose of each declaration is.
