### ISSUE TITLE
Consider moving Number into its own package

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-go#1287]
Even though the metric.Number type is currently only used by the metric package, it might be good to consider the into its own package if we would need a similar high level type for another telemetry signal/package. Given the size of the metric package, it might be also useful to split this type to reduce the API surface exported from the package.

What do you think?

/cc @MrAlias @jmacd

**Comment by MrAlias** [comment]
I was considering this as well and think it is a good idea.

Possibly relate, I had started looking into if we could encapsulate the number kind in the number type, similar to how we keep the label kind with the label. It might be worth evaluating this if we move the number to a dedicated package.

**Comment by MrAlias** [comment]
Addressing in https://github.com/open-telemetry/opentelemetry-go/issues/1303
