### ISSUE TITLE
Async/Sync concepts shouldn't be represented as types

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-go#1289]
The metrics specs introduces async and sync as concepts to explain how the data collection will be behave, https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/metrics/api.md#synchronous-and-asynchronous-instruments-compared. 

These concepts doesn't necessarily have to be represented in the API but rather their behavior should be expressed in observer vs non-observer aggregators (as it's already done, e.g. Observers implement Async, non-observers implement Sync methods). Exposing these concepts as types make it extreme difficult for the user to understand what they are for.

(I'm currently working on an experimental package that restructures the metric package that will address this issue. I will share it once I'm feeling better about it but filing this issue as a placeholder so we can have a conversation about it.)

**Comment by MrAlias** [comment]
> I'm currently working on an experimental package that restructures the metric package that will address this issue. I will share it once I'm feeling better about it but filing this issue as a placeholder so we can have a conversation about it.

I'm excited to see this!

**Comment by MrAlias** [comment]
Closing, as this sounds to have been addressed in https://github.com/open-telemetry/opentelemetry-go/pull/2587. Please reopen if this is in error.
