### ISSUE TITLE
MeterMust and variants can live in a metricutil package

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-go#1290]
The Must* types and functions are convenience wrappers, we can move them to another package. They make it harder to focus on what are the core types and where the developers start engaging with the metric package.

**Comment by MrAlias** [comment]
Removed Must* types in https://github.com/open-telemetry/opentelemetry-go/pull/2587.

**Comment by ronisec** [comment]
Is there a new home for the Must* types? Trying to figure out how we can update our Otel version which heavily uses the following practice:

```go
// Some code in the codebase

// Globally defined metrics
var (
meter = metric.Must(global.MeterProvider().Meter(instrumentationName))
myCounter = meter.NewInt64Counter("my_metric")
)

// Some code
...
```

**Comment by MrAlias** [comment]
> Is there a new home for the Must* types? Trying to figure out how we can update our Otel version which heavily uses the following practice:
> 
> ```go
> // Some code in the codebase
> 
> // Globally defined metrics
> var (
>    meter = metric.Must(global.MeterProvider().Meter(instrumentationName))
>    myCounter = meter.NewInt64Counter("my_metric")
> )
> 
> // Some code
> ...
> ```
> 
> Ideally we can panic on failure to initialize the metrics at the global level.

You will need to define your own functionality to wrap the creation function with panic logic at this point.
