### ISSUE TITLE
Making aggregators interfaces to support different flavors

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-go#1291]
In the metric package, we provide different flavors of the aggregator types, such as Float64SumObserver 
 vs BoundFloat64UpDownCounter. This is adding some mental overhead for the developer and requiring them to see another type. Instead of exporting various concrete types, would it be better to turn Float64SumObserver into an interface and provide two unexported concrete types?

**Comment by rakyll** [comment]
Or following this model at https://github.com/open-telemetry/opentelemetry-go/issues/1292, we split the bound types into separate packages, so they don't confuse the users.

**Comment by jmacd** [comment]
Either approach sounds good.

**Comment by MrAlias** [comment]
This issues looks to have been resolved by https://github.com/open-telemetry/opentelemetry-go/pull/2587
