### ISSUE TITLE
Split aggregators into different packages

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-go#1292]
The metric package currently is pretty big and hard to begin with. In order to be able to highlight the core types users should be engaging with, can we split aggregation related types into different packages?

For example,

```
package metric

type Meter struct { ... }

func (m Meter) NewInt64Counter(name string, options ...InstrumentOption) (counter.Int64UpDownCounter, error) 
func (m Meter) NewFloat64Counter(name string, options ...InstrumentOption) (counter.Float64UpDownCounter, error) 

...

package counter

type Int64UpDownCounter struct {}
type Float64UpDownCounter struct {}

```

**Comment by rakyll** [comment]
A prototype of this idea is at https://godoc.org/github.com/rakyll/opentelemetry-metric-go. It's a rough idea at this point, we still need to investigate the potential cyclic dependencies and may end up introducing some internal types to get around. I'll give an overview of the idea at the next meeting to discuss whether it's a feasible approach. If yes, I highly suggest us to give it a try. It potentially will cut the initial API surface to 1/10th and will give the users a clear entry point to start with.

**Comment by MrAlias** [comment]
Resolved by https://github.com/open-telemetry/opentelemetry-go/pull/2587
