### ISSUE TITLE
Remove extra label value types

### ISSUE THREAD

**Issue by jtescher** [open-telemetry/opentelemetry-go#1300]
Currently [label value types](https://github.com/open-telemetry/opentelemetry-go/blob/master/label/value.go#L42-L65) can include `INT32`, `UINT32`, `UINT64`, and `FLOAT32` values, but the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/9e6a3de19cb3db983b2e4d56b37ec6313fd4ffc6/specification/common/common.md#attributes) states that:

> An `Attribute` MUST have the following properties:
   ...
   The attribute value, which is either:
        * A primitive type: string, boolean, double precision floating point (IEEE 754-1985) or signed 64 bit integer.
        * An array of primitive type values. The array MUST be homogeneous, i.e. it MUST NOT contain values of different types. 

Should we remove the extra values that are not compliant?

**Comment by MrAlias** [comment]
I like the idea of reducing the API surface area and conforming to the specification. :+1:

**Comment by dstdfx** [comment]
@MrAlias would be glad to take this one
