### ISSUE TITLE
SDK Span locking overused

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#1311]
The [`span.mu` field](https://github.com/open-telemetry/opentelemetry-go/blob/9ac3a08eef14d96687edb260e2c27114a658d6b7/sdk/trace/span.go#L49) is documented to protect the contents of the `span.data` field's value (not pointer). However, it is used to also lock the span when events, links, or attributes are added:

https://github.com/open-telemetry/opentelemetry-go/blob/9ac3a08eef14d96687edb260e2c27114a658d6b7/sdk/trace/span.go#L187-L197

https://github.com/open-telemetry/opentelemetry-go/blob/9ac3a08eef14d96687edb260e2c27114a658d6b7/sdk/trace/span.go#L240-L247

https://github.com/open-telemetry/opentelemetry-go/blob/9ac3a08eef14d96687edb260e2c27114a658d6b7/sdk/trace/span.go#L286-L294

These locking should ideally be improved to not be as contentious among isolated fields and be correctly documented.

**Comment by jmacd** [comment]
I have mixed feelings about this proposal. More locks means larger spans. Have we established that this is needed?

**Comment by dmathieu** [comment]
Based on the comments in #2518, should this issue be closed?
