### ISSUE TITLE
Update Prometheus exporter test to validate monotonic vs. non-monotonic counters

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#1320]
https://github.com/open-telemetry/opentelemetry-go/blob/228bbcbc59276ee1e470a896aa3d027f1e1df27c/exporters/metric/prometheus/prometheus_test.go#L37-L40

_Originally posted by @jmacd in https://github.com/open-telemetry/opentelemetry-go/pull/1269#r514551894_

**Comment by Manimaran11** [comment]
@MrAlias I would like to look into this issue

**Comment by aNickPlx** [comment]
Is this abandoned?
Can I have a go at it?

**Comment by Manimaran11** [comment]
please go ahead.
