### ISSUE TITLE
Update Jaeger exporter to not return BatchSpanProcess shutdown function

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#1327]
https://github.com/open-telemetry/opentelemetry-go/blob/f6df5df9388279ee4627ed9e4999f0b83d09d1a8/exporters/trace/jaeger/jaeger.go#L154

Returning this function stub is not needed anymore given the `TracerProvider.Shutdown` method will call this function on shutdown.

This should be updated to match what the Zipkin package implements, i.e.

```
func NewExportPipeline(endpointOption EndpointOption, opts ...Option) (trace.TracerProvider, error)
```

**Comment by flycash** [comment]
I want to help to do this. From my understanding, I only need to change the return value from `(trace.TracerProvider, func(), error)` to `(trace.TracerProvider, error)`, right?

**Comment by MrAlias** [comment]
> I want to help to do this. From my understanding, I only need to change the return value from `(trace.TracerProvider, func(), error)` to `(trace.TracerProvider, error)`, right?

That is indeed going to be the bulk of the work. The `InstallNewPipeline` will also need to be updated to not return the now unpassed function and there might be tests that need calling structures updated, but should be the bulk of the work AFAIK.

**Comment by flycash** [comment]
Thank you.

**Comment by flycash** [comment]
@MrAlias could you help to review my PR?

**Comment by jcchavezs** [comment]
Any further feedback on this?

**Comment by MrAlias** [comment]
Resolved with https://github.com/open-telemetry/opentelemetry-go/pull/1822
