### ISSUE TITLE
Rename attributesMap.go

### ISSUE THREAD

**Issue by johananl** [open-telemetry/opentelemetry-go#1335]
https://github.com/open-telemetry/opentelemetry-go/blob/63a11144cf5a5fd185e40eba7dd22bce2b2980ef/sdk/trace/attributesMap.go#L1

While AFAIK there isn't a standard convention for naming "regular" (i.e. non-test) source files in Go, we seem to be using `foo_bar.go` throughout the codebase and this specific file seems odd.

We might want to rename this file to `attributes_map.go` or `attributesmap.go`.

**Comment by MrAlias** [comment]
@dstdfx has an open PR for this.
