### ISSUE TITLE
Sampler interface should return Tracestate

### ISSUE THREAD

**Issue by XSAM** [open-telemetry/opentelemetry-go#1341]
According to the [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/8d0d19581caa3e802e6f798fa3e15c1ad5f2e9e2/specification/trace/sdk.md), `Sampler` should return `SamplingResult` that contains `Tracestate`.

**Comment by Aneurysm9** [comment]
Once #1340 lands we'll have `TraceState` in the `SpanContext` provided to the samplers and it should be relatively straightforward to update the `SamplingResult` struct to include a `TraceState`.
