### ISSUE TITLE
Add NewExportPipeline and InstallNewPipeline functions to OTLP exporter

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#1347]
Similar to the other exporters:

* https://github.com/open-telemetry/opentelemetry-go/blob/3d6e8b5078443c822c3800e89bdb84289d82b084/exporters/metric/prometheus/prometheus.go#L90
* https://github.com/open-telemetry/opentelemetry-go/blob/fd3c82bec5fc8012da1fdd0402149b38bd8ec59d/exporters/stdout/exporter.go#L53
* https://github.com/open-telemetry/opentelemetry-go/blob/fd3c82bec5fc8012da1fdd0402149b38bd8ec59d/exporters/trace/jaeger/jaeger.go#L154
* https://github.com/open-telemetry/opentelemetry-go/blob/fd3c82bec5fc8012da1fdd0402149b38bd8ec59d/exporters/trace/zipkin/zipkin.go#L114

add the NewExportPipeline and InstallNewPipeline convince functions.

**Comment by binjip978** [comment]
Hello, i would to help with this issue, looks like https://github.com/open-telemetry/opentelemetry-collector/pull/2159 can be taken as reasonable defaults.

**Comment by MrAlias** [comment]
@binjip978 sorry about the late response, thanks for picking this issue up. I think there might be some differences between what the other exporters do and what that example does. We should try to remain consistent with what the other examples do.

**Comment by eggyhead** [comment]
:wave: looking through the linked code and wanting to understand the intention of this change since all the examples are slightly different. @MrAlias could you possibly summarize the behavior of these methods for `oltp`?
