### ISSUE TITLE
SDK should offer NewMeterProvider similar to NewTracerProvider

### ISSUE THREAD

**Issue by seanschade** [open-telemetry/opentelemetry-go#1362]
It would be nice to unify the SDK. Setting up a `TracerProvider` is very straightforward. The same cannot be said for the `MeterProvider`. 

Current tracer provider:

```
tracerProvider := sdktrace.NewTracerProvider(
	sdktrace.WithConfig(sdktrace.Config{DefaultSampler: cfg.Sampler()}),
	sdktrace.WithResource(resource),
	sdktrace.WithBatcher(exporter),
)
```

Current meter provider:

```
pusher := push.New(
	basic.New(simple.NewWithInexpensiveDistribution(), exporter),
	exporter,
	push.WithResource(resource),
)
meterProvider := pusher.MeterProvider()
```

Proposed meter provider:

```
meterProvider := sdkmeter.NewMeterProvider(
        sdkmeter.WithPusher(push.WithInexpensiveDistribution()),
        sdkmeter.WithResource(resource),
        sdkmeter.WithExporter(exporter),
)
```

I will have some time over the next week to explore this further if there is interest in the idea.

**Comment by MrAlias** [comment]
Will likely relate to https://github.com/open-telemetry/opentelemetry-go/pull/1378

**Comment by MrAlias** [comment]
This issues relates to the current metric SDK. The [metric SDK redesign project](https://github.com/orgs/open-telemetry/projects/22) includes changes to the SDK design that will make this issue obsolete. I'm closing so not wasted work is performed to address this.

FWIW, the new SDK already has this function: https://github.com/open-telemetry/opentelemetry-go/blob/ac0b13fa35d98c220a51a6408fa91053e93674fc/sdk/metric/provider.go#L34-L43
