### ISSUE TITLE
Wrong Stop method called in example

### ISSUE THREAD

**Issue by ocelotl** [open-telemetry/opentelemetry-go#1364]
[This](https://github.com/open-telemetry/opentelemetry-go/blob/master/exporters/otlp/README.md#installation-and-setup) example calls `Stop`:

```
err := exporter.Stop()
```

The OTLP exporter no longer has `Stop` since 422188a85f45411d2db8ab9eb7dcc4044736d502.

**Comment by MrAlias** [comment]
We should prefer using [Go example tests](https://blog.golang.org/examples) to including code blocks in the documentation when we fix this.

**Comment by jonioliveira** [comment]
Hello, I'd love to take this as first contribution.

**Comment by pmalek-sumo** [comment]
This seems to have been fixed in https://github.com/open-telemetry/opentelemetry-go/pull/1441
