### ISSUE TITLE
Using Open Census bridge breaks context propagation

### ISSUE THREAD

**Issue by simonjpartridge** [open-telemetry/opentelemetry-go#1365]
I have a set of gRPC microservices using Opentelemetry. The database is instrumented with OpenCensus so I have tried using the new bridge like so:
```
octrace.DefaultTracer = opencensus.NewTracer(otel.Tracer(""))
```
When I add this line the SQL traces are added as expected but traces stop being propagated between services like they are when not using this bridge.

Without using bridge:

<img width="1596" alt="Screenshot 2020-11-23 at 18 38 12" src="https://user-images.githubusercontent.com/4527871/100001554-3e29e780-2dbb-11eb-9e53-bb7508a79b9d.png">

With bridge:
<img width="1597" alt="Screenshot 2020-11-23 at 18 39 00" src="https://user-images.githubusercontent.com/4527871/100001625-54d03e80-2dbb-11eb-9c32-023c704af8f3.png">

I really can't figure out what the issue could be? Does anyone have any ideas? Thanks :)

**Comment by MrAlias** [comment]
It looks like this might be related to the need for the OpenCensus binary propagation format: https://github.com/open-telemetry/opentelemetry-go-contrib/tree/master/propagators/opencensus

**Comment by simonjpartridge** [comment]
Thanks so much @MrAlias! That was exactly the problem. I added the binary propagator (I had to copy and paste and re-jig some imports to make it work with otel 0.14) and my traces started propagating again :)

**Comment by MrAlias** [comment]
> Thanks so much @MrAlias! That was exactly the problem. I added the binary propagator (I had to copy and paste and re-jig some imports to make it work with otel 0.14) and my traces started propagating again :)

Cool :+1:, glad that helped.
