### ISSUE TITLE
V0.14.0 cannot find otel/api/global package

### ISSUE THREAD

**Issue by weizhang9** [open-telemetry/opentelemetry-go#1366]
Hi, I ran  `go get go.opentelemetry.io/otel/api/global` but failed to get the package
```
go get go.opentelemetry.io/otel/api/global: module go.opentelemetry.io/otel@upgrade found (v0.14.0), but does not contain package go.opentelemetry.io/otel/api/global
```.

Looking at the repo, I couldn't find the directory under v0.14.0 either. Has this package been removed or moved to a new module? Thanks!

**Comment by krnowak** [comment]
Yes, the contents of the `api/global` package have been moved to toplevel package, so they are at `go.opentelemetry.io/otel` now.

**Comment by MrAlias** [comment]
As @krnowak pointed out, this package has moved. Please take a look a the release notes associated with the release of this version to find info on this and all the other changes included in the release: https://github.com/open-telemetry/opentelemetry-go/releases/tag/v0.14.0
