### ISSUE TITLE
Update span status & description setting to comply with the spec

### ISSUE THREAD

**Issue by matej-g** [open-telemetry/opentelemetry-go#1376]
### Related PRs (merged ones ticked off)
- \[X] Jaeger Exporter: Fix minor mapping discrepancies #1626
- \[ ] Zipkin Exporter: Adjust span transformation to comply with the spec #1688
- \[X] Span status from HTTP code: Do not set status message if it can be inferred #1681
---

According to recent spec change in  https://github.com/open-telemetry/opentelemetry-specification/pull/1186 and 
https://github.com/open-telemetry/opentelemetry-specification/pull/1257:

#### _Regarding exporters_

For Jaeger status code and message (excerpts):

> Span `Status` MUST be reported as a key-value pair in `tags` to Jaeger, unless it is `UNSET`.
> In the latter case it MUST NOT be reported.

> |Code | `otel.status_code` | Name of the code, either `OK` or `ERROR`. MUST NOT be set if the code is `UNSET`. |
> |Description | `otel.status_description` | Description of the `Status` if it has a value otherwise not set. |

For Zipkin status code and description (excerpts):

> |Description| `error` | Description of the `Status`. MUST be set if the code is `ERROR`, use an empty string if Description has no value. MUST NOT be set for `OK` and `UNSET` codes. |

#### _Regarding status from HTTP status code (open question)_

Furthermore, the spec now states that:
> `Description` MUST be IGNORED for `StatusCode` `Ok` & `Unset` values.

and in [HTTP semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#status) spec:

> Don't set the span status description if the reason can be inferred from `http.status_code`.

Generally this seems to be the case, however `SpanStatusFromHTTPStatusCode`, which  - although not returning directly span status with description - is returning accompanying message for all statuses. The question is whether this acceptable (and the burden of checking and (not) setting span status is on the caller of `SpanStatusFromHTTPStatusCode`) or this could be simplified to return empty string for success statuses.

**Comment by matej-g** [comment]
@MrAlias I updated the description as there was another related change to the spec (see the update description), I think it makes sense to tackle it all in one go. I hope the update is OK, not sure whether it changes priority etc.

Also happy to pick up this issue :arrow_up:

**Comment by matej-g** [comment]
Hello @MrAlias! I've been looking into this and I think there are even more (although mostly minor) discrepancies between the exporters and the spec, since I opened this. I think I will split the changes into separate PRs, one for exporter, for better review process, just FYI.

**Comment by MrAlias** [comment]
@matej-g sounds good :+1:

**Comment by MrAlias** [comment]
Adding the following tasks to this to be explicit for what we need in the Jaeger exporter:

- [ ] The status code tag needs to be renamed from `"status.code"` to `"otel.status_code"`
- [ ] The status description tag needs to be renamed from `"status.message"` to `"otel.status_description"`
- [ ] The status description tag needs to not be set if the status message is not set.
- [ ] No `"error"` tag should be set if the status code is `Error`.

**Comment by MrAlias** [comment]
Addressing that last comment in #1761
