### ISSUE TITLE
Tracer configurations: how to set Export() timeout?

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-go#1386]
I haven't found any way to configure an export timeout for an OTLP ExportSpans() method. I believe this should be configurable for users.

#1378 refactors the way this setting works in the Metrics SDK. I believe such a configuration should be independent of the trace exporter--probably it belongs in the Span Batcher?

**Comment by MrAlias** [comment]
We can update to support a context timeout from the first arg. We will just need to set the timeout.

This can be done post-GA.

**Comment by MrAlias** [comment]
Resolved in https://github.com/open-telemetry/opentelemetry-go/pull/1755

That adds an `ExportTimeout` option to the `BatchSpanProcessor`. Both the HTTP and gRCP protocol drivers for the OTLP honor the timeout of the passed context: https://github.com/open-telemetry/opentelemetry-go/issues/1613#issuecomment-805297026

**Comment by jmacd** [comment]
😀 Thank you!
