### ISSUE TITLE
Metrics Accumulator split proposal

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-go#1387]
Right now the Accumulator has a global map (InstrumentDescriptor + LabelSet) -> Record. This has an advantage of simpler code, but with this approach there is a chance of high contention on the global map.

The proposal is to split Accumulator into 2 parts:

Accumulator: global map InstrumentDescriptor -> InstrumentAccumulator
InstrumentAccumulator: local to the instrument map between LabelSet -> Record

This way we can reduce contention on the global map when non-bound records are recorded.

**Comment by jmacd** [comment]
This will be important before we can vary the collection interval on a per-instrument basis. OTOH doesn't feel urgent to me.

**Comment by MrAlias** [comment]
Marking as after GA. Please update if this is incorrect.

**Comment by MrAlias** [comment]
Stale, closing.
