### ISSUE TITLE
Remove StartCollection and FinishCollection from Checkpointer

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-go#1389]
These funcs are always called before and after a `Accumulator.Collect(ctx)` also only the `basic` package implements it. So the logic that is currently implemented in the `basic` package can be moved to the Accumulator.Collect and remove the extra interfaces.

**Comment by jmacd** [comment]
We haven't decided if an exporter is allowed to consume outputs from multiple accumulators. These functions are needed to support multiple accumulators, which I think is a nice-to-have b/c it supports variable resources.

**Comment by MrAlias** [comment]
This issues relates to the current metric SDK. The [metric SDK redesign project](https://github.com/orgs/open-telemetry/projects/22) includes changes to the SDK design that will make this issue obsolete. I'm closing so no wasted work is performed to address this.
