### ISSUE TITLE
trace.ChildOf(spanCtx) in examples hallucinates a parentId on root spans

### ISSUE THREAD

**Issue by lizthegrey** [open-telemetry/opentelemetry-go#140]
rather than ParentID being left unset on the root span of the trace, a random value for ParentID is being manufactured when the following code is run inside a vanilla HTTP handler ripped from the example code:

```
func rootHandler(w http.ResponseWriter, req *http.Request) {
	attrs, tags, spanCtx := httptrace.Extract(req.Context(), req)

	req = req.WithContext(tag.WithMap(req.Context(), tag.NewMap(tag.MapUpdate{
		MultiKV: tags,
	})))

	ctx, span := tracer.Start(
		req.Context(),
		"root",
		trace.WithAttributes(attrs...),
		trace.ChildOf(spanCtx),
	)
	defer span.Finish()

	span.AddEvent(ctx, "annotation within span")
	_ = dbHandler(ctx, "foo")

	fmt.Fprintf(w, "Click [Tools] > [Logs] to see spans!")
}
```

**Comment by lizthegrey** [comment]
Pebkac. Turns out Glitch really was adding those trace context headers!

**Comment by akvanhar** [comment]
I investigated this further and it turns out that Glitch is inserting a W3C header, which we're pulling out by accident here, but it wasn't sent, so it's showing up as an empty parent span.
We have some hardening to do on our side of things.
