### ISSUE TITLE
Improve defaulting for propagation

### ISSUE THREAD

**Issue by dashpole** [open-telemetry/opentelemetry-go#1404]
Related to https://github.com/open-telemetry/opentelemetry-go/issues/1391

Currently, installing an SDK and plugins, such as otelhttp does not install any propagators.  I encountered this in my personal experience trying to instrument a web service, and force sampling by sending a sampled trace context.  I couldn't figure out why it wasn't working, and it took me a day of debugging to realize I needed to install a propagator.  It is difficult to debug when this doesn't work.  A user from gitter also ran into this problem, and this issue is based on a discussion there.

However, we can't set a default in the API: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/context/api-propagators.md#global-propagators
`The OpenTelemetry API MUST use no-op propagators unless explicitly configured otherwise.`

We could try and set the global propagator in `NewTracerProvider`, but that would have undesired behavior when using multiple TracerProviders, and might cause confusion if used in conjunction with `SetTextMapPropagator()`, since the default could clobber the user-set one.  We could also do it in `InstallNewPipeline` for various export pipelines.  This is probably better, since it also sets the global TracerProvider.

cc @MrAlias @jmacd @Aneurysm9

**Comment by dashpole** [comment]
also related: open-telemetry/opentelemetry-go#1265

**Comment by MrAlias** [comment]
Likely going to be related to this part of the SDK specificationhttps://github.com/open-telemetry/opentelemetry-specification/blob/f2869a369ff4b93024e3437837320da76d2c0637/specification/sdk-environment-variables.md#general-sdk-configuration

> ## General SDK Configuration
> 
> | Name                     | Description                                       | Default                           | Notes                               |
> | ------------------------ | ------------------------------------------------- | --------------------------------- | ----------------------------------- |
> | OTEL_PROPAGATORS         | Propagators to be used as a comma separated list  | "tracecontext,baggage"            | Values MUST be deduplicated in order to register a `Propagator` only once. Unrecognized values MUST generate a warning and be gracefully ignored. |

**Comment by Aneurysm9** [comment]
> Likely going to be related to [this part of the SDK specification](https://github.com/open-telemetry/opentelemetry-specification/blob/f2869a369ff4b93024e3437837320da76d2c0637/specification/sdk-environment-variables.md#general-sdk-configuration)
> 
> > ## General SDK Configuration
> > 
> > 
> > 
> > Name
> > Description
> > Default
> > Notes
> > 
> > 
> > 
> > 
> > OTEL_PROPAGATORS
> > Propagators to be used as a comma separated list
> > "tracecontext,baggage"
> > Values MUST be deduplicated in order to register a `Propagator` only once. Unrecognized values MUST generate a warning and be gracefully ignored.

> Additional values can be specified in the respective SDK's documentation, in case third party Propagators are supported, such as "xray" or "ottracer".

That sounds like we'd need to provide a registration mechanism for third-party propagators.

**Comment by MrAlias** [comment]
Can this be closed in favor of recommending https://pkg.go.dev/go.opentelemetry.io/contrib/propagators/autoprop @dashpole ?

**Comment by dashpole** [comment]
yes, definitely.
