### ISSUE TITLE
otel.Tracer(...) concurrent usage

### ISSUE THREAD

**Issue by schmurfy** [open-telemetry/opentelemetry-go#1408]
Sorry that is not an issue but I cannot find the answer and don't know where to ask: can the tracer object returned by `otel.Tracer("xxx")` be used in multiple goroutines or should I create it again when I need it ?

I did not found any clear documentation on this and I found conflicting examples where some declare a global variable with the tracer and reuse it and some call `otel.Tracer` each time they need to create a span.

**Comment by schmurfy** [comment]
should I be worried that nobody seems to know ?
From what I gathered the real method called underneath is dependant on each exporter implementation but is there some guidelines ?

**Comment by MrAlias** [comment]
The Tracer is safe for concurrent use is you use the default SDK provided by this project.
