### ISSUE TITLE
Consider moving github.com/DataDog/sketches-go to 1.0.0

### ISSUE THREAD

**Issue by eclipseo** [open-telemetry/opentelemetry-go#1417]
Hi,

I'd like to package open-telemetry for my distro, but we have system-wide github.com/DataDog/sketches-go at version 1.0.0. It has API breaking changes from 0.0.1. Could you consider updating the code to work with 1.0.0?

Thanks.

**Comment by krnowak** [comment]
There is a PR that drops the dependency on DDSketch: #1412

**Comment by jmacd** [comment]
FYI we plan on re-introducing this dependency. Some restructuring is needed in the OTel-Go SDK before we can get there, and we won't really be ready to use DDSketches in OTel-Go until https://github.com/open-telemetry/opentelemetry-proto/pull/226 merges. Thanks.
