### ISSUE TITLE
Move metric SDK processor, controller, aggregator-selector packages up one level

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-go#1419]
The packages `sdk/metric/processor/basic`,  `sdk/metric/controller/basic`, and  `sdk/metric/selector/simple`
 can all move up one level. This will improve readability.

See this comment: https://github.com/open-telemetry/opentelemetry-go/pull/1378#discussion_r537634831

**Comment by MrAlias** [comment]
This issues relates to the current metric SDK. The [metric SDK redesign project](https://github.com/orgs/open-telemetry/projects/22) includes changes to the SDK design that will make this issue obsolete. I'm closing so no wasted work is performed to address this.
