### ISSUE TITLE
Why we don’t have a file exporter?

### ISSUE THREAD

**Issue by govine** [open-telemetry/opentelemetry-go#1442]
We all know that the memory buffer is limited, and the port-based exporter will cause longer I/O blocking, and may have to have a retry mechanism.
Using file expoter and a collection mechanism similar to filebeat can solve this type of problem.

**Comment by MrAlias** [comment]
The stdout exporter [can be configured](https://github.com/open-telemetry/opentelemetry-go/blob/5ed96e92446d2d58d131e0672da613a84c16af7a/exporters/stdout/config.go#L37-L38) to write to whatever io.Writer you would like, including a file. Hopefully this helps.

**Comment by govine** [comment]
> The stdout exporter [can be configured](https://github.com/open-telemetry/opentelemetry-go/blob/5ed96e92446d2d58d131e0672da613a84c16af7a/exporters/stdout/config.go#L37-L38) to write to whatever io.Writer you would like, including a file. Hopefully this helps.

Oh, Thanks!
