### ISSUE TITLE
Module version policy compliance and release tooling improvement

### ISSUE THREAD

**Issue by Aneurysm9** [open-telemetry/opentelemetry-go#1446]
In order to support our [versioning policy](https://github.com/open-telemetry/opentelemetry-go/blob/master/VERSIONING.md), specifically the requirement that experimental modules are versioned independently from stable modules, we need to make some improvements to our [release process](https://github.com/open-telemetry/opentelemetry-go/blob/master/RELEASING.md) and [tooling](https://github.com/open-telemetry/opentelemetry-go/blob/master/tag.sh).  

The following capabilities would be helpful for maintainers as they prepare releases and should be present in the tooling:

* Declaring sets of modules that must maintain consistent versions.
  * Ensuring that no more than one set of modules exists for any given `major` version.
  * Promoting a module (and its dependencies, if in this repository) from `experimental` to `stable`.
  * Validating that no dependencies on any `experimental` module exist in `stable` modules.
* Incrementing the (`major`|`minor`|`patch`) version component of all modules in a set of modules.
  * This should reset the `patch` component to `0` if the `minor` component is incremented and the `minor` and `patch` components to `0` if the major component is incremented.
  * Specifying [pre-release version identifiers](https://semver.org/#spec-item-9), if required.
  * Git tags for the incremented version identifier should be created for each module.

**Comment by punya** [comment]
According to the versioning policy,

> All stable modules that use the same major version number will use the same entire version number.

Is it possible for two stable modules to have distinct major versions in the same Git commit? I.e. could we have metrics/v2 and trace/v3 at the same time?

**Comment by punya** [comment]
Related to my previous question, let's suppose we're in a situation where stable modules are all v2 (specifically, v2.3.0), and one experimental module is v0 (specifically v0.18.0). When the experimental module is promoted to stable, should it become:
* v1.0.0 -- the natural next version given that it was v0.18.0, and because there is no other v1.x module in this commit
* v1.8.0 -- because v1.7.0 was previously published from some stable module in this repository, even though it's no longer present in this commit
* v2.4.0 -- and bump all the existing v2.3.0 stable modules as well, skipping v1.x for the newly promoted module

**Comment by dashpole** [comment]
> Is it possible for two stable modules to have distinct major versions in the same Git commit? I.e. could we have metrics/v2 and trace/v3 at the same time?

Yes, I believe it is.

The second question is a good one.  The policy just states:

> All stable modules that use the same major version number will use the same entire version number.

It probably shouldn't be a v2.*, since there isn't a requirement stated anywhere for stable major versions to match.  I think both of the v1.8.0 versions would be in compliance with the stated policy, but v1.0.0 probably would cause the least surprise for users, and be easiest to implement for you

**Comment by punya** [comment]
v1.0.0 would certainly be easy to implement. However, for a module consumer, it would be confusing to see that this new module’s v1.0.0 is unrelated to and incompatible with all the existing v1.0.0 releases.

**Comment by Aneurysm9** [comment]
> v1.0.0 would certainly be easy to implement. However, for a module consumer, it would be confusing to see that this new module’s v1.0.0 is unrelated to and incompatible with all the existing v1.0.0 releases.

Yeah, that would definitely be likely to cause some surprise.  I think for that reason it would be best to go directly from `v0.x.x` to `v2.x.x`.  Perhaps the versioning policy document could use an update to clarify, but I would expect that experimental modules would be developed against the latest stable version of their dependencies and would be promoted to the same major version as their stable dependencies.

**Comment by dashpole** [comment]
> Perhaps the versioning policy document could use an update to clarify, but I would expect that experimental modules would be developed against the latest stable version of their dependencies and would be promoted to the same major version as their stable dependencies.

Just to make sure I understand, are you saying that all stable modules always have the same version, or just that when a module is promoted it advances to where another stable module is?  If we want to make a breaking change in a stable module, does that require bumping all major versions in the repo, or just the module with the breaking change?

**Comment by punya** [comment]
Are we planning to use the [major branch or the major subdirectory strategy for releasing v2 and higher versions](https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher)? As a related question, should the tooling support patching historical stable versions?

**Comment by Aneurysm9** [comment]
> Just to make sure I understand, are you saying that all stable modules always have the same version, or just that when a module is promoted it advances to where another stable module is? 

Certainly the latter, though I'm not sure about the former.   I think an element of the intent behind versioning modules in lockstep is to ensure that users can have a reasonable understanding about what version of the API and/or SDK they are using without worrying too much about the details of the individual modules.

As a thought exercise, presume we've split the API and SDK into two sets of modules and make a BC-breaking change to the API that somehow doesn't require a similarly breaking change to the SDK.  What are our options?  

* We could increment the API to v2 and leave the SDK at v1.  
  * In this case if we do not update the SDK to use API v2 we have no SDK using API v2.
  * If we do update the SDK to use API v2 while leaving it at v1 then all users of the SDK at that point must start using API v2?  Isn't that just a slightly-removed breaking change?
* We could increment both the API and SDK to v2.
  * The scope of change is clearer for consumers, both the API and SDK must be updated simultaneously.
  * We need to work through how to handle multiple API/SDK major versions existing concurrently.
* Something else?

> If we want to make a breaking change in a stable module, does that require bumping all major versions in the repo, or just the module with the breaking change?

I think the expectation, based on [OTEP-143](https://github.com/open-telemetry/oteps/blob/master/text/0143-versioning-and-stability.md#version-numbers), is that all modules in the API are versioned together and all modules in the SDK are versioned together.  I think it remains to be seen whether we can effectively increment the major version of the API without also making changes to the SDK that would require a major version increment, but the minimum unit of change would be the set of modules that comprise the API or SDK.  

> Are we planning to use the major branch or the major subdirectory strategy for releasing v2 and higher versions? 

I believe the plan is to use the major subdirectory strategy for v2 and higher module versions.

> As a related question, should the tooling support patching historical stable versions?

Yes, I think this will be required as we will need the ability to provide security and stability support for prior major versions of modules for some as-yet-undetermined period.

**Comment by punya** [comment]
> As a thought exercise, presume we've split the API and SDK into two sets of modules and make a BC-breaking change to the API that somehow doesn't require a similarly breaking change to the SDK. What are our options?

A third option (and my personal preference) is to have the SDK support *both* v1 and v2 of the API simultaneously. This would allow users to migrate smoothly from API v1 to API v2 at their preferred pace. We'd only upgrade SDK to v2 when we *drop* support for API v1.

**Comment by punya** [comment]
@Aneurysm9 I wonder if it would be more productive to create the tooling after we factor the modules by signal (at least in draft form). That will help us to more clearly see which modules would go into which "consistent version set".

**Comment by eddyleelin** [comment]
I'm working on this now @alolita.
