### ISSUE TITLE
Add more test cases to Jaeger Exporter

### ISSUE THREAD

**Issue by rghetia** [open-telemetry/opentelemetry-go#145]
see this [comment](https://github.com/open-telemetry/opentelemetry-go/pull/143#discussion_r328368123) 

Also fix this [comment](https://github.com/open-telemetry/opentelemetry-go/pull/143#discussion_r328367696)

**Comment by eran-levy** [comment]
@rghetia its still work in progress, Im trying to think what will be a good way to test the exporter, will be happy if you can take a look and share your thoughts or maybe ref me to something similar to look at - will it be enough to create span and validate the spancontext?
