### ISSUE TITLE
Jaeger exporter should use functional options

### ISSUE THREAD

**Issue by iredelmeier** [open-telemetry/opentelemetry-go#146]
Functional options would be more consistent with the rest of the code base.

Additionally, it would let us make certain configuration more clear, e.g., enabling a single `endpoint` option that would let you use _either_ a collector endpoint _or_ an agent endpoint.

**Comment by sayboras** [comment]
I can start working on this :)

**Comment by paivagustavo** [comment]
Hey @sayboras, I was already working on this but didn't mention before. Please, forgive me :(

**Comment by sayboras** [comment]
no worry, I find sometime else to work on
