### ISSUE TITLE
Organize API into Go modules based on stability and dependencies

### ISSUE THREAD

**Issue by punya** [open-telemetry/opentelemetry-go#1467]
In order to release a stable v1.0 of the Trace API and SDK without forcing the same stability on work that is still experimental (e.g. Metrics), we need to separate the Trace API into an independent Go module. While performing this separation, we must respect the following constraints:
~1. Stable modules must not depend on unstable modules.~
2. The global API must be a stable module.
~3. There must not be cyclic dependencies between modules (not just between packages).~

**Comment by MrAlias** [comment]
Related to #1446

**Comment by punya** [comment]
Here is a sequence of package refactors (moves, renames, splits) that accomplishes this goal:

```
	i.movePackage("./codes", "./semconv/codes")
	i.movePackage("./label", "./semconv/label")
	i.duplicateDependency("./semconv/label", "./internal", "./semconv/internal")
	i.createModule("./semconv")
	i.stabilize("./semconv")

	i.createModule("./trace")
	i.stabilize("./trace")

	i.duplicateDependency("./propagation", "./internal/baggage", "./propagation/internal/baggage")
	i.createModule("./propagation")
	i.stabilize("./propagation")

	i.duplicateDependency("./baggage", "./internal/baggage", "./baggage/internal")
	i.createModule("./baggage")
	i.stabilize("./baggage")

	i.duplicateDependency("./metric/number", "./internal", "./metric/internal")
	i.movePackage("./unit", "./metric/unit")
	i.createModule("./metric")

	i.createPackage("./errors") // split from .
	i.replaceDependency("./internal/metric", ".", "./errors")
	i.createModule("./errors")
	i.stabilize("./errors")

	i.removeDependency(".", "./metric")
	i.removeDependency("./internal/global", "./metric")
	i.removeDependency("./internal/global", "./metric/number")
	i.removeDependency("./internal/global", "./metric/registry")
	i.duplicateDependency("./sdk/metric", "./internal/metric", "./sdk/internal/metric")
	i.movePackage("./internal/metric", "./oteltest/internal/metric")

	i.createModule("./oteltest")
	i.stabilize(".")
```

**Comment by punya** [comment]
Today I learned that Go modules can have cyclic dependencies (https://github.com/golang/go/issues/24098), so I'm going to see if this can be solved much more simply with fewer (perhaps no) changes to the package structure.

**Comment by punya** [comment]
# Goals
1. Identify the parts of opentelemetry-go that need to have a stable public API as part of releasing the Trace release.
2. For each package, determine if it can be declared stable (put into a v1.x module), declared unstable (put into a v0.x module), or needs to be split.
3. Minimize disruption to existing pull requests and pull requests.
4. Minimize future disruption to code when we stabilize packages.

# Non-goals
1. Keeping metrics-related code out of v1.0 packages. It’s ok for v1.0 package to have metrics code in an internal/ sub-package where it can be exposed by a v0.x package located at the right place in the hierarchy.
2. Avoiding cyclic module dependencies.

# Proposal
1. Create modules at otel/metric, otel/oteltest, otel/sdk/export/metric, otel/sdk/metric (lots of cyclic dependencies).
2. Move GetMeterProvider, Meter and SetMeterProvider from otel to otel/metric.
3. Mark otel, otel/trace, otel/sdk as v1.0.

---

@Aneurysm9 @MrAlias @rakyll I would appreciate all of your feedback on this approach.
