### ISSUE TITLE
Update regular expression for traceStateKeyFormatWithMultiTenantVendor

### ISSUE THREAD

**Issue by YuriiBarninets** [open-telemetry/opentelemetry-go#1475]
The regular expression for tracestate key format with multi-tenant vendor does not match W3C TraceContext specification.

TraceContext specification:
[https://www.w3.org/TR/trace-context-1/#key](https://www.w3.org/TR/trace-context-1/#key)

TraceContext specification allows digits to be placed at the beginning of tracestate key for multi-tenant vendor scenarios, however the current regular expression in Go OpenTelemetry prohibits it:

> [traceStateKeyFormatWithMultiTenantVendor = `[a-z][_0-9a-z\-\*\/]{0,240}@[a-z][_0-9a-z\-\*\/]{0,13}`](https://github.com/open-telemetry/opentelemetry-go/blob/master/trace/trace.go#L51)

As a result, the following key will be reinterpreted as the wrong one:

> 968a934b-980df25b@dt

**Comment by MrAlias** [comment]
There is some ambiguity with the start character of the key as described in [this issue](https://github.com/w3c/trace-context/issues/441). I think we should update to match what is there as this issues describes, but it should be understood that things might change in the future.

**Comment by MrAlias** [comment]
Looking into addressing this and adding tests, we should at a minimum test for the same data set that the W3C project does: https://github.com/w3c/trace-context/blob/master/test/test_data.json
