### ISSUE TITLE
Should `Tracer#WithSpan` take options?

### ISSUE THREAD

**Issue by iredelmeier** [open-telemetry/opentelemetry-go#149]

**Comment by jmacd** [comment]
I support the idea in principle, but it feels like it clutters the API too, because you'll have to write a `[]pkg.Option{}` boilerplate to use this. I'd probably rather see calls like

```
return trace.WithSpan(ctx, trace.SpanName("abc").More(...).Optionals(...).Here(...), func(ctx) error {
    ...
})
```

**Comment by freeformz** [comment]
@jmacd You don't have to create a slice to pass var args. WithSpan could be:

```go
    WithSpan(
        ctx context.Context,
        operation string,
        body func(ctx context.Context) error,
        opts ...Option,
    ) error
```

**Comment by freeformz** [comment]
This would also make it symmetric to [NewHandler](https://godoc.org/go.opentelemetry.io/plugin/othttp#NewHandler) and the like.

**Comment by jmacd** [comment]
I think placing the variable length args after the function destroys
readability.

**Comment by freeformz** [comment]
@jmacd On that we disagree. I find it more readable and not that different really, than your example above: 

```go
return trace.WithSpan(ctx, trace.WithName("abc"), trace.WithMore(...), trace.WithHere(...))

```

**Comment by freeformz** [comment]
It's not *great*, but IMO, it is better than the odd chaining thing.

```go
return trace.WithSpan(ctx,"op",
  func(c context.Context) error {
    ...
  },
  trace.WithMore(...),trace.WithHere(...),
)
```

Additionally, adding the variable options at the end is compatible with the existing signature.

**Comment by jmacd** [comment]
It's not bad, I agree. I support this.

It's a bit of a "buried lede", where potentially most important information is a distance away from the start of the statement. I'd accompany this with a recommendation to avoid lengthy in-line `func` definitions when options are present.

**Comment by paivagustavo** [comment]
Just throwing another idea, what if we change this a little bit and do something like:
```go
return trace.WithSpan(ctx,"op", trace.WithMore(...),trace.WithHere(...))
	.Do(func(c context.Context) error {
			...
	})
```

**Comment by freeformz** [comment]
I like that.

**Comment by jmacd** [comment]
What happens if `.Do(...)` is left off, what type is returned by `WithSpan`?

**Comment by paivagustavo** [comment]
Having a hard time thinking of a good naming for the intermediate type returned by`WithSpan`.

I have been thinking about the experience of using the API, would be possible to change add a `.Do(...)` method to the `Span` type? With this possible could drop `WithSpan` altogether (specs doesn't actually forces us to have it, or did I missed it?).
  
`trace.StartSpan(ctx, "name", ...).Do(...)` seems a very natural way of using the API. 

I don't know if this is a change that may needs to go to specs?

**Comment by paivagustavo** [comment]
I think that maybe `SpanScope` maybe a good start name if are going to keep this structure. 

We could create the span when the `Do` method is called, so if one does not call `Do`, nothing happens.

**Comment by freeformz** [comment]
That is one problem with chaining in that way. As for a type name: `SpanDoer` (an interface), `SpanFuture`, `SpanScope`, etc. 

Given that `.Do` may require another type I'd prefer the inline func, with trailing ...opts.

**Comment by iredelmeier** [comment]
Any more thoughts on this? It seems like the trailing varargs is most straightforward.

**Comment by jmacd** [comment]
🤷‍♂ Sure!

**Comment by jmacd** [comment]
Let's go with trailing varargs.
