### ISSUE TITLE
Memory leak issue with Open Telemetry and jaeger exporter

### ISSUE THREAD

**Issue by varun06** [open-telemetry/opentelemetry-go#1490]
We are using Open Telemetry in a reverse Proxy at scale and seeing memory leak. 

```
func InitTracing(serviceName string, collectorEndpoint string, sample float64) (func(), error) {
	tc := propagation.TraceContext{}
	// Register the TraceContext propagator globally.
	otel.SetTextMapPropagator(tc)

	// Create and install Jaeger export pipeline.
	return jaeger.InstallNewPipeline(
		jaeger.WithCollectorEndpoint(collectorEndpoint),
		jaeger.WithProcess(jaeger.Process{
			ServiceName: serviceName,
			Tags: []label.KeyValue{
				label.String("exporter", "jaeger"),
			},
		}),
		jaeger.WithSDK(&sdktrace.Config{DefaultSampler: sdktrace.TraceIDRatioBased(sample)}),
	)
}
```
This is how I am initiating tracer.

```
	if cfg.TracingEnabled {
		// Initialize tracing and set global tracer
		flush, err := tracing.InitTracing("odnd", cfg.TracingCollectorEndpoint, cfg.TracingSampleValue)
		if err != nil {
			proxyLogger.Error("Failed to initialize tracing collector", logger.Error(err))
		}
		if flush != nil {
			defer flush()
		}
	}
```

This is how it is used to create a global tracer.

```
	tc := otel.GetTextMapPropagator()
	ctx := tc.Extract(originalReq.Context(), originalReq.Header)

	tracer := otel.Tracer(tracing.TracerName)

	tracingCtx, span := tracer.Start(ctx, "serveHTTP", trace.WithSpanKind(trace.SpanKindServer))
	originalReq = originalReq.WithContext(tracingCtx)
	defer span.End()
```

That's how we are creating a span and then few more child spans are created. But we are seeing this 

<img width="297" alt="Screen Shot 2021-01-25 at 9 48 25 AM" src="https://user-images.githubusercontent.com/1284070/105729693-19550c00-5ef3-11eb-8a8d-3aa422a26f98.png">

It goes up as we add more spans and off course that impacts GC and CPU usage on node. Can someone please have a look and let me know if i am doing something wrong in code or it's related to lib??

**Comment by MrAlias** [comment]
Thanks for the bug report. Have you been able to see the error while running with a profiler?

Also, when you defer the end of the span, does that function ever return?

**Comment by varun06** [comment]
Hey @MrAlias 

It seems that problem was calling GetTracer every time we were creating a new Span(Bug). But I was wondering, shouldn't GetTracer be a Singleton??

**Comment by MrAlias** [comment]
> Hey @MrAlias
> 
> It seems that problem was calling GetTracer every time we were creating a new Span(Bug). But I was wondering, shouldn't GetTracer be a Singleton??

Thanks for looking into this. The Tracer returned from `GetTracer` should indeed be a reference to the same Tracer value if it is named the same. Do you have evidence this is not happening? That definitely sounds like a bug if so.

**Comment by varun06** [comment]
I have lost the pprof that shows something like that, but i can share problematic code that was creating this problem.

```
func AddSpanToRequest(req *http.Request, spanName string) (*http.Request, trace.Span) {
 	var (
 		span               trace.Span
 		reqCtx, tracingCtx context.Context
 		ok                 bool
 	)

 	if req == nil {
 		return nil, nil
 	}

 	reqCtx = req.Context()
 	val := reqCtx.Value(ContextKey)
 	if tracingCtx, ok = val.(context.Context); !ok {
 		tracingCtx = context.Background()
 	}

 	tracer := global.Tracer(TracerName)
 	tracingCtx, span = tracer.Start(tracingCtx, spanName)
 	req = req.WithContext(context.WithValue(reqCtx, ContextKey, tracingCtx))
 	return req, span
}
```

and it was getting called every time someone created a new span. When i profiled, i remember seeing multiple tracer.

**Comment by brancz** [comment]
We are experiencing the exact same problem. We continuously profile our entire infrastructure, so we have profiling data available for everything. Let us know what would be useful to you! :)

Process start: https://share.polarsignals.com/7aef522/
Right before OOM: https://share.polarsignals.com/5bf8ce4/
Diff of the two profiles: https://share.polarsignals.com/8945fcd/

This data also highly suggests something within the global tracer to be leaking. Let me know what I can try or provide further that would be helpful!

**Comment by varun06** [comment]
@brancz Thanks for chiming in. I see nothing with those links. But yeah, we had same behavior. If I get some time this week, will try to read some code and see if I can find out, I am also planning to replicate this situation in a test env and see what is causing this.

**Comment by danp** [comment]
It's entirely possible I'm missing context, and apologies in advance if so! But looking at the profiles @brancz shared it gets me wondering when things added to p.tracers here would be removed:

https://github.com/open-telemetry/opentelemetry-go/blob/e499ca86b7ef54b42f6dd684ccbf73f226af10bd/internal/global/trace.go#L90-L91

If, for example, the grpc UnaryClientInterceptor is calling Tracer like so for every request:

https://github.com/open-telemetry/opentelemetry-go-contrib/blob/1c687598a61840d67e56c9c7707af4997e1a057b/instrumentation/google.golang.org/grpc/otelgrpc/interceptor.go#L81-L84

When would its associated tracer in p.tracers be removed?

**Comment by michelaquino** [comment]
Hi @bogdandrutu 
do you have a forecast to release this fix?

**Comment by MrAlias** [comment]
@michelaquino we are hoping to make a release by the end of the week that will contain this fix. Please reach out to us in the CNCF [otel-go slack channel](https://cloud-native.slack.com/archives/C01NPAXACKT) if you have any more questions about the release.

**Comment by ogulcanarbc** [comment]
I think also experiencing the same memory leak problem from the code block below. can you suggest the correct implementation to solve this problem?

```
func wrappedRoundTripFunc(rt req.RoundTripper) req.RoundTripFunc {
	return func(req *req.Request) (resp *req.Response, err error) {
		ctx := req.Context()

		apiName, ok := ctx.Value(apiNameKey).(string)
		if !ok {
			apiName = req.URL.Path
		}

		tracer := otel.GetTracerProvider().Tracer(apiName)
		_, span := tracer.Start(ctx, apiName)
		defer span.End()

		req.SetHeaders(map[string]string{
			b3.SampledHeader: castutil.BoolToBitString(span.SpanContext().IsSampled()),
			b3.TraceIDHeader: span.SpanContext().TraceID().String(),
			b3.SpanIDHeader:  span.SpanContext().SpanID().String(),
		})

		span.SetAttributes(
			attribute.String("http.url", req.URL.String()),
			attribute.String("http.method", req.Method),
			attribute.String("http.req.header", req.HeaderToString()),
		)

		if len(req.Body) > 0 {
			span.SetAttributes(
				attribute.String("http.req.body", string(req.Body)),
			)
		}

		resp, err = rt.RoundTrip(req)

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}

		if resp.Response != nil {
			span.SetAttributes(
				attribute.Int("http.status_code", resp.StatusCode),
				attribute.String("http.resp.header", resp.HeaderToString()),
				attribute.String("http.resp.body", resp.String()),
			)
		}

		return resp, err
	}
}
```

<img width="693" alt="Image" src="https://github.com/user-attachments/assets/3948c064-5475-4fab-a497-4a5f9fce7459" />
