### ISSUE TITLE
Rename default branch to main

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/opentelemetry-go#1496]
I apologize if there is already an open issue for this. I searched and did not find one. This should be done in this repo as well as https://github.com/open-telemetry/opentelemetry-go-contrib.

For more information see https://github.com/open-telemetry/community/issues/402

**Comment by MrAlias** [comment]
https://docs.google.com/document/d/1lkA0Re3vWfqXmuYLhL93Y6ABR27Sg6DzPcwi4kPXj0Y/edit

**Comment by MrAlias** [comment]
Both this repo and the contrib repo `master` branches have been renamed to `main`. Still cleaning things up to resolve this.
