### ISSUE TITLE
Exporter is shutdown before controller finishes pushing metric events in otel-collector example

### ISSUE THREAD

**Issue by kit494way** [open-telemetry/opentelemetry-go#1499]
https://github.com/open-telemetry/opentelemetry-go/blob/c066f15ed74fec52c4755014bfcf2bdfb8e0e661/example/otel-collector/main.go#L92-L96

As I understand it, calling `tracerProvider.Shutdown()` eventually invokes `Shotdown()` of  exporter which is shared with a controller.
As commented, `cont.Stop()` tries to push metric events to the exporter.
So, `cont.Stop()` should be called before  `tracerProvider.Shutdown()`, or it may cause same issue with https://github.com/open-telemetry/opentelemetry-go/issues/1437 .
Is it right?

**Comment by kobim** [comment]
This probably relates to https://github.com/open-telemetry/opentelemetry-go/pull/1443 - when using `NewBatchSpanProcessor` the underlying exporter is also closed.
Calling `cont.Stop` before shutting down the exporter should resolve this.
