### ISSUE TITLE
Invalid example in the OTLP exporter readme

### ISSUE THREAD

**Issue by morigs** [open-telemetry/opentelemetry-go#1502]
`otlp.NewExporter` missing second argument `driver`
https://github.com/open-telemetry/opentelemetry-go/tree/master/exporters/otlp

![image](https://user-images.githubusercontent.com/13474134/106253628-c8ae1d80-6228-11eb-9d5a-a615c59dc7a1.png)

**Comment by morigs** [comment]
It also seems that `WithAddress` is replaced with `WithEndpoint`

**Comment by schafle** [comment]
@MrAlias I created a PR to fix this issue, can you please take a look?
