### ISSUE TITLE
Recommend to make traceflags a struct 

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-go#1516]
Right now TraceFlags is just a bit, I think it is more extensible to have it like a struct `type TraceFlags byte` and expose helpers like `IsSampled` on this struct.

**Comment by MrAlias** [comment]
The Go type system allows methods to be added to any types, not just structs, so I'm not sure that should motivate an underlying type change. That said, I think the downside of using a struct with the small increase in resource overhead might be outweighed by the potential extensibility.

What other fields do you anticipate being added to the TraceFlags type?
