### ISSUE TITLE
HTTP client plugin's spans should reflect behavioural structure

### ISSUE THREAD

**Issue by iredelmeier** [open-telemetry/opentelemetry-go#152]
Currently, all of the `http.<x>` spans created by the [`clientTracer`](https://github.com/open-telemetry/opentelemetry-go/blob/0eb73325ce9e9855c21e783fb8236223edeedbef/plugin/httptrace/clienttrace.go) are created as siblings (see trace screenshot below). This is misleading based on the actual behaviour, e.g., the `http.dns` operation should actually be a child of the `http.getconn` span.

![Screenshot from 2019-09-27 14-18-05](https://user-images.githubusercontent.com/3298606/65804297-3bd7e900-e136-11e9-8cc4-411586188e10.png)

One option to fix this would be to manage our own set of `context.Context`s based on the actual behaviour, along the lines of what xray does [here](https://github.com/aws/aws-xray-sdk-go/blob/89001052516f60c9b3bebf297ce5f2a52ada1301/xray/httptrace.go#L27-L36)/[here](https://github.com/aws/aws-xray-sdk-go/blob/89001052516f60c9b3bebf297ce5f2a52ada1301/xray/httptrace.go#L60).

**Comment by rghetia** [comment]
@Aneurysm9 to look at it.
