### ISSUE TITLE
Makefile.proto prevents Bazel build. Please rename. 

### ISSUE THREAD

**Issue by marvin-hansen** [open-telemetry/opentelemetry-go#1525]
When building a project that depends on opentelemetry-go with bazel, the build fails because bazel invokes protoc internally to compile all *.proto files and that implies Makefile.proto.

I have this issue right now when integrating go-pg. See https://github.com/go-pg/pg/issues/1832 

The easiest solution  comes down to rename the Makefile in a way that it does not end in*proto so that Bazel, and virtually any other build tool invoking protoc can continue.

**Comment by marvin-hansen** [comment]
Added PR with the proposed change & signed CLA.

https://github.com/open-telemetry/opentelemetry-go/pull/1526

**Comment by XSAM** [comment]
It seems resolved in #1468 but not release yet.

`*.protos` files don't trigger the Bazel to comiple.

**Comment by marvin-hansen** [comment]
Thank you @XSAM that's exactly the same issue I am facing. 


I'm closing my PR and this issue as I wasn't aware of the patch only awaits releasing.

**Comment by marvin-hansen** [comment]
@XSAM is there an ETA for the next release?

**Comment by XSAM** [comment]
> @XSAM is there an ETA for the next release?

cc: @MrAlias

**Comment by MrAlias** [comment]
> ETA for the next release?

I'll try and get one out today.

**Comment by MrAlias** [comment]
[Release v0.17.0](https://github.com/open-telemetry/opentelemetry-go/releases/tag/v0.17.0)
