### ISSUE TITLE
Compilation error: duplicate method IsRecording, SpanContext, Tracer

### ISSUE THREAD

**Issue by MKruger777** [open-telemetry/opentelemetry-go#1547]
Hey Opentelemetry people,

I am trying to run this example as is in:
Ubuntu 20.04
goland 2020.1 
go version go1.13.4 linux/amd64

I then get the following exception.

# go.opentelemetry.io/otel/sdk/trace
../pkg/mod/go.opentelemetry.io/otel/sdk@v0.17.0/trace/span.go:71:2: duplicate method IsRecording
../pkg/mod/go.opentelemetry.io/otel/sdk@v0.17.0/trace/span.go:71:2: duplicate method SpanContext
../pkg/mod/go.opentelemetry.io/otel/sdk@v0.17.0/trace/span.go:71:2: duplicate method Tracer
note: module requires Go 1.14

Seriously not ruling out my go setup : ) however, other project builds correctly. 
Any ideas what could be the issue here?

Thanking you in advance.

Kind regards,
Morné Kruger

**Comment by punya** [comment]
@MKruger777 you mention that you're running Go 1.13 whereas the module requires Go 1.14. Any chance you can reproduce the problem with a supported version of Go?

**Comment by MKruger777** [comment]
Jaiks! missed that - so sorry. Gonna give it a go. Thanks!

**Comment by MKruger777** [comment]
Thanks so much,  works perfectly!
