### ISSUE TITLE
Zipkin exporter should take service.name from Resource

### ISSUE THREAD

**Issue by evantorrie** [open-telemetry/opentelemetry-go#1549]
Zipkin requires a service name to be sent with each span.  Per the specification https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/zipkin.md#service-name , 

    Zipkin service name MUST be set to the value of the resource attribute: service.name. 
    If no service.name is contained in a Span's Resource, it MUST be populated from the default Resource

**Comment by jcchavezs** [comment]
Relevant: https://github.com/open-telemetry/opentelemetry-go/issues/1695#issuecomment-797593558
