### ISSUE TITLE
Jaeger exporter must populate Jaeger's Span.Process from Resource service.name attribute

### ISSUE THREAD

**Issue by evantorrie** [open-telemetry/opentelemetry-go#1550]
Per specification: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/jaeger.md#resource

Should fall back to `resource.Default()` `service.name` attribute if the exported Span does not have its own Resource `service.name`

**Comment by veera83372** [comment]
@XSAM  still working on this?

**Comment by XSAM** [comment]
@veera83372 Sorry for the delay. I'm still working on this.
