### ISSUE TITLE
exporters/stdout TestStdoutTimestamp test failure

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#1571]
This test seems to consistently be failing for Windows testing using Go 1.14 and 1.15:

https://github.com/open-telemetry/opentelemetry-go/runs/1962753557?check_suite_focus=true

```
go test -timeout 30s -short ./exporters/stdout/...
--- FAIL: TestStdoutTimestamp (0.04s)
    metric_test.go:122: 
        	Error Trace:	metric_test.go:122
        	Error:      	Should be true
        	Test:       	TestStdoutTimestamp
FAIL
FAIL	go.opentelemetry.io/otel/exporters/stdout	0.775s
FAIL
mingw32-make: *** [Makefile:100: test] Error 123
```

Looking at the test ...

https://github.com/open-telemetry/opentelemetry-go/blob/b94cd4b24917d0099eb0ddee6f9d6be0bddee469/exporters/stdout/metric_test.go#L78-L124

## Proposals

- It is testing a "before" time is before a measured timestamp without ensuring there is a delay of time. We should add a small artificial duration to ensure this test succeeds.
- We can remove the check of the before/after timestamp. I'm not sure these are actually adding value. I think we need to verify that a timestamp is returned, but I'm not sure it is the exporters responsibility to ensure the monotonicity of the timestamps (rather that is the metrics pipeline itself).

**Comment by punya** [comment]
We're running into the same issue in #1559 too: tests flaking because they assume that a nonzero amount of time elapses.

**Comment by MrAlias** [comment]
> We're running into the same issue in #1559 too: tests flaking because they assume that a nonzero amount of time elapses. There we decided to add artificial delays in the test to make the behavior predictable.

Cool, sounds like we are going to be consistent in a solution :+1:. I've taken the same approach in the linked PR.
