### ISSUE TITLE
OTLP exporter only for traces

### ISSUE THREAD

**Issue by vmihailenco** [open-telemetry/opentelemetry-go#1583]
Is it possible to configure OTLP exporter only for traces (and omit metrics)? E.g.

```go
driver := otlpgrpc.NewDriver(...)

exporter, err := otlp.NewExporter(ctx,
	otlp.NewSplitDriver(otlp.SplitConfig{
		// ForMetrics: driver,
		ForTraces: driver,
	}),
)
```

produces

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x6d0495]

goroutine 13 [running]:
go.opentelemetry.io/otel/exporters/otlp.(*splitDriver).Start.func1(0xc000257390, 0xc0000d1c80, 0xb061b0, 0xc0000b2000, 0xc000227df0)
	/home/vmihailenco/workspace/opentelemetry-go/exporters/otlp/protocoldriver.go:92 +0x55
created by go.opentelemetry.io/otel/exporters/otlp.(*splitDriver).Start
	/home/vmihailenco/workspace/opentelemetry-go/exporters/otlp/protocoldriver.go:90 +0xcb
exit status 2
```

Uncommenting `ForMetrics` fixes the panic, but I guess it will also export metrics which is undesirable for backends that don't support metrics...

**Comment by Aneurysm9** [comment]
The OTLP exporter handles both metrics and traces.  The `splitDriver` you're using there is intended for situations where you want to export both metrics and traces, but send them to different locations.  If you only wish to export traces you can use the OTLP/gRPC driver directly and only attach it to a trace provider.  If no metric pipeline is configured to use it as an exporter then no metrics will be exported.

That said, this panic is obviously not desirable.  I wonder whether it is better to have the `NewSplitDriver()` initializer return an error if the provided `SplitConfig` is missing to reduce the likelihood of unintentionally dropping metrics/trace data if misconfigured, or maybe have the driver emit error logs if it receives metrics/trace data without the appropriate driver configured.

**Comment by vmihailenco** [comment]
Thanks for clarifying :+1: I guess it is confusing because other exporters don't have the concept of drivers at all which makes OTLP stand out... From user perspective having `otlpgrpc.Exporter` and `otlphttp.Exporter` is way simpler...

But even now it is somewhat confusing why SplitDriver is needed at all if driver must be registered separately for traces and separately for metrics...

**Comment by Aneurysm9** [comment]
> But even now it is somewhat confusing why SplitDriver is needed at all if driver must be registered separately for traces and separately for metrics...

Trace and metrics drivers don't need to be registered separately.  If you register an `otlpgrpc.Exporter` instead of a `SplitDriver` it will be used for both signals.  The [`ProtocolDriver` interface](https://github.com/open-telemetry/opentelemetry-go/blob/main/exporters/otlp/protocoldriver.go#L46-L51) covers exporting both metrics and  traces and is implemented by the `otlpgrpc.Exporter`, `otlphttp.Exporter`, and the `SplitDriver`.  The `SplitDriver` interface would be useful where you want to send metrics to one collection system and traces to another, or metrics via HTTP and traces via gRPC.  If both signals are traversing the same protocol to the same endpoint then you can use the appropriate protocol-specific driver directly.

**Comment by bryan-aguilar** [comment]
@Aneurysm9  I would like to work on this. According to the above discussion the bug lies in how `NewSplitDriver` handles bad configs. I see you suggested two possible paths forward, I can bring this up in the go SIG tomorrow.

**Comment by bryan-aguilar** [comment]
Note from SIG meeting (2021-4-01):
Should not panic when a user does not define all drivers. Change `NewSplitDriver` to take variadic arguments. Internally apply noop driver for omitted drivers.
