### ISSUE TITLE
OLTP-GRPC generator upgrade

### ISSUE THREAD

**Issue by MadVikingGod** [open-telemetry/opentelemetry-go#1585]
While working on #1122 I found that the gogo generated protobuf types are not forward compatible with the current protobuf API v2 (google.golang.org/protobuf@v1.4.0).

A solution would involve moving away from gogo to the google protobuf.

My concern with this upgrade is the performance of the generated files, what kind of performance should we measure.  And, what kind of regression would be a blocker from moving to the new API?

**Comment by MrAlias** [comment]
@bogdandrutu can you help specify what performance metrics we should be looking at here?

We can plan to make this change after the RC if need. Also, whatever decision made here needs to be included in the new repo: https://github.com/open-telemetry/opentelemetry-proto-go
