### ISSUE TITLE
Spec Conformance Review: Traces/TracerProvider

### ISSUE THREAD

**Issue by Aneurysm9** [open-telemetry/opentelemetry-go#1587]
Please review the `Traces/TracerProvider` section of the [Spec Compliance Matrix](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md) and the corresponding implementations in the [core](https://github.com/open-telemetry/opentelemetry-go) and [contrib](https://github.com/open-telemetry/opentelemetry-go-contrib) repositories.  For each entry in the compliance matrix please ensure that either the implementation conforms to [the specification](https://github.com/open-telemetry/opentelemetry-specification/tree/v1.0.1) or that an issue is created in the relevant repository to address the non-conformance.  Ignore any entries presently in the matrix for Go, assume that all features must be freshly evaluated.

**Comment by MrAlias** [comment]
| Feature                                                                | Go |
|------------------------------------------------------------------------|----|
| [TracerProvider](specification/trace/api.md#tracerprovider-operations) |    |
| Create TracerProvider                                                  | [NewTracerProvider](https://pkg.go.dev/go.opentelemetry.io/otel/sdk/trace#NewTracerProvider) |
| Get a Tracer                                                           | [TracerProvider.Tracer](https://pkg.go.dev/go.opentelemetry.io/otel/sdk/trace#TracerProvider.Tracer) |
| Safe for concurrent calls                                              | [Yes](https://github.com/open-telemetry/opentelemetry-go/pull/1607) |
| Shutdown (SDK only required)                                           | [Shutdown](https://pkg.go.dev/go.opentelemetry.io/otel/sdk/trace#TracerProvider.Shutdown) |
| ForceFlush (SDK only required)                                         | Not Implemented: [Tracking Issue](https://github.com/open-telemetry/opentelemetry-go/issues/1606) |
