### ISSUE TITLE
Spec Conformance Review: Traces/Trace / Context interaction

### ISSUE THREAD

**Issue by Aneurysm9** [open-telemetry/opentelemetry-go#1588]
Please review the `Traces/Trace / Context interaction` section of the [Spec Compliance Matrix](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md) and the corresponding implementations in the [core](https://github.com/open-telemetry/opentelemetry-go) and [contrib](https://github.com/open-telemetry/opentelemetry-go-contrib) repositories.  For each entry in the compliance matrix please ensure that either the implementation conforms to [the specification](https://github.com/open-telemetry/opentelemetry-specification/tree/v1.0.1) or that an issue is created in the relevant repository to address the non-conformance.  Ignore any entries presently in the matrix for Go, assume that all features must be freshly evaluated.

**Comment by MrAlias** [comment]
[The specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#context-interaction):

> The API MUST provide the following functionality to interact with a Context instance:
> 
> Extract the Span from a Context instance

https://pkg.go.dev/go.opentelemetry.io/otel/trace@v0.17.0#SpanFromContext

> Insert the Span to a Context instance

https://pkg.go.dev/go.opentelemetry.io/otel/trace@v0.17.0#ContextWithSpan

> If the language has support for implicitly propagated Context (see here), the API SHOULD also provide the following functionality:
> 
> Get the currently active span from the implicit context. This is equivalent to getting the implicit context, then extracting the Span from the context.
> Set the currently active span to the implicit context. This is equivalent to getting the implicit context, then inserting the Span to the context.

Go uses explicit, not implicitly scoped, context.

> All the above functionalities operate solely on the context API, and they MAY be exposed as either static methods on the trace module, or as static methods on a class inside the trace module. This functionality SHOULD be fully implemented in the API when possible.

:heavy_check_mark: 

---

| Feature                     | Go  |
|-----------------------------|-----|
| Trace / Context interaction |     |
| Get active Span             | N/A |
| Set active Span             | N/A |
