### ISSUE TITLE
Spec Conformance Review: Traces/Span

### ISSUE THREAD

**Issue by Aneurysm9** [open-telemetry/opentelemetry-go#1591]
Please review the `Traces/Span` section of the [Spec Compliance Matrix](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md) and the corresponding implementations in the [core](https://github.com/open-telemetry/opentelemetry-go) and [contrib](https://github.com/open-telemetry/opentelemetry-go-contrib) repositories.  For each entry in the compliance matrix please ensure that either the implementation conforms to [the specification](https://github.com/open-telemetry/opentelemetry-specification/tree/v1.0.1) or that an issue is created in the relevant repository to address the non-conformance.  Ignore any entries presently in the matrix for Go, assume that all features must be freshly evaluated.

**Comment by MrAlias** [comment]
[From the Span API definition](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/api.md#span):

> A `Span`'s start time SHOULD be set to the current time on [span creation](#span-creation).

https://github.com/open-telemetry/opentelemetry-go/blob/e25503a00edef6baf2b3deb1a5884d4501e08dcf/sdk/trace/span.go#L551-L555

> After the `Span` is created, it SHOULD be possible to change its name, set its `Attribute`s, add `Event`s, and set the `Status`.

All are a part of the Span interface: https://pkg.go.dev/go.opentelemetry.io/otel/trace@v0.17.0#Span

>These MUST NOT be changed after the `Span`'s end time has been set.

This was addressed in [this completed issue](https://github.com/open-telemetry/opentelemetry-go/issues/1326)

> ... implementations SHOULD NOT provide access to a `Span`'s attributes besides its `SpanContext`.

There is no method in the Span interface to access the `Span`'s attributes: https://pkg.go.dev/go.opentelemetry.io/otel/trace@v0.17.0#Span

> All `Span`s MUST be created via a `Tracer`.

It's hard to show the negative, but the only exported way to create a span is from a Tracer.

**Comment by MrAlias** [comment]
[From the Span Creation section of the Trace API](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/api.md#span-creation):

> There MUST NOT be any API for creating a `Span` other than with a [`Tracer`](#tracer).

Same as before, it's hard to show the negative, but the only exported way to create a span is from a Tracer.

> `Span` creation MUST NOT set the newly created `Span` as the currently active `Span` by default, but this functionality MAY be offered additionally as a separate operation.

The Go implementation does not have an implicit active span. All spans (and related context) are passed explicitly.

> The API MUST accept the following parameters:
> 
> - The span name. This is a required parameter.

The `Tracer.Start` method requires a span name be passed: https://pkg.go.dev/go.opentelemetry.io/otel/trace#Tracer

> - The parent `Context` or an indication that the new `Span` should be a root `Span`.

The `Tracer.Start` method requires a context passed, if the context contains a SpanContext is is interpreted as a parent: https://pkg.go.dev/go.opentelemetry.io/otel/trace#Tracer . [WithNewRoot](https://pkg.go.dev/go.opentelemetry.io/otel/trace@v0.17.0#WithNewRoot) is used to state the span should be a root.

>   The API MAY also have an option for implicitly using the current Context as parent as a default behavior.

The Go implementation does not have implied context, it is explicit.

>   This API MUST NOT accept a `Span` or `SpanContext` as parent, only a full `Context`.

It does not: https://pkg.go.dev/go.opentelemetry.io/otel/trace#Tracer

> - [`SpanKind`](#spankind)

[WithSpanKind](https://pkg.go.dev/go.opentelemetry.io/otel/trace@v0.17.0#WithSpanKind)

> ... default to `SpanKind.Internal` if not specified.

https://github.com/open-telemetry/opentelemetry-go/blob/76f93422778d8cb70813593dac19a0fc9f2338ee/sdk/trace/span.go#L511

https://github.com/open-telemetry/opentelemetry-go/blob/76f93422778d8cb70813593dac19a0fc9f2338ee/trace/trace.go#L515-L527

> - [`Attributes`](../common/common.md#attributes). Additionally, these attributes may be used to make a sampling decision as noted in [sampling description](sdk.md#sampling). An empty collection will be assumed if not specified.

[WithAttributes](https://pkg.go.dev/go.opentelemetry.io/otel/trace@v0.17.0#WithAttributes)

> - `Link`s - an ordered sequence of Links, see API definition [here](#specifying-links).

[WithLinks](https://pkg.go.dev/go.opentelemetry.io/otel/trace@v0.17.0#WithLinks)

> - `Start timestamp`

[WithTimestamp](https://pkg.go.dev/go.opentelemetry.io/otel/trace@v0.17.0#WithTimestamp)

> ... default to current time.

https://github.com/open-telemetry/opentelemetry-go/blob/e25503a00edef6baf2b3deb1a5884d4501e08dcf/sdk/trace/span.go#L551-L555

>   This argument SHOULD only be set when span creation time has already passed.
>   If API is called at a moment of a Span logical start, API user MUST NOT explicitly set this argument.

These are requirements for the user (not sure why they are in the spec).

> Implementations MUST provide an option to create a `Span` as a root span

[WithNewRoot](https://pkg.go.dev/go.opentelemetry.io/otel/trace@v0.17.0#WithNewRoot)

> ... and MUST generate a new `TraceId` for each root span created.

https://github.com/open-telemetry/opentelemetry-go/blob/e25503a00edef6baf2b3deb1a5884d4501e08dcf/sdk/trace/span.go#L521-L527

> For a Span with a parent, the `TraceId` MUST be the same as the parent.

https://github.com/open-telemetry/opentelemetry-go/blob/e25503a00edef6baf2b3deb1a5884d4501e08dcf/sdk/trace/span.go#L526

> Also, the child span MUST inherit all `TraceState` values of its parent by default.

https://github.com/open-telemetry/opentelemetry-go/blob/e25503a00edef6baf2b3deb1a5884d4501e08dcf/sdk/trace/span.go#L517

> 
> A `Span` is said to have a _remote parent_ if it is the child of a `Span` created in another process.
> Each propagators' deserialization must set `IsRemote` to true on a parent `SpanContext` so `Span` creation knows if the parent is remote.

https://github.com/open-telemetry/opentelemetry-go/blob/e25503a00edef6baf2b3deb1a5884d4501e08dcf/sdk/trace/span.go#L559

> Any span that is created MUST also be ended.
> This is the responsibility of the user.
> API implementations MAY leak memory or other resources (including, for example, CPU time for periodic work that iterates all spans) if the user forgot to end the span.

Again, these are requirements for the user (not sure why they are in the spec for implementations).

**Comment by MrAlias** [comment]
[Determining the Parent Span from a Context](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/api.md#determining-the-parent-span-from-a-context):

> When a new Span is created from a Context, the Context may contain a Span representing the currently active instance, and will be used as parent. If there is no Span in the Context, the newly created Span will be a root span.

This tests behavior when a parent is included in the context:

https://github.com/open-telemetry/opentelemetry-go/blob/e25503a00edef6baf2b3deb1a5884d4501e08dcf/sdk/trace/trace_test.go#L297-L342

The default behavior of GetSpanContextAndLinks will be used for a context without a span:

https://github.com/open-telemetry/opentelemetry-go/blob/e25503a00edef6baf2b3deb1a5884d4501e08dcf/internal/trace/parent/parent.go#L24-L40

**Comment by MrAlias** [comment]
[Specifying links](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/api.md#specifying-links)

> During the `Span` creation user MUST have the ability to record links to other `Span`s.

[WithLinks](https://pkg.go.dev/go.opentelemetry.io/otel/trace@v0.17.0#WithLinks)

> `Link`s cannot be added after Span creation.

The [Span](https://pkg.go.dev/go.opentelemetry.io/otel/trace@v0.17.0#Span) does not have a method to add links. The only time they can be added is at creation.

> The Span creation API MUST provide:
> 
> - An API to record a single `Link` where the `Link` properties are passed as arguments.
>   This MAY be called `AddLink`.
>   This API takes the `SpanContext` of the `Span` to link to and optional `Attributes`, either as individual parameters or as an immutable object encapsulating them, whichever is most appropriate for the language.

[WithLinks](https://pkg.go.dev/go.opentelemetry.io/otel/trace@v0.17.0#WithLinks) can record a single (or multiple) link(s). The link is passed as a link value.

> Links SHOULD preserve the order in which they're set.

https://github.com/open-telemetry/opentelemetry-go/blob/ad7b4715860b3b40abc876093c075bf765a6e120/sdk/trace/tracer.go#L55-L57

**Comment by MrAlias** [comment]
| Feature                                       | Go                                                                                                         |
|-----------------------------------------------|------------------------------------------------------------------------------------------------------------|
| Create root span                              | + [WithNewRoot](https://pkg.go.dev/go.opentelemetry.io/otel/trace@v0.17.0#WithNewRoot)   |
| Create with default parent (active span)      | N/A |
| Create with parent from Context               | + [1](https://github.com/open-telemetry/opentelemetry-go/blob/e25503a00edef6baf2b3deb1a5884d4501e08dcf/sdk/trace/trace_test.go#L297-L342)   |
| No explicit parent Span/SpanContext allowed   | + [Tracer.Start does not accept these are parameters.](https://pkg.go.dev/go.opentelemetry.io/otel/trace@v0.17.0#Tracer)  |
| SpanProcessor.OnStart receives parent Context | + [1](https://github.com/open-telemetry/opentelemetry-go/blob/e25503a00edef6baf2b3deb1a5884d4501e08dcf/sdk/trace/tracer.go#L65)   |
| UpdateName                                    | + [We call the method SetName](https://pkg.go.dev/go.opentelemetry.io/otel/trace@v0.17.0#Span)  |
| User-defined start timestamp                  | + [1](https://pkg.go.dev/go.opentelemetry.io/otel/trace@v0.17.0#WithTimestamp)  |
| End                                           | + [part of interface](https://pkg.go.dev/go.opentelemetry.io/otel/trace@v0.17.0#Span)   |
| End with timestamp                            | + [1](https://pkg.go.dev/go.opentelemetry.io/otel/trace@v0.17.0#WithTimestamp)  |
| IsRecording                                   | + [part of interface](https://pkg.go.dev/go.opentelemetry.io/otel/trace@v0.17.0#Span)  |
| IsRecording becomes false after End           | + [1](https://github.com/open-telemetry/opentelemetry-go/blob/e25503a00edef6baf2b3deb1a5884d4501e08dcf/sdk/trace/span.go#L241-L247)  |
| Set status with StatusCode (Unset, Ok, Error) | + [part of interface](https://pkg.go.dev/go.opentelemetry.io/otel/trace@v0.17.0#Span)   |
| Safe for concurrent calls                     | + [yes](https://github.com/open-telemetry/opentelemetry-go/blob/e25503a00edef6baf2b3deb1a5884d4501e08dcf/sdk/trace/span.go#L178-L181)  |
| events collection size limit                  | + [1](https://github.com/open-telemetry/opentelemetry-go/blob/e25503a00edef6baf2b3deb1a5884d4501e08dcf/sdk/trace/config.go#L36-L52)   |
| attribute collection size limit               | + [1](https://github.com/open-telemetry/opentelemetry-go/blob/e25503a00edef6baf2b3deb1a5884d4501e08dcf/sdk/trace/config.go#L36-L52)   |
| links collection size limit                   | + [1](https://github.com/open-telemetry/opentelemetry-go/blob/e25503a00edef6baf2b3deb1a5884d4501e08dcf/sdk/trace/config.go#L36-L52)   |
