### ISSUE TITLE
Spec Conformance Review: Traces/Span events

### ISSUE THREAD

**Issue by Aneurysm9** [open-telemetry/opentelemetry-go#1594]
- [x] Review [Span Operation -- Add Events](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/api.md#add-events) section and identify all normative requirements it contains.
- [x] Validate our implementation of the specification to conform or not. If it conforms, document the conformity here. If it does not open an Issue or PR track the work.
- [x] Review the `Traces/Span events` section of the [Spec Compliance Matrix](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md).
- [x] If there are any items listed in matrix that are not required by the specification, need clarification, or are in conflict with the specification open a PR in the specification to correct it.
- [x] Update the matrix with the current state of Go (existing entries for Go should be ignored). If Go does not provide support for an item listed be sure to link to the Issue/PR tracking the work to support it.

**Comment by MrAlias** [comment]
### [Span -- AddEvents](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/api.md#add-events)

> A Span MUST have the ability to add events.

[The AddEvent method of the span interface provides this](https://github.com/open-telemetry/opentelemetry-go/blob/2b4d5ac3293eee30536754a5d5efec5124433ded/trace/trace.go#L416-L417)


> An Event is structurally defined by the following properties:

> - Name of the event.
> - A timestamp for the event.
>   Either the time at which the event was added or a custom timestamp provided by the user.
> - Zero or more Attributes further describing the event.

[This is not normative, but is how `Event` is defined](https://github.com/open-telemetry/opentelemetry-go/blob/2b4d5ac3293eee30536754a5d5efec5124433ded/trace/trace.go#L444-L454)

> The Span interface MUST provide:
> - An API to record a single Event where the Event properties are passed as arguments.

[AddEvent is defined this way](https://github.com/open-telemetry/opentelemetry-go/blob/2b4d5ac3293eee30536754a5d5efec5124433ded/trace/trace.go#L416-L417)

>   This MAY be called AddEvent.

[it is](https://github.com/open-telemetry/opentelemetry-go/blob/2b4d5ac3293eee30536754a5d5efec5124433ded/trace/trace.go#L416-L417)

>   This API takes the name of the event, optional Attributes and an optional Timestamp which can be used to specify the time at which the event occurred, either as individual parameters or as an immutable object encapsulating them, whichever is most appropriate for the language.

[The method takes a name as a required parameters](https://github.com/open-telemetry/opentelemetry-go/blob/2b4d5ac3293eee30536754a5d5efec5124433ded/trace/trace.go#L416-L417), and [WithAttributes](https://github.com/open-telemetry/opentelemetry-go/blob/2b4d5ac3293eee30536754a5d5efec5124433ded/trace/config.go#L131-L142) and [WithTimestamp](https://github.com/open-telemetry/opentelemetry-go/blob/2b4d5ac3293eee30536754a5d5efec5124433ded/trace/config.go#L151-L155) can be passed as variadic options.

>   If no custom timestamp is provided by the user, the implementation automatically sets the time at which this API is called on the event.

[Not normative, but we do](https://github.com/open-telemetry/opentelemetry-go/blob/2b4d5ac3293eee30536754a5d5efec5124433ded/trace/config.go#L98-L100)

>   Events SHOULD preserve the order in which they are recorded.

[This is how it is implemented](https://github.com/open-telemetry/opentelemetry-go/blob/2b4d5ac3293eee30536754a5d5efec5124433ded/sdk/trace/evictedqueue.go#L37)

**Comment by MrAlias** [comment]
| Feature | Go | 
|------------|----|
| AddEvent                  | [+](https://github.com/open-telemetry/opentelemetry-go/blob/2b4d5ac3293eee30536754a5d5efec5124433ded/trace/trace.go#L416-L417)  |
| Add order preserved       | [+](https://github.com/open-telemetry/opentelemetry-go/blob/2b4d5ac3293eee30536754a5d5efec5124433ded/sdk/trace/evictedqueue.go#L37)  |
| Safe for concurrent calls | [+](https://github.com/open-telemetry/opentelemetry-go/blob/2b4d5ac3293eee30536754a5d5efec5124433ded/oteltest/harness.go#L270-L291)  |
