### ISSUE TITLE
Spec Conformance Review: Traces/Span exceptions

### ISSUE THREAD

**Issue by Aneurysm9** [open-telemetry/opentelemetry-go#1595]
- [x] Review [Span Operation -- Record Exception](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/api.md#record-exception) section and identify all normative requirements it contains.
- [x] Validate our implementation of the specification to conform or not. If it conforms, document the conformity here. If it does not open an Issue or PR track the work.
- [x] Review the `Traces/Span exceptions` section of the [Spec Compliance Matrix](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md).
- [x] If there are any items listed in matrix that are not required by the specification, need clarification, or are in conflict with the specification open a PR in the specification to correct it.
- [x] Update the matrix with the current state of Go (existing entries for Go should be ignored). If Go does not provide support for an item listed be sure to link to the Issue/PR tracking the work to support it.

*N.B.*: we have [decided](https://github.com/open-telemetry/opentelemetry-go/issues/1491#issuecomment-780206797) after discussion at the SIG meeting on 2/11/2021 to retain the `span.RecordError()` method name and to produce events with an `exception` name and prefix.  We believe this to be compliant.

**Comment by MrAlias** [comment]
Related https://github.com/open-telemetry/opentelemetry-go/issues/1661

We might also want to think through the possibility of what we will do if OTel decides to add in addition a `RecordError` API.

**Comment by MrAlias** [comment]
> [To facilitate recording an exception languages SHOULD provide a `RecordException` method if the language uses exceptions.](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/api.md#record-exception)

Based on the included conditional and [the possibility that errors might one day have their own specified method](https://cloud-native.slack.com/archives/C01N7PP1THC/p1614979474070000?thread_ts=1614978903.067900&cid=C01N7PP1THC) it seems like we might be putting our future selves into a hard position if we create an error with the `RecordError` method that records an event as an exception.

**Comment by MrAlias** [comment]
Added an agenda item to the 2020-03-11 SIG meeting to get feedback.
