### ISSUE TITLE
Spec Conformance Review: Traces/Sampling

### ISSUE THREAD

**Issue by Aneurysm9** [open-telemetry/opentelemetry-go#1596]
- [x] Review [Sampler](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/sdk.md#sampler) section of the specification and identify all normative requirements it contains.
- [x] Validate our implementation of the specification to conform or not. If it conforms, document the conformity here. If it does not open an Issue or PR track the work.
- [x] Review the `Traces/Sampling` section of the [Spec Compliance Matrix](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md).
- [x] If there are any items listed in matrix that are not required by the specification, need clarification, or are in conflict with the specification open a PR in the specification to correct it.
- [x] Update the matrix with the current state of Go (existing entries for Go should be ignored). If Go does not provide support for an item listed be sure to link to the Issue/PR tracking the work to support it.

**Comment by MrAlias** [comment]
| Feature                               | Go |
|---------------------------------------|----|
| Allow samplers to modify tracestate   | + Addressed in [#1432](https://github.com/open-telemetry/opentelemetry-go/pull/1432) |
| ShouldSample gets full parent Context | [+](https://github.com/open-telemetry/opentelemetry-go/blob/90bd4ab50c6e85743f2b8f3a1768a5afceeb1fc0/sdk/trace/sampling.go#L33)   |

**Comment by MrAlias** [comment]
I noticed that the [`Sampling` section of the sdk spec](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/sdk.md#sampling) is not covered by any other issue. Going to include it in the audit included in this issue.

**Comment by MrAlias** [comment]
### [Sampling](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/sdk.md#sampling)

> The OpenTelemetry API has two properties responsible for the data collection:
> * `IsRecording` field of a `Span`.
>   If `false` the current `Span` discards all tracing data (attributes, events, status, etc.).
>   Users can use this property to determine if collecting expensive trace data can be avoided.
>   [Span Processor](#span-processor) MUST receive only those spans which have this field set to `true`.

If `IsRecording` returns false [it is not sent to the span processors](https://github.com/open-telemetry/opentelemetry-go/blob/90bd4ab50c6e85743f2b8f3a1768a5afceeb1fc0/sdk/trace/span.go#L221-L223).

>   However, [Span Exporter](#span-exporter) SHOULD NOT receive them unless the `Sampled` flag was also set.

* The [`SimpleSpanProcessor` does not send unless sampled](https://github.com/open-telemetry/opentelemetry-go/blob/90bd4ab50c6e85743f2b8f3a1768a5afceeb1fc0/sdk/trace/simple_span_processor.go#L52)
* The [`BatchSpanProcessor` does not send unless sampled](https://github.com/open-telemetry/opentelemetry-go/blob/90bd4ab50c6e85743f2b8f3a1768a5afceeb1fc0/sdk/trace/batch_span_processor.go#L259)

> * `Sampled` flag in `TraceFlags` on `SpanContext`.
>   This flag is propagated via the `SpanContext` to child Spans.
>   For more details see the [W3C Trace Context specification](https://www.w3.org/TR/trace-context/#sampled-flag).
>   This flag indicates that the `Span` has been `sampled` and will be exported.
>   [Span Exporters](#span-exporter) MUST receive those spans which have `Sampled` flag set to true and they SHOULD NOT receive the ones that do not.

This is a restatement of the above recommendation.

> The flag combination `SampledFlag == true` and `IsRecording == false` could cause gaps in the distributed trace, and because of this OpenTelemetry API MUST NOT allow this combination.

Based on the way the sampling decision enums are structured in combination with the fact that [`isRecording`](https://github.com/open-telemetry/opentelemetry-go/blob/90bd4ab50c6e85743f2b8f3a1768a5afceeb1fc0/sdk/trace/span.go#L621-L623) is a superset of [`isSampled`](https://github.com/open-telemetry/opentelemetry-go/blob/90bd4ab50c6e85743f2b8f3a1768a5afceeb1fc0/sdk/trace/span.go#L625-L627) it is not possible for `isSampled` to return `true` without `isRecording` to also return `true`.

**Comment by MrAlias** [comment]
> **Required arguments:**
>
> * [`Context`](../context/context.md) with parent `Span`.
>   The Span's SpanContext may be invalid to indicate a root span.

https://github.com/open-telemetry/opentelemetry-go/blob/90bd4ab50c6e85743f2b8f3a1768a5afceeb1fc0/sdk/trace/sampling.go#L33

This is not technically correct. A `SpanContext` is not a `Span` contained in a `Context`. I think this is going to ultimately be related to https://github.com/open-telemetry/opentelemetry-go/issues/1182 where we should probably be storing a span in the context, not a `SpanContext`.

**Comment by MrAlias** [comment]
Tracking here: https://github.com/open-telemetry/opentelemetry-go/issues/1727
