### ISSUE TITLE
Spec Conformance Review: Traces

### ISSUE THREAD

**Issue by Aneurysm9** [open-telemetry/opentelemetry-go#1597]
Please review the `Traces` section of the [Spec Compliance Matrix](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md) and the corresponding implementations in the [core](https://github.com/open-telemetry/opentelemetry-go) and [contrib](https://github.com/open-telemetry/opentelemetry-go-contrib) repositories.  For each entry in the compliance matrix please ensure that either the implementation conforms to [the specification](https://github.com/open-telemetry/opentelemetry-specification/tree/v1.0.1) or that an issue is created in the relevant repository to address the non-conformance.  Ignore any entries presently in the matrix for Go, assume that all features must be freshly evaluated.

Many elements of the `Traces` section are covered by other review issues.  Those that remain to review here are:

* New Span ID created also for non-recording Spans
* IdGenerators
* SpanLimits

**Comment by MrAlias** [comment]
Breaking this up into:

- https://github.com/open-telemetry/opentelemetry-go/issues/1648
- https://github.com/open-telemetry/opentelemetry-go/issues/1649
- https://github.com/open-telemetry/opentelemetry-go/issues/1650
