### ISSUE TITLE
Spec Conformance Review: Baggage

### ISSUE THREAD

**Issue by Aneurysm9** [open-telemetry/opentelemetry-go#1598]
- [x] Review the [Baggage](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/baggage/api.md) API specification and identify all normative requirements it contains.
- [x] Validate our implementation of the specification to conform or not. If it conforms, document the conformity here. If it does not open an Issue or PR track the work.
- [x] Review the `Baggage` section of the [Spec Compliance Matrix](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md).
- [x] If there are any items listed in matrix that are not required by the specification, need clarification, or are in conflict with the specification open a PR in the specification to correct it.
- [x] Update the matrix with the current state of Go (existing entries for Go should be ignored). If Go does not provide support for an item listed be sure to link to the Issue/PR tracking the work to support it.

**Comment by MrAlias** [comment]
### [Overview](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/baggage/api.md#overview)

> Each name in `Baggage` MUST be associated with exactly one value.

This is implemented by relying on the internal Go map having exactly one key associated with one value:

https://github.com/open-telemetry/opentelemetry-go/blob/90bd4ab50c6e85743f2b8f3a1768a5afceeb1fc0/internal/baggage/baggage.go#L90-L93


> Depending on language idioms, a language API MAY implement these functions by providing the defined functionality interacting purely via the `Context`.

That is how we implemented the public interface:

https://github.com/open-telemetry/opentelemetry-go/blob/v0.18.0/baggage/baggage.go

> The Baggage API MUST be fully functional in the absence of an installed SDK.
> If a Baggage propagator is installed into the API, it will work with or without an installed SDK.

The propagator does not depend on the SDK and works as specified here.

https://github.com/open-telemetry/opentelemetry-go/blob/bb4c297eb36f6af082bfa1d3216d33bd90da05f0/propagation/baggage.go#L17-L24

> The `Baggage` container MUST be immutable, so that the containing `Context` also remains immutable.

The baggage container is implemented as a `Map` type that can only [`Apply`](https://github.com/open-telemetry/opentelemetry-go/blob/90bd4ab50c6e85743f2b8f3a1768a5afceeb1fc0/internal/baggage/baggage.go#L73) an update and receive an updated copy of the original. The original remains unmodified.

**Comment by MrAlias** [comment]
### [Context Interaction](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/baggage/api.md#context-interaction)

> This section defines all operations within the Baggage API that interact with the [`Context`](../context/context.md).
>
> The API MUST provide the following functionality to interact with a `Context` instance:
>
> - Extract the `Baggage` from a `Context` instance
> - Insert the `Baggage` to a `Context` instance
>
> The functionality listed above is necessary because API users SHOULD NOT have access to the [Context Key](../context/context.md#create-a-key) used by the Baggage API implementation.

The baggage API does not require a user to access the context keys that baggage are stored with, in fact, they are inaccessible to the user. This section appears not-applicable to our implementation as we choose to implement based on the option outlined in the Overview: "Depending on language idioms, a language API MAY implement these functions by providing the defined functionality interacting purely via the Context."

Extracting and inserting are not functionality reasonable for an implementation that interact purely via the Context.

> If the language has support for implicitly propagated `Context` (see [here](../context/context.md#optional-global-operations)), the API SHOULD also provide the following functionality:
>
> - Get the currently active `Baggage` from the implicit context.
>   This is equivalent to getting the implicit context, then extracting the `Baggage` from the context.
> - Set the currently active `Baggage` to the implicit context.
>   This is equivalent to getting the implicit context, then inserting the `Baggage` to the context.
>
> All the above functionalities operate solely on the context API, and they MAY be exposed as static methods on the baggage module, as static methods on a class inside the baggage module (it MAY be named `BaggageUtilities`), or on the `Baggage` class.
> This functionality SHOULD be fully implemented in the API when possible.

The project does not support an implicit context.

> ### Clear Baggage in the Context
>
> To avoid sending any name/value pairs to an untrusted process, the Baggage API MUST provide a way to remove all baggage entries from a context.
>
> This functionality can be implemented by having the user set an empty `Baggage` object/struct into the context, or by providing an API that takes a `Context` as input, and returns a new `Context` with no `Baggage` associated.

https://github.com/open-telemetry/opentelemetry-go/blob/bb4c297eb36f6af082bfa1d3216d33bd90da05f0/baggage/baggage.go#L64-L67

**Comment by MrAlias** [comment]
Added a [PR](https://github.com/open-telemetry/opentelemetry-specification/pull/1525) for the specification to explicitly identify the caveat mentioned in the last comment.

> The baggage API does not require a user to access the context keys that baggage are stored with, in fact, they are inaccessible to the user. This section appears not-applicable to our implementation as we choose to implement based on the option outlined in the Overview: "Depending on language idioms, a language API MAY implement these functions by providing the defined functionality interacting purely via the Context."
> 
> Extracting and inserting are not functionality reasonable for an implementation that interact purely via the Context.

**Comment by MrAlias** [comment]
### [Propagation](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/baggage/api.md#propagation)

> `Baggage` MAY be propagated across process boundaries or across any arbitrary boundaries (process, $OTHER_BOUNDARY1, $OTHER_BOUNDARY2, etc) for various reasons.

Indeed it can if the [`propagator.Baggage`](https://github.com/open-telemetry/opentelemetry-go/blob/bb4c297eb36f6af082bfa1d3216d33bd90da05f0/propagation/baggage.go#L28-L32) `TextMapPropagator` is configured.

> The API layer or an extension package MUST include the following `Propagator`s:
>
> * A `TextMapPropagator` implementing the [W3C Baggage Specification](https://w3c.github.io/baggage).

https://github.com/open-telemetry/opentelemetry-go/blob/bb4c297eb36f6af082bfa1d3216d33bd90da05f0/propagation/baggage.go#L28-L34

> If the propagator is unable to parse the incoming `baggage`, `extract` MUST return a `Context` with no baggage entries in it.
> If the incoming `baggage` is present, but contains no entries, `extract` MUST return a `Context` with no baggage entries in it.

This is not done currently, tracking with [this issue](https://github.com/open-telemetry/opentelemetry-go/issues/1685)

**Comment by MrAlias** [comment]
### [Conflict Resolution](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/baggage/api.md#conflict-resolution)

> If a new name/value pair is added and its name is the same as an existing name, than the new pair MUST take precedence.
> The value is replaced with the added value (regardless if it is locally generated or received from a remote peer).

The same as stated when reviewing the overview section, this is implemented by relying on the internal Go map having exactly one key associated with one value:

https://github.com/open-telemetry/opentelemetry-go/blob/90bd4ab50c6e85743f2b8f3a1768a5afceeb1fc0/internal/baggage/baggage.go#L90-L93

Any update of an existing key will overwrite the value.

**Comment by MrAlias** [comment]
### Spec-compliance-matrix

| Feature                            | Go |
|------------------------------------|----|
| Basic support                      | + sure, not sure what this means but we implement the specification based on our audit |
| Use official header name `baggage` | [+](https://github.com/open-telemetry/opentelemetry-go/blob/bb4c297eb36f6af082bfa1d3216d33bd90da05f0/propagation/baggage.go#L26)   |
