### ISSUE TITLE
Add circle-ci build

### ISSUE THREAD

**Issue by rghetia** [open-telemetry/opentelemetry-go#16]

**Comment by freeformz** [comment]
I don't want to be contrarian, but how about CircleCI?

https://twitter.com/carmatrocity/status/1098575963032408065

**Comment by pjanotti** [comment]
OC Go repos have been using Travis but that's just a legacy/convenience that can get us up and running fast. It should be easy enough to migrate if we have a compelling reason to do so.

**Comment by thinkerou** [comment]
maybe we should add ci first, and add some unit test case step by step.
