### ISSUE TITLE
Spec Conformance Review: Context Propagation/Context

### ISSUE THREAD

**Issue by Aneurysm9** [open-telemetry/opentelemetry-go#1600]
- [x] Review the [Context](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/context/context.md) API specification and identify all normative requirements it contains.
- [x] Validate our implementation of the specification to conform or not. If it conforms, document the conformity here. If it does not open an Issue or PR track the work.
- [x] Review the `Context Propagation` section of the [Spec Compliance Matrix](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md).
- [x] If there are any items listed in matrix that are not required by the specification, need clarification, or are in conflict with the specification open a PR in the specification to correct it.
- [x] Update the matrix with the current state of Go (existing entries for Go should be ignored). If Go does not provide support for an item listed be sure to link to the Issue/PR tracking the work to support it.

**Comment by MrAlias** [comment]
### [Context](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/context/context.md)

> A `Context` MUST be immutable, and its write operations MUST result in the creation of a new `Context` containing the original values and the specified values updated.
> Languages are expected to use the single, widely used `Context` implementation if one exists for them.
> In the cases where an extremely clear, pre-existing option is not available, OpenTelemetry MUST provide its own `Context` implementation.

The [Golang context.Context](https://golang.org/pkg/context/) is used as the project context. It operates as required.

> Depending on the language, its usage may be either explicit or implicit.
> Users writing instrumentation in languages that use `Context` implicitly are discouraged from using the `Context` API directly.
> In those cases, users will manipulate `Context` through cross-cutting concerns APIs instead, in order to perform operations such as setting trace or baggage entries for a specified `Context`.

The Go implementation uses [context.Context](https://golang.org/pkg/context/) as an explicit context. No implicit context is used.

> ## Create a key
>
> Keys are used to allow cross-cutting concerns to control access to their local state.
> They are unique such that other libraries which may use the same context cannot accidentally use the same key.
> It is recommended that concerns mediate data access via an API, rather than provide direct public access to their keys.
>
> The API MUST accept the following parameter:
>
> - The key name.
>   The key name exists for debugging purposes and does not uniquely identify the key.
>   Multiple calls to `CreateKey` with the same name SHOULD NOT return the same value unless language constraints dictate otherwise.
>   Different languages may impose different restrictions on the expected types, so this parameter remains an implementation detail.
>
> The API MUST return an opaque object representing the newly created key.

The Go Context uses `interface{}` types as keys. These are opaque key types that are created using the Go language. Scoping and naming the key is supported by the Go language implementation used.

> ## Get value
>
> Concerns can access their local state in the current execution state represented by a `Context`.
>
> The API MUST accept the following parameters:
>
> - The `Context`.
> - The key.
>
> The API MUST return the value in the `Context` for the specified key.

The Go [Context.Value](https://pkg.go.dev/context#Context) method satisfies this.

> ## Set value
>
> Concerns can record their local state in the current execution state represented by a `Context`.
>
> The API MUST accept the following parameters:
>
> - The `Context`.
> - The key.
> - The value to be set.
>
> The API MUST return a new `Context` containing the new value.

[context.WithValue](https://pkg.go.dev/context#WithValue) satisfies this.

> ## Optional Global operations
>
> These operations are expected to only be implemented by languages using `Context` implicitly, and thus are optional.

The Go project does not implement any of these as it uses explicit context.

**Comment by MrAlias** [comment]
I'm not entirely sure if we need to ensure the Go context package implements the specified API given this line:

> Languages are expected to use the single, widely used `Context` implementation if one exists for them.
> In the cases where an extremely clear, pre-existing option is not available, OpenTelemetry MUST provide its own `Context` implementation.

It seems this can be interpreted as: use the standard context and if one doesn't exist build an API that satisfies the following.

**Comment by MrAlias** [comment]
### [spec-compliance-matrix](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md#context-propagation)

| Feature                | Go  |
|------------------------|-----|
| Create Context Key     | + keys are Go interfaces; e.g. `interface{}(name)` |
| Get value from Context | + [Context.Value](https://pkg.go.dev/context#Context)  |
| Set value for Context  | + [context.WithValue](https://pkg.go.dev/context#WithValue) |
| Attach Context         | N/A (no implicit context) |
| Detach Context         | N/A (no implicit context) |
| Get current Context    | N/A (no implicit context) |
