### ISSUE TITLE
Spec Conformance Review: Environment Variables

### ISSUE THREAD

**Issue by Aneurysm9** [open-telemetry/opentelemetry-go#1602]
- [x] Review the [OpenTelemetry Environment Variable Specification](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/sdk-environment-variables.md) and identify all normative requirements it contains.
- [x] Validate our implementation of the specification to conform or not. If it conforms, document the conformity here. If it does not open an Issue or PR track the work.
- [x] Review the `Environment Variables` section of the [Spec Compliance Matrix](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md#environment-variables).
- [x] If there are any items listed in matrix that are not required by the specification, need clarification, or are in conflict with the specification open a PR in the specification to correct it.
- [x] Update the matrix with the current state of Go (existing entries for Go should be ignored). If Go does not provide support for an item listed be sure to link to the Issue/PR tracking the work to support it.

**Comment by MrAlias** [comment]
> SDKs MAY choose to allow configuration via the environment variables in this specification, but are not required to.
> If they do, they SHOULD use the names listed in this document.

We do not support this type of configuration. To accelerate our release of RC1 we should postpone this. Tracking [here](https://github.com/open-telemetry/opentelemetry-go/issues/1698).

> ## OTLP Exporter
>
> See [OpenTelemetry Protocol Exporter Configuration Options](./protocol/exporter.md).

This is required and tracked [here](https://github.com/open-telemetry/opentelemetry-go/issues/1085)
