### ISSUE TITLE
Spec Conformance Review: Exporters/OTLP

### ISSUE THREAD

**Issue by Aneurysm9** [open-telemetry/opentelemetry-go#1603]
- [ ] Review the [OpenTelemetry Protocol Exporter](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/protocol/otlp.md) specification and identify all normative requirements it contains.
- [ ] Validate our implementation of the specification to conform or not. If it conforms, document the conformity here. If it does not open an Issue or PR track the work.
- [ ] Review the `Exporters/OTLP` section of the [Spec Compliance Matrix](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md).
- [ ] If there are any items listed in matrix that are not required by the specification, need clarification, or are in conflict with the specification open a PR in the specification to correct it.
- [ ] Update the matrix with the current state of Go (existing entries for Go should be ignored). If Go does not provide support for an item listed be sure to link to the Issue/PR tracking the work to support it.

**Comment by MadVikingGod** [comment]
Feature | Optional | Go
-- | -- | --
OTLP |   |  
OTLP/gRPC Exporter | * | ?
OTLP/HTTP binary Protobuf Exporter | * | ?
OTLP/HTTP JSON Protobuf Exporter | * | ?
OTLP/HTTP gzip Content-Encoding support | X | ?
Concurrent sending |   | ?
Honors retryable responses with backoff | X | ?
Honors non-retryable responses | X | ?
Honors throttling response | X | ?
Multi-destination spec compliance | X | ?

\* For each type of exporter, OTLP, Zipkin, and Jaeger, implementing at least one of the supported formats is required. Implementing more than one formats is optional.

**Comment by MadVikingGod** [comment]
So a bit on the concurrent sending:
My reading of the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md#otlpgrpc-concurrent-requests) says that Implementing concurrent requests is optional, recommended.  It also goes into detail about how it should be configurable.  So I was going to capture those here:

Feature | Optional | Go
-- | -- | --
| Concurrent sending                        | X | + (if sdk manages concurrent calls)
| Max concurrent request configurable | X | ?
| Configurable fast/slow shutdown | X | ?
| Reporting of failed requests | X | ?

The shutdown should wait for all inflight requests to be acknowledged before shutting down, this should be able to be disabled.

**Comment by MadVikingGod** [comment]
Update:
Feature | Optional | Go
-- | -- | --
| OTLP                                      |   |  
| OTLP/gRPC Exporter                        | * | [+](https://github.com/open-telemetry/opentelemetry-go/blob/e25503a00edef6baf2b3deb1a5884d4501e08dcf/exporters/otlp/otlpgrpc/driver.go#L49)
| OTLP/HTTP binary Protobuf Exporter        | * | [+](https://github.com/open-telemetry/opentelemetry-go/blob/e25503a00edef6baf2b3deb1a5884d4501e08dcf/exporters/otlp/otlphttp/driver.go#L70)
| OTLP/HTTP JSON Protobuf Exporter          | * | [-](https://github.com/open-telemetry/opentelemetry-go/pull/1586)
| OTLP/HTTP gzip Content-Encoding support   | X | [+](https://github.com/open-telemetry/opentelemetry-go/blob/e25503a00edef6baf2b3deb1a5884d4501e08dcf/exporters/otlp/otlphttp/options.go#L99)
| Concurrent sending                        | X | - 
| - Max concurrent request configurable | X | -
| - Configurable fast/slow shutdown | X | -
| - Reporting of failed concurrent requests | X | -
| Honors retryable responses with backoff   |   | [-](https://github.com/open-telemetry/opentelemetry-go/issues/1632)
| Honors non-retryable responses            |   | [-](https://github.com/open-telemetry/opentelemetry-go/issues/1632)
| Honors throttling response                | X | [-](https://github.com/open-telemetry/opentelemetry-go/issues/1632)
| Multi-destination spec compliance         | X | +
| - Per-destination Queues               | X | +
| - Shared Immutable References | X | ?

High level.  The only non-compliant feature is Retries, tracked in #1632
Still need to create a PR with spec to update the matrix.

**Comment by MrAlias** [comment]
Can this be closed now that [this](https://github.com/open-telemetry/opentelemetry-specification/pull/1585) has been resolved?

**Comment by MadVikingGod** [comment]
Yup.
