### ISSUE TITLE
Spec Conformance Review: Exporters/Zipkin

### ISSUE THREAD

**Issue by Aneurysm9** [open-telemetry/opentelemetry-go#1604]
- [x] Review the [OpenTelemetry to Zipkin Transformation](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/sdk_exporters/zipkin.md) and identify all normative requirements it contains.
- [x] Validate our implementation of the specification to conform or not. If it conforms, document the conformity here. If it does not open an Issue or PR track the work.
- [x] Review the `Exporters/Zipkin` section of the [Spec Compliance Matrix](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md).
- [x] If there are any items listed in matrix that are not required by the specification, need clarification, or are in conflict with the specification open a PR in the specification to correct it.
- [x] Update the matrix with the current state of Go (existing entries for Go should be ignored). If Go does not provide support for an item listed be sure to link to the Issue/PR tracking the work to support it.

**Comment by MadVikingGod** [comment]
| Feature | Optional | Go
| -- | -- | --
| [Zipkin](specification/trace/sdk_exporters/zipkin.md) |          |   
| Zipkin V1 JSON                                        | X        | ? 
| Zipkin V1 Thrift                                      | X        | ? 
| Zipkin V2 JSON                                        | *        | ? 
| Zipkin V2 Protobuf                                    | *        | ? 
| Service name mapping                                  |          | ? 
| SpanKind mapping                                      |          | ? 
| InstrumentationLibrary mapping                        |          | ? 
| Boolean attributes                                    |          | ? 
| Array attributes                                      |          | ? 
| Status mapping                                        |          | ? 
| Error Status mapping                                  |          | ? 
| Event attributes mapping to Annotations               |          | ? 
| Integer microseconds in timestamps                    |          | ? 

\* For each type of exporter, OTLP, Zipkin, and Jaeger, implementing at least one of the supported formats is required. Implementing more than one formats is optional.

**Comment by MrAlias** [comment]
### [Service name](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/sdk_exporters/zipkin.md#service-name)

> Zipkin service name MUST be set to the value of the [resource attribute](../../resource/semantic_conventions/README.md): `service.name`.
> If no `service.name` is contained in a Span's Resource, it MUST be populated from the [default](../../resource/sdk.md#sdk-provided-resource-attributes) `Resource`.

https://github.com/open-telemetry/opentelemetry-go/blob/e9aaa04b8f88b0f8158bd27f72e57d33878f5bdd/exporters/trace/zipkin/model.go#L43-L52

We set the service name from the resource, but we default to `""` instead of from the default resource. While the resource passed to with the span data should include the default resource attributes we need to explicitly default to this value.

Tracking with https://github.com/open-telemetry/opentelemetry-go/issues/1777

> In Zipkin it is important that the service name is consistent for all spans in a local root.
> Otherwise service graph and aggregations would not work properly.
> OpenTelemetry doesn't provide this consistency guarantee.
> Exporter may chose to override the value for service name based on a local root span to improve Zipkin user experience.

We do not currently do this. It is not a requirement, so not going to add this as a task.

> *Note*, the attribute `service.namespace` MUST NOT be used for the Zipkin service name and should be sent as a Zipkin tag.

This is not used.

**Comment by MrAlias** [comment]
### [SpanKind](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/sdk_exporters/zipkin.md#spankind)

> The following table lists all the `SpanKind` mappings between OpenTelemetry and Zipkin.
>
> | OpenTelemetry | Zipkin | Note |
> | ------------- | ------ | ---- |
> | `SpanKind.CLIENT`|`SpanKind.CLIENT`||
> | `SpanKind.SERVER`|`SpanKind.SERVER`||
> | `SpanKind.CONSUMER`|`SpanKind.CONSUMER`||
> | `SpanKind.PRODUCER`|`SpanKind.PRODUCER` ||
> | `SpanKind.INTERNAL`|`null` |must be omitted (set to `null`)|

The underlying type in the Zipkin span model for the span kind is `string`. This means the that we have interpreted `null` mapping for the `SpanKind.INTERNAL` as `""` or [`Undetermined`](https://github.com/openzipkin/zipkin-go/blob/815bc64e1a6031d5a51c88b07092d34c20aaeb61/model/kind.go#L22) in the model. Otherwise, our mapping straightforwardly follows this:

https://github.com/open-telemetry/opentelemetry-go/blob/e9aaa04b8f88b0f8158bd27f72e57d33878f5bdd/exporters/trace/zipkin/model.go#L101-L119

**Comment by MrAlias** [comment]
### [InstrumentationLibrary](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/sdk_exporters/zipkin.md#instrumentationlibrary)

> OpenTelemetry Span's `InstrumentationLibrary` MUST be reported as `tags` to Zipkin using the following mapping.

This is how we report this information:

https://github.com/open-telemetry/opentelemetry-go/blob/e9aaa04b8f88b0f8158bd27f72e57d33878f5bdd/exporters/trace/zipkin/model.go#L171-L176

> | OpenTelemetry | Zipkin
> | ------------- | ------ |
> | `InstrumentationLibrary.name`|`otel.library.name`|
> | `InstrumentationLibrary.version`|`otel.library.version`|

Currently we do not use these

https://github.com/open-telemetry/opentelemetry-go/blob/e9aaa04b8f88b0f8158bd27f72e57d33878f5bdd/exporters/trace/zipkin/model.go#L30-L33

But, they are being addressed in https://github.com/open-telemetry/opentelemetry-go/pull/1688

**Comment by MrAlias** [comment]
#### [OTLP -> Zipkin](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/sdk_exporters/zipkin.md#otlp---zipkin)

> If Zipkin `SpanKind` resolves to either `SpanKind.CLIENT` or `SpanKind.PRODUCER` then the service SHOULD specify remote endpoint otherwise Zipkin won't treat the Span as a dependency.
> `peer.service` is the preferred attribute but is not always available.
> The following table lists the possible attributes for `remoteEndpoint` by preferred ranking:
>
> |Rank|Attribute Name|Reason|
> |---|---|---|
> |1|peer.service|[OpenTelemetry adopted attribute for remote service.](../semantic_conventions/span-general.md#general-remote-service-attributes)|
> |2|net.peer.name|[OpenTelemetry adopted attribute for remote hostname, or similar.](../semantic_conventions/span-general.md#general-network-connection-attributes)|
> |3|net.peer.ip & net.peer.port|[OpenTelemetry adopted attribute for remote address of the peer.](../semantic_conventions/span-general.md#general-network-connection-attributes)|
> |4|peer.hostname|Remote hostname defined in OpenTracing specification.|
> |5|peer.address|Remote address defined in OpenTracing specification.|
> |6|http.host|Commonly used HTTP host header attribute for Http Spans.|
> |7|db.name|Commonly used database name attribute for DB Spans.|
>
> * Ranking should control the selection order.
>   For example, `net.peer.name` (Rank 2) should be selected before `http.host` (Rank 6).
> * `net.peer.ip` can be used by itself as `remoteEndpoint` but should be combined with `net.peer.port` if it is also present.

Being addressed in https://github.com/open-telemetry/opentelemetry-go/pull/1688

**Comment by MrAlias** [comment]
### [Attribute](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/sdk_exporters/zipkin.md#attribute)

> OpenTelemetry Span `Attribute`(s) MUST be reported as `tags` to Zipkin.

This is how we map them:

https://github.com/open-telemetry/opentelemetry-go/blob/e9aaa04b8f88b0f8158bd27f72e57d33878f5bdd/exporters/trace/zipkin/model.go#L162-L164

> Some attributes defined in semantic convention document maps to the strongly-typed fields of Zipkin spans.
>
> Primitive types MUST be converted to string using en-US culture settings.
> Boolean values MUST use lower case strings `"true"` and `"false"`.

The `"attributes".Value.Emit` method is used to conform with this:

https://github.com/open-telemetry/opentelemetry-go/blob/e9aaa04b8f88b0f8158bd27f72e57d33878f5bdd/attribute/value.go#L177-L193

> Array values MUST be serialized to string like a JSON list as mentioned in [semantic conventions](../../overview.md#semantic-conventions).

This is not done, but is being addressed in https://github.com/open-telemetry/opentelemetry-go/pull/1688

**Comment by MrAlias** [comment]
### [Status](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/sdk_exporters/zipkin.md#status)

> Span `Status` MUST be reported as a key-value pair in `tags` to Zipkin, unless it is `UNSET`.
> In the latter case it MUST NOT be reported.

We do not filter out the `UNSET` status:

https://github.com/open-telemetry/opentelemetry-go/blob/e9aaa04b8f88b0f8158bd27f72e57d33878f5bdd/exporters/trace/zipkin/model.go#L168

Being addressed in https://github.com/open-telemetry/opentelemetry-go/pull/1688

> The following table defines the OpenTelemetry `Status` to Zipkin `tags` mapping.
>
> | Status|Tag Key| Tag Value |
> |--|--|--|
> |Code | `otel.status_code` | Name of the code, either `OK` or `ERROR`. MUST NOT be set if the code is `UNSET`. |
> |Description| `error` | Description of the `Status`. MUST be set if the code is `ERROR`, use an empty string if Description has no value. MUST NOT be set for `OK` and `UNSET` codes. |
>
> Note: The `error` tag should only be set if `Status` is `Error`.
> If a boolean version (`{"error":false}` or `{"error":"false"}`) is present, it SHOULD be removed.
> Zipkin will treat any span with `error` sent as failed.

Not implemented correctly, but being addressed in https://github.com/open-telemetry/opentelemetry-go/pull/1688

**Comment by MrAlias** [comment]
### [Events](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/sdk_exporters/zipkin.md#events)

> OpenTelemetry `Event` has an optional `Attribute`(s) which is not supported by Zipkin.
> Events MUST be converted to the Annotations with the names which will include attribute values like this:
>
> ```
> "my-event-name": { "key1" : "value1", "key2": "value2" }
> ```

This is how we map these values:

https://github.com/open-telemetry/opentelemetry-go/blob/e9aaa04b8f88b0f8158bd27f72e57d33878f5bdd/exporters/trace/zipkin/model.go#L121-L150

**Comment by MrAlias** [comment]
### [Unit of Time](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/sdk_exporters/zipkin.md#unit-of-time)

> Zipkin times like `timestamp`, `duration` and `annotation.timestamp` MUST be reported in microseconds as whole numbers.
> For example, `duration` of 1234 nanoseconds will be represented as 1 microsecond.

The Go Zipkin model uses `time.Time` and `time.Duration` to represent time. Meaning, our mapping (from the same type) is just to pass these types. The specification does not appear applicable here.

**Comment by MrAlias** [comment]
## [Request Payload](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/sdk_exporters/zipkin.md#request-payload)

> For performance considerations, Zipkin fields that can be absent SHOULD be omitted from the payload when they are empty in the OpenTelemetry `Span`.
>
> For example, an OpenTelemetry `Span` without any `Event` should not have an `annotations` field in the Zipkin payload.

We do this for events:

https://github.com/open-telemetry/opentelemetry-go/blob/e9aaa04b8f88b0f8158bd27f72e57d33878f5bdd/exporters/trace/zipkin/model.go#L122-L124

https://github.com/open-telemetry/opentelemetry-go/pull/1688 will also do this for tags:

https://github.com/open-telemetry/opentelemetry-go/pull/1688/files#diff-655880b4017f8eb43d67420fad745dba9673714e963b4c51e40df3bde316647eR187

**Comment by MrAlias** [comment]
| Feature | Optional | Go |
| -- | -- | -- |
| Zipkin V1 JSON                                        | X        | -  |
| Zipkin V1 Thrift                                      | X        | -  |
| Zipkin V2 JSON                                        | *        | +  |
| Zipkin V2 Protobuf                                    | *        | -  |
| Service name mapping                                  |          | [-](https://github.com/open-telemetry/opentelemetry-go/issues/1777)  |
| SpanKind mapping                                      |          | +  |
| InstrumentationLibrary mapping                        |          | [-](https://github.com/open-telemetry/opentelemetry-go/pull/1688)  |
| Boolean attributes                                    |          | +  |
| Array attributes                                      |          | [-](https://github.com/open-telemetry/opentelemetry-go/pull/1688)  |
| Status mapping                                        |          | [-](https://github.com/open-telemetry/opentelemetry-go/pull/1688)  |
| Error Status mapping                                  |          | [-](https://github.com/open-telemetry/opentelemetry-go/pull/1688)  |
| Event attributes mapping to Annotations               |          | +  |
| Integer microseconds in timestamps                    |          | N/A  |
