### ISSUE TITLE
Spec Conformance Review: Exporters/Jaeger

### ISSUE THREAD

**Issue by Aneurysm9** [open-telemetry/opentelemetry-go#1605]
- [x] Review the [OpenTelemetry to Jaeger Transformation](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/sdk_exporters/jaeger.md) and identify all normative requirements it contains.
- [x] Validate our implementation of the specification to conform or not. If it conforms, document the conformity here. If it does not open an Issue or PR track the work.
- [x] Review the `Exporters/Jaeger` section of the [Spec Compliance Matrix](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md).
- [x] If there are any items listed in matrix that are not required by the specification, need clarification, or are in conflict with the specification open a PR in the specification to correct it.
- [x] Update the matrix with the current state of Go (existing entries for Go should be ignored). If Go does not provide support for an item listed be sure to link to the Issue/PR tracking the work to support it.

**Comment by MadVikingGod** [comment]
| Feature | Optional | Go
| -- | -- | --
| [Jaeger](specification/trace/sdk_exporters/jaeger.md) |          |  
| Jaeger Thrift over UDP                                | *        | ? 
| Jaeger Protobuf via gRPC                              | *        | ? 
| Jaeger Thrift over HTTP                               | *        | ? 
| Service name mapping                                  |          | ? 
| Resource to Process mapping                           |          | ? 
| InstrumentationLibrary mapping                        |          | ? 
| Status mapping                                        |          | ? 
| Error Status mapping                                  |          | ? 
| Events converted to Logs                              |          | ? 

\* For each type of exporter, OTLP, Zipkin, and Jaeger, implementing at least one of the supported formats is required. Implementing more than one formats is optional.

**Comment by MrAlias** [comment]
https://github.com/open-telemetry/opentelemetry-go/issues/1639

**Comment by MrAlias** [comment]
### [Resource mapping](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/sdk_exporters/jaeger.md#resource)

> OpenTelemetry resources MUST be mapped to Jaeger's `Span.Process` tags.
> Multiple resources can exist for a single process and exporters need to handle this case accordingly.
>
> Critically, Jaeger backend depends on `Span.Process.ServiceName` to identify the service that produced the spans.
> That field MUST be populated from the `service.name` attribute of the [`service` resource](../../resource/semantic_conventions/README.md#service).
> If no `service.name` is contained in a Span's Resource, that field MUST be populated from the [default](../../resource/sdk.md#sdk-provided-resource-attributes) `Resource`.

Currently, the Jaeger exporter does map resource attributes to Jaeger tags that are store in a process:

https://github.com/open-telemetry/opentelemetry-go/blob/bf180d0fd21fe95662781ecd9a0e835a08de8f0f/exporters/trace/jaeger/jaeger.go#L458-L484

The service name set is a bit complex. It will by default use the `Default` resource:

https://github.com/open-telemetry/opentelemetry-go/blob/bf180d0fd21fe95662781ecd9a0e835a08de8f0f/exporters/trace/jaeger/jaeger.go#L106-L114

But, if the user specifies a `Process` in the configuration provided to the exporter, it will the service name specified there:

https://github.com/open-telemetry/opentelemetry-go/blob/bf180d0fd21fe95662781ecd9a0e835a08de8f0f/exporters/trace/jaeger/jaeger.go#L120

https://github.com/open-telemetry/opentelemetry-go/blob/bf180d0fd21fe95662781ecd9a0e835a08de8f0f/exporters/trace/jaeger/jaeger.go#L486-L490

And this will take precedent over any existing service name in the SDK configured `Resource`. This means our implementation is not compliant as it can default to things other than the default resource service name.

**Comment by MrAlias** [comment]
### [Instrumentation library mapping](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/sdk_exporters/jaeger.md#instrumentationlibrary)

> OpenTelemetry Span's `InstrumentationLibrary` MUST be reported as span `tags` to Jaeger using the following mapping.
>
> | OpenTelemetry | Jaeger |
> | ------------- | ------ |
> | `InstrumentationLibrary.name`|`otel.library.name`|
> | `InstrumentationLibrary.version`|`otel.library.version`|

We use the following keys:

https://github.com/open-telemetry/opentelemetry-go/blob/97501a3fee7647a3a14b6d4429d814ffb17c2a67/exporters/trace/jaeger/jaeger.go#L37-L40

and map them according to the specification:

https://github.com/open-telemetry/opentelemetry-go/blob/97501a3fee7647a3a14b6d4429d814ffb17c2a67/exporters/trace/jaeger/jaeger.go#L263-L268

**Comment by MrAlias** [comment]
### [IDs mapping](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/sdk_exporters/jaeger.md#ids)

> Trace and span IDs in Jaeger are random sequences of bytes.
> However, Thrft model represents IDs using `i64` type, or in case of a 128-bit wide Trace ID as two `i64` fields `traceIdLow` and `traceIdHigh`.
> The bytes MUST be converted to/from unsigned ints using Big Endian byte order, e.g. `[0x10, 0x00, 0x00, 0x00] == 268435456`.
> The unsigned ints MUST be converted to `i64` by re-interpreting the existing 64bit value as signed `i64`.
>
> For example (in Go):
>
> ```go
> var (
>     id       []byte = []byte{0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
>     unsigned uint64 = binary.BigEndian.Uint64(id)
>     signed   int64  = int64(unsigned)
> )
> fmt.Println("unsigned:", unsigned)
k> fmt.Println("  signed:", signed)
> // Output:
> // unsigned: 18374686479671623680
> //   signed: -72057594037927936
> ```

This is how we convert trace and span IDs for both links:

https://github.com/open-telemetry/opentelemetry-go/blob/97501a3fee7647a3a14b6d4429d814ffb17c2a67/exporters/trace/jaeger/jaeger.go#L308-L310

and the span itself:

https://github.com/open-telemetry/opentelemetry-go/blob/97501a3fee7647a3a14b6d4429d814ffb17c2a67/exporters/trace/jaeger/jaeger.go#L319-L321

**Comment by MrAlias** [comment]
### [Parent Span ID mapping](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/sdk_exporters/jaeger.md#parent-id)

> Jaeger Thrift format allows capturing parent ID in a top-level Span field.
> Jaeger Proto format does not support parent ID field; instead the parent MUST be recorded as a `SpanReference` of type `CHILD_OF`, e.g.:
>
> ```python
>     SpanReference(
>         ref_type=opentracing.CHILD_OF,
>         trace_id=span.context.trace_id,
>         span_id=parent_id,
>     )
> ```
>
> This span reference MUST be the first in the list of references.

We only support the thrift format currently, and we set the parent span ID in the top-level Span field:

https://github.com/open-telemetry/opentelemetry-go/blob/97501a3fee7647a3a14b6d4429d814ffb17c2a67/exporters/trace/jaeger/jaeger.go#L322

**Comment by MrAlias** [comment]
### [SpanKind mapping](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/sdk_exporters/jaeger.md#spankind)

> OpenTelemetry `SpanKind` field MUST be encoded as `span.kind` tag in Jaeger span, except for `SpanKind.INTERNAL`, which SHOULD NOT be translated to a tag.
>
> | OpenTelemetry | Jaeger |
> | ------------- | ------ |
> | `SpanKind.CLIENT`|`"client"`|
> | `SpanKind.SERVER`|`"server"`|
> | `SpanKind.CONSUMER`|`"consumer"`|
> | `SpanKind.PRODUCER`|`"producer"` |
> | `SpanKind.INTERNAL`| do not add `span.kind` tag |

We only add the span kind if it is not `SpanKind.INTERNAL`:

https://github.com/open-telemetry/opentelemetry-go/blob/97501a3fee7647a3a14b6d4429d814ffb17c2a67/exporters/trace/jaeger/jaeger.go#L270-L274

And we store with the correct key (^) and values:

https://github.com/open-telemetry/opentelemetry-go/blob/97501a3fee7647a3a14b6d4429d814ffb17c2a67/trace/trace.go#L620-L627

**Comment by MrAlias** [comment]
### [Unit of time mapping](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/sdk_exporters/jaeger.md#unit-of-time)

> In Jaeger Thrift format the timestamps and durations MUST be represented in microseconds (since epoch for timestamps).
> If the original value in OpenTelemetry is expressed in nanoseconds, it MUST be rounded or truncated to microseconds.
>
> In Jaeger Proto format the timestamps and durations MUST be represented with nanosecond precision using `google.protobuf.Timestamp` and `google.protobuf.Duration` types.

We only support the thrift format currently, and we set timestamps and durations appropriately:

https://github.com/open-telemetry/opentelemetry-go/blob/97501a3fee7647a3a14b6d4429d814ffb17c2a67/exporters/trace/jaeger/jaeger.go#L298

https://github.com/open-telemetry/opentelemetry-go/blob/97501a3fee7647a3a14b6d4429d814ffb17c2a67/exporters/trace/jaeger/jaeger.go#L325

https://github.com/open-telemetry/opentelemetry-go/blob/97501a3fee7647a3a14b6d4429d814ffb17c2a67/exporters/trace/jaeger/jaeger.go#L326

**Comment by MrAlias** [comment]
### [Status mapping](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/sdk_exporters/jaeger.md#status)

> Span `Status` MUST be reported as a key-value pair in `tags` to Jaeger, unless it is `UNSET`.
> In the latter case it MUST NOT be reported.
>
> The following table defines the OpenTelemetry `Status` to Jaeger `tags` mapping.
>
> | Status|Tag Key| Tag Value |
> |--|--|--|
> |Code | `otel.status_code` | Name of the code, either `OK` or `ERROR`. MUST NOT be set if the code is `UNSET`. |
> |Description | `otel.status_description` | Description of the `Status` if it has a value otherwise not set. |

We do not currently conform to the specification:

https://github.com/open-telemetry/opentelemetry-go/blob/97501a3fee7647a3a14b6d4429d814ffb17c2a67/exporters/trace/jaeger/jaeger.go#L276-L285

Tracking here: https://github.com/open-telemetry/opentelemetry-go/issues/1376#issuecomment-811449690

**Comment by MrAlias** [comment]
### [Error flag mapping](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/sdk_exporters/jaeger.md#error-flag)

> When Span `Status` is set to `ERROR`, an `error` span tag MUST be added with the Boolean value of `true`.
> The added `error` tag MAY override any previous value.

We do this:

https://github.com/open-telemetry/opentelemetry-go/blob/97501a3fee7647a3a14b6d4429d814ffb17c2a67/exporters/trace/jaeger/jaeger.go#L282-L284

**Comment by MrAlias** [comment]
### [Attributes mapping](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/sdk_exporters/jaeger.md#attributes)

> OpenTelemetry Span `Attribute`(s) MUST be reported as `tags` to Jaeger.

https://github.com/open-telemetry/opentelemetry-go/blob/97501a3fee7647a3a14b6d4429d814ffb17c2a67/exporters/trace/jaeger/jaeger.go#L255-L261

> Primitive types MUST be represented by the corresponding types of Jaeger tags.
> Array values MUST be serialized to string like a JSON list as mentioned in [semantic conventions](../../overview.md#semantic-conventions).

We conform to this:

https://github.com/open-telemetry/opentelemetry-go/blob/97501a3fee7647a3a14b6d4429d814ffb17c2a67/exporters/trace/jaeger/jaeger.go#L333-L374

**Comment by MrAlias** [comment]
### [Links mapping](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/sdk_exporters/jaeger.md#links)

> OpenTelemetry `Link`(s) MUST be converted to `SpanReference`(s) in Jaeger, using `FOLLOWS_FROM` reference type.

This is the type we use:

https://github.com/open-telemetry/opentelemetry-go/blob/97501a3fee7647a3a14b6d4429d814ffb17c2a67/exporters/trace/jaeger/jaeger.go#L311

> The Link's attributes cannot be represented in Jaeger explicitly. The exporter MAY additionally convert `Link`(s) to span `Log`(s):
>
> * use Span start time as the timestamp of the Log
> * set Log tag `event=link`
> * set Log tags `trace_id` and `span_id` from the respective `SpanContext`'s fields
> * store `Link`'s attributes as Log tags

Currently, we do not implement this option.

> Span references generated from `Link`(s) MUST be added _after_ the span reference generated from [Parent ID](#parent-id), if any.

This does not apply to us, we only support thrift which has a dedicated field for parent span ID.

**Comment by MrAlias** [comment]
### [Events mapped](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/sdk_exporters/jaeger.md#events)

> Events MUST be converted to Jaeger Logs.

That is how we convert them:

https://github.com/open-telemetry/opentelemetry-go/blob/97501a3fee7647a3a14b6d4429d814ffb17c2a67/exporters/trace/jaeger/jaeger.go#L287-L301

> OpenTelemetry Event's `time_unix_nano` and `attributes` fields map directly to Jaeger Log's `timestamp` and `fields` fields.

https://github.com/open-telemetry/opentelemetry-go/blob/97501a3fee7647a3a14b6d4429d814ffb17c2a67/exporters/trace/jaeger/jaeger.go#L297-L300

> Jaeger Log has no direct equivalent for OpenTelemetry Event's `name` and `dropped_attributes_count` fields but OpenTracing semantic conventions specify some special attribute names [here](https://github.com/opentracing/specification/blob/master/semantic_conventions.md#log-fields-table).
> OpenTelemetry Event's `name` and `dropped_attributes_count` fields should be added to Jaeger Log's `fields` map as follows:
>
> | OpenTelemetry Event Field | Jaeger Attribute |
> | -------------------------- | ----------------- |
> | `name`|`event`|
> | `dropped_attributes_count`|`otel.event.dropped_attributes_count`|
>
> * `dropped_attributes_count` should only be recorded when it contains a non-zero value.

We do not record the `dropped_attributes_count`. This could potentially be interpreted as a normative recommendation so we should have an issue track this for after the RC.

> * If OpenTelemetry Event contains an attributes with the key `event`, it should take precedence over Event's `name` field.

We do not do this, the name takes precedence:

https://github.com/open-telemetry/opentelemetry-go/blob/97501a3fee7647a3a14b6d4429d814ffb17c2a67/exporters/trace/jaeger/jaeger.go#L296

This could potentially be interpreted as a normative recommendation so we should have an issue track this for after the RC.

**Comment by MrAlias** [comment]
https://github.com/open-telemetry/opentelemetry-go/issues/1766
https://github.com/open-telemetry/opentelemetry-go/issues/1767

**Comment by MrAlias** [comment]
| Feature | Optional | Go |
| -- | -- | -- |
| [Jaeger](specification/trace/sdk_exporters/jaeger.md) |          | Go |
| Jaeger Thrift over UDP                                | *        | [+](https://github.com/open-telemetry/opentelemetry-go/blob/97501a3fee7647a3a14b6d4429d814ffb17c2a67/exporters/trace/jaeger/uploader.go#L40-L66) |
| Jaeger Protobuf via gRPC                              | *        | -  |
| Jaeger Thrift over HTTP                               | *        | [+](https://github.com/open-telemetry/opentelemetry-go/blob/97501a3fee7647a3a14b6d4429d814ffb17c2a67/exporters/trace/jaeger/uploader.go#L95-L124)  |
| Service name mapping                                  |          | [-](https://github.com/open-telemetry/opentelemetry-go/issues/1762)  |
| Resource to Process mapping                           |          | [+](https://github.com/open-telemetry/opentelemetry-go/issues/1605#issuecomment-811394420) |
| InstrumentationLibrary mapping                        |          | [+](https://github.com/open-telemetry/opentelemetry-go/issues/1605#issuecomment-811396530) |
| Status mapping                                        |          | [+](https://github.com/open-telemetry/opentelemetry-go/issues/1605#issuecomment-811450103) with [this merged fix](https://github.com/open-telemetry/opentelemetry-go/pull/1761) |
| Error Status mapping                                  |          | [+](https://github.com/open-telemetry/opentelemetry-go/issues/1605#issuecomment-811464828) |
| Events converted to Logs                              |          | [+](https://github.com/open-telemetry/opentelemetry-go/issues/1605#issuecomment-811487220) |
