### ISSUE TITLE
Add ExportTimeout to BatchSpanProcessor

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#1613]
[The specification states](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#batching-processor) the BatchSpanProcessor needs to be configurable with a export timeout:

> exportTimeoutMillis - how long the export can run before it is cancelled. The default value is 30000.

Currently we do not set a timeout for this.

We should be able to acomplish this by adding a deadline to the context we pass to the `ExportSpans` method:

https://github.com/open-telemetry/opentelemetry-go/blob/e499ca86b7ef54b42f6dd684ccbf73f226af10bd/sdk/trace/batch_span_processor.go#L189

**Comment by matej-g** [comment]
Volunteering for this one :raising_hand:

**Comment by matej-g** [comment]
@MrAlias I might need a little hint on this one - is all that is required for the export timeout to create a child context with timeout and passing it over to `SpanExporter.ExportSpans` or does this task require doing something more in `exportSpans`?

I'm asking because according to the [documentation](https://github.com/open-telemetry/opentelemetry-go/blob/a9b2f85134dc918ff44969ff0b05fe3c5ac1a1f2/sdk/export/trace/trace.go#L34), `ExportSpans` _should_ honor the context:
```
// This function is called synchronously, so there is no concurrency
// safety requirement. However, due to the synchronous calling pattern,
// it is critical that all timeouts and cancellations contained in the
// passed context must be honored.
```
However, I'm not sure that this is the case for all exporters, looking at their code (e.g. Jaeger [exporter](https://github.com/open-telemetry/opentelemetry-go/blob/main/exporters/trace/jaeger/jaeger.go#L204-L205) does not seem to do anything with the passed context). Is this something that is still to-do on the part of exporter(s)?

**Comment by MrAlias** [comment]
> However, I'm not sure that this is the case for all exporters, looking at their code (e.g. Jaeger [exporter](https://github.com/open-telemetry/opentelemetry-go/blob/main/exporters/trace/jaeger/jaeger.go#L204-L205) does not seem to do anything with the passed context). Is this something that is still to-do on the part of exporter(s)?

This is a good question. I think there are two options as I see it: wait for the called exporter to return and hope it honors the deadline, or abandon a goroutine that the call could be made on and leak resources. In the shutdown situation I could see an users being okay with the second option, but in the _repeated_ hot path of exporting telemetry I do not think this can fly.

I think the resolution to this issue is to indeed create a child context with timeout set in configuration and passing it over to `SpanExporter.ExportSpans`. We then need to create issues to address any exporter we provide that does not honor the context timeout for the tracing signal.

**Comment by MrAlias** [comment]
Doing a quick audit of the trace exporters:

- The [`stdout`](https://github.com/open-telemetry/opentelemetry-go/blob/a9b2f85134dc918ff44969ff0b05fe3c5ac1a1f2/exporters/stdout/trace.go#L34-L52) exporter doesn't interact with the passed context, though I'm not sure it really needs to or can. I would not expect this exporter to be used in a production system outside of debugging and outside of abandoning a thread that made the syscall I don't think it is going to be possible to support the context cancellation here. That said maybe we could check that the context hasn't already ended before performing any work.
- The [`zipkin`](https://github.com/open-telemetry/opentelemetry-go/blob/a9b2f85134dc918ff44969ff0b05fe3c5ac1a1f2/exporters/trace/zipkin/zipkin.go#L157) exporter uses `http.NewRequestWithContext` to build the performed request. That will honor the passed timeout.
- The [`jaeger`](https://github.com/open-telemetry/opentelemetry-go/blob/a9b2f85134dc918ff44969ff0b05fe3c5ac1a1f2/exporters/trace/jaeger/jaeger.go#L215) exporter could be updated to use the [`AddWait`](https://pkg.go.dev/google.golang.org/api/support/bundler#Bundler.AddWait) of the bundler which in the situation where the bundler is waiting on memory to complete the operation will wait for the memory allocation or return based on the context deadline. However, the currently used `Add` method will return immediately instead. So if it is switched to `AddWait` it would be introducing a delay.
- The [http driver](https://github.com/open-telemetry/opentelemetry-go/blob/a9b2f85134dc918ff44969ff0b05fe3c5ac1a1f2/exporters/otlp/otlphttp/driver.go#L257) for the OTLP exporter also uses `http.NewRequestWithContext` to build the performed request.
- The [grpc driver](https://github.com/open-telemetry/opentelemetry-go/blob/a9b2f85134dc918ff44969ff0b05fe3c5ac1a1f2/exporters/otlp/otlpgrpc/driver.go#L151) users the [`grpc.ClientConn`](https://pkg.go.dev/google.golang.org/grpc#ClientConn) that is passed the context which should honor the timeout.

Based on this, I think the only change we may want to discuss is the Jaeger exporter. Switching to the `AddWait` might help prevent resource starvation on systems that have call rates for large exports. Using that method instead would result in deadline errors instead of the OOM system killing the process because it is pilling up bundles that are requesting endless memory. I do not think this is a decision we need to make at this point (it can be made post 1.0 release).

**Comment by matej-g** [comment]
Great, thanks for the detailed answer! I'll go ahead and file an issue for Jaeger. For this issue I'll keep the scope as agreed (add timeout to context).
