### ISSUE TITLE
SimpleSpanProcessor.Shutdown needs to be configurable with a timeout that it honors

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#1616]
[The specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#shutdown-1):

> Shutdown SHOULD complete or abort within some timeout.

The already passed context should be used to determine if the method should abort. Similar to the batch span processor:

https://github.com/open-telemetry/opentelemetry-go/blob/992837f195eacbd84f0596bfaa79470dba7408e5/sdk/trace/batch_span_processor.go#L126-L150

Tests will need to be added to verify the behavior and that an appropriate error is returned when the deadline is reached or the context canceled.

**Comment by veera83372** [comment]
@MrAlias  is it already being done by anyone or can i pick this up?

**Comment by MrAlias** [comment]
@veera83372 it has not, but I would wait for [this](https://github.com/open-telemetry/opentelemetry-go/pull/1612/files#diff-a2b65cf93ae462e0bd8332bb5d11b122479f45c0b8869258af2faefc9b145cbdR59-R74) to land prior to starting on something.

**Comment by veera83372** [comment]
@MrAlias  Can i pick this now?

**Comment by MrAlias** [comment]
@veera83372 :rocket:
