### ISSUE TITLE
BatchSpanProcessor must gracefully ignored `OnEnd`, `OnStart`, or `ForceFlush` post `Shutdown`

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#1617]
[The specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#shutdown-1):

> After the call to Shutdown, subsequent calls to OnStart, OnEnd, or ForceFlush are not allowed. SDKs SHOULD ignore these calls gracefully, if possible.

**Comment by cynthiakedu** [comment]
Can I pick up this issue?

**Comment by MrAlias** [comment]
I think this is done (#1772). Please reopen if not.
