### ISSUE TITLE
BatchSpanProcessor.ForceFlush aborts after configured timeout

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#1618]
[The specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#forceflush-1):

> ForceFlush SHOULD complete or abort within some timeout. ForceFlush can be implemented as a blocking API or an asynchronous API which notifies the caller via a callback or an event. OpenTelemetry client authors can decide if they want to make the flush timeout configurable.

**Comment by ijsong** [comment]
@MrAlias  `ForceFlush` of BatchSpanProcessor accepts `context.Context` as the first argument. It seems that users can set a deadline for it. 
Does `ForceFlush` need another way to timeout?

**Comment by MrAlias** [comment]
@ijsong no, the deadline in the context should be all that is needed. We just need to implement the abort functionality based on this. I.e. similar to the `Shutdown` method:

https://github.com/open-telemetry/opentelemetry-go/blob/345f264a137ed7162c30d14dd4739b5b72f76537/sdk/trace/batch_span_processor.go#L128-L144

**Comment by ijsong** [comment]
@MrAlias `ForceFlush` calls `(SpanExporter).ExportSpans`, and it should respect timeout and cancellation of context according to comments:

https://github.com/open-telemetry/opentelemetry-go/blob/345f264a137ed7162c30d14dd4739b5b72f76537/sdk/export/trace/trace.go#L31-L43 

It seems that `ForceFlush` must be stopped by either context cancellation or timeout without any other helper. The helper you linked also can make `ForceFlush` be timed out or canceled, but it must do even without the helper. Do you have plans to change the interface and implementation of `ExportSpans`?

**Comment by humivo** [comment]
I can try this one!
