### ISSUE TITLE
I can't find `label` folder

### ISSUE THREAD

**Issue by 99Kies** [open-telemetry/opentelemetry-go#1624]
![image](https://user-images.githubusercontent.com/45918704/109543840-c7129680-7b01-11eb-9110-59fb33ef7fda.png)
![image](https://user-images.githubusercontent.com/45918704/109544095-18bb2100-7b02-11eb-8ebe-601efe76f996.png)

I can't find `label` folder

**Comment by MrAlias** [comment]
The `label` package was renamed to `attribute`: https://github.com/open-telemetry/opentelemetry-go/pull/1541
