### ISSUE TITLE
Jaeger Exporter: Clarify how service name should be set for process

### ISSUE THREAD

**Issue by matej-g** [open-telemetry/opentelemetry-go#1625]
The [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/jaeger.md#resource) states that:

> Critically, Jaeger backend depends on `Span.Process.ServiceName` to identify the service
that produced the spans. That field MUST be populated from the `service.name` attribute
of the [`service` resource](../../resource/semantic_conventions/README.md#service).
If no `service.name` is contained in a Span's Resource, that field MUST be populated from the
[default](../../resource/sdk.md#sdk-provided-resource-attributes) `Resource`.

While it is not entirely clear to me what `Span.Process.ServiceName` represents, it seems that we are setting service name from the [`Process` struct ](https://github.com/open-telemetry/opentelemetry-go/blob/main/exporters/trace/jaeger/jaeger.go#L193) which is set via [`jaeger.WithProcess`](https://github.com/open-telemetry/opentelemetry-go/blob/e25503a00edef6baf2b3deb1a5884d4501e08dcf/exporters/trace/jaeger/jaeger.go#L60) during the exporter pipeline instantiation.

At the same time, the `service.name` tag on a span is being populated from the resource attribute.

The question is whether this is behavior adheres to the specification, or the service name should rather be set on the basis of the resource attribute.

**Comment by MrAlias** [comment]
Possible duplicate: https://github.com/open-telemetry/opentelemetry-go/issues/1550#

**Comment by evantorrie** [comment]
> Possible duplicate, or related: #1550

Yes, once #1550 is addressed, `jaeger.WithProcess()` should be removed. The `Span.Process.ServiceName` for the Jaeger exporter will be synthesized from the `Resource` `service.name` attribute.

**Comment by matej-g** [comment]
Ah, I must have missed that issue, that's exactly it. Please close this @MrAlias. Sorry!
