### ISSUE TITLE
SDK: Add Unit-Test for Probability Sampler

### ISSUE THREAD

**Issue by rghetia** [open-telemetry/opentelemetry-go#163]
There is a [TODO](https://github.com/open-telemetry/opentelemetry-go/blob/cd5ee69468071f1c136731a29c71a943cf14ffb8/sdk/trace/trace_test.go#L133) for adding test for Probability Sampler.

**Comment by iredelmeier** [comment]
@freeformz, it sounds like you want to work on this?

**Comment by freeformzSFDC** [comment]
What should this test, or tests, cover?

**Comment by rghetia** [comment]
> What should this test, or tests, cover?

with AlwaysSample all spans are sampled,
with NeverSample zero spans are sampled,
with probability approximate number of spans are sampled. 
Something similar to what is done in [OC](https://github.com/census-instrumentation/opencensus-go/blob/bf352733d4dffdd0e650c71cabc694aca654be9a/trace/trace_test.go#L90-L192)
