### ISSUE TITLE
Easily accidental overriding Config with `WithConfig` in sdk/trace/provider.go

### ISSUE THREAD

**Issue by ijsong** [open-telemetry/opentelemetry-go#1631]
When creating `TracerProvider`, it is likely to override resource and id generator with `WithConfig`.
To work around this, `WithConfig` should be located ahead of `WithResource` and `WithIDGenerator` in parameters of `NewTracerProvider`. 
However, it is not documented and also is prone to miss. There are some options like using only `WithConfig` or checking predefined configuration in `WithConfig`. 

https://github.com/open-telemetry/opentelemetry-go/blob/13938ab5a867b7840c6c829b74a9ab39b828730e/sdk/trace/provider.go#L54-L57

https://github.com/open-telemetry/opentelemetry-go/blob/13938ab5a867b7840c6c829b74a9ab39b828730e/sdk/trace/provider.go#L235-L255

**Comment by Aneurysm9** [comment]
Do we need to expose `WithConfig()` directly?  It seems like it might be better to just ensure that we have other options for specifying the remaining values in the `Config` struct, which would also allow us to unexport it.  It looks like `WithSampler()` and `WithSpanLimits()` are the only options missing.

**Comment by ijsong** [comment]
@Aneurysm9 
`WithConfig()` is not needed, it just allows us to set tracing settings to the provider at once.
As you mentioned, it can be replaced by adding `WithDefaultSampler()` and `WithSpanLimits()`, and it seems to be more natural.
