### ISSUE TITLE
Spec Conformance Review: OTLP Exporter Retries

### ISSUE THREAD

**Issue by MadVikingGod** [open-telemetry/opentelemetry-go#1632]
The [OTLP exporter Must Retry](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#retry) on transient errors.

Acceptance Criteria:
- [ ] OTLP/grpc driver retries when it experiences a transient error
- [x] [OTLP/http driver retries when it experiences a transient error](https://github.com/open-telemetry/opentelemetry-go/blob/13938ab5a867b7840c6c829b74a9ab39b828730e/exporters/otlp/otlphttp/driver_test.go#L138)

**Comment by XSAM** [comment]
Part of #1603

**Comment by MrAlias** [comment]
The gRPC driver for the OTLP exporter accepts a config that has a retry policy enabled by default:

https://github.com/open-telemetry/opentelemetry-go/blob/841d2a5885b37fc25fe77e72dca3b0f6bac945b2/exporters/otlp/otlpgrpc/options.go#L25-L59

This was added [here](https://github.com/open-telemetry/opentelemetry-go/pull/777) for reference.

**Comment by MadVikingGod** [comment]
Yes, but according to GRPC documents you can't enable retry [except with an environment variable](https://pkg.go.dev/google.golang.org/grpc#WithDisableRetry).

Unless we are going to rewrite the retry logic within our code, I don't think this is going to be fixed.  We could maybe have some documentation that you actually get retries with `GRPC_GO_RETRY=on`.

**Comment by MadVikingGod** [comment]
I did a bit of experimenting with it.  Here is an example of a client not retrying, and how to get it to retry.
https://github.com/MadVikingGod/opentelemetry-go/tree/retry-example/exporters/otlp/example

**Comment by MrAlias** [comment]
> Yes, but according to GRPC documents you can't enable retry [except with an environment variable](https://pkg.go.dev/google.golang.org/grpc#WithDisableRetry).

Ah, right, we ran into this on the old issues as well. One option that proposed was to copy the collector and write our own implementation: https://github.com/open-telemetry/opentelemetry-go/issues/561#issuecomment-634305198

**Comment by MrAlias** [comment]
We may need to write our own back-off/retry algorithm (like the collector) instead of relying on the gRPC method.
