### ISSUE TITLE
Update Jaeger Environment Variables

### ISSUE THREAD

**Issue by sofixa** [open-telemetry/opentelemetry-go#1639]
[The specification states](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/sdk-environment-variables.md#jaeger-exporter) the following environment variables need to be supported:

| Name                            | Description                                       | Default                                                                                          |
| ------------------------------- | ------------------------------------------------- | ------------------------------------------------------------------------------------------------ |
| OTEL_EXPORTER_JAEGER_AGENT_HOST | Hostname for the Jaeger agent                     | "localhost"                                                                                      |
| OTEL_EXPORTER_JAEGER_AGENT_PORT | Port for the Jaeger agent                         | 6832                                                                                             |
| OTEL_EXPORTER_JAEGER_ENDPOINT   | HTTP endpoint for Jaeger traces                   |  "http://localhost:14250" |
| OTEL_EXPORTER_JAEGER_USER       | Username to be used for HTTP basic authentication | -                                                                                                |
| OTEL_EXPORTER_JAEGER_PASSWORD   | Password to be used for HTTP basic authentication | -                                                                                                |

Currently the following are used:

https://github.com/open-telemetry/opentelemetry-go/blob/992837f195eacbd84f0596bfaa79470dba7408e5/exporters/trace/jaeger/env.go#L27-L43

These need to be updated to conform to the specification.

**Comment by s-nadendla** [comment]
@Aneurysm9 I can take a crack at this.

**Comment by MrAlias** [comment]
Closed with #1752
