### ISSUE TITLE
Spec Conformance Review: IdGenerators

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#1649]
- [x] Review [Id Generators](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/sdk.md#id-generators) section of the specification and identify all normative requirements it contains.
- [x] Validate our implementation of the specification to conform or not. If it conforms, document the conformity here. If it does not open an Issue or PR track the work.
- [x] Review the `IdGenerators` section of the [Spec Compliance Matrix](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md).
- [x] Update the matrix with the current state of Go (existing entries for Go should be ignored). If Go does not provide support for an item listed be sure to link to the Issue/PR tracking the work to support it.

**Comment by Aneurysm9** [comment]
> The SDK MUST by default randomly generate both the `TraceId` and the `SpanId`.

√ The SDK's [default `IDGenerator` implementations](https://github.com/open-telemetry/opentelemetry-go/blob/main/sdk/trace/id_generator.go#L40-L59) do generate `TraceID` and `SpanID` from a random data source.

> The SDK MUST provide a mechanism for customizing the way IDs are generated for both the `TraceId` and the `SpanId`.

√ [`IDGenerator`](https://github.com/open-telemetry/opentelemetry-go/blob/main/sdk/trace/id_generator.go#L27-L31) is an interface that can be implemented by external packages.  A [`WithIDGenerator` `TracerProviderOption` is provided](https://github.com/open-telemetry/opentelemetry-go/blob/main/sdk/trace/id_generator.go#L27-L31) to configure a `TracerProvider` with a custom `IDGenerator`.

> The SDK MAY provide this functionality by allowing custom implementations of an interface like the java example below (name of the interface MAY be `IdGenerator`, name of the methods MUST be consistent with [SpanContext](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/api.md#retrieving-the-traceid-and-spanid)), which provides extension points for two methods, one to generate a `SpanId` and one for `TraceId`.

≈ We use `IDGenerator` as the name of our interface, to remain consistent with Go conventions.  Our interface does not utilize the two methods listed in the specification, but instead `NewSpanID`, which is consistent with `SpanContext`'s reference to `SpanID`, and `NewIDs` which generates both a `SpanID` and a `TraceID`.  This is done as we do not foresee a time when generating a `TraceID` would not also require generating a new `SpanID`.  

> Additional `IdGenerator` implementing vendor-specific protocols such as AWS X-Ray trace id generator MUST NOT be maintained or distributed as part of the Core OpenTelemetry repositories.

√ There is an [AWS X-Ray `IDGenerator` implementation](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/propagators/aws/xray/idgenerator.go#L37) in the contrib repository.  There are no non-default implementations in the core repository.
