### ISSUE TITLE
Exporter: export Link from SpanData in Jaeger exporter

### ISSUE THREAD

**Issue by rghetia** [open-telemetry/opentelemetry-go#165]
Jaeger Exporter was added prior to Link support. Hence, Link is not exported via Jaeger exporter. See [TODO](https://github.com/open-telemetry/opentelemetry-go/blob/cd5ee69468071f1c136731a29c71a943cf14ffb8/exporter/trace/jaeger/jaeger.go#L197)

**Comment by paivagustavo** [comment]
Hi @rghetia!

I was playing with this issue but looks like the `apitrace.Link` structure does not have a "type of link" (seems like Jaeger accepts "child of" and "follows from") to map to Jaeger's `SpanRefType`. 

So links are not getting exported even after uncomment the mentioned code. Hardcoding `child_of` works.

Should this be added to the api? Should we assume every link is a `child_of` relationship? Or is this not yet ready to be done?

**Comment by rghetia** [comment]
@paivagustavo for now hardcode child_of and add a TODO pending resolution of the issue https://github.com/open-telemetry/opentelemetry-specification/issues/65.
