### ISSUE TITLE
Spec Conformance Review: SpanLimits

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#1650]
- [x] Review [Span Limits](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/sdk.md#span-limits) section of the specification and identify all normative requirements it contains.
- [x] Validate our implementation of the specification to conform or not. If it conforms, document the conformity here. If it does not open an Issue or PR track the work.
- [x] Review the `SpanLimits` section of the [Spec Compliance Matrix](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md).
- [x] Update the matrix with the current state of Go (existing entries for Go should be ignored). If Go does not provide support for an item listed be sure to link to the Issue/PR tracking the work to support it.

**Comment by XSAM** [comment]
# [Span Limits](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/sdk.md#span-limits)

> To protect against such errors, SDK Spans MAY discard attributes, links, and events that would increase the number of elements of each collection beyond the configured limit.

https://github.com/open-telemetry/opentelemetry-go/blob/0fe65e6bd2b3fad00289427e0bac1974086d4326/sdk/trace/span.go#L545-L548
https://github.com/open-telemetry/opentelemetry-go/blob/0fe65e6bd2b3fad00289427e0bac1974086d4326/sdk/trace/span.go#L303-L307
https://github.com/open-telemetry/opentelemetry-go/blob/0fe65e6bd2b3fad00289427e0bac1974086d4326/sdk/trace/span.go#L433-L437

> It the SDK implements the limits above it MUST provide a way to change these limits, via a configuration to the TracerProvider, by allowing users to configure individual limits like in the Java example bellow.

https://github.com/open-telemetry/opentelemetry-go/blob/0fe65e6bd2b3fad00289427e0bac1974086d4326/sdk/trace/provider.go#L299-L304

> The name of the configuration options SHOULD be `AttributeCountLimit`,
`EventCountLimit` and `LinkCountLimit`. The options MAY be bundled in a class,
which then SHOULD be called `SpanLimits`. Implementations MAY provide additional
configuration such as `AttributePerEventCountLimit` and `AttributePerLinkCountLimit`.

https://github.com/open-telemetry/opentelemetry-go/blob/0fe65e6bd2b3fad00289427e0bac1974086d4326/sdk/trace/provider.go#L299-L304

> **Configurable parameters:**
>
>* `AttributeCountLimit` (Default=128) - Maximum allowed span attribute count;
>* `EventCountLimit` (Default=128) - Maximum allowed span event count;
>* `LinkCountLimit` (Default=128) - Maximum allowed span link count;
>* `AttributePerEventCountLimit` (Default=128) - Maximum allowed attribute per span event count;
>* `AttributePerLinkCountLimit` (Default=128) - Maximum allowed attribute per span link count;

https://github.com/open-telemetry/opentelemetry-go/blob/0fe65e6bd2b3fad00289427e0bac1974086d4326/sdk/trace/config.go#L36-L69

> There SHOULD be a log emitted to indicate to the user that an attribute, event, or link was discarded due to such a limit. To prevent excessive logging, the log should not be emitted once per span, or per discarded attribute, event, or links.

Not implements yet but it is not a required feature, [tracking issue](https://github.com/open-telemetry/opentelemetry-go/issues/1707).

**Comment by XSAM** [comment]
The specification does not say [how to discard over limited data on span](https://github.com/open-telemetry/opentelemetry-specification/issues/1440) but I think we need to [unify our dropping approach](https://github.com/open-telemetry/opentelemetry-go/issues/1708) at least.
