### ISSUE TITLE
Span status description MUST not be set if code is not ERROR

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#1658]
From [the specification](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/api.md#set-status):

> `Status` is structurally defined by the following properties:
> - `StatusCode`, one of the values listed below.
> - Optional `Description` that provides a descriptive message of the `Status`.
>   `Description` MUST only be used with the `Error` `StatusCode` value.

Additionally

> The Span interface MUST provide:
> - An API to set the `Status`.
>   This SHOULD be called `SetStatus`.
>   This API takes the `StatusCode`, and an optional `Description`, either as individual parameters or as an immutable object encapsulating them, whichever is most appropriate for the language.
>   `Description` MUST be IGNORED for `StatusCode` `Ok` & `Unset` values.

This is not currently done:

https://github.com/open-telemetry/opentelemetry-go/blob/7153ef2dc294fbfebaafd355ab98050b4181ff1f/sdk/trace/span.go#L171-L182

To resolve this issue, descriptions need to be ignored if the status code is `OK` or `UNSET`.

**Comment by MrAlias** [comment]
Assigning to @veera83372

**Comment by MrAlias** [comment]
@veera83372 can you comment on the issue so I can assign it to you officially?

**Comment by veera83372** [comment]
Sure, I have picked it up
