### ISSUE TITLE
Do not set error status when recording an error with RecordError

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#1661]
From [the specification](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/api.md#set-status):

> The status code should only be set to `ERROR` according to the rules defined within the semantic conventions.

However we set the span status when recording an error:

https://github.com/open-telemetry/opentelemetry-go/blob/37688ef67616aa5a99e27fb03320fd0dc87e590e/sdk/trace/span.go#L265

It was pointed out in [this thread](https://cloud-native.slack.com/archives/C01N7PP1THC/p1614978903067900) that there could be a situation where an error is encountered but handled so when it is recorded the user may not want the span to be considered errored.

We should remove this line to ensure we are in compliance with the specification. Additionally, we need to be clear of this behavior in the method documentation (that it will not set the span status).

**Comment by veera83372** [comment]
@MrAlias  Picking this up

**Comment by seh** [comment]
Should we introduce a functional option for `span.RecordError` to request that it set the status as well if the supplied `error` is not nil?

**Comment by veera83372** [comment]
@seh  Sounds like good idea that users don't need to set it separately  when needed. they can invoke this function with respective argument

**Comment by MrAlias** [comment]
> Should we introduce a functional option for `span.RecordError` to request that it set the status as well if the supplied `error` is not nil?

@seh tracking this in https://github.com/open-telemetry/opentelemetry-go/issues/1677
