### ISSUE TITLE
Restrict modification of changelog at PR

### ISSUE THREAD

**Issue by XSAM** [open-telemetry/opentelemetry-go#1682]
It's scary that we accidentally change the released section of the changelog at PR, which will mess our release notes and confuse users.

It might be a good solution to write a tool to prevent this change in the changelog and integrate it into the CI, which lowers reviewers' mental burden.

Prior fix to the changelog #1680

**Comment by punya** [comment]
Should we consider adopting https://www.conventionalcommits.org/ to generate the changelog automatically from commit messages?

**Comment by XSAM** [comment]
The first thought in my head is only allowing the change to happen in the `Unreleased` section, which needs write a tool to parse markdown.

**Comment by punya** [comment]
Ah, that's a great idea and much less intrusive.

As an alternative, could we keep the unreleased changes section in a separate file, and move it into the CHANGELOG as part of the release process? The tooling would be easier and contributors would be less likely to make a mistake.

However, it would be *slightly* more work for maintainers at release time.

**Comment by XSAM** [comment]
> As an alternative, could we keep the unreleased changes section in a separate file, and move it into the CHANGELOG as part of the release process? The tooling would be easier and contributors would be less likely to make a mistake.
>
> However, it would be slightly more work for maintainers at release time.

Yeah, that seems a good approach too.

But I slightly prefer to write more codes and be less intrusive. Furthermore, we might consider making this tool used by every OpenTelemetry repo in the feature if it is actually useful and essential. ;)
