### ISSUE TITLE
The SDK MUST extract information from the OTEL_RESOURCE_ATTRIBUTES environment variable

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#1689]
Currently we do not default to including attributes specified with the `OTEL_RESOURCE_ATTRIBUTES` environment variable. This is required by [the specification](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/resource/sdk.md#specifying-resource-information-via-an-environment-variable):

> The SDK MUST extract information from the `OTEL_RESOURCE_ATTRIBUTES` environment variable and [merge](#merge) this, as the secondary resource, with any resource information provided by the user, i.e. the user provided resource information has higher priority.
> 
> The `OTEL_RESOURCE_ATTRIBUTES` environment variable will contain of a list of key value pairs, and these are expected to be represented in a format matching to the [W3C Baggage](https://github.com/w3c/baggage/blob/fdc7a5c4f4a31ba2a36717541055e551c2b032e4/baggage/HTTP_HEADER_FORMAT.md#header-content), except that additional semi-colon delimited metadata is not supported, i.e.: `key1=value1,key2=value2`. All attribute values MUST be considered strings.

These attributes will be used to create a Resource if [`resource.New`](https://pkg.go.dev/go.opentelemetry.io/otel/sdk@v0.18.0/resource#New) is used to create a resource passed to an SDK, but it must be done by the user.

The `TracerProvider` and metric `Controller` need to be updated to default extracting these attributes into a resource that is merged with the `resource.Default` resource they already use.

Having these attributes automatically merged into the used resource makes the [`FromEnv` detector](https://pkg.go.dev/go.opentelemetry.io/otel/sdk@v0.18.0/resource#FromEnv) of limited value. It would only include attributes that would latter be merged in. It seems like that detector should be removed, or possibly changed to accept a list of environment variable names that it would then pull in as attributes of a Resource. Meaning if you wanted to specify a Resource in a way other than defined for the `OTEL_RESOURCE_ATTRIBUTES` environment variable you could accomplish it that way.

**Comment by evantorrie** [comment]
I think this will also apply to `Resource.Default()`, i.e. if `OTEL_RESOURCE_ATTRIBUTES` is defined in the environment, then `Resource.Default()` should include those (to the point of overriding say the default determined `service.name`).

**Comment by MrAlias** [comment]
> I think this will also apply to `Resource.Default()`, i.e. if `OTEL_RESOURCE_ATTRIBUTES` is defined in the environment, then `Resource.Default()` should include those (to the point of overriding say the default determined `service.name`).

From what I can tell the environment resource detector is not included in the default:

https://github.com/open-telemetry/opentelemetry-go/blob/8b1be11a549eefb6efeda2f940cbda70b3c3d08d/sdk/resource/resource.go#L43

But, there would still be a problem if it was that the user supplied resource to an SDK would not be merged with the environment attributes. Instead it would overwrite them:

https://github.com/open-telemetry/opentelemetry-go/blob/8b1be11a549eefb6efeda2f940cbda70b3c3d08d/sdk/trace/provider.go#L198-L201

**Comment by cynthiakedu** [comment]
@Aneurysm9 Can I take this issue?

**Comment by dhruv-vora** [comment]
@Aneurysm9 I'd like to take this issue
