### ISSUE TITLE
Resource service name attribute should have precedence over reporter in zipkin

### ISSUE THREAD

**Issue by jcchavezs** [open-telemetry/opentelemetry-go#1695]
As of now Zipkin exporter receives a serviceName as parameter (see https://github.com/open-telemetry/opentelemetry-go/blob/main/exporters/trace/zipkin/zipkin.go#L85) to force the user to pass a serviceName in, however if the resources API provides a serviceName that should have a preference over the reporter service name, otherwise it forces the user to launch different exporters to achieve different resources reporting.

Ping @mohit-a21

**Comment by matej-g** [comment]
Possibly duplicate with issue https://github.com/open-telemetry/opentelemetry-go/issues/1549?

**Comment by bogdandrutu** [comment]
I would suggest probably to remove the `serviceName` since we added a default value in the Resource. The specs removed the need to have it as an argument to the exporter see https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/zipkin.md

**Comment by jcchavezs** [comment]
Good to know. I will open a PR for that.

**Comment by MrAlias** [comment]
duplicate of #1549
