### ISSUE TITLE
Track specification change for composite TextMapPropagator inject/extract

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#1696]
Currently the composite `TextMapPropagator` requires that the inject/extract methods accept a getter/setter as an argument even though the underlying `TextMapPropagator` is only given the option to support this argument. The [implementation of the composite `TextMapPropagator` does not support these currently required arguments (it is just a `TextMapPropagator` interface itself)](https://pkg.go.dev/go.opentelemetry.io/otel@v0.18.0/propagation#NewCompositeTextMapPropagator).

[A PR to the specification](https://github.com/open-telemetry/opentelemetry-specification/pull/1541) has been made to ease this requirement. Until this is merged and released, this implementation of the specification will be out of compliance. This issue is intended to track these needed changes upstream and ensure when we release an RC it is for an implementation of a specification that we can be compliant with.

**Comment by Aneurysm9** [comment]
@MrAlias looks like the spec PR linked here was merged.  Can this issue be closed, or is there something we need to do?
