### ISSUE TITLE
Test exporting a batch of spans from Jaeger Exporter is working as expected 

### ISSUE THREAD

**Issue by XSAM** [open-telemetry/opentelemetry-go#1699]
We need to write some tests to prove the Jaeger Exporter can correctly export a batch of spans, which address [this comment](https://github.com/open-telemetry/opentelemetry-go/pull/1673#discussion_r590636247)

Possible steps:

- [ ] Fix the typo of `testCollectorEnpoint` to `testCollectorEndpoint`
- [ ] Refactor `testCollectorEndpoint` to record all the `gen.Batch` that was exported.
- [ ] Check the correctness of `gen.Batch`.

**Comment by MrAlias** [comment]
Is this required for the 1.0 RC release? Should it be added to the project/milestone?

**Comment by XSAM** [comment]
> Is this required for the 1.0 RC release?

Since this test wants to prove a feature, populating Jaeger's Span Process must from Resource, that is required for the 1.0 RC release, I thought the test itself would become required for the 1.0 RC release.

> Should it be added to the project/milestone?

Sure thing. I forget to add this.

**Comment by IrisTuntun** [comment]
@Aneurysm9 I'd like to take this issue.
