### ISSUE TITLE
The exported `attribute` package API should not allow for a copylock vet error to be exposed.

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#1704]
The exported `attribute` package API should not allow for a copylock vet error to be exposed.

_Originally posted by @MrAlias in https://github.com/open-telemetry/opentelemetry-go/pull/1703#r595616110_

**Comment by MrAlias** [comment]
Uncommenting, e.g.

```
git diff
diff --git a/attribute/set.go b/attribute/set.go
index 882dc112..18b221ef 100644
--- a/attribute/set.go
+++ b/attribute/set.go
@@ -246,7 +246,7 @@ func NewSet(kvs ...KeyValue) Set {
                return empty()
        }
        s, _ := NewSetWithSortableFiltered(kvs, new(Sortable), nil)
-       return s //nolint
+       return s
 }
 
 // NewSetWithSortable returns a new `Set`.  See the documentation for
@@ -259,7 +259,7 @@ func NewSetWithSortable(kvs []KeyValue, tmp *Sortable) Set {
                return empty()
        }
        s, _ := NewSetWithSortableFiltered(kvs, tmp, nil)
-       return s //nolint
+       return s
 }
 
 // NewSetWithFiltered returns a new `Set`.  See the documentation for
```

and then running go vet:

```
$ go vet ./attribute
# go.opentelemetry.io/otel/attribute
attribute/set.go:249:9: return copies lock value: go.opentelemetry.io/otel/attribute.Set contains sync.Mutex
attribute/set.go:262:9: return copies lock value: go.opentelemetry.io/otel/attribute.Set contains sync.Mutex
```

It's not great, but I can see this making sense if this is only for internal use and we are ensuring there will be no deadlock manually. However, we are exporting this API. When a users uses the returned `Set` from these functions they will receive the same error.

**Comment by MrAlias** [comment]
Some potential options:

1. Have all the `New*` methods return `*Set`. This will add an additional allocation.
2. Explore a lock-less solution. Would need to benchmark to show viable.
3. Unexport the Set and associated declarations. This is not desirable as it is used in external packages, like the dogstatsd exporter in contrib.

**Comment by lastchiliarch** [comment]
Maybe we can wrap encoders and encoded as a whole atomic.Value to remove the sync.Mutex.
I'd like to have a try If atomic.Value is possible solution.

**Comment by MrAlias** [comment]
> Maybe we can wrap encoders and encoded as a whole atomic.Value to remove the sync.Mutex.
> I'd like to have a try If atomic.Value is possible solution.

I think this is a good solution to explore, but as I way saying in point 2 above, we will need to include performance benchmarks to ensure performance or resource usage doesn't change much.
