### ISSUE TITLE
Dropped spans result in broken traces

### ISSUE THREAD

**Issue by Flarna** [open-telemetry/opentelemetry-go#1709]
Consider following trace: Span1 => Span2 => Span3

In case Span2 is dropped because of sampling the parentSpandId used in Span3 refers to a span never arriving on backend.

If I understood the code correct each span gets it's unique spanId before a sample decision is made.

Shouldn't a non sampled span propagate the spanId from it's parent instead of creating a new one? In that case Span3 above would refer to Span1 and backend would not complain about `invalid parent span ID`.

**Comment by Aneurysm9** [comment]
Each span does indeed get a unique `SpanID`.  The `ParentBased` sampler should be making determinations based on whether the parent was sampled, however, not on the parent `SpanID`.  So, in this case if Span2 were not sampled then when its `SpanContext` was used as a parent context for Span3 the `ParentBased` sampler would also not sample Span3, at least in its default configuration.  The user would need to make a choice to reconfigure the sampler to allow spans with non-sampled parents to be sampled.

Even when a users makes such a choice, I'm not sure it would be correct to rewrite the trace graph in such a manner as it could present an inaccurate impression of execution flow.  This would be particularly pronounced in cases where a probabilistic sampler were used to sample Span2 and Span3, leading to cases where the flow sometimes appeared to be any of:

```
Span1 => Span2
Span1 => Span3
Span1 => Span2 => Span3
```

when only the last of those is accurate.  At least having `Span1, Span3` with an indication that Span3 is missing its parent allows the user to know that there is an incomplete picture being presented.

**Comment by Flarna** [comment]
Thanks for the fast answer.

So in short missing spans because of non parent based sampling should result in missing spans in the trace.

This differs to the case if the whole SDK is not present in a process in the middle where the parent span should be forwarded (see https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#behavior-of-the-api-in-the-absence-of-an-installed-sdk).

**Comment by Aneurysm9** [comment]
That is my expectation, yes, and it is indeed different to the case where no SDK is installed, though even in that case this situation may arise.  Imagine three systems, A, B, and C, where A and C have working SDKs installed and B does not but forwards the span context information.  If Span1 and Span2 are started in A, Span1 is sampled but Span2 is not, and during Span2 a request is sent to B with Span2's context propagated.  B then makes a request to C, forwarding Span2's context and C attempts to start Span3 and sample it.  In this situation C has no information available to it about Span1, only the TraceID, Span2's SpanID, and its flags.  This is actually the same situation if B had an SDK and attempted to start a span of its own as well.

**Comment by MrAlias** [comment]
@Flarna that is true, that behavior is as specified:

> [Generate a new span ID for the Span, independently of the sampling decision.](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.1.0/specification/trace/sdk.md#sdk-span-creation)

and

> [if the parent is a non-recording Span (which it usually always is if no SDK is present), it MAY return the parent Span back from the creation method.](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.1.0/specification/trace/api.md)
