### ISSUE TITLE
Develop and implement a plan to extend interfaces

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#1714]
The specification SIG has stated that they will consider additions to API/SDK interfaces that are not expected for instrumentation or operator users of OpenTelemetry to not be backwards incompatible. In Go adding a method to an Exported interface is a breaking change.

There are a few ways we can support these changes while remaining compatible:

- Add a private method to the interfaces and require implementation to embed the interface. This topic is also explored in more detail in Jonathan Amsterdam's ["Detecting Incompatible API Changes" talk](https://youtu.be/JhdL5AkH-AQ?t=1328). The take away is that you allow for compile time compatability, but will cause the client to panic at runtime if they don't implement the added method.
- Add a private method to the interface and export a NoOp implementation that will need to be embedded. This is similar to the previous approach, but will have a silent failure or no action instead of a panic. This could be worse in cases where these silent failures are important and unnoticed by the user.
- Plan to add interfaces as new methods are needed. Also talked about in Jonathan Amsterdam's [talk](https://youtu.be/JhdL5AkH-AQ?t=1532) and the [Go blog](https://blog.golang.org/module-compatibility).

To resolve this we need to:

- [x] Inventory what interfaces have the possibility to be extended by the specification.
- [x] Define a plan for how we will handle these situations.
   - If it is something where we need to update interfaces, we need to do that before a stable release.
- [ ] Document this decision in our contributing guidelines.

**Comment by seh** [comment]
_s/incomparable/incompatible/_?

**Comment by MrAlias** [comment]
List of exported interfaces we plan to release with 1.0.0:

- [`"go.opentelemetry.io/otel/sdk/resource".Option`](https://github.com/open-telemetry/opentelemetry-go/blob/64b640cc26f7886241fd32e51af811ec3471f36f/sdk/resource/config.go#L32)
- [`"go.opentelemetry.io/otel/sdk/resource".Detector`](https://github.com/open-telemetry/opentelemetry-go/blob/64b640cc26f7886241fd32e51af811ec3471f36f/sdk/resource/auto.go#L31)
- [`"go.opentelemetry.io/otel/sdk/trace".SpanExporter`](https://github.com/open-telemetry/opentelemetry-go/blob/64b640cc26f7886241fd32e51af811ec3471f36f/sdk/trace/span_exporter.go#L21)
- [`"go.opentelemetry.io/otel/sdk/trace".Sampler`](https://github.com/open-telemetry/opentelemetry-go/blob/64b640cc26f7886241fd32e51af811ec3471f36f/sdk/trace/sampling.go#L27)
- [`"go.opentelemetry.io/otel/sdk/trace".ParentBasedSamplerOption`](https://github.com/open-telemetry/opentelemetry-go/blob/64b640cc26f7886241fd32e51af811ec3471f36f/sdk/trace/sampling.go#L192)
- [`"go.opentelemetry.io/otel/sdk/trace".SpanProcessor`](https://github.com/open-telemetry/opentelemetry-go/blob/64b640cc26f7886241fd32e51af811ec3471f36f/sdk/trace/span_processor.go#L26)
- [`"go.opentelemetry.io/otel/sdk/trace".IDGenerator`](https://github.com/open-telemetry/opentelemetry-go/blob/64b640cc26f7886241fd32e51af811ec3471f36f/sdk/trace/id_generator.go#L28)
- [`"go.opentelemetry.io/otel/sdk/trace".ReadOnlySpan`](https://github.com/open-telemetry/opentelemetry-go/blob/64b640cc26f7886241fd32e51af811ec3471f36f/sdk/trace/span.go#L37)
- [`"go.opentelemetry.io/otel/sdk/trace".ReadWriteSpan`](https://github.com/open-telemetry/opentelemetry-go/blob/64b640cc26f7886241fd32e51af811ec3471f36f/sdk/trace/span.go#L91)
- [`"go.opentelemetry.io/otel/sdk/trace".TracerProviderOption`](https://github.com/open-telemetry/opentelemetry-go/blob/64b640cc26f7886241fd32e51af811ec3471f36f/sdk/trace/provider.go#L238)
- [`"go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc".Option`](https://github.com/open-telemetry/opentelemetry-go/blob/64b640cc26f7886241fd32e51af811ec3471f36f/exporters/otlp/otlptrace/otlptracegrpc/options.go#L29)
- [`"go.opentelemetry.io/otel/exporters/otlp/otlptrace".Client`](https://github.com/open-telemetry/opentelemetry-go/blob/64b640cc26f7886241fd32e51af811ec3471f36f/exporters/otlp/otlptrace/clients.go#L26)
- [`"go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp".Option`](https://github.com/open-telemetry/opentelemetry-go/blob/64b640cc26f7886241fd32e51af811ec3471f36f/exporters/otlp/otlptrace/otlptracehttp/options.go#L51)
- [`"go.opentelemetry.io/otel/exporters/trace/jaeger".EndpointOption`](https://github.com/open-telemetry/opentelemetry-go/blob/64b640cc26f7886241fd32e51af811ec3471f36f/exporters/trace/jaeger/uploader.go#L38)
- [`"go.opentelemetry.io/otel/exporters/trace/jaeger".AgentEndpointOption`](https://github.com/open-telemetry/opentelemetry-go/blob/64b640cc26f7886241fd32e51af811ec3471f36f/exporters/trace/jaeger/uploader.go#L78)
- [`"go.opentelemetry.io/otel/exporters/trace/jaeger".CollectorEndpointOption`](https://github.com/open-telemetry/opentelemetry-go/blob/64b640cc26f7886241fd32e51af811ec3471f36f/exporters/trace/jaeger/uploader.go#L172)
- [`"go.opentelemetry.io/otel/exporters/trace/zipkin".Option`](https://github.com/open-telemetry/opentelemetry-go/blob/64b640cc26f7886241fd32e51af811ec3471f36f/exporters/trace/zipkin/zipkin.go#L56)
- [`"go.opentelemetry.io/otel/exporters/stdout".Option`](https://github.com/open-telemetry/opentelemetry-go/blob/64b640cc26f7886241fd32e51af811ec3471f36f/exporters/stdout/config.go#L74)
- [`"go.opentelemetry.io/otel/propagation".TextMapCarrier`](https://github.com/open-telemetry/opentelemetry-go/blob/64b640cc26f7886241fd32e51af811ec3471f36f/propagation/propagation.go#L23)
- [`"go.opentelemetry.io/otel/propagation".TextMapPropagator`](https://github.com/open-telemetry/opentelemetry-go/blob/64b640cc26f7886241fd32e51af811ec3471f36f/propagation/propagation.go#L56)
- [`"go.opentelemetry.io/otel".ErrorHandler`](https://github.com/open-telemetry/opentelemetry-go/blob/64b640cc26f7886241fd32e51af811ec3471f36f/error_handler.go#L18)
- [`"go.opentelemetry.io/otel/bridge/opentracing/migration".DeferredContextSetupTracerExtension`](https://github.com/open-telemetry/opentelemetry-go/blob/64b640cc26f7886241fd32e51af811ec3471f36f/bridge/opentracing/migration/api.go#L33)
- [`"go.opentelemetry.io/otel/bridge/opentracing/migration".OverrideTracerSpanExtension`](https://github.com/open-telemetry/opentelemetry-go/blob/64b640cc26f7886241fd32e51af811ec3471f36f/bridge/opentracing/migration/api.go#L66)
- [`"go.opentelemetry.io/otel/oteltest".Option`](https://github.com/open-telemetry/opentelemetry-go/blob/64b640cc26f7886241fd32e51af811ec3471f36f/oteltest/config.go#L65)
- [`"go.opentelemetry.io/otel/trace".Span`](https://github.com/open-telemetry/opentelemetry-go/blob/64b640cc26f7886241fd32e51af811ec3471f36f/trace/trace.go#L340)
- [`"go.opentelemetry.io/otel/trace".Tracer`](https://github.com/open-telemetry/opentelemetry-go/blob/64b640cc26f7886241fd32e51af811ec3471f36f/trace/trace.go#L477)
- [`"go.opentelemetry.io/otel/trace".TracerProvider`](https://github.com/open-telemetry/opentelemetry-go/blob/64b640cc26f7886241fd32e51af811ec3471f36f/trace/trace.go#L495)
- [`"go.opentelemetry.io/otel/trace".TracerOption`](https://github.com/open-telemetry/opentelemetry-go/blob/64b640cc26f7886241fd32e51af811ec3471f36f/trace/config.go#L50)
- [`"go.opentelemetry.io/otel/trace".SpanStartOption`](https://github.com/open-telemetry/opentelemetry-go/blob/64b640cc26f7886241fd32e51af811ec3471f36f/trace/config.go#L122)
- [`"go.opentelemetry.io/otel/trace".SpanEndOption`](https://github.com/open-telemetry/opentelemetry-go/blob/64b640cc26f7886241fd32e51af811ec3471f36f/trace/config.go#L134)
- [`"go.opentelemetry.io/otel/trace".EventOption`](https://github.com/open-telemetry/opentelemetry-go/blob/64b640cc26f7886241fd32e51af811ec3471f36f/trace/config.go#L170)
- [`"go.opentelemetry.io/otel/trace".SpanOption`](https://github.com/open-telemetry/opentelemetry-go/blob/64b640cc26f7886241fd32e51af811ec3471f36f/trace/config.go#L175)
- [`"go.opentelemetry.io/otel/trace".SpanStartEventOption`](https://github.com/open-telemetry/opentelemetry-go/blob/64b640cc26f7886241fd32e51af811ec3471f36f/trace/config.go#L181)
- [`"go.opentelemetry.io/otel/trace".SpanEventOption`](https://github.com/open-telemetry/opentelemetry-go/blob/64b640cc26f7886241fd32e51af811ec3471f36f/trace/config.go#L212)

**Comment by MrAlias** [comment]
The way I understand the groups decision on how we want to handle interface changes in the future is conditional on what should implement the interface is and how it will be used.

- Interfaces that we provide for end-users to implement and call.
- Interfaces that we provide which will be implemented internally only.
- Interfaces that we provide which will be implemented by SDK developers.

### End-User Interfaces

These interfaces will be called by the SDK and can be user provided. Adding or changing methods for these interfaces will break user implementations and therefore MUST NOT be done.

These interfaces may also be called by the user themselves. Removing methods that users call from these interface definitions will break users' code and therefore MUST NOT be done.

These interfaces MUST NOT change once they are made stable.

If new functionality is needed for these interfaces it MUST be added by including an additional interface. That interface can be a simple interface for the specific functionality that you want to add or it can be a super-set of the original interface. For example, if you wanted to a `Close` method to the `Exporter` interface:

```go
type Exporter interface {
	Export()
}
```

A new interface, `Closer`, can be added:

```go
type Closer interface {
	Close()
}
```

Code that is passed the `Exporter` interface can now check to see if the passed value also satisfies the new interface. E.g.

```go
func caller(e Exporter) {
	/* ... */
	if c, ok := e.(Closer); ok {
		c.Close()
	}
	/* ... */
}
```

Alternatively, a new type that is the super-set of an `Exporter` can be created.

```go
type ClosingExporter struct {
	Exporter
	Close()
}
```

This new type can be used similar to the simple interface above in that a passed `Exporter` type can be asserted to satisfy the `ClosingExporter` type and the `Close` method called.

This super-set approach can be useful if there is explicit behavior that needs to be coupled with the original type and passed as a unified type to a new function, but, because of this coupling, it also limits the applicability of the added functionality. If there exist other interfaces where this functionality should be added, each one will need their own super-set interfaces and will duplicate the pattern. For this reason, the simple targeted interface that defines the specific functionality should be preferred.

### Internal Only Interface Implementations

These interfaces should be guarded from external implementations. While not perfect, this should be done using an unexported method.

### SDK Implemented Interfaces

These interfaces can only accrete, methods MUST NOT be removed or changed. Users are expected to call the methods of these interfaces.

These interfaces SHOULD NOT be guarded, a build failure should occur when things are added to the interface and SDK developers have not satisfied the new methods. This is an assumed responsibility that comes with development of an SDK.

The default SDK will be released in lock-step with any changes to the interfaces such that it satisfies the interface.

This divergence from the standard backwards compatibility guarantee of a Go API is part of the OpenTelemetry versioning policy and is meant to provide room to evolve the OpenTelemetry specification.

**Comment by MrAlias** [comment]
An interesting point to consider in the already decided configuration policy is that if we instead configure by just passing a configuration struct type we would not have any "Internal Only Interface" and all code written by users could be checked by the compiler without exception.
