### ISSUE TITLE
perf: add SetAttribute(attribute.KeyValue)

### ISSUE THREAD

**Issue by vmihailenco** [open-telemetry/opentelemetry-go#1718]
As I understand we have to use `attribute.KeyValue` over `interface{}` for performance reasons, because passing `string` as an interface allocates.

But then there is `span.SetAttributes(kvs ...attribute.KeyValue)` which allocates a slice for `kvs`.

So we save an allocation using `attribute.KeyValue` and introduce an allocation by using `span.SetAttributes`. The net result is 0 (and mental overhead of `attribute.KeyValue`).

Why not to add `SetAttribute(attribute.KeyValue)` to have an API that does not allocate in common case?

I am asking because in benchmarks these allocations add up and produce some [noticeable](https://github.com/go-redis/redis/issues/1701) results.

**Comment by seh** [comment]
See #361 and #302 for previous discussion on this topic.

**Comment by vmihailenco** [comment]
@seh thanks, I am aware of those discussions (and more) and that set_attribute existed at various points to do various tasks. Every time there was a reason why it should be added, removed, added again and then removed. Looks rather arbitrary.

But it looks like these 100-200ns actually matter for some benchmarks. I guess I can wrap everything with `IsRecording`, but that only hides the problem.

**Comment by seh** [comment]
I didn't mean to argue against you; rather, I'm in favor of a unary `SetAttribute` method. I just wanted to make sure you were aware of the path that led to our current state.

**Comment by MadVikingGod** [comment]
To test out how much better this would be I created a small benchmark.  It doesn't look like having a unary function for this would create any performance gain.

This is totally understandable and could be desirable from a usability POV.  Maybe a more nuanced benchmark might point us toward how this could be improved.

**Comment by MadVikingGod** [comment]
It doesn't look like this is needed for a performance reason, so we decided to not implement this method.  If there is another reason to create this function please reopen this issue.
