### ISSUE TITLE
How to set service name?

### ISSUE THREAD

**Issue by watjurk** [open-telemetry/opentelemetry-go#1721]
As of version `v0.19.0` jaeger exporter uses `go.opentelemetry.io/otel/sdk/resource`'s service name, so I no longer can control what is my service name.
My question is: how can I set custom `go.opentelemetry.io/otel/sdk/resource`' service name?

Thanks!

**Comment by MrAlias** [comment]
[Register a Resource with your TracerProvider](https://github.com/open-telemetry/opentelemetry-go/blob/2b4fa9681bd0c69574aaa879039382002b220204/sdk/trace/provider.go#L257-L270) that has the [service name attribute](https://github.com/open-telemetry/opentelemetry-go/blob/2b4fa9681bd0c69574aaa879039382002b220204/semconv/resource.go#L21-L22) set to with a value of your service name. A good way to do this and not loose defaults is to [Merge](https://github.com/open-telemetry/opentelemetry-go/blob/2b4fa9681bd0c69574aaa879039382002b220204/sdk/resource/resource.go#L114) your resource with [the Default](https://github.com/open-telemetry/opentelemetry-go/blob/2b4fa9681bd0c69574aaa879039382002b220204/sdk/resource/resource.go#L141-L145) (make sure your resource is the second argument as that will take precedence).

**Comment by watjurk** [comment]
Thanks for quick response, but It does not work, [trace.WithResource](https://github.com/open-telemetry/opentelemetry-go/blob/2b4fa9681bd0c69574aaa879039382002b220204/sdk/trace/provider.go#L257-L270) returns [trace.TracerProviderOption](https://github.com/open-telemetry/opentelemetry-go/blob/2b4fa9681bd0c69574aaa879039382002b220204/sdk/trace/provider.go#L55) but [jaeger.NewRawExporter](https://github.com/open-telemetry/opentelemetry-go/blob/main/exporters/trace/jaeger/jaeger.go#L90-L94) wants [jaeger.Option](https://github.com/open-telemetry/opentelemetry-go/blob/2b4fa9681bd0c69574aaa879039382002b220204/exporters/trace/jaeger/jaeger.go#L42).
Apart from that I think It would be nice to provide a way to set (or modify) default resource.

**Comment by watjurk** [comment]
Oh sorry, I didn't see [WithSDKOptions](https://github.com/open-telemetry/opentelemetry-go/blob/main/exporters/trace/jaeger/jaeger.go#L75-L80). I think this resolves this issue, thanks!
