### ISSUE TITLE
Convenience functions `NewExportPipeline` and `InstallNewPipeline` can not be flushed. 

### ISSUE THREAD

**Issue by MadVikingGod** [open-telemetry/opentelemetry-go#1725]
Currently, the exporters stdout, jaeger, and zipkin offer convenience functions for getting started quickly exporting data in these formats.  When using these functions there isn't a direct or obvious way to flush or shutdown the TracerProviders that are created.

A workaround I've found is to cast the global TracerProvider to a `*sdktrace.TracerProvider`, eg.  `otel.GetTracerProvider().(*sdktrace.TracerProvider)`

Possible solutions:
- standardize the convenience functions to expose the concrete type they return.  This would let users of those functions manage the shutdown/flush logic as they see fit.
- provide a global `Shutdown()`.  These should iterate over *Provider and call the associated shutdown.  We would also need to define the signature of the shutdown that will be called.

**Comment by MadVikingGod** [comment]
One thing that I noticed while working this is that Jaeger's exporter has a built-in batcher.  This will probably lead to odd behavior when using Jaeger + the batching span processor.

**Comment by MrAlias** [comment]
> One thing that I noticed while working this is that Jaeger's exporter has a built-in batcher. This will probably lead to odd behavior when using Jaeger + the batching span processor.

I found this as well while working on https://github.com/open-telemetry/opentelemetry-go/issues/1380. I'm still thinking it through, but I think we need to rip the bundler out of the Jaeger exporter for just this reason.

**Comment by MrAlias** [comment]
Tracking with https://github.com/open-telemetry/opentelemetry-go/issues/1799

**Comment by MadVikingGod** [comment]
Would it make sense to have these same convenience functions as part of `otlpgrpc` and `otlphttp`?  

We could have a similar one in the `exporter/otlp` module, but because the grpc and HTTP are modules we can't have as simple of a `InstallNewPipeline` because users would have to provide the driver.

**Comment by MrAlias** [comment]
> Would it make sense to have these same convenience functions as part of `otlpgrpc` and `otlphttp`?
> 
> We could have a similar one in the `exporter/otlp` module, but because the grpc and HTTP are modules we can't have as simple of a `InstallNewPipeline` because users would have to provide the driver.

This sounds like something we could add after an RC. I'd be interested to get some user feedback on how to solve this before we implement a solution here.

**Comment by MadVikingGod** [comment]
The only outstanding exporter is Jaeger.  I was going to let the bundler work finish if it doesn't take care of it for me.

**Comment by MrAlias** [comment]
We need https://github.com/open-telemetry/opentelemetry-go/pull/1806 to merge before we can update the Jaeger convenience functions. Otherwise, we are returning either a default SDK or a No-Op SDK.
