### ISSUE TITLE
Sampling parameters require a `Context` with an embedded `Span`

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#1727]
Currently we use the following sampling decision parameteres:

https://github.com/open-telemetry/opentelemetry-go/blob/90bd4ab50c6e85743f2b8f3a1768a5afceeb1fc0/sdk/trace/sampling.go#L31-L40

The [specification requires](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/sdk.md#sampler):

> * [`Context`](../context/context.md) with parent `Span`.
>   The Span's SpanContext may be invalid to indicate a root span.
> ...

This likely needs to be addressed more holistically [here](https://github.com/open-telemetry/opentelemetry-go/issues/1182) first.

**Comment by Aneurysm9** [comment]
I think this also ties in to the concept of a "propagation span" that only has a span context and is non-recording.  I think with the `IsRemote` predicate on span contexts we're now closer to being able to simply stick a span into a context with only a remote span context and let the SDK figure out what to do with it when starting a new span.

**Comment by MrAlias** [comment]
> I think this also ties in to the concept of a "propagation span" that only has a span context and is non-recording. I think with the `IsRemote` predicate on span contexts we're now closer to being able to simply stick a span into a context with only a remote span context and let the SDK figure out what to do with it when starting a new span.

Agreed! That is a change I am working on submitting [here](https://github.com/open-telemetry/opentelemetry-go/compare/main...MrAlias:rm-remote-ctx-keys). It requires [this](https://github.com/open-telemetry/opentelemetry-go/pull/1726) to merge first, but I think we can achieve this now.
