### ISSUE TITLE
Jaeger exporter: `ExportSpans` should honor context deadline

### ISSUE THREAD

**Issue by matej-g** [open-telemetry/opentelemetry-go#1730]
As was established in discussion https://github.com/open-telemetry/opentelemetry-go/issues/1613#issuecomment-805297026, Jaeger's `ExportSpans` implementation currently does not honor a context deadline, which it should. See also statement in the [documentation](https://github.com/open-telemetry/opentelemetry-go/blob/a9b2f85134dc918ff44969ff0b05fe3c5ac1a1f2/sdk/export/trace/trace.go#L34-L37).

**Comment by humivo** [comment]
Hey can I take on this issue?
