### ISSUE TITLE
otlp: want error went WithInsecure is needed

### ISSUE THREAD

**Issue by andreimatei** [open-telemetry/opentelemetry-go#1735]
I spent a bunch of time figuring out that a basic example app trying to send traces to an OpenTelemetry collector running locally wants an `otlp.WithInsecure()` in order to work.
Some sort of error or log message to tell me this would have been great.

I was getting an "exporter disconnected" log message from somewhere, but I couldn't tell much from that.

**Comment by paivagustavo** [comment]
Hey @andreimatei, sorry for that unhelpful error message.

The OTLP gRPC driver only checks if the connections is still active and if not it returns a default "exporter disconnected" error. 

I think this should be easily fixed if we wrap the connection error, giving a more detailed error message, for example:
```
2021/03/26 18:11:24 exporter disconnected: grpc: no transport security set (use grpc.WithInsecure() explicitly or set credentials)
```

I'll be creating a PR to fix this soon.
