### ISSUE TITLE
Remove Process configuration for the Jaeger exporter

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#1762]
The [`Process`](https://github.com/open-telemetry/opentelemetry-go/blob/97501a3fee7647a3a14b6d4429d814ffb17c2a67/exporters/trace/jaeger/jaeger.go#L178-L186) serves the same functionality as the OTel `Resource`. The `Resource` should be unified on as the way process information is passed to the exporter (via the SDK itself).

Additionally, having this type for configuring the exporter [moves us out of specification compliance when we try to merge the provided service name](https://github.com/open-telemetry/opentelemetry-go/issues/1605#issuecomment-811394420).

This does not mean that we should stop correctly forming a process that we pass to the exported data, just our representation.

We should remove the type and all configuration options related to it.

**Comment by IrisTuntun** [comment]
Can I take this issue?

**Comment by MrAlias** [comment]
To complete this, the [Jaeger exporter section: Service Name](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md#exporters) part of the spec-compliance-matrix needs to be updated.

**Comment by IrisTuntun** [comment]
Hi, I have two questions:

1. Do we just remove process configuration in Jaeger completely? For example, [jaegerBatchList](https://github.com/open-telemetry/opentelemetry-go/blob/07a8d195e21336a1f6e691d2c322c5c87e88567c/exporters/trace/jaeger/jaeger.go#L440) supports overwriting the span's resources using the resources from the process. If we remove process configuration for the Jaeger exporter. The overwrite will not be feasible any more, right?

1. > To complete this, the [Jaeger exporter section: Service Name](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md#exporters) part of the spec-compliance-matrix needs to be updated.

    It seems that [OpenTelemetry to Jaeger Transformation : Resource](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/jaeger.md#resource) doesn't mention process configuration for Jaeger at all. Do we still need to update the doc?

**Comment by Aneurysm9** [comment]
>     1. Do we just remove process configuration in Jaeger completely? For example, [jaegerBatchList](https://github.com/open-telemetry/opentelemetry-go/blob/07a8d195e21336a1f6e691d2c322c5c87e88567c/exporters/trace/jaeger/jaeger.go#L440) supports overwriting the span's resources using the resources from the process. If we remove process configuration for the Jaeger exporter. The overwrite will not be feasible any more, right?

I believe that is correct.  The information that could be configured in the `Process` struct that is to be removed can and should be configured in a `Resource` instead.

**Comment by MrAlias** [comment]
> > 1. Do we just remove process configuration in Jaeger completely? For example, [jaegerBatchList](https://github.com/open-telemetry/opentelemetry-go/blob/07a8d195e21336a1f6e691d2c322c5c87e88567c/exporters/trace/jaeger/jaeger.go#L440) supports overwriting the span's resources using the resources from the process. If we remove process configuration for the Jaeger exporter. The overwrite will not be feasible any more, right?
> 
> I believe that is correct. The information that could be configured in the `Process` struct that is to be removed can and should be configured in a `Resource` instead.

agreed ^


> 2. > To complete this, the [Jaeger exporter section: Service Name](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md#exporters) part of the spec-compliance-matrix needs to be updated.
>    
>    It seems that [OpenTelemetry to Jaeger Transformation : Resource](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/jaeger.md#resource) doesn't mention process configuration for Jaeger at all. Do we still need to update the doc?

Not sure I'm following. The original quoted section is for the spec-compliance-matrix. That needs to be updated to show we correctly handle the service name mapping (currently it is marked `-` and linked to this issue for that to be resolved).

The Jaeger transformation docs for resources not mentioning the process configuration for Jaeger is what is consequence of what is motivating this issue: the exporter should not have configuration for the process, it should be derived from the existing `Resource`.
