### ISSUE TITLE
Zipkin exporter: default service name

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#1777]
Currently in the exporter we default to `""` if the resource doesn't contain a service name:

https://github.com/open-telemetry/opentelemetry-go/blob/e9aaa04b8f88b0f8158bd27f72e57d33878f5bdd/exporters/trace/zipkin/model.go#L43-L52

[The specification states](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/trace/sdk_exporters/zipkin.md#service-name):

> If no `service.name` is contained in a Span's Resource, it MUST be populated from the default `Resource`.

While it is a good chance that the passed resource will be a merge with the default, it needs to explicitly be set to the default in the exporter.

**Comment by lastchiliarch** [comment]
I'd like to take this. 
Seems like we should use resource.Default() to get the default resource and then try to get the semconv.ServiceNameKey  as the default service name.

**Comment by MrAlias** [comment]
> Seems like we should use resource.Default() to get the default resource and then try to get the semconv.ServiceNameKey as the default service name.

Correct :+1:

**Comment by MrAlias** [comment]
Resolved by #1786
