### ISSUE TITLE
Jaeger exporter: default service name  typo

### ISSUE THREAD

**Issue by lastchiliarch** [open-telemetry/opentelemetry-go#1783]
### Description

When process the default service name,  use the semconv.ServiceVersionKey  instead of semconv.ServiceNameKey.

Maybe it's a typo.

https://github.com/open-telemetry/opentelemetry-go/blob/e9aaa04b8f88b0f8158bd27f72e57d33878f5bdd/exporters/trace/jaeger/jaeger.go#L502-L507

### Expected behavior

Fix the typo.

**Comment by humivo** [comment]
I can try to make this small fix!  So I just have to change the semconv.ServiceVersionKey to semconv.ServiceNameKey?
