### ISSUE TITLE
RecordBatch mutates the provided slice of attributes

### ISSUE THREAD

**Issue by seanhoughton** [open-telemetry/opentelemetry-go#1787]
### Description

When using meter.RecordBatch the provided set of attributes is sorted by the key. Reusing attribute slices is very convenient if many metrics share a common set of attributes along with a few additional appended on the end. This is unexpected as a user and can create strange bugs if users assume the provided slice will be treated as immutable. 

The in-place sorting happens here: https://github.com/open-telemetry/opentelemetry-go/blob/main/attribute/set.go#L313

### Environment

- opentelemetry-go version: head as of April 8, 2021 - 584328080a31963debf9e41e003937d6494934d3

### Steps To Reproduce

```golang
func TestMutatingAttributes(t *testing.T) {
	_, err := prometheus.InstallNewPipeline(prometheus.Config{})
	if err != nil {
		t.Error(err)
	}
	meter := global.Meter("test")
	counter, err := meter.NewInt64UpDownCounter("example")
	if err != nil {
		t.Error(err)
	}

	ctx := context.Background()
	labels := []attribute.KeyValue{
		attribute.String("B", "val"),
		attribute.String("A", "val"),
	}
	meter.RecordBatch(ctx, labels, counter.Measurement(100))

	if labels[0].Key != "B" {
		t.Errorf("Labels were mutated, expected B, got %s", labels[0].Key)
	}
	if labels[1].Key != "A" {
		t.Errorf("Labels were mutated, expected A, got %s", labels[1].Key)
	}

}
```

### Expected behavior

Either the function docs should clearly indicate that the labels are mutated or a copy of the slice should be used internally before sorting.

**Comment by IrisTuntun** [comment]
Hi, can I take this issue?
