### ISSUE TITLE
Remove the bundler from the Jaeger exporter

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#1799]
The Jaeger exporter currently uses `"google.golang.org/api/support/bundler".Bundler` to batch OpenTelemetry span data:

https://github.com/open-telemetry/opentelemetry-go/blob/99c477feb834abb5121c978eb798e7dd3d36538e/exporters/trace/jaeger/jaeger.go#L214

The bundler was originally added to the exporter prior to the BatchSpanProcessor existing, and it was used to [batch the transformed Jaeger spans](https://github.com/open-telemetry/opentelemetry-go/pull/112/files#diff-e286de1d58cf375910830765e59322519753de6c641ac3243c49d083506098f6R113-R117). Now that the project contains a BatchSpanProcessor and will send batches of span data to exporters, instead of one-by-one, this batching will cause an impedance mismatch as well as additional cognitive load determining which batching scheme to use.

The bundler, by design, is used to "amortizes an action with fixed costs over multiple item". While this amortization is likely not being utilized given we are sending the exporter a batch and then sequentially adding it to the bundler, we still should verify that removing it does not drastically change the resource overhead or performance.

### Needed changes

- [ ] Remove the bundler
- [ ] Remove the associated bundler configuration
- [x] Validate that this does not add excessive resource consumption overhead

**Comment by MrAlias** [comment]
With the bundler in place it was masking the "data too large for a UDP frame error":

https://github.com/open-telemetry/opentelemetry-go/blob/c5d006c07ab78e6b21690e86c859e5f6752d0086/exporters/trace/jaeger/agent.go#L120

If the bundler was configured to have a buffer larger than this frame size that error is returned for every attempt to send. Removing the bundler has exposed this error because now any testing is not being bundled, though production use of the BatchSpanProcessor would be, and it is exposing this error.

It seems like the UDP sends may need to be split or batched intelligently.

**Comment by Aneurysm9** [comment]
> It seems like the UDP sends may need to be split or batched intelligently.

Perhaps the use of the bundler should be shifted there and changed to properly track the size of objects added to the bundle.  I always thought it a bit odd that the bundler was effectively just being used to count the number of spans and not as it was intended.

**Comment by MrAlias** [comment]
> Perhaps the use of the bundler should be shifted there and changed to properly track the size of objects added to the bundle. I always thought it a bit odd that the bundler was effectively just being used to count the number of spans and not as it was intended.

Yeah, that could be a useful use of the bundler. It looks like it might be a bit more complex because it is sending the trift buffer which may not map one-to-one with the spans we enqueue to the bytes buffered. This will make it a bit opaque from our perspective of what size would fit into a frame.

I'm realizing that since this has always been in the code and given we recommend to use the BatchSpanProcessor in production, which should batch effectively and not hit this error either for reasonable batch sizes, we can track the issue and move forward with this.

**Comment by MrAlias** [comment]
> With the bundler in place it was masking the "data too large for a UDP frame error":
> 
> https://github.com/open-telemetry/opentelemetry-go/blob/c5d006c07ab78e6b21690e86c859e5f6752d0086/exporters/trace/jaeger/agent.go#L120
> 
> If the bundler was configured to have a buffer larger than this frame size that error is returned for every attempt to send. Removing the bundler has exposed this error because now any testing is not being bundled, though production use of the BatchSpanProcessor would be, and it is exposing this error.
> 
> It seems like the UDP sends may need to be split or batched intelligently.

Tracking with https://github.com/open-telemetry/opentelemetry-go/issues/1828
