### ISSUE TITLE
End options needed to set explicit stop timestamp

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-go#181]
This is for symmetric with Start options and the explicit start timestamp.

**Comment by matej-g** [comment]
Is still open / unassigned? I'd be happy to have a look too

**Comment by iredelmeier** [comment]
@matej-g still open! Are you still able to take a look?

**Comment by matej-g** [comment]
> @matej-g still open! Are you still able to take a look?

Sure!

**Comment by matej-g** [comment]
So I was having a look, maybe I did not understand the issue correctly, but it seems like the end timestamp (`EndTime`) is already implemented in `EndOptions` (see here: https://github.com/open-telemetry/opentelemetry-go/blob/master/api/trace/api.go#L47). 

Is this correct or am I missing something?

**Comment by iredelmeier** [comment]
@matej-g looks like you're right 👍

Closing as already done.

**Comment by matej-g** [comment]
thanks @iredelmeier, piggybacking off of this discussion, are there any other open issues that I could look into?

**Comment by iredelmeier** [comment]
@matej-g the `good first issue` label/[filter](https://github.com/open-telemetry/opentelemetry-go/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) is usually a good place to start.

If something there catches your key, feel free to comment and one of else will try to assign it to you. If not, let me know here or on Gitter and I can try to do another issue pass!
