### ISSUE TITLE
API should export standards-conventional attribute names

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-go#182]
The strings documented in our standards conventions should be available as exported variables from a standard package in the API.

**Comment by freeformz** [comment]
Why not in the `api` package ?

**Comment by jmacd** [comment]
I agree, this doesn't require a new package.

**Comment by paivagustavo** [comment]
I would like to take this one.

**Comment by iredelmeier** [comment]
Can I ask that we hold off on this for now until after the OpenTelemetry-ified Datadog plugins officially land? Otherwise, I think de-duping things will be a really big mess.

**Comment by paivagustavo** [comment]
Sure @iredelmeier. Also, I was going to hold on this because there is some ongoing work on semantic conventions on the specs repo.

**Comment by rghetia** [comment]
taken care of with resources. if anything missing open a new issue.
