### ISSUE TITLE
trace.Link omits its Attributes field when marshalled to JSON

### ISSUE THREAD

**Issue by toby-allsopp** [open-telemetry/opentelemetry-go#1820]
### Description

Because `trace.Link` embeds `trace.SpanContext` and `trace.SpanContext` has a custom `MarshalJSON` method, `trace.Link`'s other fields, i.e. `Attributes` do not get marshalled.

### Environment

- OS: Windows
- Architecture: amd64
- Go Version: 1.16.3
- opentelemetry-go version: v0.19.0

### Steps To Reproduce

```
json.Marshal(trace.Link{spanContext, []attribute.KeyValue{attribute.String("key", "value")})
```

### Expected behavior

JSON marshalling should include the attributes of the link.

**Comment by IrisTuntun** [comment]
Hi can I take this issue?
