### ISSUE TITLE
Consider using a byte array for `TraceID` (and possibly `SpanID`)

### ISSUE THREAD

**Issue by iredelmeier** [open-telemetry/opentelemetry-go#183]
A 16-byte byte array feels like it would be more intuitive for holding `TraceID`s.

In particular, it would make formatting and conversions (particularly to/from hex) easier, as well as make it easier to use a standard generator such as [UUIDs](https://github.com/gofrs/uuid).

**Comment by paivagustavo** [comment]
I'm working on this. I think we could takeSpa nID on another PR since it's getting big already.

**Comment by jmacd** [comment]
Yes, your TraceID change is great and I agree that SpanID should be done in a separate PR.
