### ISSUE TITLE
Import path should be nested under `go.opentelemetry.io`

### ISSUE THREAD

**Issue by iredelmeier** [open-telemetry/opentelemetry-go#184]
While most of the code is nested somewhere under the root, we currently have [a module](https://github.com/open-telemetry/opentelemetry-go/blob/f863bfbd865b0a00f5b4cc51461465553b351f99/go.mod) directly at the root.

The lack of nesting (e.g., `go.opentelemetry.io/opentelemetry` instead of `go.opentelemetry.io` directly) feels unusual and, more significantly, likely to mess with various go tools, e.g., `go get` and/or go docs.

For comparison, note that https://godoc.org/go.opentelemetry.io shows this repo's code, whereas something like https://godoc.org/google.golang.org 404s. I imagine that adding other repos under `go.opentelemetry.io` will mess with godoc.org.

**Comment by jmacd** [comment]
LGTM

**Comment by rghetia** [comment]
use go.opentelemetry.io/otel

**Comment by lizthegrey** [comment]
this appears to have broken godoc.org and https://godoc.org/go.opentelemetry.io/otel is empty. https://godoc.org/go.opentelemetry.io still displays the old code.
