### ISSUE TITLE
Suggestion: rename `CurrentSpan`/`SetCurrentSpan`

### ISSUE THREAD

**Issue by iredelmeier** [open-telemetry/opentelemetry-go#185]
Thoughts on renaming these to `SpanFromContext` and `ContextWithSpan` to be more idiomatic?

**Comment by VineethReddy02** [comment]
Hey, @iredelmeier I would like to work on this. Could you help me what are exact changes required?
Could you please point me some good first issues in getting started to contribute to open-telemetry.

**Comment by iredelmeier** [comment]
@VineethReddy02 the change for this should basically be a find-and-replace for the function provided in [current.go](https://github.com/open-telemetry/opentelemetry-go/blob/3516ebc456c7ce437d6c12071e44d90b029fc2aa/api/trace/current.go) (which should probably also be renamed!) and their usages.

With the caveat that a PR implementing this suggestion may get rejected on the basis of the suggestion itself getting rejected, this would definitely be a good first issue! Inconveniently, I'm unable to modify issue labels in this repo.

Some more good first issues (definitely non-exhaustive!):

* #181 
* #184 (blocked on some decision-making)
* #186 (possibly)
* #192 
* #195

**Comment by rakyll** [comment]
See also https://github.com/open-telemetry/opentelemetry-go/issues/299.

**Comment by iredelmeier** [comment]
@VineethReddy02 are you still able to work on this?

**Comment by VineethReddy02** [comment]
Hey @iredelmeier so what ```CurrentSpan``` & ```SetCurrentSpan``` should be renamed to?

**Comment by iredelmeier** [comment]
@VineethReddy02 `CurrentSpan` -> `SpanFromContext` and `SetCurrentSpan` -> `ContextWithSpan`

**Comment by jmacd** [comment]
@rakyll proposed "WithSpan" as opposed to "ContextWithSpan". What do you think? I do feel that "Context" adds stutter here. If we went with "WithSpan", what's the opposite name? (I still like `CurrentSpan`). Also if we went with "WithSpan", there's a `Tracer.WithSpan`, similar to `trace.WithRegion` in the builtin library, that creates confusion.

**Comment by paivagustavo** [comment]
I like more `trace.ContextWithSpan` (it is a little verbose but more clear than `trace.WithSpan` that could be misleading) and `trace.CurrentSpan`.

**Comment by jmacd** [comment]
Although the PR merged, I am open to renaming `trace.SpanFromContext` to `trace.CurrentSpan`.

**Comment by rghetia** [comment]
stale issue.
