### ISSUE TITLE
Should `WithRecord` override the span context's sampled flag?

### ISSUE THREAD

**Issue by iredelmeier** [open-telemetry/opentelemetry-go#187]
Currently in the SDK, a span must be both "sampled" - i.e., it's span context's sampled flag must be true - and "recorded" - e.g., through `WithRecord` or the sampling decision - in order to actually be exported.

Should `WithRecord` be sufficient to guarantee that the span will be exported?

This could be useful in cases where, e.g., an upstream service is sampling too aggressively.

**Comment by rghetia** [comment]
Both sampled and record flags are required.
