### ISSUE TITLE
Links provided to Span.End are silently dropped

### ISSUE THREAD

**Issue by packetmpm** [open-telemetry/opentelemetry-go#1878]
### Description

The sdk impl of `span.End` discards any `trace.Link`s provided via `trace.SpanOption`. This exclusion is documented in _implementation_ (i.e. in `sdk.span`) but is not mentioned of it in the published API (`trace.Span`).

My use case is nearly identical to the one laid out in the spec - a batch process wherein I'd like to link the batch's single span with spans of all the data items that are processed. I can't supply the links at span creation time because I don't know them yet so I can only buffer them into a slice and then supply them to `Span.End`. Of course, per the previous paragraph this approach does not work.

https://github.com/open-telemetry/opentelemetry-go/blob/42a845093e93d69415ec335f0226ceee59839277/sdk/trace/span.go#L188-L189

### Environment

- OS: All
- Architecture: All
- Go Version: All
- opentelemetry-go version: v0.20.0

### Steps To Reproduce

Add a link to a span as part of the `span.End` call.

```.go
span.End(trace.WithLinks(trace.Link{SpanContext: sc}))
```

### Expected behavior

Expect the link to be added to the span's state (it is not).

**Comment by packetmpm** [comment]
Just found this language in the spec

> Links cannot be added after Span creation

I disagree with the spec as it undercuts the usefulness of links but fair play to the implementation, it's doing the "right" thing.

**Comment by MrAlias** [comment]
We need to look into splitting start and end options again to engineer away this confusion.
