### ISSUE TITLE
Example of using Istio with OpenTelemetry

### ISSUE THREAD

**Issue by skhalash** [open-telemetry/opentelemetry-go#1896]
### Problem Statement

When playing around with Istio using OpenTelemetry as an instrumentation library, I found no quick example on the web that illustrates such scenarios. Since I didn't have any prior experience with OpenTelemetry SDK, the following points were not clear to me:

* Context propagation API is decoupled from span creation API (unlike in `OpenTracing`). So you can just use a `context propagator` and you don't need any `tracer` if you only rely on spans created by Envoy proxies
* What if you do want to create some spans _in between_ proxy spans?
* Where to look for the OpenZipkin header propagator?

I'd like to contribute to the project by adding an example of using Istio with OpenTelemetry that addresses the above-mentioned problems to save folks like me some time. Do you think it will be of any use?

### Proposed Solution

An example of using Istio's automatic spans OpenTelemetry that ties them together.

**Comment by sanjaygopinath89** [comment]
@skhalash I am looking for an example for the same use case. Can you give some pointers on how I can link the span generated from OTEL golang application and the span generated from Istio/Envoy proxy so that it can be part of a single trace  ..?

**Comment by pangsq** [comment]
There is an example in this repo - https://github.com/open-telemetry/opentelemetry-go/tree/main/example/passthrough.
It guides how to pass through context with spans which can be used in istio. 

However, it seems opentelemetry's propagators do not support the zipkin headers(x-b3-xxx) generated by envoy (as described in https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#x-b3-traceid).
And I find a b3propagation in `go.opencensus.io/plugin/ochttp/propagation/b3`, so I write a b3propagator in my gists(https://gist.github.com/pangsq/a14545ec19e9c2c473b8f0430d53ce02). Hope it helps.

**Comment by MrAlias** [comment]
The B3 propagator is found [here](https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/propagators/b3).
