### ISSUE TITLE
BatchSpanProcessor Cause a memory leak

### ISSUE THREAD

**Issue by tensorchen** [open-telemetry/opentelemetry-go#1904]
### Description

BatchSpanProcessor Cause a memory leak

### Environment

- OS: [MacOS]
- Go Version: [e.g. 1.16]
- opentelemetry-go version: [v0.20.0]
- opentelemetry-go-contrib-otelgrpc [v0.20.0]

### Steps To Reproduce

1. Change `opentelemetry-go-contrib-otelgrpc config.Init()` to the code：

```
driver := otlpgrpc.NewDriver(otlpgrpc.WithEndpoint("127.0.0.1:12520"))
	exporter, err := otlp.NewExporter(context.Background(), driver)
	if err != nil {
		log.Fatal(err)
	}
	kvs := []attribute.KeyValue{
		semconv.TelemetrySDKLanguageGo,
		semconv.TelemetrySDKNameKey.String("xxx"),
	}
	res := resource.NewWithAttributes(kvs...)
	tp := sdktrace.NewTracerProvider(
		sdktrace.WithSampler(sdktrace.AlwaysSample()),
		sdktrace.WithBatcher(exporter),
		sdktrace.WithResource(res),
	)
	otel.SetTracerProvider(tp)
	otel.SetTextMapPropagator(propagation.NewCompositeTextMapPropagator(propagation.TraceContext{}, propagation.Baggage{}))
```

2. start grpc server

3.  start grpc client

```
ghz --insecure --proto hello-service.proto --call api.HelloService.SayHello -d '{"greeting":"tensorchen"}' -z 20m 127.0.0.1:7777
```

4. Result

![image](https://user-images.githubusercontent.com/16510475/117952430-becba880-b347-11eb-899d-84f8b1febebe.png)

![image](https://user-images.githubusercontent.com/16510475/117952531-d30fa580-b347-11eb-9ac2-74eb8d073a08.png)

**Comment by tianyaqu** [comment]
Duplicate with #1833 and resoleved by #1860.  The cause of the leak is batch span processor will never drop the bathced spans when get an exporting failure, thus making the size of batched spans larger than the grpc message body.
