### ISSUE TITLE
Document the "Passthrough" use-case

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#1908]
It would be nice to document the "Passthrough" use-case where no SDK is registered but span context from a request is passed through the tracing system. Ideally this will include an example.

_Originally posted by @dashpole in https://github.com/open-telemetry/opentelemetry-go/issues/1893#issuecomment-839931590_

**Comment by dashpole** [comment]
I'm happy to take this on.  I'll start after https://github.com/open-telemetry/opentelemetry-go/pull/1901 is merged
