### ISSUE TITLE
Remove `WithRecording` option from trace API

### ISSUE THREAD

**Issue by iredelmeier** [open-telemetry/opentelemetry-go#192]
This option needs to be removed before the GA release. The specification decision on how to resolve this issue has been postponed until after GA. To reduce the maintenance burden of this code after GA and to ensure we can support the future resolution of this issue at the specification level we need to remove this option.

Work needs to be done to explore how this option can be removed and still conform to the SDK specification sampling.

**Comment by danstephen88** [comment]
Say again

**Comment by paivagustavo** [comment]
When we tried to remove this (#223), we found out about the problem discussed in #224. Blocking this until https://github.com/open-telemetry/opentelemetry-specification/issues/307 to be resolved.

**Comment by MrAlias** [comment]
Info from duplicate issue #787

> Was there ever a resolution to [open-telemetry/opentelemetry-specification#307](https://github.com/open-telemetry/opentelemetry-specification/issues/307)
> 
> I see @paivagustavo tried in #223 to do this, and ran into the same problem that `span.SetName()` requires a resampling decision. In the Go implementation, if the span did not already have `IsRecording() == true`, then there's no data for it to make that decision.
> 
> It doesn't look like there has been any change made to the specification and thus calling `SetName()` still seems to require another call to the sampler.
> 
> Found some more issues related to this for background reading:
> [open-telemetry/opentelemetry-specification#468](https://github.com/open-telemetry/opentelemetry-specification/issues/468)
> #224
> 
> and more recently
> 
> [open-telemetry/opentelemetry-specification#620](https://github.com/open-telemetry/opentelemetry-specification/issues/620)
> [open-telemetry/opentelemetry-specification#634](https://github.com/open-telemetry/opentelemetry-specification/issues/634)
