### ISSUE TITLE
Allow SpanContext to be serialized/deserialized to JSON

### ISSUE THREAD

**Issue by michaelperel** [open-telemetry/opentelemetry-go#1927]
### Problem Statement
I am using [Redis' PubSub](https://redis.io/topics/pubsub) feature (specifically via [go-redis](https://github.com/go-redis/redis)), and would like to implement distributed tracing. Specifically:

Microservice A publishes a message of bytes that represent JSON to a channel.

Microservice B subscribes to the channel, consume the messages, and does work.

I would like Microservice B to create child spans of a span in Microservice A (or at least link the spans in Microservice B to Microservice A). Unfortunately, I don't see a way to inject headers in this pubsub system as you would via HTTP.

To overcome this, I would like to pass the [SpanContext](https://pkg.go.dev/go.opentelemetry.io/otel/trace#SpanContext) in the JSON message from Microservice A.

**Unfortunately, when Microservice B Unmarshals the SpanContext, it is empty because the fields are unexported.**

### Proposed Solution
Export the fields of SpanContext so that it can be easily passed around via JSON when propagating context or provide documentation on how to propagate context when not using HTTP.

#### Alternatives
Perhaps there is another way to propagate context in messaging systems using arbitrary wire protocols?

**Comment by Aneurysm9** [comment]
The [propagation API](https://pkg.go.dev/go.opentelemetry.io/otel@v0.20.0/propagation) should be used to achieve this.  The propagation system can utilize any type that implements the [`TextMapCarrier` interface](https://pkg.go.dev/go.opentelemetry.io/otel@v0.20.0/propagation#TextMapCarrier), not just HTTP headers.  This is used by the [Sarama instrumentation](https://pkg.go.dev/go.opentelemetry.io/contrib/instrumentation/github.com/Shopify/sarama#ConsumerMessageCarrier) to propagate trace context information using Kafka headers.  I'm not familiar with Redis' PubSub, so I don't know whether it has headers, but if it does they'd be a great choice.  If it doesn't and you're in control of both ends of the communication and are able to transmit the data in-band, that is also an option.  To do that you'd want to implement a simple carrier using a type that can be round-tripped through JSON.

As for exporting the fields of the `SpanContext` type, the spec requires that a span context is immutable and we have ensured this by not exporting any fields.  We also want to avoid accidental reliance on the internals of that type for propagation of the sort that you've described as we make no guarantees regarding its structure or contents.

**Comment by michaelperel** [comment]
Thanks, this worked perfectly
