### ISSUE TITLE
bridge/opencensus: Causing infinite trace exporting as exporter traces itself

### ISSUE THREAD

**Issue by ahmetb** [open-telemetry/opentelemetry-go#1928]
### Description

When I use `bridge/opencensus` along with `trace.WithBatcher` and GCP's span exporter (`github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/trace`), I get an infinite loop of Batch upload RPCs' own traces triggering more Batch uploads.

My motive of using opencensus bridge is to tap into builtin OpenCensus Tracing capabilities in many GCP Client Libraries that are already in place (but not captured in OpenTelemetry).

### Environment

- OS: linux
- Architecture: x86_64
- Go Version: 1.16
- opentelemetry-go version: v0.20.0

### Steps To Reproduce

```go
gcp, err := texporter.NewExporter()
// handle err

tracer := trace.NewTracerProvider(trace.WithBatcher(gcp,
		trace.WithBatchTimeout(time.Millisecond*200),
		trace.WithMaxExportBatchSize(10)),
		trace.WithSampler(trace.AlwaysSample()))

otel.SetTracerProvider(tracer)
tp := otel.GetTracerProvider().Tracer("my-server")

// register opencensus bridge
octrace.DefaultTracer = opencensus.NewTracer(tp)
```

Once I do this:

1. **Good:** It successfully exports OpenCensus spans (from GCP client libraries) to OpenTelemetry and they show up on Google Cloud Trace.

2. **Bad:** My theory is that the batch uploader gets caught up in a loop. As soon as it starts pushing traces out, the "google.devtools.cloudtrace.v2.TraceService.BatchWriteSpans" span is also written into the exporter, so there's always something to export and I get a flood of spans that are just completely useless.

> ![image](https://user-images.githubusercontent.com/159209/118582187-caeca700-b747-11eb-8b04-8187f071bbe2.png)

Span details of these spam traces from the tracer's own upload RPC:

> 
![image](https://user-images.githubusercontent.com/159209/118582338-01c2bd00-b748-11eb-865e-0544f2f9e557.png)

### Expected behavior

No infinite loops and trace span list being polluted.

cc: @dashpole @ymotongpoo

**Comment by dashpole** [comment]
Thanks for reporting this!  I'll take a look today

**Comment by dashpole** [comment]
I'm having a bit of a hard time reproducing, and i'm trying to figure out if it is specific to the opencensus bridge.  Can you try replacing:
```golang
// register opencensus bridge
octrace.DefaultTracer = opencensus.NewTracer(tp)
```
with
```golang
_, span = tp.Start(ctx, "operation")
span.End()
```

**Comment by ahmetb** [comment]
I am not having trouble using OpenTracing. So tp.Start/End already works fine (notice the dots in the chart outside that crowded cloud).

The issue only happens if I set `octrace.DefaultTracer` with the instructions provided in bridge repo. https://github.com/open-telemetry/opentelemetry-go/blob/main/bridge/opencensus/README.md#user-journey

Feel free to hit me up internally on Chat, I can present a demo app.

**Comment by dashpole** [comment]
Figured it out.  By default, the opentelemetry-go client adds OpenCensus telemetry. You can disable it with a client option: https://github.com/googleapis/google-api-go-client/blob/f9bd89c838efc8b3decfafdda789e8907c11963d/option/option.go#L232


```golang
import "google.golang.org/api/option"

gcp, err := texporter.NewExporter(texporter.WithTraceClientOptions(option.WithTelemetryDisabled()))
```

The trace client telemetry is probably useful, so long as you have a low sampling ratio.  But with AlwaysSample() you get an infinite loop of sending.

**Comment by ahmetb** [comment]
OK that helps me a lot. I did not know trace client telemetry could be useful to some.
