### ISSUE TITLE
Otlp HTTP exporter wrong output for JSON marshaler

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-go#1939]
See https://github.com/open-telemetry/opentelemetry-collector/issues/3195

It seems that the exporter marshals the ids as base64 (default proto json encoding for bytes fields), but base on the specs https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md#otlphttp-request they must be base16 (hex)

**Comment by Aneurysm9** [comment]
See @MrAlias' comment on https://github.com/open-telemetry/opentelemetry-go/issues/1924#issuecomment-845474851.  We're going to remove `http/json` from the OTLP exporter for now.
