### ISSUE TITLE
Add Schema support

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-go#1948]
### Problem Statement

The specification recently added the concept of Schema. We need to add a corresponding implementation in the API and SDK.

### Proposed Solution

Here is the proposal in the form of draft PRs:

- Tracer API changes: https://github.com/open-telemetry/opentelemetry-go/pull/1889 (Similar changes will be needed for the Meter).
- Resource SDK changes: https://github.com/open-telemetry/opentelemetry-go/pull/1938
- Generate semantic conventions according to specification version: https://github.com/open-telemetry/opentelemetry-go/pull/1933

**Comment by tigrannajaryan** [comment]
@Aneurysm9 @MrAlias I have 3 draft PRs that show the extent of necessary changes. How do you prefer to move forward? Should I now polish each individual PR and merge each as it is ready or you prefer all 3 to be fully cooked and only after that merge all 3 at once?

**Comment by Aneurysm9** [comment]
I think the draft PRs are already pretty close to mergeable, so polishing them individually would be fine by me.

**Comment by MrAlias** [comment]
> I think the draft PRs are already pretty close to mergeable, so polishing them individually would be fine by me.

Agreed!

I'm okay with merging them separately. We will be sure to hold off releasing until they are all merged.

**Comment by MadVikingGod** [comment]
With all of these merged can we close this? @Aneurysm9 @MrAlias
