### ISSUE TITLE
When running the TestDisconnected function of the otlp_integration_test.go file appears error

### ISSUE THREAD

**Issue by zhyChesterCheung** [open-telemetry/opentelemetry-go#1951]
### Description

When running `make test` according to the `CONTRIBUTING.md`, I found something wrong with `TestDisconnected` function. The error message is that as newGRPCExporter() was called and then `tracesDriver` start a connection, it occurs WaitForStateChange error. But after I comment out the `otlpgrpc.WithDialOption()` used in `newGRPCExporter` function as a param, the test case could access normally. Please make sure if the `otlpgrpc.WithDialOption()` configuration should be there in this test function thx.

### Environment

- OS: MacOS X 10.15.7
- Architecture: amd64
- Go Version: Both 1.16.3 & 1.15.6
- opentelemetry-go version: v0.19.0

### Steps To Reproduce

1. Clone the latest repo as the source code with `https://github.com/open-telemetry/opentelemetry-go`
2. Run `make test` as `CONTRIBUTING.md` going
3. See error with panic: test timed out, which is caused by `TestDisconnected` function in `otlp_integration_test.go` file

### Expected behavior

It could be helpful if all of the test case can run successfully so that other guys could get started faster to contribute. Great honor~!

**Comment by dashpole** [comment]
I am not able to reproduce this...  Can anyone else?

**Comment by gizmo-rt** [comment]
@zhyChesterCheung Test works perfectly fine for mentioned environment  specification.

**Comment by p0r7m** [comment]
@zhyChesterCheung Test works perfectly fine for mentioned environment  specification.

**Comment by MrAlias** [comment]
I am unable to reproduce.

```sh
$ uname -s -r -v -m -o    
Linux 5.12.3-arch1-1 #1 SMP PREEMPT Wed, 12 May 2021 17:54:18 +0000 x86_64 GNU/Linux

$ git rev-parse --verify HEAD                                          
aed458026f8171751eb415f37f2815629fcd0848

$ go version
go version go1.16.4 linux/amd64

$ make test > /dev/null; echo $?
0
```

**Comment by Aneurysm9** [comment]
The old OTLP exporter (and thus this test) was removed in #1990.  Feel free to create a new issue if this error is reproducible with the new exporter implementation.
