### ISSUE TITLE
how to make use of span link? help wanted

### ISSUE THREAD

**Issue by xinnjie** [open-telemetry/opentelemetry-go#1966]
As current description of `Link`
> A Span may be linked to zero or more other Spans (defined by SpanContext) that are causally related. Links can point to Spans inside a single Trace or across different Traces. Links can be used to represent batched operations where a Span was initiated by multiple initiating Spans, each representing a single incoming item being processed in the batch.

Once we attach `Link` to span, how do we make use of it in grafana query?
Suppose I attach a `Link` to span A (in traceA ) to spanB (in traceB), can I get result of traceB when querying traceA in grafana?

**Comment by MrAlias** [comment]
Thanks for your interest in the project! This project helps define what a `Link` is and how to create one, but it does not specify how it is interpreted. This question is something the Grafana community will need to answer.

**Comment by xinnjie** [comment]
> Thanks for your interest in the project! This project helps define what a `Link` is and how to create one, but it does not specify how it is interpreted. This question is something the Grafana community will need to answer.

Thanks for you reply!
