### ISSUE TITLE
Generate semconv package for 1.4.0

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-go#1975]
Now that spec 1.4.0 is release we need to generate semconv 1.4.0 and update SDK's resource detectors to use it.

I can generate semconv/trace.go and semconv/resources.go using the generator but I don't know how to generate semconv/http.go, exception.go, etc.

@MrAlias @Aneurysm9 can you help?

**Comment by MrAlias** [comment]
We should also document this process and decide on https://github.com/open-telemetry/opentelemetry-collector/issues/2600

**Comment by tigrannajaryan** [comment]
It is partially documented here https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#semantic-convention-generation but only says how to generate trace.go and resource.go.

**Comment by MrAlias** [comment]
> It is partially documented here https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#semantic-convention-generation but only says how to generate trace.go and resource.go.

Ah, gotcha. I missed that :+1:

**Comment by MrAlias** [comment]
@tigrannajaryan I think the `http.go` and `exception.go` hand crafted and not generated because they do not have [yaml definitions](https://github.com/open-telemetry/opentelemetry-specification/tree/main/semantic_conventions). I think if you run the generator based on the docs you shared that you should accomplish all that we can with the generation.

**Comment by tigrannajaryan** [comment]
> they do not have [yaml definitions](https://github.com/open-telemetry/opentelemetry-specification/tree/main/semantic_conventions).

I see some yamls: https://github.com/open-telemetry/opentelemetry-specification/blob/main/semantic_conventions/trace/http.yaml and https://github.com/open-telemetry/opentelemetry-specification/blob/main/semantic_conventions/trace/exception.yaml

**Comment by MrAlias** [comment]
> I see some yamls: https://github.com/open-telemetry/opentelemetry-specification/blob/main/semantic_conventions/trace/http.yaml and https://github.com/open-telemetry/opentelemetry-specification/blob/main/semantic_conventions/trace/exception.yaml

Interesting, I must have misunderstood the generation gap for these files then. @Aneurysm9 is going to have a lot more context here.

**Comment by Aneurysm9** [comment]
> > they do not have [yaml definitions](https://github.com/open-telemetry/opentelemetry-specification/tree/main/semantic_conventions).
> 
> I see some yamls: https://github.com/open-telemetry/opentelemetry-specification/blob/main/semantic_conventions/trace/http.yaml and https://github.com/open-telemetry/opentelemetry-specification/blob/main/semantic_conventions/trace/exception.yaml

Those are generated into `trace.go`.  `http.go` contains two values we've used commonly in instrumentation that aren't in the conventions as an enumeration and some helper functions that can probably just be copied wholesale.  `exception.go` includes a constant for the event name used with exceptions that could probably move closer to where it is used if it isn't going to be included in the conventions.

**Comment by tigrannajaryan** [comment]
So do we just copy existing http.go and exeception.go and we should be good?
