### ISSUE TITLE
Exporter convenience functions do not set a service name by default

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#1979]
The `InstallNewPipeline` and `NewExportPipeline` create a `TracerProvicer` that does not have any `Resource` associated with it. This means that by default the service name, a required attribute, will not be set and the default value will be used. The purpose of these functions was to provide users with a simple one-call solution to setup exporters with all the required values included and production level configuration set. Not setting the service name means these functions are not serving their purpose.

## Possible solutions

1. Remove these functions. They can be useful, but, as this issue points out, their API may not be the most validate with user feedback. Removing these functions prior to a stable release means they can be added back in with more context from measured use.
2. Add a way for the service name to be passed.
   1. Add an argument for the service name. This will resolve this issue, but will not be extensible.
   2. Add a configuration/options that include the service name as arguments. This will solve this issue, but will be cumbersome and add API bloat.
3. Leave it as is. These functions will remain incomplete in their setup with best practices but they can be documented that you should not use them if you want your service to be identified, or that you should use environment variables.

**Comment by seh** [comment]
I favor removing the functions until we can come up with a better interface. We should be encouraging use of Resources, rather than making it easier to ignore them.

**Comment by Aneurysm9** [comment]
I second removing them.  While useful, they're also limiting and add API surface that we may not need to carry.  I also think they're candidates for later specification/conventionalization when the configuration/convenience WG starts making recommendations.
