### ISSUE TITLE
Container Resource MetaData auto detection in Resource SDK 

### ISSUE THREAD

**Issue by pavankrish123** [open-telemetry/opentelemetry-go#1981]
### Problem Statement

In the spirit of what was done in #1788 #1840 for Process and Operating system auto detection - It is worthwhile to have an auto detection processor that collects and reports container information `container.id` and ~`container.name`.~

### Proposed Solution

Most of the container runtime environments (Docker, CRI-O, and containerd) have this informaton in cgroup files on the container filesystem. Resource SDK initialization goes through these files and fetches it. 

#### Alternatives

Other option is to set environment variables on containers. But that is still sort of manual thing to do or some orchestration agent does it (like K8, PAAS environement)    

cc: @stevebappd

**Comment by jmacd** [comment]
@pavankrish123 How would you detect the container name in K8s, by the way? I've heard concerns about using the K8s API server for this because of load.

**Comment by pavankrish123** [comment]
@jmacd - At least our idea is to tap into container filesystem (different locations for different runtimes) and derive this information rather than touch  k8 apis. As you correctly mentioned accessing K8 apis is definitely not healthy. 

Here is a feature our team has pushed recently on Java side https://github.com/open-telemetry/opentelemetry-java/pull/3321 to do the same w/o using K8 downward apis. 

cc: @lo-jason @stevebappd

**Comment by jmacd** [comment]
@pavankrish123 This is great to hear. Very cool!

**Comment by pavankrish123** [comment]
@jmacd  I Fixed the description (Struck off the `contianer.name` ask) -  I believe  only `container.id`  can be derived through filesystem (PR https://github.com/open-telemetry/opentelemetry-java/pull/3321) . `container.name` I am not sure. 

Good catch 👍🏼

**Comment by jmacd** [comment]
This interests me because Prometheus goes to great lengths to fill in this kind of name as a label without hammering the k8s API. If we could get basic resource information like this in the SDK itself, would be a huge win. I didn't think it was possible w/o modifying the k8s object...
