### ISSUE TITLE
Error: TraceID has no field or method String

### ISSUE THREAD

**Issue by androna-xm** [open-telemetry/opentelemetry-go#1995]
I am using `go.opentelemetry.io/otel/trace v0.20.0` and i am trying to extract the TraceID by
`traceID := trace.SpanContextFromContext(ctx).TraceID.String()`
(as i saw from a tutorial, with probably a previous version )
Now, however, i get this error
`"go.opentelemetry.io/otel/trace".SpanContextFromContext(ctx).TraceID.String undefined (type func() "go.opentelemetry.io/otel/trace".TraceID has no field or method String)`
I checked and the return type of trace.SpanContextFromContext(ctx).TraceID is not string , so how could i get the traceID as a string?

**Comment by MrAlias** [comment]
https://pkg.go.dev/go.opentelemetry.io/otel/trace#SpanContext.TraceID

![20210611_075704](https://user-images.githubusercontent.com/5543599/121706619-a657c680-ca8a-11eb-905b-5c97db84beac.png)

```go
trace.SpanContextFromContext(ctx).TraceID().String()
```
