### ISSUE TITLE
Error : TraceID has no field or method String

### ISSUE THREAD

**Issue by androna-xm** [open-telemetry/opentelemetry-go#1996]
I am using go.opentelemetry.io/otel/trace v0.20.0 and i am trying to extract the TraceID by 
`traceID := trace.SpanContextFromContext(ctx).TraceID.String()` 
(as i saw from a tutorial, with probably a previous version )
Now, however, i get this error 
`"go.opentelemetry.io/otel/trace".SpanContextFromContext(ctx).TraceID.String undefined (type func() "go.opentelemetry.io/otel/trace".TraceID has no field or method String)`
I checked and the return type of trace.SpanContextFromContext(ctx).TraceID is not string , so how could i get the traceID as a string?

**Comment by MrAlias** [comment]
Answered in https://github.com/open-telemetry/opentelemetry-go/issues/1995

https://github.com/open-telemetry/opentelemetry-go/issues/1995#issuecomment-859641369
