### ISSUE TITLE
Exporter to Zipkin , connection refused

### ISSUE THREAD

**Issue by androna-xm** [open-telemetry/opentelemetry-go#1999]
I have zipkin running  in a container

> services:
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
 
and its logs show that everything is ok `Serving HTTP at /0.0.0.0:9411 - http://127.0.0.1:9411/`

I also followed this https://github.com/open-telemetry/opentelemetry-go/blob/example/zipkin/v0.20.0/example/zipkin/main.go to create a zipkin exporter 
with this URL "http://localhost:9411/api/v2/spans"

However i get this error from the container that my instrumented app is running :
`request to http://localhost:9411/api/v2/spans failed: Post "http://localhost:9411/api/v2/spans": dial tcp 127.0.0.1:9411: connect: connection refused`

Any ideas how could i solve this?

**Comment by MrAlias** [comment]
Can you please include your runtime environment (i.e. the stuff listed in the [bug report template](https://github.com/open-telemetry/opentelemetry-go/blob/main/.github/ISSUE_TEMPLATE/bug_report.md)) and the code that is causing your error?

**Comment by MrAlias** [comment]
I'm not able to reproduce with the current info. Please reopen with more info if this is still a bug for you.
