### ISSUE TITLE
How to become a reviewer / get involved?

### ISSUE THREAD

**Issue by cstockton** [open-telemetry/opentelemetry-go#2]
I've read the documentation at https://github.com/open-telemetry/community/blob/master/community-membership.md - I do not see the path to becoming a reviewer- only how to become an approver (by being a reviewer for at least 3 months) or how the current owners were selected. I would like to be involved in the initial design and implementation of this project in whatever ways I can, how do I do that?

**Comment by bogdandrutu** [comment]
We will publish soon a meeting that you should join, then start reviewing/write PRs. After you prove that you know enough about the project and people will propose you as approver you can become approver. Just to review or write PRs you don't need any status

**Comment by cstockton** [comment]
Okay thanks a lot- where will the announcement for the meeting be published so I can keep an eye out?

**Comment by SergeyKanzhelev** [comment]
Here: https://github.com/open-telemetry/community#golang-sdk

**Comment by SergeyKanzhelev** [comment]
Closing for now.
