### ISSUE TITLE
Cannot resolve the go.opentelemetry.io/otel/semconv/v1.4.0 pacakge

### ISSUE THREAD

**Issue by AchoArnold** [open-telemetry/opentelemetry-go#2000]
### Description

When I try to follow the example [here](https://github.com/open-telemetry/opentelemetry-go/blob/main/example/jaeger/main.go) to initialize the jaeger exporter, I get the error 

```
go.opentelemetry.io/otel/semconv/v1.4.0: module go.opentelemetry.io/otel@latest found (v0.20.0), but does not contain package go.opentelemetry.io/otel/semconv/v1.4.0
```

### Environment

- OS: Windows
- Architecture: x86
- Go Version: 1.15
- opentelemetry-go version:  v0.20.0

### Steps To Reproduce

1. git clone git@github.com:open-telemetry/opentelemetry-go.git
2. cd example/jaeger
3. rm -rf go.mod go.sum
4. go get -v ./...

### Expected behavior

I expected it to fetch all the otel packages but for some reason it can't resolve the `go.opentelemetry.io/otel/semconv/v1.4.0` package.

If I do `got mod init temp` It get the following file

```go.mod
module temp

go 1.15

require (
        go.opentelemetry.io/otel v0.20.0
        go.opentelemetry.io/otel/exporters/jaeger v0.0.0-20210612183922-3be9813d56ff
        go.opentelemetry.io/otel/sdk v0.20.0
)
```

**Comment by Aneurysm9** [comment]
It looks like you're mixing released and unreleased versions of modules.  If you use `go.opentelemetry.io/otel/exporters/jaeger v0.20.0` you should not have this issue.  Alternately, do not remove the `go.mod` file that has `replace` directives that allow the use of local copies of its dependencies that are in sync.

**Comment by AchoArnold** [comment]
Hello @Aneurysm9 , Please how do  install the v0.20.0 of `go.opentelemetry.io/otel/exporters/jaeger` ? When I do go get `go.opentelemetry.io/otel/exporters/jaeger` it automatically downloads the `v0.0.0-20210612183922-3be9813d56ff` version.

**Comment by marcosrmendezthd** [comment]
i'm getting a similar error.

```
go: go.opentelemetry.io/otel/exporters/jaeger@v0.20.0: reading go.opentelemetry.io/otel/exporters/jaeger/exporters/jaeger/go.mod at revision exporters/jaeger/v0.20.0: unknown revision exporters/jaeger/v0.20.0
```

**Comment by MrAlias** [comment]
@AchoArnold `go.opentelemetry.io/otel/exporters/jaeger` has not be released yet, please use the versioned `go.opentelemetry.io/otel/exporters/trace/jaeger` package.

```sh
go get go.opentelemetry.io/otel/exporters/trace/jaeger@v0.20.0
```

**Comment by rahulkarmore** [comment]
Hi @MrAlias I used your solution, it work form me for the time being, 
`go get go.opentelemetry.io/otel/exporters/trace/jaeger@v0.20.0
go: upgraded go.opentelemetry.io/otel v0.15.0 => v0.20.0
go: upgraded go.opentelemetry.io/otel/exporters/trace/jaeger v0.15.0 => v0.20.0
go: added go.opentelemetry.io/otel/metric v0.20.0
go: upgraded go.opentelemetry.io/otel/sdk v0.15.0 => v0.20.0
go: added go.opentelemetry.io/otel/trace v0.20.0`

but when I will perform go mod tidy it will give me below error again

`  go.opentelemetry.io/otel/label: module go.opentelemetry.io/otel@latest found (v1.24.0), but does not contain package go.opentelemetry.io/otel/label
basicRepo/src/telemetry imports
        go.opentelemetry.io/otel/exporters/trace/jaeger imports
        go.opentelemetry.io/otel/semconv: module `

here is the imports 
![image](https://github.com/open-telemetry/opentelemetry-go/assets/42960205/517555ba-c4a1-4384-a71a-a4f5d7c2a535)

**Comment by MrAlias** [comment]
> go.opentelemetry.io/otel/exporters/trace/jaeger

Please open a new issue to address your comment. You are using `go.opentelemetry.io/otel/label` and, as the error message points out, that package is not used in the stable versions of OTel.

**Comment by MrAlias** [comment]
> Hi @MrAlias I used your solution, it work form me for the time being, `go get go.opentelemetry.io/otel/exporters/trace/jaeger@v0.20.0 go: upgraded go.opentelemetry.io/otel v0.15.0 => v0.20.0 go: upgraded go.opentelemetry.io/otel/exporters/trace/jaeger v0.15.0 => v0.20.0 go: added go.opentelemetry.io/otel/metric v0.20.0 go: upgraded go.opentelemetry.io/otel/sdk v0.15.0 => v0.20.0 go: added go.opentelemetry.io/otel/trace v0.20.0`
> 
> but when I will perform go mod tidy it will give me below error again
> 
> ` go.opentelemetry.io/otel/label: module go.opentelemetry.io/otel@latest found (v1.24.0), but does not contain package go.opentelemetry.io/otel/label basicRepo/src/telemetry imports go.opentelemetry.io/otel/exporters/trace/jaeger imports go.opentelemetry.io/otel/semconv: module`
> 
> here is the imports ![image](https://private-user-images.githubusercontent.com/42960205/312924315-517555ba-c4a1-4384-a71a-a4f5d7c2a535.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MzUwMzcsIm5iZiI6MTcxMDQzNDczNywicGF0aCI6Ii80Mjk2MDIwNS8zMTI5MjQzMTUtNTE3NTU1YmEtYzRhMS00Mzg0LWE3MWEtYTRmNWQ3YzJhNTM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDE2NDUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjOWE4YmZhYmY5ZjUyMWNjMGJkMWQ2MDc0NDk3YWVkM2ZjN2RhMTM1NmJkZWU5NzZhZGI3YzIzZThmOWZlOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ls-vE8_8ua_Im3zWTvK-Z88rat_936r-fA3ZwijmtWQ)
> 
> below are go.mod screenshot ![image](https://private-user-images.githubusercontent.com/42960205/312924715-8fd44baf-39cc-437d-ac54-8b28dc85e073.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MzUwMzcsIm5iZiI6MTcxMDQzNDczNywicGF0aCI6Ii80Mjk2MDIwNS8zMTI5MjQ3MTUtOGZkNDRiYWYtMzljYy00MzdkLWFjNTQtOGIyOGRjODVlMDczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDE2NDUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4YWQ2N2Q5NDkxNmI3Njk1NGNjMzU3Yzk1Yjc3OWMxNzliYzk5YTQ3ZmNmZjA2MjJjYmMxNDU2NDkxNzdhOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6UajBKlsAw_p-XBLC9xi0HhL2rhZ7_tkKYUQ3hIuJsc)

Please open a new issue to address your comment. You are using `go.opentelemetry.io/otel/label` and, as the error message points out, that package is not used in the stable versions of OTel.
