### ISSUE TITLE
unable to import semconv due to versioned path

### ISSUE THREAD

**Issue by marcosrmendezthd** [open-telemetry/opentelemetry-go#2011]
### Description

go is unable to import the semconv package as it looks like a version

### Environment

- OS: MacOSX
- Architecture: amd64
- Go Version: 1.16.3
- opentelemetry-go version: v0.20.0

### Steps To Reproduce

 go get -u go.opentelemetry.io/otel/exporters/jaeger@v0.20.0
go: go.opentelemetry.io/otel/semconv@v0.20.0: reading go.opentelemetry.io/otel/semconv/semconv/go.mod at revision semconv/v0.20.0: unknown revision semconv/v0.20.0
 go get -u go.opentelemetry.io/otel/exporters/jaeger@v0.20.0

### Expected behavior

Should be able to import.

**Comment by marcosrmendezthd** [comment]
an option is to rename the semconv folder from v1.4.0 to 1.4.0, or move it to another repo.

**Comment by marcosrmendezthd** [comment]
i tested renaming the folder and that didn't yield good results. moving the code back to the semconv folder worked though. so i think that if versioning semconv is required, then it probably needs its own repo.

**Comment by Aneurysm9** [comment]
`go.opentelemetry.io/otel/exporters/jaeger` does not yet have a released version and thus I'm not sure that this should be expected to work.  When I attempt this I get the following result:

```console
$ go get -u go.opentelemetry.io/otel/exporters/jaeger@v0.20.0
go get: module go.opentelemetry.io/otel@v0.20.0 found, but does not contain package go.opentelemetry.io/otel/exporters/jaeger
```

Using the correct import path for the released module gives expected results:

```console
$ go get -u go.opentelemetry.io/otel/exporters/trace/jaeger@v0.20.0
go: downloading go.opentelemetry.io/otel/exporters/trace/jaeger v0.20.0
go get: added github.com/davecgh/go-spew v1.1.1
go get: added go.opentelemetry.io/otel/exporters/trace/jaeger v0.20.0
go get: added gopkg.in/yaml.v3 v3.0.0-20210107192922-496545a6307b
```

As `go.opentelemetry.io/otel/semconv/v1.4.0` is a package and not a module (it is part of the `go.opentelemetry.io/otel` module) it should not run afoul of the module version determination logic.  Indeed, when I try to run `go get` to include it the tooling makes it clear that it has determined which module it belongs to but that the current version does not include that package:

```console
$  go get go.opentelemetry.io/otel/semconv/v1.4.0
go get: module go.opentelemetry.io/otel@upgrade found (v0.20.0), but does not contain package go.opentelemetry.io/otel/semconv/v1.4.0
```

**Comment by marcosrmendezthd** [comment]
thanks. that worked.
