### ISSUE TITLE
Refactor duplicate code in the OTLP exporter

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#2015]
In #1827 the OTLP exporter was split by signal. The split resulted in large amounts of unexported code being duplicated (e.g. transform, connection, otlpconfig). Refactor and unification this code is needed.

**Comment by lonewolf3739** [comment]
@MrAlias I would like to pick this up.

**Comment by MadVikingGod** [comment]
Looks like #2024 covers part of this.  I doubt it is everything.

**Comment by lonewolf3739** [comment]
> Looks like #2024 covers part of this. I doubt it is everything.

Looks like it has overlap work. I think another common piece of functionality is config.
