### ISSUE TITLE
Verify and update OTLP exporter documentation

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#2016]
In #1827 the OTLP exporter was split by signal. This split likely left documentation in the project outdated.

- [ ] Inventory the documentation for and examples of the OTLP exporter (e.g. project docs, website docs, readme)
- [ ] Verify it is accurate and update if not.

**Comment by Submarinee** [comment]
I'm happy to take this on. Could you please  assign this to me?

**Comment by MrAlias** [comment]
Closed with #2053
