### ISSUE TITLE
Ready for stable 1.0.0 release

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#2021]
We need to ensure we have the support of the community to release the stable tracing signal as 1.0.0. This means we need representatives from the interested companies and all of the maintainers/approvers of this project to sign off on it. If you are listed below, please respond in a comment stating that you support the release or please identify issues you see blocking the release:

- [Evan Torrie](https://github.com/evantorrie), Yahoo
- [Josh MacDonald](https://github.com/jmacd), LightStep
- [Sam Xie](https://github.com/XSAM)
- [David Ashpole](https://github.com/dashpole), Google
- [Gustavo Silva Paiva](https://github.com/paivagustavo), LightStep
- [Aaron Clawson](https://github.com/MadVikingGod)
- [Robert Pająk](https://github.com/pellared), Splunk
- [Anthony Mirabella](https://github.com/Aneurysm9), AWS
- [Tyler Yahn](https://github.com/MrAlias), Splunk

**Comment by Aneurysm9** [comment]
Ship it!

**Comment by MrAlias** [comment]
:rocket:

**Comment by evantorrie** [comment]
Two thumbs up.  👍 👍

**Comment by MadVikingGod** [comment]
🚢 it!

**Comment by jmacd** [comment]
Looks good to me

**Comment by codeboten** [comment]
🚢🚢🚢🚢🚢🚢🚢

**Comment by paivagustavo** [comment]
🚀🚀

**Comment by RichVanderwal** [comment]
🚀

**Comment by pellared** [comment]
I support the release 🚢 :shipit:

**Comment by XSAM** [comment]
🚀
