### ISSUE TITLE
Update or remove `resource.WithBuiltinDetectors()`

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-go#2026]
### Problem Statement

I noticed that the `resource.WithBuiltinDetectors()` option, which once included all the builtin detectors, has not been maintained. It could be removed, or it could be updated to actually name all the builtin detectors, which includes `WithHost()`,`WithOSType()`, and `WithProcess()` options which are not included in `resource.Default()`.

### Proposed Solution

Remove `WithBuiltinDetectors()`.

#### Alternatives

Add `WithHost()`,`WithOSType()`, and `WithProcess()` to the result from `WithBuiltinDetectors()`.

**Comment by jmacd** [comment]
Note: https://github.com/open-telemetry/opentelemetry-go/pull/1840 adds more builtin detectors.

**Comment by zhyChesterCheung** [comment]
My honor to take this issue, I'll do it as above said, add ```WithHost()```, ```WithOSType()```, ```WithProcess()``` instead of ```resource.WithBuiltinDetectors()```. Could you please assign it to me?

**Comment by nelsonghezzi** [comment]
#1840 was merged, so now `WithOSDescription()` can be added as well (or just add `WithOS()` which includes both OS type and description detectors).
