### ISSUE TITLE
move mockMeter to test-support package

### ISSUE THREAD

**Issue by rghetia** [open-telemetry/opentelemetry-go#203]
Based on this [comment](https://github.com/open-telemetry/opentelemetry-go/pull/177#discussion_r333219642), mockMeter is useful for testing not just api but sdk, plugin, etc. Opening this issue to move mockMeter to a support package, maybe test/metrics.

**Comment by freeformz** [comment]
I suggest a deep test/helpers package. That would make exported bits it that package 'helpers.Thing' and reduce naming clashes with `metrics`, `traces`, etc (which we already have a *ton* of.

**Comment by Sikkj** [comment]
![20191018214433](https://user-images.githubusercontent.com/33941545/67132475-418e8f00-f209-11e9-8604-827a81a4e6be.png)

**Comment by Sikkj** [comment]
Gccccvc

**Comment by Sikkj** [comment]
Cvvf gfhhg57 la vida

**Comment by Sikkj** [comment]
![IMG-20191018-WA0001](https://user-images.githubusercontent.com/33941545/67132514-6aaf1f80-f209-11e9-84b4-7d1f8a8a6e0d.jpg)

**Comment by Sikkj** [comment]
Silvia y a mi me
