### ISSUE TITLE
WithNewRoot uses the parent context for sampling decisions.

### ISSUE THREAD

**Issue by dashpole** [open-telemetry/opentelemetry-go#2031]
### Description

If I specify WithNewRoot, the [parent span context is not used](https://github.com/open-telemetry/opentelemetry-go/blob/311a6396a7a4e4e6edb15e07601b6834fd90180d/sdk/trace/span.go#L562) when getting the trace ID, or generating the new span id.  However, it [is still used](https://github.com/open-telemetry/opentelemetry-go/blob/311a6396a7a4e4e6edb15e07601b6834fd90180d/sdk/trace/span.go#L585) if you have a ParentBased sampler.

WithPublicEndpoint() would seem to imply that we **don't trust** incoming span contexts, and my expectation was that we wouldn't want to use them to make sampling decisions.

WithNewRoot(), on the other hand, would seem to only imply that the spans started are root spans.  It doesn't necessarily imply anything about sampling (although the specification seems to below).

IMO, we should either:

1. Change WithNewRoot() to store the [newly created parent span context](https://github.com/open-telemetry/opentelemetry-go/blob/311a6396a7a4e4e6edb15e07601b6834fd90180d/sdk/trace/span.go#L561) in the context before passing the context to samplers.
2. Document that WithPublicEndpoint still uses incoming span contexts for making sampling decisions, and recommend against using ParentBased samplers with public endpoints.

The specification would seem to (implicitly) support 1, since [it ties having no parent ](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#parentbased) to being a root span.

**Comment by Aneurysm9** [comment]
```go
	var psc trace.SpanContext
	if o.NewRoot() {
		ctx = trace.ContextWithSpanContext(ctx, psc)
	} else {
		psc = trace.SpanContextFromContext(ctx)
	}
```

Is this what you're thinking for option 1?  Seems right to me.

**Comment by dashpole** [comment]
Yeah, thats what i'm suggesting.
