### ISSUE TITLE
metrics: ValueObserver values are always 0

### ISSUE THREAD

**Issue by dave-tucker** [open-telemetry/opentelemetry-go#2045]
### Description

My `ValueObserver` always reports a zero value, which is different from the actual value (printed to log in the ValueObserver callback function). I'm using the OTLP GRPC exporter for metrics and the opentelemetry-collector with [this config](https://github.com/dave-tucker/libovsdb/commit/3d58a950cd18eb221a75d103172f295de4a710ae#diff-e3b13fb63d72e5c0d4dafdb013f40ec55d8241dd8c3ee00bf09a7b3f92d9153b)

Applicaton logs:
```
2021/06/30 12:09:09 bridge table size: 11344
```

Otel-collector log:
```
otel_1        | 2021-06-30T11:09:09.869Z        DEBUG   loggingexporter/logging_exporter.go:66  ResourceMetrics #0
otel_1        | Resource labels:
otel_1        |      -> service.name: STRING(unknown_service:stress)
otel_1        |      -> telemetry.sdk.language: STRING(go)
otel_1        |      -> telemetry.sdk.name: STRING(opentelemetry)
otel_1        |      -> telemetry.sdk.version: STRING(1.0.0-RC1)
otel_1        | InstrumentationLibraryMetrics #0
otel_1        | InstrumentationLibrary libovsdb.ovn.org/cache 
otel_1        | Metric #0
otel_1        | Descriptor:
otel_1        |      -> Name: libovsdb.cache.bridge.size
otel_1        |      -> Description: the size of the bridge table in the cache
otel_1        |      -> Unit: 
otel_1        |      -> DataType: DoubleGauge
otel_1        | DoubleDataPoints #0
otel_1        | StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
otel_1        | Timestamp: 2021-06-30 11:09:09.86869021 +0000 UTC
otel_1        | Value: 0.000000
otel_1        | 
```

### Environment

- OS: linux
- Architecture: x86
- Go Version: 1.16
- opentelemetry-go version: v0.21.0

### Steps To Reproduce

I'll try and put together a minimal reproduction case... but in the meantime

My actual code (NOTE: This is still a work-in-progress):
- [MetricExporter](https://github.com/dave-tucker/libovsdb/commit/3d58a950cd18eb221a75d103172f295de4a710ae#diff-01065bc531c3bd395f56629a02afd033f4d33e62f1b565180428b5ddeeff5690R287) setup in `main` function
- [ValueObserver](https://github.com/dave-tucker/libovsdb/commit/3d58a950cd18eb221a75d103172f295de4a710ae#diff-01065bc531c3bd395f56629a02afd033f4d33e62f1b565180428b5ddeeff5690R131) metric created in a `run` function that is called by `main`

1. Checkout https://github.com/dave-tucker/libovsdb/tree/otel
2. Run `docker run -itd -p 6640:6640 libovsdb/ovs:latest`
3. Run the collector stack: `cd examples/opentelemetry && docker-compose up -d`
4. Run the application: `go run ./cmd/stress/stress.go -verbose -otlp localhost:4317 -inserts 10000 -ovsdb tcp::6640 test` - this will generate load that will cause the cache of bridge table elements to grow up to 10000... it'll take a while
5. Observe the opentelemetry collector logs `docker-compose logs --tail=100 -f otel`

### Expected behavior

For the value that appears in Prometheus and the opentelemetry-collector log to be `11344`

**Comment by dave-tucker** [comment]
Minimal case to reproduce. https://github.com/dave-tucker/otel-metric-repro

**Comment by dave-tucker** [comment]
Update: I've tested with the `stdoutmetric` exporter and the reproduction case above works as expected...

```
exp, err := stdoutmetric.New(stdoutmetric.WithPrettyPrint())
	if err != nil {
		log.Fatal(err)
	}
```

Looks like this issue is with the `otlpmetric` exporter. I plan on testing further to see if I can isolate the problem.

**Comment by jmacd** [comment]
Is the collector consuming OTLP v0.9 yet? I suspect we can explain this as follows:
OTel-Go is producing OTLP v0.9 using the new NumberDataPoint.
OTel-Collector is reading OTLP v0.7 which recognizes a DoubleDataPoint in the corresponding protocol.
Thus, an Integer data point written in OTLP v0.9 is unrecognized by a collector reading v0.7.

**Comment by dave-tucker** [comment]
@jmacd that sounds like a reasonable explanation.
Here's the tracking issue for v0.9.0 https://github.com/open-telemetry/opentelemetry-collector/issues/3535
Looks like I was too enthusiastic to try out the cool new features :laughing:

**Comment by jmacd** [comment]
In this PR https://github.com/lightstep/opentelemetry-prometheus-sidecar/pull/235 I experienced the same problem 😞

**Comment by MrAlias** [comment]
This looks to have been resolved in https://github.com/open-telemetry/opentelemetry-collector/issues/3535.
