### ISSUE TITLE
conflicting `response_class` and `error` fields in logs

### ISSUE THREAD

**Issue by thomasliu623** [open-telemetry/opentelemetry-go#2048]
Hi! I'm seeing `response_class` and `error` fields in my logs, and I wanted to understand where these are coming from?

Sample values I'm seeing for these fields are: 
- `response_class` — `5xx`, `4xx`, `3xx`, `2xx`, ....
- `error` — `true`, ....

I'm looking into this because I noticed that these two fields can produce conflicting values. For instance, when `response_class` is showing `2xx` (for success status code), I'm seeing `error` as `true` which is contradictory. Can you help me understand how these fields are determined / populated?

**Comment by Aneurysm9** [comment]
Are you sure you have created this issue in the correct repository?  The term `response_class` does not appear in this repository.  We will need more information regarding the instrumentation producing these values and where they are produced if you believe they are a result of using the OpenTelemetry Go SDK.

**Comment by MrAlias** [comment]
Closing as this looks to have been opened in the wrong repository. Please reopen if this was in error.
