### ISSUE TITLE
Jaeger exporter should be its own go module

### ISSUE THREAD

**Issue by iredelmeier** [open-telemetry/opentelemetry-go#205]
Among other things, this would decouple the core code from all the Jaeger dependencies, such as Thrift.

**Comment by eran-levy** [comment]
@rghetia @iredelmeier will be happy to contribute the new module, can I just reference the new module repo here?

**Comment by eran-levy** [comment]
@rghetia ok will ref soon, wanted to make sure I document the way to generate the thrift clients that we have under internal/gen-go/jaeger - which jaeger version are we compatible with? when I generated using the Makefile that available at: https://github.com/jaegertracing/jaeger/tree/v1.14.0 I didnt see the same files that we have under our internal/gen-go/jaeger folder, how did you generate them?

**Comment by rghetia** [comment]
@eran-levy I did not generate those files. I had simply ported jaeger exporter from opencensus jaeger exporter [v0.1.0](https://github.com/census-ecosystem/opencensus-go-exporter-jaeger/tree/v0.1.0). 
If jaeger client library is used then gen-go files are not required. See [PR#7](https://github.com/census-ecosystem/opencensus-go-exporter-jaeger/pull/7). Using jaeger client library was discussed in #128.

**Comment by eran-levy** [comment]
@rghetia ok np, so here is the repo: https://github.com/eran-levy/opentelemtry-go-exporter-jaeger
let me know after you fork this repo into https://github.com/open-telemetry and then I will commit the changes to: https://github.com/open-telemetry/opentelemetry-go

**Comment by rghetia** [comment]
@eran-levy there may be some confusion here. While we have not decided where the exporter would reside, but we want the exporters to be its own module. Similar to examples (example/http, example/basic). Later when we have a place (another repo or different directory within the same repo) we will have another PR to do the change.

**Comment by eran-levy** [comment]
@rghetia ok, tnx, see PR #237
