### ISSUE TITLE
Consider to split SpanConfig into StartSpanConfig and EndSpanConfig

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-go#2066]
Right now not all the SpanConfig properties apply to both start and end options, it would be good to have them as separate configs to clearly identify which properties apply to which operation.

**Comment by MrAlias** [comment]
From the SIG meeting last week:

This change isn't opposed, but it does not seem like a high priority. Given we already have both a `StartSpanOption` and `EndSpanOption` interface the end user will work with and they give clear guidance the motivation to change this would be to support SDK developers. This change would limit the future extension and use of the `SpanConfig` in situation not yet considered and will likely result in addition types.

**Comment by jmacd** [comment]
This only matters to an SDK author, doesn't seem to be a source of user confusion. I suggest we close this.

**Comment by MrAlias** [comment]
Given the user facing types are the options not the config and having a unified config for a span allows easier extension in the future, the community in last week's SIG meeting agreed this can be closed.
