### ISSUE TITLE
Create a new linked Span from the current Context

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-go#2068]
### Problem Statement

In a long-living operation (context), I want to start a new Trace that is linked to the long-living operation. An example can be a bidirectional grpc stream where every received message represents a new operation, or a long living consumer operation in a pub-sub solution where every received message is a new operation.

Right now, I had to do something like this (in a grpc case):

```golang
	// Since the receiverCtx is long lived do not use it to start the span, just link to it.
	_, span = rec.tracer.Start(context.Background(), spanName, trace.WithLinks(trace.Link{
		SpanContext: trace.SpanContextFromContext(receiverCtx),
	}))

	ctx = trace.ContextWithSpan(receiverCtx, span)
```

### Proposed Solution

```golang
	// Since the receiverCtx is long lived do not use it to start the span, just link to it.
	ctx, span = rec.tracer.Start(receiverCtx, spanName, trace.WithParentAsLink(true))
```

OR:

```golang
	// Since the receiverCtx is long lived do not use it to start the span, just link to it.
	ctx, span = rec.tracer.Start(receiverCtx, spanName, trace.WithNoParent(true), trace.WithLinks(trace.Link{
		SpanContext: trace.SpanContextFromContext(receiverCtx),
	})
```

**Comment by Aneurysm9** [comment]
Does the existing `trace.WithNewRoot()` option enable the second proposed solution?  I think `trace.WithParentAsLink(true)` is nicer/simpler, but perhaps combining `WIthNewRoot` and a simpler `Link` initializer might be more flexible.

**Comment by bogdandrutu** [comment]
Thanks for pointing me to a bug :D
