### ISSUE TITLE
SDK should be usable without globals

### ISSUE THREAD

**Issue by iredelmeier** [open-telemetry/opentelemetry-go#207]
i.e., it should be feasible to use the SDK's tracer via something like `trace.NewTracer(opts...)` (where `trace` is `sdk/trace`), and the equivalent for metrics once metrics are far enough along.

**Comment by jmacd** [comment]
This may be a duplicate, maybe not.

https://github.com/open-telemetry/opentelemetry-go/issues/171

**Comment by iredelmeier** [comment]
> This may be a duplicate, maybe not.
> 
> #171

Two sides of a similar coin, I think? Unclear whether they're duplicates per se.
