### ISSUE TITLE
duplicate method SpanContext

### ISSUE THREAD

**Issue by ikuanyshbekov** [open-telemetry/opentelemetry-go#2070]
### Description

Hi guys,
You apparently forgot to delete one of the SpanContext() methods in the ReadWriteSpan interface.

Duplicate method SpanContext() in package https://github.com/open-telemetry/opentelemetry-go/blob/main/sdk/trace/span.go line 97
// Warning: methods may be added to this interface in minor releases.
type ReadWriteSpan interface {
	trace.Span <-- has SpanContext()
	ReadOnlySpan <-- has SpanContext()
}

the runtime error:
/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.0.0-!r!c1/trace/span.go:97:2: duplicate method SpanContext

### Environment

- OS: Ubuntu
- Architecture: x86
- Go Version: 1.16
- opentelemetry-go version: v1.0.0-RC1

### Steps To Reproduce

-

**Comment by Aneurysm9** [comment]
Can you provide a minimal reproduction case for this?  Our [existing tests](https://github.com/open-telemetry/opentelemetry-go/blob/main/sdk/trace/trace_test.go#L1473-L1475) for the `ReadWriteSpan` interface have not produced this error.

**Comment by ikuanyshbekov** [comment]
Problem solved. (underlying docker image used go 1.13)
