### ISSUE TITLE
metrics: ints are not recorded

### ISSUE THREAD

**Issue by ajsaclayan** [open-telemetry/opentelemetry-go#2079]
### Description

Hi OpenTelemetry community,
I'm seeing weird behavior when generating `Int64Counter` as well as `Int64ValueObserver`s. When viewing the metrics, the value is not recorded.

### Environment

- OS: Windows
- Architecture: 64 bit
- Go Version: 1.16
- otel/metric: v0.21.0
- otel/sdk/metric: v0.21.0

### Steps To Reproduce

Running a local kind cluster running `v0.29.0` of [opentelemetry-collector](https://github.com/open-telemetry/opentelemetry-collector). The collector is configured to write to a file to view metrics.

1. Initialize a metric provider and OTLP exporter, pointing to the local collector
2. Generate int counter/gauge metrics to be exported to local collector.
`intcounter` example:
```
intCounter := metric.Must(a.meter).
		NewInt64Counter(
			"IntSumMetric",
			metric.WithDescription("Int sum metric"),
		).Bind(a.commonLabels...)
	
intCounter.Add(a.context, rand.Int63n(10))
```
3. Run application
4. View metric in exporter

### Expected behavior
The sum recorded should have a value between 0-10. No value is recorded and the metric has the object `doubleSum`.
```
{
    "name": "IntSumMetric",
    "description": "Int sum metric",
    "doubleSum": {
        "dataPoints": [
            {
                "labels": [
                    {
                        "key": "dropped_label_count",
                        "value": "0"
                    }
                ],
                "startTimeUnixNano": "1625085629239312300",
                "timeUnixNano": "1625086409244676700"
            }
        ],
        "aggregationTemporality": "AGGREGATION_TEMPORALITY_CUMULATIVE",
        "isMonotonic": true
    }
},
```
I've also viewed the metrics in another exporter (New Relic) where the metric values are not recorded.

**Comment by jmacd** [comment]
See #2045, this is an unfortunate case of OTel-Go getting ahead of the collector (and other vendors).

**Comment by MrAlias** [comment]
Similar to #2045, this looks resolved by https://github.com/open-telemetry/opentelemetry-collector/issues/3535
