### ISSUE TITLE
Incorrect os.type value for DragonFly BSD

### ISSUE THREAD

**Issue by nelsonghezzi** [open-telemetry/opentelemetry-go#2084]
### Description

When the detector for the `os.type` attribute was added (#1788), it was done using the `runtime.GOOS` constant.

Now I notice that this maps 1:1 to all the values in the spec except for one, DragonFly BSD:

| GOOS  | [semconv](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/os.md) |
|---|---|
| `dragonfly` | `dragonflybsd` |

Althought *BSD is not officially supported/tested in the SDK, fixing this to be standard-compliant should be trivial.

### Environment

- OS: DragonFly BSD
- Architecture: x86_64
- Go Version: all
- opentelemetry-go version: since 0.20.0

### 1) Handle only this corner case with special logic 

There are already available constants with the correct values for this attributes in the `semconv/1.4.0` package. For example:

```go
// DragonFly BSD
OSTypeDragonflyBSD = OSTypeKey.String("dragonflybsd")
```

So they can be used for this specific `GOOS`:

```go
func (osTypeDetector) Detect(ctx context.Context) (*Resource, error) {
	osType := runtimeOS()

	var osTypeAttribute attribute.KeyValue

	if osType == "dragonfly" {
		osTypeAttribute = semconv.OSTypeDragonflyBSD
	} else {
		osTypeAttribute = semconv.OSTypeKey.String(strings.ToLower(osType))
	}

	return NewWithAttributes(
		semconv.SchemaURL,
		osTypeAttribute,
	), nil
}
```

I think this is the smallest change to fix the issue.

### 2) Generalize the previous solution with a map and apply it to all applicable `GOOS`s

This might be a bit more redundant/verbose but looks more complete, and has the small advantage that if in the future the standard's value change for some existing OS type, the correct new value will be picked up (after updating the `semconv` package reference). It also makes more evident that the mapping between `GOOS`s and semconv values isn't necessarily direct/equivalent.

```go
func (osTypeDetector) Detect(ctx context.Context) (*Resource, error) {
	osType := runtimeOS()

	// the elements in this map are the intersection between
 	// available GOOS values and semconv OS types
	osTypeAttributeMap := map[string]attribute.KeyValue{
		"darwin":    semconv.OSTypeDarwin,
		"dragonfly": semconv.OSTypeDragonflyBSD,
		"freebsd":   semconv.OSTypeFreeBSD,
		"linux":     semconv.OSTypeLinux,
		"netbsd":    semconv.OSTypeNetBSD,
		"openbsd":   semconv.OSTypeOpenBSD,
		"solaris":   semconv.OSTypeSolaris,
		"windows":   semconv.OSTypeWindows,
	}

	var osTypeAttribute attribute.KeyValue

	if attr, ok := osTypeAttributeMap[osType]; ok {
		osTypeAttribute = attr
	} else {
		// fallback for new or unrecognized GOOS, the spec
		// allows for custom values if none applies
		osTypeAttribute = semconv.OSTypeKey.String(strings.ToLower(osType))
	}

	return NewWithAttributes(
		semconv.SchemaURL,
		osTypeAttribute,
	), nil
}
```

**Comment by Aneurysm9** [comment]
I think I prefer option 2, more explicit less "magic".

**Comment by nelsonghezzi** [comment]
> I think I prefer option 2, more explicit less "magic".

Agree!

I can tackle this, so you can assign me the issue if you want.
