### ISSUE TITLE
Getting Started document  otel.Meter is incorrect

### ISSUE THREAD

**Issue by lastchiliarch** [open-telemetry/opentelemetry-go#2087]
### Description

[Getting Started](https://opentelemetry.io/docs/go/getting-started/#creating-metric-instruments)  otel.Meter is incorrect.

It seems Meter is in global package now.

I'd like to send an PR if possible.

### Expected behavior

Update otel.Meter to global.Meter.

**Comment by Aneurysm9** [comment]
oops, I must have missed that when I last updated those docs.  A PR would be appreciated.
