### ISSUE TITLE
CI lint should be stricter

### ISSUE THREAD

**Issue by iredelmeier** [open-telemetry/opentelemetry-go#210]
At the very least, we should be running with `gofmt` and `goimports`, and probably also `golint`.

(These are all available through golangci-lint but are [disabled by default](https://github.com/golangci/golangci-lint/tree/f2c566b7e29ca789df6bfc90762d140c832983e2#disabled-by-default-linters--e--enable).)

**Comment by freeformz** [comment]
goimports is enabled: https://github.com/open-telemetry/opentelemetry-go/blob/388d3248feac6cf3d8b500bca38102124ad9ff27/.golangci.yml#L9

+1 on `gofmt` & `golint`. I think I meant to enable them, but forgot too.

You can assign this to me if you want.
