### ISSUE TITLE
OTEL_EXPORTER_OTLP_HEADERS value should not be assumed CGI escaped

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#2110]
### Discussed in https://github.com/open-telemetry/opentelemetry-go/discussions/2050

<div type='discussions-op-text'>

<sup>Originally posted by **arielvalentin** July  1, 2021</sup>
We are trying to use the `OTEL_EXPORTER_OTLP_HEADERS` to configure the SDK with custom authentication token headers and we found that the `stringToHeader` function is CGI unescaping the values, which requires us to CGI escape the keys and values:

https://github.com/open-telemetry/opentelemetry-go/blob/main/exporters/otlp/otlptrace/internal/otlpconfig/envconfig.go#L180

```golang
name, err := url.QueryUnescape(nameValue[0])
if err != nil {
	continue
}
trimmedName := strings.TrimSpace(name)
value, err := url.QueryUnescape(nameValue[1])
if err != nil {
	continue
}
```

However, after reviewing the Specification it looks like there is not an explicit requirement for the values to be [CGI escaped](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#specifying-headers-via-environment-variables):

> Specifying headers via environment variables
> 
> The OTEL_EXPORTER_OTLP_HEADERS, OTEL_EXPORTER_OTLP_TRACES_HEADERS, OTEL_EXPORTER_OTLP_METRICS_HEADERS environment variables will contain a list of key value pairs, and these are expected to be represented in a format matching to the W3C Correlation-Context, except that additional semi-colon delimited metadata is not supported, i.e.: key1=value1,key2=value2. All attribute values MUST be considered strings.

As far as I can tell I do not see any explicit guidance in the header format that states the keys and values should be CGI escaped:

https://github.com/w3c/baggage/blob/main/baggage/HTTP_HEADER_FORMAT.md

Is there something I am misunderstanding here? Is there a requirement for the environment variables to have CGI Escaped Keys and Values?

cc: @open-telemetry/ruby-approvers </div>

**Comment by Aneurysm9** [comment]
The w3c spec requires that values are URL encoded:

> A value contains a **URL encoded UTF-8 string**. Leading and trailing whitespaces (OWS) are allowed but MUST be trimmed when converting the header into a data structure.
* [HTTP Header Format Specification](https://github.com/w3c/baggage/blob/main/baggage/HTTP_HEADER_FORMAT.md#value)

**Comment by MrAlias** [comment]
> The w3c spec requires that values are URL encoded:
> 
> > A value contains a **URL encoded UTF-8 string**. Leading and trailing whitespaces (OWS) are allowed but MUST be trimmed when converting the header into a data structure.
> 
> * [HTTP Header Format Specification](https://github.com/w3c/baggage/blob/main/baggage/HTTP_HEADER_FORMAT.md#value)
> 
> Keys do not need to be encoded because they must be [`token`](https://datatracker.ietf.org/doc/html/rfc2616#section-2.2) values that cannot contain characters that require escaping. We may not be enforcing that strongly enough.

@arielvalentin ^

**Comment by arielvalentin** [comment]
Thank you all for double checking this! 

I missed the detail of the value being URL-encoded the first time through.

I'll bring this back to the Ruby team and ensure we account for this. 

I think one thing that confused me was that it also indicates the value could also have multiple occurrences of `=` characters as well as slashes, etc... I assume that means when the value is decoded. Is that correct?

**Comment by arielvalentin** [comment]
After reading this several times I _think_ I am starting to understand this 😅 

> A value contains a URL encoded UTF-8 string.

The value is a `UTF-8` string but is URL encoded to satisfy the `baggage-octet` format of `US-ASCII` and excludes certain characters in the range:

```ABNF
value                  =  *baggage-octet
baggage-octet          =  %x21 / %x23-2B / %x2D-3A / %x3C-5B / %x5D-7E
                          ; US-ASCII characters excluding CTLs,
                          ; whitespace, DQUOTE, comma, semicolon,
                          ; and backslash
```

> Note, value MAY contain any number of the equal sign (=) characters. Parsers MUST NOT assume that the equal sign is only used to separate key and value.

Since the `=` character should be URL encoded `%3D`, then I assume this is referring to the _decoded_ value.

In the case of the `OTEL_EXPORTER_OLTP_HEADERS` environment variable, the SDK should parse the text according to the Baggage Format and anticipate values to be URL encoded and then decoded into a UTF-8 string.

**Comment by MrAlias** [comment]
Closing as it sounds like this is not a bug. Please reopen if more discussion is needed.
