### ISSUE TITLE
Allow sampler to be extended

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-go#2124]
https://github.com/open-telemetry/opentelemetry-go/blob/main/sdk/trace/sampling.go#L27

In the future the specs for sampling (especially because there is an active Sampling SIG) my require new capabilities for the Sampler that may need more funcs in the interface.

I think none of the public interface should have this limitation that they cannot be extended.

**Comment by Aneurysm9** [comment]
Interfaces that will be implemented by third parties cannot have new method added to them as that may result in prior implementations no longer satisfying the interface and breaking backward compatibility.  If new capabilities are required a new interface will be added and the SDK will attempt to coerce the received sampler to the new interface where the new interface is required.

**Comment by bogdandrutu** [comment]
@Aneurysm9 that is not entirely true :) you can have a private method and a BaseSampler and force everyone to extend (via embedding) that struct. That way you can still add methods. Your proposal also works but the comments there are very scary maybe consider to not have that comment 3 times, and explain that optional interfaces can be created in case of future changes required

**Comment by MrAlias** [comment]
Please be sure to read [the backstory on the decision](https://github.com/open-telemetry/opentelemetry-go/issues/1714#issuecomment-861897838) see our [contributing guidelines for interface stability](https://github.com/open-telemetry/opentelemetry-go/blob/main/CONTRIBUTING.md#interface-stability). The documentation you see there is a reminder and supplement to these sources.

**Comment by jmacd** [comment]
We can extend the sampler by adding fields to `SamplingParameters`.
