### ISSUE TITLE
TracerID string func only supply hex encoding ?

### ISSUE THREAD

**Issue by ddzrc** [open-telemetry/opentelemetry-go#2126]
### Problem Statement

i am think hex string encoding is too long in log， but TracerID is only support hex encoding

**Comment by Aneurysm9** [comment]
The canonical ASCII-compatible representation of trace context data is hexadecimal as that is the representation used by the w3c trace context recommendation.  However, a trace ID is an array of 16 bytes and custom representations can be created.
