### ISSUE TITLE
Inconsistent global set behavior

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#2140]
### Description

The global `TextMapPropagator`, `MeterProvider`, and `TracerProvider` can be set as many times as the user wants to call the appropriate set method. 

https://github.com/open-telemetry/opentelemetry-go/blob/fd9de7ec027fed5fa70c7529ba28b00ccdd5e4cb/internal/global/state.go#L62

https://github.com/open-telemetry/opentelemetry-go/blob/fd9de7ec027fed5fa70c7529ba28b00ccdd5e4cb/internal/metric/global/metric.go#L53

https://github.com/open-telemetry/opentelemetry-go/blob/fd9de7ec027fed5fa70c7529ba28b00ccdd5e4cb/internal/global/state.go#L85

The global `ErrorHandler` can only be set once. Subsequent calls to `SetErrorHandler` are ignored.

https://github.com/open-telemetry/opentelemetry-go/blob/fd9de7ec027fed5fa70c7529ba28b00ccdd5e4cb/handler.go#L73-L84

### Expected behavior

This inconsistent behavior needs to be made consistent.

**Comment by pellared** [comment]
Strong opinion: we should allow setting as many times as the user wants to call the appropriate set method.

Why? Even for the sake of unit testing 😉 

Just to confirm. Is it possible to get a "current" value to be able to make some set+revert logic?

**Comment by MrAlias** [comment]
> Just to confirm. Is it possible to get a "current" value to be able to make some set+revert logic?

Yes. There should be a corresponding `Get*` function for any `Set*` function (e.g. [this](https://github.com/open-telemetry/opentelemetry-go/blob/2b1bb29ef89708de6a0676d3bf7aa6162594cf35/trace.go#L37))
