### ISSUE TITLE
New sampler: Jaeger remote

### ISSUE THREAD

**Issue by kvrhdn** [open-telemetry/opentelemetry-go#2148]
### Problem Statement

We are migrating from OpenTracing to OpenTelemetry, we use the Jaeger exporter and our apps will their sampling strategies from the OTel Collector.
While [`jaeger_remote` is a known value for `OTEL_TRACES_SAMPLER` according to the specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#general-sdk-configuration), this isn't supported yet by opentelemetry-go.

Is there any work in progress to implement this? Is this something you would accept at this point?

### Proposed Solution

Add a new implement of [the Sampler interface](https://github.com/open-telemetry/opentelemetry-go/blob/2b1bb29ef89708de6a0676d3bf7aa6162594cf35/sdk/trace/sampling.go#L26-L41) that uses the Jaeger remote protocol to apply sampling strategies.

#### Alternatives

I'm not aware of any other remote sampling implementations.

#### Prior Art

I don't know if any other client library has implemented the Jaeger remote sampler.
The Jaeger receiver in collector has support for remote sampling: https://github.com/open-telemetry/opentelemetry-collector/blob/main/receiver/jaegerreceiver/README.md#remote-sampling

### Additional Context

N/A

**Comment by Aneurysm9** [comment]
I'm not aware of any ongoing work on a remote sampler and I don't think there is any reason why we would not accept one if it were provided.

**Comment by kvrhdn** [comment]
I've pushed my work in progress here: https://github.com/open-telemetry/opentelemetry-go/pull/2150, if anyone already wants to take a look. I have still have a bunch of TODO's to fix and we'll need a rate limiting and per operation sampler to support all Jaeger strategies.

**Comment by MrAlias** [comment]
Related to https://github.com/open-telemetry/opentelemetry-go/issues/327

**Comment by MadVikingGod** [comment]
The conversation continues in the contrib repo: [Add Jaeger remote sampler
](https://github.com/open-telemetry/opentelemetry-go-contrib/pull/936)
