### ISSUE TITLE
Array attribute value type design leads to dropped user data

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#2158]
### Description

A user can add semantically invalid array attributes that are syntactically valid.

```go
attributes.Array("mixed value", []interface{}{1,2.0,"three"})
```

Additionally, a user can add an attribute that is semantically valid, it is an array of primitive types according to the specification, and it will again be syntactically valid.

```go
attributes.Array("foo", []interface{}{1,2,3})
```

However, in both cases these attributes will be dropped as they are interpreted as invalid.

https://github.com/open-telemetry/opentelemetry-go/blob/23cb9396117ee0be80981ec9a60d1d1620688e29/attribute/value.go#L121

This doping of the attribute is not detectable by the user unless they check if the returned attribute is `Invalid`, something not common to expect in the Go ecosystem (`error`s are used for this purpose). From their perspective the code compiles, runs, and produces telemetry. The only way they can determine the attribute has been dropped is by independent verification of the produced telemetry or by inspection of the implementation of OTel-go.

This design adds unneeded burden to the user of the project and will produce a frustrating (at best) user experience.

### Proposed Solution

Given generics are not a part of the Go language yet, the `ArrayValue` type should be deprecated in favor of typed values:

- `func StringSliceValue(v []string) Value`
- `func BoolSliceValue(v []bool) Value`
- `func Float64SliceValue(v []float64) Value`
- `func Int64SliceValue(v []int64) Value`

Additionally, the constructor function for an "Array" `KeyValue` type needs to be deprecated in favor of typed functions.

- `func StringSlice(k string, v []string) KeyValue`
- `func BoolSlice(k string, v []bool) KeyValue`
- `func Float64Slice(k string, v []float64) KeyValue`
- `func Int64Slice(k string, v []int64) KeyValue`

Finally the "resolver" methods of a `Value` type will need to split as well.

- `func (v Value) AsStringSlice() []string`
- `func (v Value) AsBoolSlice() []bool`
- `func (v Value) AsFloat64Slice() []float64`
- `func (v Value) AsInt64Slice() []int64`

By doing this the user of the project will have clear understanding of what is allowed by the OTel specification based on the syntax of the implementation. Any use outside of what is provided will not only be semantically invalid according to the specification, but syntactically according to the Go language specification.

#### Alternatives

- The existing implementation is kept and logging could be added when https://github.com/open-telemetry/opentelemetry-go/issues/1068 is resolved.
  - This will not resolve the underlying issue identified here, but will make it more visible to the user *if* they use logging.
  - This will be blocked on https://github.com/open-telemetry/opentelemetry-go/issues/1068
- Update the creation methods to return an error instead of return an invalid attribute.
  - This will create a lot of boilerplate code checking the returned error.
  - This will mean attributes cannot be created and passed as arguments in a single line. I.e. `span.SetAttributes(attributes.Int64("foo", 1))` would not be possible.
- Allow `[]interface{}` types with valid underlying homogeneous data to be included (https://github.com/open-telemetry/opentelemetry-go/pull/2151).
  - This will only allow another edge case, it will not make it clear to the user what attribute types are allowed without reading the docs, specification, or implementation.
  - This does not resolve the situation where semantically invalid data is syntactically valid.

#### Prior Art

- Other language implementations of OTel were checked but if they use static types they included arrays by using generics.
- OpenCensus only allowes [`string` values](https://github.com/census-instrumentation/opencensus-go/blob/fb455b0a56818b2d4caf7f9bff94764f98a28f29/tag/map.go#L25-L29) and does not have this problem.
- OpenTracing allows values unknown value types [to pass through](https://github.com/opentracing/opentracing-go/blob/bdbb7cc3a1c08db5cc8b3296ec4447544fb43fe3/span.go#L58), something the OTel specification explicitly does not allow.

### Additional Context

https://github.com/open-telemetry/opentelemetry-go/pull/2151

**Comment by Aneurysm9** [comment]
I support the proposed solution.  Using separate, strongly typed interfaces seems to be the safest way forward.  It should also present the least opportunity for surprise to the user.

I think I combination of alternatives one and three might also be workable, but it still depends on the user having logging enabled and detecting the failure through the logs.
