### ISSUE TITLE
otel-collector example does not use metrics

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-go#2161]
### Description

The [`example/otel-collector`](https://github.com/open-telemetry/opentelemetry-go/tree/main/example/otel-collector) example mentions metrics on its README but it does not have any metrics export code since #1990. 

### Expected behavior

The example would either document how to use metrics or it would remove any mention of metrics from its description.

**Comment by fatsheep9146** [comment]
I'm new on OpenTelemetry, and when I search for demo examples, I found this issue. If this issue still need help, I've love to help with this. Is this ok for you? @Aneurysm9 @MrAlias

**Comment by Aneurysm9** [comment]
That would be great, @fatsheep9146.  I'll assign this issue to you.

**Comment by fatsheep9146** [comment]
I've already tested the demo code for metrics otel-collector locally, but I'm not sure how to write this doc is the best.
1. Modify this existing 'otel-collector' example, complement with metric part
2. Add a new folder which name is 'otel-collector-for-metric' and put the code right there.

Which one do you suggest? @Aneurysm9

**Comment by fatsheep9146** [comment]
I have already make a seperate demo for otel-colletor and metric data. @mx-psi @Aneurysm9 @MrAlias

**Comment by pellared** [comment]
Solved by https://github.com/open-telemetry/opentelemetry-go/pull/5283
