### ISSUE TITLE
prometheus default metrics (go_goroutines, go_info, go_memstats ...) are not exposed 

### ISSUE THREAD

**Issue by xmlking** [open-telemetry/opentelemetry-go#2171]
prometheus [exporter](https://github.com/open-telemetry/opentelemetry-go/blob/main/exporters/prometheus/prometheus.go#L91-L93) is not exposing default metrics (go_goroutines, go_info, go_memstats ...)  

The workaround to fix is with ugly code below
```go
var pConfig = prometheus.Config{Registry: goprom.DefaultRegisterer.(*goprom.Registry)}
exporter, err := prometheus.New(pConfig, pController)
```

please consider changed [this code](https://github.com/open-telemetry/opentelemetry-go/blob/main/exporters/prometheus/prometheus.go#L91-L93)  to
```go
	if config.Registry == nil {
		config.Registry = prometheus.DefaultRegisterer.(*prometheus.Registry)}
	}
```

My Workaround 
https://github.com/xmlking/toolkit/blob/develop/telemetry/metrics/metrics.go#L64

**Comment by jmacd** [comment]
The OTel library has a module for runtime metrics, https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/instrumentation/runtime

**Comment by dashpole** [comment]
I believe this is addressed with the current (new) version of the prometheus exporter.  See https://github.com/open-telemetry/opentelemetry-go/pull/3239#issuecomment-1271730211.

Basically, we register with the DefaultRegisterer by default, and allow users to override this with the WithRegisterer option.

**Comment by MrAlias** [comment]
> I believe this is addressed with the current (new) version of the prometheus exporter. See [#3239 (comment)](https://github.com/open-telemetry/opentelemetry-go/pull/3239#issuecomment-1271730211).
> 
> Basically, we register with the DefaultRegisterer by default, and allow users to override this with the WithRegisterer option.
