### ISSUE TITLE
OpenCensus Metrics bridge doesn't work with the OpenTelemetry prometheus exporter

### ISSUE THREAD

**Issue by dashpole** [open-telemetry/opentelemetry-go#2204]
### Problem Statement

I'd like to be able to send metrics from OpenCensus and OpenTelemetry SDKs to the same prometheus endpoint.  This will allow me to migrate my OpenCensus metrics to OpenTelemetry over time.

### Proposed Solution

Still investigating

### Additional Context

From https://github.com/open-telemetry/opentelemetry-collector/pull/3816

> @dashpole thanks for the suggestion! I tried the bridge, but ran into two problems:
> 
> * It looks like the otel Prometheus `Exporter` [does not implement metric.Exporter](https://pkg.go.dev/go.opentelemetry.io/otel/exporters/prometheus@v0.22.0?utm_source=gopls#Exporter), so I'm not able to pass it into `opencensus.NewMetricExporter()`
> * The `metricexport.Exporter` returned by [`opencensus.NewMetricExporter`](https://pkg.go.dev/go.opentelemetry.io/otel/bridge/opencensus@v0.21.0?utm_source=gopls#NewMetricExporter) can't be passed into [`view.RegisterExporter`](https://pkg.go.dev/go.opencensus.io/stats/view?utm_source=gopls#RegisterExporter) which expects a [`view.Exporter`](https://pkg.go.dev/go.opencensus.io/stats/view?utm_source=gopls#Exporter) instead.
> 
> Any idea where I'm going wrong?

**Comment by bogdandrutu** [comment]
This one blocks collector transition as well. Consider to prioritize this.

**Comment by dashpole** [comment]
Agreed.  Once the SDK is rewritten to be spec-compliant, I'll make sure the prometheus exporter works well with the otel SDK.  I'll also want to make sure the prometheus exporter for go is compliant with the prom <-> otlp spec I wrote.

**Comment by dashpole** [comment]
Once #3541 lands, the following will work to use the OpenCensus bridge with the prometheus exporter:

```golang
exporter, err := prometheus.New()
// handle err
// Register the OpenCensus producer with the Prometheus exporter
exporter.RegisterProducer(opencensus.NewMetricProducer())
provider := metric.NewMeterProvider(metric.WithReader(exporter))
// use meter provider
```
