### ISSUE TITLE
What is the purpose of SchemaURL?

### ISSUE THREAD

**Issue by maxifom** [open-telemetry/opentelemetry-go#2209]
I can see SchemaURL in the code everywhere, but it doesn't get exported by prometheus exporter, is it intended? And what the SchemaURL is used for?

**Comment by MrAlias** [comment]
The schema URL defines the version of semantic conventions used in resource. Each version of semantic conventions will export a unique schema URL that defines the form of the semantic conventions and the transforms to others.

https://github.com/open-telemetry/opentelemetry-go/blob/cdf67ddfa31a5b44285827c644fd111497fe0dfd/semconv/v1.4.0/schema.go#L17-L19

For more information on the schema URL take a look at the OTEP they were introduced with: https://github.com/open-telemetry/oteps/blob/09e285ec83d9f67759d99433f9ef1b32cd0551ca/text/0152-telemetry-schemas.md#schema-url

I imagine when the Prometheus exporter becomes stable it will include this information, but currently it is not expected to export this data.

Hope that helps.
