### ISSUE TITLE
Simplify the otel-collector example

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-go#2238]
The otel-collector example is doing too much to be an entry level example. It'd great to keep the scope to just export OTLP to a collector running locally (via Docker) to provide an easy to setup entry point to developers.

**Comment by fulviodenza** [comment]
I can work on this, assign this to me, thanks

**Comment by mabdh** [comment]
Hi @rakyll @MrAlias , is someone working with this issue? if not, can I pick this?

**Comment by drichards188** [comment]
Am I correct in my understanding that #2962 was closed and not accepted because of the name logger, and that it's a new example, instead of altering the original otel-collector example?

Is moving from microk8s to Docker to host the collector desirable, or is it best to retain the microk8s deployment and just simplify it?

**Comment by MrAlias** [comment]
> Am I correct in my understanding that #2962 was closed and not accepted because of the name logger, and that it's a new example, instead of altering the original otel-collector example?
> 
> Is moving from microk8s to Docker to host the collector desirable, or is it best to retain the microk8s deployment and just simplify it?

+1 moving to just Docker and docker compose like the other instrumentation examples (e.g. https://github.com/open-telemetry/opentelemetry-go-contrib/blob/e2cab2e7ca4271c0d6474071a7ce48c0c274e840/instrumentation/github.com/gorilla/mux/otelmux/example/docker-compose.yml) do.

**Comment by amila-ku** [comment]
@MrAlias i would like to work on this if this is still needed(quick check at the examples gives the idea it  yet to be completed).

If so i would modify the example to remove existing k8s deployment step and replace it with a docker compose based example.

**Comment by parauliya** [comment]
Hi @MrAlias ,
I would like to work on it, if this is still needed.
Could you please confirm that the above PR #3560 is in process for merging or is being rejected?
