### ISSUE TITLE
Use multiple MeterProviders in the same application

### ISSUE THREAD

**Issue by emilgelman** [open-telemetry/opentelemetry-go#2249]
### Description

The way to obtain a `Meter` in the current implementation is to use the `global` package, which forces the application to use a single `MeterProvider`.

From my observation, the `Histogram` instrument behaves differently according to the supplied `AggregatorSelector`, which is configured in the `MeterProvider`.

In some cases, a specific application may want to create two different `Histogram`s, for example one with Exact distribution and one with Histogram distribution, which currently seems impossible using the `global` package.

Also, the specification states that: "some applications may want to or have to use multiple MeterProvider instances, e.g. to have different configuration for each"
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#meterprovider

Should the `global` package be extended to allow multiple `MeterProvider`s?

### Environment

- OS: iOS
- Architecture: x64
- Go Version: 1.16
- opentelemetry-go version: v0.23.0

**Comment by Aneurysm9** [comment]
I don't believe there is anything in the current implementation that would prevent construction of multiple `MeterProvider`s, is therer?  The `global` package only provides access to a single `MeterProvider`, but that should not preclude an application from creating and using others.  I don't believe the `global` package should be extended to support multiple providers for any signal type as it is intended to provide access to default providers to be used in the absence of explicit configuration.

**Comment by emilgelman** [comment]
Thank you @Aneurysm9 for the reply.
You are right, there is nothing that prevents construction of multiple `MeterProvider`s. I just wanted to verify if that was the idiomatic way, or if there were any plans to extend the `global` package. Attaching complete code as reference, as I feel this may become a pretty common use case. For example, my application needs to report both synchronous gauges (exact distribution) and histograms (histogram distribution).

```
package main

import (
	"context"
	"time"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/exporters/otlp/otlpmetric"
	"go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp"
	controller "go.opentelemetry.io/otel/sdk/metric/controller/basic"
	processor "go.opentelemetry.io/otel/sdk/metric/processor/basic"
	"go.opentelemetry.io/otel/sdk/metric/selector/simple"
)

func main() {
	ctx := context.Background()
	client := otlpmetrichttp.NewClient(otlpmetrichttp.WithInsecure(), otlpmetrichttp.WithEndpoint("0.0.0.0:55681"))
	exp, err := otlpmetric.New(ctx, client)
	if err != nil {
		panic("Failed to create the collector exporter")
	}
	defer func() {
		ctx, cancel := context.WithTimeout(ctx, time.Second)
		defer cancel()
		if err := exp.Shutdown(ctx); err != nil {
			otel.Handle(err)
		}
	}()

	exactDistributionPusher := controller.New(
		processor.New(
			simple.NewWithExactDistribution(),
			exp,
		),
		controller.WithExporter(exp),
		controller.WithCollectPeriod(time.Millisecond*100),
	)
	if err := exactDistributionPusher.Start(ctx); err != nil {
		panic("could not start metric controoler: %v")
	}

	histogramPusher := controller.New(
		processor.New(
			simple.NewWithHistogramDistribution(),
			exp,
		),
		controller.WithExporter(exp),
		controller.WithCollectPeriod(time.Millisecond*100),
	)

	if err := histogramPusher.Start(ctx); err != nil {
		panic("could not start metric controoler: %v")
	}

	defer func() {
		ctx, cancel := context.WithTimeout(ctx, time.Second)
		defer cancel()
		// pushes any last exports to the receiver
		if err := exactDistributionPusher.Stop(ctx); err != nil {
			otel.Handle(err)
		}
		if err := histogramPusher.Stop(ctx); err != nil {
			otel.Handle(err)
		}
	}()

	exactHistogram, err := exactDistributionPusher.MeterProvider().Meter("exact").NewInt64Histogram("test.histogram.exact")
	if err != nil {
		panic(err)
	}

	histogramHistogram, err := histogramPusher.MeterProvider().Meter("histogram").NewInt64Histogram("test.histogram.histogram")
	if err != nil {
		panic(err)
	}

	exactHistogram.Record(ctx, 2)
	time.Sleep(time.Second * 1)
	exactHistogram.Record(ctx, -5)
	time.Sleep(time.Second * 1)
	exactHistogram.Record(ctx, 8)
	time.Sleep(time.Second * 1)

	histogramHistogram.Record(ctx, 2)
	time.Sleep(time.Second * 1)
	histogramHistogram.Record(ctx, -5)
	time.Sleep(time.Second * 1)
	histogramHistogram.Record(ctx, 8)
	time.Sleep(time.Second * 1)
}
```
