### ISSUE TITLE
Remove the `sdk/export/metric` package

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-go#2273]
### Problem Statement

As with https://github.com/open-telemetry/opentelemetry-go/issues/1380, but for the metrics SDK.

### Proposed Solution

The types in `sdk/export/metric` will be moved into `sdk/metric/exporter`, `sdk/metric/processor`, and `sdk/metric/aggregator` in such a way as to avoid cycles and keep things in their most natural location. The sub-package `aggregation` will be merged with `sdk/metric/aggregator`.

#### Alternatives

None.

#### Prior Art

See #1380.

### Additional Context

Related: the `ExportKind` types will end up in the `processor` package which is why I want to rename them first, see #2272

**Comment by MovieStoreGuy** [comment]
Could we also make sure to comment that these packages are deprecated as well to avoid confusing when trying to adopt?

**Comment by MrAlias** [comment]
Resolved by #2382
