### ISSUE TITLE
Metrics: misconfiguration leads to wrong temporality and no error message

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-go#2286]
### Description

When you configure the metrics `basic.Processor` with an AggregationTemporalitySelector that disagrees with the configured Exporter, it's possible for the exporter to receive the wrong data and no error message.

I observed this with the following configuration:

- `basic.Processor` given a `StatelessAggregationTemporalitySelector` (a.k.a. StatelessExportKindSelector).
- Prometheus exporter used, this exporter will see deltas and no error messages.

Related: #2274.

### Expected behavior

This should return errors to the exporter. After View Configuration is implemented, it should not be possible to arrive in this configuration. See https://github.com/open-telemetry/opentelemetry-specification/pull/2013

**Comment by MrAlias** [comment]
This issues relates to the current metric SDK. The [metric SDK redesign project](https://github.com/orgs/open-telemetry/projects/22) includes changes to the SDK design that will make this issue obsolete. I'm closing so no wasted work is performed to address this.
