### ISSUE TITLE
Broken dependency

### ISSUE THREAD

**Issue by pnemtsev** [open-telemetry/opentelemetry-go#2291]
### Description

Hello. I have a bad time trying to build this example
https://pkg.go.dev/go.opentelemetry.io/otel/exporters/otlp@v0.20.0#example-NewExporter
The `go mod tidy` command results in this error
```
go mod tidy
go: finding module for package go.opentelemetry.io/otel
go: finding module for package go.opentelemetry.io/otel/sdk/trace
go: finding module for package go.opentelemetry.io/otel/exporters/otlp/otlpgrpc
go: finding module for package go.opentelemetry.io/otel/exporters/otlp
go: found go.opentelemetry.io/otel in go.opentelemetry.io/otel v1.0.1
go: found go.opentelemetry.io/otel/exporters/otlp in go.opentelemetry.io/otel/exporters/otlp v0.20.0
go: found go.opentelemetry.io/otel/exporters/otlp/otlpgrpc in go.opentelemetry.io/otel/exporters/otlp v0.20.0
go: found go.opentelemetry.io/otel/sdk/trace in go.opentelemetry.io/otel/sdk v1.0.1
go: finding module for package go.opentelemetry.io/otel/unit
go: finding module for package go.opentelemetry.io/otel/internal/metric
go: finding module for package go.opentelemetry.io/otel/semconv
go: found go.opentelemetry.io/otel/internal/metric in go.opentelemetry.io/otel/internal/metric v0.24.0
go: finding module for package go.opentelemetry.io/otel/metric/registry
hello.world imports
	go.opentelemetry.io/otel/exporters/otlp imports
	go.opentelemetry.io/otel/sdk/metric/controller/basic imports
	go.opentelemetry.io/otel/metric/registry: module go.opentelemetry.io/otel/metric@latest found (v0.24.0), but does not contain package go.opentelemetry.io/otel/metric/registry
```

### Environment

- OS: Ubuntu 20.04
- Architecture: x86-64
- Go Version: 1.15.11
- opentelemetry-go version: v1.0.1

### Steps To Reproduce

1. Take source code from the example.
2. Run `go mod init`
3. Run `go mod tidy`

### Expected behavior

I expect to see successfully built dependency tree.

**Comment by pnemtsev** [comment]
Thanks for the explanation. It works now.
I think that old go.mod file might be fixed to prevent similar issues, so i will leave the issue open.

**Comment by MrAlias** [comment]
Thanks for the follow up. We do not plan to update any old, unstable, releases of the OTel-go project. Given the current, stable, release works as expected I'm going to close this.
