### ISSUE TITLE
Getting Started still refers to sdk RC

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry-go#2292]
Release 1.0.x is out, but the **Getting started** page still refers to RC releases, for example see https://github.com/open-telemetry/opentelemetry-go/blame/main/website_docs/getting-started.md#L268-L269:

```console
$ go get go.opentelemetry.io/otel/sdk@v1.0.0-RC2 \
         go.opentelemetry.io/otel/exporters/stdout/stdouttrace@v1.0.0-RC2
```

/cc @austinlparker

**Comment by Aneurysm9** [comment]
I think that, now that we've shipped v1.0.0, we can drop the version specifier there.  I think it was only necessary to avoid Go selecting the wrong v0.x version.
