### ISSUE TITLE
Automate checks that all spec versions have corresponding semconv package

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-go#2294]
### Problem Statement

A new semconv package is supposed to be created for every spec release. We had done it for v1.4.0 and
did not update since them. 

### Proposed Solution

It would be nice to automate this in some form of pre-release check, not sure what exactly is the best way.

**Comment by MrAlias** [comment]
We have updated the semconv packages to be current with v1.10.0. I'm going to track the "automation" work in #1907
