### ISSUE TITLE
Support the OTEL_BSP_* environment variables

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#2306]
Add support for the following environment variables as defined in the [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/sdk-environment-variables.md#batch-span-processor).

-  `OTEL_BSP_SCHEDULE_DELAY`
-  `OTEL_BSP_EXPORT_TIMEOUT`
-  `OTEL_BSP_MAX_QUEUE_SIZE`
-  `OTEL_BSP_MAX_EXPORT_BATCH_SIZE`

Part of #1698

**Comment by ianzhang1988** [comment]
Can someone elaborate how actually these OTEL_BSP_* work.

In my test, It show that at every `OTEL_BSP_EXPORT_TIMEOUT` sdk send `OTEL_BSP_MAX_EXPORT_BATCH_SIZE` spans. Then some spans got droped(I guess it used up OTEL_BSP_MAX_QUEUE_SIZE).

Is `OTEL_BSP_EXPORT_TIMEOUT` interval for sending spans?

**Comment by MrAlias** [comment]
@ianzhang1988 please take a look at the related batch span processor docs (https://pkg.go.dev/go.opentelemetry.io/otel/sdk/trace#BatchSpanProcessorOption) and the specification info on the environment variables (https://github.com/open-telemetry/opentelemetry-specification/blob/08a15efd4c43336ae31d14809aaa1acce07c9a0a/specification/sdk-environment-variables.md#batch-span-processor).

If these do not answer your question, please open an new issue for your question.

**Comment by ianzhang1988** [comment]
@MrAlias After some digging, I found that It's my server end (jaeger) do not send http 202, then block otel upload. Sorry for the false alarm.
