### ISSUE TITLE
Support the OTEL_SPAN_* environment variables

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#2307]
Add support for the following environment variables as defined in the [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/sdk-environment-variables.md#span-collection-limits).

- `OTEL_SPAN_ATTRIBUTE_COUNT_LIMIT`
- `OTEL_SPAN_EVENT_COUNT_LIMIT`
- `OTEL_SPAN_LINK_COUNT_LIMIT`

Part of #1698

**Comment by cuichenli** [comment]
i will work on this if it is ok
