### ISSUE TITLE
go.opentelemetry.io/otel/sdk fails static check because of 'SpanContext redeclared'

### ISSUE THREAD

**Issue by kwapik** [open-telemetry/opentelemetry-go#2315]
### Description

When running `staticcheck` in `go.opentelemetry.io/otel/sdk` it fails with the following error:
```bash
~/.../opentelemetry-go/sdk ((tags/v1.0.1^0) *)$ staticcheck ./...
-: could not analyze dependency go.opentelemetry.io/otel/sdk/trace [go.opentelemetry.io/otel/sdk/trace.test] of go.opentelemetry.io/otel/sdk/trace_test [go.opentelemetry.io/otel/sdk/trace.test] (compile)
-: could not analyze dependency go.opentelemetry.io/otel/sdk/trace of go.opentelemetry.io/otel/sdk/trace/tracetest (compile)
-: could not analyze dependency go.opentelemetry.io/otel/sdk/trace of go.opentelemetry.io/otel/sdk/trace/tracetest [go.opentelemetry.io/otel/sdk/trace/tracetest.test] (compile)
-: could not analyze dependency go.opentelemetry.io/otel/sdk/trace/tracetest [go.opentelemetry.io/otel/sdk/trace/tracetest.test] of go.opentelemetry.io/otel/sdk/trace/tracetest.test (compile)
-: could not analyze dependency go.opentelemetry.io/otel/sdk/trace_test [go.opentelemetry.io/otel/sdk/trace.test] of go.opentelemetry.io/otel/sdk/trace.test (compile)
trace/span.go:99:2: SpanContext redeclared (compile)
```

This is caused by duplication of `SpanContext` method in `ReadWriteSpan` [here](https://github.com/open-telemetry/opentelemetry-go/blob/main/sdk/trace/span.go#L97).
First declaration is in `trace.Span` [here](https://github.com/open-telemetry/opentelemetry-go/blob/main/trace/trace.go#L364).
Second declaration is in `ReadOnlySpan` [here](https://github.com/open-telemetry/opentelemetry-go/blob/main/sdk/trace/span.go#L45).

I don't know if this is intended.

### Environment

- OS: Linux, Ubuntu 20.04.3 LTS
- Architecture: x86_64
- Go Version: go1.17.2
- opentelemetry-go version: v1.0.1, 73727527

### Steps To Reproduce

1. Install `staticcheck` `go install honnef.co/go/tools/cmd/staticcheck@latest`
2. Clone repository `git clone git@github.com:open-telemetry/opentelemetry-go.git`
3. `cd opentelemetry-go`
3. Checkout version `git checkout v1.0.1`
4. `cd sdk`
4. Run `staticcheck ./...`

### Expected behavior

No errors happening.

**Comment by MrAlias** [comment]
I am not able to reproduce this.

```sh
~/go/src/go.opentelemetry.io/otel/sdk (git)-[v1.0.1] % docker run --rm -v "$PWD":/usr/src/go.opentelemetry.io/otel -w /usr/src/go.opentelemetry.io/otel/sdk golang:1.17 go install honnef.co/go/tools/cmd/staticcheck@latest && staticcheck ./... && echo success
go: downloading honnef.co/go/tools v0.2.1
go: downloading golang.org/x/tools v0.1.0
go: downloading github.com/BurntSushi/toml v0.3.1
go: downloading golang.org/x/sys v0.0.0-20210119212857-b64e53b001e4
go: downloading golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1
go: downloading golang.org/x/mod v0.3.0
success
```
