### ISSUE TITLE
Exporter signal-specific environment variables interpretation

### ISSUE THREAD

**Issue by cbandy** [open-telemetry/opentelemetry-go#2338]
### Description

Spec [v1.8.0 clarified](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.8.0/specification/protocol/exporter.md#endpoint-urls-for-otlphttp) that per-signal environment variables for HTTP endpoints must be interpreted as full/complete URLs.

`otlptracehttp@v1.2.0` (incorrectly) appends `/v1/traces` to the URL provided in `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT`.

### Environment

- Go Version: 1.16, 1.17
- opentelemetry-go version: v1.1.0, v1.2.0

### Steps To Reproduce

```go
package main

import (
	"context"
	"fmt"
	"net"
	"net/http"

	"go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp"
)

func main() {
	l, err := net.Listen("tcp", "localhost:9999")
	if err != nil {
		panic(err)
	}
	defer l.Close()

	server := http.Server{}
	server.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fmt.Println("URL:", r.URL)
	})
	go server.Serve(l)

	client := otlptracehttp.NewClient()
	client.Start(context.Background())
	fmt.Println("err:", client.UploadTraces(context.Background(), nil))
}
```

```console
$ OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:9999 go run main.go 
URL: /v1/traces
err: <nil>

$ OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://localhost:9999 go run main.go 
URL: /v1/traces
err: <nil>
```
```console
$ OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:9999/asdf go run main.go 
URL: /asdf/v1/traces
err: <nil>

$ OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://localhost:9999/asdf go run main.go 
URL: /asdf/v1/traces
err: <nil>
```

### Expected behavior

I expected `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT` to "be used as-is without any modification".

That is, I expected the `OTEL_EXPORTER_OTLP_ENDPOINT` env var to be interpreted differently than the `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT` env var.

**Comment by cbandy** [comment]
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#endpoint-urls-for-otlphttp

> 1. For the per-signal variables (`OTEL_EXPORTER_OTLP_<signal>_ENDPOINT`), the URL MUST be used as-is without any modification. The only exception is that if an URL contains no path part, the root path `/` MUST be used (see [Example 2](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#example-2)).

**Comment by cbandy** [comment]
Same results in `otlptracehttp@v1.2.0`.

**Comment by arielvalentin** [comment]
I believe the URL path is being overridden here:

https://github.com/open-telemetry/opentelemetry-go/blob/f4b63f184d298d924f9ad630a24e51fc136bdac8/exporters/otlp/otlptrace/otlptracehttp/client.go#L91

This should check if the signal specific endpoint was defined, however the existing patters seem to evaluate environment variables and set defaults in a different function:

https://github.com/open-telemetry/opentelemetry-go/blob/f4b63f184d298d924f9ad630a24e51fc136bdac8/exporters/otlp/otlptrace/internal/otlpconfig/envconfig.go#L83

@open-telemetry/go-maintainers Would it be best to separate the protocol, host and port from the path here and update the URL path like it does with Secure/Insecure?

**Comment by MrAlias** [comment]
Looks like the HTTP client will always append a suffix:

https://github.com/open-telemetry/opentelemetry-go/blob/2b7c6506721dd03452a6ae367b2149ddf6f2c872/exporters/otlp/otlptrace/otlptracehttp/client.go#L204

And the gRPC client will never:

https://github.com/open-telemetry/opentelemetry-go/blob/2b7c6506721dd03452a6ae367b2149ddf6f2c872/exporters/otlp/otlptrace/otlptracegrpc/client.go#L73

If we update the `otlpconfig` package to appropriately parse the endpoint based on the source and update the HTTP client to not modify the endpoint it should resolve this.
