### ISSUE TITLE
Race conditions in TestNew_collectorConnectionDiesThenReconnectsWhenInRestMode / TestNew_collectorConnectionDiesThenReconnects

### ISSUE THREAD

**Issue by pkwarren** [open-telemetry/opentelemetry-go#2344]
### Description

These two otlptracegrpc tests do the following:

- Start a gRPC server.
- Add a wrapper around gRPC server net.Listener to wrap Listener.Accept() to know when a connection is established server side.
- Call SpanExporter.ExportSpans immediately after the connection is established expecting for the export to succeed.

### Environment

- OS: Linux/MacOS
- Architecture: x86_64
- Go Version: 1.15/1.17
- opentelemetry-go version: v1.1.0

### Steps To Reproduce

Run either of the tests in the subject repeatedly, e.g.:

```
$ export GOMAXPROCS=2; for i in `seq 1 500`; do echo -n "Run $i: "; go test ./... -run '\QTestNew_collectorConnectionDiesThenReconnects\E$' -count 1 -race -v; if [ $? -ne 0 ]; then break; fi; ; done
```

### Expected behavior

Tests should be free of race conditions. Looking at the code I'm not sure how best to rewrite these tests to work consistently. We need an interface in the tests to know if the exporter (and underlying gRPC client) has successfully reconnected prior to asserting expectations. We might be able to sleep longer than the maximum reconnection interval, however this is error prone.

The tests are both in a separate package so can't rely on internal state (`package otlptracegrpc_test` vs. `package otlptracegrpc`). It might be good to separate both of these tests out into separate files that can rely on internal state to know when it is safe to call the exporter methods.

**Comment by pkwarren** [comment]
https://github.com/open-telemetry/opentelemetry-go/blob/7ce58f355851d0412e45ceb79d977bc612701b3f/exporters/otlp/otlptrace/internal/connection/connection.go#L132-L190 is where the connection is made (in a background goroutine).

https://github.com/open-telemetry/opentelemetry-go/blob/7ce58f355851d0412e45ceb79d977bc612701b3f/exporters/otlp/otlptrace/otlptracegrpc/client.go#L83-L85 is where the tests are failing (because the connection has been established but internal state hasn't been updated to reflect the client has reconnected).

**Comment by MrAlias** [comment]
This looks like a duplicate of https://github.com/open-telemetry/opentelemetry-go/issues/1527

**Comment by pkwarren** [comment]
Yeah sorry for the duplicate - I don't know why a search didn't turn that up.
