### ISSUE TITLE
Dependabot doesn't have appropriate permissions

### ISSUE THREAD

**Issue by MadVikingGod** [open-telemetry/opentelemetry-go#2372]
### Description

All of the dependabot actions are failing on the commit step: https://github.com/open-telemetry/opentelemetry-go/actions/workflows/dependabot.yml

This looks like it is a lack of permissions

### Environment

- OS: github
- opentelemetry-go version: main

### Steps To Reproduce

1. Run Dependabot on it's schedule

### Expected behavior

Dependabot should update it's pull request with appropriate versions

**Comment by MadVikingGod** [comment]
Related #846

**Comment by dmathieu** [comment]
It looks like this is fixed with #2997, since we now have a single PR for all dependabot upgrades, created by whoever runs the workflow.

**Comment by MrAlias** [comment]
Closed with #2997
