### ISSUE TITLE
Document shutting down of provider closes connection to collector

### ISSUE THREAD

**Issue by morigs** [open-telemetry/opentelemetry-go#2384]
### Problem Statement

Calling `Shutdown` on `TracerProvider` (and probably on `Stop` in metrics `controller.Controller` too) causes closing of underlying grpc connection through `TracerProvider.Shutdown->SpanProcessor.Shutdown->SpanExporter.Shutdown->Client.Stop`.
This is not obvious because user can provide his own grpc client using `otlptracegrpc.WithGRPCConn`.

### Proposed Solution

Documentation and doc comments should explicitly mention that all exporter connections are closed automatically during shutdown

#### Alternatives

Grpc client is not closed on shutdown when it's provided using `otlptracegrpc.WithGRPCConn`

### Additional Context

This lack of info causes confusion. When user tries to close the connection manually, he gets `Rpc error: code = Canceled desc = grpc: the client connection is closing`.

**Comment by MadVikingGod** [comment]
I think this might be the wrong behavior.

Originally the exporter managed the lifecycle of the connection, so it made sense to close the connection when shutdown.  Now that the exporter doesn't, at least not when it's provided a connection, I think we might not want to also close it when shutting down.  I know this will make our logic a bit more complex, but just like the consumer shouldn't close the channel, I think that the consumer shouldn't close the connection.
