### ISSUE TITLE
Non-GitHub import path?

### ISSUE THREAD

**Issue by iredelmeier** [open-telemetry/opentelemetry-go#24]
Especially given that the GitHub org name [may change](https://github.com/open-telemetry/community/issues/136), we should consider using an import path that isn't github.com/open-telemetry/opentelemetry-go.

Thoughts on, e.g., setting something up on opentelemetry.io or even opentelemetry.dev (which I think CNCF owns)?

**Comment by bogdandrutu** [comment]
Both are owned. @rghetia can you please setup the vanity URL as we did https://github.com/census-ecosystem/opencensus-go-vanityurls.

I would suggest to go with io for the moment to be consistent with Java and the official domain. CNCF people are also admins for the io domain.

**Comment by rghetia** [comment]
> @rghetia can you please setup the vanity URL as we did https://github.com/census-ecosystem/opencensus-go-vanityurls.
> 
> I would suggest to go with io for the moment to be consistent with Java and the official domain. CNCF people are also admins for the io domain.

sure.
