### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by jonathonfletcher** [open-telemetry/opentelemetry-go#2406]
please can working code for [Getting Started](https://opentelemetry.io/docs/go/getting-started/) be added as an example under [open-telemetry/opentelemetry-go/example](https://github.com/open-telemetry/opentelemetry-go/tree/main/example)? it would make the article easier for beginners to walk through.

**Comment by Aneurysm9** [comment]
The code from the getting started guide is available at https://github.com/open-telemetry/opentelemetry-go/tree/main/example/fib.

**Comment by jonathonfletcher** [comment]
oops, I missed that. thank you @Aneurysm9
