### ISSUE TITLE
Jaeger Exporter Unusuable due to Semconv Package Errors

### ISSUE THREAD

**Issue by steve-gray** [open-telemetry/opentelemetry-go#2421]
### Description

Jaeger exporter is presently unusable due to semconv package errors.  `go get -u ./...` fails with:

```github.com/yourprojecthere/ladder imports
        go.opentelemetry.io/otel/exporters/trace/jaeger imports
        go.opentelemetry.io/otel/semconv: cannot find module providing package go.opentelemetry.io/otel/semconv
```

Despite the discussion in #2011, the tips in there don't seem to work and all of the versions of things have moved substantially since , nothing seems to have been done around this issue for months. With Jaeger now deprecating their other packages, unless I've missed a trick somewhere it looks like there's now no supported path to use Jaeger exporters?

### Environment

- OS: MacOS
- Architecture: x64
- Go Version: 1.17
- opentelemetry-go version: latest 

### Steps To Reproduce

This minimal example in a new Go 1.17 will error:

```
package main

import (
	"fmt"
	"log"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/propagation"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/exporters/trace/jaeger"
	"go.opentelemetry.io/otel/propagation"
	sdktrace "go.opentelemetry.io/otel/sdk/trace"
)

// Init configures an OpenTelemetry exporter and trace provider
func Init() *sdktrace.TracerProvider {
	jaegerAgentEndpoint := "http://localhost:14268"

	tp, _, err := jaeger.NewExportPipeline(
		jaeger.WithCollectorEndpoint(fmt.Sprintf("%s/api/traces", jaegerAgentEndpoint)),
		jaeger.WithProcess(jaeger.Process{
			ServiceName: "testapp",
		}),
		//		jaeger.WithSDK(&sdktrace.Config{DefaultSampler: sdktrace.AlwaysSample()}),
	)
	if err != nil {
		log.Fatal(err)
	}

	otel.SetTracerProvider(tp)
	otel.SetTextMapPropagator(propagation.NewCompositeTextMapPropagator(propagation.TraceContext{}, propagation.Baggage{}))
	return tp
}

````

### Expected behavior

- Go get should not fail with minimal example above.

**Comment by MrAlias** [comment]
Using the correct Jaeger exporter module will prevent this issue: [`go.opentelemetry.io/otel/exporters/jaeger`](https://pkg.go.dev/go.opentelemetry.io/otel/exporters/jaeger)

**Comment by steve-gray** [comment]
Thats got me on the right path @MrAlias  thanks. Out of curiosity, how do I perform sampling using an external sampler like Jaeger?

**Comment by MrAlias** [comment]
Glad to hear this resolved your issue.

Take a look a [this](https://github.com/open-telemetry/opentelemetry-go-contrib/pull/936) PR. It is looking to add a Jaeger remote sampler.
