### ISSUE TITLE
module go.opentelemetry.io/otel/metric@latest found (v0.25.0), but does not contain package go.opentelemetry.io/otel/metric/registry

### ISSUE THREAD

**Issue by liminxufen** [open-telemetry/opentelemetry-go#2422]
### Description
go.opentelemetry.io/otel/exporters/otlp imports
go.opentelemetry.io/otel/sdk/metric/controller/basic imports
go.opentelemetry.io/otel/metric/registry: module go.opentelemetry.io/otel/metric@latest found (v0.25.0), but does not contain package go.opentelemetry.io/otel/metric/registry
![image](https://user-images.githubusercontent.com/17428619/143805527-6a09dc5c-90e8-40f6-b5e2-99214c0d2057.png)
![image](https://user-images.githubusercontent.com/17428619/143805711-daa0772f-fdef-424a-bc19-b9384a9878fd.png)

### Environment

- OS:  centos
- Architecture:  x86_64
- Go Version:  1.15
- opentelemetry-go version: v1.2.0

### Steps To Reproduce

go mod tidy

**Comment by MadVikingGod** [comment]
This is a problem because the otlp exporter has been split.  You should be able to `go get -u go.opentelemetry.io/otel/exporters/otlp/otlptrace` and use the `otlptrace.New()`, which has a different setup, to get past this.

**Comment by Aneurysm9** [comment]
> This problem may go away if we retract the `go.opentelemetry.io/otel/exporters/otlp` package in #2328

I don't think we want to retract any prior versions of that module, that would make it unusable for people legitimately attempting to use the older versions.  We should instead publish a deprecation note in a new version, which the Go tooling should display in situations like this, I think.

**Comment by MadVikingGod** [comment]
That is what [retract](https://go.dev/doc/modules/gomod-ref#retract) does.  There is no module deprecation, that is only for function/type

**Comment by Aneurysm9** [comment]
`retract` will prevent the Go toolchain from attempting to use that version, which may cause yet more breakage.  Instead, a comment may be added to the [`mod` directive](https://go.dev/ref/mod#go-mod-file-module) that will warn the user that the module is deprecated but still allow its use:

```
// Deprecated: use example.com/mod/v2 instead.
module example.com/mod
```

**Comment by MrAlias** [comment]
Closing as the solution to this issue was identified [here](https://github.com/open-telemetry/opentelemetry-go/issues/2422#issuecomment-981716733). Leaving the discussion for deprecating/retracting modules to #2328.
