### ISSUE TITLE
Potential memory leak using jaeger exporter

### ISSUE THREAD

**Issue by emaincourt** [open-telemetry/opentelemetry-go#2426]
### Description

Hi,

I recently integrated opentelemetry to replace the now deprecated jaeger client but am actually facing issues regarding part of the allocated memory never getting released. This is the first time I am working with opentelemetry so please let me know if I'm doing something wrong here.

### Environment

- OS: Docker
- Architecture: x86
- Go Version: 1.16
- opentelemetry-go version: 1.2.0
- otelhttp: 0.27.0

### Steps To Reproduce

Regarding the client, I'm starting and ending my traces the following way:

```go
// Instantiating the tracer provider
exp, err := jaeger.New(jaeger.WithCollectorEndpoint())
if err != nil {
	return err
}

tp := tracesdk.NewTracerProvider(
	tracesdk.WithBatcher(exp),
	tracesdk.WithResource(resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceNameKey.String(serviceName),
	)),
)

otel.SetTracerProvider(tp)
otel.SetTextMapPropagator(propagation.NewCompositeTextMapPropagator(propagation.TraceContext{}, propagation.Baggage{}))

// Start a trace
ctx, _ = otel.Tracer("name").Start(ctx, name)

// End a trace
if span := trace.SpanFromContext(ctx); span != nil {
	span.End()
}
```

When load testing the api that I integrated the client with, memory consumption constantly increases when tracing is enabled. If not, it remains stable. Please find below a graph of the memory usage of the service:

![image](https://user-images.githubusercontent.com/16223100/144601445-f3f2865d-8acb-4cc2-bded-b167b1b96e8a.png)

Also, here is an extract of the heap profile after the first load test on the left, and after the second load test on the right:

![image](https://user-images.githubusercontent.com/16223100/144601948-cce636b3-a74f-48e5-a1fb-e5a41cb78f29.png)

The more tests I run, the higher the memory goes without never getting released. In case it would matter, my traces get properly sent as I can see them in Jaeger UI.

Apart from that, I'm also making use of `otelhttp` that stands as a middleware to handle context propagation across my services. Basically all the handlers are being wrapped in it. In this case, things get a lot worse:

![image](https://user-images.githubusercontent.com/16223100/144602564-4ea60fa1-5274-4cb8-9d74-b5ef92c5b130.png)

However this time, the heap looks different:

![image](https://user-images.githubusercontent.com/16223100/144602800-d1322be2-d70a-4240-886c-5f2bce33a2b4.png)

I went across the [span benchmark](https://github.com/open-telemetry/opentelemetry-go/issues/2402) issue that could potentially match my problem but am not 100% sure. There is also [this closed issue](https://github.com/open-telemetry/opentelemetry-go/issues/1490) but don't think it's related.

### Expected behavior

I might be doing something wrong, but I would expect the memory not to increase continuously over time. What do you think ? Should I change the way I'm integrating the SDK maybe ?

Thanks in advance

**Comment by Aneurysm9** [comment]
Thanks for the report.  Are you able to reproduce the behavior with a different exporter (or perhaps even with an SDK configured without an exporter)?  Knowing that would help us direct our inquiry.

**Comment by emaincourt** [comment]
@Aneurysm9 Thanks a lot for your answer. I've been replacing the jaeger exporter with the stdout one and see no evidence of memory leak. Memory remains stable at 1536kB. Please find below related heap profiles:

![image](https://user-images.githubusercontent.com/16223100/144825794-c0bf8cc1-f757-460b-8a61-8c789939a358.png)

**Comment by emaincourt** [comment]
Actually I ran some more tests and it does not seem to be related to the sdk. Sorry for the noise. I'm still digging into my leak but it seems to be because a bunch of spans sometimes never get closed somehow.

**Comment by husoule** [comment]
您好，您的邮件我已经收到。
