### ISSUE TITLE
Is it possible to rename "instrumentation library" to "instrumentation scope"?

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-go#2431]
This initially came from a [discussion](https://github.com/open-telemetry/opentelemetry-specification/pull/1236#issuecomment-970464780) about introducing Logger Name. 

While discussing the issue during the spec SIG meeting we came to a conclusion that the intent for "instrumentation library" was actually to have an "instrumentation scope".

The "instrumentation library" is currently used throughout the spec API and SDK. We want to explore if it is possible to rename "instrumentation library" to "instrumentation scope" without breaking existing stability guarantees.

This issue is a questions for the maintainers of this repo: are we able to do this in a non-breaking manner?

Note: this should be only done if it is not a breaking change. We must continue honouring our stability guarantees.

Warning: please don't make the actual change yet. We need to confirm first that it is possible to make this change **everywhere** before moving forward.

Spec issue recorded here: https://github.com/open-telemetry/opentelemetry-specification/issues/2203

**Comment by MrAlias** [comment]
It is not going to be possible to rename "instrumentation library" to "instrumentation scope" without introducing a breaking change. There is the SDK type itself,

https://github.com/open-telemetry/opentelemetry-go/blob/2b7c6506721dd03452a6ae367b2149ddf6f2c872/sdk/instrumentation/library.go#L25

As well as things like the read-only span interface,

https://github.com/open-telemetry/opentelemetry-go/blob/099df58e4e32e4b0808c6d4571c7f6750ac2b5fd/sdk/trace/span.go#L68

Changing these names will be breaking changes that would violate our stability guarantees.

It might be possible to add new types, options, and methods, and deprecate the old ones. I would have to probably go through the changes a bit more carefully if we wanted to go this route, but I'm not sure it would serve us in the long run.

**Comment by tigrannajaryan** [comment]
It appears the conclusion of many SDKs is that this is not a possible change. Closing. Thanks for checking.
