### ISSUE TITLE
opentelemetry-go/example/otel-collector/main.go

### ISSUE THREAD

**Issue by jinxin-fu** [open-telemetry/opentelemetry-go#2435]
In this example, I can find the tracerProvider logic in the file ,but no metricprovider.  I Follow the direction to deploy opentelemetry-collector and prometheus . Configuration is as follows:
otlp:
receiver
```
  otel-collector-config: |
    receivers:
      # Make sure to add the otlp receiver.
      # This will open up the receiver on port 55680.
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
    processors:
```
exporter
```
    exporters:
      prometheus:
        endpoint: 0.0.0.0:8889
        namespace: "testapp"
      logging:
 
    service:
      extensions: [health_check]
      pipelines:
        metrics:
          receivers: [otlp]
          processors: []
          exporters: [prometheus]
```
I  do not deploy jaeger so I remove the config for jaeger exporter . Prometheus can get the target serviceMonitor/observability/otel-collector, but when i run main.go get the follow log :
```
2021/12/08 07:58:24 Waiting for connection...
2021/12/08 07:58:24 Doing really hard work (1 / 10)
2021/12/08 07:58:25 Doing really hard work (2 / 10)
2021/12/08 07:58:26 Doing really hard work (3 / 10)
2021/12/08 07:58:27 Doing really hard work (4 / 10)
2021/12/08 07:58:28 Doing really hard work (5 / 10)
2021/12/08 07:58:29 Doing really hard work (6 / 10)
2021/12/08 07:58:29 rpc error: code = Unimplemented desc = unknown service opentelemetry.proto.collector.trace.v1.TraceService
2021/12/08 07:58:30 Doing really hard work (7 / 10)
2021/12/08 07:58:31 Doing really hard work (8 / 10)
2021/12/08 07:58:32 Doing really hard work (9 / 10)
2021/12/08 07:58:33 Doing really hard work (10 / 10)
2021/12/08 07:58:34 rpc error: code = Unimplemented desc = unknown service opentelemetry.proto.collector.trace.v1.TraceService
2021/12/08 07:58:34 Done!
2021/12/08 07:58:34 rpc error: code = Unimplemented desc = unknown service opentelemetry.proto.collector.trace.v1.TraceService

```
And there are no metrics data in collector ,  Is there  any case for reference to create the MetricsProvider for OTLP

**Comment by MadVikingGod** [comment]
Right now the Metrics portion of the GO API and SDK are in unstable and likely to change.  We don't have a ready to use example because they were broken more often then working.  If you do start to use the metrics portion of the SDK please understand that there will likely be breaking changes before stability.

We will provide a working example when the API and SDK are stabilized.  

To get a working example you will have to create and set a MeterProvider, which requires a number of components, and eventually a metrics exporter.

**Comment by jinxin-fu** [comment]
OK,I got it. Thanks




---- 回复的原邮件 ----
| 发件人 | Aaron ***@***.***> |
| 日期 | 2021年12月09日 06:52 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [open-telemetry/opentelemetry-go] opentelemetry-go/example/otel-collector/main.go (Issue #2435) |

Right now the Metrics portion of the GO API and SDK are in unstable and likely to change. We don't have a ready to use example because they were broken more often then working. If you do start to use the metrics portion of the SDK please understand that there will likely be breaking changes before stability.

We will provide a working example when the API and SDK are stabilized.

To get a working example you will have to create and set a MeterProvider, which requires a number of components, and eventually a metrics exporter.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MrAlias** [comment]
Closing as this looks resolved.

**Comment by fracasula** [comment]
Digged a bit more, when looking at the collector logs I see:
```
2022-12-14T15:02:06.921Z	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging", "#metrics": 2}
2022-12-14T15:02:15.743Z	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging", "#metrics": 25}
2022-12-14T15:02:25.775Z	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging", "#metrics": 25}
2022-12-14T15:02:35.801Z	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging", "#metrics": 25}
2022-12-14T15:02:45.830Z	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging", "#metrics": 25}
2022-12-14T15:02:55.862Z	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging", "#metrics": 25}
2022-12-14T15:03:05.684Z	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging", "#metrics": 25}
2022-12-14T15:03:06.888Z	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging", "#metrics": 2}
2022-12-14T15:03:15.712Z	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging", "#metrics": 25}
```

The `"#metrics": 2` are the ones I'm sending, but when I call `/metrics` I only see the other ones :thinking:

**Comment by fracasula** [comment]
I solved it. The Go code above is correct. The problem was that the mounting of the Collector configuration YAML file that I was doing. I copied from an old example and it didn't match the current one.

I'm using the `otel/opentelemetry-collector` image with tag `0.67.0` and the correct volume mount is `/etc/otelcol/config.yaml` (not `/conf/otel-collector-config.yaml`).

For reference this is the YAML file I used to test the meter provider:
```yaml
receivers:
  otlp:
    protocols:
      grpc:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      label1: value1

processors:
  batch:

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]

```
