### ISSUE TITLE
[Question] how could I get parent span ID from context?

### ISSUE THREAD

**Issue by yeqown** [open-telemetry/opentelemetry-go#2436]
I want to get `parentSpanID` from context, but `Span` interface doesn't expose any API.

**Comment by MrAlias** [comment]
OpenTelemetry does not store the parent span ID in a context. Additionally, you are correct, it is not possible to get a span's parent span ID from the `"go.opentelemetry.io/otel/trace".Span` interface.

Can you clarify your use case to better understand what you are trying to do?

**Comment by yeqown** [comment]
I used `OpenTracing/Jaeger` tracer in my projects, now I want to change the tracer to be `OpenTelemetry`. I do not want to break the trace while updates are executed asymptotically, so I want to continue to pass `Jaeger` trace header to following service, such as:

server A (otel tracer) ---> server B (jaeger) ---> server C (jaeger)

what I want is:

- trace is complete (same trace Id)
- serverB keep the relationship (child span of server A) **Why I need parent span id**

**Comment by XSAM** [comment]
> server A (otel tracer) ---> server B (jaeger) ---> server C (jaeger)

I am not sure Jaeger will use `ParentSpanID` to achieve something. But to accomplish such a trace, it is not required to use `ParentSpanID`.

Also, OTel uses `0` as `ParentSpanID` when using the Jaeger propagator, and it is a valid trace header for Jaeger. So it won't break things.

**Comment by yeqown** [comment]
> I am not sure Jaeger will use ParentSpanID to achieve something. But to accomplish such a trace, it is not required to use ParentSpanID.

Jaeger's propagator would inject and extract `ParentSpanID` to `SpanContext` from carrier, if there is not `ParentSpanID` that means curretn span is root span (actually it's not)

> Also, OTel uses 0 as ParentSpanID when using the Jaeger propagator, and it is a valid trace header for Jaeger. So it won't break things.

My otel-collector would sent spans to Jaeger, so in Jaeger Dashboard, how could jaeger rebuild the relationship between spans withou `ParentSpanID`?

I would test this case ~
