### ISSUE TITLE
Jaeger span status translation incorrect

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#2439]
### Description

The Jaeger exporter translates a span status to an integer tag.

https://github.com/open-telemetry/opentelemetry-go/blob/b1775412390fcd9a196f4d432a92a95cd4761925/exporters/jaeger/jaeger.go#L150

[The OpenTelemetry specification states](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.8.0/specification/trace/sdk_exporters/non-otlp.md#span-status) this should be a string tag with the value of `OK` or `ERROR`.

This can cause error spans to be translated to OK in the collector: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/3de607f6cd38673924397f8a3c9158d89b491207/pkg/translator/jaeger/jaegerproto_to_traces.go#L211-L233

The `error` tag is cleared and since our `Error` code is the `pdata.StatusOk` value the span ultimately will not be counted as an error (there are also errors in the collector receiver based on this).

**Comment by MadVikingGod** [comment]
Just a heads up from after our conversation in the SIG meeting.  We were planning to release at 10am tomorrow.  That would be before this is open for a day.  Seeing as we have multiple approvals, and it is a bug I can understand allowing us to merge sooner, but I would like to point out that we are doing so.
