### ISSUE TITLE
Wrong comments for attribute.Value AsFloat64Slice and AsStringSlice methods

### ISSUE THREAD

**Issue by morigs** [open-telemetry/opentelemetry-go#2443]
### Description

`attribute.Value`'s methods `AsFloat64Slice` and `AsStringSlice` have wrong doc comments:

`AsFloat64Slice returns the []float64 value. Make sure that the Value's type is INT64SLICE.`

`AsStringSlice returns the []string value. Make sure that the Value's type is INT64SLICE.`

### Environment

- opentelemetry-go version: aedef05e953cbca349f1d8b4dfd46f69d96c6a61

### Steps To Reproduce

See [here](https://github.com/open-telemetry/opentelemetry-go/blob/aedef05e953cbca349f1d8b4dfd46f69d96c6a61/attribute/value.go#L190) and [here](https://github.com/open-telemetry/opentelemetry-go/blob/aedef05e953cbca349f1d8b4dfd46f69d96c6a61/attribute/value.go#L206)

### Expected behavior

Expected comments to be the following:

`AsFloat64Slice returns the []float64 value. Make sure that the Value's type is FLOAT64SLICE.`

`AsStringSlice returns the []string value. Make sure that the Value's type is STRINGSLICE.`

It looks like file is [generated](https://github.com/open-telemetry/opentelemetry-go/blob/aedef05e953cbca349f1d8b4dfd46f69d96c6a61/attribute/value.go#L25) by `stringer` so I'm not sure is it stringer-related issue or otel-related issue.

**Comment by MrAlias** [comment]
Closed by #2476
