### ISSUE TITLE
A tool to generate svg|image|whatever from trace.txt?

### ISSUE THREAD

**Issue by withernet** [open-telemetry/opentelemetry-go#2483]
### Problem Statement

Am writing trace output to `trace.txt`; is there a way to view this in a more friendly format without sending it to jaeger? Maybe a tool to load the file to display the traces?

### Proposed Solution

If there isn't a tool: `otelcli trace.txt --output svg` => generates SVG of data

**Comment by MrAlias** [comment]
Thanks for your interest in the project and your suggestion. This project is specifically scoped to [measure and send telemetry signal to observability platforms](https://github.com/open-telemetry/opentelemetry-go#opentelemetry-go). Visualization of this data is not in the scope of the project.

Please be sure to add this to the [OpenTelemetry registry](https://opentelemetry.io/registry/) if you decide to build this yourself.
