### ISSUE TITLE
How does a metric relate to a trace?

### ISSUE THREAD

**Issue by JeffreyBool** [open-telemetry/opentelemetry-go#2484]
How does a metric relate to a trace?

**Comment by MrAlias** [comment]
Metrics and traces are both telemetry sources, their relationship is defined by the author who uses them in instrumentation. There is no universal relationship defined in the OpenTelemetry sense. Please take a look at [OpenTelemetry documentation](https://opentelemetry.io/docs/concepts/data-sources/) for more information.
