### ISSUE TITLE
Should metrics API be developed for golang 1.18

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-go#2494]
It looks like golang 1.18 will support generics (see https://go.dev/doc/tutorial/generics). With that the need of "Number" for example as a public type is a bit unclear, and probably other "sdkapi" public types. 

Should the opentelemetr-go be designed using generics?

**Comment by Aneurysm9** [comment]
This is something I've been wondering about myself.  I think there is a very high hurdle to clear before we decide to take this path as our current policy is to support at least the current and immediately prior releases of Go, which would mean that we could not use features in 1.18 until after the release of 1.19 without changing that policy.  That said, it may be worth making the change and I'd be interested in seeing what sort of improvements to the API could be offered by taking advantage of generics.

**Comment by MrAlias** [comment]
I definitely think it is an option worth exploring.

**Comment by MrAlias** [comment]
Go 1.18 is expected to be released in February 2022. With a 6 month cadence on these releases, that puts 1.19 being released around August 2022.

This means the question becomes: should be break our compatibility guarantee with the Go project to build our metric API with generics?

**Comment by MrAlias** [comment]
We also need to explore the feasibility of using generics in the API/SDK to motivate a decision here. This should involve building a prototype.

**Comment by MrAlias** [comment]
Follow on the consensus of the SIG:

- We want to make the API as usable and stable a possible. As mentioned in the [release notes](https://go.dev/doc/go1.18)
   > it is possible that there will be code using generics that will work with the 1.18 release but break in later releases
   
   For this reason, we do not want to utilize Go generic features in the API.
- The SDK is the primary place where generics can aid in design, as mentioned in the issue description. We would like to include their use there as we have more control over the life-cycle of the SDK.

I going to close this issue as this has been the consensus for a few weeks and is the approach we took with the [API redesign](https://github.com/open-telemetry/opentelemetry-go/pull/2587) and are taking with the [SDK work](https://github.com/orgs/open-telemetry/projects/22).

**Comment by MrAlias** [comment]
Related to https://github.com/open-telemetry/opentelemetry-go/issues/2528
