### ISSUE TITLE
why marshal TraceID not use tag,specification use TraceId

### ISSUE THREAD

**Issue by 1157987916** [open-telemetry/opentelemetry-go#2508]
https://github.com/open-telemetry/opentelemetry-go/blob/73edf3dfcca4b0696597b0412ba3b5106ed794e7/trace/trace.go#L184-L190

[specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#spancontext)

**Comment by 1157987916** [comment]
![image](https://user-images.githubusercontent.com/42087738/149282868-191ce5cf-58a9-47c5-aba8-27c389730a9d.png)

**Comment by 1157987916** [comment]
![企业微信截图_16420570994129](https://user-images.githubusercontent.com/42087738/149283988-8d409da2-8ef6-48f1-b7a8-1a6685b7b5f0.png)

Log data model will use TraceId,it should be  the same

**Comment by dmathieu** [comment]
Do you mean why use `TraceID` instead of `TraceId`? If that's the case, using `ID` instead of `Id` is a Go idiom.
The specification is a means for all libraries to behave in a similar way. But each of them should also respect the idioms of their language, not blindly follow the spec.

**Comment by Aneurysm9** [comment]
@dmathieu is correct regarding the capitalization difference.  If your question is also about why `SpanContextConfig` does not have struct tags that would cause it to be marshaled using `TraceId`, that struct is not intended for communication, only for use with the SDK.  The [`propagation` package](https://pkg.go.dev/go.opentelemetry.io/otel@v1.3.0/propagation) should be used to propagate trace context information.
