### ISSUE TITLE
Control log output of TracerProvider

### ISSUE THREAD

**Issue by obitech** [open-telemetry/opentelemetry-go#2511]
### Problem Statement

Hi, I'm not sure if this is already possible as I haven't found anything in the go-docs. But is it possible to control the log output of the otel tracing instrumentation, or pass a custom logger? For example, if there is an error, log messages are currently formatted like this:

```
 2022/01/14 09:36:16 max retry time elapsed: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup XXX on YYY: no such host"
 ```

Is there any option to change the default log format?  Ideally I want this to be in JSON (or have the option to output it like that).

### Proposed Solution

I want the option to control the log format of the OTEL tracing SDK. Maybe this could be achieved through some sort of MessageProducer Option.

#### Alternatives

Right now the only alternative seems to be to accept the current state of the logging output (unless I'm missing something)

#### Prior Art

The [grpc_zap](https://github.com/grpc-ecosystem/go-grpc-middleware/blob/a77ba4df9c270ec918ed6a6d506309078e3e4c4d/logging/zap/options.go#L91) library has an Option which lets me customize the message producer.

**Comment by dmathieu** [comment]
I suppose once the log API has stabilized, the library can switch to that and provide more powerful means of setting the log format.

**Comment by obitech** [comment]
@dmathieu so adjusting this not possible right now, correct?

**Comment by Aneurysm9** [comment]
There are two potential routes that this message could have been emitted.  The first, and most likely in this case, is through the [global error handler](https://pkg.go.dev/go.opentelemetry.io/otel#Handle), which defaults to printing to `stderr` with the stdlib's `log` package.  You can change this behavior with [`otel.SetErrorHandler()`](https://pkg.go.dev/go.opentelemetry.io/otel#SetErrorHandler).  

The other way is through an internal logger that is only available to the API and SDK.  This also defaults to printing to `stderr` with the stdlib's `log` package, but [can be replaced](https://pkg.go.dev/go.opentelemetry.io/otel#SetLogger) with a [`logr.Logger`](https://pkg.go.dev/github.com/go-logr/logr#Logger) backed by your preferred logging library.

**Comment by obitech** [comment]
Thank you! Should we leave this issue open with regards to the message producer? For my use case it's enough for now.
