### ISSUE TITLE
Would be good to have code link for Getting Started section

### ISSUE THREAD

**Issue by romanoff** [open-telemetry/opentelemetry-go#2521]
Would be great if there was link to code link after description here: https://opentelemetry.io/docs/instrumentation/go/getting-started/

For example in `Creating resource` section https://opentelemetry.io/docs/instrumentation/go/getting-started/#creating-a-resource it's not clear that resource should come from `go.opentelemetry.io/otel/sdk/resource` package.

**Comment by dmathieu** [comment]
Would a link to [the examples](https://github.com/open-telemetry/opentelemetry-go/tree/main/example) be sufficient?
