### ISSUE TITLE
Baggage Member values are being validated in the Go Member data structure

### ISSUE THREAD

**Issue by williamgcampbell** [open-telemetry/opentelemetry-go#2523]
### Description

I saw https://github.com/open-telemetry/opentelemetry-go/issues/2498 around validating too often, but this ticket is asserting that we should not be validating the Member values at all in the Go data structure. The values should be encoded before transit, and decoded back into plaintext form when put back into the data structure. This is mentioned in https://github.com/open-telemetry/opentelemetry-go/issues/2519. 

The [otel spec ](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/baggage/api.md) has more vanilla language than the [W3C spec](https://github.com/w3c/baggage/blob/main/baggage/HTTP_HEADER_FORMAT.md#value) about Member values. As I understand it, the values should be encoded for transit only. 

### Environment

- OS: linux/mac
- Architecture: x86_64
- Go Version: 1.17
- opentelemetry-go version: v1.2.0

### Steps To Reproduce

1. Using the baggage module, create a new Member with a value that contains any characters that should be ignored according to the [W3C spec](https://www.w3.org/TR/baggage/#value)
2. Any function that validates will return an error

Example:
```
func TestBaggageMember(t *testing.T) {
	_, err := baggage.NewMember("key", "a,2")
	require.NoError(t, err) // fail
}
```

### Expected behavior

No validation is done when creating or manipulating member values in the Go structures, and proper encoding is done before the propagation of values.

**Comment by dmathieu** [comment]
I'm not sure this issue is still accurate.
`NewMember` will require valid/unencoded values. But I believe that's the proper behavior for that method.
Since #2529, `Parse` will however properly decode values.
