### ISSUE TITLE
Case against a generics-based metrics API in Go-1.18

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-go#2528]
### Problem Statement

The Go generics feature upcoming in Go-1.18 may look appealing as the basis for an OTel metrics API. This has been [used as an example for generics in Go](https://go.googlesource.com/proposal/+/refs/heads/master/design/43651-type-parameters.md#metrics). The example uses ordered, generic-typed attribute value lists which offers the potential to optimize the cost of building attribute sets. 

OTel-Go as a project could decide to embrace "ordered, generic-typed attribute value lists" as an option; probably even without support in the specification, since it relates to building a concrete data type: attribute sets. But this would be an optimization and one that makes the API a bit more dangerous (e.g., you can swap any two arguments of the same type, leading to incorrect attributes). To take this approach in OTel, new generics-based builders for attribute sets would be recommended, and new optional instrument APIs to take pre-built attribute sets.

The prototype in #2525 also uses generics, but there it is an attempt to streamline the SDK internals, particularly around the two code paths for int64 and float64. The question posed in this issue is, what benefits could there be from using generics in the API, e.g., to make the API indifferent to `int64` vs `float64`. Would this allow users to tailor their instruments to dedicated types, such as `time.Duration`? This would let us define a `Histogram[time.Duration]` that would naturally enforce the proper units, maybe.

OpenTelemetry has a strong requirement about separation of the API and the SDK. This need for separation comes into conflict with the limitations of generics in Go 1.18. You are able to make generic types, but not generic methods. This leads to a negative result when considering generics in the API. Suppose you can find a way to make the hypothetical `Histogram[time.Duration]` work by restructuring the API in arbitrary ways? What will the `Meter` API look like after this is done?

### Proposed Solution

Sketch of the (failed) solution is based on the layout options described in #2526 

Because there are no generic methods, the Meter has two interfaces. I've removed attributes and options for this presentation:

```
type AnyCapturer[N instrument.Number] interface {
    Capture(ctx context.Context, value N)
}

type IntegerInstrument = AnyCapturer[int64]
type FloatingPointInstrument = AnyCapturer[float64]

type MeterImpl interface {
	NewInteger(name, unit string, synchronous bool) IntegerInstrument
	NewFloatingPoint(name, unit string, synchronous bool) FloatingPointInstrument
	NewCallback(insts []instrument.Asynchronous, function CallbackFunc) (Callback, error)
}
```

In the `instrument` package an "any kind of 64-bit number" constraint:

```
type Number interface {
	~int64 | ~float64
}
```

In the top-level `metric` package you need something to encode the number type passed into the instrument constructor, imagine it's called `Unit[N]`. Here are some units.

```
type Unit[N instrument.Number] string

var (
	Duration = Unit[time.Duration]("ns")
	Seconds = Unit[float64]("s")
	Bytes = Unit[int64]("{bytes}")
)
```

Now because the Meter can't have a generic method, we'll build generic constructors that take the Meter as an argument instead:

```
func Synchronous[N instrument.Number](meter Meter, unit Unit[N]) syncmetric.Meter[N] {
	... // non-exported type implements the interface below that stores "meter", "unit", knows "N" and "synchronous"
}
```

the `syncmetric.Meter[N]` would let you construct any of the synchronous instruments for type `N`, (e.g., in the `syncmetric` subpackage),

```
type Meter[N instrument.Number] interface {
	Counter(name string) Counter[N]
	UpDownCounter(name string) UpDownCounter[N]
	Histogram(name string) Histogram[N]
}

type Counter[N instrument.Number] interface {
	Add(ctx context.Context, value N)
}

type UpDownCounter[N instrument.Number] interface {
	Add(ctx context.Context, value N)
}


type Histogram[N instrument.Number] interface {
	Record(ctx context.Context, value N)
}
```

and finally to use this, it would look like:

```
   durations := metric.Synchronous(meter, metric.Nanoseconds).Histogram("durations")
   durations.Record(ctx, time.Since(startTime))
```

However, what I've sketched doesn't quite work. I would have to go back to `Unit[N instrument.Number]` and introduce an adapter type that would know for each `N` (actual type) whether to use the integer or floating point code path. 

So, it would be more complicated,

```
type Unit[N instrument.Number, A Adapter[N]] string

type Adapter[N instrument.Number] {
    NewInstrument(m Meter, name, unit string, synchronous bool) AnyCapturer[N]
}

type Int64Adapter struct{}
type Float64Adapter struct{}

func (Int64Adapter) NewInstrument(m Meter, name unit string, synchronous bool) AnyCapturer[int64] {
  return m.NewIntegerInstrument(name, unit, synchronous)
}

func (Float64Adapter) NewInstrument(m Meter, name unit string, synchronous bool) AnyCapturer[float64] {
  return m.NewFloatingPointInstrument(name, unit, synchronous)
}

var (
	Duration = Unit[time.Duration, Int64Adapter]("ns")
	Seconds = Unit[float64, Float64Adapter]("s")
	Bytes = Unit[int64, Int64Adapter]("{bytes}")
)
```

I've omitted a lot of details. An approach like this will work, but as you can see we're just re-creating the `sdkapi` concept over again and a lot of complexity is moving back into the API. This leads me to reject a potential Go-1.18 generics-based API for metrics.

**Comment by punya** [comment]
Thanks for doing this analysis. I agree with the conclusion, and I'd add that the Go team themselves have urged caution in adopting generics while the community figures out the best ways to use it. As a long-lived API, I believe OTel-Go's API should be conservative when adopting this feature.

Adopting generics to streamline the implementation seems totally reasonable though (as long as the API surface remains the same).

**Comment by jmacd** [comment]
Users will have an opportunity to use generics to enhance the API in minor ways if they please. For example, users can wrap an OTel instrument to obtain an instrument for a special-purpose type: 

```
type Ints interface {
	~int64 | ~int32 | ~int16 | ~int8 | ~int
}

type Counter[N Ints] interface {
	Add(value N)
}


type Int64Counter = Counter[int64]

func GeneralizeCounter[N Ints](inst Int64Counter) Counter[N] {
	return genericCounter[N]{
		inst: inst,
	}
}

type genericCounter[N Ints] struct {
	inst Int64Counter
}

func (g genericCounter[N]) Add(value N) {
	g.inst.Add(int64(value))
}
```

This will have to be done separately for synchronous Counters (w/ Add()), Histograms (w/ Record()), and async instruments (w/ Observe()).

Another opportunity to use generics that the user will have is to replicate the `Must()` facility for error checking in instrument constructors. For example:

```
type Counter interface {
	Add(int64)
}

type Meter interface {
	NewCounter(name string) (Counter, error)
}

type meter struct {}

func (m meter) NewCounter(name string) (Counter, error) {
	return nil, fmt.Errorf("not implemented")
}

func Must[Instrument any](inst Instrument, err error) Instrument {
	if err != nil {
		panic(fmt.Sprint("new instrument: ", err))
	}
	return inst
}

func main() {
	var m Meter = meter{}

	inst := Must(m.NewCounter("hello")) // panics with "new instrument: not implemented"

	inst.Add(10)
}
```

**Comment by MrAlias** [comment]
There seems to be community consensus here. Closing.
