### ISSUE TITLE
example in the readme is already outdated

### ISSUE THREAD

**Issue by marcosrmendezthd** [open-telemetry/opentelemetry-go#257]
perhaps remove it and just leave the existing links to the samples?

sdktrace.Register, sdktrace.ApplyConfig...

**Comment by freeformzSFDC** [comment]
FWIW: This is why I encourage developers to write [`Example`](https://golang.org/pkg/testing/#hdr-Examples) functions whenever possible.

**Comment by rghetia** [comment]
check embedmd tool.

**Comment by freeformzSFDC** [comment]
For me *personally*: there is still a problem with that approach in that the examples aren't present in the docs I'm reading, so I'm unlikely to know they even exist. i.e. my starting point for a library is it's godoc. Maybe it's just me though?

**Comment by rghetia** [comment]
I support godoc Example. For some of the complex example, readme file with code snippets would be better off using  embedmd tool than not using it.

**Comment by jmacd** [comment]
@freeformz I suspect this is just a lack of knowledge, so it would be best if you made recommendations instead of suspecting you're in the minority. :)

**Comment by freeformzSFDC** [comment]
@jmacd I'm not sure I understand what you are getting at, feel free to msg me on gitter if you would like to provide confidential feedback (always appreciated).

**Comment by rghetia** [comment]
Remove code from the readme and put enough comments in example code. Simply link example in readme.

**Comment by jmacd** [comment]
@freeformzSFDC I apologize I didn't mean anything, except that we probably needed a little more guidance. I found this blog post to get me started https://blog.golang.org/examples

I also added a testable example to #265, although I had to introduce an option to suppress the timestamp to make the output deterministic.

https://github.com/open-telemetry/opentelemetry-go/pull/265/files#diff-ba31170c68cdc4ef54aa37d037ababaf
