### ISSUE TITLE
semconv: Backwards compatibility with v0 with v1?

### ISSUE THREAD

**Issue by trynity** [open-telemetry/opentelemetry-go#2577]
### Problem Statement

The refactoring of `semconv` has lead to some interesting problems when attempting to vendor multiple dependencies for our codebase. 

While `v0` versions per Semantic Versioning are inherently unstable, having backwards compatibility with `v0` while on `v1` would be extremely helpful, as Go Modules do not currently keep two separate versions when it's `v0/v1`, and only do that for later versions.

### Proposed Solution

Including the previously deleted code for `semconv` in the directory in which it used to live, would allow folks who still have packages which depend on `v0` versions of `otel` live simultaneously with code that depends on newer versions.

#### Alternatives

I have also filed an issue for `etcd` for the particular issue I'm encountering, but also asking here as a more general solution: https://github.com/etcd-io/etcd/issues/13664

**Comment by MrAlias** [comment]
cc @dashpole

**Comment by dashpole** [comment]
This is the same situation we have in the kubernetes/kubernetes codebase as well.  We have a dependency on Etcd, which hasn't released a new minor release in a while, and are stuck on a v0 release of otel-go.  Etcd's v3.6.0 release should be happening quite soon according to https://github.com/etcd-io/etcd/issues/13538, after which we will both be unblocked.

**Comment by dashpole** [comment]
I think the right answer here is probably to sit tight for a few weeks while we wait for them to release.  If we did want to make v1 backwards-compatible with v0, it would take a lot more than `semconv` to make that work, and I don't think that makes sense in this case.

**Comment by yue9944882** [comment]
IIUC the compatibility seems permanently broken for the package `go.opentelemetry.io/otel/internal/metric`. when i was trying to forcibly downgrade all of my otel dependencies to the old good `v0.20.0`, go mod command halted at "ambiguous import" b/c the package cut a `v0.26.0` release and it's conflicting w/ the old one. so i had to upgrade all of them to `v1`. with that being said, i think otel pkgs before `v0.26.0` release are no longer available via go mod.


```
$ go mod tidy
...
        k8s.io/apiserver/pkg/registry/generic imports
        k8s.io/apiserver/pkg/storage/storagebackend/factory imports
        k8s.io/component-base/traces imports
        go.opentelemetry.io/otel/exporters/otlp imports
        go.opentelemetry.io/otel/sdk/metric/controller/basic imports
        go.opentelemetry.io/otel/sdk/metric imports
        go.opentelemetry.io/otel/internal/metric: ambiguous import: found package go.opentelemetry.io/otel/internal/metric in multiple modules:
        go.opentelemetry.io/otel v1.3.0 (/Users/zuoxiu.jm/go/pkg/mod/go.opentelemetry.io/otel@v0.20.0/internal/metric)
        go.opentelemetry.io/otel/internal/metric v0.26.0 (/Users/zuoxiu.jm/go/pkg/mod/go.opentelemetry.io/otel/internal/metric@v0.26.0)
```

**Comment by mx-psi** [comment]
So that things are cross-linked, here is the related Kubernetes issue: kubernetes/kubernetes#106536

**Comment by mrsufgi** [comment]
for those with issues here - the 3.6.0-alpha.0 of etcd is out. solved my dependencies issues.

**Comment by MrAlias** [comment]
> for those with issues here - the 3.6.0-alpha.0 of etcd is out. solved my dependencies issues.

Closing as the underlying issue looks resolved. Please reopen if this is in error.

**Comment by vitaminmoo** [comment]
For anyone hitting this on etcd v3.5.x - Upgrade to at least v3.5.5 and the otel deps have been bumped upstream. No need to run the 3.6.0 alpha.
