### ISSUE TITLE
Add some notes on `opentelemetry-go/example/prometheus` 

### ISSUE THREAD

**Issue by Charlotte3240** [open-telemetry/opentelemetry-go#2584]
I got some demo code , but I can't understand this .
https://github.com/open-telemetry/opentelemetry-go/blob/main/example/prometheus/main.go

I need some note , please
Thanks !

**Comment by MrAlias** [comment]
Thanks for your interest in the project and feedback. Can you describe your confusion or what was unclear to you so we can take action on this?

**Comment by MrAlias** [comment]
Closing due to lack of response. Please reopen if you are able to provide the needed information. Thanks!
