### ISSUE TITLE
go get: module go.opentelemetry.io/otel@upgrade found (v1.3.0) 404

### ISSUE THREAD

**Issue by dino-ma** [open-telemetry/opentelemetry-go#2595]
go get: module go.opentelemetry.io/otel@upgrade found (v1.3.0), but does not contain package go.opentelemetry.io/otel/label

**Comment by dmathieu** [comment]
The `label` package was pre-GA (before 1.0.0). You need to use the `attribute` package with the most recent versions.
See https://github.com/open-telemetry/opentelemetry-go/tree/main/attribute

See also this example: https://github.com/open-telemetry/opentelemetry-go/blob/main/example/namedtracer/main.go#L33

**Comment by dino-ma** [comment]
We used to use Jaeger opentracing. Now we want to use this project. Is there any best practice to refer to?

**Comment by dmathieu** [comment]
OpenTelemetry doesn't necessarily conform to the APIs or package names in Opentracing.
You will therefore have to go through your project and update all calls so they import the proper packages and use the proper methods.

You can find several examples of usages of OpenTelemetry in the [example folder](https://github.com/open-telemetry/opentelemetry-go/tree/main/example).

**Comment by dino-ma** [comment]
We don't use collect directly, but client - > UDP - > agent - > Collector - > KFK - > injester - > es.
This example is not enough for me.(https://github.com/open-telemetry/opentelemetry-go/blob/main/example/jaeger/main.go)

**Comment by dmathieu** [comment]
Yes, this repository is the client library, not the collector.
You can also find documentation here: https://opentelemetry.io/docs/instrumentation/go/

After reading all that, you can also ask specific questions in the CNCF slack.

**Comment by dino-ma** [comment]
Thank you very much. I'll find out first.

**Comment by MrAlias** [comment]
This looks resolved, so I'm going to close. Please reopen if this is in error.
