### ISSUE TITLE
Consider splitting package `api/core` in more meaningful packages

### ISSUE THREAD

**Issue by paivagustavo** [open-telemetry/opentelemetry-go#261]
Currently, package `core` has a set of types/functions that doesn't really fit together. For example, it defines `Key` and `Value` types (widely used on the whole api), `Number` type (mainly or exclusively used for metrics) and `SpanContext` type (used on the trace api). 

Package name as `core` is discouraged by the Go community and the UX of these type of packages is bad. What does `core` mean for a user of the otel go client?

My proposal is to:
1. Move the `Key` and `Values` to the `api/key` package and consider renaming this package to `api/keyvalue`.
2. Move `Number` to a new package `api/metrics/number` or even `api/metrics` itself.
3. Move `SpanContext` to the `api/trace`.

**Comment by freeformzSFDC** [comment]
I agree with `core` being a bad name, but IMO more things should be folded into `api` itself (or some renamed package there of) vs making *more* sub packages of api.

**Comment by freeformzSFDC** [comment]
Related: I have a personal todo to take a stab at collapsing various split out packages into more coherent `api` / `sdk` packages. I can prioritize that if there is interest, but I haven't because my otel work is just one of many threads I'm pulling on.

**Comment by paivagustavo** [comment]
@freeformz Most of what I proposed is to move these types into already _existing_ packages and renaming packages. I agree with you that we have a lot of packages and there are a lot of naming conflicts on those.

**Comment by jmacd** [comment]
I personally haven't felt there's a problem. Could you two @paivagustavo and @freeformz come up with a complete proposal? I'd prefer not to see `api.` package prefixes, would prefer `otel.`. Maybe it would help if we split the API and SDK into separate repos? There has also been a request to split the metrics and trace API/SDK apart into separate repos, which I do not feel is worthwhile.

In any case I do feel that package names are very important to readability, and `core` isn't great. I look forward to your proposal(s).

**Comment by freeformzSFDC** [comment]
My proposal, or at least an initial take on it, is #295
