### ISSUE TITLE
Synchronize BatchSpanProcessor dropped count

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#2618]
It looks like `bsp.dropped` is never reset. This means we log the export count in terms of what was exported since last and the dropped count in terms of all times. This is inconsistent and we should unify on a single temprorality.

_Originally posted by @MrAlias in https://github.com/open-telemetry/opentelemetry-go/pull/2615#discussion_r807454772_

**Comment by MadVikingGod** [comment]
Closing for #2620
