### ISSUE TITLE
Mismatch temporality in BatchSpanProcessor Debug message

### ISSUE THREAD

**Issue by MadVikingGod** [open-telemetry/opentelemetry-go#2620]
Currently, the [debug message in the BatchSpanProcessor](https://github.com/open-telemetry/opentelemetry-go/blob/065ba75c4b9750665d8b577b170997cafeb8f903/sdk/trace/batch_span_processor.go#L253) reports two different temporalities of metrics.
- The number of spans exported - Delta
- The number of dropped spans - Cumulative

This issue is to discuss and track changes to BSP and its debug message.

Found in #2615
_Originally posted by @MrAlias in https://github.com/open-telemetry/opentelemetry-go/pull/2615#discussion_r808193193_

**Comment by pellared** [comment]
Duplicates https://github.com/open-telemetry/opentelemetry-go/issues/2618 ?

**Comment by MadVikingGod** [comment]
Yes, it was made at almost the same time.  MrAlias suggested closing #2613 2618 in favor of this.

**Comment by Aneurysm9** [comment]
Can we change the label to `total_dropped` or something like that to make it clearer that it is a running total?  I'm not sure I see an issue with the differing temporalities, as long as it is understood.  If that's not an option, I think I'd prefer option 3) making the exported span count cumulative.

**Comment by pellared** [comment]
Option 3) looks like an easy to implement, yet usable solution

**Comment by MadVikingGod** [comment]
To hopefully not stall this too long, I will create a PR to rename the label to `total_dropped`.  We can always revisit if there is a better approach offered.
