### ISSUE TITLE
potential name collision with currentSpanKey context key

### ISSUE THREAD

**Issue by ljmsc** [open-telemetry/opentelemetry-go#2631]
### Description
since the context key [currentSpanKey](https://github.com/open-telemetry/opentelemetry-go/blob/main/trace/context.go) is only the value zero it can potentially collide with other packages which uses the same strategy to safe data in the context (e.g. iota).

### Environment
- OS: all
- Architecture: all
- Go Version: all
- opentelemetry-go version: all

### Steps To Reproduce
store something else at value zero in your context. this will override the currentSpan which is stored by the otel lib in the context.

### Expected behavior
only the otel lib itself can manipulate the current span in the context. There should be no naming collision with context keys

### Potential Fix
I already created a PR https://github.com/open-telemetry/opentelemetry-go/pull/2630 to fix this issue.

**Comment by Aneurysm9** [comment]
There is no conflict potential as the type of the key value provided to `context.WithValue()` and `ctx.Value()` is included in the map key used internally.  See https://github.com/open-telemetry/opentelemetry-go/pull/2630#pullrequestreview-888917950 for more details.
