### ISSUE TITLE
Tag a 0.1 release

### ISSUE THREAD

**Issue by austinlparker** [open-telemetry/opentelemetry-go#264]
👋 As we'll soon be using this package in OpenTelemetry workshops, it'd be great if we could get a 0.1 tag/github release so that workshops can have a relatively stable point-in-time to pull.

**Comment by bogdandrutu** [comment]
Can this please be done today? The velocity workshop is tomorrow.

**Comment by bogdandrutu** [comment]
I think we need to create a branch, where we merge a PR that updates all go.mod/sum that refers to go.opentelemetry.io/otel to the new tag version, and set the tag to that PR after it is merged.

**Comment by krnowak** [comment]
This can be closed, right?

**Comment by rghetia** [comment]
yes
