### ISSUE TITLE
Refactor out the duplicated code in OTLP exporter

### ISSUE THREAD

**Issue by hanyuancheung** [open-telemetry/opentelemetry-go#2641]
### Problem Statement

Code in `exporter/otlp/otlpmetric(otlptrace)/internal/` are duplicated. Since the Metrics spec has been stable, as well as the Metrics API/SDK are going to be stable, we should refactor these duplicated codes.

### Proposed Solution

Refactor `(transform, connection, otlpconfig)` in `exporter/otlp/otlpmetric(otlptrace)/internal/`, move to `exporter/otlp/internal/*`.

#### Alternatives

Maybe do this after Metrics implementation is stable.

**Comment by dmathieu** [comment]
Note: I've started doing that with environment variables in #2608.

**Comment by hanyuancheung** [comment]
> Note: I've started doing that with environment variables in #2608.

I get it. After this PR was merged, I'll finish the other parts.

**Comment by hanyuancheung** [comment]
> #2608 has been merged.

Yeah, I‘ve started working on this.

**Comment by MrAlias** [comment]
Closed with https://github.com/open-telemetry/opentelemetry-go/pull/4420
