### ISSUE TITLE
many bad code styles

### ISSUE THREAD

**Issue by hidu** [open-telemetry/opentelemetry-go#2657]
### Problem Statement

I found many (`156 go files`) bad code styles in `import` part and `comment` part.

Here are some examples：
1. imports not sorted
https://github.com/open-telemetry/opentelemetry-go/blob/0e4c1563e9931ebb178576bb28360293d90b443c/trace.go#L17-L20

expect:
```go
import (
	"go.opentelemetry.io/otel/trace"

	"go.opentelemetry.io/otel/internal/global"
)
```

2. comment not begined with blank

https://github.com/open-telemetry/opentelemetry-go/blob/0e4c1563e9931ebb178576bb28360293d90b443c/trace/trace_test.go#L338-L344

expect:
```
// proto: func (sc SpanContext) HasSpanID() bool {}
```

### Proposed Solution

1. sort the imports groups: 1th-group is go pkgs, 2th is thrid-party module pkgs, 3th is current module pkgs
2. add a blank space after `//`

**Comment by Aneurysm9** [comment]
Closing for the reasons noted at https://github.com/open-telemetry/opentelemetry-go/pull/2658#issuecomment-1060002767.
