### ISSUE TITLE
Creating Span with given trace ID

### ISSUE THREAD

**Issue by Shadoka** [open-telemetry/opentelemetry-go#2665]
I am receiving a trace ID via http header and want to create a Span with this ID.

When creating a new Span I can't seem to change the randomly generated trace ID but I also don't see any way to set the trace ID prior to the creation of the Span.

Is it possible to set a specific trace ID?

**Comment by pellared** [comment]
You need to configure/use propagator(s).

Take a look at:
- https://opentelemetry.io/docs/instrumentation/go/manual/#propagators-and-context
- https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/instrumentation/net/http/otelhttp

**Comment by Shadoka** [comment]
Oh ok, I actually saw the entry on propagators in the first link you posted, but I couldn't really understand how I am supposed to use those. But the spec appears to be helpful in that regard.

Thank you for posting those links

**Comment by pellared** [comment]
You can also check how https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/instrumentation/net/http/otelhttp extracts and injects the context to the propagators (as it contains both client and server code).
