### ISSUE TITLE
Deprecation of x509.CertPool.Subjects()

### ISSUE THREAD

**Issue by MadVikingGod** [open-telemetry/opentelemetry-go#2667]
### Description

In the go 1.18 release [x509.CertPool.Subjects()](https://pkg.go.dev/crypto/x509@go1.18rc1#CertPool.Subjects) is deprecated.  This will cause issues with linting when we include 1.18 as a target

### Environment

- Go Version: 1.18
- opentelemetry-go version: latest

### Steps To Reproduce

1. Setup environment to use 1.18rc1
2. Run `make lint`
3. See error:
```
exporters/otlp/internal/envconfig/envconfig_test.go:291:18: SA1019: tlsCert.RootCAs.Subjects is deprecated: if s was returned by SystemCertPool, Subjects will not include the system roots. (staticcheck)
        assert.Equal(t, tlsCert.RootCAs.Subjects(), option.TestTLS.RootCAs.Subjects())
```

### Expected behavior

No linting errors.

**Comment by sourikghosh** [comment]
@MadVikingGod  @MrAlias
we can silence the error by `// nolinit //` but is there any other alternative to this?

**Comment by dmathieu** [comment]
This cert doesn't come from SystemCertPool, and it doesn't seem behavior should be impacted. And as far as I can see, there's no alternative.
So it seems marking the lint as ignored would be the best solution.
