### ISSUE TITLE
can't get timestamp in example/fib

### ISSUE THREAD

**Issue by congbaoyangrou** [open-telemetry/opentelemetry-go#2668]
### Description

I am new in otel, I just run the main in example/fib and tap a number, then I get the traces.txt inside which every timestamp like StartTime or EndTime are all '0001-01-01T00:00:00Z'. 

### Environment

- Architecture: M1
- Go Version: 1.17.5
- opentelemetry-go version: v1.4.0

### Steps To Reproduce

just run the function main() in examples/fib.

### Expected behavior

should have a correct timestamp 

Did I configure something wrong？

**Comment by Aneurysm9** [comment]
That example [configures the `stdouttrace` exporter](https://github.com/open-telemetry/opentelemetry-go/blob/main/example/fib/main.go#L39) to not emit timestamps.  Removing or commenting that line out will cause timestamps to appear.  I believe this is done as this example is used in the getting started guide and there is no need to tie its output to a point in time.
