### ISSUE TITLE
Go module package not the same as the code tagged in the repo

### ISSUE THREAD

**Issue by rotiv13** [open-telemetry/opentelemetry-go#2681]
### Description

Update to the lastest version is causing issues because the code might be out of sync some how inside the package it self where some attribute is missing

### Environment

- OS: Window 10
- Architecture: x64
- Go Version: 1.17
- opentelemetry-go version: 1.5.0

### Steps To Reproduce

Updating from v1.0.0-RC3 to v1.5.0 gives an error that `attribute.ARRAY` is not defined for code inside the go module package

![image](https://user-images.githubusercontent.com/13447561/158834314-97ecfa70-de69-4050-a8d9-05db23f112a5.png)

### Expected behavior

Update to work without the error

**Comment by Aneurysm9** [comment]
Did you update all `go.opentelemetry.io/otel/*` modules from `v1.0.0-RC3` to `v1.5.0`?  As a release candidate, the former version was still eligible for backward incompatible changes and indeed some were made before `v1.0.0`.

**Comment by rotiv13** [comment]
Yes. 
![image](https://user-images.githubusercontent.com/13447561/158838950-f4cf7c55-bea5-4280-9d2f-154fce00ae53.png)

**Comment by Aneurysm9** [comment]
and `go.opentelemetry.io/otel/exporters/jaeger` that is complaining?  Or the trace SDK?  Do you have transitive dependencies that are not updated?

**Comment by MrAlias** [comment]
The mentioned line in the v1.5.0 release does not refer to the `attribute.ARRAY` type.

https://github.com/open-telemetry/opentelemetry-go/blob/2cfc5210f254e9fa3537582830446a64ab3016ab/exporters/jaeger/jaeger.go#L251

This seems to imply the dependency has not been updated.

**Comment by rotiv13** [comment]
Yes I am using go modules. and I ran `go mod vendor` and `go mod tidy` before having this issue. 
![image](https://user-images.githubusercontent.com/13447561/158840904-d4d3ee5c-049c-4fa0-be28-76f7d7bada97.png)

this is a screenshot of the versions.yaml file in the package in the vendor folder

**Comment by rotiv13** [comment]
Figured it out. I have a dependency that is still using an older version of otel and it was not allowing me to update to the latest version. Sry to have bothered you guys. I will try and update the other dependency and try again.
