### ISSUE TITLE
Bug: TestExporterShutdown fail sometimes cause of DeadlineExceeded or context canceled

### ISSUE THREAD

**Issue by hanyuancheung** [open-telemetry/opentelemetry-go#2686]
### Description

When running `make test-race` on workflows, there is something wrong that happened. This issue looks like an occasional occurrence, which makes workflow fail sometimes.

### Steps To Reproduce

https://github.com/open-telemetry/opentelemetry-go/runs/5614008610?check_suite_focus=true
https://github.com/open-telemetry/opentelemetry-go/runs/5613998084?check_suite_focus=true

**Comment by teddylear** [comment]
I can try to take a look into this if that's alright.

**Comment by teddylear** [comment]
Taking a look into this I'm not sure what the issue is if someone else wants to take a look. My suspicion is that it has something to do with the improper context being grabbed after creation, but I'm newer to Golang and not sure how to resolve issue.

**Comment by Kaushal28** [comment]
Hi @hanyuancheung Could you provide the steps to reproduce this again? Seems like the links that you mentioned in the description do not have the data now.

**Comment by pellared** [comment]
@Kaushal28 Can you review https://github.com/open-telemetry/opentelemetry-go/pull/3989 and https://github.com/open-telemetry/opentelemetry-go/pull/3990? When I reproduced the problem(s) it was easier for me to try to fix them, but I would appreciate your reviews.
