### ISSUE TITLE
disscussion: Add ParseTraceParent And WithTraceParent methods?

### ISSUE THREAD

**Issue by 1046102779** [open-telemetry/opentelemetry-go#2708]
Is it necessary?

```golang
func (sc SpanContext) WithTraceParent(tp TraceParent) SpanContext{
    // ......
}

func ParseTranceParent(traceparent string) TraceParent {
    // ......
}
```

For example:

If a message in MQ is `cloudevent` message type, and it included trace infos, we need to directly parse `traceparent` and `tracestate` field in message.

https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/extensions/distributed-tracing.md#traceparent

**Comment by Aneurysm9** [comment]
This is what the [propagation API](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/context/api-propagators.md) is for.  Use the [TraceContext propagator](https://pkg.go.dev/go.opentelemetry.io/otel@v1.5.0/propagation#TraceContext).
