### ISSUE TITLE
In-memory metrics exporter for tests

### ISSUE THREAD

**Issue by MadVikingGod** [open-telemetry/opentelemetry-go#2722]
### Problem Statement

A number of contrib instruments have relied on metric/metrictest to provide an in-memory meterprovider/meter.  This was removed and a substitute is needed.

- It should be able to store 1 or more collection of both synchronous or asynchronous instruments.
- It should use the SDK, because this is an end to end test. (you can't record metrics with just the API, if recording is not needed use the nonrecording meter provider)
- Tests should be able to read the contents of any collections that have happened.

### Proposed Solution

In sdk/metric/metertest create an in-memory exporter, and some function to create and wireup a MeterProvider with that exporter.

**Comment by MrAlias** [comment]
@MadVikingGod has a start for this. If you are looking to work on this and want a starting point please ping @MadVikingGod here.
