### ISSUE TITLE
Move SpanContext from core package into trace

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-go#275]

**Comment by jmacd** [comment]
There are relationships with context propagation that belong outside the trace package. I think it could go in the trace package, but it might require a lot of package restructuring to avoid cycles.

This relates to #261

**Comment by VineethReddy02** [comment]
I will take this up.

**Comment by VineethReddy02** [comment]
Hey @jmacd I see chaos with moving this. When you say move SpanContext with all the functions defined it as context? Like
```
// IsValid checks if the span context is valid. A valid span context
// has a valid trace ID and a valid span ID.
func (sc SpanContext) IsValid() bool

// HasTraceID checks if the span context has a valid trace ID.
func (sc SpanContext) HasTraceID() bool

// HasSpanID checks if the span context has a valid span ID.
func (sc SpanContext) HasSpanID() bool
```

And in ```trace``` package can I place them in ```api.go```

**Comment by jmacd** [comment]
Yes, any SpanContext  methods will move with the type.

**Comment by dackroyd** [comment]
Resolved by the linked PR?
