### ISSUE TITLE
Consolidated feedback for the new Metrics SDK

### ISSUE THREAD

**Issue by MadVikingGod** [open-telemetry/opentelemetry-go#2757]
The new Metrics SDK is currently in a bit of flux.  It is currently being written here on this [branch](https://github.com/jmacd/opentelemetry-go/tree/jmacd/generic_sdk).  

With this, it brings generics that have a number of style decisions and new types with new names.  The goal of this issue is to consolidate all the feedback. If you create a PR (for a specific change) please link here to maintain visibility.

Current asks for feedback:
Maintainers add and remove topics as they are discovered, and resolved.

- Names: When reading through the code does the name of the struct or interface tell you what that does.
- Generic style: A number of components have 3+ generics.  This hurts readability and may be improved at the cost of performance.

**Comment by bogdandrutu** [comment]
@MadVikingGod another feedback related to no-op package for metrics https://github.com/open-telemetry/opentelemetry-go/issues/2767

**Comment by MrAlias** [comment]
This seems stale at this point, closing.
