### ISSUE TITLE
Inconsistent design for No-Op package choice

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-go#2767]
In `trace` package:

```golang
import 	"go.opentelemetry.io/otel/trace"

tp := trace.NewNoopTracerProvider()
```

In `metric` package:

```golang
import 	"go.opentelemetry.io/otel/metric/nonrecording"

tp := nonrecording.NewNoopMeterProvider()
```

I found this very confusing, if I use one API vs the other to look in different places for the no-op

**Comment by bogdandrutu** [comment]
Based on the trace package design the no-op implementation should leave in the same package as the interface definition.

**Comment by craigpastro** [comment]
Happy to give this a shot if that is okay?
