### ISSUE TITLE
no more spans sent with 1.6.1

### ISSUE THREAD

**Issue by vincentserpoul** [open-telemetry/opentelemetry-go#2768]
### Description

I realized a few days ago my spans were not sent anymore, I thought there was an error on my side, tried to tune things for a few days, to no avail.

### Environment

- OS: linux
- Architecture: x86
- Go Version: 1.16, 1.18
- opentelemetry-go version: v1.6.1
- collector: opentelemetry collector installed via the [helm chart](https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-collector) (0.47)

### Steps To Reproduce

I decided to go back to basics

1. Clone the [opentelemetry-go repo](https://github.com/open-telemetry/opentelemetry-go/) main branch
2. cd to the [example lying in the repo](https://github.com/open-telemetry/opentelemetry-go/tree/main/example/otel-collector).
3. go mod tidy, go run main.go > **spans are sent**
4. remove all the replace in go.mod, go mod tidy, go run main.go > **spans are not sent anymore**
5. re-add the replace of the main oltptrace in go.mod
```
replace go.opentelemetry.io/otel/exporters/otlp/otlptrace => ../../exporters/otlp/otlptrace
```
**spans are sent**.

### Expected behavior

importing the otlptrace@v1.6.1 doesn't seem to work properly.

**Comment by alexrudd** [comment]
Think I've also just hit this. Reverted to 1.5 and everything is working again.

**Comment by Aneurysm9** [comment]
Can you provide information about what collector and OTLP proto version you are using?  Please also see https://github.com/open-telemetry/opentelemetry-go/pull/2769#issuecomment-1090805970 for some details about changes to the OTLP  protocol and how they're (supposed to be) handled by this exporter and the collector.

**Comment by Aneurysm9** [comment]
We have released [`v1.6.2`](https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.6.2) which should mitigate issues that can arise with the use of the OTLP proto `v0.15.0` and any prior SDK release.  Can you please verify that your data flow is as expected with `v1.6.2`?

**Comment by vincentserpoul** [comment]
it is now flowing, thank you for the very short reaction time!

**Comment by enosi-rl** [comment]
I hit the same problem yesterday and spent too much time debugging the AWS side (tracing is in lambda's) before seeing the new release and landing on this issue.

v1.6.1 and the 0.48 release of the collector produced no spans with silent failure.

Thanks for the quick fix.
