### ISSUE TITLE
panic: comparing uncomparable type propagation.compositeTextMapPropagator

### ISSUE THREAD

**Issue by corani** [open-telemetry/opentelemetry-go#2772]
### Description

Calling `otel.SetTextMapPropagator` with a `propagation.NewCompositeTextMapPropagator` panics.

### Environment

- OS: Linux
- Architecture: x86
- Go Version: 1.17.8
- opentelemetry-go version: 1.6.2

### Steps To Reproduce

```go
package main

import (
    "go.opentelemetry.io/otel"
    "go.opentelemetry.io/otel/propagation"
)

func main() {
    prop := propagation.NewCompositeTextMapPropagator(
        // anything
    )

    otel.SetTextMapPropagator(prop) // this works
    otel.SetTextMapPropagator(prop) // this panics
}
```

results in:

```
panic: runtime error: comparing uncomparable type propagation.compositeTextMapPropagator
```

### Expected behavior

This worked in 1.6.1.

Issue was introduced in 1.6.2, in `otel/internal/global/state.go:79`.

**Comment by corani** [comment]
Appears to have been introduced in https://github.com/open-telemetry/opentelemetry-go/pull/2749

**Comment by dmathieu** [comment]
I guess this happens because we moved the comparison outside of `delegateTextMapPropagatorOnce.Do`.
So re-setting the propagator used not to run the comparison.

**Comment by corani** [comment]
Confirmed fixed, thanks for the quick action!
