### ISSUE TITLE
Propose to split sdk/exporter

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-go#278]
Currently the sdk/exporter contains exporters for both traces and metrics. I am proposing to split this into sdk/metricexporter and sdk/traceexporter.

**Comment by falonhnatiuk** [comment]
Help

**Comment by jmacd** [comment]
I would prefer `sdk/export/trace` and `sdk/export/metric`.  Users can rename these on import as "metricexport" and "traceexport" if need be, but this lets us use formal type names without stutter like `metric.Batcher` instead of `export.MetricBatcher`.
