### ISSUE TITLE
Latest OTEL v1.6.3 incompatible with v0.28.0

### ISSUE THREAD

**Issue by pkwarren** [open-telemetry/opentelemetry-go#2781]
### Description

We're attempting to upgrade dependencies from v1.6.0 to v1.6.3 and encountering this compilation failure during the upgrade:

```
# go.opentelemetry.io/otel/exporters/otlp/otlpmetric/internal/metrictransform
../../../../../go/pkg/mod/go.opentelemetry.io/otel/exporters/otlp/otlpmetric@v0.28.0/internal/metrictransform/metric.go:427:26: cannot use sum.CoerceToFloat64(desc.NumberKind()) (value of type float64) as type *float64 in struct literal
```

This appears to be fixed on the main branch, but there aren't yet compatible releases v0.29.0 (or later) of the unstable packages.

### Environment

- OS: Linux
- Architecture: x86_64
- Go Version: 1.17
- opentelemetry-go version: v1.6.3 + v0.28.0

### Steps To Reproduce

1. Create a test program which pulls in v1.6.3 and v0.28.0 dependency versions.

### Expected behavior

There should be compatible versions of opentelemetry-go (stable, unstable) and opentelemetry-go-contrib which can be used alongside each other.

**Comment by dmitryax** [comment]
The same issue observed on the collector side https://github.com/open-telemetry/opentelemetry-collector-contrib/runs/5980685721?check_suite_focus=true

**Comment by Aneurysm9** [comment]
I will prepare a new release of the metrics modules shortly that should address this issue.

**Comment by dmitryax** [comment]
Thank you!
