### ISSUE TITLE
Alibaba Cloud cannot display ip

### ISSUE THREAD

**Issue by longxinH** [open-telemetry/opentelemetry-go#2797]
### Problem Statement
Alibaba Cloud cannot display the ip field because the field collected by Alibaba Cloud is ```localEndpoint.ipv4```
<img width="897" alt="image" src="https://user-images.githubusercontent.com/12230340/163984714-b696bbf5-11c3-4c4c-98f8-91aef8334fea.png">

### Proposed Solution

The ```toZipkinSpanModel``` method only sets ```LocalEndpoint.serviceName```

**Comment by MrAlias** [comment]
Our Zipkin exporter should be compliant with the [OpenTelemetry specification](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.14.0/specification/trace/sdk_exporters/zipkin.md). Does Alibaba Cloud support this data-model?

**Comment by MrAlias** [comment]
Closing as this looks stale. Please re-open if this was an error.
