### ISSUE TITLE
Add back the Prometheus example code

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#2803]
Blocked by the metric SDK having a working example in the new_sdk/main branch

Removed in https://github.com/open-telemetry/opentelemetry-go/pull/2802

**Comment by MrAlias** [comment]
@damemi are you still able to work on this? I'm happy to pick it up if not.

**Comment by damemi** [comment]
@MrAlias yup! opened a PR at https://github.com/open-telemetry/opentelemetry-go/pull/3168, basically just copying examples from some of the tests and setting up an endpoint. please take a look

**Comment by MrAlias** [comment]
Closed by #3168
