### ISSUE TITLE
Add back the OpenCensus bridge code

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#2808]
Blocked by the metric SDK having a working example in the new_sdk/main branch

Removed in https://github.com/open-telemetry/opentelemetry-go/pull/2802

**Comment by dprotaso** [comment]
Is this still blocked? 

I'm actually looking for a to export OTel traces from a component that's instrumented with the OpenCensus SDK. Would bringing back the tracing bridge code be an option so we don't wait on the metrics SDK?

**Comment by MrAlias** [comment]
> Is this still blocked?
> 
> I'm actually looking to export OTel traces from a component that's instrumented with the OpenCensus SDK. Would bringing back the tracing bridge code be an option so we don't wait on the metrics SDK?

This bridge was never removed from the `main` branch and continues to be a part of the releases. It is removed on the `new_sdk/main` branch as we are reworking the metric SDK. The current release should still work to bridge tracing functionality.

**Comment by dprotaso** [comment]
oh great - thanks for the clarification

**Comment by dashpole** [comment]
I'm working on spec PR to specify how the OpenCensus bridge will be implemented: https://github.com/open-telemetry/opentelemetry-specification/pull/2722

**Comment by MrAlias** [comment]
Moving to the next milestone (Metric SDK Beta) based on discussion in the SIG today.

If https://github.com/open-telemetry/opentelemetry-specification/pull/2722 is resolved before the alpha release, we will move this back into the alpha milestone.

**Comment by MrAlias** [comment]
We have a replacement bridge.
