### ISSUE TITLE
Add sdk/metric/sdkinstrument package to new_sdk/main

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#2813]
This may not need to live in it's own package. Otherwise, we should try and find naming that does not include the term sdk (that is already a part of the package import path).

**Comment by MrAlias** [comment]
I'm guessing the naming choice comes from the desire to not collide with the API package `"go.opentelemetry.io/otel/metric/instrument"`.

**Comment by MrAlias** [comment]
I would purpose we rename this to `instrument` from there...

- Merge the `number` package into this.
  - Rename the `number.Number` type to `instrument.Value`
- Move the `Metrics`, `Scope`, `Instrument`, `Points` types from the `reader` package to here. They all seem related to metric instruments and seem better fit here.

**Comment by MadVikingGod** [comment]
Additionally when `NumberKind` and `InstrumentKind` are defined views will need to be able to Match based on them.
