### ISSUE TITLE
Merge the new_sdk/main branch into main

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#2818]
Blocked by all issues in https://github.com/open-telemetry/opentelemetry-go/milestone/22. This will be the last issue that closes the milestone.

- [ ] Create a PR to merge `new_sdk/main` into main
   - [ ] Update the changelog entries added in #3150 with the PR number
- [ ] Delete `new_sdk/main`
- [ ] Delete `new_sdk/example`

**Comment by MrAlias** [comment]
This needs to include deleting the new_sdk/example branch. It will no longer be needed.

**Comment by MrAlias** [comment]
The PR number needs to be added to the changelog entries added in #3150

**Comment by MrAlias** [comment]
Merging will orphan the following packages:

- `go.opentelemetry.io/otel/sdk/metric/aggregator/aggregatortest`
- `go.opentelemetry.io/otel/sdk/metric/aggregator/histogram`
- `go.opentelemetry.io/otel/sdk/metric/aggregator/lastvalue`
- `go.opentelemetry.io/otel/sdk/metric/aggregator/sum`
- `go.opentelemetry.io/otel/sdk/metric/aggregator`
- `go.opentelemetry.io/otel/sdk/metric/controller/basic`
- `go.opentelemetry.io/otel/sdk/metric/controller/controllertest`
- `go.opentelemetry.io/otel/sdk/metric/controller/time`
- `go.opentelemetry.io/otel/sdk/metric/export/aggregation`
- `go.opentelemetry.io/otel/sdk/metric/export`
- `go.opentelemetry.io/otel/sdk/metric/number`
- `go.opentelemetry.io/otel/sdk/metric/processor/basic`
- `go.opentelemetry.io/otel/sdk/metric/processor/processortest`
- `go.opentelemetry.io/otel/sdk/metric/processor/reducer`
- `go.opentelemetry.io/otel/sdk/metric/registry`
- `go.opentelemetry.io/otel/sdk/metric/sdkapi`
- `go.opentelemetry.io/otel/sdk/metric/selector/simple`

Do we want to plan a deprecation strategy for these? (Related to https://github.com/open-telemetry/opentelemetry-go/issues/2328)

**Comment by jmacd** [comment]
Question about go.opentelemetry.io/otel/sdk/metric/aggregator/exponential/mapping (which exists today and should stay _somewhere_).
I think it's OK if that package moves.

**Comment by MrAlias** [comment]
> Question about go.opentelemetry.io/otel/sdk/metric/aggregator/exponential/mapping (which exists today and should stay _somewhere_). I think it's OK if that package moves.

Indeed, this needs to be migrated to the new SDK. Please create an issue and add it to the [beta milestone](https://github.com/open-telemetry/opentelemetry-go/milestone/23) so we can track the work.
