### ISSUE TITLE
Implement the sdk/metric/number package

### ISSUE THREAD

**Issue by MadVikingGod** [open-telemetry/opentelemetry-go#2841]
~Blocked by #2799~

- [ ] Implement the sdk/metric/number package
- [ ] Ensure that the package is tested 
- [ ] Document the package in the godocs 
- [ ] Ensure all implementation `TODO`s have an issue tracking them.

**Comment by MrAlias** [comment]
Should the `number` and `sdkinstrument` package be combined into a single `instrument` package that instead calls the `Number` type `Value`?

**Comment by MrAlias** [comment]
It seems like this package may be avoidable based on the current direction the SDK (specifically the aggregations) is going.

Closing to remove possibly stale work. We can reopen this if it is deemed necessary in the future.
