### ISSUE TITLE
Define the data structure between the metric SDK and the reader.

### ISSUE THREAD

**Issue by MadVikingGod** [open-telemetry/opentelemetry-go#2889]
The form of the data exported from metrics readers will not be defined in #2809, or [#2885](https://github.com/open-telemetry/opentelemetry-go/pull/2885#discussion_r865016788), then it needs a formal definition.

Acceptance Criteria:

- [ ] Define where this type should live.  It is `sdk/metric/export` in #2885
- [ ] Define the type and the fields of the data returned by Collect()
- [ ] Define, if different, the type and fields of the data passed to Export() in a push exporter.

**Comment by MrAlias** [comment]
Is this a duplicate of #2959?

**Comment by MadVikingGod** [comment]
Yes, yet it is.

**Comment by MrAlias** [comment]
Closing in favor of #2959
