### ISSUE TITLE
v1.7.0 otlpgrpc dependency failure (go.opentelemetry.io/otel/metric/number)

### ISSUE THREAD

**Issue by adeturner** [open-telemetry/opentelemetry-go#2897]
### Description

```bash
$ go get -u go.opentelemetry.io/otel/exporters/otlp/otlpgrpc
go.opentelemetry.io/otel/exporters/otlp/otlpgrpc imports
    go.opentelemetry.io/otel/exporters/otlp/internal/transform imports
    go.opentelemetry.io/otel/metric/number: cannot find module providing package go.opentelemetry.io/otel/metric/number
```

I note [Release 1.6](https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.6.0) introduced _a breaking change of the unstable Metrics API. Code instrumented with the go.opentelemetry.io/otel/metric will need to be modified._

As a workaround this is looking like a good combination

	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.30.0
	go.opentelemetry.io/otel v1.5.0
	go.opentelemetry.io/otel/sdk v1.5.0
	go.opentelemetry.io/otel/sdk/metric v0.27.0
	go.opentelemetry.io/otel/trace v1.5.0
	go.opentelemetry.io/otel/exporters/otlp v0.20.0 // indirect
	go.opentelemetry.io/otel/internal/metric v0.27.0 // indirect
	go.opentelemetry.io/otel/metric v0.27.0 // indirect
	go.opentelemetry.io/otel/sdk/export/metric v0.20.0 // indirect
	go.opentelemetry.io/proto/otlp v0.7.0 // indirect

### Environment

- OS: Windows
- Architecture: x86
- Go Version: 1.18.1
- opentelemetry-go version: v1.7

### Steps To Reproduce

```bash
$ go clean -cache -modcache -i -r
$ go get -u go.opentelemetry.io/otel/exporters/otlp/otlpgrpc
go: downloading go.opentelemetry.io/otel v1.7.0
go: downloading go.opentelemetry.io v0.1.0
go: downloading go.opentelemetry.io/otel/exporters/otlp v0.20.0
go: downloading go.opentelemetry.io/otel/sdk v1.7.0
go: downloading go.opentelemetry.io/proto/otlp v0.7.0
go: downloading go.opentelemetry.io/otel/sdk/export/metric v0.20.0
go: downloading go.opentelemetry.io/proto v0.16.0
go: downloading go.opentelemetry.io/proto/otlp v0.16.0
go: downloading google.golang.org/grpc v1.46.0
go: downloading go.opentelemetry.io/otel/sdk/export/metric v0.28.0
go: downloading go.opentelemetry.io/otel/metric v0.30.0
go: downloading go.opentelemetry.io/otel/sdk/metric v0.30.0
go: downloading github.com/go-logr/logr v1.2.3
go: downloading go.opentelemetry.io/otel/trace v1.7.0
go: downloading github.com/golang/protobuf v1.5.2
go: downloading github.com/grpc-ecosystem/grpc-gateway v1.16.0
go: downloading google.golang.org/protobuf v1.28.0
go: downloading golang.org/x/net v0.0.0-20220425223048-2871e0cb64e4
go: downloading github.com/go-logr/stdr v1.2.2
go: downloading golang.org/x/sys v0.0.0-20220503163025-988cb79eb6c6
go: downloading google.golang.org/genproto v0.0.0-20220505152158-f39f71e6c8f3
go: downloading golang.org/x/text v0.3.7
go: downloading github.com/grpc-ecosystem/grpc-gateway/v2 v2.7.0
go: downloading github.com/grpc-ecosystem/grpc-gateway/v2 v2.10.0
go.opentelemetry.io/otel/exporters/otlp/otlpgrpc imports
    go.opentelemetry.io/otel/exporters/otlp/internal/transform imports
    go.opentelemetry.io/otel/metric/number: cannot find module providing package go.opentelemetry.io/otel/metric/number
```

### Expected behavior

Clean path with go get -u to latest

**Comment by dmathieu** [comment]
You need to use the [otlptrace](https://pkg.go.dev/go.opentelemetry.io/otel/exporters/otlp/otlptrace) and [otlpmetric](https://pkg.go.dev/go.opentelemetry.io/otel/exporters/otlp/otlpmetric) packages instead of `go.opentelemetry.io/otel/exporters/otlp`.

**Comment by adeturner** [comment]
Thanks @dmathieu
