### ISSUE TITLE
Is the cool-off time between go versions right?

### ISSUE THREAD

**Issue by MadVikingGod** [open-telemetry/opentelemetry-go#2918]
I would like to do a review of our go version process. Go1.18 was added in #2679, published in v1.6.0 on 2022-03-23, and I have proposed to remove go1.16 in #2917.

As currently written we support the two latest versions, and a dropped version (1.16) for up to 3 months. 

Is this an acceptable time period?
Is this too long?
Is this too short?
Was this time useful?

**Comment by dmathieu** [comment]
I don't know if we should support a version if it's not support anymore on the language side.

**Comment by MadVikingGod** [comment]
Notes from the SIG meeting:

The ask on the call is the first release after a new version of go, eg. go1.18, should add the new go version.  The release after that will remove the oldest version, eg. go 1.16.
