### ISSUE TITLE
Missing 'semconv' in the instruction

### ISSUE THREAD

**Issue by starzhanganz** [open-telemetry/opentelemetry-go#2932]
### Description
Perfect Doc!

However, following the instruction to create the files, it complains semconv is undefined.
I can see this is in the source code, but just need to be updated in the guide.
thanks!

`❯ go run .
# awesomeProject/fib
./main.go:58:4: undefined: semconv
./main.go:59:4: undefined: semconv
./main.go:60:4: undefined: semconv
`
So need to add the below line in the import to fix the issue
	`semconv "go.opentelemetry.io/otel/semconv/v1.10.0"`

### Environment

- OS: [Mac 12.4 darwin/amd64]
- Go Version: [1.18]

### Steps To Reproduce

1. Follow the instructions to create go file
2. Run 'go run .'
3. See errors

**Comment by dmathieu** [comment]
The getting started page is being revamped. You may want to look at #2895, which should resolve your issue.

**Comment by starzhanganz** [comment]
cool, I am closing this one. thanks
