### ISSUE TITLE
defer cancel 

### ISSUE THREAD

**Issue by starzhanganz** [open-telemetry/opentelemetry-go#2937]
### Description
Found an issue if defer the _cancel_ here: [link](https://github.com/open-telemetry/opentelemetry-go/blob/main/example/otel-collector/main.go#L93)
This application won't be interrupted if the gRPC or collecter server is not reachable, and that will cause the process can't be killed.

### Environment

- OS: [Mac]
- Architecture: [14.2]
- Go Version: [1.18]
- opentelemetry-go version: [e.g. v0.14.0, 3c7face]

### Steps To Reproduce

1. Start a collector on local running on local port localhost:4317

Example of the Docker-composer code to start the service:

```version: "3.9"

services:
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:latest
    command: "--config=/etc/collector-config.yaml"
    volumes:
      - ./collector-config.yaml:/etc/collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "4317:4317"   # OTLP gRPC receiver
    networks:
      - otel
    depends_on:
      - jaeger
      - .......
 
```
2.  copy code from https://github.com/open-telemetry/opentelemetry-go/blob/main/example/otel-collector/main.go, and change the port to localhost:4317   
3. Run 'go run .'
4. it should start sending test data
5. change the port to some port that doesn't exist, i.e. localhost:43171
6. Process hangs at "2022/06/02 09:58:29 Waiting for connection...", can't interrupt by press ctrl+c

### Expected behavior

the process should be able to be interrupted by press ctrl+c

**Comment by dmathieu** [comment]
Hi,

Thank you for reporting this issue. It is due to trying to open the gRPC connection without a timeout. So when the endpoint doesn't respond, the process blocks and waits forever.

I have opened #2939 as a fix.
