### ISSUE TITLE
Move to using Instrumentation Scope

### ISSUE THREAD

**Issue by MadVikingGod** [open-telemetry/opentelemetry-go#2941]
### Problem Statement

There has been a move in the specification to change the name of [Instrumentation Libary to Instrumentation Scope](https://github.com/open-telemetry/opentelemetry-specification/pull/2276).  Our implementation should move away from using Library to Scope.

### Proposed Solution

Take this in steps:
1. Create `instrumentation.Scope` that is the same shape as `instrumentation.Library`, and make Library an alias of Scope.  This should be a non-breaking change, but should be checked.
2. Deprecate `Instrumentation.Library`, and move all sdk uses to Scope.
3. For each area in the SDK, trace metrics exporter etc, move as many references from Library to Scope.  Examples would be internal struct names
    - For traces the biggest impediment is `Span.InstrumentationLibrary()`, we would need to add an extra Interface that could be checked and used[^1]. 
    - For Metrics there are a number of Interfaces that might need similar treatment
  

#### Alternatives

Change documentation to explain that Instrumentation Library should be treated as the Scope referenced in the specification.

#### Prior Art

- Java migrated traces over in this PR: https://github.com/open-telemetry/opentelemetry-java/pull/4215

[^1]: See the `io.Seeker` discussion in [Module Compatibility - Working with interfaces](https://go.dev/blog/module-compatibility)

**Comment by MrAlias** [comment]
IIRC this was closed with #2977. @craigpastro please reopen this if not.

**Comment by craigpastro** [comment]
Thanks @MrAlias! If there is anything more I can help with please let me know. Otherwise, yeah, let's close it. Thank you!
