### ISSUE TITLE
Subspans missing and indeterministic behavior 

### ISSUE THREAD

**Issue by mohitreddy1996** [open-telemetry/opentelemetry-go#2946]
### Description

Hi,
We are using otel go sdk to instrument our code to collect traces. We have currently configured the trace with `AlwaysSample`. We have otel collector deployment setup in K8s cluster where this service runs. We are missing few sub-spans/nested spans and not sure how to debug this. Any directions here would be super helpful. The code is more or less as follows:

```
cCtx, span := otel.Tracer("app").Start(ctx, "parent")
defer span.End()
span.SetAttributes(attribute.Int("numSubTrees", subspans)) 

eg, c := errgroup.WithContext(cCtx)  // we tried this just `eg := errgroup{}` and passed cCtx to `otel.Tracer("app").Start(cCtx,....)` below
for j := range subspans {
	idx := j
	eg.Go(func() error {
		subtreeCtx, subtreeSpan := otel.Tracer("app").Start(c, fmt.Sprintf("subtree_%d", idx))
		defer subtreeSpan.End()
        // some logic here
        return nil
	})
}
err = eg.Wait()

```

We do see a span `parent` and has attributes set to the desired length (100). But subspans of this parent span are undeterministic (sometimes and are often in 1 <= X <= 5 spans). Not sure if there is a limit on the subspans at the SDK level or otel collector has a processor which could drop some spans or the visualizer (AWS XRay) has limitations.

### Environment

- OS: linux
- Architecture: x86-64
- Go Version: 1.18.3
- opentelemetry-go version: v1.7.0

### Steps To Reproduce
Code pasted above

### Expected behavior

I would expect all nested spans to be displayed and traced - we are passing `cCtx` returned by the parent span for all the nested spans, therefore each of those have information about the parent span.

**Comment by MadVikingGod** [comment]
I built an example from the code you provided and found out a few things:

- Canceling the context of the errgroup doesn't prevent it from starting go routines,
- Canceling the context won't stop a span from starting or stopping,

A few things I would check is:
- You don't have any logic that prevents the eg.Go from starting,
- You don't have an early exit in the go routine that would exit before you start a span,
- If you are using batching (WithBatcher or the BatchSpanProcessor) that your queue size isn't low enough to drop some spans.
- If your exporter does batching, or size management (Jaeger) that doesn't drop your spans.

For debugging I would suggest that you make sure you enable error logging `otel.SetLogger`, and if you can add the stdouttrace exporter to your config to double check that something is not preventing the spans from being created in the first place.

**Comment by MrAlias** [comment]
Closing due to lack of response. Please reopen if this was in error and the suggestions did not lead to a resolution.
