### ISSUE TITLE
Add instrument kind to the SDK

### ISSUE THREAD

**Issue by MadVikingGod** [open-telemetry/opentelemetry-go#2947]
We need some way to distinguish the kind of instrument, eg. Sync Counter or Async Gauge, for determining which aggregation[^1] or temporality[^2] to use.

How is this different from the view.Instrument?  The scope of the views currently don't take into account what kind of instrument, because views neither match this nor make any changes based on this.  So there is no space in the view to record the kind.  

Potential solution:
This could follow the same kind of pattern as Temporarily in #2944

```go
type InstrumentKind uint8

const(
   undefinedInstrument Instrumentkind = iota
   SyncCounter
...
)
```

[^1]:  > [Default Aggregation](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#default-aggregation): The Default Aggregation informs the SDK to use the **Instrument Kind** ... to select an aggregation and configuration parameters.
[^2]: > [MetricReader](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#metricreader): The default output temporality (optional), a function of **instrument kind**.

**Comment by MrAlias** [comment]
Is there anyway we can use the Go type system to handle this instead of creating an additional enum to track it?

**Comment by MadVikingGod** [comment]
Not that I know of.  There isn't an interface that we can define that would encapsulate async[int|float]64 instruments, nor could we capture [sync|async]int64 instruments.  

We could create an 1.18 type argument, eg `syncint64.Counter | asyncfloat64.Gauge |...` but that only becomes useful in a function.  If you were to use that in a type it would color anything that tries to store that type.

```go
// This is ok, but limited usefulness because you can't determine which T within the scope of this function
func [T universalInterface] something(inst T)... 

// This is problematic because any slice or map of these must be resolved.  You can't store both a [syncint64.Counter]someType and [asyncfloat64.Gauge]someType in the same slice/map. 
type [T universalInterface] someType struct {
}
```
