### ISSUE TITLE
Bug in getting-started.md undefined: semconv

### ISSUE THREAD

**Issue by bradtopol** [open-telemetry/opentelemetry-go#2951]
### Description

I was following the steps in the getting-started.md to run the fib trace example.  
When I get to the $ go run . I get the following errors:

 go run .
# fib
./main.go:22:4: undefined: semconv
./main.go:23:4: undefined: semconv
./main.go:24:4: undefined: semconv

I then added the following import to main.go

"go.opentelemetry.io/otel/semconv/v1.10.0"

And then everything worked.   
Should this import be added to the example or did I do something wrong that I needed that?

### Environment

- OS: mac OS 11.6
- Architecture: [e.g. x86, i386] 
- Go Version: [e.g. 1.15] go version go1.17.6 darwin/amd64
- 
- opentelemetry-go version: [e.g. v0.14.0, 3c7face]
- bradtopol@Brads-MBP fib % go get go.opentelemetry.io/otel/sdk \
         go.opentelemetry.io/otel/exporters/stdout/stdouttrace
go: downloading go.opentelemetry.io/otel/sdk v1.7.0
go: downloading go.opentelemetry.io/otel v1.7.0
go: downloading go.opentelemetry.io/otel/exporters/stdout v0.20.0
go: downloading go.opentelemetry.io/otel/exporters/stdout/stdouttrace v1.7.0
go: downloading go.opentelemetry.io/otel/trace v1.7.0
go get: upgraded go.opentelemetry.io/otel v1.6.3 => v1.7.0
go get: added go.opentelemetry.io/otel/exporters/stdout/stdouttrace v1.7.0
go get: added go.opentelemetry.io/otel/sdk v1.7.0
go get: upgraded go.opentelemetry.io/otel/trace v1.6.3 => v1.7.0
go get: added golang.org/x/sys v0.0.0-20210423185535-09eb48e85fd7

### Steps To Reproduce
See above

### Expected behavior

I expected it to work without me having to add an extra import

If the example needs the extra import I am happy to submit a PR for this.

**Comment by hanyuancheung** [comment]
This is not a bug behavior, the getting-started.md is the basic example for newcomers, the full example you can find in 
https://github.com/open-telemetry/opentelemetry-go/tree/main/example/fib
I think it is clear enough to get started for beginners.

**Comment by bradtopol** [comment]
Hi @hanyuancheung but if you add the single extra line the code will actually compile and be runnable.  Why wouldn't you want to add the single line so that example compiles and the instructions would actually work as is?  I was smart enough to know it needed the  **semconv "go.opentelemetry.io/otel/semconv/v1.10.0"** add to the import list.  But wouldn't most folks trying to get started not know to add this when the code doesn't compile?  Shouldn't we reduce the friction of them getting started by having the example that we list in the markdown actually be able to compile without an error?
