### ISSUE TITLE
import json msg

### ISSUE THREAD

**Issue by huahuayu** [open-telemetry/opentelemetry-go#2974]
Hi, I have try the fib example https://github.com/open-telemetry/opentelemetry-go/tree/main/example/fib

In that example, it exports open telemetry JSON msg to the file.

```go
	// Write telemetry data to a file.
	f, err := os.Create("traces.txt")
	if err != nil {
		l.Fatal(err)
	}
	defer f.Close()

	exp, err := newExporter(f)
	if err != nil {
		l.Fatal(err)
	}
```

The json is like this:

```json
{
	"Name": "Run",
	"SpanContext": {
		"TraceID": "be0434cafbc1c5bfb198ac14b66dc007",
		"SpanID": "bd5631bfc93b7076",
		"TraceFlags": "01",
		"TraceState": "",
		"Remote": false
	},
	"Parent": {
		"TraceID": "00000000000000000000000000000000",
		"SpanID": "0000000000000000",
		"TraceFlags": "00",
		"TraceState": "",
		"Remote": false
	},
	"SpanKind": 1,
	"StartTime": "0001-01-01T00:00:00Z",
	"EndTime": "0001-01-01T00:00:00Z",
	"Attributes": null,
	"Events": null,
	"Links": null,
	"Status": {
		"Code": "Unset",
		"Description": ""
	},
	"DroppedAttributes": 0,
	"DroppedEvents": 0,
	"DroppedLinks": 0,
	"ChildSpanCount": 2,
	"Resource": [
		{
			"Key": "environment",
			"Value": {
				"Type": "STRING",
				"Value": "demo"
			}
		},
		{
			"Key": "service.name",
			"Value": {
				"Type": "STRING",
				"Value": "fib"
			}
		},
		{
			"Key": "service.version",
			"Value": {
				"Type": "STRING",
				"Value": "v0.1.0"
			}
		},
		{
			"Key": "telemetry.sdk.language",
			"Value": {
				"Type": "STRING",
				"Value": "go"
			}
		},
		{
			"Key": "telemetry.sdk.name",
			"Value": {
				"Type": "STRING",
				"Value": "opentelemetry"
			}
		},
		{
			"Key": "telemetry.sdk.version",
			"Value": {
				"Type": "STRING",
				"Value": "1.7.0"
			}
		}
	],
	"InstrumentationLibrary": {
		"Name": "fib",
		"Version": "",
		"SchemaURL": ""
	}
}
```

## Question

Since you have an export function, then I think there is an import function.

In my application, I can keep generating open telemetry compatible json msg streams, but how can I import them to take advantage of telemetry toolchains?

**Comment by dmathieu** [comment]
This library isn't the place for setting up data import. However, the [collector](https://github.com/open-telemetry/opentelemetry-collector) does that out of the box.

You may want to look at the [otel docs](https://opentelemetry.io/docs/) which show a graph with the recommended architecture to get data flowing from your application to your observability database.

**Comment by Aneurysm9** [comment]
The data format produced by the STDOUT exporter is for debugging only and cannot be re-imported to existing SDK structures.  It may change at any time and should not be relied upon for data interchange.  If you need to do data interchange then I recommend using OTLP or another, well-specified and stable, format.

**Comment by huahuayu** [comment]
Thanks, @dmathieu @Aneurysm9 I get you, I am studying the collector.
