### ISSUE TITLE
Occasional  error in unittest `TestExporterShutdown/testClientStopHonorsTimeout`

### ISSUE THREAD

**Issue by Petrie** [open-telemetry/opentelemetry-go#2989]
### Description
This is an error in unittest `TestExporterShutdown/testClientStopHonorsTimeout`

A few days ago, I open a pr https://github.com/open-telemetry/opentelemetry-go/pull/2987 , try fix golangci-lint not working correctly. But the pr checks occur a error in unittest `TestExporterShutdown/testClientStopHonorsTimeout` for exporter grpc client `Stop()` function :[exporters/otlp/otlptrace/otlptracegrpc/client.go#L130](https://github.com/open-telemetry/opentelemetry-go/blob/main/exporters/otlp/otlptrace/otlptracegrpc/client.go#L130)

I figure out in `Stop(ctx context.Context)` the `select` for `<-ctx.Done()` and `acquired ` may reach at the same time. In `select` if `acquired`  be exec first, The `Stop(ctx context.Context)` function  may return nil . when `Stop(ctx context.Context)` function return nil, unittest `TestExporterShutdown/testClientStopHonorsTimeout` and `TestExporterShutdown/testClientStopHonorsTimeout` will failure. 

### Environment

- OS: [Mac OS X]
- Architecture: [ i386]
- Go Version: [go version go1.17.11 darwin/amd64]
- opentelemetry-go version: [main]

### Steps To Reproduce
```shell 
cd exporters/otlp/otlptrace/otlptracegrpc/
while true ; do go clean -testcache | go list \
| xargs go test -v -timeout 60s -race -run \
  TestExporterShutdown/testClientStopHonorsTimeout; sleep 0.5;  done;
```
Wait for 2~3 minutes, the error while occur.

![image](https://user-images.githubusercontent.com/2252964/177048905-fb90b429-ad38-4a2f-80e6-4bf3a326aae8.png)

 
### Expected behavior
The all unittest pass

**Comment by pellared** [comment]
I think it was fixed or at least I have not seen it for a very long time.
