### ISSUE TITLE
Rename SetCurrentSpan to WithSpan

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-go#299]
context.WithValue derives from the existing context and doesn't replace the value in the existing context. It is misleading to call this function SetCurrentSpan because it doesn't set, it derives.

Also no need for "Current". It operates on any context and any span.

**Comment by paivagustavo** [comment]
Hey @rakyll, there is already an open issue for this https://github.com/open-telemetry/opentelemetry-go/issues/185. If you want to add your suggestion there :)

**Comment by rakyll** [comment]
Closing this, it looks like a duplicate of #185.
