### ISSUE TITLE
No need for an exported NoopSpan

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-go#300]
I looks like we are expecting user to program against Tracer implementations. User doesn't have to know about no op span types, we just need to return one from the NoopTracer. Maybe it would be useful to can unexport NoopSpan. Otherwise, it is polluting the API doc and make the user focus on an insignificant type.

**Comment by iredelmeier** [comment]
If we were to do this, I think it would help to change the signature of `CurrentSpan` to return a bool if there's no span on the context.

**Comment by jmacd** [comment]
I agree that we should get NoopSpan out of the documentation. This connected with the "IsRecording" question. If we had a better to test for a no-op span, it would help.

**Comment by iredelmeier** [comment]
"IsRecording" bites again!

**Comment by rghetia** [comment]
@rakyll  would moving this to api/noop package be okay?

**Comment by MrAlias** [comment]
This looks to be a stale issue. Please reopen in something remains to be addressed.
