### ISSUE TITLE
Async Gauge metric in Prometheus example is not consistently collected

### ISSUE THREAD

**Issue by mcbex** [open-telemetry/opentelemetry-go#3005]
### Description

I am running the prometheus example locally and noticed the [second update to the asynchronous gauge observer](https://github.com/open-telemetry/opentelemetry-go/blob/main/example/prometheus/main.go#L119-L122) was not being collected. 

I believe this is because in the example code there is a 5 second sleep after each set of metrics is emitted but [the controller](https://github.com/open-telemetry/opentelemetry-go/blob/main/example/prometheus/main.go#L46-L54) is configured with the default `CollectPeriod` of 10 seconds. So if you test the prometheus endpoint right after starting the server in order to observe the first value from the gauge, the second value will be overwritten before the collect period ends. Waiting > 5 seconds (but < 10) after starting the server to test the endpoint allows the second gauge value to be collected. 

This behavior is unintuitive and causes the example to be difficult to understand. 

### Environment

- OS: Darwin
- Architecture: ARM 64
- Go Version: 1.18
- opentelemetry-go version: v1.8.0

### Steps To Reproduce

1. From the project root `cd examples/prometheus`
2. Run `go run main.go`
3. As soon as the server starts `curl localhost:2222` and see that the `ex_com_one` gauge has a label of `ex_com_lemons=10` and a value of 1
4. Continue to run `curl localhost:2222` once a second or so. After the example reports that it has finished updating there is still only one metric for the `ex_com_one` gauge with a value of 13 and a label of `ex_com_lemons=10`

### Expected behavior

I expect that if I poll the prometheus endpoint frequently enough I will observe all three label/value states for the `ex_com_one` gauge and collect a metric with a label of `ex_com_lemons=13` and a value of 1. 

Based on the comments in "go.opentelemetry.io/otel/sdk/metric/controller/basic" I added the configuration `controller.WithCollectPeriod(time.Duration(0)),` to the controller after which the example behaved as I expected.

**Comment by mcbex** [comment]
I would be happy to submit a PR if my proposed change (configure the controller with a collect period of 0) seems reasonable.

**Comment by MrAlias** [comment]
Closing, stale.
