### ISSUE TITLE
Rename sdk/metric/export package to sdk/metric/metricdata

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#3013]
Currently the `sdk/metric/export` package contains the data types that metric telemetry are represented by.

The name of this package is problematic. It is not [uniquely descriptive of its contents](https://rakyll.org/style-packages/#short-but-representative-names) and [it conflicts with other packages](https://rakyll.org/style-packages/#clean-import-paths) we have previously published [^1] [^2].

[Another proposal](https://github.com/open-telemetry/opentelemetry-go/pull/2961#issuecomment-1165886976) was to use the package name `sdk/metric/data`. This name still does not effectively represent the contents of the package as being related to metrics. It has a high probability of colliding with other data type packages we will add in the future.

I propose we rename it to `sdk/metric/metricdata`. This follows other "test" package names (e.g. [`http/httptest`](https://pkg.go.dev/net/http/httptest@go1.18.4)), but instead will refer to fact that package contains data types related to metrics.

[^1]: https://pkg.go.dev/go.opentelemetry.io/otel/sdk/export
[^2]: https://pkg.go.dev/go.opentelemetry.io/otel/sdk/metric@v0.31.0/export

**Comment by hanyuancheung** [comment]
done with https://github.com/open-telemetry/opentelemetry-go/pull/3014
