### ISSUE TITLE
Custom histogram float

### ISSUE THREAD

**Issue by CodingJzy** [open-telemetry/opentelemetry-go#3028]
hello，I looked at the example of Prometheus and found that the float of histogram can only be set during initialization? In other words, a meter can only have one histogram float. Can't you set it when declaring the histogram type?

For example, the following hist1 and hist2 can only use the same precision []float64{1,5}?
```go
	config := prometheus.Config{
		DefaultHistogramBoundaries: []float64{1,5},
	}
	c := controller.New(
		processor.NewFactory(
			selector.NewWithHistogramDistribution(
				histogram.WithExplicitBoundaries(config.DefaultHistogramBoundaries),
			),
			aggregation.CumulativeTemporalitySelector(),
			processor.WithMemory(true),
		),
	)

    hist1, err := meter.SyncFloat64().Histogram("ex.com.one)
    hist2, err := meter.SyncFloat64().Histogram("ex.com.two")
```

**Comment by Aneurysm9** [comment]
The metrics SDK is being rewritten and will address this.  Please follow [this project](https://github.com/orgs/open-telemetry/projects/22) for updates.

**Comment by CodingJzy** [comment]
> The metrics SDK is being rewritten and will address this. Please follow [this project](https://github.com/orgs/open-telemetry/projects/22) for updates.

So is it available now?
