### ISSUE TITLE
Add SDK integration testing framework

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#3031]
Complete the `sdk/metric/metrictest` package.

- [ ] Create a testing framework to end-to-end test the SDK
  - Needs to be extensible. When new aggregators or interfaces are added the SDK it should not be challenging to test their addition.
  - Test all functionality the metric API will send to the SDK
  - Test the configuration of the SDK

**Comment by MrAlias** [comment]
This issues is referenced by https://github.com/open-telemetry/opentelemetry-go-contrib/issues/2755, https://github.com/open-telemetry/opentelemetry-go-contrib/issues/2757, https://github.com/open-telemetry/opentelemetry-go-contrib/issues/2759, and https://github.com/open-telemetry/opentelemetry-go-contrib/issues/2761 as adding integration testing utilities. It is not defined to accomplish this.

I'm going to create a separate issue to address that.

**Comment by MrAlias** [comment]
I wonder if this issue can't be moved to the post-GA project?

We can add an `sdk/metric/internal/metrictest` package post 1.0 that builds out the integration testing of the SDK. If another SDK requests access to that package we could then "stabilize" it by moving it to `sdk/metric/metrictest`.

The downside to delaying this is that it will likely never get done. Putting off adding tests for later is a good way to ensure they are never created.

**Comment by MrAlias** [comment]
Moving to the "Metric SDK (GA)" project. We should complete this prior to releasing a GA, but should also wait for the SDK to stabilize in the beta release so we don't churn updating the developed tests.

**Comment by joshcarp** [comment]
Hello. I came across the `go.opentelemetry.io/otel/sdk/metric/metrictest@v0.31.0`  and I was wondering why it got removed because there doesn't seem to be any alternative and there seems to be [some repos already using it](https://github.com/search?l=Go&q=go.opentelemetry.io%2Fotel%2Fsdk%2Fmetric%2Fmetrictest&type=Code)

**Comment by MrAlias** [comment]
> Hello. I came across the `go.opentelemetry.io/otel/sdk/metric/metrictest@v0.31.0` and I was wondering why it got removed because there doesn't seem to be any alternative and there seems to be [some repos already using it](https://github.com/search?l=Go&q=go.opentelemetry.io%2Fotel%2Fsdk%2Fmetric%2Fmetrictest&type=Code)

It was built against the v0.31.0 SDK which was replaced in v0.32.0. Use a manual reader and the `metricdatatest` package to test expected metric values: https://github.com/open-telemetry/opentelemetry-go/issues/3407

**Comment by MrAlias** [comment]
Unit testing metric instrumentation can be accomplished using a manual reader and the `metricdatatest` package.

Having a full "test suite" would duplicate much of the dedicated testing we already have built for our SDK. Closing as it will not be useful way to spend development effort to further this project in building testing we already have but making it generic for other SDKs.

**Comment by krak3n** [comment]
@MrAlias is there an example of how to do this?

**Comment by sk-** [comment]
@krak3n take a look at this file https://github.com/open-telemetry/opentelemetry-go-contrib/blob/f998e3f7c81927b5e7626551863e8db668b9e591/instrumentation/net/http/otelhttp/test/handler_test.go#L60
