### ISSUE TITLE
Inconsistent name with MeterProvider

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-go#304]
global.MeterProvider is returning a metric.Provider, so users would expect it to return a MetricProvider.

**Comment by jmacd** [comment]
With hindsight, I agree. The type it provides is named `metric.Meter` so it is providing a `Meter` and you could argue that it's correctly named. The same happens in tracing. The package is named `trace` and the type is `Tracer`. The API is `GetTracer`. So in this sense, `GetMeter` is consistent.

I think `GetMetricProvider` sounds better, although the entire named-Meter API specification is up for re-review, and we may end up removing this API in favor of something else.

**Comment by jmacd** [comment]
This type is named `metric.Provider` now.
