### ISSUE TITLE
could you please publish "exporters/otlp/internal" as module or publish new go.opentelemetry.io/otel/exporters/otlp ?

### ISSUE THREAD

**Issue by andyliuliming** [open-telemetry/opentelemetry-go#3046]
### Description

when use the gazelle to do some tidy, the 

```
go_repository(
        name = "io_opentelemetry_go_otel_exporters_otlp",
        build_file_generation = "on",
        build_file_proto_mode = "disable_global",
        importpath = "go.opentelemetry.io/otel/exporters/otlp",
        sum = "h1:PTNgq9MRmQqqJY0REVbZFvwkYOA85vbdQU/nVfxDyqg=",
        version = "v0.20.0",
    )
```

will be generated.

and that's because https://github.com/open-telemetry/opentelemetry-go/blob/exporters/otlp/v0.20.0/exporters/otlp/go.mod 
was ever published.
and that one was picked by the gazelle automatically.

could you please help publish a new package version or the new module?
### Environment

- Architecture: [e.g. x86, i386]
- Go Version: [e.g. 1.15]
- opentelemetry-go version: [e.g. v0.14.0, 3c7face]

### Steps To Reproduce

1. Use the configuration '...'
2. Run '...'
3. See error

**Comment by michaelrios** [comment]
This issue is blocking my team from using this package at all. We had to strip the package out entirely to continue moving forward.

**Comment by dariuschandrafoodpanda** [comment]
This issue also blocking my team's work. My work try to find `exporters/otlp/internal/envconfig` that is not exist in `exporters/otlp/v0.20.0` tag but exist in `v1.10.0` tag. Could you please release `exporters/otlp/v0.21.0`

**Comment by gsagula** [comment]
Any update on this issue?

**Comment by pellared** [comment]
It should be fixed as part of https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.17.0

**Comment by MrAlias** [comment]
> It should be fixed as part of https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.17.0
