### ISSUE TITLE
invalid operation: logr != nil (mismatched types logr.Logger and nil)

### ISSUE THREAD

**Issue by chenjazz** [open-telemetry/opentelemetry-go#3048]
GOROOT=D:\Users\80360840\sdk\go1.17.1 #gosetup
![image](https://user-images.githubusercontent.com/11512994/182007876-d0b78e95-12a5-4669-a381-80331e994537.png)

**Comment by MrAlias** [comment]
Based on the only included information with this issue it looks to be an invalid issue for this project. Rather, it relates to the k8s.io/klog project. I'm closing for this reason.

If this is in error, please [**add all of the requested bug report information included with the template**](https://github.com/open-telemetry/opentelemetry-go/issues/new?assignees=&labels=bug&template=bug_report.md&title=) and then reopen.
