### ISSUE TITLE
Jaeger promotion is sharp decline when the trace contains lots of spans

### ISSUE THREAD

**Issue by THMAIL** [open-telemetry/opentelemetry-go#3061]
### Problem Statement
When I Using Jaeger with opentelemetry-go SDK，I found that the opentelemetry-go SDK promotion is sharp decline when the trace contains lots of spans;

1. When a trace only contains one span, the Requests/sec is 252789.51；
2. When a trace contains two span, the Requests/sec is 212383.30；
3. When a trace contains four span, the Requests/sec is 135420.40；
4. When a trace contains eight span, the Requests/sec is 90875.16；
5. When a trace contains sixteen span, the Requests/sec is 49333.33；

### Proposed Solution

Increase the ability of concurrent, reduce the sharp decline in TPS when the numbers of span increase

#### Alternatives

Through pprof , I found the two most time -consuming places are sid-generator and newRecordingSpan：
1. the codes of sid-generator from opentelemetry-go

   ```go
   // NewIDs returns a non-zero trace ID and a non-zero span ID from a
   // randomly-chosen sequence.
   func (gen *randomIDGenerator) NewIDs(ctx context.Context) (trace.TraceID, trace.SpanID) {
   	gen.Lock()
   	defer gen.Unlock()
   	tid := trace.TraceID{}
   	_, _ = gen.randSource.Read(tid[:])
   	sid := trace.SpanID{}
   	_, _ = gen.randSource.Read(sid[:])
   	return tid, sid
    }
   ```

    Here use Lock，It's too heavy and when Multi -thread competition is fierce

2. the codes of newRecordingSpan from opentelemetry-go

   ```go
   func (tr *tracer) newRecordingSpan(psc, sc trace.SpanContext, name string, sr SamplingResult, config *trace.SpanConfig) *recordingSpan {
   	startTime := config.Timestamp()
   	if startTime.IsZero() {
   		startTime = time.Now()
   	}
   
   	s := &recordingSpan{
   		parent:      psc,
   		spanContext: sc,
   		spanKind:    trace.ValidateSpanKind(config.SpanKind()),
   		name:        name,
   		startTime:   startTime,
   		events:      newEvictedQueue(tr.provider.spanLimits.EventCountLimit),
   		links:       newEvictedQueue(tr.provider.spanLimits.LinkCountLimit),
   		tracer:      tr,
   	}
   
   	for _, l := range config.Links() {
   		s.addLink(l)
   	}
   
   	s.SetAttributes(sr.Attributes...)
   	s.SetAttributes(config.Attributes()...)
   
   	return s
   }
   ```
   
   Allocating memory costs much time and we need allocate memory for every span every time.Why don't we pre-allocate this memory or take other better measures?
   
   Once I delete the codes of sid-generator and newRecordingSpan , the Requests/sec can reach 174784.66 when a trace contains sixteen span. It is almost three times than the original ! ! !

3. Maybe there are places that can be optimized, waiting for the official discovery

#### Prior Art

I have tried to annotate the codes of sid-generator and newRecordingSpan，it get a good result, the Requests/sec from 48067.63 increase to 171664.33. Almost doubled ! ! !

### Additional Context
My collector is Jaeger ，SDK is opentelemetry-go
** Here is my test-code： **
```go
package main

import (
	"context"
	"fmt"
	"github.com/gin-gonic/gin"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/exporters/jaeger"
	"go.opentelemetry.io/otel/sdk/resource"
	tracesdk "go.opentelemetry.io/otel/sdk/trace"
	semconv "go.opentelemetry.io/otel/semconv/v1.9.0"
	"go.opentelemetry.io/otel/trace"
	"io"
	"math/rand"
	"net/http"
	"os"
	"strconv"
	"time"
)

var (
	//service     = "jaeger-OTtrace-demo-02"
	environment = "production"
	service     = os.Getenv("jaeger_servicename")
	id          = 1
	loopnum     = getInt("loopnum")
	attrsize    = getInt("attrsize")
	traceType   = os.Getenv("traceType")
)

func tracerProvider() *tracesdk.TracerProvider {
	exp, _ := jaeger.New(jaeger.WithAgentEndpoint(jaeger.WithAgentHost(os.Getenv("agent_host")), jaeger.WithAgentPort(os.Getenv("agent_port"))))
	tp := tracesdk.NewTracerProvider(
		//tracesdk.WithIDGenerator(&idGenerator{}),
		// Always be sure to batch in production.
		tracesdk.WithBatcher(exp),
		// Record information about this application in a Resource.
		tracesdk.WithResource(resource.NewWithAttributes(
			semconv.SchemaURL,
			semconv.ServiceNameKey.String(service),
			attribute.String("environment", environment),
			attribute.Int64("ID", int64(id)),
		)),
	)
	return tp
}

func (gen *idGenerator) NewIDs(ctx context.Context) (trace.TraceID, trace.SpanID) {
	return tid_temp, gen.NewSpanID(ctx, tid_temp)
}

var (
	tp = tracerProvider()
	tr = tp.Tracer(
		"tracerName = \"go.opentelemetry.io/contrib/instrumentation/github.com/gin-gonic/gin/otelgin\"",
		trace.WithInstrumentationVersion("semver:test"),
	)
)

func main() {
	gin.SetMode(gin.ReleaseMode)
	r := gin.New()
	//pprof.Register(r)
	r.GET("/", func(c *gin.Context) {
		produceTrace(c, tr, fileContent)
		c.String(http.StatusOK, "hello World!\n3")
	})
	r.Run(":8002")
}

func produceTrace(c *gin.Context, tr trace.Tracer, fileContent attribute.KeyValue) {
	//startTime := time.Now().UnixNano() / 1e6
	ctx, span := tr.Start(c.Request.Context(), "produceTrace")
	defer span.End()
	span.SetAttributes(fileContent)
	for i := 0; i < loopnum; i++ {
		//_, span2 := tr.Start(ctx, fmt.Sprintf("produceTrace-%d", i))
		_, span2 := tr.Start(ctx, "123")
		span2.End()
	}
	//fmt.Println(time.Now().UnixNano()/1e6 - startTime)
}

func randInt(min, max int) int {
	return rand.Intn(max-min) + min
}

func getInt(key string) int {
	value := os.Getenv(key)
	if value == "" {
		return 0
	}
	i, err := strconv.Atoi(value)
	if err != nil {
		return 0
	}
	return i
}

func CurrentTimeMillis() int64 {
	return int64(time.Now().UnixNano() / int64(time.Millisecond))
}
```

**Comment by Aneurysm9** [comment]
> * When a trace only contains one span, the Requests/sec is 252789.51；
> * When a trace contains two span, the Requests/sec is 212383.30；
> * When a trace contains four span, the Requests/sec is 135420.40；
> * When a trace contains eight span, the Requests/sec is 90875.16；
> * When a trace contains sixteen span, the Requests/sec is 49333.33；

49333.33 * 16 = 789333.28

Since your sample application is doing no real work you are only measuring the overhead of the request handing and span creation.  As you create more spans per request the balance of that overhead moves from the request handling to span creation.  Doing some simple multiplication still shows that more than three times as many spans are created in the same duration when creating 16 per request than when only creating one.  

Note also that when doubling the number of spans created the throughput decreases by less than half.  This indicates that there are other factors accounting for the throughput than simply span creation.

We do take performance seriously and have several [benchmarks ](https://github.com/open-telemetry/opentelemetry-go/runs/7661500407?check_suite_focus=true#step:4:309) around span creation.  These benchmarks indicate that spans could be created at about twice the rate you observed if no other work was being performed.  We have worked hard to minimize the number of allocations required to start a span, but they cannot be eliminated entirely as work must be done and data must be stored.

A mutex is required on the ID generator as the [random source is not safe for concurrent use](https://pkg.go.dev/math/rand#NewSource) by multiple goroutines and the ID generator must be safe for concurrent use by multiple goroutines.

**Comment by MrAlias** [comment]
Thanks for your interest in the project!

> Once I delete the codes of sid-generator and newRecordingSpan , the Requests/sec can reach 174784.66 when a trace contains sixteen span. It is almost three times than the original

We recognize that there is going to computational overhead in tracing application code. However, we are unable to just remove features and functionality to realize performance improvement. We are required to comply with the [OpenTelemetry specification](https://github.com/open-telemetry/opentelemetry-specification) and these proposed fixes do not. Please take a look at the specification and if you still have suggestions for performance improvements please reopen this with a revised and specific suggestion.
