### ISSUE TITLE
ability to judge if current span is root span

### ISSUE THREAD

**Issue by zhzure** [open-telemetry/opentelemetry-go#3067]
### Problem Statement

i got a use case when using open-telemetry. 
our project have a lots of polling request which directly query database in go routine, which means this kind of span ig root span and only root span, 
may be i could add tag like `IsRoot` in it if i can judge this span is root span

### Proposed Solution

may be like:
``` go
IsRoot() bool

```
in **Span** interface

**Comment by Aneurysm9** [comment]
The `Span` interface is intended to be write-only and is controlled by the [tracing API Span specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#span).  We cannot implement this change without changes to the specification.
