### ISSUE TITLE
module go.opentelemetry.io/otel/metric@latest found (v0.31.0), but does not contain package go.opentelemetry.io/otel/metric/registry

### ISSUE THREAD

**Issue by zelha** [open-telemetry/opentelemetry-go#3069]
### Description
Can't import metric/registry when using both redisotel ang otlpgrpc. When importing dependencies I get :

```
 go.opentelemetry.io/otel/sdk/metric/controller/basic imports
 go.opentelemetry.io/otel/metric/registry: module go.opentelemetry.io/otel/metric@latest found (v0.31.0), but does not contain package go.opentelemetry.io/otel/metric/registry
```
I could reproduce this dependency conflict only with both redisotel otlpgrpc in my project.

### Environment

- OS: Darwin MACM-FRJVNN2CP7 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T6000 arm64
- Architecture: arm64
- Go Version: go@1.19 also reproduced with go@1.17 
- opentelemetry-go version: v0.20.0

### Steps To Reproduce

1. Import both `"github.com/go-redis/redis/extra/redisotel/v9"`and `"go.opentelemetry.io/otel/exporters/otlp/otlpgrpc"`
2. Run `go mod tidy`
3. See error

You can find in this repository [zelha/debug-go-otelgrpc-redis](https://github.com/zelha/debug-go-otelgrpc-redis) a project that reproduces the issue.

### Expected behavior

The dependency should be resolved.

**Comment by Aneurysm9** [comment]
`v0.20.0` was a beta release from more than a year ago and is no longer supported.  Please use a current version of `otelgrpc`.
