### ISSUE TITLE
NoopTracer implements more than api.Tracer

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-go#307]
The following methods are not enforced by the api.Tracer:

```
func (t NoopTracer) WithComponent(name string) Tracer
func (t NoopTracer) WithResources(attributes ...core.KeyValue) Tracer
func (t NoopTracer) WithService(name string) Tracer
```

Ether remove them, or put them in the Tracer interface. If they have to be put in the Tracer interface, WithXXX might not be the best name. From a user perspective, it looks like the optional functional arguments pattern.

**Comment by jmacd** [comment]
These are dead code left over from a previous API change.
