### ISSUE TITLE
website_docs/libraries.md invalid HTTP link.

### ISSUE THREAD

**Issue by rahuldimri** [open-telemetry/opentelemetry-go#3074]
When we click on the [instrumentation libraries](https://github.com/open-telemetry/opentelemetry-go/blob/main/docs/reference/specification/glossary/#instrumentation-library) link we are getting 404 error.

![image](https://user-images.githubusercontent.com/107100022/183668762-319cbb58-87c7-4f07-9539-8bad4dd4e649.png)

**Comment by dmathieu** [comment]
The website_docs folder is meant to be built for the opentelemetry.io website. If you read the doc there, the link does work.

**Comment by rahuldimri** [comment]
@dmathieu thanks for the info. one question is here is why do we have HTTP link reference on the .md files.

![image](https://user-images.githubusercontent.com/107100022/183677192-501aa1d3-1d38-47ef-8fe5-4f90c47a0adb.png)

**Comment by dmathieu** [comment]
The markdown links are turned into actual links by the GitHub interface, there is nothing we can do about that. That's why there are links in that document.

**Comment by MrAlias** [comment]
Closed along with the #3075 

> This link is intended to be this way. The `https://opentelemetry.io` prefix was specifically dropped here: #2666
> 
> These files back the opentelemetry.io and are expected to have relative links to allow the communications SIG the freedom to move things without breaking this documentation.
