### ISSUE TITLE
Should the SDK API constrain the Readers that can be used?

### ISSUE THREAD

**Issue by MadVikingGod** [open-telemetry/opentelemetry-go#3085]
### Background

Currently, we require that the Readers provided to the `WithReader` Option be comparable.  We check that the two readers we create are comparable, but if a user embeds a Reader in a non-comparable struct WithReader will panic.  An example of how to trigger this can be found [here](https://github.com/MadVikingGod/opentelemetry-go/blob/df9265b309ab573caee22e72a9532331cc41afa4/sdk/metric/config_test.go#L136-L145).

This type of embedding will probably be used in the prometheus exporter.

### Problem Statement

Should we further constrain our option to prevent users from supplying a non-comparable reader?  This would likely be run into by exporter developers and hopefully caught by a working example.  

### Proposed Solution

We could create a ComparableReader interface that we constrain the WithReader with.  Here is an [example branch](https://github.com/MadVikingGod/opentelemetry-go/blob/00d063b9db90eb6a97bd2249ebc50f5653d52e28/sdk/metric/config.go#L133).

This would in effect turn the runtime panic into a compile-time error.  You wouldn't be able to use a non-comparable Reader with the only option we have.

This would have two drawbacks:

1. This would change the SDK API if done after the alpha is released.  We are allowed to, but I would like to minimize this if possible.
2. Because you can't cast `Reader` -> `ComparableReader` the output of New*Reader would have to change from Reader. 
  - Either to a `*manualReader`, which has usability concerns,
  - or to a `*ManualReader`, note this is exporting ManualReader, which means we need to guard aginst users using a `&ManualReader{}`

#### Alternatives

1) Accept the runtime error, and encourage exporter creators to check that it works with the SDK.
2) Remove the comparable constraint on readers.

**Comment by MrAlias** [comment]
Closing as https://github.com/open-telemetry/opentelemetry-go/pull/3233 looks to have resolved this. The `Reader` implementation no longer needs to be comparable. Please reopen if this was an error.

**Comment by MrAlias** [comment]
https://github.com/open-telemetry/opentelemetry-go/blob/b6a22abab751307b4851b3cc51728fa557f907bb/sdk/metric/config.go#L29

**Comment by MrAlias** [comment]
https://github.com/open-telemetry/opentelemetry-go/blob/b6a22abab751307b4851b3cc51728fa557f907bb/sdk/metric/pipeline.go#L404
