### ISSUE TITLE
continously logging the `context deadline exceeds` error

### ISSUE THREAD

**Issue by scarshad** [open-telemetry/opentelemetry-go#3088]
### Description
We are using otel http exporter and we are seeing this error logged continuously. Is anyone else facing this problem.

### A clear and concise description of what the bug is
```
  error = Post "http://***.traces/otlp/v0.9": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
my go mod file
```go
        github.com/bradfitz/gomemcache v0.0.0-20220106215444-fb4bf637b56d
	github.com/gin-gonic/gin v1.8.0
	github.com/go-redis/redis/extra/redisotel/v8 v8.11.5
	github.com/signalfx/splunk-otel-go/instrumentation/gopkg.in/olivere/elastic/splunkelastic v0.9.0
	go.mongodb.org/mongo-driver v1.9.1
	go.opentelemetry.io/contrib/instrumentation/github.com/bradfitz/gomemcache/memcache/otelmemcache v0.32.0
	go.opentelemetry.io/contrib/instrumentation/go.mongodb.org/mongo-driver/mongo/otelmongo v0.32.0
	go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc v0.32.0
	go.opentelemetry.io/contrib/propagators/b3 v1.7.0
	go.opentelemetry.io/contrib/propagators/ot v1.7.0
	go.opentelemetry.io/otel v1.7.0
	go.opentelemetry.io/otel/exporters/otlp/otlptrace v1.6.0
	go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp v1.6.0
	go.opentelemetry.io/otel/sdk v1.7.0
	go.opentelemetry.io/otel/trace v1.7.0
	google.golang.org/grpc v1.47.0
```

How I am initializing the package
```go
client := otlptracehttp.NewClient(
		otlptracehttp.WithHeaders(headers),
		otlptracehttp.WithEndpoint(*),
		otlptracehttp.WithURLPath(*),
		otlptracehttp.WithInsecure(),
	)

tracerProvider := sdktrace.NewTracerProvider(
		sdktrace.WithBatcher(otlptrace.New(context.Background(), client)),
		sdktrace.WithResource(Resource(serviceName, attributeMap)),
		//sdktrace.WithSampler(sampler),
	)

// rest of the code
```

**Comment by dmathieu** [comment]
This error indicates Go timed out while waiting for your OTLP provider to respond. It may be a connectivity issue, or within that external service.

**Comment by scarshad** [comment]
Sorry for the delay, somehow I missed it.
Can you please explain this `or within that external service` 
We have a collector service up and running and no pod restart, everything seems fine but the we are receiving this error very frequently.

**Comment by dmathieu** [comment]
That external service is your collector. The error indicates your collector didn't respond in time, so the request was cancelled.

**Comment by scarshad** [comment]
So, as far now. We are seeing this error in a few services which have the sudden spikes. So this error from a service which have the RPS increases from 1k to more than 40K. 
So, our collector pods are not able to handle this scenario. For now I am increasing the batch size for their service and observing.

**Comment by MrAlias** [comment]
> So, as far now. We are seeing this error in a few services which have the sudden spikes. So this error from a service which have the RPS increases from 1k to more than 40K. So, our collector pods are not able to handle this scenario. For now I am increasing the batch size for their service and observing.

Did this resolve your issue @scarshad? Can this issue be closed?

**Comment by scarshad** [comment]
Yes, it's resolved. We are good to close it.
PS: This issue is not that much related to the client, yes the custom batching helps us but the problem is due to the sudden traffic on the service. 

Thanks to @dmathieu for the help.

**Comment by Ca-moes** [comment]
Answering for similar error output, but different cause.

On my side it was a network error. When using the `otlphttp` exporter to send metrics to Mimir in a different cluster, Mimir was also in a different AWS VPC, and there was no VPC peering established for connection between private subnets.
