### ISSUE TITLE
Bug: WithAttributes should append instead of replacing attributes

### ISSUE THREAD

**Issue by iredelmeier** [open-telemetry/opentelemetry-go#309]
This would be especially useful for plugin customization.

**Comment by jmacd** [comment]
I'd call it a __bug__ that `WithAttributes` does not append.

**Comment by iredelmeier** [comment]
@jmacd I could get behind that characterization ;)

**Comment by iredelmeier** [comment]
(Also, this is a `good-first-issue`)
