### ISSUE TITLE
Suggestion: Rename non-api `propagation` package to `propagators`

### ISSUE THREAD

**Issue by iredelmeier** [open-telemetry/opentelemetry-go#311]
This would resolve the naming conflict with `api/propagation`.

**Comment by paivagustavo** [comment]
Agree that we should rename the package to `propagators` but I think the api package should be renamed too. Specs says `Propagators API`, so it make sense to use that.

To solve the naming conflict, what about we merge both this package to the api package? It seems that others (java and js) are doing this and it makes sense to me as well.
