### ISSUE TITLE
Refactor pipelineRegistry

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#3112]
It seems like the `pipelineRegistry` type does not need to be defined generic types. It is a requirement that is coming from the `createAggregators` method. However, there is already also [`createAggregators`](https://github.com/open-telemetry/opentelemetry-go/blob/8580a3525ccc01ee141264a910d19cf1d7ec4f8a/sdk/metric/pipeline.go#L243) function that is defined with generic value types. If we changed that function to accept a `pipelineRegistry` instead of a `Reader` the method could be dropped, the `pipelineRegistry` unified, and instruments would just call the function directly.

_Originally posted by @MrAlias in https://github.com/open-telemetry/opentelemetry-go/pull/3084#discussion_r948164484_

**Comment by MadVikingGod** [comment]
@MrAlias I believe this was reloved with #3115, correct?

**Comment by MrAlias** [comment]
> @MrAlias I believe this was reloved with #3115, correct?

Indeed :+1:
