### ISSUE TITLE
Suggestion: expose "default" propagators

### ISSUE THREAD

**Issue by iredelmeier** [open-telemetry/opentelemetry-go#312]
e.g., `const DefaultTextFormatPropagator TextFormatPropagator = HTTPTraceContextPropagator` (which I realize wouldn't technically compile due to lack of imports...)

This would help ensure consistency across plugins.

**Comment by jmacd** [comment]
This is a request for an alias, "DefaultTextFormatPropagator" that's equal to the HTTP propagator. This helps clarify that B3 is not the default.

Could we name the HTTP propagator "W3CTraceContextPropagator"?

**Comment by iredelmeier** [comment]
I think that renaming the HTTP propagator to `W3CTraceContextPropagator` would be worth doing, but is separate from the default.

**Comment by iredelmeier** [comment]
See #355 for the rename side of things.

**Comment by ptravers** [comment]
Would you mind if I picked up this issue?

**Comment by rghetia** [comment]
will be fixed by #494
