### ISSUE TITLE
Support instrumentation scope attributes in OTLP metric exporter

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#3140]
Follow up to https://github.com/open-telemetry/opentelemetry-go/issues/3129

**Comment by MadVikingGod** [comment]
Just a heads up, this isn't in a released version of the spec, and there is talk about pulling it back before the release: https://github.com/open-telemetry/opentelemetry-specification/issues/2762.  We may want to hold off until it becomes part of a spec release.

**Comment by MrAlias** [comment]
Closing in favor of tracking with #3368
