### ISSUE TITLE
Block release until the scope attribute specification issue is resolved

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#3145]
https://github.com/open-telemetry/opentelemetry-specification/issues/2762

**Comment by MrAlias** [comment]
We plan to revert the addition of scope attributes, make the release, and add them back in right after the release (to be released in v1.11.0).

**Comment by MadVikingGod** [comment]
Opened #3154 to allow us to not block the v1.10 release.  When that is merged we can move this to the 1.11 milestone.

**Comment by MadVikingGod** [comment]
The reverts are in, moving this to the 1.11 release.

**Comment by MrAlias** [comment]
From SIG meeting today:

- This should not block a release until the specification that includes these changes has been released.
- The spec changes, currently, look to only require the API accept attributes at Tracer/Meter/Logger creation. The SDK, it seems, is not yet required to handle/export these. A possible resolution to this issue would be to add the Meter/Tracer `WithScopeAttributes` options back but nothing more (including not adding them to the configs).
- Another option would be to chose a behavior we think close to what the specification will eventually include and build that in. That way users will be able to export scope attributes (dropping these attributes will likely be a pain point for users.

**Comment by MrAlias** [comment]
The upstream issue is closed and it doesn't look like there is a plan to add the attributes back as identifying. Given we have removed our implementation as well I'm going to close this issue as the release should not be blocked by this.
