### ISSUE TITLE
baggage.Members() returns members with `hasData` set to `false`

### ISSUE THREAD

**Issue by lgfa29** [open-telemetry/opentelemetry-go#3164]
### Description

_NOTE: I'm not sure if this is actually a bug or working as intended, so feel free to close it._

When calling [`baggage.Members()`](https://pkg.go.dev/go.opentelemetry.io/otel@v1.9.0/baggage#Baggage.Members) the slice of `Member` returned has [all elements with `hasData` set to `false`](https://github.com/open-telemetry/opentelemetry-go/blob/v1.9.0/baggage/baggage.go#L483-L487). This prevents them from being set in other baggages since [`baggage.SetMember()` will fail](https://github.com/open-telemetry/opentelemetry-go/blob/v1.9.0/baggage/baggage.go#L499-L501).

### Environment

- OS: macOS
- Architecture: x86
- Go Version: 1.19
- opentelemetry-go version: 1.9.0

### Steps To Reproduce

Sample playground: https://go.dev/play/p/tJa5-fMVCk1

### Expected behavior

Members returned by `baggage.Members()` can be used in other baggages.

**Comment by MrAlias** [comment]
This looks like something we failed to include in https://github.com/open-telemetry/opentelemetry-go/pull/2522

**Comment by lgfa29** [comment]
Thanks for the confirmation! I will try to get a PR with a fix soon :slightly_smiling_face:

**Comment by MrAlias** [comment]
@lgfa29 it looks like @hanyuancheung has submitted #3165 to address this. Please take a look at that PR before starting work here.

**Comment by lgfa29** [comment]
> @lgfa29 it looks like @hanyuancheung has submitted #3165 to address this. Please take a look at that PR before starting work here.

Oh awesome! I got sidetracked so I didn't have time to open the PR. That looks like the changes I was thinking of doing, so looks like I don't have to anymore 🙂 

Thanks for the heads-up!
