### ISSUE TITLE
Implement Histogram aggregator

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-go#317]
The metics export pipeline has support for configurable aggregators. In the SDK specification (WIP), https://github.com/open-telemetry/opentelemetry-specification/pull/347, four aggregators are specified that SHOULD be provided to support measure metric instruments.  One is currently missing from this set, the Histogram aggregator.  This aggregator should (probably) support both exponential bucket sizes and linear bucket sizes.

**Comment by jmacd** [comment]
I'm not sure if this is blocked on the spec or not. We've settled the issue about TimeSeries representation in the protocol, 
https://github.com/open-telemetry/opentelemetry-proto/issues/54
so I'm marking this as unblocked.

The basic Histogram Aggregator will be similar to the other Measure-kind of aggregators (DDSketch, Array, MinMaxSumCount) but will support configurable (and default) bucket ranges.  The protocol supports declaring a variety of bucket-range options, probably those should be mirrored in the Histogram aggregator.

**Comment by paivagustavo** [comment]
I've been working on this.
