### ISSUE TITLE
Support stand-alone exponential histogram data structure for use by OpenTelemetry components

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-go#3170]
### Problem Statement

https://github.com/open-telemetry/opentelemetry-go/issues/2501 describes adding stand-alone exponential histogram _mapping functions_ for use by OpenTelemetry components (e.g., [the OTel Collector's standard logging exporter](https://github.com/open-telemetry/opentelemetry-collector/pull/5938)). The same request exists for a stand-alone exponential histogram data structure (e.g., [the OTel Collector's statsd receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12951)).

### Proposed Solution

Following the decision in https://github.com/open-telemetry/opentelemetry-go/issues/3169, create a `structure` sub-package, a sibling of `mapping` that supports use in the Collector as well as by the metrics SDK. The contents of #3022 contain the pending `structure` package.

#### Alternatives

Presently, the pending PR https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12951 refers to Lightstep's copy of the code in #3022, which is acceptable as a temporary measure. Ideally we do not maintain this dependency indefinitely.

**Comment by MrAlias** [comment]
Added to the beta milestone. Please remove if this was in error.

**Comment by jmacd** [comment]
(I was going to ask you first :grin:)

**Comment by MrAlias** [comment]
Yeah, lets add it now than. We can always bump it later if want to re-scope the milestone, but it is good to track it as work that needs to be done for the metric SDK (at some point).
