### ISSUE TITLE
Document metrics on opentelemetry.io

### ISSUE THREAD

**Issue by cartermp** [open-telemetry/opentelemetry-go#3186]
Hello! This was discussed in the maintainer's meeting. The ask was that we (docs maintainers) come to language SIGs who are ready to start documenting metrics with an outline of what metrics docs should generally look like. We can iterate over time, but the main goal is to ensure that we have getting-started and manual instrumentation docs that cover all the essentials (initialization, creating an instrument, copy-pasteable code samples).

Here's some outlines!

Getting started: https://github.com/open-telemetry/opentelemetry.io/issues/1746#issuecomment-1250157077

Getting started is easiest to define, since Python is already complete. However, if a language (like Go) doesn't already follow this format, it's a bit more work. Mea culpa for me not following up on https://github.com/open-telemetry/opentelemetry-go/pull/2895, which is likely a prerequiste.

Manual instrumentation: https://github.com/open-telemetry/opentelemetry.io/issues/1746#issuecomment-1250157891

The initial take here is just to have each major instrument documented with a code sample. We can probably figure out an ideal way to organize all the metrics content over time.

Note that "✨✨ **HELP NEEDED!** ✨✨" is present in some places. That's where we need the most help. As a general rule of thumb, it's pretty easy for us to add and update code samples that just use the metric API. However, knowing how to _properly_ initialize things in the _most correct_ way is a challenge. At a minimum, if you can contribute that, then we can probably take it and run with it.

**Comment by pellared** [comment]
I had a chat with @svrnm and he suggested to take inspiration/structure/content from: https://opentelemetry.io/docs/instrumentation/js/manual/#metrics

**Comment by dmathieu** [comment]
And as a starting point/example, we have the otel-collector example about to be updated with metrics: https://github.com/open-telemetry/opentelemetry-go/pull/4466

**Comment by cartermp** [comment]
I agree with matching what JS has documented.

**Comment by cartermp** [comment]
Should this issue get transferred to the docs site, or are you all fine with tracking here?

**Comment by pellared** [comment]
> Should this issue get transferred to the docs site, or are you all fine with tracking here?

@cartermp For us it does not matter where it is as long as it will be in [this project](https://github.com/orgs/open-telemetry/projects/34).

**Comment by MrAlias** [comment]
@pellared did https://github.com/open-telemetry/opentelemetry.io/pull/3235 resolve this?

**Comment by MrAlias** [comment]
Views still need to be documented.

**Comment by pellared** [comment]
Done https://opentelemetry.io/docs/instrumentation/go/manual/#metrics
