### ISSUE TITLE
Consider to remove NoMinMax from ExplicitBucketHistogram

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-go#3194]
https://github.com/open-telemetry/opentelemetry-go/blob/baf9f18b00b9218981bb78a20490d03708aec66c/sdk/metric/aggregation/aggregation.go#L128

For the moment it does not make sense to allow configuration of this. We can always record them for delta Histogram/ExponentialHistogram

**Comment by Aneurysm9** [comment]
Why would we not want this to be configurable?  The values are optional in the spec and a user may not have a need for them.  In that case they should be able to avoid sending the data in the first place.

**Comment by bogdandrutu** [comment]
Then at least make it to be according to the specs, which says they cannot be present in Cumulative. So name it `NoMinMaxForDelta`

**Comment by MrAlias** [comment]
> Then at least make it to be according to the specs, which says they cannot be present in Cumulative. So name it `NoMinMaxForDelta`

@bogdandrutu can you link to the part of the specification that min/max cannot be present for cumulative temporality?

**Comment by bogdandrutu** [comment]
Here is the text from the [data model](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/data-model.md)

> The aggregation temporality also has implications on the min and max fields. Min and max are more useful for Delta temporality, since the values represented by Cumulative min and max will stabilize as more events are recorded. Additionally, it is possible to convert min and max from Delta to Cumulative, but not from Cumulative to Delta. When converting from Cumulative to Delta, min and max can be dropped, or captured in an alternative representation such as a gauge.

**Comment by bogdandrutu** [comment]
@MrAlias found in the specs this as an option to the aggregation. The only difference is that it is a bit different as name `RecordMinMax` see https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#explicit-bucket-histogram-aggregation

**Comment by MrAlias** [comment]
> @MrAlias found in the specs this as an option to the aggregation. The only difference is that it is a bit different as name `RecordMinMax` see https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#explicit-bucket-histogram-aggregation

Gotcha. We chose a different name so the zero value of the field matches what the default of the specification defines to be the default behavior. That way when users use `ExplicitBucketHistogram{}` they get the default specified value.

**Comment by MrAlias** [comment]
> Here is the text from the [data model](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/data-model.md)
> 
> > The aggregation temporality also has implications on the min and max fields. Min and max are more useful for Delta temporality, since the values represented by Cumulative min and max will stabilize as more events are recorded. Additionally, it is possible to convert min and max from Delta to Cumulative, but not from Cumulative to Delta. When converting from Cumulative to Delta, min and max can be dropped, or captured in an alternative representation such as a gauge.

From this it sounds like this isn't required to not be recorded, just that it is likely going to be less useful for cumulative data, right?
