### ISSUE TITLE
No way to configure default histogram buckets with prometheus exporter

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-go#3196]
This refers to the default value of the Reader, since the Prometheus Exporter implementation creates its own reader. I can create my own reader and wrap prometheus exporter, but that does not seem nice.

**Comment by bogdandrutu** [comment]
Actually the wrapping does not work, since the `aggregation` is a private func in the Reader interface, so cannot override.

**Comment by MrAlias** [comment]
Yeah, this was identified in the PR adding the exporter: https://github.com/open-telemetry/opentelemetry-go/pull/3135#discussion_r969765408

I think we could add an option to the Prometheus exporter package to support this, e.g. `WithDefaultAggregationSelector` similar to the main reader option. The issue with this approach would be if other reader options are added later they would need to be duplicated in the Prometheus exporter package.

It would be ideal if a prom option was just a superset of the reader options, but the need to restrict temporality selection means a user shouldn't be allowed to pass that option.

**Comment by MrAlias** [comment]
For the time being, you can create a view for all histograms with an override. Something like this: https://github.com/open-telemetry/opentelemetry-go-contrib/blob/91e5196bccb7897f0b025f0175ac8e6561488443/instrumentation/github.com/gocql/gocql/otelgocql/example/client.go#L144-L154, but with a different selector that matches all hists.

**Comment by r3code** [comment]
The workaround to override buckets is
```
import { 
  "go.opentelemetry.io/otel/exporters/prometheus"
  "go.opentelemetry.io/otel/sdk/metric"
  ...
}

func defaultBoundaries() []float64 {
	return []float64{50, 100, 300, 500, 750, 1000, 1500, 2000, 2500, 3000, 5000}
}

func DefaultBucketsAggregation(ik metric.InstrumentKind) metric.Aggregation { //nolint:ireturn
	switch ik {
	case metric.InstrumentKindCounter, metric.InstrumentKindUpDownCounter, metric.InstrumentKindObservableCounter, metric.InstrumentKindObservableUpDownCounter:
		return metric.AggregationSum{}
	case metric.InstrumentKindObservableGauge, metric.InstrumentKindGauge:
		return metric.AggregationLastValue{}
	case metric.InstrumentKindHistogram:
		return metric.AggregationExplicitBucketHistogram{
			Boundaries: defaultBoundaries(),
			NoMinMax:   false,
	}
}
...
promExporter, err := prometheus.New(
  prometheus.WithRegisterer(<prometheus>),
  prometheus.WithAggregationSelector(DefaultBucketsAggregation),
)
```
