### ISSUE TITLE
Do not forget to merge metric/global into top level package

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-go#3198]
See https://github.com/open-telemetry/opentelemetry-go/blob/main/metric/global/global.go, this needs to be consistent with trace and be available under `go.opentelemetry.io/otel`.

**Comment by Aneurysm9** [comment]
That cannot happen until after the metrics API is in a `v1.x` module.

**Comment by bogdandrutu** [comment]
>  That cannot happen until after the metrics API is in a v1.x module.

I know my english is very bad, but I tried to point in the title that this should be a "tracking" issue to "not forget" to do this. It does not say do it now.

**Comment by MrAlias** [comment]
Resolved by https://github.com/open-telemetry/opentelemetry-go/pull/3818
