### ISSUE TITLE
May be better to return a pointer to View, since it is a pretty large struct

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-go#3199]
https://github.com/open-telemetry/opentelemetry-go/blob/main/sdk/metric/view/view.go#L54, also change methods to be on the pointer instead of value, to avoid unnecessary copy every time match is called.

**Comment by jyz0309** [comment]
Can I take this issue? :)

**Comment by bogdandrutu** [comment]
The PR was closed based on wrong assumptions:
The benchmark to measure New is not the relevant part, calling funcs on View is the one that worries more if "performance" was seen as the major reason, though I believe is the correct way to not pollute the stack and every larger object to be heap allocated and avoid unnecessary copies of the struct.

**Comment by bogdandrutu** [comment]
@MrAlias why did you remove this from the milestone, it is still needed in my opinion...

**Comment by MrAlias** [comment]
> @MrAlias why did you remove this from the milestone, it is still needed in my opinion...

We closed that milestone in favor of tracking beta with a project and releases with milestones. It's still on the list of things to do 🙂

**Comment by MrAlias** [comment]
The view design was changed in the completion of https://github.com/open-telemetry/opentelemetry-go/issues/3399.

This issue is no longer relevant to the new design. Closing.
