### ISSUE TITLE
Add JSON encoder to stdoutmetric exporter that ignores timestamps

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#3223]
The current stdoutmetric exporter uses a JSON encoder to print metric data to STDOUT. It can be configured with alternate encoders. For example and demonstration purposes, it is needed to print metric data without timestamp. Otherwise, the produced output will continually change. Therefore, a new JSON encoder needs to be added to the exporter package that ignores these timestamps, likely just printing a zero value for them instead.

- [ ] Add timestamp redacting JSON encoder to the stdoutmetric package
- [ ] Update the example code in the stdoutmetric package to use the SDK directly to output metric data using the new encoder.

**Comment by fatsheep9146** [comment]
Can I take this issue? @MrAlias

**Comment by Petrie** [comment]
hi @MrAlias , I would like to work on this issue, please assign it to me.
