### ISSUE TITLE
Upgrade golang.org/x/sys/unix to at least v0.0.0-20220412211240-33da011f77ad for vulnerability fix

### ISSUE THREAD

**Issue by marcofeltmann** [open-telemetry/opentelemetry-go#3234]
### Description

According to the new Go vulnerability check there is a security issue in golang.org/x/sys/unix package before v0.0.0-20220412211240-33da011f77ad, which is currently used by  go.opentelemetry.io/otel/sdk v1.10.0 (resource subpackage)

### Environment

- OS: Linux gopherbook 5.19.0-1-amd64 # 1 SMP PREEMPT_DYNAMIC Debian 5.19.6-1 (2022-09-01) x86_64 GNU/Linux
- Architecture x86_64
- go version go1.19.1 linux/amd64
- opentelemetry-go version: v1.10.0 (updated minutes ago)

### Steps To Reproduce

1. `go install golang.org/x/vuln/cmd/govulncheck@latest`
2. `govulncheck package/using/otel/sdk`

### Expected behavior
I don't want to see any vulnerability issued packages used here.

### Reality

```
govulncheck ./...

govulncheck is an experimental tool. Share feedback at https://go.dev/s/govulncheck-feedback.

Scanning for dependencies with known vulnerabilities...
No vulnerabilities found.

=== Informational ===

The vulnerabilities below are in packages that you import, but your code
doesn't appear to call any vulnerable functions. You may not need to take any
action. See https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck
for details.

Vulnerability #1: GO-2022-0493
  When called with a non-zero flags parameter, the Faccessat function
  can incorrectly report that a file is accessible.

  Found in: golang.org/x/sys/unix@v0.0.0-20220111092808-5a964db01320
  Fixed in: golang.org/x/sys/unix@v0.0.0-20220412211240-33da011f77ad
  More info: https://pkg.go.dev/vuln/GO-2022-0493
```

```
go mod why golang.org/x/sys/unix

# golang.org/x/sys/unix
github.com/company/package
go.opentelemetry.io/otel/sdk/resource
golang.org/x/sys/unix

```

**Comment by MrAlias** [comment]
https://pkg.go.dev/vuln/GO-2022-0493
