### ISSUE TITLE
Getting parent span attributes from a span

### ISSUE THREAD

**Issue by mehdihadeli** [open-telemetry/opentelemetry-go#3242]
Hi,
How can I get parent span attributes or whole parent span from a span?

**Comment by dmathieu** [comment]
That is not possible.
Parent spans don't necessarily come from the same service.
And even with only local spans, storing every trace tree would have a major performance impact on the SDK.

**Comment by dmathieu** [comment]
If your intent is to retrieve the main span from your service (for example, the HTTP span), one solution would be to have a middleware running first, which adds that span into your context.
You can then retrieve that specific span as needed.

**Comment by mehdihadeli** [comment]
@dmathieu Thanks for your response,
My use case is passing a message `correclationId` subsequently to next spans in the local service spans. And I want to have this `correlationId` in the all spans.
How can I retrieve specific span data?

**Comment by dmathieu** [comment]
Use baggage? https://opentelemetry.io/docs/concepts/signals/baggage/
https://pkg.go.dev/go.opentelemetry.io/otel/baggage

**Comment by mehdihadeli** [comment]
@dmathieu Yes, I think this works for passing my ID subsequently. 
But one question, Is it possible to retrieve specific span from the context, for example with span ID or something else?

**Comment by dmathieu** [comment]
You can store spans within the context as [values](https://pkg.go.dev/context#WithValue). This is how the SDK allows storing and retrieving the current span.
See https://github.com/open-telemetry/opentelemetry-go/blob/main/trace/context.go#L25

However, you have to pass the full span into the context. You can't find a span by ID.

**Comment by mehdihadeli** [comment]
Yes, so I just have access to the last stored span in the context, correct? And previous spans in the context will override

**Comment by dmathieu** [comment]
You can store any other span in another value that you own.

**Comment by dmathieu** [comment]
Something like:

```golang
package telemetry

type traceContextKeyType int
const mainSpanKey traceContextKeyType = iota

func ContextWithMainSpan(parent context.Context, span Span) context.Context {
	return context.WithValue(parent, mainSpanKey, span)
}

func MainSpanFromContext(ctx context.Context) Span {
	if ctx == nil {
		return noopSpan{}
	}
	if span, ok := ctx.Value(mainSpanKey).(Span); ok {
		return span
	}
	return noopSpan{}
}
```

Then, in a middleware that runs first, you change the request's context to be one which holds your main span.
And whenever you need to retrieve that main span, you can use `telemetry.MainSpanFromContext`.

**Comment by mehdihadeli** [comment]
> Something like:
> 
> ```go
> package telemetry
> 
> type traceContextKeyType int
> const mainSpanKey traceContextKeyType = iota
> 
> func ContextWithMainSpan(parent context.Context, span Span) context.Context {
> 	return context.WithValue(parent, mainSpanKey, span)
> }
> 
> func MainSpanFromContext(ctx context.Context) Span {
> 	if ctx == nil {
> 		return noopSpan{}
> 	}
> 	if span, ok := ctx.Value(mainSpanKey).(Span); ok {
> 		return span
> 	}
> 	return noopSpan{}
> }
> ```
> 
> Then, in a middleware that runs first, you change the request's context to be one which holds your main span. And whenever you need to retrieve that main span, you can use `telemetry.MainSpanFromContext`.

Thanks for your guide.
