### ISSUE TITLE
Add multiple exporter in the config

### ISSUE THREAD

**Issue by mehdihadeli** [open-telemetry/opentelemetry-go#3246]
Hi,
Is it possible adding multiple exporter like Jaeger and zipkin together in the config?

**Comment by dmathieu** [comment]
Sure. When you use WithSyncer/WithBatcher/WithSpanProcessor on TracerProvider initialization, the created SpanProcessor is appended to an array.
So you just have to use `WithX` multiple times.

See https://github.com/open-telemetry/opentelemetry-go/blob/13ddf7d31e389c891689eca29428bcc72ef98572/sdk/trace/provider.go#L294-L310

Example:

```
tp := sdktrace.NewTracerProvider(
	sdktrace.WithBatcher(firstExporter),
	sdktrace.WithBatcher(secondExporter),
)
```

**Comment by mehdihadeli** [comment]
@dmathieu Thanks
