### ISSUE TITLE
Support for Jaeger remote sampler 

### ISSUE THREAD

**Issue by almariah** [open-telemetry/opentelemetry-go#327]
The remote sampler will consult Jaeger agent for the appropriate sampling strategy to use. This allows controlling the sampling strategies in the services from a central configuration in Jaeger backend, or even dynamically.

**Comment by jmacd** [comment]
@lizthegrey Do you have thoughts on this, given your OTEP about sampling?

**Comment by joe-elliott** [comment]
Since this is just a proxy does it make sense to configure and handle this entirely in the receiver?

If we can agree on how to handle this we could be glad to add the feature.

**Comment by bogdandrutu** [comment]
We discussed about the collector integration to use extensions.

**Comment by annanay25** [comment]
I will pick this up.

**Comment by rghetia** [comment]
move to collector repo

**Comment by jmacd** [comment]
I suspect there is a desire to apply sampling in the client-side SDK, in which case this issue belongs here.

**Comment by annanay25** [comment]
Yes, once jaeger remote sampling is implemented in the agent/collector, we can pick up the client side SDK sampling.
