### ISSUE TITLE
Add Instrumentation Scope and Version as info metric and label in Prometheus exporter

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#3273]
Based on https://github.com/open-telemetry/opentelemetry-specification/pull/2703

> Prometheus exporters SHOULD generate an [Info](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#info)-typed
> metric named `otel_scope_info`. If present, Instrumentation Scope
> `name` and `version` MUST be added as `otel_scope_name` and
> `otel_scope_version` labels. Scope attributes MUST also be added as labels
> following the rules described in the [`Metric Attributes`](#metric-attributes)
> section below.
> 
> Prometheus exporters MUST add the scope name as the `otel_scope_name` label and
> the scope version as the `otel_scope_version` label on all metric points by
> default.
> 
> Prometheus exporters SHOULD provide a configuration option to disable the
> `otel_scope_info` metric and `otel_scope_` labels.

**Comment by fatsheep9146** [comment]
@MrAlias @Aneurysm9  Could I take this issue?
