### ISSUE TITLE
Generate the v1.14 version of the semconv package

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#3276]
The v1.14 version of the specification has been released. A new v1.14 version of semconv needs to be generated for this.

Blocked by https://github.com/open-telemetry/opentelemetry-go/issues/3191 which is working to add new HTTP semantic convention functionality due to upstream breaking changes.

**Comment by MrAlias** [comment]
```terminal
$ make semconv-generate
[ "v1.14.0" ] || ( echo "TAG unset: missing opentelemetry specification tag"; exit 1 )
[ "/home/tyler/code/opentelemetry-specification" ] || ( echo "OTEL_SPEC_REPO unset: missing path to opentelemetry specification repo"; exit 1 )
/home/tyler/go/src/go.opentelemetry.io/otel/.tools/semconvgen -i "/home/tyler/code/opentelemetry-specification/semantic_conventions/trace" -t ""semconv/"/template.j2" -s "v1.14.0"
panic: unable to render template: exit status 1
Traceback (most recent call last):
  File "/usr/local/bin/gen-semconv", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/opentelemetry/semconv/main.py", line 67, in main
    semconv = parse_semconv(args, parser)
  File "/usr/local/lib/python3.8/site-packages/opentelemetry/semconv/main.py", line 38, in parse_semconv
    semconv.finish()
  File "/usr/local/lib/python3.8/site-packages/opentelemetry/semconv/model/semantic_convention.py", line 313, in finish
    fixpoint_ref = self.resolve_ref(semconv)
  File "/usr/local/lib/python3.8/site-packages/opentelemetry/semconv/model/semantic_convention.py", line 454, in resolve_ref
    raise ValidationError.from_yaml_pos(
opentelemetry.semconv.model.exceptions.ValidationError: Semantic Convention trace-exception reference `exception.type` but it cannot be found! - @2:5


goroutine 1 [running]:
main.main()
	/home/tyler/go/pkg/mod/go.opentelemetry.io/build-tools/semconvgen@v0.3.0/generator.go:61 +0x44e
make: *** [Makefile:213: semconv-generate] Error 2
```

Looking into the schema to see if there were changes. Might look into what the collector did here.

**Comment by MrAlias** [comment]
> ```
> $ make semconv-generate
> [ "v1.14.0" ] || ( echo "TAG unset: missing opentelemetry specification tag"; exit 1 )
> [ "/home/tyler/code/opentelemetry-specification" ] || ( echo "OTEL_SPEC_REPO unset: missing path to opentelemetry specification repo"; exit 1 )
> /home/tyler/go/src/go.opentelemetry.io/otel/.tools/semconvgen -i "/home/tyler/code/opentelemetry-specification/semantic_conventions/trace" -t ""semconv/"/template.j2" -s "v1.14.0"
> panic: unable to render template: exit status 1
> Traceback (most recent call last):
>   File "/usr/local/bin/gen-semconv", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.8/site-packages/opentelemetry/semconv/main.py", line 67, in main
>     semconv = parse_semconv(args, parser)
>   File "/usr/local/lib/python3.8/site-packages/opentelemetry/semconv/main.py", line 38, in parse_semconv
>     semconv.finish()
>   File "/usr/local/lib/python3.8/site-packages/opentelemetry/semconv/model/semantic_convention.py", line 313, in finish
>     fixpoint_ref = self.resolve_ref(semconv)
>   File "/usr/local/lib/python3.8/site-packages/opentelemetry/semconv/model/semantic_convention.py", line 454, in resolve_ref
>     raise ValidationError.from_yaml_pos(
> opentelemetry.semconv.model.exceptions.ValidationError: Semantic Convention trace-exception reference `exception.type` but it cannot be found! - @2:5
> 
> 
> goroutine 1 [running]:
> main.main()
> 	/home/tyler/go/pkg/mod/go.opentelemetry.io/build-tools/semconvgen@v0.3.0/generator.go:61 +0x44e
> make: *** [Makefile:213: semconv-generate] Error 2
> ```
> 
> Looking into the schema to see if there were changes. Might look into what the collector did here.

https://github.com/open-telemetry/opentelemetry-collector/pull/6713#pullrequestreview-1231800211

**Comment by Aneurysm9** [comment]
Yup, looks like the same issue.  https://github.com/open-telemetry/opentelemetry-go-build-tools/pull/217 should unblock this by allowing us to point at the root of the spec conventions but request output of specific types.
