### ISSUE TITLE
Prometheus exporter does not cumulatively sum histogram buckets

### ISSUE THREAD

**Issue by albertlockett** [open-telemetry/opentelemetry-go#3281]
### Description

Using the otel-go sdk to collect metrics with prometheus exporter does report the values in the bucket as a cumulative sum of the value for this bucket and the buckets of lower values.

If I do this:
```
	histogram, _ := meter.SyncInt64().Histogram("my-histogram")
	histogram.Record(ctx, 95)
	histogram.Record(ctx, 95)
	histogram.Record(ctx, 95)
	histogram.Record(ctx, 245)
	histogram.Record(ctx, 245)
	histogram.Record(ctx, 495)
```
	
I get an output like this:
```
$ curl -XGET http://localhost:2222/metrics                                     
...
my_histogram_bucket{le="100"} 3
my_histogram_bucket{le="250"} 2
my_histogram_bucket{le="500"} 1
my_histogram_bucket{le="1000"} 0
...
my_histogram_bucket{le="+Inf"} 6
```

### Environment

- OS: osx
- Architecture: intel
- Go Version: 1.19
- opentelemetry-go version: 

### Steps To Reproduce

here's a project that will reproduce
https://github.com/albertlockett/otel-go-metrics-test01/blob/main/go.mod

### Expected behavior

I was expecting an output like this (this is the behaviour I get from opentelemetry-js)
```
my_histogram_bucket{le="100"} 3
my_histogram_bucket{le="250"} 5
my_histogram_bucket{le="500"} 6
my_histogram_bucket{le="1000"} 6
my_histogram_bucket{le="+Inf"} 6
```

**Comment by albertlockett** [comment]
https://github.com/open-telemetry/opentelemetry-go/pull/3282

**Comment by dangermike** [comment]
I have seen the same behavior, including with the provided example code from [/example/prometheus/main.go](https://github.com/open-telemetry/opentelemetry-go/blob/84e28fd3bdb10b11a15be895f2eda56f2c341384/example/prometheus/main.go).

Thanks, @albertlockett!
