### ISSUE TITLE
End() with panic should SetStatus(Error)

### ISSUE THREAD

**Issue by aep** [open-telemetry/opentelemetry-go#3283]
span.End() does recover

https://github.com/open-telemetry/opentelemetry-go/blob/84e28fd3bdb10b11a15be895f2eda56f2c341384/sdk/trace/span.go#L381

and it does set an exception event, but it doesn't set the span status to error.

this seems, wrong?

**Comment by NewReStarter** [comment]
It seems to be the expected behavior. check below api specification 
* [End](https://opentelemetry.io/docs/reference/specification/trace/api/#end)
* [Semantic Conventions for Exceptions](https://opentelemetry.io/docs/reference/specification/trace/semantic_conventions/exceptions/)
``` java
Span span = myTracer.startSpan(/*...*/);
try {
  // Code that does the actual work which the Span represents
} catch (Throwable e) {
  span.recordException(e, Attributes.of("exception.escaped", true));
  throw e;
} finally {
  span.end();
}
```
`exception` should be `panic` in your case.

`span.End()` should only 
> Signals that the operation described by this span has now (or at the time optionally specified) ended.

You may consider set it explicitly with `span.SetStatus()`

**Comment by aep** [comment]
confusingly the golang package doesn't behave that way tho.
it _does_ catch the exception internally in End

**Comment by dmathieu** [comment]
It catches it, but also rethrows it: https://github.com/open-telemetry/opentelemetry-go/blob/84e28fd3bdb10b11a15be895f2eda56f2c341384/sdk/trace/span.go#L383

**Comment by aep** [comment]
right. according to the spec you quoted, this must be done by the user (before span.end) 
so i opened a PR in otelchi to do that.

not entirely sure if the behaviour in otel-go is ok, because in this case it did lead exactly to the situation where the library user (otelchi) was assuming otel-go handles the panic correctly.

**Comment by NewReStarter** [comment]
other language sdk(c++/python) also behave this way, so I guess it's expected behavior.

**Comment by aep** [comment]
allright, thank you.
closing this because it needs to be solved in otelchi
