### ISSUE TITLE
Remove AddLink from Span interface

### ISSUE THREAD

**Issue by paivagustavo** [open-telemetry/opentelemetry-go#329]
From the [specs](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-tracing.md#add-links), `AddLink` only exist during the creation of Span.

**Comment by VineethReddy02** [comment]
I will work on this! So the change involves removing ```AddLink``` from span interface right?

**Comment by paivagustavo** [comment]
Hey @VineethReddy02, thanks for picking this up! 

Yes, just remove it from the interface and also from its implementations (sdk `span`, `noop_span` and `mock_span`).  We should also remove the `Link` method, just realized this now.

The only thing that must be kept is the `addLink` (unexported method) of the sdk span, that should be  used during the span creation (`tracer.Start()`) when we have a  `trace.LinkedTo()` option.

**Comment by VineethReddy02** [comment]
I also see ```go.opentelemetry.io/otel/sdk/tracesdk/trace/tracer.go:62:7: span.AddLink undefined```
So what exactly should I do at the places we are using ```AddLink``?

**Comment by paivagustavo** [comment]
@VineethReddy02 that should be using the unexported `addLink`. But that rest should be removed.

**Comment by paivagustavo** [comment]
Close with #349.
