### ISSUE TITLE
go mod tidy failing with package not found errors

### ISSUE THREAD

**Issue by laxmikantbpandhare** [open-telemetry/opentelemetry-go#3292]
### Description

I am facing import issues like below. Is there any workaround for this?

```
go.opentelemetry.io/otel/semconv: module go.opentelemetry.io/otel@latest found (v1.11.0), but does not contain package go.opentelemetry.io/otel/semconv

go.opentelemetry.io/otel/metric/registry: module go.opentelemetry.io/otel/metric@latest found (v0.32.3), but does not contain package go.opentelemetry.io/otel/metric/registry
```

### Environment

- Architecture: [e.g. x86, i386]
- Go Version: [e.g. 1.19]
- opentelemetry-go version: [e.g. v0.23.0,]

### Steps To Reproduce

go mod tidy on the project

### Expected behavior

it will run successfully

**Comment by laxmikantbpandhare** [comment]
Imports that I have

```
	go.opentelemetry.io/contrib v0.20.0 // indirect
	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.20.0 // indirect
	go.opentelemetry.io/otel v1.11.0 // indirect
	go.opentelemetry.io/otel/exporters/otlp v0.20.0 // indirect
	go.opentelemetry.io/otel/metric v0.20.0 // indirect
	go.opentelemetry.io/otel/sdk v1.11.0 // indirect
	go.opentelemetry.io/otel/sdk/export/metric v0.20.0 // indirect
	go.opentelemetry.io/otel/trace v1.11.0 // indirect
	go.opentelemetry.io/proto/otlp v0.19.0 // indirect
```

**Comment by MrAlias** [comment]
`go.opentelemetry.io/otel/sdk/export/metric` and `go.opentelemetry.io/otel/metric/registry` no longer exist. You will need to updated your code to not depend on them.

**Comment by laxmikantbpandhare** [comment]
@MrAlias ok! Any idea about other import

```
go.opentelemetry.io/otel/semconv: module go.opentelemetry.io/otel@latest found (v1.11.0), but does not contain package go.opentelemetry.io/otel/semconv
```

Is the above also got deprecated?

**Comment by MrAlias** [comment]
> @MrAlias ok! Any idea about other import
> 
> ```
> go.opentelemetry.io/otel/semconv: module go.opentelemetry.io/otel@latest found (v1.11.0), but does not contain package go.opentelemetry.io/otel/semconv
> ```
> 
> Is the above also got deprecated?

Sort of. That package structure changed prior to the stable v1 release.

```go
import (
	semconv "go.opentelemetry.io/otel/semconv/v1.12.0"
)
```

That should resolve the dependency.

**Comment by laxmikantbpandhare** [comment]
Oh! got it. I am closing this issue as this has nothing to do with any bugs in the project. @MrAlias - thank you for helping out.
