### ISSUE TITLE
Metrics SDK default label encoding not unique

### ISSUE THREAD

**Issue by lzchen** [open-telemetry/opentelemetry-go#332]
Looking at the current implementation of the [default label encoder](https://github.com/open-telemetry/opentelemetry-go/blob/master/sdk/metric/labelencoder.go#L48), will this produce unique encodings with `get_label_set({"foo=bar": "baz"})` and `get_label_set({"foo": "bar=baz"})`? Are we restricting users from have '=' in their labelkeys/values? Sorry if I am misunderstanding as my Go is not as strong :).

**Comment by jmacd** [comment]
This is a legitimate issue. I'll add this to the list of things that need to be cleared up.

**Comment by jmacd** [comment]
I think we should restrict keys not to contain certain characters, yes, but some kind of escaping will still be needed. On that topic, there are still open questions about whether unspecified values need to be treated differently from empty-string values, which will touch on the same issue.

**Comment by jmacd** [comment]
Note https://github.com/DataDog/datadog-go/issues/83
