### ISSUE TITLE
Issues or mis-use of histogram metrics

### ISSUE THREAD

**Issue by xcheng85** [open-telemetry/opentelemetry-go#3344]
I created a custom histogram bucket: 

ExplicitBucketHistogram{
			Boundaries: []float64{0.5, 1, 2.5, 5, 10, 20, 40, 60, 80, 120, 160, 240, 320, 480, 640},
		}),
and then I add a histogram metric data point: 200

I am expecting to see 5 buckets to have counter: 1 but only 2 buckets instead. Could you please help ? 

unity_event_1_bucket{namespace="evd-cia3dviz",le="240"} 1
unity_event_1_bucket{namespace="evd-cia3dviz",le="320"} 0
unity_event_1_bucket{namespace="evd-cia3dviz",le="480"} 0
unity_event_1_bucket{namespace="evd-cia3dviz",le="640"} 0
unity_event_1_bucket{namespace="evd-cia3dviz",le="+Inf"} 1

version: 

	go.opentelemetry.io/otel v1.10.0
	go.opentelemetry.io/otel/metric v0.32.1
	go.opentelemetry.io/otel/sdk v1.10.0
	go.opentelemetry.io/otel/sdk/metric v0.32.1

   	go.opentelemetry.io/otel/exporters/prometheus v0.32.1

**Comment by MrAlias** [comment]
> Thank you. Would you please inform the schedule of next release ?

We don't currently have a date, but you can track its progress here: https://github.com/open-telemetry/opentelemetry-go/milestone/31
