### ISSUE TITLE
Add support for instrumentation scope attributes during meter/tracer/logger creation

### ISSUE THREAD

**Issue by paivagustavo** [open-telemetry/opentelemetry-go#3368]
### Problem Statement

Currently, there is no way to define instrumentation scope attributes when creating a tracer/meter as specified in https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#get-a-meter

### Proposed Solution

Add back instrumentation scope attributes.

#### Prior Art

This was already implemented by https://github.com/open-telemetry/opentelemetry-go/pull/3132 but it was reverted because specs was not ready yet (https://github.com/open-telemetry/opentelemetry-go/pull/3154).

**Comment by MrAlias** [comment]
Similar to https://github.com/open-telemetry/opentelemetry-go/issues/3140, this cannot be added until we have a clear specification for how to export these values. Specifically how conflicts are resolved given these attributes are not identifying.

**Comment by MrAlias** [comment]
Both #3739 and #3738 add options to the trace and metric API to set the instrumentation scope attributes. The SDKs in both situation do not do anything with this information.

**Comment by pellared** [comment]
I think that
1. we should set add `Attributes` to [`instrumentation.Scope`]
2. the API should be able to set these using `WithAttributes` options when calling `Tracer` or Meter` 
3. the OTLP exporter should honor these values and pass it via https://github.com/open-telemetry/opentelemetry-proto/blob/b5c1a7882180a26bb7794594e8546798ecb68103/opentelemetry/proto/common/v1/common.proto#L76-L79

@MrAlias Do you still see these as being blocked by the specification? Is there any existing issue on the specification or do you have some recommendation on how to proceed (e.g. where we should define such information)?

**Comment by MrAlias** [comment]
@pellared how will we distinguish between instruments scopes if attributes are added. They are a non-identifying field, they cannot be used in comparisons.

How will we resolve duplicate instrument scopes being passed with different attributes. The specification does not say how this is to be resolved. If we make a decision here it will be unspecified and likely to conflict with what the specification ultimately decides.

**Comment by pellared** [comment]
> @pellared how will we distinguish between instruments scopes if attributes are added. They are a non-identifying field, they cannot be used in comparisons.

From spec

> Tracers are identified by name, version, and schema_url fields. When more than one Tracer of the same name, version, and schema_url is created, it is unspecified whether or under which conditions the same or different Tracer instances are returned. It is a user error to create Tracers with different attributes but the same identity.

> Meters are identified by name, version, and schema_url fields. When more than one Meter of the same name, version, and schema_url is created, it is unspecified whether or under which conditions the same or different Meter instances are returned. It is a user error to create Meters with different attributes but the same identity.

> Loggers are identified by name, version, and schema_url fields. When more than one Logger of the same name, version, and schema_url is created, it is unspecified whether or under which conditions the same or different Logger instances are returned. It is a user error to create Loggers with different attributes but the same identity.
 
> How will we resolve duplicate instrument scopes being passed with different attributes. The specification does not say how this is to be resolved. If we make a decision here it will be unspecified and likely to conflict with what the specification ultimately decides.

I think we could simply create a type which is like `instrumentation.Scope` but without Attributes and use it in maps.

> How will we resolve duplicate instrument scopes being passed with different attributes. The specification does not say how this is to be resolved. If we make a decision here it will be unspecified and likely to conflict with what the specification ultimately decides.

Trying to solve this here: https://github.com/open-telemetry/opentelemetry-specification/pull/3855

**Comment by MrAlias** [comment]
> > How will we resolve duplicate instrument scopes being passed with different attributes. The specification does not say how this is to be resolved. If we make a decision here it will be unspecified and likely to conflict with what the specification ultimately decides.
> 
> Trying to solve this here: [open-telemetry/opentelemetry-specification#3855](https://github.com/open-telemetry/opentelemetry-specification/pull/3855)

How does that resolve the questions quoted? It is adjusting definitions to include logs in instrumentation scope references. The questions already exist for all signal types that use instrument scope.

**Comment by pellared** [comment]
> How does that resolve the questions quoted? It is adjusting definitions to include logs in instrumentation scope references. The questions already exist for all signal types that use instrument scope.

Sorry, my PR was only about how to solve attribute with duplicate keys 🤦 


>  When more than one Tracer of the same name, version, and schema_url is created, it is unspecified whether or under which conditions the same or different Tracer instances are returned

Therefore, I think we should do exactly the same as we do right now when the tracer/logger that have "the same IDs" (return the existing tracer that we have in the map).

**Comment by MrAlias** [comment]
> Therefore, I think we should do exactly the same as we do right now when the tracer/logger that have "the same IDs" (return the existing tracer that we have in the map).

So drop the second set of attributes. Again, I go back to the lack of definition in the specification. That behavior is not defined there. There are "TODO"s in the spec to define the behavior, but there is not stable specification defining it.

I do not support implementing a behavior in our implementation that specifically called out in the specification as something they will decide in the future. Especially since it may ultimately be a different behavior. The last time this was brought up in the SIG meeting this was the SIG consensus as well.

**Comment by pellared** [comment]
Thanks. I will try to refine the specification as part of my work for OTel Go Logs.

**Comment by pellared** [comment]
> Thanks. I will try to refine the specification as part of my work for OTel Go Logs.

I started by creating https://github.com/open-telemetry/opentelemetry-specification/pull/4146

**Comment by pellared** [comment]
https://github.com/open-telemetry/opentelemetry-specification/issues/4160 is merged.
Unblocked from the specification perspective. I will start working on it.

**Comment by pellared** [comment]
I created follow-up issues:
- https://github.com/open-telemetry/opentelemetry-go/issues/5844
- https://github.com/open-telemetry/opentelemetry-go/issues/5845
- https://github.com/open-telemetry/opentelemetry-go/issues/5846
