### ISSUE TITLE
Verify compliant metric API specification implementation: Instrument Asynchronous UpDownCounter

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#3379]
- [x] Identify all the normative requirements, recommendations, and options [the specification] defines as comments to this issue
- [ ] Ensure the [current metric API implementation] is compliant with these normative requirements, recommendations, and options in those comments.

[the specification]: https://github.com/open-telemetry/opentelemetry-specification/blob/v1.14.0/specification/metrics/api.md#asynchronous-updowncounter
[current metric API implementation]: https://github.com/open-telemetry/opentelemetry-go/tree/v1.11.1/metric

**Comment by jmacd** [comment]
See the discussion in https://github.com/open-telemetry/opentelemetry-go/issues/3278.

I'm concerned that the fix in https://github.com/open-telemetry/opentelemetry-go/pull/3350 will break when filters are applied. In the comment here (https://github.com/open-telemetry/opentelemetry-go/issues/3278#issuecomment-1281108795), there is a suggestion not to `set()` the aggregator to the last value, but to initialize the output aggregator to zero and then `add()` the result from each instrument. That way when filters are applied, you get the sum not the last value. 

I picked up on this because https://github.com/open-telemetry/opentelemetry-go/pull/3350#pullrequestreview-1147935775 should not be true -- that is counters should not be behaving exactly like gauges.

**Comment by MrAlias** [comment]
> See the discussion in #3278.
> 
> I'm concerned that the fix in #3350 will break when filters are applied. In the comment here ([#3278 (comment)](https://github.com/open-telemetry/opentelemetry-go/issues/3278#issuecomment-1281108795)), there is a suggestion not to `set()` the aggregator to the last value, but to initialize the output aggregator to zero and then `add()` the result from each attribute set. That way when filters are applied, you get the sum not the last value.
> 
> I picked up on this because [#3350 (review)](https://github.com/open-telemetry/opentelemetry-go/pull/3350#pullrequestreview-1147935775) should not be true -- that is counters should not be behaving exactly like gauges.

This issues is about the compliance of the metric API, `go.opentelemetry.io/ote/metric`. This comment seems to be about the compliance of the SDK. Is there more to it? Is this meant to say our API implementation needs to be addressed?

**Comment by jmacd** [comment]
Sorry, I thought this was about end-to-end compliance testing. I'm not sure whether a new issue is needed for the comment in https://github.com/open-telemetry/opentelemetry-go/issues/3379#issuecomment-1290899787, seems to fall in with #3278.

**Comment by MrAlias** [comment]
https://github.com/open-telemetry/opentelemetry-go/issues/3453

**Comment by MrAlias** [comment]
> There MUST NOT be any API for creating an Asynchronous UpDownCounter other than with a `Meter`.

With #3454 now complete, our implementation is compliant.

**Comment by MrAlias** [comment]
> This MAY be called `CreateObservableUpDownCounter`. If strong type is desired, OpenTelemetry API authors MAY decide the language idiomatic name(s), for example `CreateUInt64ObservableUpDownCounter`, `CreateDoubleObservableUpDownCounter`, `CreateObservableUpDownCounter<UInt64>`, `CreateObservableUpDownCounter<double>`.

We do not follow this optional criteria. We instead follow more common Go method naming and use `Int64ObservableUpDownCounter` and `Float64ObservableUpDownCounter` method names.

**Comment by MrAlias** [comment]
> It is highly recommended that implementations use the name `ObservableUpDownCounter` (or any language idiomatic variation, e.g. `observable_updowncounter`) unless there is a strong reason not to do so.

I'm going to assume the authors intended "recommended" to be the normative key word "RECOMMENDED".

We do not follow this recommendation. #3453 is tracking this issue, and #3575 should address this.

**Comment by MrAlias** [comment]
> For callback functions registered after an asynchronous instrument is created, the API is required to support a mechanism for unregistration.

I'm going to assume the authors intended "recommended" to be the normative key word "RECOMMENDED".

We are compliant with this, as explained here: https://github.com/open-telemetry/opentelemetry-go/issues/3373#issuecomment-1371558340

**Comment by MrAlias** [comment]
Remaining:

- [ ] #3453

**Comment by MrAlias** [comment]
Every normative clause from the `Asynchronous UpDownCounter` section of the v1.16.0 specification has been identified and our API has been validated that it complies. Closing.
