### ISSUE TITLE
Make test target failing with race conditions

### ISSUE THREAD

**Issue by elsesiy** [open-telemetry/opentelemetry-go#339]
As mentioned in #306 running `make test` fails with some data races.as 
I attached the log output and here's what I did:
1. Clone repo
2. `make precommit`
3. `make test`

I also had to modify the shebang as proposed in https://github.com/open-telemetry/opentelemetry-go/pull/336.

Env info:
`go version go1.13.4 darwin/amd64`

[make_test_output.txt](https://github.com/open-telemetry/opentelemetry-go/files/3877023/make_test_output.txt)

**Comment by iredelmeier** [comment]
@elsesiy do you want to pick this up as part of your work for #306 or do you want someone else to? At a glance, it looks like the problem is that the `testExporter` (and maybe some other metrics test types) is missing a lock.

**Comment by jmacd** [comment]
I'll take this one.

**Comment by jmacd** [comment]
I'm confused because when I run `go test -race` directly on this test, it fails for me. But when I run `make precommit` it does not fail for me locally w/ the same code. Is this flakiness?

**Comment by jmacd** [comment]
It looks like the test should wrap a mutex around its `records` field. I hadn't written the mutex because in the real SDK export is called in a single threaded context, but it's not in this test.

**Comment by jmacd** [comment]
Also, I've determined why this hasn't failed very often, since it fails reliably for me on my machine. (1) I wasn't running the `make test` rule, I _thought_ `make precommit` would do that for me. (2) the CircleCI machine has very limited concurrency, as opposed to my machine.

**Comment by elsesiy** [comment]
@jmacd I noticed that too but after digging through the targets I found that race detection is only done on `make test`. Thanks for the update!

**Comment by jmacd** [comment]
We added race detection to the CI tests. Thanks for finding this. :)
