### ISSUE TITLE
Make SpanContext and related types de-serializable

### ISSUE THREAD

**Issue by marwan-at-work** [open-telemetry/opentelemetry-go#3393]
### Description

The SpanContext and its sub types (TraceID, SpanID, etc) have MarshalJSON methods, but do not have UnmarshalJSON methods. 

It makes for a broken experience because you can use the encoding/json library to marshal a type, but suddenly you cannot un-marshal back into the Go type anymore. 

### Steps To Reproduce

1. Create a SpanContext or a TraceID
2. Use encoding/json to marshal it
3. Try unmarshaling it back to the original type

### Expected behavior

It should be deserialized properly.

**Comment by Aneurysm9** [comment]
These types can be marshalled to JSON to support the STDOUT exporter for debugging purposes and are not intended to be used to round-trip data.  If you need to communicate a `SpanContext` to a remote process utilizing the OTel Go SDK (or any other OTel SDK, for that matter) then the Propagation API is the way to do so.
