### ISSUE TITLE
Clearing the trace from a duplicated context

### ISSUE THREAD

**Issue by NickOttrando** [open-telemetry/opentelemetry-go#3410]
Hi, I'm running a web application in gin and want to have one trace for the main request, and then separate traces for any goroutines that are ran.

Before running my goroutine I'm copying the main thread's ctx using Gin's [copy function](https://pkg.go.dev/github.com/gin-gonic/gin#Context.Copy), and then I try to get a span for the new context, but I believe it still has the same trace as the main thread's.

Code sample:

```go
ac := ctx.Copy()
newCtx, span := otel.Tracer(constant.OpenTelemetryService).Start(ctx.Request.Context(), spanName)
ctx.Request = ctx.Request.Clone(newCtx)
```

Printing out the spans below, you can see both ctx and ac have the same trace.

> ctx span: 
> &{mu:{state:0 sema:0} parent:{traceID:[105 215 66 60 229 193 68 182 184 80 134 176 153 174 84 192] spanID:[92 56 221 55 129 1 25 111] traceFlags:1 traceState:{list:[]} remote:false} spanKind:1 name:/internal/util.RedisGetValue startTime:{wall:13893386900716079992 ext:7038990364 loc:0x38733c0} endTime:{wall:13893386900759378035 ext:7082288407 loc:0x38733c0} status:{Code:0 Description:} childSpanCount:0 spanContext:{traceID:[105 215 66 60 229 193 68 182 184 80 134 176 153 174 84 192] spanID:[105 82 255 8 19 14 216 193] traceFlags:1 traceState:{list:[]} remote:false} attributes:[{Key:Xid Value:{vtype:4 numeric:0 stringly:3830696f-da70-4e78-b0cf-3bd5e5efca63 slice:<nil>}}] droppedAttributes:0 events:{queue:[] capacity:128 droppedCount:0} links:{queue:[] capacity:128 droppedCount:0} executionTracerTaskEnd:<nil> tracer:0xc0005b67c0}
> 
> ac span: 
> &{mu:{state:0 sema:0} parent:{traceID:[105 215 66 60 229 193 68 182 184 80 134 176 153 174 84 192] spanID:[105 82 255 8 19 14 216 193] traceFlags:1 traceState:{list:[]} remote:false} spanKind:1 name:/internal/async.Enqueue startTime:{wall:13893386900759546992 ext:7082456437 loc:0x38733c0} endTime:{wall:0 ext:0 loc:<nil>} status:{Code:0 Description:} childSpanCount:0 spanContext:{traceID:[105 215 66 60 229 193 68 182 184 80 134 176 153 174 84 192] spanID:[83 211 198 112 112 196 215 24] traceFlags:1 traceState:{list:[]} remote:false} attributes:[{Key:Xid Value:{vtype:4 numeric:0 stringly:3830696f-da70-4e78-b0cf-3bd5e5efca63 slice:<nil>}}] droppedAttributes:0 events:{queue:[] capacity:128 droppedCount:0} links:{queue:[] capacity:128 droppedCount:0} executionTracerTaskEnd:<nil> tracer:0xc0005b67c0}

What do I need to do to ensure they are different after I copy a gin context?

**Comment by MrAlias** [comment]
The spans you printed are different, they have different span IDs. They belong to the same trace, is that the issue you are having? This is an intentional relationship of a tracing system. You can read more about this in the OTel docs: https://opentelemetry.io/docs/concepts/observability-primer/#distributed-traces

If you would like to define a new trace you will need to use a context that does not inherit from a context that is already tracing. Trace context is explicitly passed in this implementation of OTel and this is expected behavior.

**Comment by NickOttrando** [comment]
> The spans you printed are different, they have different span IDs. They belong to the same trace, is that the issue you are having? 
> 
> If you would like to define a new trace you will need to use a context that does not inherit from a context that is already tracing. Trace context is explicitly passed in this implementation of OTel and this is expected behavior.

Hi there, yes I would basically like to clone the request context which already has a trace associated with it, but remove that trace so I can instantiate another one for the separate go-routine. Is there no way to do that?

**Comment by NickOttrando** [comment]
> If I understood your problem correctly, it seems that you should use the [WithNewRoot](https://pkg.go.dev/go.opentelemetry.io/otel/trace#WithNewRoot) function when starting a span.
> 
> Something like that:
> 
> ```go
> newCtx, span := otel.Tracer(constant.OpenTelemetryService).Start(ctx.Request.Context(), spanName, trace.WithNewRoot()) 
> ```

Hi @maksim77, this does look like it will do exactly what I want. Will try it out and close the issue if it works, thanks!
