### ISSUE TITLE
Add simplified constructor for simple metric SDK setup: stdout exporter.

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-go#343]
It takes about 15 lines of code to setup an exporter. This is because the complete export pipeline has a number of various configurations possible, but it confuses most users who do not care to change the standard configuration.

Each exporter should provide a simple method to set it up using a recommended setup. For example, the stdout exporter should by default (IMO) use: the inexpensive measure option, the ungrouped batcher (stateful), and a push controller, e.g., the code snippet below.

```
	selector := simple.NewWithInexpensiveMeasure()
	exporter, err := metricstdout.New(options)
	if err != nil {
		return nil
	}
	batcher := ungrouped.New(selector, metricsdk.NewDefaultLabelEncoder(), true)
	pusher := push.New(batcher, exporter, time.Second)
	pusher.Start()
         return pusher
```

**Comment by iredelmeier** [comment]
Assigned to @matej-g (can't currently pick in the assignees list)

**Comment by matej-g** [comment]
@iredelmeier yes, thank you, I'll be glad to have a take this!

**Comment by matej-g** [comment]
So I have been looking at this task and reading through spec / documentation,
but I guess I have still some questions, as a newcomer I want to make sure I understand:

- The terminology is not entirely clear to me - the issues description speaks of setting up an exporter, although it seems like exporter is actually one of the stages in the pipeline which we want to construct. Should I understand the task as setting up the whole exporter pipeline (i.e. aggregation selector, batcher, exporter and controller), in this case with default, recommended configuration? Is this process synonymous with setting up an exporter?

- From the point of the code organization, I'm not sure where would these recommended pipeline setups fit the best; should they be included in a new package under `/otel/sdk/metric/`?

**Comment by jmacd** [comment]
> Should I understand the task as setting up the whole exporter pipeline

Yes, that was the intent of this issue. We want to simplify the default setup.

I would put this in the stdout directory, so the signature might be:

```
func NewExportPipeline(config Config) (metric.Provider, io.Closer)
```

and to install one of these:
```
   provider, closer := stdout.NewExportPipeline(...)
   defer closer.Close()
   global.SetMeterProvider(provider)
```

(Note: I invented the name `Config` above. It's actually named `Options`, but there's a growing consensus in this code base to use `Config` for the name of a config struct and `Option` as the name of the functional option type. I would like to rename this `Options` type to `Config`.)

**Comment by matej-g** [comment]
@jmacd Thank you for the guidance, I tried my hand at a solution in https://github.com/open-telemetry/opentelemetry-go/pull/395
