### ISSUE TITLE
Align Async Counter behavior when used with filtered attributes.

### ISSUE THREAD

**Issue by MadVikingGod** [open-telemetry/opentelemetry-go#3439]
### Problem Statement

If an attribute filter is used with an Async Counter the last value observed will be exported. This

```go
// When there is an Attribute Filter that only allows "foo" attributes.
 
ctr, _ := meter.AsyncInt64().Counter("testCounter")
...
ctr.Observe(ctx, 4, attribute.Int("Version", 1))
ctr.Observe(ctx, 5, attribute.Int("Version", 2))
```
Yields a Sum with a value of 5.

This has been discussed in the spec, and the expected output is a Sum with a value of 9.
https://github.com/open-telemetry/opentelemetry-specification/issues/2905

### Proposed Solution

Correct our instruments, filters, or aggregators to get the appropriate value.

**Comment by wisdommatt** [comment]
@MadVikingGod , @MrAlias I would like to work on this

**Comment by MrAlias** [comment]
@wisdommatt please outline the design approach you plan to take here. This is likely not going to be obvious to resolve and having consensus on the approach will likely help prevent wasting work.

**Comment by wisdommatt** [comment]
@MrAlias sure, will look at the otel spec issue https://github.com/open-telemetry/opentelemetry-specification/issues/2905, then share my feedback/design approach.
