### ISSUE TITLE
Add simplified constructor for simple metric SDK setup: prometheus exporter

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-go#345]
Ensure that the Prometheus exporter has a simple method for installing the SDK. This exporter will have to integrate a controller and depends on the defaultkeys batcher, so it should be fairly straightforward.

**Comment by VineethReddy02** [comment]
I can take this up. Can I know what exactly needs to be done here?

**Comment by jmacd** [comment]
This issue is similar to but different than #343 and #344 -- I forgot to put the link to #343 which has an explanation. I am concerned that the Prometheus exporter, which is being refactored under #370, may change enough that this work should be postponed until that issue is addressed.

**Comment by jmacd** [comment]
@paivagustavo Note.

**Comment by jmacd** [comment]
This was done.
