### ISSUE TITLE
Asynchronous Instrument API non-compliant with OTel Specification: callbacks cannot be unregistered

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#3452]
The OpenTelemetry specification states:

> The API SHOULD support registration of `callback` functions associated with asynchronous instruments after they are created.
> 
> Where the API supports registration of `callback` functions after asynchronous instrumentation creation, the user MUST be able to undo registration of the specific callback after its registration by some means.

Currently, we allow callbacks to be registered with the `Meter`. We do not support an "un-register" mechanism.

**Comment by MrAlias** [comment]
One proposal is to have the register call return the unregister mechanism:

```go
type Meter interface {
	// ...
	RegisterCallback([]instrument.Asynchronous, func(context.Context)) (Unregisterer, error)
}

type Unregisterer interface {
	Unregister() error
}
```

**Comment by MrAlias** [comment]
Same structure different naming:

```go
type Meter interface {
	// ...
	RegisterCallback([]instrument.Asynchronous, func(context.Context)) (Registration, error)
}

type Registration interface {
	Cancel() error
}
```

This would however go against common Go naming practice of naming the interface after the one method it performs. However, it would allow for the interface to be extended in the future without then having a naming mismatch. Also the return type name would better match what it represents.

**Comment by MrAlias** [comment]
I think we can also update the function signature to better communicate one or more instruments need to be provided and at the same time reduce the boilerplate needed to pass arguments:

```go
type Meter interface {
	// ...
	RegisterCallback(f func(context.Context), instrument instrument.Asynchronous, additional ...instrument.Asynchronous) (Registration, error)
}
```

This was inspired from the Java implementation: https://javadoc.io/doc/io.opentelemetry/opentelemetry-api/latest/io/opentelemetry/api/metrics/Meter.html#batchCallback(java.lang.Runnable,io.opentelemetry.api.metrics.ObservableMeasurement,io.opentelemetry.api.metrics.ObservableMeasurement...)

**Comment by MrAlias** [comment]
> I think we can also update the function signature to better communicate one or more instrument is needed and at the same time reduce the boilerplate needed to pass arguments:
> 
> ```go
> type Meter interface {
> 	// ...
> 	RegisterCallback(f func(context.Context), instrument instrument.Asynchronous, additional ...instrument.Asynchronous) (Registration, error)
> }
> ```
> 
> This was inspired from the Java implementation: https://javadoc.io/doc/io.opentelemetry/opentelemetry-api/latest/io/opentelemetry/api/metrics/Meter.html#batchCallback(java.lang.Runnable,io.opentelemetry.api.metrics.ObservableMeasurement,io.opentelemetry.api.metrics.ObservableMeasurement...)
> 
> This means a call like:
> 
> ```go
> m.RegisterCallback([]instrument.Asynchronous{i1, i2}, cBack)
> ```
> 
> becomes
> 
> ```go
> m.RegisterCallback(cBack, i1, i2)
> ```

This will not work well if you already have a slice of instrument. You cannot just use `...` after the slice to directly pass it.

**Comment by jmacd** [comment]
I remember discussing this once with @MadVikingGod -- one idea we discussed was to admit a second form of callback constructor, one that returns an unregistration handle of some kind, e.g., `NewUnregisterableCallback(func (context.Context)) (Unregister, error)`
