### ISSUE TITLE
Uniform handling of ErrNoData errors from aggregators in the SDK

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-go#346]
The Meter implementation's lock-free implementation always collects a record one final time before "forgetting" it, but this final collection usually comes up with empty data. There is already haphazard support for no-data conditions in the exporters, e.g., the ErrNoLastValue condition and, this TODO in the stdout exporter:
```
            // TODO: Should tolerate ErrEmptyDataSet here,
            // just like ErrNoLastValue below, since
            // there's a race condition between creating
            // the Aggregator and updating the first
            // value.
```
I'd like to add a predicate to the Aggregator interface to test whether an aggregator actually contains no data. This will be called by the Meter impl after it checkpoints the aggregator, and if there's no data, it won't process for export. That will keep a lot of repetition out of the exporters.

There will be subtle cases for the (Min)MaxSumCount aggregator, which since it doesn't take a lock has to check for no-data across four fields. Its predicate would return empty only when all four fields are empty. Thus, the exporters will still have to tolerate a no-data condition, but only the aggregators that can have "partial" no data conditions will need to be careful. I'll think about how I'd like the exporter code to look. It's this pattern I'd like to consolidate somehow:
```
            if value, err := agg.Max(); err != nil {
                if err == ErrNoData {
                    return nil
                }

                return err
            } else {
                // use `value`
            }
```

**Comment by evantorrie** [comment]
@jmacd I took a quick look at this.  If we try to use only the existing aggregator fields to determine whether an Aggregator has valid data, I don't see an obvious way to make it work for `Counter()`.

For instance, suppose we have a non-monotonic `Counter` which we `Update()` with a `+x` and `-x`. Then the check-pointed value would be equal to `core.Number(0)`;  indistinguishable from the uninitialized value for a Counter.

If it's acceptable that a non-monotonic `Counter()` whose current checkpoint value is exactly "0" *not* be exported, then we could get away with just using the uninitialized `core.Number(0)` value as the uninitialized value.  Any thoughts?

**Comment by jmacd** [comment]
Yes, I agree with your reasoning. 

I've thought more about the code I'd like to see here, starting with the change to `ForEach`.  The idea is to improve handling for ErrNoData approximately as follows:

1. Consolidate `ErrNoLastValue` and `ErrEmptyDataSet` into a single `ErrNoData` error in the `sdk/export/metric/aggregator` package. Make it an exported type so that we can use `errors.Is()` to test this type of error.
2. Let `CheckpointSet.ForEach()` and the function argument return `error`.
3. Simplify the exporters to return fast for any kind of error, except for MinMaxSumCount (because it is not atomic).
4. Let ForEach() tolerate two special kinds of error, ErrNoData and ErrNonMonotoneInput, which signify that a single metric export encountered a problem -- the export will continue for these. ErrNoData is treated silently, as this is expected from the Meter implementation. ErrNonMonotoneInput will trigger the SDK's error handling function, since it is unexpected. Any other kind of error will immediately halt `ForEach` and return the error to the caller. 
5. All the Export() functions will be simplified by using the `error` from `ForEach`, instead of the current ad-hoc handling.
6. MinMaxSumCount is the only current special case, and remember it's intended for measure metrics. It's well defined (IMO) to not report a zero sum for a non-monotone counter that is zero. The counter field will cause the metric to report in most cases--actually I think that if we force the count field to update last among the four atomic updates, it will force the MinMaxSumCount to report an implied zero sum along with at least one count, even in a situation where there is no min/max data available due to a race with Checkpoint.

I think that will help us reason about when a batch of metrics could fail completely vs. partially, recognizing that errors fall into expected/known (ErrNoData), unexpected/known (ErrNonMonotoneInput), and unexpected/unknown (fatal) categories.

I'm keen on using the new Go 1.13 error handling support, so like for the implementation of `NewInconsistentMergeError()`, I'd recommend creating a `NewNonMonotoneInputError()` that formats the offending metric name+labels but `errors.Is(..., ErrNonMonotoneInput)` remains true.

**Comment by evantorrie** [comment]
A few things changed since the original report of this issue.  

#557 addressed most of https://github.com/open-telemetry/opentelemetry-go/issues/346#issuecomment-558761379.  With the new `StateLocker` lock-free approach, the problem of inconsistent values in a a multi-valued lock-free aggregate (e.g. `MinMaxSumCount`) is no longer present.

In addition, `ErrNonMonotoneInput` fell into disuse in v0.3, although v0.4 may restore it - see https://github.com/open-telemetry/opentelemetry-specification/issues/465

Shall we consider this issue closed at this point?

**Comment by jmacd** [comment]
Done!!! Thank you.
