### ISSUE TITLE
Can we automatically propagate span attributes to children ?

### ISSUE THREAD

**Issue by eddycharly** [open-telemetry/opentelemetry-go#3473]
I would like child spans to automatically inherit attributes from its parent, is this actually possible ?

It looks like span attributes cannot be read, would it make sense to create a `GetAttributes` method (I'm using golang) so that I can propagate the attributes manually ?

**Comment by Aneurysm9** [comment]
There is no currently specified mechanism for achieving this.  It may be possible using the [`SpanProcessor`](https://pkg.go.dev/go.opentelemetry.io/otel/sdk@v1.11.1/trace#SpanProcessor) interface to build something that might do this, but I'm not aware of any such implementation.

The `Span` API is intentionally write-only, so adding a method to get attributes from a span is not in the cards:

> Spans are not meant to be used to propagate information within a process. To prevent misuse, implementations SHOULD NOT provide access to a Span's attributes besides its SpanContext.

\- [Trace Specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#span)

**Comment by eddycharly** [comment]
Thanks !
Closing, I will look at `SpanProcessor`.

**Comment by jim-minter** [comment]
Take a look at TraceState, which is a field within the SpanContext:

https://github.com/open-telemetry/opentelemetry-go/blob/b2246d58650bc6db04459353843250ee3bba77fc/trace/tracestate.go#L81-L91

You can store up to 32 pieces of information in there and they are propagated to the associated span and all its children.  How the info is output is dependent on the exporter you're using (I'm using a custom exporter and I haven't looked at what the out-of-the-box ones do here).

I found it pretty fiddly to initialize, but something like the following worked for me:

```go
var ts trace.TraceState

if ts, err = ts.Insert(key, value); err != nil {
        return nil, err
}

ctx = trace.ContextWithSpanContext(ctx, trace.NewSpanContext(trace.SpanContextConfig{TraceState: ts}))
```
