### ISSUE TITLE
zipkin exporter support custom  http request headers 

### ISSUE THREAD

**Issue by snailzed** [open-telemetry/opentelemetry-go#3474]
### Problem Statement

file: go.opentelemetry.io/otel/exporters/zipkin/zipkin.go
method:  func (e *Exporter) ExportSpans(ctx context.Context, spans []sdktrace.ReadOnlySpan) error 

Hope to support custom http request headers before sending spans to zipkin server.  If your service can only rely on http request host to implement request forwarding...

### Proposed Solution

support custom http request headers before sending spans to zipkin server.

we may add a func like WithHTTPHead to support this.

eg:

```go 

// Exporter exports spans to the zipkin collector.
type Exporter struct {
	url    string
	client *http.Client
	logger *log.Logger
        httpHead   map[string]string

	stoppedMu sync.RWMutex
	stopped   bool
}

//WithHTTPHead custom http request headers 
func WithHTTPHead(head map[string]string) Option {
   	return optionFunc(func(cfg config) config {
		cfg.httpHead = head
		return cfg
	})
}

```

and then add http head before call ExportSpans method to  send spans to zipkin server.  

code eg:

```go

// ExportSpans exports spans to a Zipkin receiver.
func (e *Exporter) ExportSpans(ctx context.Context, spans []sdktrace.ReadOnlySpan) error {
   ...
   req, err := http.NewRequestWithContext(ctx, http.MethodPost, e.url, bytes.NewBuffer(body))
   if err != nil {
		return e.errf("failed to create request to %s: %v", e.url, err)
   }
   for k, v := range  e.httpHead {
     if k == "host" {
         req.Host = v
      }else{
      	req.Header.Set(k,v) 
    }
   }
  ...
}

```
#### Prior Art

A clear and concise list of any similar and existing solutions from other projects that provide context to possible solutions.

**Comment by dmathieu** [comment]
I would call the method `WithHeaders`, as we do with [the otlp exporter](https://github.com/open-telemetry/opentelemetry-go/blob/main/exporters/otlp/otlptrace/otlptracegrpc/options.go#L108) but outside of that, it seems like a good idea.

**Comment by snailzed** [comment]
> I would call the method `WithHeaders`, as we do with [the otlp exporter](https://github.com/open-telemetry/opentelemetry-go/blob/main/exporters/otlp/otlptrace/otlptracegrpc/options.go#L108) but outside of that, it seems like a good idea.

haha, thank you for your quick reply.  Yeah, `WithHeaders` is better . And [the jaeger exporter](https://github.com/open-telemetry/opentelemetry-go/blob/main/exporters/jaeger/uploader.go#L184) could may also make same change to support custom http request headers. Hope these functions can be implemented soon. Thanks again.

**Comment by srijan-27** [comment]
@dmathieu, @MrAlias - I came across a use case of this in my framework, where we need to set custom headers in zipkin exporter.
Just wanted to know if this is to picked up? Or if not, then why?

**Comment by srijan-27** [comment]
@dmathieu - Thanks for confirmation! Will work on this and create a PR.
Could you assign this to me?
