### ISSUE TITLE
Support `WithAttributes` for default MeterProvider

### ISSUE THREAD

**Issue by austince** [open-telemetry/opentelemetry-go#3494]
### Problem Statement

For adding a static set of attributes to spans, the SpanConfig offers a nice way (along with the `WithAttributes` option builder) to accomplish this.

https://github.com/open-telemetry/opentelemetry-go/blob/7aba25d651015fb89064991cc3982dfacfda8179/trace/config.go#L218-L229

There doesn't seem to be compatible functionality for the Metrics API. The motivation is the same as for spans, where some meters could be given additional information about what is being metered.
Let's say we have two k8s services that our process talks to via `http.Client`s. We want to track the number of requests and have the ability to group by service name. The [conventional attributes](https://opentelemetry.io/docs/reference/specification/metrics/semantic_conventions/http-metrics/#attributes) are too low-level to be able to do this nicely. 

### Proposed Solution

Similar to the `WithAttributes(..)` func for spans, we could add a new [`MeterOption`](https://github.com/open-telemetry/opentelemetry-go/blob/7aba25d651015fb89064991cc3982dfacfda8179/metric/config.go#L34-L37) that accepts a slice of attributes to attach. 

#### Alternatives

Use the `Resource` in the `MeterProvider`. This seems to be a good place for global attributes but not for dynamic local ones. 

#### Prior Art

I can't find any similar examples in the [Java](https://github.com/open-telemetry/opentelemetry-java) or [.NET](https://github.com/open-telemetry/opentelemetry-dotnet/) implementations. 

### Additional Context

Discussed a bit on Slack: https://cloud-native.slack.com/archives/C01NPAXACKT/p1669499929785919

**Comment by Aneurysm9** [comment]
This functionality would need to be defined in the [OpenTelemetry Specification](https://github.com/open-telemetry/opentelemetry-specification) before we could begin any implementation here.

**Comment by Aneurysm9** [comment]
Instrumentation scope attributes _may_ be the thing you're looking for, but there are still unresolved questions in the spec SIG regarding whether they are identifying for instruments produced by a meter bearing them or not.

**Comment by austince** [comment]
Hmm, alright. I've seen those comments elsewhere. Thanks for the pointers, I'll keep up with those discussions 👍🏼
