### ISSUE TITLE
Broken imports in go.opentelemetry.io/otel/exporters/otlp/otlpgrpc dependency

### ISSUE THREAD

**Issue by poorpy** [open-telemetry/opentelemetry-go#3496]
### Description

While trying to download `otlpgrpc` go get bails out with an error. I tried both `v0.20.0` and `v0.19.0`.

### Environment

- OS: Arch Linux
- Architecture: x86_64
- Go Version: go1.19
- opentelemetry-go version: v1.11.1

### Steps To Reproduce

1. cd into existing go project
2. Run `go clean -modcache`
3. Run `go get go.opentelemetry.io/otel/exporters/otlp/otlpgrpc`

### Expected behavior

Module otlpgrpc would finish downloading.

### Full go get output
[v0.19.0.txt](https://github.com/open-telemetry/opentelemetry-go/files/10113160/v0.19.0.txt)
[v0.20.0.txt](https://github.com/open-telemetry/opentelemetry-go/files/10113161/v0.20.0.txt)

**Comment by dmathieu** [comment]
The otlpgrpc package is very old, and has been removed pre v1.x, in favor of [https://github.com/open-telemetry/opentelemetry-go/tree/main/exporters/otlp/otlptrace/otlptracehttp](otlptracehttp). You should be using this package with the stable version.

**Comment by poorpy** [comment]
@dmathieu thanks :D
