### ISSUE TITLE
Exporter: `WithLogger` uses the `github.com/go-logr/logr` interface to replace the standard library logger

### ISSUE THREAD

**Issue by aniaan** [open-telemetry/opentelemetry-go#3497]
### Problem Statement

Currently `otel api` and `sdk` use globalLogger to print logs. globalLogger uses the `github.com/go-logr/logr` library, which provides the interface, and the specific log implementation can be determined by the user, which is designed to be flexible.
https://github.com/open-telemetry/opentelemetry-go/blob/aa868d506b7e4de2f534f47b168b27b7f8824351/internal/global/internal_logging.go#L30-L42

But the Exporter uses golang's standard log library, so the printing of logs in a project will be fragmented, which is not conducive to unified log processing and collection.

https://github.com/open-telemetry/opentelemetry-go/blob/aa868d506b7e4de2f534f47b168b27b7f8824351/exporters/zipkin/zipkin.go#L66-L72

I have a project where my logging library of choice is `zap`. When I use the otel api and sdk, I can use `github.com/go-logr/zapr` to wrap my logger and set the globalLogger, but when I use Exporter, I can't do anything about it, because I can only use golang's standard logging library.

### Proposed Solution

Exporter uses the `github.com/go-logr/logr` library, which is consistent throughout the project

If the community agrees with the proposal, I can submit a PR to resolve the issue

**Comment by MrAlias** [comment]
The `go.opentelemetry.io/otel/exporters/zipkin` package is released as stable. That function signature cannot be changed in a backwards compatible way to the proposal.

**Comment by MadVikingGod** [comment]
I would be open to this addition.  We can't remove or change the current WithLogger, but we can add another option and use logr under the hood.

My only real concern is compatibility between logr and the proposed structured logging.
