### ISSUE TITLE
CPU Overhead

### ISSUE THREAD

**Issue by sylr** [open-telemetry/opentelemetry-go#3518]
### Description

It seems to me that the opentelemetry-go cpu overhead is a bit large:

![abstraction_cpu_profile](https://user-images.githubusercontent.com/153052/205992328-1a0ae807-04b6-42d9-9a3c-afd937f54d5c.png)

### Environment

- OS: linux
- Architecture: x86
- Go Version: 1.19
- opentelemetry-go version: v1.11.1

### Steps To Reproduce

1. Run github.com/sylr/hey on my website
2. Export cpu profiles into grafana

### Expected behavior

Smaller opentelemetry overhead.

**Comment by sylr** [comment]
Might very well be, haven't thought of that.

**Comment by dmathieu** [comment]
There doesn't seem to be anything specifically actionable in this ticket, and "smaller overhead" has an extremely large definition of done.
Unless there's something more specific, I think we should close this ticket.
