### ISSUE TITLE
Generate the v1.16 version of the semconv package

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#3526]
The v1.16 version of the specification has been released. A new v1.16 version of semconv needs to be generated for this.

Blocked by #3191 which is working to add new HTTP semantic convention functionality due to upstream breaking changes.

**Comment by MrAlias** [comment]
From the work in the collector, it looks like this has significant changes included. Heads up.

**Comment by Aneurysm9** [comment]
See https://github.com/open-telemetry/opentelemetry-go-build-tools/pull/217 and https://github.com/open-telemetry/opentelemetry-collector/pull/6713 for the changes that were required in the collector and go-build-tools repos.
