### ISSUE TITLE
please add skywalking exporter

### ISSUE THREAD

**Issue by xqk** [open-telemetry/opentelemetry-go#3531]

**Comment by dmathieu** [comment]
Hi,

Thank you for your proposal. The exporters interface is public, and anybody can implement their own exporter.
You can see that interface here: https://github.com/open-telemetry/opentelemetry-go/blob/4e763472eee5ef03b97274694d2d1b07f0b3cd11/sdk/trace/span_exporter.go#L21-L47

The list of exporters in this specific repository is also quite limited, and specified for all otel SDKs. For example, for tracing, we implement jaeger and zipkin: https://github.com/open-telemetry/opentelemetry-specification/tree/791f463964c9a4d5a019408f9b669a30592c7c88/specification/trace/sdk_exporters

If you need an exporter to a specific database, I would therefore recommend you to set it up on a repository that you own and can maintain yourself.
