### ISSUE TITLE
`HTTPClientAttributesFromHTTPRequest` never sets `http.flavor`

### ISSUE THREAD

**Issue by gdavison** [open-telemetry/opentelemetry-go#3533]
### Description

Calling `HTTPClientAttributesFromHTTPRequest` never sets the attribute `http.flavor`.

`(*SemanticConventions).httpBasicAttributesFromHTTPRequest` checks for the presence of a value in `request.ProtoMajor` to set the value of `http.flavor`. However, this is not set on the client side, so will always be unset:

> For client requests, these fields are ignored. The HTTP client code always uses either HTTP/1.1 or HTTP/2. See the docs on Transport for details.

### Environment

- OS: macOS
- Architecture: amd64
- Go Version: 1.19
- opentelemetry-go version: v1.11.2

### Steps To Reproduce

1. Create an HTTP request
2. Call `HTTPClientAttributesFromHTTPRequest` on the request
3. Check value of `http.flavor`

### Expected behavior

`http.flavor` should be set.

**Comment by MrAlias** [comment]
Please see https://github.com/open-telemetry/opentelemetry-go/pull/3499
