### ISSUE TITLE
provide stable render result of `baggage`

### ISSUE THREAD

**Issue by zirain** [open-telemetry/opentelemetry-go#3538]
### Problem Statement

hi folks,
result of `baggage.String()` is random, because of `map`.
it's very painful for downstream user, when trying to get a stable result in UT.
for now, you always need do someting like following:
```
orderer := func(s string) string {
		members := strings.Split(s, listDelimiter)
		for i, m := range members {
			parts := strings.Split(m, propertyDelimiter)
			if len(parts) > 1 {
				sort.Strings(parts[1:])
				members[i] = strings.Join(parts, propertyDelimiter)
			}
		}
		sort.Strings(members)
		return strings.Join(members, listDelimiter)
	}
```

### Proposed Solution

provider new function named `OrderedString()` return sorted result

#### Alternatives

`NONE`

#### Prior Art

`NONE`

### Additional Context

If this's acceptable, I can raise a PR.

**Comment by dmathieu** [comment]
Could you describe the reason for needing an ordered baggage as a string?

**Comment by zirain** [comment]
I just want to avoid copy this [code block](https://github.com/open-telemetry/opentelemetry-go/blob/7a60bc785d669fa6ad26ba70e88151d4df631d90/baggage/baggage_test.go#L494) to UT, or is there a better way?
