### ISSUE TITLE
Int type traceContextKey

### ISSUE THREAD

**Issue by PalanQu** [open-telemetry/opentelemetry-go#3547]
### Description

We store the span in context with key which is int type, I think we should use a empty struct as the key, If accepted, I will create a PR to fix this.

current: 
``` go
// trace/context.go
const currentSpanKey traceContextKeyType = iota

if span, ok := ctx.Value(currentSpanKey).(Span); ok {
    return span
}
```

expect:
``` go
type spanKey struct {}

if span, ok := ctx.Value(spanKey{}).(Span); ok {
    return span
}
```

### Environment

- OS: Ubuntu18.04
- Architecture: x86
- Go Version: 1.18.3
- opentelemetry-go version: 1f5e6adbf2ca8fdb394ea07b3370506889a10bfa

**Comment by dmathieu** [comment]
What problem would this be solving?

**Comment by Aneurysm9** [comment]
> What problem would this be solving?

I'm not sure this would solve any problem and may create more.  With a type derived from `int` we can have multiple distinct context keys as necessary, but there can only be one empty struct value.
