### ISSUE TITLE
I can't set custom boundaries for histogram aggregation

### ISSUE THREAD

**Issue by krupyansky** [open-telemetry/opentelemetry-go#3552]
### Description

I want to set custom boundaries in the meter provider.

### Environment

- OS: linux (ubuntu 22.04)
- Architecture: x86
- Go Version: 1.19
- opentelemetry-go version: v0.34.0, v1.11.2

### Steps To Reproduce

1. git clone https://github.com/krupyansky/otel-bug
2. make init
3. make curl-metrics
4. go to localhost:8889/metrics
5. see default boundaries 0, 5, 10, 25, 50, 75, 100, 250 etc, but expect custom boundaries 0, 100, 250, 500, 750, 1000 etc that sets in https://github.com/krupyansky/otel-bug/blob/master/pkg/telemetry.go#L72

### Expected behavior

I want see custom boundaries for histogram

**Comment by MrAlias** [comment]
I'm not able to reproduce. Running the above steps I get:

```treminal
# HELP http_client_total_duration 
# TYPE http_client_total_duration histogram
http_client_total_duration_bucket{instance="xi",job="serviceName",service="catalog",le="0"} 0
http_client_total_duration_bucket{instance="xi",job="serviceName",service="catalog",le="5"} 0
http_client_total_duration_bucket{instance="xi",job="serviceName",service="catalog",le="10"} 0
http_client_total_duration_bucket{instance="xi",job="serviceName",service="catalog",le="25"} 1
http_client_total_duration_bucket{instance="xi",job="serviceName",service="catalog",le="50"} 1
http_client_total_duration_bucket{instance="xi",job="serviceName",service="catalog",le="75"} 1
http_client_total_duration_bucket{instance="xi",job="serviceName",service="catalog",le="100"} 1
http_client_total_duration_bucket{instance="xi",job="serviceName",service="catalog",le="250"} 1
http_client_total_duration_bucket{instance="xi",job="serviceName",service="catalog",le="500"} 1
http_client_total_duration_bucket{instance="xi",job="serviceName",service="catalog",le="750"} 1
http_client_total_duration_bucket{instance="xi",job="serviceName",service="catalog",le="1000"} 1
http_client_total_duration_bucket{instance="xi",job="serviceName",service="catalog",le="2500"} 1
http_client_total_duration_bucket{instance="xi",job="serviceName",service="catalog",le="5000"} 1
http_client_total_duration_bucket{instance="xi",job="serviceName",service="catalog",le="7500"} 1
http_client_total_duration_bucket{instance="xi",job="serviceName",service="catalog",le="10000"} 1
http_client_total_duration_bucket{instance="xi",job="serviceName",service="catalog",le="+Inf"} 1
http_client_total_duration_sum{instance="xi",job="serviceName",service="catalog"} 23
http_client_total_duration_count{instance="xi",job="serviceName",service="catalog"} 1
http_client_total_duration_bucket{instance="xi",job="serviceName",service="ordering",le="0"} 0
http_client_total_duration_bucket{instance="xi",job="serviceName",service="ordering",le="5"} 0
http_client_total_duration_bucket{instance="xi",job="serviceName",service="ordering",le="10"} 0
http_client_total_duration_bucket{instance="xi",job="serviceName",service="ordering",le="25"} 0
http_client_total_duration_bucket{instance="xi",job="serviceName",service="ordering",le="50"} 0
http_client_total_duration_bucket{instance="xi",job="serviceName",service="ordering",le="75"} 0
http_client_total_duration_bucket{instance="xi",job="serviceName",service="ordering",le="100"} 0
http_client_total_duration_bucket{instance="xi",job="serviceName",service="ordering",le="250"} 1
http_client_total_duration_bucket{instance="xi",job="serviceName",service="ordering",le="500"} 1
http_client_total_duration_bucket{instance="xi",job="serviceName",service="ordering",le="750"} 1
http_client_total_duration_bucket{instance="xi",job="serviceName",service="ordering",le="1000"} 1
http_client_total_duration_bucket{instance="xi",job="serviceName",service="ordering",le="2500"} 1
http_client_total_duration_bucket{instance="xi",job="serviceName",service="ordering",le="5000"} 1
http_client_total_duration_bucket{instance="xi",job="serviceName",service="ordering",le="7500"} 1
http_client_total_duration_bucket{instance="xi",job="serviceName",service="ordering",le="10000"} 1
http_client_total_duration_bucket{instance="xi",job="serviceName",service="ordering",le="+Inf"} 1
http_client_total_duration_sum{instance="xi",job="serviceName",service="ordering"} 187
http_client_total_duration_count{instance="xi",job="serviceName",service="ordering"} 1
```

Env:

```terminal
$ uname -a
Linux xi 6.0.11-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 02 Dec 2022 17:25:31 +0000 x86_64 GNU/Linux

$ go version
go version go1.19.4 linux/amd64
```

**Comment by krupyansky** [comment]
@MrAlias it's bug

I want see

# HELP http_client_total_duration 
# TYPE http_client_total_duration histogram
http_client_total_duration_bucket{instance="xi",job="serviceName",service="catalog",le="0"} 1
http_client_total_duration_bucket{instance="xi",job="serviceName",service="catalog",le="100"} 1
http_client_total_duration_bucket{instance="xi",job="serviceName",service="catalog",le="250"} 1
http_client_total_duration_bucket{instance="xi",job="serviceName",service="catalog",le="500"} 1
http_client_total_duration_bucket{instance="xi",job="serviceName",service="catalog",le="750"} 1
http_client_total_duration_bucket{instance="xi",job="serviceName",service="catalog",le="1000"} 1
http_client_total_duration_bucket{instance="xi",job="serviceName",service="catalog",le="1200"} 1
http_client_total_duration_bucket{instance="xi",job="serviceName",service="catalog",le="1500"} 1
http_client_total_duration_bucket{instance="xi",job="serviceName",service="catalog",le="1750"} 1
http_client_total_duration_bucket{instance="xi",job="serviceName",service="catalog",le="2000"} 1
http_client_total_duration_bucket{instance="xi",job="serviceName",service="catalog",le="2500"} 1
http_client_total_duration_bucket{instance="xi",job="serviceName",service="catalog",le="3000"} 1
http_client_total_duration_bucket{instance="xi",job="serviceName",service="catalog",le="5000"} 1
http_client_total_duration_bucket{instance="xi",job="serviceName",service="catalog",le="7500"} 1
http_client_total_duration_bucket{instance="xi",job="serviceName",service="catalog",le="10000"} 1
http_client_total_duration_bucket{instance="xi",job="serviceName",service="catalog",le="+Inf"} 1
http_client_total_duration_sum{instance="xi",job="serviceName",service="catalog"} 23
http_client_total_duration_count{instance="xi",job="serviceName",service="catalog"} 1

**Comment by MrAlias** [comment]
Ah, gotcha :+1:

**Comment by MrAlias** [comment]
You are getting the [default histogram buckets](https://github.com/open-telemetry/opentelemetry-go/blob/a724cf884287e04785eaa91513d26a6ef9699288/sdk/metric/reader.go#L150) because [your instrument](https://github.com/krupyansky/otel-bug/blob/7a48a9a2b349142249937fd149d7d213010ae9c2/main.go#L27) doesn't set the unit to milliseconds. The view you defined [matches on the unit being milliseconds](https://github.com/krupyansky/otel-bug/blob/7a48a9a2b349142249937fd149d7d213010ae9c2/pkg/telemetry.go#L67).

Removing that match criteria or including a unit definition for the instrument produces the desired buckets being applied for me.

**Comment by krupyansky** [comment]
@MrAlias thank you very much!)

I close the issue
