### ISSUE TITLE
Correlating or linking a span at a later time when its information is available

### ISSUE THREAD

**Issue by eduser25** [open-telemetry/opentelemetry-go#3608]
### Problem Statement

I was wondered if it is possible to assign a traceID or assign a remote span context status to a span after the fact.

The use case here is, say for example you want to have an internal, detailed view of a how a connection behaves in a distributed system (let's say client-server, basic http), the remote span context is only inferred after propagation through L7 layer, meaning I can only find a way to tell what is part of the original operation a bit too late, and some operations which I'd like to keep track of (TCP accept time, TLS handshake time) have already had their spans started and ended, without not being able to associate them as part of the ongoing global span at a later time.

I wonder if I'm missing something in this regard. The client side seems easily instrumenteable for this use case, but I can't find a way to properly correlate a span that has already started with a trace ID that is inferred at a later stage during the span's lifetime. Example below:

![Screenshot 2023-01-20 at 2 20 09 PM](https://user-images.githubusercontent.com/5503924/213815922-b97c2c74-d3ca-4ab0-bf39-bb8d910e063c.png)
![Screenshot 2023-01-20 at 2 19 53 PM](https://user-images.githubusercontent.com/5503924/213815943-5cc3c841-3f64-404e-ac48-931a4c3e0f56.png)

Originally, the operations on the server socket/tls should be part of the overall span, but I don't seem to find my way through the api to do it. At the time these happen, tracing still has no hold over the remote information as it is held in L7.

### Proposed Solution

I guess believe it would be nice to have a way to be able to tell a certain context tree of operations belongs to a certain span in cases where the span context cannot be inferred til a later time. I'm not entirely sure if this would go against the specification though.

**Comment by Aneurysm9** [comment]
The [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#specifying-links) prohibits adding span links after a span has been created.  We cannot implement this feature request here unless the specification changes.
