### ISSUE TITLE
docs:  why does the meteric counter addition required a context object?

### ISSUE THREAD

**Issue by sasha-wing** [open-telemetry/opentelemetry-go#3618]
It is not clear in the documentation why the counter requires the context and how it is using it.
```
counter.Add(ctx, 1, attribute.String("foo", "bar"))
```
This one for example.

**Comment by MrAlias** [comment]
It is currently used to determine a timeout:

https://github.com/open-telemetry/opentelemetry-go/blob/c7e26795299ff79f13b162eec7800bed592931e1/sdk/metric/instrument.go#L197-L199

I don't think this by itself justifies keeping the context in the method signature for any synchronous instrument though. The caller can just as easily check if a timeout happened and the call to `Add` or `Record` are lightweight enough that they do not need to be canceled halfway through.

Another original idea for including this parameter was so any existing span embedded in the context can be linked to the measurement. This is not currently done though.

**Comment by MrAlias** [comment]
The context will also be needed when we add support for exemplars.

**Comment by MrAlias** [comment]
Given the context needs specified above, we plan to continue accepting a context argument with the `Add`/`Record` method.

**Comment by ravanscafi** [comment]
Hello, sorry for reviving this @MrAlias, but how one would go about recording a metric specifically when there's a timeout/context error?

e.g., on an HTTP client implementation, I have a meter using the request context and I would like to keep track of HTTP timeouts, however, the metrics are ignored because of this timeout.

**Comment by pellared** [comment]
@ravanscafi We have been recently discussing it. See: https://github.com/open-telemetry/opentelemetry-go/pull/4671 for more details.
