### ISSUE TITLE
Cut 0.2 release

### ISSUE THREAD

**Issue by lizthegrey** [open-telemetry/opentelemetry-go#363]
Now that we have functioning metrics, should we cut a 0.2 series release? I recognize context prop isn't there yet, but that should hold a 0.3 series rather than 0.2 series...

**Comment by jmacd** [comment]
Sounds good!

**Comment by rghetia** [comment]
[v0.2.0](https://github.com/open-telemetry/opentelemetry-go/releases/tag/v0.2.0) is released
