### ISSUE TITLE
WithContainerID: Extracts incorrect container ID in ECS.

### ISSUE THREAD

**Issue by mackjmr** [open-telemetry/opentelemetry-go#3633]
### Description

`WithContainerID` ([link](https://pkg.go.dev/go.opentelemetry.io/otel/sdk@v1.6.1/resource#WithContainerID)) extracts the container ID from `/proc/self/cgroup` using the following [regex](https://github.com/open-telemetry/opentelemetry-go/blob/c7e26795299ff79f13b162eec7800bed592931e1/sdk/resource/container.go#L32). The container ID in ECS does not does not match the expected format of the regex.

- Example working cgroup:
```
14:name=systemd:/docker/8c1e75bb325eb9c64571326952a6507132f1fc7eba7cd5b694422abe39fc7ed8
13:rdma:/
12:pids:/docker/8c1e75bb325eb9c64571326952a6507132f1fc7eba7cd5b694422abe39fc7ed8
11:hugetlb:/docker/8c1e75bb325eb9c64571326952a6507132f1fc7eba7cd5b694422abe39fc7ed8
10:net_prio:/docker/8c1e75bb325eb9c64571326952a6507132f1fc7eba7cd5b694422abe39fc7ed8
9:perf_event:/docker/8c1e75bb325eb9c64571326952a6507132f1fc7eba7cd5b694422abe39fc7ed8
8:net_cls:/docker/8c1e75bb325eb9c64571326952a6507132f1fc7eba7cd5b694422abe39fc7ed8
7:freezer:/docker/8c1e75bb325eb9c64571326952a6507132f1fc7eba7cd5b694422abe39fc7ed8
6:devices:/docker/8c1e75bb325eb9c64571326952a6507132f1fc7eba7cd5b694422abe39fc7ed8
5:memory:/docker/8c1e75bb325eb9c64571326952a6507132f1fc7eba7cd5b694422abe39fc7ed8
4:blkio:/docker/8c1e75bb325eb9c64571326952a6507132f1fc7eba7cd5b694422abe39fc7ed8
3:cpuacct:/docker/8c1e75bb325eb9c64571326952a6507132f1fc7eba7cd5b694422abe39fc7ed8
2:cpu:/docker/8c1e75bb325eb9c64571326952a6507132f1fc7eba7cd5b694422abe39fc7ed8
1:cpuset:/docker/c
```

Extracted container ID => `8c1e75bb325eb9c64571326952a6507132f1fc7eba7cd5b694422abe39fc7ed8` ✅ 

- Example cgroup in ECS (docker container deployed with fargate):
```
11:freezer:/ecs/121c14dc9fd841a5a995bdfb82dd4e32/121c14dc9fd841a5a995bdfb82dd4e32-2232344121
10:devices:/ecs/121c14dc9fd841a5a995bdfb82dd4e32/121c14dc9fd841a5a995bdfb82dd4e32-2232344121
9:blkio:/ecs/121c14dc9fd841a5a995bdfb82dd4e32/121c14dc9fd841a5a995bdfb82dd4e32-2232344121
8:perf_event:/ecs/121c14dc9fd841a5a995bdfb82dd4e32/121c14dc9fd841a5a995bdfb82dd4e32-2232344121
7:pids:/ecs/121c14dc9fd841a5a995bdfb82dd4e32/121c14dc9fd841a5a995bdfb82dd4e32-2232344121
6:memory:/ecs/121c14dc9fd841a5a995bdfb82dd4e32/121c14dc9fd841a5a995bdfb82dd4e32-2232344121
5:cpuset:/ecs/121c14dc9fd841a5a995bdfb82dd4e32/121c14dc9fd841a5a995bdfb82dd4e32-2232344121
4:cpu,cpuacct:/ecs/121c14dc9fd841a5a995bdfb82dd4e32/121c14dc9fd841a5a995bdfb82dd4e32-2232344121
3:net_cls,net_prio:/ecs/121c14dc9fd841a5a995bdfb82dd4e32/121c14dc9fd841a5a995bdfb82dd4e32-2232344121
2:hugetlb:/ecs/121c14dc9fd841a5a995bdfb82dd4e32/121c14dc9fd841a5a995bdfb82dd4e32-2232344121
1:name=systemd:/ecs/121c14dc9fd841a5a995bdfb82dd4e32/121c14dc9fd841a5a995bdfb82dd4e32-2232344121	
```

Extracted container ID => `2232344121` ❌ 
Expected container ID => `121c14dc9fd841a5a995bdfb82dd4e32-2232344121`

### Environment

- Operating system/Architecture: Linux/X86_64
- Platform version: 1.4.0
- Lauch type: FARGATE

### Steps To Reproduce

Deploy a docker container with Fargate and use `WithContainerID()`.

### Expected behavior

The valid container ID to be added as a resource attribute in ECS. 

One way to do this would be to adapt the regex if it is detected to be a Fargate environment. 

Another way to do this is by leveraging `ECS_CONTAINER_METADATA_URI` ([link](https://docs.aws.amazon.com/AmazonECS/latest/userguide/task-metadata-endpoint-v4-fargate.html)). This endpoint returns a json containing the `DockerId` (and other metadata about the container itself). opentelemetry-java uses this method to detect resource attributes on ECS ([PR](https://github.com/open-telemetry/opentelemetry-java/pull/4574)).

**Comment by MrAlias** [comment]
cc @Aneurysm9

**Comment by Aneurysm9** [comment]
The [ECS resource detector](https://pkg.go.dev/go.opentelemetry.io/contrib/detectors/aws/ecs) can correctly determine the [continer ID](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/detectors/aws/ecs/ecs.go#L97).  I don't know that `WithContainerID()` should be modified to special-case for ECS when a separate detector is already available.

**Comment by mackjmr** [comment]
Thanks for the response @Aneurysm9, the approach you mentioned makes sense to me. I think it would still be helpful to document this limitation in `WithContainerID()` and suggest using the ECS resource detector instead. Does that make sense? If so, happy to put up the PR to document this.

**Comment by Aneurysm9** [comment]
> I think it would still be helpful to document this limitation in `WithContainerID()` and suggest using the ECS resource detector instead. Does that make sense? If so, happy to put up the PR to document this.

That sounds good to me.
