### ISSUE TITLE
Example Docs for Passthrough Traces Need Update for Moved NewTracerProvider

### ISSUE THREAD

**Issue by drewthor** [open-telemetry/opentelemetry-go#3637]
### Description

https://github.com/open-telemetry/opentelemetry-go/blob/4883cb119d59de101dba898fd02604b989734089/example/passthrough/README.md

`NewTracerProvider` has been moved from `go.opentelemetry.io/otel/trace` to `go get go.opentelemetry.io/otel/bridge/opentracing` in v1.12.0 so this documentation needs to be updated for the changes for sample code.

### Environment
- opentelemetry-go version: v1.12.0

**Comment by MrAlias** [comment]
Thanks for your interest in the project. `NewTracerProvider` from `go.opentelemetry.io/otel/trace` was not moved to `go.opentelemetry.io/otel/bridge/opentracing`. A [`NewTracerProvider`](https://pkg.go.dev/go.opentelemetry.io/otel/bridge/opentracing#NewTracerProvider) function was added to `go.opentelemetry.io/otel/bridge/opentracing` to return ...

> a new TracerProvider that creates new instances of WrapperTracer from the given TracerProvider.

It is not added as a replacement, but a distinct function. No update to documentation is needed.

**Comment by drewthor** [comment]
Ah yes, thank you! I believe I got confused with the `go.opentelemetry.io/otel/trace` and `go.opentelemetry.io/otel/sdk/trace` packages. Apologies for the invalid issue.
