### ISSUE TITLE
Verify compliant metric SDK specification implementation: MeterProvider

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#3640]
- [x] Identify the normative requirements from the top level `MeterProvider` section of [the specification]:

  > A `MeterProvider` MUST provide a way to allow a [`Resource`](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/resource/sdk.md) to be specified. If a `Resource` is specified, it SHOULD be associated with all the metrics produced by any `Meter` from the `MeterProvider`. The [tracing SDK specification](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/trace/sdk.md#additional-span-interfaces) has provided some suggestions regarding how to implement this efficiently.

- [x] Ensure the [current metric SDK implementation] is compliant with these normative requirements, recommendations, and options in those comments.

[the specification]: https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/metrics/sdk.md
[current metric SDK implementation]: https://pkg.go.dev/go.opentelemetry.io/otel/sdk/metric@v0.39.0

**Comment by pellared** [comment]
> A MeterProvider MUST provide a way to allow a [Resource](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/resource/sdk.md) to be specified.

It is possible to provide a `Resource` for `MeterProvider` by using [`metric.NewMeterProvider`](https://pkg.go.dev/go.opentelemetry.io/otel/sdk/metric@v0.39.0#NewMeterProvider) with [`metric.WithResource`](https://pkg.go.dev/go.opentelemetry.io/otel/sdk/metric@v0.39.0#WithResource) passed as a parameter.

**Comment by pellared** [comment]
>  If a Resource is specified, it SHOULD be associated with all the metrics produced by any Meter from the MeterProvider. 

I could not a failed to find a unit test that ensures that this is implemented. Creating issue.

**Comment by pellared** [comment]
> The [tracing SDK specification](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/trace/sdk.md#additional-span-interfaces) has provided some suggestions regarding how to implement this efficiently.

This is not normative.

**Comment by pellared** [comment]
@MrAlias Can you please double-check and close if you agree with my verification (double-verification 😉 ).

**Comment by MrAlias** [comment]
LGTM :+1:
