### ISSUE TITLE
Verify compliant metric SDK specification implementation: MeterProvider/MeterProvider Creation

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#3641]
- [x] Identify all the normative requirements, recommendations, and options [the specification] defines as comments to this issue
- [x] Ensure the [current metric SDK implementation] is compliant with these normative requirements, recommendations, and options in those comments.

[the specification]: https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/metrics/sdk.md
[current metric SDK implementation]: https://pkg.go.dev/go.opentelemetry.io/otel/sdk/metric@v0.39.0

**Comment by pellared** [comment]
> The SDK SHOULD allow the creation of multiple independent `MeterProvider`s.

It is possible by using [`metric.NewMeterProvider`](https://pkg.go.dev/go.opentelemetry.io/otel/sdk/metric@v0.39.0#NewMeterProvider)

**Comment by pellared** [comment]
It looks like we comply with this fragment of the specification.

@MrAlias Can you please double-check and close if you agree with my verification?

**Comment by MrAlias** [comment]
LGTM :+1:
