### ISSUE TITLE
Verify compliant metric SDK specification implementation: MeterProvider/Meter Creation

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#3642]
- [x] Identify all the normative requirements, recommendations, and options [the specification] defines as comments to this issue
- [x] Ensure the [current metric SDK implementation] is compliant with these normative requirements, recommendations, and options in those comments.

[the specification]: https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/metrics/sdk.md
[current metric SDK implementation]: https://pkg.go.dev/go.opentelemetry.io/otel/sdk/metric@v0.39.0

**Comment by pellared** [comment]
> New `Meter` instances are always created through a `MeterProvider` (see [API](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/metrics/api.md#meterprovider)). The `name`, `version` (optional), `schema_url` (optional), and `attributes` (optional) arguments supplied to the `MeterProvider` MUST be used to create an [InstrumentationScope](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/glossary.md#instrumentation-scope) instance which is stored on the created `Meter`.

_Verification in progress..._

**Comment by pellared** [comment]
> In the case where an invalid name (null or empty string) is specified, a working Meter MUST be returned as a fallback rather than returning null or throwing an exception, its name SHOULD keep the original invalid value, and a message reporting that the specified value is invalid SHOULD be logged.

**Comment by pellared** [comment]
> When a Schema URL is passed as an argument when creating a `Meter` the emitted telemetry for that `Meter` MUST be associated with the Schema URL, provided that the emitted data format is capable of representing such association.

_Verification in progress..._

**Comment by pellared** [comment]
> Configuration (i.e., [MetricExporters](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/metrics/sdk.md#metricexporter), [MetricReaders](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/metrics/sdk.md#metricreader) and [Views](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/metrics/sdk.md#view)) MUST be managed solely by the `MeterProvider` and the SDK MUST provide a way to configure all options that are implemented by the SDK. This MAY be done at the time of MeterProvider creation if appropriate.

_Verification in progres..._

**Comment by pellared** [comment]
> The `MeterProvider` MAY provide methods to update the configuration. If
configuration is updated (e.g., adding a `MetricReader`), the updated
configuration MUST also apply to all already returned `Meters` (i.e. it MUST NOT
matter whether a `Meter` was obtained from the `MeterProvider` before or after
the configuration change). Note: Implementation-wise, this could mean that
`Meter` instances have a reference to their `MeterProvider` and access
configuration only via this reference.

_Verification in progress_

**Comment by MrAlias** [comment]
> > Configuration (i.e., [MetricExporters](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/metrics/sdk.md#metricexporter), [MetricReaders](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/metrics/sdk.md#metricreader) and [Views](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/metrics/sdk.md#view)) MUST be managed solely by the `MeterProvider` and the SDK MUST provide a way to configure all options that are implemented by the SDK. This MAY be done at the time of MeterProvider creation if appropriate.
> 
> I read it three times and I am not sure what the author had in mind. Origins from: [open-telemetry/opentelemetry-specification#1730](https://github.com/open-telemetry/opentelemetry-specification/pull/1730)
> 
> What does "configuration" mean here? What does "manage" mean? Does it mean that we cannot configure a [`PeriodicReader`](https://pkg.go.dev/go.opentelemetry.io/otel/sdk/metric#NewPeriodicReader) using [options](https://pkg.go.dev/go.opentelemetry.io/otel/sdk/metric#PeriodicReaderOption)?
> 
> What does "SDK MUST provide a way to configure all options that are implemented by the SDK" mean (it looks like "the SDK has everything configurable").
> 
> Maybe it is my reading, but I find this paragraph not clear. Moreover, the paragraph contains normative wording.
> 
> @MrAlias Can you please double-check? (Maybe the issue is on my side)

This looks similar to the trace SDK where the `TracerProvider` held all the configuration (if I remember correctly it was just copied from the trace specification). The intent, as I understand it, is that there shouldn't be some other object other than the `MeterProvider` that holds configuration, like a `Configurator` object.

This does seem strange though given the exporter and reader will configure the temporality and default aggregators.

Given our setup matches other already stable language implementations, I'm guessing we aren't doing something the specification didn't intend.

I would suggest opening a PR in the specification to clarify this section after working with the spec SIG to understand its meaning. That way if we are out of compliance we can fix it now.

**Comment by MrAlias** [comment]
> EDIT: I guess that what the author had in mind is that the `MetricProvider` takes the responsibility of instantiating components (readers, exporter, views) which do actual work. If my guess is correct this would mean that if the user sets up a periodic reader it should be "started" by the metric provider. If so then e.g. this would violate the specification: https://github.com/open-telemetry/opentelemetry-go/blob/sdk/metric/v0.39.0/sdk/metric/periodic_reader.go#L130-L133.

I don't think the started nature matters too much here. More so the configuration of how a reader fits into the metric pipelines.

**Comment by pellared** [comment]
PR created for clarifying the specification about the configuration:

- https://github.com/open-telemetry/opentelemetry-specification/pull/3522

**Comment by pellared** [comment]
https://github.com/open-telemetry/opentelemetry-specification/pull/3522 is merged. Closing the issue as all related issues and PRs are closed.
