### ISSUE TITLE
Verify compliant metric SDK specification implementation: MeterProvider/Resolving duplicate instrument registration conflicts

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#3653]
- [x] Identify all the normative requirements, recommendations, and options [the specification] defines as comments to this issue
- [x] Ensure the [current metric SDK implementation] is compliant with these normative requirements, recommendations, and options in those comments.

[the specification]: https://github.com/open-telemetry/opentelemetry-specification/blob/0c5bfa999a5310801d5c36d2a82cbcd0e32ca9cb/specification/metrics/sdk.md#resolving-duplicate-instrument-registration-conflicts
[current metric SDK implementation]: https://github.com/open-telemetry/opentelemetry-go/tree/v1.12.0/sdk/metric

**Comment by MrAlias** [comment]
> Based on [the recommendations from the data model](data-model.md#opentelemetry-protocol-data-model-producer-recommendations), the SDK MUST aggregate data from identical Instruments together in its export pipeline.

As noted above, the OTel Go implementation is not compliant. The missing `name` conflict aggregation is being tracked in https://github.com/open-telemetry/opentelemetry-go/issues/3835.

Otherwise, since identical [describes instances where all identifying fields are equal" and [the identifying fields are](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/metrics/api.md#instrument):

- The name of the Instrument
- The kind of the Instrument - whether it is a [Counter](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/metrics/api.md#counter) or one of the other kinds, whether it is synchronous or asynchronous
- An optional unit of measure
- An optional description
- *note*: we do not currently support advice so it is not considered here

And the cache look up key:

https://github.com/open-telemetry/opentelemetry-go/blob/135c64f2897000780febb0945d1d9db195faecc6/sdk/metric/pipeline.go#L326

is missing the instrument kind, and contains the additional aggregation name, monotonicity, temporality, and number:

https://github.com/open-telemetry/opentelemetry-go/blob/135c64f2897000780febb0945d1d9db195faecc6/sdk/metric/instrument.go#L152-L171

The implementation is not compliant:

- If two different instruments with the same, name, unit, and description but of different kinds are created it could be the case that two different aggregators will be used
- If two different instruments with the same, name, unit, kind, and description but of different number types (i.e. `int64` and `float64`) are created they will use different aggregators

**Comment by MrAlias** [comment]
> When a duplicate instrument registration occurs, and it is not corrected with a View, a warning SHOULD be emitted.

Implemented here:

https://github.com/open-telemetry/opentelemetry-go/blob/135c64f2897000780febb0945d1d9db195faecc6/sdk/metric/pipeline.go#L325

This is not warning though:

https://github.com/open-telemetry/opentelemetry-go/blob/135c64f2897000780febb0945d1d9db195faecc6/sdk/metric/pipeline.go#L357-L366

It was added prior to [`Warn`](https://github.com/open-telemetry/opentelemetry-go/blob/135c64f2897000780febb0945d1d9db195faecc6/internal/global/internal_logging.go#L66-L70) being added.

**Comment by MrAlias** [comment]
> > When a duplicate instrument registration occurs, and it is not corrected with a View, a warning SHOULD be emitted.
> 
> Implemented here:
> 
> https://github.com/open-telemetry/opentelemetry-go/blob/135c64f2897000780febb0945d1d9db195faecc6/sdk/metric/pipeline.go#L325
> 
> This is not warning though:
> 
> https://github.com/open-telemetry/opentelemetry-go/blob/135c64f2897000780febb0945d1d9db195faecc6/sdk/metric/pipeline.go#L357-L366
> 
> It was added prior to [`Warn`](https://github.com/open-telemetry/opentelemetry-go/blob/135c64f2897000780febb0945d1d9db195faecc6/internal/global/internal_logging.go#L66-L70) being added.

https://github.com/open-telemetry/opentelemetry-go/pull/4202

**Comment by dashpole** [comment]
Should this be closed?

**Comment by MrAlias** [comment]
> Should this be closed?

The [specification issue](https://github.com/open-telemetry/opentelemetry-specification/issues/3539) for duplicate name conflicts looks like it is going to resolve in a different direction then we implemented. We will likely need to track that change and adjust accordingly.

**Comment by dashpole** [comment]
Thanks.  I just noticed that all the TODOs were checked.
