### ISSUE TITLE
Verify compliant metric SDK specification implementation: MetricReader

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#3660]
- [x] Identify all the normative requirements, recommendations, and options [the specification] defines as comments to this issue
- [x] Ensure the [current metric SDK implementation] is compliant with these normative requirements, recommendations, and options in those comments.

[the specification]: https://github.com/open-telemetry/opentelemetry-specification/blob/v1.23.0/specification/metrics/sdk.md
[current metric SDK implementation]: https://pkg.go.dev/go.opentelemetry.io/otel/sdk/metric@v0.39.0

**Comment by MrAlias** [comment]
> To construct a `MetricReader` when setting up an SDK, the caller SHOULD provide at least the following:
> 
> * The `exporter` to use, which is a `MetricExporter` instance.
> * The default output `aggregation` (optional), a function of instrument kind.  If not configured, the [default aggregation](#default-aggregation) SHOULD be used.
> * The default output `temporality` (optional), a function of instrument kind.  If not configured, the Cumulative temporality SHOULD be used.
> * The default aggregation cardinality limit to use, a function of instrument kind.  If not configured, a default value of 2000 SHOULD be used.

This recommendation is confusing. It applies to all readers but not all readers accept these parameters.

Additionally, the default aggregation cardinality limit should be marked experimental.

This is going to require a specification issue/PR.

**Comment by MrAlias** [comment]
> A common sub-class of `MetricReader`, the periodic exporting `MetricReader` SHOULD be provided to be used typically with push-based metrics collection.

We are compliant with this. We provide a [`PeriodicReader`](https://github.com/open-telemetry/opentelemetry-go/blob/c197fe93057875323a2e4f07af6d5707de52f1fd/sdk/metric/periodic_reader.go#L141).

TODO: PR the specification to remove the "sub-class" term as our language does not have classes.

**Comment by MrAlias** [comment]
> The `MetricReader` MUST ensure that data points from OpenTelemetry [instruments](./api.md#instrument) are output in the configured aggregation temporality for each instrument kind.

This requirement is not clear to me. The reader is not the `Aggregator`, it does not ensure the temporality of an aggregation. I'm not sure how this requirement can be fulfilled. It seems like a specification issue/PR is needed to clarify this.

> For synchronous instruments being output with Cumulative temporality, this means converting [Delta to Cumulative](supplementary-guidelines.md#synchronous-example-cumulative-aggregation-temporality) aggregation temporality.
> For asynchronous instruments being output with Delta temporality, this means converting [Cumulative to Delta](supplementary-guidelines.md#asynchronous-example-delta-temporality) aggregation temporality.

This assumes all synchronous instruments record delta values and asynchronous instruments cumulative. This is not a valid assumption. A specification issue/PR is needed.

**Comment by MrAlias** [comment]
> The `MetricReader` is not required to ensure data points from a non-SDK [MetricProducer](#metricproducer) are output in the configured aggregation temporality, as these data points are not collected using OpenTelemetry instruments.

This is non-normative, but I'm guessing the intent was to have it be normative.

Again, given the temproality is not handled by the `MetricReader` but by the `Aggregator` I'm not sure this is entirely clear. A specification issue/PR is needed.

cc @dashpole

**Comment by MrAlias** [comment]
> The SDK MUST support multiple `MetricReader` instances to be registered on the same `MeterProvider` [...]

A variable number of [`WithReader`](https://pkg.go.dev/go.opentelemetry.io/otel/sdk/metric#WithReader) options can be passed to [`NewMeterProvider`](https://pkg.go.dev/go.opentelemetry.io/otel/sdk/metric#NewMeterProvider). Each option will register the `Reader` with returned `MeterProvider`:

https://github.com/open-telemetry/opentelemetry-go/blob/c197fe93057875323a2e4f07af6d5707de52f1fd/sdk/metric/provider.go#L55-L59

https://github.com/open-telemetry/opentelemetry-go/blob/c197fe93057875323a2e4f07af6d5707de52f1fd/sdk/metric/pipeline.go#L486-L494

**Comment by MrAlias** [comment]
> [...] the [MetricReader.Collect](#collect) invocation on one `MetricReader` instance SHOULD NOT introduce side-effects to other `MetricReader` instances.

Each `Reader` registered with a `MeterProvider` has its own `pipeline`:

https://github.com/open-telemetry/opentelemetry-go/blob/c197fe93057875323a2e4f07af6d5707de52f1fd/sdk/metric/pipeline.go#L486-L494

That pipeline contains independent aggregators that are not shared with other pipelines:

https://github.com/open-telemetry/opentelemetry-go/blob/c197fe93057875323a2e4f07af6d5707de52f1fd/sdk/metric/pipeline.go#L77

Recording a value for an instrument will make a measurement for each of these aggregations inpendently:

https://github.com/open-telemetry/opentelemetry-go/blob/c197fe93057875323a2e4f07af6d5707de52f1fd/sdk/metric/instrument.go#L249-L256

https://github.com/open-telemetry/opentelemetry-go/blob/c197fe93057875323a2e4f07af6d5707de52f1fd/sdk/metric/instrument.go#L218-L225

Therefore, due to the separation of aggregators, the invocation of `Collect` for one `Reader` cannot affect the data of another reader.

I think adding a test for this would be helpful to ensure compatibility. However, it is probably unlikely the test will be able to check all edge cases for this and isn't strictly required for the resolution of this issue.

**Comment by MrAlias** [comment]
> The SDK MUST NOT allow a `MetricReader` instance to be registered on more than one `MeterProvider` instance.

Both implementation of the `Reader` interface only allow themselves to be registered at most once:

https://github.com/open-telemetry/opentelemetry-go/blob/84b2e5467131a1f1faf41f788677e5ee66a9b8de/sdk/metric/periodic_reader.go#L189-L195

https://github.com/open-telemetry/opentelemetry-go/blob/84b2e5467131a1f1faf41f788677e5ee66a9b8de/sdk/metric/manual_reader.go#L57-L65

Given the method to register with the `MeterProvider` is unexported, 3rd-party users do not have the ability to override this method. Meaning the SDK does not allow any implementation of a `Reader` to be registered more than once. Thus  the implementation is compliant.

**Comment by MrAlias** [comment]
> The SDK SHOULD provide a way to allow `MetricReader` to respond to [MeterProvider.ForceFlush](#forceflush) and [MeterProvider.Shutdown](#shutdown). [OpenTelemetry SDK](../overview.md#sdk) authors MAY decide the language idiomatic approach, for example, as `OnForceFlush` and `OnShutdown` callback functions.

The `ForceFlush` and `Shutdown` functions are methods on the `Reader` interface:

https://github.com/open-telemetry/opentelemetry-go/blob/84b2e5467131a1f1faf41f788677e5ee66a9b8de/sdk/metric/reader.go#L81-L103

Each of our implementations use the Go idiomatic way to define how each will respond by having methods of their own that implement the interface.

**Comment by dashpole** [comment]
> > The `MetricReader` is not required to ensure data points from a non-SDK [MetricProducer](#metricproducer) are output in the configured aggregation temporality, as these data points are not collected using OpenTelemetry instruments.

> This is non-normative, but I'm guessing the intent was to have it be normative.

> Again, given the temporality is not handled by the `MetricReader` but by the `Aggregator` I'm not sure this is entirely clear. A specification issue/PR is needed.

> cc @dashpole 

This was just meant to carve out an exception to the rule above for MetricProducers.

**Comment by dashpole** [comment]
My reading of "must ensure that datapoints ... are output in [X] aggregation temporality" was that it could be fulfilled by passing aggregation temporality config to something that correctly handles aggregation temporality. 

From the spec: `Note: the term aggregation is used instead of aggregator. It is RECOMMENDED that implementors reserve the "aggregator" term for the future when the SDK allows custom aggregation implementations.`

I suspect at the time it was written, there was _only_ the `MetricReader`, and no notion of an `Aggregator`.  The "reader" essentially meant something like "reader and all measurement -> aggregation details".

**Comment by MrAlias** [comment]
> > A common sub-class of `MetricReader`, the periodic exporting `MetricReader` SHOULD be provided to be used typically with push-based metrics collection.
> 
> We are compliant with this. We provide a [`PeriodicReader`](https://github.com/open-telemetry/opentelemetry-go/blob/c197fe93057875323a2e4f07af6d5707de52f1fd/sdk/metric/periodic_reader.go#L141).
> 
> TODO: PR the specification to remove the "sub-class" term as our language does not have classes.

https://github.com/open-telemetry/opentelemetry-specification/pull/3628

**Comment by MrAlias** [comment]
> > To construct a `MetricReader` when setting up an SDK, the caller SHOULD provide at least the following:
> > 
> > * The `exporter` to use, which is a `MetricExporter` instance.
> > * The default output `aggregation` (optional), a function of instrument kind.  If not configured, the [default aggregation](#default-aggregation) SHOULD be used.
> > * The default output `temporality` (optional), a function of instrument kind.  If not configured, the Cumulative temporality SHOULD be used.
> > * The default aggregation cardinality limit to use, a function of instrument kind.  If not configured, a default value of 2000 SHOULD be used.
> 
> This recommendation is confusing. It applies to all readers but not all readers accept these parameters.
> 
> Additionally, the default aggregation cardinality limit should be marked experimental.
> 
> This is going to require a specification issue/PR.

Given the parameters are recommendations, and are defined in [RFC 2119](https://www.rfc-editor.org/rfc/rfc2119.txt) to mean ...

> that there may exist valid reasons in particular circumstances to ignore a particular item, but the full implications must be understood and carefully weighed before choosing a different course.

There exist a valid reason to ignore these parameters (e.g. does not export, has a dependency on cumulative temporality).

I think the specification could have been better phrased, but I don't want to block this issue on fixing the phrasing in the specification. Moving on.

**Comment by MrAlias** [comment]
Everything has been identified and verified to be compliant. Closing.
