### ISSUE TITLE
Verify compliant metric SDK specification implementation: MetricReader/MetricReader operations/Collect

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#3662]
- [x] Identify all the normative requirements, recommendations, and options [the specification] defines as comments to this issue
- [x] Ensure the [current metric SDK implementation] is compliant with these normative requirements, recommendations, and options in those comments.

[the specification]: https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/metrics/sdk.md
[current metric SDK implementation]: https://pkg.go.dev/go.opentelemetry.io/otel/sdk/metric@v0.39.0

**Comment by dashpole** [comment]
I would like to take this.

**Comment by dashpole** [comment]
> MetricReader is an SDK implementation object that provides the common configurable aspects of the OpenTelemetry Metrics SDK and determines the following capabilities:

> * Registering [MetricProducer](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/metrics/sdk.md#metricproducer)(s)

https://github.com/open-telemetry/opentelemetry-go/blob/cbc5890d9cba29c57a0c39dd27ed204e29d5370a/sdk/metric/reader.go#L60-L65

> * Collecting metrics from the SDK and any registered [MetricProducers](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/metrics/sdk.md#metricproducer) on demand.

https://github.com/open-telemetry/opentelemetry-go/blob/cbc5890d9cba29c57a0c39dd27ed204e29d5370a/sdk/metric/reader.go#L73-L79

> * Handling the [ForceFlush](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/metrics/sdk.md#forceflush) and [Shutdown](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/metrics/sdk.md#shutdown) signals from the SDK.

https://github.com/open-telemetry/opentelemetry-go/blob/cbc5890d9cba29c57a0c39dd27ed204e29d5370a/sdk/metric/reader.go#L81-L103

**Comment by dashpole** [comment]
> To construct a MetricReader when setting up an SDK, the caller SHOULD provide at least the following:

> * The exporter to use, which is a MetricExporter instance.

This option is ONLY exposed on periodic readers.

https://github.com/open-telemetry/opentelemetry-go/blob/cbc5890d9cba29c57a0c39dd27ed204e29d5370a/sdk/metric/periodic_reader.go#L114

> * The default output aggregation (optional), a function of instrument kind. If not configured, the [default aggregation](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/metrics/sdk.md#default-aggregation) SHOULD be used.

**This option is not provided when constructing a MetricReader.**

> * The default output temporality (optional), a function of instrument kind. If not configured, the Cumulative temporality SHOULD be used.

**This option is not provided when constructing a MetricReader.**

> * The default aggregation cardinality limit to use, a function of instrument kind. If not configured, a default value of 2000 SHOULD be used.

**This option is not provided when constructing a MetricReader.**

**Comment by dashpole** [comment]
> A common sub-class of MetricReader, the periodic exporting MetricReader SHOULD be provided to be used typically with push-based metrics collection.

We provide a PeriodicMetricReader:

https://github.com/open-telemetry/opentelemetry-go/blob/cbc5890d9cba29c57a0c39dd27ed204e29d5370a/sdk/metric/periodic_reader.go#L114

**Comment by dashpole** [comment]
> The MetricReader MUST ensure that data points from OpenTelemetry [instruments](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/metrics/api.md#instrument) are output in the configured aggregation temporality for each instrument kind. For synchronous instruments being output with Cumulative temporality, this means converting [Delta to Cumulative](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/metrics/supplementary-guidelines.md#synchronous-example-cumulative-aggregation-temporality) aggregation temporality. For asynchronous instruments being output with Delta temporality, this means converting [Cumulative to Delta](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/metrics/supplementary-guidelines.md#asynchronous-example-delta-temporality) aggregation temporality.

The periodic reader defaults to the exporter's temporality: https://github.com/open-telemetry/opentelemetry-go/blob/cbc5890d9cba29c57a0c39dd27ed204e29d5370a/sdk/metric/periodic_reader.go#L213-L215

The manual reader defaults to the configured temporality: https://github.com/open-telemetry/opentelemetry-go/blob/cbc5890d9cba29c57a0c39dd27ed204e29d5370a/sdk/metric/manual_reader.go#L84-L87

The collection + aggregation pipeline uses the temporality of the reader: https://github.com/open-telemetry/opentelemetry-go/blob/cbc5890d9cba29c57a0c39dd27ed204e29d5370a/sdk/metric/pipeline.go#L328-L329

That temporality is used to ensure that the aggregation is output in the correct temporality: https://github.com/open-telemetry/opentelemetry-go/blob/cbc5890d9cba29c57a0c39dd27ed204e29d5370a/sdk/metric/internal/aggregate/aggregate.go#L92-L96

I believe that satisfies the "MUST ensure that data points ... are output in the configured aggregation temporality", even though much of the implementation details are not implemented within our Readers.

**Comment by dashpole** [comment]
> The SDK MUST support multiple MetricReader instances to be registered on the same MeterProvider, and the [MetricReader.Collect](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/metrics/sdk.md#collect) invocation on one MetricReader instance SHOULD NOT introduce side-effects to other MetricReader instances.

Multiple readers can be registered on a single MeterProvider (readers are appended to a list):

https://github.com/open-telemetry/opentelemetry-go/blob/cbc5890d9cba29c57a0c39dd27ed204e29d5370a/sdk/metric/config.go#L120-L130

Each reader results in an independent pipeline:
https://github.com/open-telemetry/opentelemetry-go/blob/cbc5890d9cba29c57a0c39dd27ed204e29d5370a/sdk/metric/pipeline.go#L481-L488

Invoking Collect on a reader only calls produce on its own pipeline.  Periodic:
https://github.com/open-telemetry/opentelemetry-go/blob/cbc5890d9cba29c57a0c39dd27ed204e29d5370a/sdk/metric/periodic_reader.go#L273
and Manual: https://github.com/open-telemetry/opentelemetry-go/blob/cbc5890d9cba29c57a0c39dd27ed204e29d5370a/sdk/metric/manual_reader.go#L148

produce only invokes callbacks and computes aggregations from the pipeline's own, independent callbacks and aggregations: https://github.com/open-telemetry/opentelemetry-go/blob/cbc5890d9cba29c57a0c39dd27ed204e29d5370a/sdk/metric/pipeline.go#L123-L179

**Comment by dashpole** [comment]
> The SDK MUST NOT allow a MetricReader instance to be registered on more than one MeterProvider instance.

We return this error when a reader is registered more than once (e.g. with different MeterProviders): https://github.com/open-telemetry/opentelemetry-go/blob/cbc5890d9cba29c57a0c39dd27ed204e29d5370a/sdk/metric/reader.go#L27

Periodic Reader impl: https://github.com/open-telemetry/opentelemetry-go/blob/cbc5890d9cba29c57a0c39dd27ed204e29d5370a/sdk/metric/periodic_reader.go#L188-L195

Manual Reader impl: https://github.com/open-telemetry/opentelemetry-go/blob/cbc5890d9cba29c57a0c39dd27ed204e29d5370a/sdk/metric/manual_reader.go#L57-L65

**Comment by dashpole** [comment]
> The SDK SHOULD provide a way to allow MetricReader to respond to [MeterProvider.ForceFlush](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/metrics/sdk.md#forceflush) and [MeterProvider.Shutdown](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/metrics/sdk.md#shutdown).

The ForceFlush and Shutdown signals of readers are aggregated when the MeterProvider is created: https://github.com/open-telemetry/opentelemetry-go/blob/cbc5890d9cba29c57a0c39dd27ed204e29d5370a/sdk/metric/config.go#L32-L43

https://github.com/open-telemetry/opentelemetry-go/blob/cbc5890d9cba29c57a0c39dd27ed204e29d5370a/sdk/metric/provider.go#L51-L58

And then are invoked when ForceFlush and Shutdown are invoked on the MeterProvider: https://github.com/open-telemetry/opentelemetry-go/blob/cbc5890d9cba29c57a0c39dd27ed204e29d5370a/sdk/metric/provider.go#L114-L118

https://github.com/open-telemetry/opentelemetry-go/blob/cbc5890d9cba29c57a0c39dd27ed204e29d5370a/sdk/metric/provider.go#L137-L151

**Comment by dashpole** [comment]
MetricReader Operations:

> Collect

https://github.com/open-telemetry/opentelemetry-go/blob/cbc5890d9cba29c57a0c39dd27ed204e29d5370a/sdk/metric/manual_reader.go#L129

https://github.com/open-telemetry/opentelemetry-go/blob/cbc5890d9cba29c57a0c39dd27ed204e29d5370a/sdk/metric/periodic_reader.go#L249

> Collects the metrics from the SDK and any registered [MetricProducers](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/metrics/sdk.md#metricproducer).

From SDK:

https://github.com/open-telemetry/opentelemetry-go/blob/cbc5890d9cba29c57a0c39dd27ed204e29d5370a/sdk/metric/manual_reader.go#L148

https://github.com/open-telemetry/opentelemetry-go/blob/cbc5890d9cba29c57a0c39dd27ed204e29d5370a/sdk/metric/periodic_reader.go#L273

From Producers:

https://github.com/open-telemetry/opentelemetry-go/blob/cbc5890d9cba29c57a0c39dd27ed204e29d5370a/sdk/metric/manual_reader.go#L153-L159

https://github.com/open-telemetry/opentelemetry-go/blob/cbc5890d9cba29c57a0c39dd27ed204e29d5370a/sdk/metric/periodic_reader.go#L278-L284

> Collect SHOULD provide a way to let the caller know whether it succeeded, failed or timed out.

Collect returns an error.  See signature above.

> When the Collect operation fails or times out on some of the instruments, the SDK MAY return successfully collected results and a failed reasons list to the caller.

We support partial results by aggregating errors and continuing on during callbacks that return errors: https://github.com/open-telemetry/opentelemetry-go/blob/cbc5890d9cba29c57a0c39dd27ed204e29d5370a/sdk/metric/pipeline.go#L130-L132

https://github.com/open-telemetry/opentelemetry-go/blob/cbc5890d9cba29c57a0c39dd27ed204e29d5370a/sdk/metric/pipeline.go#L142-L144

**Comment by dashpole** [comment]
> Shutdown

https://github.com/open-telemetry/opentelemetry-go/blob/cbc5890d9cba29c57a0c39dd27ed204e29d5370a/sdk/metric/reader.go#L91-L103

> Shutdown MUST be called only once for each MetricReader instance. After the call to Shutdown, subsequent invocations to Collect are not allowed. SDKs SHOULD return some failure for these calls, if possible.

In Shutdown(), readers store a shutdownProducer in the produer, which returns an error that is returned to the caller of Collect:
https://github.com/open-telemetry/opentelemetry-go/blob/cbc5890d9cba29c57a0c39dd27ed204e29d5370a/sdk/metric/manual_reader.go#L107-L110

https://github.com/open-telemetry/opentelemetry-go/blob/cbc5890d9cba29c57a0c39dd27ed204e29d5370a/sdk/metric/periodic_reader.go#L330-L333

> Shutdown SHOULD provide a way to let the caller know whether it succeeded, failed or timed out.

Shutdown returns an error.

> Shutdown SHOULD complete or abort within some timeout.

**Shutdown does not impose a timeout on collection or exporting of telemetry in the periodic reader**

It does accept a context, which allows users to easily place a timeout on collection or export.

**Comment by dashpole** [comment]
That is all for the MetricReader, MetricReader operations, Collect, and Shutdown sections.  The bolded text above are contentious, or are areas where we differ from the specification.  Our only differences occur in SHOULD sections.

**Comment by dashpole** [comment]
I think I misread the intention of this issue... If this is _only_ about verifying collect, see https://github.com/open-telemetry/opentelemetry-go/issues/3662#issuecomment-1646225911

I did not find any issues regarding the Collect function..
