### ISSUE TITLE
Verify compliant metric SDK specification implementation: MetricReader/Periodic exporting MetricReader

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#3664]
- [x] Identify all the normative requirements, recommendations, and options [the specification] defines as comments to this issue
- [x] Ensure the [current metric SDK implementation] is compliant with these normative requirements, recommendations, and options in those comments.

[the specification]: https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/metrics/sdk.md
[current metric SDK implementation]: https://pkg.go.dev/go.opentelemetry.io/otel/sdk/metric@v0.39.0

**Comment by dashpole** [comment]
> This is an implementation of the MetricReader 

We have a compile-time check to ensure PeriodicReader implements Reader:

https://github.com/open-telemetry/opentelemetry-go/blob/ab61991465d957db46e4f8a78b1dcf84546bdef8/sdk/metric/periodic_reader.go#L160-L161

> which collects metrics based on a user-configurable time interval and passes the metrics to the configured [Push Metric Exporter](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#push-metric-exporter).

The run() function collects and exports metrics on the user-configured interval:
https://github.com/open-telemetry/opentelemetry-go/blob/ab61991465d957db46e4f8a78b1dcf84546bdef8/sdk/metric/periodic_reader.go#L166-L186

**Comment by dashpole** [comment]
> Configurable parameters:

> exportIntervalMillis - the time interval in milliseconds between two consecutive exports. The default value is 60000 (milliseconds).

We support this configuration option:
https://github.com/open-telemetry/opentelemetry-go/blob/ab61991465d957db46e4f8a78b1dcf84546bdef8/sdk/metric/periodic_reader.go#L87-L95

Default matches the spec:
https://github.com/open-telemetry/opentelemetry-go/blob/ab61991465d957db46e4f8a78b1dcf84546bdef8/sdk/metric/periodic_reader.go#L34

> exportTimeoutMillis - how long the export can run before it is cancelled. The default value is 30000 (milliseconds).

We support this configuration option:
https://github.com/open-telemetry/opentelemetry-go/blob/ab61991465d957db46e4f8a78b1dcf84546bdef8/sdk/metric/periodic_reader.go#L69-L77

Default matches the spec:
https://github.com/open-telemetry/opentelemetry-go/blob/ab61991465d957db46e4f8a78b1dcf84546bdef8/sdk/metric/periodic_reader.go#L33

**Comment by dashpole** [comment]
> The reader's Collect() method may still be invoked by other callers.

Collect is safe to call concurrently, and is part of the public interface. There is nothing preventing users from calling Collect while the periodic reader is running.
https://github.com/open-telemetry/opentelemetry-go/blob/ab61991465d957db46e4f8a78b1dcf84546bdef8/sdk/metric/periodic_reader.go#L239-L249

**Comment by dashpole** [comment]
I believe those are all of the normative requirements.  I did not find any sections where we do not comply with the spec.

**Comment by pellared** [comment]
I double-checked. Closing.
