### ISSUE TITLE
Verify compliant metric SDK specification implementation: MetricProducer

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#3668]
- [x] Identify all the normative requirements, recommendations, and options [the specification] defines as comments to this issue
- [ ] Ensure the [current metric SDK implementation] is compliant with these normative requirements, recommendations, and options in those comments.

[the specification]: https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/metrics/sdk.md
[current metric SDK implementation]: https://pkg.go.dev/go.opentelemetry.io/otel/sdk/metric@v0.39.0

**Comment by MadVikingGod** [comment]
Requirements from reading the [Metric Producer](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#metricproducer) Section of the spec.

- `MetricProducer` is an open interface that can be implemented outside the SDK.
  > `MetricProducer` defines the interface which bridges to third-party metric sources MUST implement so they can be plugged into an OpenTelemetry `MetricReader` as a source of aggregated metric data. 
- > The SDK's in-memory state MAY implement the `MetricProducer` interface for convenience.
- > SDK authors MAY provide utility libraries to facilitate conversion between delta and cumulative temporalities.
- > If the batch of Metric points returned by Produce() includes a Resource, the `MetricProducer` MUST accept configuration for the Resource.
- The MetricProducer Interface must have the following defined:
  - `Produce`
    - > Produce MUST return a batch of Metric points.
    - > Produce does not have any required parameters... SDK authors MAY choose to add parameters
    - > Produce SHOULD provide a way to let the caller know whether it succeeded, failed or timed out.
    - > When the Produce operation fails, the MetricProducer MAY return successfully collected results and a failed reasons list to the caller.
    - > If a batch of Metric points can include `InstrumentationScope` information, Produce SHOULD include a single InstrumentationScope which identifies the `MetricProducer`.

**Comment by damemi** [comment]
@MrAlias can you assign this to me?

**Comment by damemi** [comment]
> Requirements from reading the [Metric Producer](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#metricproducer) Section of the spec.
> 
> * `MetricProducer` is an open interface that can be implemented outside the SDK.
>   > `MetricProducer` defines the interface which bridges to third-party metric sources MUST implement so they can be plugged into an OpenTelemetry `MetricReader` as a source of aggregated metric data.
> * > The SDK's in-memory state MAY implement the `MetricProducer` interface for convenience.

I didn't find any implementations of this in the in-memory state

> SDK authors MAY provide utility libraries to facilitate conversion between delta and cumulative temporalities.

Didn't see any

> If the batch of Metric points returned by Produce() includes a Resource, the `MetricProducer` MUST accept configuration for the Resource.

Produce() (ScopeMetrics) does not include a Resource

>The MetricProducer Interface must have the following defined:
>   * `Produce`

It does

>     
> Produce MUST return a batch of Metric points.

Produce() [returns []metricdata.ScopeMetrics](https://github.com/open-telemetry/opentelemetry-go/blob/e0852d609c4a4205d550e2de45afdbf80d43557b/sdk/metric/reader.go#L110).

> Produce does not have any required parameters... SDK authors MAY choose to add parameters

`Produce()` requires a Go context. It's unclear whether the specification means that Produce "MUST" not have any required parameters (and authors may add *optional* parameters), or if authors may add required parameters.

> Produce SHOULD provide a way to let the caller know whether it succeeded, failed or timed out.

Produce() returns a Go `error` (along with the batch of data points)

> When the Produce operation fails, the MetricProducer MAY return successfully collected results and a failed reasons list to the caller.

This is up to each Producer's implementation, but for example the [opencensus bridge](https://github.com/open-telemetry/opentelemetry-go/blob/c404a30b96f6117ac677c5e15119a4d724e2ab3e/bridge/opencensus/metric.go#L46) will return successful results and an aggregated error (from `internal.ConvertMetrics()`)

> If a batch of Metric points can include `InstrumentationScope` information, Produce SHOULD include a single InstrumentationScope which identifies the `MetricProducer`.

`ScopeMetrics` [includes a single `InstrumentationScope`](https://github.com/open-telemetry/opentelemetry-go/blob/c404a30b96f6117ac677c5e15119a4d724e2ab3e/sdk/metric/metricdata/data.go#L37)

---

I think the only action item from this would be to clarify the intent of `Produce does not have any required parameters... SDK authors MAY choose to add parameters`

**Comment by MrAlias** [comment]
The `MetricProducer` specification needs to be stabilized before we can release our implementation of it stabilly.

**Comment by MrAlias** [comment]
> I think the only action item from this would be to clarify the intent of `Produce does not have any required parameters... SDK authors MAY choose to add parameters`

@damemi do you plan to open a spec issue/PR for this?

**Comment by MrAlias** [comment]
> The `MetricProducer` specification needs to be stabilized before we can release our implementation of it stabilly.

https://github.com/open-telemetry/opentelemetry-specification/issues/3599

**Comment by MrAlias** [comment]
TODO:

- [ ] https://github.com/open-telemetry/opentelemetry-specification/issues/3599

**Comment by damemi** [comment]
> > I think the only action item from this would be to clarify the intent of `Produce does not have any required parameters... SDK authors MAY choose to add parameters`
> 
> @damemi do you plan to open a spec issue/PR for this?

Opened https://github.com/open-telemetry/opentelemetry-specification/issues/3601 for this question

**Comment by arminru** [comment]
Clarified that the required `context` parameter is fine: https://github.com/open-telemetry/opentelemetry-specification/commit/15df4606984e7c5f51e319aa39659b7815241588

**Comment by dashpole** [comment]
I believe this can be closed now.
