### ISSUE TITLE
Verify compliant metric SDK specification implementation: Defaults and configuration

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#3669]
- [x] Identify all the normative requirements, recommendations, and options [the specification] defines as comments to this issue
- [x] Ensure the [current metric SDK implementation] is compliant with these normative requirements, recommendations, and options in those comments.

[the specification]: https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/metrics/sdk.md
[current metric SDK implementation]: https://pkg.go.dev/go.opentelemetry.io/otel/sdk/metric@v0.39.0

**Comment by pellared** [comment]
> The SDK MUST provide configuration according to the [SDK environment variables](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/configuration/sdk-environment-variables.md) specification.

The spec says: 

> SDKs MAY choose to allow configuration via the environment variables in this specification, but are not required to.

Therefore, the most important thing is to check if there are no environment variable is marked as stable which is not defined in https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/configuration/sdk-environment-variables.md

From https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/configuration/sdk-environment-variables.md#metrics-sdk-configuration:

Following env vars are defined:

- `OTEL_METRICS_EXPORTER` (Stable) - not implemented, but can be later implemented in https://pkg.go.dev/go.opentelemetry.io/contrib/exporters/autoexport
- `OTEL_METRICS_EXEMPLAR_FILTER` (Experimental?) - not implemented. But I do not think it is required. More: https://github.com/open-telemetry/opentelemetry-go/issues/559
- `OTEL_METRIC_EXPORT_INTERVAL` (Stable) - implemented in [periodic reader](https://github.com/open-telemetry/opentelemetry-go/blob/sdk/metric/v0.39.0/sdk/metric/periodic_reader.go) as defined per spec
- `OTEL_METRIC_EXPORT_TIMEOUT` (Stable) - implemented in [periodic reader](https://github.com/open-telemetry/opentelemetry-go/blob/sdk/metric/v0.39.0/sdk/metric/periodic_reader.go) as defined per spec


I do not find any env vars that would make the validated https://pkg.go.dev/go.opentelemetry.io/otel/sdk/metric@v0.39.0 not compliant.

**Comment by pellared** [comment]
It looks like we comply with this fragment of the specification.

@MrAlias Can you please double-check and close if you agree with my verification?

**Comment by MrAlias** [comment]
LGTM
