### ISSUE TITLE
Verify compliant metric SDK specification implementation: Numerical limits handling

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#3670]
- [x] Identify all the normative requirements, recommendations, and options [the specification] defines as comments to this issue
- [x] Ensure the [current metric SDK implementation] is compliant with these normative requirements, recommendations, and options in those comments.

[the specification]: https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/metrics/sdk.md
[current metric SDK implementation]: https://pkg.go.dev/go.opentelemetry.io/otel/sdk/metric@v0.39.0

**Comment by pellared** [comment]
> The SDK MUST handle numerical limits in a graceful way according to [Error handling in OpenTelemetry](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/error-handling.md).

_TODO_

**Comment by pellared** [comment]
> If the SDK receives float/double values from [Instruments](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/metrics/api.md#instrument), it MUST handle all the possible values. For example, if the language runtime supports [IEEE 754](https://en.wikipedia.org/wiki/IEEE_754), the SDK needs to handle NaNs and Infinites.

_TODO_

**Comment by pellared** [comment]
> It is unspecified _how_ the SDK should handle the input limits. The SDK authors MAY leverage/follow the language runtime behavior for better performance, rather than perform a check on each value coming from the API.

_TODO_

**Comment by pellared** [comment]
> It is unspecified how the SDK should handle the output limits (e.g. integer overflow). The SDK authors MAY rely on the language runtime behavior as long as errors/exceptions are taken care of.

_TODO_

**Comment by pellared** [comment]
It looks like we comply with this fragment of the specification.

@MrAlias Can you please double-check and close if you agree with my verification?

**Comment by MrAlias** [comment]
LGTM
