### ISSUE TITLE
Generate the v1.18.0 semconv package

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#3701]
[Release v1.18.0](https://github.com/open-telemetry/opentelemetry-specification/releases/tag/v1.18.0)

We should look into a fix of attributes that use `*Otel*` in their names instead of `OTel`.

**Comment by Aneurysm9** [comment]
> We should look into a fix of attributes that use `*Otel*` in their names instead of `OTel`.

Can we just add it to the [list here](https://github.com/open-telemetry/opentelemetry-go-build-tools/blob/main/semconvgen/generator.go#L285)?

**Comment by MrAlias** [comment]
https://github.com/open-telemetry/opentelemetry-go-build-tools/pull/241

**Comment by MrAlias** [comment]
We should merge https://github.com/open-telemetry/opentelemetry-go/pull/3697 first.
