### ISSUE TITLE
README installations instructions fail

### ISSUE THREAD

**Issue by iredelmeier** [open-telemetry/opentelemetry-go#372]
Since the root package is currently tools-only (see #371), `go get -u go.opentelemetry.io/otel` fails with `build go.opentelemetry.io/otel: cannot load go.opentelemetry.io/otel: no Go source files`.

**Comment by jmacd** [comment]
Related: #257

**Comment by rghetia** [comment]
conclusion is to use alias as suggested in #371

**Comment by rghetia** [comment]
this is addressed in #476
