### ISSUE TITLE
The `otel` package implicitly requires Go >= 1.18

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#3723]
https://github.com/open-telemetry/opentelemetry-go/blob/441a173514a86cebb79abfe02da73953a6cdbad1/internal/attribute/attribute.go#L25-L45

### Proposal

Refactor that package to not use generics.

**Comment by Petrie** [comment]
You can assign this to me, thanks @MrAlias

**Comment by pellared** [comment]
nit: Shouldn't the name be changed to

```
The otel package implicitly requires Go >= 1.18
```

or

```
The otel package implicitly requires Go > 1.17
```

?

**Comment by ash2k** [comment]
Any explanation why not? Just curious.

I'm looking at some code that uses [`atomic.Value`](https://pkg.go.dev/sync/atomic#Value)+type casts. It could use [`atomic.Pointer`](https://pkg.go.dev/sync/atomic#Pointer) (added in Go 1.19) instead to avoid type casts, be more readable and type safe. If not, would be good to at document the decision somewhere in contributor docs.
