### ISSUE TITLE
Add opentelemetry collector/agent exporter for metrics

### ISSUE THREAD

**Issue by rghetia** [open-telemetry/opentelemetry-go#377]
Add exporter to export Metrics to Open-telemetry collector.
This is blocked on release of [open-telemetry/protocol](https://github.com/open-telemetry/opentelemetry-proto).

**Comment by jmacd** [comment]
(@MrAlias I'm glad to hear you're at work on this!)

**Comment by MrAlias** [comment]
I've got a rough draft to post as a PR for this (hopefully tomorrow after some cleanup), but it currently only supports the `Sum` and `MinMaxSumCount` aggregations. These are the default aggregation strategies for the simple selector, and compatible with the sketch and exact selectors as well. This seems like a decent start at least.

There is an issue with the transfer of data contained in `MinMaxSumCount`. The OTLP `Summary` does not have fields for `Min` or `Max`, rather it has a `Percentiles` field (much like prometheus. The rough draft I have together only sends the `Sum` and `Count` (existing fields in the OTLP `Summary`), but there is an incongruence.

I'm pretty sure there is an OTEP or spec issue to drop the `Min`/`Max` parts of the `MinMaxSumCount` aggregation type, so this would be inline with that. However, it seems like a PR to the proto library is needed to synchronize the proto definition with what the spec supports.

I'm interested in what others think of this approach and how to solve the incongruency.

**Comment by MrAlias** [comment]
Created https://github.com/open-telemetry/opentelemetry-proto/pull/122 to add a new data type that will support MinMaxSumCount transport.
