### ISSUE TITLE
Add SamplingHint to API package

### ISSUE THREAD

**Issue by elsesiy** [open-telemetry/opentelemetry-go#380]
As far as I can tell the current API/SDK are missing the changes proposed in [OTEP0006](https://github.com/open-telemetry/oteps/blob/master/text/0006-sampling.md) such as `SamplingHint` in the API package or the necessary adjustments in the SDK interface to produce `SamplingDecision`s.

Please let me know if I'm mistaken or this is not the process to keep track of OTEP implementation status in the language-specific repos, thanks!

**Comment by rghetia** [comment]
spec is not update for SamplingHint yet. There is an [issue](https://github.com/open-telemetry/opentelemetry-specification/issues/282) open in the spec repo.

**Comment by rghetia** [comment]
Sampling Hint is removed from the spec.
