### ISSUE TITLE
Non-Semver Friendly Changes in v1.14

### ISSUE THREAD

**Issue by steve-gray** [open-telemetry/opentelemetry-go#3815]
The removal of the unit package is causing downstream packages like:

- go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc

to fail as the unit object has been changed/removed. This is unexpected in a version that is going from v1.13 to v1.14. This is unexpected, and appears to disagree with VERSIONING.md in this project.

**Comment by MrAlias** [comment]
Please wait for the pending contrib release to address this.

Also, to be clear, the unit package is deprecated and it's modules version is v0.37.0 not v1.14.0.

**Comment by steve-gray** [comment]
Are we potentially doing something wrong this end? The docs indicate that go get -u will only step up minor versions and patch versions unless its a 0.x.y release. I suspect they're working off Github tags, just like pkg.dev - and so the 0.36/0.37 distinctions aren't ever being used by any tooling? Are we supposed to pull these package from somewhere else that that those tags explicitly?

Some follow-on questions:

- Is there an approximate timeline on the update?

- Is there a way to keep the old version temporarily in Go.mod without having to do all our dep updates by hand one by one (and eschewing go get -u ./...). Can we pull the packages from somewhere where these 0.36/0.37 tags are used? Then at least anything sensible on semver will know that 0.x to 0.y is a break-change risk.

**Comment by steve-gray** [comment]
It looks like the update is out, so we're back in action- thanks @MrAlias

It'd be good to understand what we've done wrong on the tooling front so we're protected in future. It's been generally fairly good the last year or so/first time I can recall a change like this causing us an issue. Could be luck though rather than anything else 😄

**Comment by MrAlias** [comment]
> It'd be good to understand what we've done wrong on the tooling front so we're protected in future. It's been generally fairly good the last year or so/first time I can recall a change like this causing us an issue. Could be luck though rather than anything else smile

I imagine it has just been luck. We have always had a delay between this repository and contrib and for unstable modules we have released breaking changes before.

You should be all set if you wait for the companion release of contrib. We try to release it as soon as we can.

> It looks like the update is out, so we're back in action- thanks @MrAlias 

Glad to hear it. I'm gonna close this issue as it seems done.
