### ISSUE TITLE
Add Logs Bridge API

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-go#3827]
- [x] #4809
- [x] #4907
- [x] #4908
- [x] #4909
- [x] #4910
- [x] #4911
- [x] #4912
- [x] #4913
- [x] #4914
- [x] #4915
- [x] #4916

**Comment by mattsains** [comment]
is there anything I can do to help?

**Comment by pellared** [comment]
From https://github.com/open-telemetry/opentelemetry-go/blob/d423bd4cf28f65bdcbd1b1d83d0f59c4388f37b0/README.md#L23-L24:

> - [2]: The Logs signal development is halted for this project while we stabilize the Metrics SDK.
   No Logs Pull Requests are currently being accepted.

You can help with existing TODO issues related to metrics or help addressing existing bugs.
