### ISSUE TITLE
Update go directive value in go.mod files to 1.19

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go#3839]
Shouldn't we bump Go to 1.19 in `go.mod` files per https://github.com/open-telemetry/opentelemetry-go/pull/3813?

**Comment by Anu-MT** [comment]
Hi, I would like to work on https://github.com/open-telemetry/opentelemetry-go/pull/3850 if its still open.

**Comment by MrAlias** [comment]
@Anu-MT it looks like #3850 is ready to merge. This should be closed shortly.
