### ISSUE TITLE
zPages: rpcz support

### ISSUE THREAD

**Issue by VineethReddy02** [open-telemetry/opentelemetry-go#386]
Feature Proposal from @SergeyKanzhelev 

zPages is a great practice many organizations and SRE uses for the last line of defence while troubleshooting application issues. zPages aggregate telemetry in-process in a memory buffer and allow to query this informaiton directly from the app. It will be great to design and implement zPages

See some info on zPages: https://opencensus.io/zpages/

Also features in SRE book.

 - [ ] Basic project set up.
    -   [ ] Create a separate project. Zipkin can be used as an example.
    -  [ ]  Implement TelemetryProcessor that will receive all span's creation/finish events.
    -  [ ]  Make sure you can configure processor to receive all spans
 - [ ] Basic zPage
      - [ ] Implement HttpListener (as in Prometheus package) that will return an empty html
      - [ ]  Hook up telemetry processor and this httpListener. As a prove that those are connected - write the current number of active spans and the "last seen" span information in html output.
 - [ ] Specification on zPage output
      - [ ] Take the zPage [implemented in OpenCensus](https://github.com/census-instrumentation/opencensus-java/blob/c960b19889de5e4a7b25f90919d28b066590d4f0/contrib/zpages/README.md) as a baseline.
      - [ ] Write down very basic specification on zPage output
- [ ] Iterate on zPage output. Update specs, implement it in Golang.
- [ ] Perf benchmarking.
     - [ ]  Benchmark individual zPage methods
     - [ ]  Benchmark zPage with the multiple simultaneous connections

**Comment by jmacd** [comment]
One of the useful things you can do with a z-page is link from one active request to an active, remote child request. This is a nice way to find deadlocks and hung requests. It calls for a specification of what z-pages can do and how to form links into a z-page if you know the endpoint you are talking to.

**Comment by MrAlias** [comment]
Closed with https://github.com/open-telemetry/opentelemetry-go-contrib/pull/894

**Comment by burdiyan** [comment]
AFAIK, this only implements tracez, but this issue is about supporting rpcz.
