### ISSUE TITLE
Custom histogram boundaries override each other

### ISSUE THREAD

**Issue by fracasula** [open-telemetry/opentelemetry-go#3888]
### Description

I'm trying to define two views for my histograms. One view for all histograms and then a specific one for a histogram with a given name.

This means that if I do this with my library...

```go
setup(
	WithDefaultHistogramBucketBoundaries("meter-1", []float64{10, 20, 30}),
	WithHistogramBucketBoundaries("bar", "meter-1", []float64{40, 50, 60}),
)
```

...then all histograms initialized with `meter-1` should get the `[10, 20, 30]` buckets, but if a histogram with the `bar` name is initialized with `meter-1` then it should get the `[40, 50, 60]` buckets.

Unfortunately due to...

```go
// RETURNS TRUE FOR BOTH CASES
func (i Instrument) matchesName(other Instrument) bool {
	return i.Name == "" || i.Name == other.Name
}
```

...both criterias match but the first one seem to prevail.

How can I have a default view that applies to all histograms and then a specific one for `bar`?

[This](https://github.com/rudderlabs/rudder-go-kit/blob/feat.otelBuckets/stats/internal/otel/options.go#L93) is where I define the view for all my histograms.

And [this](https://github.com/rudderlabs/rudder-go-kit/blob/feat.otelBuckets/stats/internal/otel/options.go#L116) is where I define the view for histograms of a specific name.

### Environment

- OS: [Linux]
- Architecture: [e.g. x86]
- Go Version: [1.20]
- opentelemetry-go version: https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.14.0

### Steps To Reproduce

Run `TestHistogramBuckets` [here](https://github.com/rudderlabs/rudder-go-kit/blob/feat.otelBuckets/stats/internal/otel/otel_test.go#L115). You should see that the `custom does not override default` subtest fails because the `bar` histogram is not getting the expected `[40, 50, 60]` boundaries.

### Expected behavior

I would expect the more lax criteria/view to be overridden by the more specific one.

**Comment by MrAlias** [comment]
What about setting the default buckets you want with an `AggregationSelector`?

https://pkg.go.dev/go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc#WithAggregationSelector

**Comment by fracasula** [comment]
> What about setting the default buckets you want with an `AggregationSelector`?
> 
> https://pkg.go.dev/go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc#WithAggregationSelector

Yes, that would work, thanks @MrAlias :+1:

**Comment by fracasula** [comment]
Your suggestion seems to work with `otlpmetricgrpc.WithAggregationSelector` but it doesn't seem to work when using a Prometheus exporter. 

Can you please confirm @MrAlias ?

This is what I tried. For now I'm hard-coding the buckets to be `[]float64{10, 20, 30}` just to test it. I tried to pass it both as an exporter option and as a view or just one or the other but I always get the default buckets:

```go
func (m *Manager) buildPrometheusMeterProvider(c config, res *resource.Resource) (*sdkmetric.MeterProvider, error) {
	exporterOptions := []prometheus.Option{
		prometheus.WithRegisterer(c.meterProviderConfig.prometheusRegisterer),
	}
	if len(c.meterProviderConfig.histogramBoundaries) > 0 {
		exporterOptions = append(exporterOptions,
			prometheus.WithAggregationSelector(func(ik sdkmetric.InstrumentKind) aggregation.Aggregation {
				switch ik {
				case sdkmetric.InstrumentKindCounter, sdkmetric.InstrumentKindUpDownCounter,
					sdkmetric.InstrumentKindObservableCounter, sdkmetric.InstrumentKindObservableUpDownCounter:
					return aggregation.Sum{}
				case sdkmetric.InstrumentKindObservableGauge:
					return aggregation.LastValue{}
				case sdkmetric.InstrumentKindHistogram:
					return aggregation.ExplicitBucketHistogram{
						Boundaries: []float64{10, 20, 30},
					}
				}
				panic("unknown instrument kind")
			}),
		)
		c.meterProviderConfig.views = append(c.meterProviderConfig.views, sdkmetric.NewView(
			sdkmetric.Instrument{},
			sdkmetric.Stream{
				Aggregation: aggregation.ExplicitBucketHistogram{
					Boundaries: []float64{10, 20, 30},
				},
			},
		))
	}
	exp, err := prometheus.New(exporterOptions...)
	if err != nil {
		return nil, fmt.Errorf("prometheus: failed to create metric exporter: %w", err)
	}
	return sdkmetric.NewMeterProvider(
		sdkmetric.WithResource(res),
		sdkmetric.WithReader(exp),
		sdkmetric.WithView(c.meterProviderConfig.views...),
	), nil
}
```

Which gives:

```
=== RUN   TestPrometheusExporter
    otel_test.go:181: Bucket 0: cumulative_count:0 upper_bound:0 
    otel_test.go:181: Bucket 1: cumulative_count:0 upper_bound:5 
    otel_test.go:181: Bucket 2: cumulative_count:0 upper_bound:10 
    otel_test.go:181: Bucket 3: cumulative_count:1 upper_bound:25 
    otel_test.go:181: Bucket 4: cumulative_count:1 upper_bound:50 
    otel_test.go:181: Bucket 5: cumulative_count:1 upper_bound:75 
    otel_test.go:181: Bucket 6: cumulative_count:1 upper_bound:100 
    otel_test.go:181: Bucket 7: cumulative_count:1 upper_bound:250 
    otel_test.go:181: Bucket 8: cumulative_count:1 upper_bound:500 
    otel_test.go:181: Bucket 9: cumulative_count:1 upper_bound:750 
    otel_test.go:181: Bucket 10: cumulative_count:1 upper_bound:1000 
    otel_test.go:181: Bucket 11: cumulative_count:1 upper_bound:2500 
    otel_test.go:181: Bucket 12: cumulative_count:1 upper_bound:5000 
    otel_test.go:181: Bucket 13: cumulative_count:1 upper_bound:7500 
    otel_test.go:181: Bucket 14: cumulative_count:1 upper_bound:10000 
    otel_test.go:181: Bucket 15: cumulative_count:1 upper_bound:inf 
```
