### ISSUE TITLE
Upgrading Opentelemetry may cause metric data to no longer be displayed.

### ISSUE THREAD

**Issue by 1046102779** [open-telemetry/opentelemetry-go#3897]
### Description

In the past two days, I have been upgrading the Opentelemetry-Go that all services rely on, including metrics and tracing. At the same time, Opentelemetry-Collector was also upgraded, and the exporter is Prometheus; I found that after all service has been running for a period of time, it will no longer display data in grafana dashboard. Several services are like this, but grafana is normal after all services is restarted. Then it happened again after another day of running.

### Environment

- OS: centos8
- Architecture: x86
- Go Version: 1.19
- older opentelemetry-go version: v1.7.0
- older opentelemtry-go version: v0.52.0
- opentelemetry-go version: v1.14.0
- opentelemetry-collector version: v0.73.0

### See error

**now: 10:06**

#### privateassist
<img width="1594" alt="image" src="https://user-images.githubusercontent.com/20457624/225793522-3d835121-e599-43a7-a782-6a76cde89046.png">

#### mqlog
<img width="805" alt="image" src="https://user-images.githubusercontent.com/20457624/225793599-a7ba1c65-c3a4-4874-b12e-794dcc276c9c.png">

**Comment by 1046102779** [comment]
I use Opentelemetry `otlpmetrichttp` to export metrics to collector, and then through exporter report to prometheus. configuration as follow:

```yaml
exporters:
  prometheus:
    endpoint: "0.0.0.0:9091"
    send_timestamps: true
    metric_expiration: "180m"
    resource_to_telemetry_conversion:
      enabled: true
```

How to debug the collector? See if there are new related service metrics in it.

## Service A----PrivateAssist
Problem: **No metrics.**

<img width="1705" alt="image" src="https://user-images.githubusercontent.com/20457624/226227360-4ccac7c6-cec0-43b6-9bb8-863e4e1bda76.png">

## Service B----mqlog
Problem 1: **No metrics between 18:00~00:00**
Problem 2: **soaring at 00:00**
<img width="1655" alt="image" src="https://user-images.githubusercontent.com/20457624/226227445-a8c38675-7905-4c84-a756-5cf9edc55813.png">

## Service C----aitokens 
**Normal**
<img width="1622" alt="image" src="https://user-images.githubusercontent.com/20457624/226227705-4d5b47e2-d215-49ea-9f0b-d6d221aa3741.png">

## Service D----qqchannel-gateway
**Normal**
<img width="1634" alt="image" src="https://user-images.githubusercontent.com/20457624/226227778-2959e210-63bd-4e3c-9133-ce584a354afa.png">

### Service E---sqqgroup
**Normal**
<img width="1669" alt="image" src="https://user-images.githubusercontent.com/20457624/226227827-7bb6a6ef-f832-4065-8ac0-89869748b68f.png">

**Comment by pellared** [comment]
> At the same time, Opentelemetry-Collector was also upgraded

How do you know that is not an issue with Opentelemetry-Collector? 😉 

> How to debug the collector? See if there are new related service metrics in it.

The easiest way is to use [the `logging` exporter](https://github.com/open-telemetry/opentelemetry-collector/blob/v0.73.0/exporter/loggingexporter/README.md)

**Comment by dmathieu** [comment]
Additionnally, I would say that raw data would be more useful than graphs in grafana.
What does the actual metrics endpoint look like after a restart? Can you see the actual issue in the emitted metrics data?

**Comment by 1046102779** [comment]
> Additionnally, I would say that raw data would be more useful than graphs in grafana. What does the actual metrics endpoint look like after a restart? Can you see the actual issue in the emitted metrics data?

I think about how to get the metrics reported by `opentelemetry-go` sdk.

**Comment by pellared** [comment]
I hope that the OTel Demo can help you achieving your goal: https://opentelemetry.io/docs/demo/
