### ISSUE TITLE
User-provided attributes unavailable in SamplingParameters

### ISSUE THREAD

**Issue by cartermp** [open-telemetry/opentelemetry-go#3898]
### Description

User-provided attributes seem unavailable in SamplingParameters. The attributes created from instrumentation libraries do appear, though. So for example, spans created from net/http instrumentation have attributes available, but not attributes on a span I create or that I add to the instrumentation library-created span.

### Environment

go version go1.20.2 linux/amd64

Latest otel-go version: https://github.com/cartermp/otel-lang-samples/blob/main/go/go.mod#L6-L12

### Steps To Reproduce

Repro:

* This code is a silly sampler that just prints attributes, but demonstrates the issue: https://github.com/cartermp/otel-lang-samples/blob/main/go/deterministic_sampler.go#L28-L40
* You can run the code as-is in a codespace or gitpod (`go build` and `./go-otel-samples`) and verify that only attributes from `net/http` instrumentation are prinited
* If I send these traces to Honeycomb, all spans are present and have the attributes you'd expect from: https://github.com/cartermp/otel-lang-samples/blob/main/go/main.go#L67-L83

### Expected behavior

I expect to have all attributes on all spans available.

**Comment by MrAlias** [comment]
Is the issue that the sampling parameters don't contain the attributes set on a span after its creation?

**Comment by cartermp** [comment]
Ah, yes, it seems if I create a span with attributes using `trace.WithAttributes` it works:

```go
_, span := tracer.Start(ctx, "fib", trace.WithAttributes(attribute.Bool("flag", false), attribute.String("name", "bagheera")))
```

yields:

```
{flag {1 0  <nil>}}
{name {4 0 bagheera <nil>}}
```

in stdout.

But for any I set with `span.SetAttributes` they won't be available.

**Comment by MrAlias** [comment]
Right, this is because sampling decisions are made during the span creation. This is part of the specification: https://github.com/open-telemetry/opentelemetry-specification/blob/4fa8a0dcfe8b3f8413f8626067c40fca2c46613d/specification/trace/sdk.md#sdk-span-creation

**Comment by cartermp** [comment]
I see, thanks! Blegh, I guess this means these kinds of decisions either have to be done in a tail sampler or some other external head sampler that works on exported spans.
