### ISSUE TITLE
Use `cache-dependency-path` in `actions/setup-go`

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go#3911]
With `actions/setup-go` updated to `v4` the caching is enabled by default. We should consider setting `cache-dependency-path: '**/go.sum'`. However, we need to ensure on a fork what is time diff benefit (if any).

_Originally posted by @pellared in https://github.com/open-telemetry/opentelemetry-go/issues/3901#issuecomment-1476032135_

**Comment by Tijmen34** [comment]
Hey, I'd like to do test the time benefit of this if possible.

**Comment by Tijmen34** [comment]
@MrAlias comparing current runs to new runs using cache-dependency-path, most notable benefit is MacOS compatibility test runs. Overall, adding this specifically does not give a lot of benefit. You could only change the caching of MacOS for example.

[Standard run](https://github.com/open-telemetry/opentelemetry-go/actions/runs/4544326538)

[Forked run](https://github.com/Tijmen34/opentelemetry-go/actions/runs/4535391350)

**Comment by ashutosh887** [comment]
@pellared @Tijmen34 
Please assign me to work on this issue

**Comment by dmathieu** [comment]
Is there really any work needed? It seems @Tijmen34's test showed this has very little impact.

**Comment by Tijmen34** [comment]
I actually do see some value in adding this to improve the speed of MacOS compatibility tests. It is however up for debate.

**Comment by pellared** [comment]
@Tijmen34 I really like this commit: https://github.com/Tijmen34/opentelemetry-go/commit/22221455677144d26173711552c314e4206c157c

1. It is simpler
2. It is a little faster (for sure not worse)
3. It has been recently showcased in https://github.com/mvdan/github-actions-golang/ per https://github.com/mvdan/github-actions-golang/pull/27

**Comment by Tijmen34** [comment]
> @Tijmen34 I really like this commit: [Tijmen34@2222145](https://github.com/Tijmen34/opentelemetry-go/commit/22221455677144d26173711552c314e4206c157c)
> 
>     1. It is simpler
> 
>     2. It is a little faster (for sure not worse)
> 
>     3. It has been recently showcased in https://github.com/mvdan/github-actions-golang/ per [Update setup-go mvdan/github-actions-golang#27](https://github.com/mvdan/github-actions-golang/pull/27)
> 
> 
> Feel free to open a PR 😉

Thanks, great to hear. PR has been opened, very happy that I have been able to contribute. 😄

**Comment by pellared** [comment]
Fixed in https://github.com/open-telemetry/opentelemetry-go/pull/4074
