### ISSUE TITLE
Allow modifing the baggage without starting a new span

### ISSUE THREAD

**Issue by ic2hrmk** [open-telemetry/opentelemetry-go#3915]
### Problem Statement

Hello, I'm implementing a middleware that attaches a Transaction ID to each request received by the HTTP server. This transaction ID would be then returned to the end user as a header. The initial (root) span is created by the [Gin OTEL middleware](go.opentelemetry.io/contrib/instrumentation/github.com/gin-gonic/gin/otelgin), so it's guaranteed to have the span already initialized for every context. 

Since this context is propagated all through the whole microservice, it makes sense to add a custom member to the `otel.Baggage` holding this value.

The thing is, in all examples, the baggage propagation is only being done by starting [a new span](https://github.com/open-telemetry/opentelemetry-go/blob/main/example/namedtracer/main.go#L73):
~~~go
        m0, _ := baggage.NewMember(string(fooKey), "foo1")
	m1, _ := baggage.NewMember(string(barKey), "bar1")
	b, _ := baggage.New(m0, m1)
	ctx = baggage.ContextWithBaggage(ctx, b)

	var span trace.Span
	ctx, span = tracer.Start(ctx, "operation")
	defer span.End()
~~~

Technically, there is no operation is started, so there is no need to have a new span; creating a new span on the middleware will only bloat the stack call on the Jaeger UI.

Adding this transaction ID as an attribute to the current span will not resolve the issue either because it won't be propagated to the children spans.

### Request

Allow modifying the baggage for the current trace without initializing a new span.

**Comment by Aneurysm9** [comment]
In addition to what @MrAlias has said, the span and the baggage are stored in the same context but with different keys.  Changing the baggage in a context with `baggage.ContextWithBaggage()` doesn't change the span in the context, if one exists.  As long as the changed context is used for outward propagation then the baggage can be changed at any time during a span's lifecycle.

**Comment by ic2hrmk** [comment]
@MrAlias, sounds good. Tbh, I didn't expect it to be immutable at first. I had an assumption that some of the attributes could be resolved and added to baggage even for the current span (not span attributes itself!), but now that's clear to me. Thank you for the prompt response
