### ISSUE TITLE
Use `atomic.Pointer` instead of `atomic.Value`

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go#3918]
I'm looking at some code that uses [`atomic.Value`](https://pkg.go.dev/sync/atomic#Value)+type casts. It could use [`atomic.Pointer`](https://pkg.go.dev/sync/atomic#Pointer) (added in Go 1.19) instead to avoid type casts, be more readable and type safe. If not, would be good to at document the decision somewhere in contributor docs.

_Originally posted by @ash2k in https://github.com/open-telemetry/opentelemetry-go/issues/3723#issuecomment-1479222792_

**Comment by MrAlias** [comment]
What else needs to be done for this issue?

**Comment by dmathieu** [comment]
Closing this, as per #3926, we won't be switching every other occurence of `atomic.Value` to `atomic.Pointer`, due to the low impact this has.
