### ISSUE TITLE
OTEL javaagent way: Tracing request body and response body

### ISSUE THREAD

**Issue by KamJohn** [open-telemetry/opentelemetry-go#3930]
### Problem Statement

I just wanna known that how to tracing my web request/response body.i am using OTEL autoconfiguration agent in springboot app.

**Comment by dmathieu** [comment]
Spring Boot is a java framework.
You opened this issue on the Golang SDK. You may want to ask this as a discussion on the java SDK, or on stackoverflow.

**Comment by KamJohn** [comment]
> 

OMG...i didnt enven noticed that  so sorry for that
