### ISSUE TITLE
`otel.Version()` is used in across modules

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go#3946]
The usage of `otel.Version()` in other modules then the API can cause reporting improper version of other components.

For instance, if one use the `1.2.0` version of the API, but `1.0.0` of the SDK, the version in the resources would be reported as `1.2.0` (instead of `1.0.0`).

This is "kind of" related to https://github.com/open-telemetry/opentelemetry-go/issues/3846

**Comment by MrAlias** [comment]
https://github.com/open-telemetry/opentelemetry-go/blob/63a0f51c2daf36e046fa216acc652a93a1c44a10/sdk/resource/builtin.go#L65

**Comment by remychantenay** [comment]
I believe we can close this issue, WDYT @pellared ?
