### ISSUE TITLE
[OpenTracing Bridge] Add methods to expose TraceID and SpanID from bridgeSpanContext

### ISSUE THREAD

**Issue by ChenX1993** [open-telemetry/opentelemetry-go#3954]
### Problem Statement
Hi, 
Similar to this issue: https://github.com/open-telemetry/opentelemetry-go/issues/3532, add methods to get TraceID and SpanID.
We need to get those info for some use case like contextual logging with trace info.

### Proposed Solution

Similar to this PR, add two additional methods for TraceID and SpanID.

**Comment by Kaushal28** [comment]
Hi, can I pick this up?
