### ISSUE TITLE
Add `go.work` file

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go#3964]
[Go 1.18 release](https://go.dev/doc/go1.18) introduced Go Workspaces; some references:
- https://go.dev/doc/tutorial/workspaces
- https://go.dev/blog/get-familiar-with-workspaces
- https://go.dev/ref/mod#workspaces

I propose to add a [`go.work` file](https://go.dev/ref/mod#go-work-file). The main reason is that I believe some of the contributors are using [`gopls`](https://github.com/golang/tools/tree/master/gopls) or/and [VSCode](https://code.visualstudio.com/docs/languages/go)

I propose to add only the `go.work` file for convivence.  We would still need to have the `replace` in `go.mod` files as:

1. we need to properly define all `require` of given module (we are not publishing modules so we need to define all dependencies)
2. all our existing automation does not rely on Go workspaces and also we should not force to use it. E.g. it is sometimes more convenient to just open the editor for a single module.

Probably the cleanest way would be to automate it in [`crosslink`](https://github.com/open-telemetry/opentelemetry-go-build-tools/tree/main/crosslink).

Even the proposal is not accepted then I would like to at least add `go.work` to `.gitignore`. I am doing it as the first step as it should not harm anybody.

**Comment by dmathieu** [comment]
Can this issue be closed, since `go.work` has been added to gitignore?

**Comment by MadVikingGod** [comment]
It should also be noted that both the `go.work`, and the replace directives are only for our development; neither are respected when this code is used as a library[^1].  

I personally would rather have a `go.work` that includes all the current modules.


[^1]: from https://go.dev/ref/mod#go-mod-file-replace: replace directives only apply in the main module’s go.mod file and are ignored in other modules.
