### ISSUE TITLE
The es index is too big created by jaeger

### ISSUE THREAD

**Issue by yunduansing** [open-telemetry/opentelemetry-go#3978]
### Description

**All micro services create only one es index everyday and is too big (200GB+ each index)，how to change it ?**

### Environment

- Architecture: [e.g. x86, i386]
- Go Version: [e.g. 1.15] 1.18
- opentelemetry-go version: [e.g. v0.14.0, 3c7face] v1.1.0

### Steps To Reproduce

exp, err := jaeger.New(jaeger.WithCollectorEndpoint(jaeger.WithEndpoint(url)))
			if err != nil {
				applog.Error("jaeger init fail:", err.Error())
				return
			}
			otel.SetTracerProvider(tracesdk.NewTracerProvider(
				// Always be sure to batch in production.
				tracesdk.WithBatcher(exp, tracesdk.WithBatchTimeout(time.Second)),
				// Record information about this application in an Resource.
				tracesdk.WithResource(resource.NewWithAttributes(
					semconv.SchemaURL,
					semconv.ServiceNameKey.String(name),
				)),
			))

### Expected behavior

**Hope the es index size could increases slowly or one index per service **

**Comment by dmathieu** [comment]
This looks like a jaeger issue, not an opentelemetry one.
