### ISSUE TITLE
The embedded package name will likely collide when we add one to `otel/trace`

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#3981]
Possibly rename to ...

- `membed`
- `metricembed` 
- `mbed`

**Comment by MrAlias** [comment]
also, maybe use `private` instead of `embed`

**Comment by MrAlias** [comment]
Would be worth adding a comment for API users what the embedded type is.

**Comment by pellared** [comment]
I prefer having `embed` in the name. `private` suggest that nobody should use it (it feels even more strict than `internal`.

**Comment by MrAlias** [comment]
> Could you please give an example?

If an implementation builds an SDK that implements both tracing and metrics and imports both the `embedded` packages.

**Comment by pellared** [comment]
Personally, I think that the existing `embedded` name is OK.
I sometimes find that API and SDK package name collision annoying, but here I think it would be an issue only if someone would like to implement both trace and metrics API in one package.

**Comment by MadVikingGod** [comment]
I don't see a need to really change this.  The only time they will collide is if you are creating both metric and trace types in the same file.  And if this does happen the author can rename the import.

**Comment by MrAlias** [comment]
The potential for import name conflict is less than between the API and SDK imports (i.e. `otel/trace` and `otel/sdk/trace`). Given the existing precedence, closing.
