### ISSUE TITLE
attribute.Set when returned as non-pointer, doesn't allow calling almost any function

### ISSUE THREAD

**Issue by RangelReale** [open-telemetry/opentelemetry-go#4045]
### Description

When `attribute.Set` is a return value from a function, like `TracerConfig.InstrumentationAttributes() attribute.Set`, almost no method can be called, as they require a pointer receiver.

### Environment

- OS: Windows 10
- Architecture: x86
- Go Version: 1.20
- opentelemetry-go version: [e.g. v0.15.0]

### Steps To Reproduce

```go
	c := trace.NewTracerConfig(opts...)
	attrIter := c.InstrumentationAttributes().Iter()
	for attrIter.Next() {

	}
```

```
cannot call pointer method Iter on "go.opentelemetry.io/otel/attribute".Set
```

This works:

```go
	c := trace.NewTracerConfig(opts...)
	attributes := c.InstrumentationAttributes()
	attrIter := attributes.Iter()
	for attrIter.Next() {

	}
```

### Expected behavior

We shouldn't need to introduce a new local variable just for iterating the attributes.

**Comment by MrAlias** [comment]
Changing the method signature of `InstrumentationAttributes` to return `*attribute.Set` will be a backwards incompatible change. It is not something we can do for the stable package.

If this issues is mean to propose a solution with type of change, we cannot accept it and it should be closed as "won't fix".

**Comment by RangelReale** [comment]
Maybe `func (l *Set) Iter() Iterator` could be a non-pointer receiver? This way it could work both with pointers and non-pointers.

**Comment by MrAlias** [comment]
> Maybe `func (l *Set) Iter() Iterator` could be a non-pointer receiver? This way it could work both with pointers and non-pointers.

This will also change the method signature of a stably released type. It would also violate our project stability guarantees.
