### ISSUE TITLE
How can I disable the JSON log printing?

### ISSUE THREAD

**Issue by bruce601080102** [open-telemetry/opentelemetry-go#4071]
I would like to ask how to disable the automatic printing of JSON that appears when using span.End(). 

example:
Now listening on: http://0.0.0.0
Application started. Press CTRL+C to shut down.
{
        "Name": "Hello World11",
        "SpanContext": {
                "TraceID": "4cb0e7c67d217dee42855c08bfefd197",
                "SpanID": "69183910b023cc6b",
                "TraceFlags": "01",
                "TraceState": "",
                "Remote": false
        },
        "Parent": {
                "TraceID": "00000000000000000000000000000000",
                "SpanID": "0000000000000000",
                "TraceFlags": "00",
                "TraceState": "",
                "Remote": false
        },
        "SpanKind": 1,
        "StartTime": "2023-05-07T03:29:27.719470845Z",
        "EndTime": "2023-05-07T03:29:27.719477001Z",

**Comment by rogerogers** [comment]
Did you use the stdout exporter?

**Comment by bruce601080102** [comment]
Thanks, the problem was fixed after commenting out the stdout.
