### ISSUE TITLE
A sample/example as how to use Summaries

### ISSUE THREAD

**Issue by SamYuan1990** [open-telemetry/opentelemetry-go#4088]
### Problem Statement

A clear and concise description of what the problem is.
Ex. I'm always frustrated when I want to use Summaries ref https://opentelemetry.io/docs/specs/otel/compatibility/prometheus_and_openmetrics/#summaries but found https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/data-model.md#summary-legacy

### Proposed Solution

I am confused as can I use Summaries? how can I use it? if not, any alteratives?

#### Alternatives

n/A?

#### Prior Art

A clear and concise list of any similar and existing solutions from other projects that provide context to possible solutions.
n/A?

### Additional Context

n/A?

**Comment by dashpole** [comment]
You cannot use summaries with the OpenTelemetry API, and I don't believe there is interest in adding API surface to include summaries. It would need to be added to the specification in order for us to support it in this repository.

We recommend using a Histogram instrument instead, e.g. with Float64Histogram():

https://github.com/open-telemetry/opentelemetry-go/blob/1e1cc901a561d44b9e22f39a3d8f27c08232f897/metric/meter.go#L117

If you _really_ want a summary, it will be possible for bridges, such as the [OpenCensus bridge](https://github.com/open-telemetry/opentelemetry-go/tree/main/bridge/opencensus) or [Prometheus bridge](https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/bridges/prometheus) to produce summary data after https://github.com/open-telemetry/opentelemetry-go/pull/4622.  This means will eventually be possible to use the prometheus client_golang to [create a Summary](https://github.com/prometheus/client_golang/blob/13a208d0b30cd458d191f23b2987d863c7bec45b/prometheus/summary.go#L182), and add it to metrics exported by OpenTelemetry using the Prometheus bridge.

**Comment by dashpole** [comment]
Closing as not planned.  I'm happy to answer further questions, but I don't think the OTel Go API is going to support summaries.
