### ISSUE TITLE
Add experimental histogram advice API

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#4094]
Specification PR: https://github.com/open-telemetry/opentelemetry-specification/pull/3216

**Comment by codeboten** [comment]
I believe this would solve https://github.com/open-telemetry/opentelemetry-go/issues/3826

**Comment by MrAlias** [comment]
Prototype: https://github.com/open-telemetry/opentelemetry-go/pull/4341

**Comment by dashpole** [comment]
@MrAlias @MadVikingGod Should we include this in the next (GA) release now that the specification is stable?  It seems like one of the most requested features from users, and would be great to have if there are no objections.

**Comment by MrAlias** [comment]
> @MrAlias @MadVikingGod Should we include this in the next (GA) release now that the specification is stable? It seems like one of the most requested features from users, and would be great to have if there are no objections.

I think adding it in v1.20.0 sounds good to me. The RC for 1.19.0 has already been released. Adding this event API to that release would mean the SDK needs to be updated to support it. Given that is a major change worth a minor version release I don't think we can add it to an RC. But I do think the next minor release should be targeted for this :+1: .

**Comment by dashpole** [comment]
We can start working on this now, right?  Or do we need to wait until the after the SDK has been released?

**Comment by MrAlias** [comment]
> We can start working on this now, right? Or do we need to wait until the after the SDK has been released?

As long as we don't merge something to main until we make the next release, that sounds good to me. :+1:

**Comment by dashpole** [comment]
I'll just wait in that case
