### ISSUE TITLE
Allow SpanContext to be provided when starting a Span

### ISSUE THREAD

**Issue by nicktrav** [open-telemetry/opentelemetry-go#411]
I have a potential use-case where a process will be responsible for accepting incoming span payloads (could be in multiple wire formats) and then shipping them to various locations (initially Stackdriver) via one or more exporters.

Given that the incoming span payloads are fully formed, I'd like to be able to preserve the existing `SpanContext` when creating a new `Span` instance. The current implementation in `sdk/trace/span.go` always generates one for us:
https://github.com/open-telemetry/opentelemetry-go/blob/b80b336eb83d6765db23288d459c596669b10f02/sdk/trace/span.go#L255-L259

I'd like to propose allowing an explicit `SpanContext` to be set, using something like a `StartOption` (e.g. something like `func WithSpanContext(c SpanContext) StartOption`).

**Comment by rghetia** [comment]
@nicktrav I don't fully understand your use case. Is the goal to extended the same span across two different process? What do you mean by `span payloads are fully formed`?

**Comment by nicktrav** [comment]
@rghetia The use case is a process that aggregates telemetry information and exports it to a tracing backend. I say "fully formed" in the sense that all the process has to do is take the span data coming in "as is" and send it on its way. To do this, we need some way of creating Spans with an explicit context, rather than generating new trace / span IDs, as is done here:
https://github.com/open-telemetry/opentelemetry-go/blob/b80b336eb83d6765db23288d459c596669b10f02/sdk/trace/span.go#L255-L259

The specific use-case is [Istio's Mixer component](https://istio.io/docs/concepts/what-is-istio/#observability) (I'm looking into what it would take to use open-telemetry rather than open-census). There's a gRPC service that's exposed that accepts span payloads in the form of protobuf bytes sent from remote Envoy proxy processes. Mixer unpacks, aggregates and filters these span payloads before pushing it into a backend.

You can see how this is happening here:
https://github.com/istio/istio/blob/00fe1c296be31d9ff4ac2eefe3c876b92b109ce3/mixer/pkg/adapter/opencensus/trace.go#L68

**Comment by rghetia** [comment]
> There's a gRPC service that's exposed that accepts span payloads in the form of protobuf bytes sent from remote Envoy proxy processes. Mixer unpacks, aggregates and filters these span payloads before pushing it into a backend.

This sounds similar to [otel-collector](https://github.com/open-telemetry/opentelemetry-collector). It allows to receive spans, processes it and then exports it to one or more backend.

**Comment by rghetia** [comment]
Closing this as it is not part of the specification.
