### ISSUE TITLE
Stable Metrics API missing OTLP exporter

### ISSUE THREAD

**Issue by JobberRT** [open-telemetry/opentelemetry-go#4132]
#### What I want to achieve
1. Using `trace.Tracer` and `metrics.Meter` to record tracing/metrics data, and implement `Console`(for debug)/`HTTP`/`GRPC` exporter for both.
2. Send data to `OTEL-Collector`
3. Using `OTEL-Collector's Exporter` to send data to different backend(prometheus/jaeger)
4. Using `Grafana` to visualize the data

#### What problem I met
It seems that metrics api doesn't provide a OTLP exporter(or anything else), only `stdoutmetric.exporter` which prints data to stdout.

I see in `otel/exporters` there's two type of exporter to use: `stdout` and `otlp`, and trace api implements both exporter while metrics api only has `stdout` exporter.

Is this a **TODO** or excepted? If excepted, how can I send metrics data to `OTEL-Collector`?

**Comment by dmathieu** [comment]
There is an OTLP exporter for metrics, both for HTTP and gRPC: https://github.com/open-telemetry/opentelemetry-go/tree/main/exporters/otlp/otlpmetric

**Comment by pellared** [comment]
Take a look at https://pkg.go.dev/go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp and https://pkg.go.dev/go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc

There are not stable but I think they are good to use 😉

**Comment by JobberRT** [comment]
@dmathieu @pellared  

I'm sorry, it was my oversight. 
I only executed `go.opentelemetry.io/otel` and forgot to execute `go.opentelemetry.io/otel/...`, which resulted in not updating all the submodules. 

No wonder I vaguely remember seeing the Metrics OTLP Exporter when I checked the code yesterday after the Stable API was just released. 

Thank you all for your efforts! 🥰🥰🥰
