### ISSUE TITLE
Ensure that OTLP/JSON exporter uses correct capitalization of field names

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-go#4139]
We have recently found that the OTLP spec was confusingly written and it was not clear what capitalization to use for trace id, span id fields.

The spec was clarified in this PR: https://github.com/open-telemetry/opentelemetry-proto/pull/468/files (it was considered a bug in the spec and we were allowed to fix it).

**All fields (including traceId and spanId fields) in OTLP/JSON must use camelCase names in exporters.**

I have not verified how the OTLP/JSON exporter behaves in this repository. If the exporter is not already using camelCase name please fix it, if it already is compliant with the spec please close this issue.

Note that Otel Collector currently accepts both camelCase and snake_case field names and will continue to do so for a while to give time for existing users to transition all existing non-compliant data sources to new versions that are OTLP spec-compliant.

**Comment by Aneurysm9** [comment]
There is no OTLP/JSON exporter in this repository.  Should we close this issue or keep it open in case we add one?

**Comment by pellared** [comment]
Closing.

OTLP/JSON is not required so I do not think we need an issue until someone explicitly asks for it.

From https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/protocol/exporter.md?plain=1#L144-L146:

> SDKs SHOULD support both `grpc` and `http/protobuf` transports and MUST
support at least one of them. If they support only one, it SHOULD be
`http/protobuf`. They also MAY support `http/json`.

https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/protocol/exporter.md?plain=1#L144-L146
