### ISSUE TITLE
Log an error for empty view criteria

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#4149]
The [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/0c5bfa999a5310801d5c36d2a82cbcd0e32ca9cb/specification/metrics/sdk.md#view) recommends:

>   * If no criteria is provided, the SDK SHOULD treat it as an error. It is recommended that the SDK implementations fail fast. Please refer to [Error handling in OpenTelemetry](../error-handling.md) for the general guidance.

This is not treated as an error:

https://github.com/open-telemetry/opentelemetry-go/blob/b2246d58650bc6db04459353843250ee3bba77fc/sdk/metric/view.go#L57-L59

An error should be logged to match the other existing error already logged by `NewView`:

https://github.com/open-telemetry/opentelemetry-go/blob/b2246d58650bc6db04459353843250ee3bba77fc/sdk/metric/view.go#L94-L98

_Originally posted by @MrAlias in https://github.com/open-telemetry/opentelemetry-go/issues/3645#issuecomment-1569121108_

**Comment by pellared** [comment]
> An error should be logged 

Why not returning an error as suggested per the specification? I would consider changing the declaration to:

```go
func NewView(criteria Instrument, mask Stream) (View, error) {
```

1. We still can return a view when a error is reported
2. I guess usually the operators (users) do not want such errors and would prefer to react. In some cases they may even want to crash the app if they find that they do not accept  a misconfigured View.

**Comment by MrAlias** [comment]
Returning an error means `NewView` will not be able to be passed directly to `WithView`.

**Comment by pellared** [comment]
On the other hand, the exporter factory functions like https://pkg.go.dev/go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp#New are returning `(metric.Exporter, error)` and that we also cannot directly pass to https://pkg.go.dev/go.opentelemetry.io/otel/sdk/metric#NewPeriodicReader.

I see Go as a quite verbose language when it comes to error handling. I do not feel that "fluent-like" API is idiomatic. The user can always create a helper that would handle the error (e.g. log, ignore, panic).

**Comment by MrAlias** [comment]
I don't follow. You are suggesting that precedence from a different function from a different package from a different part of the setup should take precedence for `NewView`? A function with existing precedence for error handling?

**Comment by pellared** [comment]
That is only "one" reason out of three.

1. I feel that explicit error handling is more idiomatic
2. It would literally follow the OTel Specification
3. Precedence from a different package

(in this order)
