### ISSUE TITLE
Ensure the advice API can be added to the metric SDK

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#4162]
Adding the explicit bucket histogram advice API is tracked here: https://github.com/open-telemetry/opentelemetry-go/issues/4003

In order to make a stable release of the metric SDK, it needs to be ensured that that API can be added in a backwards compatible manner. This issue tracks that verification.

Resolving this may result in a complete solution being submitted as a PR, but it could also be resolved with a clear description of how to add a compliant implementation in a backwards compatible manner.

**Comment by dashpole** [comment]
I'm going to pick this up!

**Comment by dashpole** [comment]
Note on the spec: It is a bit odd, IMO, for advice to be identifying for instruments.  Does that mean the same instrument could be created, but with different buckets?

**Comment by MrAlias** [comment]
Prototype: https://github.com/open-telemetry/opentelemetry-go/pull/4341

**Comment by MrAlias** [comment]
Alt prototype: https://github.com/open-telemetry/opentelemetry-go/pull/4340

**Comment by MrAlias** [comment]
Both prototypes have been reviewed to satisfy the issue.

**Comment by dashpole** [comment]
Other feedback for the spec: Advice seemed unneccessary.  I can't see a world in which I would ever want to set histogram bounds on a non-histogram instrument.  If someone is configuring the aggregation in a view (from a non-histogram instrument), they need to set the buckets anyways, so the advice can't be used.
