### ISSUE TITLE
Flaky test: TestBatchSpanProcessorForceFlushCancellation 

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go#4197]
https://github.com/open-telemetry/opentelemetry-go/actions/runs/5174510036/jobs/9320908218?pr=4154

```sh
--- FAIL: TestBatchSpanProcessorForceFlushCancellation (0.00s)
    batch_span_processor_test.go:571: expected "context canceled" error, got <nil>
```

**Comment by tonisanta** [comment]
Hello @pellared I had a quick look at this issue but with yours changes in this [PR](https://github.com/open-telemetry/opentelemetry-go/pull/4369) I would say this issue should be also solved! If not, feel free to provide any extra info and I'll try to help.

**Comment by pellared** [comment]
It looks that you are right. Closing. Thank you.
