### ISSUE TITLE
Return the same agg for identical instruments

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#4201]
From the [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/metrics/sdk.md#duplicate-instrument-registration):

> Based on [the recommendations from the data model](data-model.md#opentelemetry-protocol-data-model-producer-recommendations), the SDK MUST aggregate data from identical Instruments together in its export pipeline.

Since identical "describes instances where all identifying fields are equal" and [the identifying fields are](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/metrics/api.md#instrument):

- The name of the Instrument
- The kind of the Instrument - whether it is a [Counter](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/metrics/api.md#counter) or one of the other kinds, whether it is synchronous or asynchronous
- An optional unit of measure
- An optional description
- *note*: we do not currently support advice so it is not considered here

And the cache look up key:

https://github.com/open-telemetry/opentelemetry-go/blob/135c64f2897000780febb0945d1d9db195faecc6/sdk/metric/pipeline.go#L326

is missing the instrument kind, and contains the additional aggregation name, monotonicity, temporality, and number:

https://github.com/open-telemetry/opentelemetry-go/blob/135c64f2897000780febb0945d1d9db195faecc6/sdk/metric/instrument.go#L152-L171

The OTel Go implementation is not compliant:

- If two different instruments with the same, name, unit, kind, and description but of different number types (i.e. `int64` and `float64`) are created they will use different aggregators

_Originally posted by @MrAlias in https://github.com/open-telemetry/opentelemetry-go/issues/3653#issuecomment-1577348297_

**Comment by MadVikingGod** [comment]
The spec says:
> Language-level features such as the distinction between integer and floating point numbers SHOULD be considered as identifying.

Wouldn't an int counter be different from a float counter of the same name, and should get different aggregators because of that?

**Comment by MrAlias** [comment]
For the API sure, but [the data-model](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.21.0/specification/metrics/data-model.md#opentelemetry-protocol-data-model) conflicts with this:

> Within certain data point types (e.g., Sum and Gauge) there is variation permitted in the numeric point value; in this case, the associated variation (i.e., floating-point vs. integer) is not considered identifying.

And the SDK spec references the data-model not the API here.

**Comment by MrAlias** [comment]
I think the specification needs to be changed here.

**Comment by MrAlias** [comment]
https://github.com/open-telemetry/opentelemetry-specification/pull/3585 clarified the identifying fields to be:

- name
- instrument kind
- unit
- description
- language-level features such as the number type (`int64` and `float64`)

Based on this, the cache key needs to be updated to include the instrument kind and drop the aggregation name, monotonicity, and temporality.

**note**: the name matching is still being done in a case-sensitive manner. This is still an open question: https://github.com/open-telemetry/opentelemetry-specification/issues/3539
