### ISSUE TITLE
Move website_docs to OTel website repo

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry-go#4214]
Are we ready yet to move the OTel Go docs to the OTel website? Go is the last language SIG for which this needs to be done. The OTel comms team is working on improving docs across languages by having, to the extent possible, consistent content and organization. Having all language SIG docs as part of the OTel website repo makes that much easier to do.

If y'all are ready for the move now (which has been discussed for a while now, https://github.com/open-telemetry/opentelemetry.io/issues/1935), the Comms team can do the legwork involved in the move.

Thanks!

### Tasks

- [x] https://github.com/open-telemetry/opentelemetry.io/pull/2872
- [ ] #4219

/cc @svrnm @cartermp

**Comment by MrAlias** [comment]
If it makes things easier for the comms team I'm good with moving.

**Comment by svrnm** [comment]
@chalin thanks for pushing this!

@MrAlias easier by a lot! we also provide [codownership](https://github.com/open-telemetry/opentelemetry.io/blob/main/.github/CODEOWNERS) to the SIG approvers/maintainers such that you get notified about changes for the GO documentation.
