### ISSUE TITLE
Add simplified constructor for simple trace SDK setup: Jaeger exporter

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-go#424]
Like #343, #344, #345 but for the trace SDK. This one should cover Jaeger.

This means new methods for simplified setup, should follow the style of the metrics APIs.  NewRawExporter(), NewExportPipeline(), ...

**Comment by matej-g** [comment]
Hi, is this still available? I was working on #343, so I would be interested in tackling this one as well

**Comment by iredelmeier** [comment]
Possibly relevant: #161
