### ISSUE TITLE
Data race on BatchSpanProcessor

### ISSUE THREAD

**Issue by peolivei2** [open-telemetry/opentelemetry-go#4249]
We're seeing the data race below for SDK 1.14.0:

![image](https://github.com/open-telemetry/opentelemetry-go/assets/41344967/3b6682fc-2e0e-447d-a19b-9c75ae154ad6)

**Comment by dmathieu** [comment]
Could you provide a reproduction example?

**Comment by peolivei2** [comment]
@dmathieu the problem here is the approach the SDK is taking for handling the close/send of the queue channel. It's not guaranteeing that it won't send to the channel after closing, but instead relying on a recover after a panic. That's a valid data race as documented here:
- https://go.dev/doc/articles/race_detector#Unsynchronized_send_and_close_operations
- https://github.com/golang/go/issues/30372

It doesn't repro consistently because of another race condition in the SDK:
![image](https://github.com/open-telemetry/opentelemetry-go/assets/41344967/b8ec2631-82a4-4bf8-8368-e1f0e4ce388c)

My suggestion here would be to not close the queue channel at all, then combine the selects above so you just atop adding to the queue after the shutdown.

**Comment by dmathieu** [comment]
Combining the selects wouldn't be a reliable solution either, as Go doesn't run select/case statements in the order they are specified, but in shuffle order.
So every time, we could be appending to the queue again and returning true, or detect the stopCh has been closed, and return false.

See https://medium.com/a-journey-with-go/go-ordering-in-select-statements-fd0ff80fd8d6

**Comment by pellared** [comment]
I quickly looked at the code and it uses channels improperly.

The "consumer" goroutine is closing the channel: https://github.com/open-telemetry/opentelemetry-go/blob/fd5284f75cfc69d07a61024793e0ed09a8dc9c23/sdk/trace/batch_span_processor.go#L321-L350

Moreover, the "producer" goroutine has some hacks to prevent panics if it sends to a closed channel.:

https://github.com/open-telemetry/opentelemetry-go/blob/fd5284f75cfc69d07a61024793e0ed09a8dc9c23/sdk/trace/batch_span_processor.go#L361-L395

I guess there may be more problems, but it looks clear that the synchronization is not implemented properly.

Reference: https://go101.org/article/channel-closing.html
