### ISSUE TITLE
Not possible to unit test a SpanProcessor

### ISSUE THREAD

**Issue by mattsains** [open-telemetry/opentelemetry-go#4284]
### Problem Statement

I am writing a custom span processor, and I'm trying to write unit tests for it. Specifically, I am trying to write a unit test that calls this interface method:

```
SpanProcessor.OnEnd(s "go.opentelemetry.io/otel/sdk/trace".ReadOnlySpan)
```

However, the ReadOnlySpan interface cannot be implemented, and I can't find any way of generating a test one given the public functions in this repository.

### Proposed Solution

A way to generate a test span, kind of like the following which is possible to create an instance of the other span interface in this repo, `"go.opentelemetry.io/otel/trace".Span`:

```
_, mockSpan := otrace.NewNoopTracerProvider().Tracer("").Start(context.Background(), "")
``` 

#### Alternatives

Alternatively, allow the `"go.opentelemetry.io/otel/sdk/trace".ReadOnlySpan` type to be implemented so that it can be mocked.

**Comment by Aneurysm9** [comment]
The `tracetest` package has a [method](https://pkg.go.dev/go.opentelemetry.io/otel/sdk@v1.16.0/trace/tracetest#SpanStub.Snapshot) for creating a `ReadOnlySpan` from a [`SpanStub`](https://pkg.go.dev/go.opentelemetry.io/otel/sdk@v1.16.0/trace/tracetest#SpanStub), which is a struct with exported fields you can construct in tests.

**Comment by MrAlias** [comment]
Why not just register the span processor with a `TracerProvider` and produce the span that way?

That or embed the `ReadOnlySpan` interface into a span `struct` of your design?

**Comment by mattsains** [comment]
> The `tracetest` package has a [method](https://pkg.go.dev/go.opentelemetry.io/otel/sdk@v1.16.0/trace/tracetest#SpanStub.Snapshot) for creating a `ReadOnlySpan` from a [`SpanStub`](https://pkg.go.dev/go.opentelemetry.io/otel/sdk@v1.16.0/trace/tracetest#SpanStub), which is a struct with exported fields you can construct in tests.

oh, that's perfect, thanks!
