### ISSUE TITLE
[Suggestion Needed] How to correctly enable tracing in existing web service

### ISSUE THREAD

**Issue by Kaushal28** [open-telemetry/opentelemetry-go#4286]
I already have a fully functional shim microservice (receives requests from its clients and it redirects these requests to other services or databases based on some business logic). Now, I want to implement tracing using open telemetry.

I need a trace per request. So I am planning is to create a middleware for all the endpoints where I'll initialize the root otel span. I'll pass around the root span context to methods that are making calls to third party services/database, so that I can initialize the new child spans there.

I am also planning to use: [this `net/http` instrumentation](https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/instrumentation/net/http) so that I can also get traces from `net/http` library.

To achieve this, it requires passing around the root context so that the child contexts can be created out of it. Once child context is initialized, I can use that in above instrumentation to get the traces out of third party libraries.

Is this correct way to achieve this? I feel like it requires many changes and also new developer writing a method will also have to remember using the root context he is getting in the new method. Are there any other robust approaches for this kind of problems?

I also tried finding the examples in this repository and on internet but couldn't validate my approach anywhere. Thanks.

**Comment by dmathieu** [comment]
Did you see [this example](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/net/http/otelhttp/example/server/server.go#L102)? It shows how to use the Handler we provide for HTTP servers using `net/http`.

As for the use of context, we follow the conventions defined by Go itself. See https://go.dev/blog/context
Which is that each context is idempotent. So whenever a new span is created, a new context is created as well. In the case of net/http applications, the context in `*http.Request` is updated though.
So yes, it means a context has to be passed around to be able to create child spans.
