### ISSUE TITLE
Need a way to test metrics

### ISSUE THREAD

**Issue by howardjohn** [open-telemetry/opentelemetry-go#4291]
### Problem Statement

A way to test metrics collection. This can be done fairly easily in other metrics libraries such as [OpenCensus](https://github.com/istio/istio/blob/86341501179752ccdf2130b44b2092ceebea742b/pkg/monitoring/monitortest/test.go#L72-L76) or Prometheus

However, otel-go makes this challenging when using the fairly common pattern of global metric definitions. For example, if our application code looks like:

```go
	meter           = otel.GetMeterProvider().Meter("my-meter")
	someMetric, _ = meter.Int64Counter(
		"things",
		metric.WithDescription("ssomething happening"),
	)
```

This works fine. `otel.SetMeterProvider()` can be called, and the special default meter provider in `internal/global/meter.go` (which is both extremely complex and internal, so it cannot be consumed directly), and it will copy any instruments attached to our meters *the first time we call SetMeterProvider*. The problem is if we call `SetMeterProvider` multiple times we lose all our instruments.

This means we cannot have multiple different tests setting their own meter providers.

So while we can write a test like:

```go
reader := sdkmetric.NewManualReader()
mp := sdkmetric.NewMeterProvider(
	sdkmetric.WithReader(reader),
)
otel.SetMeterProvider(mp)
rm := &metricdata.ResourceMetrics{}
require.NoError(t, reader.Collect(ctx, rm))
t.Logf("Got metrics!: %+v", rm)

assert.Len(t, rm.ScopeMetrics, 1)
```

We can only do so once per package.

So we could make sure we only call `otel.SetMeterProvider` once per package -- that almost works, as well. But then each test pollutes the other. We need a way to _reset_ the data between each test.

### Proposed Solution

There are a lot of options here, I think its best to leave proposals to the maintainers who are more familiar with the goals of the projects. But some sort of way I can reasonable write a test like:

```go
var (
	meter           = otel.GetMeterProvider().Meter("my-meter")
	someMetric, _ = meter.Int64Counter(
		"things",
		metric.WithDescription("something happening"),
	)
)
func TestA(t *testing.T) {
	metricTest := NewMetricTest(t)
	someMetric.Record(1)
	metricTest.AssertMetricHasValue("things", 1)
}
func TestB(t *testing.T) {
	metricTest := NewMetricTest(t)
	someMetric.Record(2)
	metricTest.AssertMetricHasValue("things", 2)
}
```

Where the two tests do not interfere with each other.

#### Alternatives

I do not know any alternatives besides not testing our code or not adopting OpenTelemetry. I suppose we could not using global metrics.

#### Prior Art

Here is how we do this today with OC: https://github.com/istio/istio/blob/86341501179752ccdf2130b44b2092ceebea742b/pkg/monitoring/monitortest/test.go#L72-L76

**Comment by dmathieu** [comment]
One thing that many instrumentation libraries are doing is provide a way to set a custom provider, and rely on the global one if none were provided.

For example, the [net/http instrumentation](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/net/http/otelhttp/config.go#L67), with its [WithMeterProvider](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/net/http/otelhttp/config.go#L98) option.

With that solution, you can skip setting a custom meter provider at runtime, and your tests can set one. You do rely on the global at runtime, but not for tests.

**Comment by howardjohn** [comment]
Thanks, that is a good reference. It doesn't quite work for our case, I think, as our instruments are also global which is really the root of all these challenges.

**Comment by dmathieu** [comment]
Looking at the OpenCensus code you mentioned, I don't think we could do the same thing and remain compliant with the specifications.
It seems moving the instruments to not be global may be the path forward for you.

To take the net/http example again, the NewMiddleware method [creates measures](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/net/http/otelhttp/handler.go#L77) when the struct is created.
If several structs are created, the same metric will be created multiple times. But if they use the same meter provider, they will also get memoized internally.

**Comment by howardjohn** [comment]
I understand that we _can_ refactor our application - which would be quite a massive effort, as we have 100s of metrics currently - to support this. But its frustrating that we would have to fundamentally change our application architecture to adopt otel-go. TBH, I am not entirely convinced migrating off globals is even a good idea architecturally.

I did a bit of a survey of usages I found of otel-go metrics in OSS projects. This is obviously not conclusive but what I was able to find in 15min or so.

## Globals

DataDog: https://github.com/DataDog/datadog-agent/blob/4e9ab30be857f79831ccbf39772af02cd4ee70a4/pkg/logs/sender/sender.go#L18-L20. 200+ metrics

https://github.com/mahboubii/otelauto (not directly comparable as its a library)


spiderpool: https://github.com/spidernet-io/spiderpool/blob/9b0f49076c7e24e310330c662a9aca7716021f47/pkg/metric/metrics_instance.go#L76

uptrace: https://github.com/uptrace/uptrace/blob/8ff07c846e9b92d3d283c6b158b39d6b30ebca3d/pkg/tracing/init.go#L21

## Non-globals

Kyverno: https://github.com/kyverno/kyverno/blob/eb4b8614f0be4fcc0efdd15c3d7b8d499bdb4cb2/pkg/engine/engine.go#L55-L58. 16 metrics


Rueidis (redis client): https://github.com/redis/rueidis/blob/844f2bd7ad71b02c094c3d67ce55af5baed1d777/rueidisotel/trace.go#L44
otel-go examples/

secrets-store-csi-driver: https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/57b18e80fe781f3dac581475ce817d633b532e71/pkg/rotation/stats_reporter.go#L58 (3 metrics)

## Mixed

Temporal: https://github.com/temporalio/temporal/blob/687125a011697d030bf197db968f679632d483e8/common/metrics/otel_metrics_handler.go#L55C6-L55C27 - a bit of a gray area, looks like they have a struct that can access all the metrics, which are defined globally (https://github.com/temporalio/temporal/blob/687125a011697d030bf197db968f679632d483e8/common/metrics/metric_defs.go#L1639)

**Comment by pellared** [comment]
> TBH, I am not entirely convinced migrating off globals is even a good idea architecturally.

Using globals always hurts testability 🤷 

I agree with @dmathieu comments.

**Comment by dmathieu** [comment]
I am going to close this. It seems we have a consensus among approvers not to do anything on this.
As a side note, based on the code samples you provided, you should be able to do what you're trying to achieve with your own helpers and no code change within the library.
