### ISSUE TITLE
prometheus: Do not embed metric.Reader

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go#4310]
Probably not a blocker but I think that `prometheus.Exporter` should not have the `Reader` field embedded (as it can be accessed and modified). I think it would be better to use "delegation" instead of embedding.

https://github.com/open-telemetry/opentelemetry-go/blob/55fb2bb57b47133d0b966e4d55151fba47aae057/exporters/prometheus/exporter.go#L53

_Originally posted by @pellared in https://github.com/open-telemetry/opentelemetry-go/issues/3671#issuecomment-1634560086_

**Comment by MrAlias** [comment]
cc @dashpole

**Comment by dashpole** [comment]
Having the reader embedded allows the exporter to be passed to WithReader(), which keeps initialization simple:

https://github.com/open-telemetry/opentelemetry-go/blob/55fb2bb57b47133d0b966e4d55151fba47aae057/example/prometheus/main.go#L46

What would "delegation" look like?

**Comment by pellared** [comment]
I mean have the reader field unexpected and make the exporter to implement the reader interface. I will create a PR tomorrow.

**Comment by pellared** [comment]
I have forgotten that `metric.Reader` has unexported methods. Therefore still I prefer to "encapsulate" instead of using embedding. I find it cleaner.

**Comment by pellared** [comment]
Closing as not planned per https://github.com/open-telemetry/opentelemetry-go/pull/4313
