### ISSUE TITLE
`aggregator_example_test.go` is out of date.

### ISSUE THREAD

**Issue by MadVikingGod** [open-telemetry/opentelemetry-go#4331]
### Problem Statement

[`aggregator_example_test.go`](https://github.com/open-telemetry/opentelemetry-go/blob/main/sdk/metric/internal/aggregate/aggregator_example_test.go) is out of date and doesn't represent how aggregators are built and used anymore.

### Proposed Solution

Update the example to show how these aggregations are currently built.

#### Alternatives

Remove this example.

### Additional Context

I believe this file was made before the meter had a pipeline structure. This was an example of how the Meter/MeterProvider might use the Aggregations. Now that the pipeline exists, I question if this still provides us value, especially if we can fundamentally change the use of Aggregators and not have this break.

**Comment by MrAlias** [comment]
> Remove this example.

+1
