### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by 0michalsokolowski0** [open-telemetry/opentelemetry-go#4335]
### Description

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0xb7e584]

goroutine 46 [running]:
go.opentelemetry.io/otel/sdk/trace.(*forceFlushSpan).Resource(0x1217600?)
	<autogenerated>:1 +0x24
go.opentelemetry.io/otel/exporters/otlp/otlptrace/internal/tracetransform.Spans({0xc0002d6000, 0x2, 0xc0000966c0?})
	/go/pkg/mod/go.opentelemetry.io/otel/exporters/otlp/otlptrace@v1.16.0/internal/tracetransform/span.go:47 +0x183
go.opentelemetry.io/otel/exporters/otlp/otlptrace.(*Exporter).ExportSpans(0xc0000a9d10, {0x164ebf0, 0xc003d17650}, {0xc0002d6000?, 0xc0002d9160?, 0xc00081ec00?})
	/go/pkg/mod/go.opentelemetry.io/otel/exporters/otlp/otlptrace@v1.16.0/exporter.go:44 +0x3a
go.opentelemetry.io/otel/sdk/trace.(*batchSpanProcessor).exportSpans(0xc0002072c0, {0x164eb80, 0xc0039680f0?})
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.16.0/trace/batch_span_processor.go:269 +0x264
go.opentelemetry.io/otel/sdk/trace.(*batchSpanProcessor).drainQueue(0xc0002072c0)
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.16.0/trace/batch_span_processor.go:330 +0x275
go.opentelemetry.io/otel/sdk/trace.NewBatchSpanProcessor.func1()
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.16.0/trace/batch_span_processor.go:129 +0x6f
created by go.opentelemetry.io/otel/sdk/trace.NewBatchSpanProcessor
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.16.0/trace/batch_span_processor.go:126 +0x2ea

### Environment

- go.opentelemetry.io/otel v1.11.2
- tlptrace v1.16.0

### Expected behavior

No panic.

**Comment by dmathieu** [comment]
It looks like your Tracer Provider has a nil resource.

https://github.com/open-telemetry/opentelemetry-go/blob/f6a658c6c2f2909e93f064b2962aa9d3114b3e27/sdk/trace/span.go#L628

Could you give us a short reproduction example? The way you configure your SDK is probably related to the error here.

**Comment by 0michalsokolowski0** [comment]
> Could you give us a short reproduction example? The way you configure your SDK is probably related to the error here.
Thanks for the suggestion, I will check that.

Shouldn't there be nil check here? https://github.com/open-telemetry/opentelemetry-go/blob/main/exporters/otlp/otlptrace/internal/tracetransform/span.go#L47
Considering Resource() is pointer

**Comment by pellared** [comment]
@0michalsokolowski0 Any update?

**Comment by 0michalsokolowski0** [comment]
```

	res, err := getResource(ctx)
	if err != nil {}

	exporter, err := createExporter(ctx)
	if err != nil {}

	bsp := trace.NewBatchSpanProcessor(exporter)
        ...
}

func getResource(ctx context.Context) (*resource.Resource, error) {
	hostname, _ := os.Hostname()

	return resource.New(
		ctx,
		resource.WithDetectors(gcp.NewDetector()),
		resource.WithTelemetrySDK(),
		resource.WithContainer(),
		resource.WithFromEnv(),
		resource.WithAttributes(
			semconv.ServiceNameKey.String(config.ServiceName()),
			semconv.ServiceNamespaceKey.String("backend"),
			semconv.ServiceInstanceIDKey.String(hostname),
			semconv.DeploymentEnvironmentKey.String(config.EnvID()),
		),
	)
}

func createExporter(ctx context.Context) (*otlptrace.Exporter, error) {
	ctx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()

	conn, err := grpc.DialContext(
		ctx,
		config.String("tracing.collector_addr"),
		grpc.WithTransportCredentials(insecure.NewCredentials()),
		grpc.WithBlock(),
	)
	if err != nil {}
	
	exporter, err := otlptracegrpc.New(ctx, otlptracegrpc.WithGRPCConn(conn))
	if err != nil {
		return nil, err
	}

	return exporter, nil
}
```

**Comment by pellared** [comment]
Can you please provide a [working example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by 0michalsokolowski0** [comment]
No, I cannot. It randomly killed two pods out of N and happened at least once.

> Usually, a provider with a nil resource would be considered an error. 

Triggering this seems like the easiest way to reproduce it to me.

**Comment by pellared** [comment]
> > ider with a nil resource would be considered an error.
> 
> Triggering this seems like the easiest way to reproduce it to me.

Have you tried it? I do not think it is possible in the latest version.

**Comment by 0michalsokolowski0** [comment]
I am afraid I don't follow.
There is a pointer that shouldn't ever be nil, but surprisingly it is nil.
Afaik it should be fixed first. I don't have time to try to reproduce something happening randomly now and then.
If that's a problem, I can close the issue.

**Comment by pellared** [comment]
I have finally found the bug. Thanks for reporting 👍
