### ISSUE TITLE
Project does not vendor-in thrift generated files from Jaeger repo

### ISSUE THREAD

**Issue by annanay25** [open-telemetry/opentelemetry-go#434]
I was looking to start work on #327, but quickly realised that the project does not vendor-in _the entire_ thrift-compiled directory from the Jaeger project (https://github.com/open-telemetry/opentelemetry-go/blob/master/exporters/trace/jaeger/internal/gen-go/jaeger/jaeger.go).

All APIs related to span processing have been copied over, but remote sampling definitions are missing. It would be cleaner to vendor in the entire directory as we do as part of the collector project.

**Comment by rghetia** [comment]
@annanay25 can you please elaborate on the problem? may be output of failure?

**Comment by annanay25** [comment]
@rghetia - what I meant, is that the [jaeger.go](https://github.com/open-telemetry/opentelemetry-go/blob/master/exporter/trace/jaeger/internal/gen-go/jaeger/jaeger.go) file in this repo is a duplicate of the thrift-generated files in the jaeger repo. It includes the agent and collector APIs, but the sampling APIs are missing. 

We should ideally vendor-in the entire `thrift-gen` package from jaeger repo.

**Comment by MrAlias** [comment]
This looks like it might have been resolved in https://github.com/open-telemetry/opentelemetry-go/pull/1712

Please reopen if not.
