### ISSUE TITLE
sampled is not propagated properly

### ISSUE THREAD

**Issue by carbin-gun** [open-telemetry/opentelemetry-go#4344]
### Description

At grpc  client side the span is marked as 'not-sampled' , and passed by the `x-b3-sampled: 0 ` as medatatata. but the server mark the  server-side span is `sampled`. which cause the whole trace is partially recorded. 

### Environment

- OS:  Mac
- Architecture: m1
- Go Version: 1.19.5
- opentelemetry-go version: main

### Steps To Reproduce
1. In opentelemetry-go source code `sdk/trace/tracer.go:73` the `newSpan` function ,the new span `TraceFlags` Decision is decided always by calling the  `Sampler` function `ShouldSample` from `TracerProvider`. which may produce a different value from the metadata value. then  the  **not complete** `spans` were created.  

for example: from the client side , the `x-b3-sampled`(let's say the propagation protocol is `b3`) may be set `0/false`, the client side will not produce an exported span from that , but at the server side , the decision will be made again but the sampling result  decision may be different. let's see the code below

```
	samplingResult := tr.provider.sampler.ShouldSample(SamplingParameters{
		ParentContext: ctx,
		TraceID:       tid,
		Name:          name,
		Kind:          config.SpanKind(),
		Attributes:    config.Attributes(),
		Links:         config.Links(),
	})

	scc := trace.SpanContextConfig{
		TraceID:    tid,
		SpanID:     sid,
		TraceState: samplingResult.Tracestate,
	}
	if isSampled(samplingResult) {
                // runs here ,the result will always be FlagsSampled I think
		scc.TraceFlags = psc.TraceFlags() | trace.FlagsSampled
	} else {
		scc.TraceFlags = psc.TraceFlags() &^ trace.FlagsSampled
	}

```
![image](https://github.com/open-telemetry/opentelemetry-go/assets/1298473/103e7ed1-fde4-49d0-8455-8b83dc552daa)

2. Let's see what the `uber/jaeger-client-go` do , in the source code `tracer.go:200` ; from the code , the `Span` created will follow the rule
 - if the parent span is remote, the newly created span will be marked sampling state by  the  parent span value; and the span will be marked as final ; 
 - if the newly created span is marked final, the following sampling decision will not be made; 
 - the result will be: the newly created span's samplingSate will follow the client's sampling value(ie: x-b3-sampled) 

![111](https://github.com/open-telemetry/opentelemetry-go/assets/1298473/c26b9bd8-34fd-4bb5-9487-36d7f127c801)

![222](https://github.com/open-telemetry/opentelemetry-go/assets/1298473/c15a6028-8bd3-4e87-8bc0-9190be319d93)

### Expected behavior

1. the server side span will follow the `x-b3-sampled` value , or the span will not be consistent/continuous  which is not expected from my side. 
2. for the implementation , the way from jaeger  is right I think. 
 - vary sampling decision between server and client code
 - if parent span is remote, follow the sampling decision (ie: the TraceFlags)

**Comment by Aneurysm9** [comment]
Which sampler are you using?  If you use the [`ParentBased` sampler](https://pkg.go.dev/go.opentelemetry.io/otel/sdk@v1.16.0/trace#ParentBased) this should be handled as you expect.

**Comment by carbin-gun** [comment]
Wow, I didn't realize there's a [ParentBased sampler](https://pkg.go.dev/go.opentelemetry.io/otel/sdk@v1.16.0/trace#ParentBased)

I've read the source code, such a great composite sampler!

Thanks,  I will close this issue.
