### ISSUE TITLE
Correct location for DefaultExponentialHistogram

### ISSUE THREAD

**Issue by MadVikingGod** [open-telemetry/opentelemetry-go#4347]
_Originally Discussion in https://github.com/open-telemetry/opentelemetry-go/pull/4245#discussion_r1249555330_
            
Currently, for all `Aggregators` in the `sdk/metric/aggregation` package, the zero value, e.g. `ExplicitBucketHistogram{}`, will result in a data stream with the recommended settings from the specification.
The Exponential Histogram does not, specifically `MaxScale` is valid at 0 and the recommended starting value is 20.

The user experience of setting up a view to use the specification-recommended Exponential Histogram currently would be to find the recommendations in the specification and then construct the `Aggregation` to match.  

The goal of this ticket is to improve that experience.

# Proposed solutions:

## DocStrings

Add the recommended configuration to the doc string.  This has the least impact on code.

## DefaultExponentialHistogram()

This would be a function that returns the specification-recommended `Aggregation`.  It could be located in the `sdk/metric/aggregation` alongside the type definition of `ExponentialHistogram,` or in `sdk/metric` alongside the `DefaultAggregationSelector` and `DefaultTemporalitySelector`.

## ExponentialHistogram Constructor

This would allow you to only build valid  ExponentialHistograms via a Constructor.  There are multiple ways that this could be achieved via unexporting fields, or making a [`HasValue`](https://github.com/MadVikingGod/opentelemetry-go/blob/mvg/exp-hist-agg/baggage/baggage.go#L63) like field.

**Comment by MrAlias** [comment]
Moving to the post-GA project as this doesn't seem needed for GA (right?).

**Comment by MrAlias** [comment]
Closing as we have not seen a large user desire for this. If there is desire in the future, please comment and we can reopen.
