### ISSUE TITLE
Reimplement concurrent processing in BatchSpanProcessor

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go#4354]
It would be a lot better to e.g. wait for `exportSpans` done during shutdown (and return the error), but this would need major reimplementation of the whole processing logic.

The processing logic may be implemented e.g. similarly to `PeriodicReader`.

_Originally posted by @pellared in https://github.com/open-telemetry/opentelemetry-go/pull/4353#discussion_r1272180864_

**Comment by MrAlias** [comment]
This might be a duplicate of https://github.com/open-telemetry/opentelemetry-go/issues/1178

**Comment by pellared** [comment]
> This might be a duplicate of #1178

I agree. Closing.
