### ISSUE TITLE
Exporting fails if a 204 No Content is returned

### ISSUE THREAD

**Issue by gouthamve** [open-telemetry/opentelemetry-go#4363]
### Description

The current http exporters [expect a http.StatusOK (200) response code](https://github.com/open-telemetry/opentelemetry-go/blob/d423bd4cf28f65bdcbd1b1d83d0f59c4388f37b0/exporters/otlp/otlpmetric/otlpmetrichttp/client.go#L180-L204). But this is not required by the spec and also not [something the collector requires](https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/otlphttpexporter/otlp.go#L135-L137).

Trying to use the exporter in a test fails with:

```
failed to upload metrics: failed to send metrics to http://localhost:9090/api/v1/otlp/v1/metrics: 204 No Content
```

**Comment by dmathieu** [comment]
There is actually a requirement to return a `200` from full success exports: https://github.com/open-telemetry/opentelemetry-proto/blob/main/docs/specification.md#full-success-1
The spec also mentions than any other unspecified HTTP response should conform to the HTTP specification: https://github.com/open-telemetry/opentelemetry-proto/blob/main/docs/specification.md#all-other-responses

Which I read as: there shouldn't be a 204. But if there's one, we should handle it anyway.

> and also not [something the collector requires](https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/otlphttpexporter/otlp.go#L135-L137).

This link isn't about returning NoContent. It's about partial successes (which we do handle), and which still must return a 200.
See https://github.com/open-telemetry/opentelemetry-go/blob/main/exporters/otlp/otlpmetric/otlpmetrichttp/client.go#L195
