### ISSUE TITLE
Some aggregators may have inconsistent states when updating multiple values

### ISSUE THREAD

**Issue by paivagustavo** [open-telemetry/opentelemetry-go#437]
`MinMaxSumCount` and `Histogram` aggregators keeps multiple fields that are independently atomically updated by `Updated()` and `Checkponit()`, which could result in inconsistent states when these two methods are called concurrently. This is a result of the lock-free implemented algorithm on these aggregators.

From a study based on the Prometheus implementation that @jmacd linked in the #385, we could achieve a lock-free `Update()` algorithm that is consistent by making `Checkpoint()` a blocking method, since the last is called by the SDK itself this should not be a problem for the end user.

[Link to the mentioned algorithm](https://github.com/prometheus/client_golang/blob/e7776d2c54305c1b62fdb113b5a7e9b944c5c27e/prometheus/histogram.go#L227). 
[Link to the discussion](https://github.com/open-telemetry/opentelemetry-go/pull/385/files#r358592144).

**Comment by jmacd** [comment]
Note the new `StateLocker` type in #438 will help here. :tada:
