### ISSUE TITLE
span RecordError is not treat as newrelic error

### ISSUE THREAD

**Issue by KaptinLin** [open-telemetry/opentelemetry-go#4376]
### Description

No spans in this trace contain errors.

<img width="520" alt="image" src="https://github.com/open-telemetry/opentelemetry-go/assets/999331/667eaf48-9a99-4519-a7a7-3e9eb3d4b752">

but i get the exception Span event

<img width="540" alt="image" src="https://github.com/open-telemetry/opentelemetry-go/assets/999331/11ad255f-ae87-4965-a6f3-4bfa5d479754">

### Environment

- OS: window
- Architecture: x86
- Go Version: 1.21rc2
- opentelemetry-go version: v1.16.0

### Expected behavior
It should treat as error

**Comment by MrAlias** [comment]
Thank you for the interest in the project. The error you mention is an error in how the New Relic platform displays errors, it is not a bug in the OpenTelemetry Go code. Please open an issue with New Relic.
