### ISSUE TITLE
Add a description and website to the GitHub Project

### ISSUE THREAD

**Issue by paivagustavo** [open-telemetry/opentelemetry-go#439]
Adding a description of the project and link for the opentelemetry website could help people that are searching for the project.

![image](https://user-images.githubusercontent.com/7898464/72958993-a0731f80-3d87-11ea-8df0-a3192a69049a.png)

**Comment by rghetia** [comment]
Apparently I cannot update it either. Admin has to do it.
@mtwo, @tedsuo can you please update it.

**Comment by mtwo** [comment]
Added!
