### ISSUE TITLE
Counters, Gauges and Measures return bare structs when methods have pointer recievers 

### ISSUE THREAD

**Issue by neetle** [open-telemetry/opentelemetry-go#440]
Currently all of the `metric.NewT(Counter|Gauge|Measure)` and `metric.T(Counter|Gauge|Measure).Bind()` return bare structs. For example, `metric.NewFloat64Measure()` returns a `Float64Measure` and func `(*Float64) Bind() BoundFloat64Measure`.

However, all the methods on the returned structs have pointer receivers, so you need to take the address of the result before you can call the next method. This leads to code like
```go 
myMeasure := metric.NewFloat64()
myBoundMeasure := myMeasure.Bind() // implied pointer to myMeasure here
myStruct := struct{ measure *metric.BoundFloat64Measure } { 
  measure: &myBoundMeasure, // explicit pointer to myBoundMeasure 
} 
```

While this is a relatively minor discomfort, it's a schism in the API nevertheless. 

From this, I can see two resolutions to the issue: 

1)  Given that the zero value for these structs isn't safe to use, `metric.NewT(Counter|Gauge|Measure) ` and all associated methods could return a pointer rather than a bare struct.

2) Given concerns of allocations voiced on Gitter by @jmacd, all methods on `T(Counter|Gauge|Measure)` and `BoundT(Counter|Gauge|Measure)` could have bare struct receivers.

**Comment by neetle** [comment]
I'm personally leaning towards 2 if the structs are also made safe to use as a zero value.

**Comment by MrAlias** [comment]
I updated the instruments methods to have value receivers in #462 (in line with option (2)).

The zero value of the instruments does not seem to me to be an issue. Given they are expected to be constructed with some `Meter` implementation, it is not expected that these structs will be directly constructed.
