### ISSUE TITLE
Remove Jaeger exporter

### ISSUE THREAD

**Issue by arukiidou** [open-telemetry/opentelemetry-go#4405]
### Description
- Remove jaeger exporter, because jaeger exporter is dropped from spec.
  - open-telemetry/opentelemetry-specification/issues/3551
    - open-telemetry/opentelemetry-specification/pull/2858
    - open-telemetry/opentelemetry-specification/pull/3567

### Current status for removal

- will deprecated in v1.17.0 #4423 
- will removed in v1.18.0 #4467

**Comment by pellared** [comment]
After a release when it is deprecated, I think we can remove Jaeger exporter codebase and stop releasing new versions.

**Comment by arukiidou** [comment]
@pellared 
Is the timeline I described correct?

> will deprecated in v1.17.0 
> will removed in v1.18.0

**Comment by pellared** [comment]
@arukiidou Yes
