### ISSUE TITLE
Update Doc links to PeriodicReader after release

### ISSUE THREAD

**Issue by MadVikingGod** [open-telemetry/opentelemetry-go#4448]
Currently there are documentation references to `PeriodicReaders` in [otlpmetrichttp] and [oltpmetricgrpc], but because the PeriodicReaders have not been released we can't make a live link to them in the go docs.  

After the v0.40 release (or when PeriodicReaders are released) update these docs to reflect the current status.

_Originally posted by @pellared in https://github.com/open-telemetry/opentelemetry-go/pull/4336#discussion_r1272467211_

**Comment by MrAlias** [comment]
You should be able to link prior to the release. You can use https://pkg.go.dev/golang.org/x/pkgsite to verify the links will correctly render.

**Comment by pellared** [comment]
It will be addressed as part of https://github.com/open-telemetry/opentelemetry-go/issues/4688
