### ISSUE TITLE
Stream configuration supports units, which isn't in the specification

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-go#4454]
The `Stream` struct supports configuring a `Unit` https://github.com/open-telemetry/opentelemetry-go/blob/a5ff7af3f3737213063651caa549cb86bae42461/sdk/metric/instrument.go#L146

This appears outside of the scope of what the specification suggests for stream configuration: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#stream-configuration

Can someone help me confirm whether this is an issue w/ the spec or whether the struct shouldn't contain that field?

**Comment by MrAlias** [comment]
My reading of the specification is that it doesn't require implementation to include the unit in the stream configuration, but it doesn't restrict implementations from including it (or other fields) either.

**Comment by codeboten** [comment]
Right, I guess I'm not sure what this would mean for the telemetry generated. If someone configured a view to select a unit and configure the stream with a different unit, wouldn't it break the measurements captured?

**Comment by MrAlias** [comment]
I mean, sure, a user can always find a way to break their telemetry with a view. I doesn't have to be with a unit.

The reason I see this being helpful is if some instrumentation incorrectly sets the unit. In that case the operator of the system can fix the unit without having to make changes to the instrumentation upstream.

**Comment by codeboten** [comment]
> The reason I see this being helpful is if some instrumentation incorrectly sets the unit. In that case the operator of the system can fix the unit without having to make changes to the instrumentation upstream.

Fair enough, it would be great to have this as part of the specification though, otherwise folks will be able to do it in go and not in other languages. Mostly I'm interested in whether or not this is a field that needs to be part of the configuration schema :)

Do you know if there's already a spec issue with discussion around this?

**Comment by MrAlias** [comment]
> > The reason I see this being helpful is if some instrumentation incorrectly sets the unit. In that case the operator of the system can fix the unit without having to make changes to the instrumentation upstream.
> 
> Fair enough, it would be great to have this as part of the specification though, otherwise folks will be able to do it in go and not in other languages. Mostly I'm interested in whether or not this is a field that needs to be part of the configuration schema :)

Yeah, makes sense to me :+1:.

> Do you know if there's already a spec issue with discussion around this?

I think this one: https://github.com/open-telemetry/opentelemetry-specification/issues/1822

**Comment by codeboten** [comment]
I'll close this issue since there's already one in the spec. Thanks @MrAlias
