### ISSUE TITLE
Example of using Istio with OpenTelemetry

### ISSUE THREAD

**Issue by mark8s** [open-telemetry/opentelemetry-go#4458]
When playing around with Istio using OpenTelemetry as an instrumentation library, I found no quick example on the web that illustrates such scenarios.

Has anyone combined istio and jaeger to implement distributed tracking for go projects?

I need a simple demo to learn. thank you~

**Comment by dmathieu** [comment]
This repository holds the opentelemetry-go API and SDK, used to instrument applications.
While istio is written in Go, and could use this library, you wouldn't do so directly if you were to instrument your istio installation.
So I am going to close this issue. You may have more luck asking your question directly within istio, or in the opentelemetry slack channel.

It may not be of any help, but istio actually has documentation about otel: https://istio.io/latest/docs/tasks/observability/logs/otel-provider/
