### ISSUE TITLE
[security] audit repository tooling

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-go#4459]
The security SIG is looking to ensure that security tooling is setup consistently across the organization. As a result, we're asking maintainers to ensure the following tools are enabled in each repository:

- [x] CodeQL enabled via [GitHub Actions](https://github.com/open-telemetry/opentelemetry-collector/blob/main/.github/workflows/codeql-analysis.yml)
- [ ] Static code analysis tool (the collector uses govulncheck [https://pkg.go.dev/golang.org/x/vuln] on every build)
- [x] Repository security settings
    - [x] Security Policy ✅
    - [x] Security advisories ✅
    - [x] Private vulnerability reporting ✅
    - [x] Dependabot alerts ✅
    - [x] Code scanning alerts ✅

Parent issue: https://github.com/open-telemetry/sig-security/issues/12

**Comment by MadVikingGod** [comment]
Our current CodeQL is schedule to run at 1:30am every day, where the collector runs on pushes to main, and PRs.  Should we update it?

**Comment by codeboten** [comment]
The recommendation is to run it on push to main and on PRs https://github.com/open-telemetry/sig-security/issues/15

**Comment by pellared** [comment]
I think we can also use this issue to adopt the same tooling/automation in https://github.com/open-telemetry/opentelemetry-go-contrib

**Comment by sakshi-1505** [comment]
Hello Team, I think we have already added codeQL. On the staticcheck front, please allow me to suggest golangcilint, this is one of the most verbose & efficient staticcode checker as well a vulnerability analyser I have worked with. I can open a draftPR with it's integration if we are all on same page @pellared @MadVikingGod

**Comment by pellared** [comment]
We want to use `govulncheck`. See: https://pkg.go.dev/golang.org/x/vuln

**Comment by sakshi-1505** [comment]
Thanks @pellared for the update, I will open a PR for this.

**Comment by pellared** [comment]
Please check how other tools are versioned, installed and used via `Makefile` and `internal/tools` Go module.

**Comment by sakshi-1505** [comment]
@pellared @codeboten We can close this issue now, we are all green!

**Comment by pellared** [comment]
> I think we can also use this issue to adopt the same tooling/automation in https://github.com/open-telemetry/opentelemetry-go-contrib

https://github.com/open-telemetry/opentelemetry-go-contrib/issues/4413 is created.

Closing this issue.
