### ISSUE TITLE
Documentation bug: shouldn't the the example metric be gauges instead of counter/up down counter?

### ISSUE THREAD

**Issue by utezduyar** [open-telemetry/opentelemetry-go#4461]
### Description

Instrument types in `func ExampleMeter_asynchronous_multiple` which I believe is the source of "Example (Asynchronous_multiple) [¶](https://pkg.go.dev/go.opentelemetry.io/otel/metric#example-Meter-Asynchronous_multiple)" is wrong. 

The example creates a counter and an up/down counter and adds heap and gccount values to it. To my understanding these values are not additive therefore the instrument type is not correct, it should be gauge. 

I understand that maybe the examples are there for the sake of giving examples but the data that is picked is confusing people starting new on metrics.

**Comment by pkbhowmick** [comment]
Hey according to the api specifications, this is not really a bug. Please check here: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md

**Comment by utezduyar** [comment]
Can you be more specific please? 

The heap value and gc count value retrieved with the api are not additive values therefore using them as counter and up/down counter is wrong. They should have been gauges but we already have a gauge example therefore we should focus on finding a good example to demonstrate counter and up/down counter. The example should report deltas so that the instrument adds the deltas. 

Or you see something I don't.

**Comment by dmathieu** [comment]
We could also consider that this is just meant to be a usage example, not one which is meant to be fully accurate.

**Comment by utezduyar** [comment]
Maybe you are right @pkbhowmick. I experimented and I think the callback function is needing the absolute value. Then I don't understand the difference between a gauge and an async up/down counter. Following code seems to generate the same output in the collector

```
       _, err = meter.Int64ObservableUpDownCounter(
		"Foo",
		metric.WithInt64Callback(func(_ context.Context, obsrv metric.Int64Observer) error {
			obsrv.Observe(3)
			return nil
		}),
	)

	_, err = meter.Int64ObservableGauge(
		"Foo2",
		metric.WithInt64Callback(func(_ context.Context, obsrv metric.Int64Observer) error {
			obsrv.Observe(3)
			return nil
		}),
	)
```

I hope someone can clarify it.

**Comment by dmathieu** [comment]
Is this solved by https://github.com/open-telemetry/opentelemetry-go/pull/4504 ?
