### ISSUE TITLE
autoconfigure module

### ISSUE THREAD

**Issue by chameleon82** [open-telemetry/opentelemetry-go#4474]
### Problem Statement

Currently it is not possible to autoconfigure exporters with environment variables`OTEL_METRICS_EXPORTER` and `OTEL_TRACES_EXPORTER` regarding specification [sdk exporter selection](https://opentelemetry.io/docs/specs/otel/configuration/sdk-environment-variables/#exporter-selection).
Autoconfigure module can support next `none`, `otlp` and may support `logging` and `logging-otlp` exporters ( see java example [logging-exporter](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#logging-exporter)) 

### Proposed Solution

Similar to java implementation [sdk-extensions/autoconfigure](https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/autoconfigure)

#### Alternatives

Due otlp exporters are separate modules it is not possible to make that change as part of current implementation and require separate module depend on otlp exporters 

#### Prior Art

Example of implementation https://github.com/agoda-com/opentelemetry-logs-go/tree/master/autoconfigure 
(that project also consider to auto-configure http/protobuf,http/json,grpc format regarding spec)

**Comment by dmathieu** [comment]
The solution you're looking for lies in our contrib repository.
https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/exporters/autoexport

**Comment by chameleon82** [comment]
I think this can be closed for now then as auto-exporters is the only functionality which can't be auto-configured with current project.
