### ISSUE TITLE
metricdatatest is not using TestingT interface

### ISSUE THREAD

**Issue by carolplay** [open-telemetry/opentelemetry-go#4482]
### Problem Statement

The helper testing methods in `metricdatatest` accepts `testing.T` which is a struct, however, the norm is to use the interface `TestingT`. Example: https://github.com/open-telemetry/opentelemetry-go/blob/main/sdk/metric/metricdata/metricdatatest/assertion.go#L113
Consequence: when I am using other testing framework such as Ginkgo, I cannot use these `metricdatatest` helper methods by supplying `TestingT` interfaced `GinkgoT()`.

### Proposed Solution

The three assertion methods should use type `TestingT` for parameter t: `AssertEqual`, `AssertAggregationsEqual`, `AssertHasAttributes`, example: https://github.com/stretchr/testify/blob/master/assert/assertions.go#L405

#### Prior Art

A clear and concise list of any similar and existing solutions from other projects that provide context to possible solutions.

**Comment by dmathieu** [comment]
They should not use `TestingT`, which is a testify-specific interface and we shouldn't have a dependency on testify in these helpers.
It should probably use [testing.TB](https://pkg.go.dev/testing#TB) though.

**Comment by pellared** [comment]
> It should probably use [testing.TB](https://pkg.go.dev/testing#TB) though.

It would be better if this is an interface defined by us because as far as I remember `testing.TB` is only working for structs from `testing` (because of unexported methods).
