### ISSUE TITLE
service.name is not propagate to Jaeger using trace HTTP exporter

### ISSUE THREAD

**Issue by marcmolla** [open-telemetry/opentelemetry-go#4486]
### Description

It seems that service.name is not propagated to jaeger when we integrate open telemetry-go using otlptracehttp. At jaeger ui, we see OTLPResourceNoServiceName instead of the service name.

We checked the contexts of the service post to jaeger and the label "my_service" is not in the protobuf message.

### Environment

- OS: Ubuntu 22.04.1 LTS
- Architecture: x86_64
- Go Version: 1.21
- opentelemetry-go version: v1.17.0

### Steps To Reproduce

1. Add basic setup of HTTP exporter to the process:
```go
        //traces
	client := otlptracehttp.NewClient(otlptracehttp.WithEndpoint("10.20.30.40:4318"), otlptracehttp.WithInsecure(), otlptracehttp.WithCompression(otlptracehttp.NoCompression))
	exp, err := otlptrace.New(context.Background(), client)
	if err != nil {
		log.Fatalf("creating OTLP trace exporter: %s", err.Error())
	}
	if err != nil {
		log.Fatal(err)
	}

	r, _ := resource.Merge(
		resource.Default(),
		resource.NewWithAttributes(
			semconv.SchemaURL,
			semconv.ServiceName("my_service"),
			semconv.ServiceVersion("v0.1"),
		),
	)

	tp := trace.NewTracerProvider(
		trace.WithBatcher(exp),
		trace.WithResource(r),
	)
	defer func() {
		if err := tp.Shutdown(context.Background()); err != nil {
			log.Fatal(err)
		}
	}()
	otel.SetTracerProvider(tp)
```

3. Setup jaeger-all-in-one
4. Check jaeger ui

### Expected behavior

We expect that service.name is propagated to jaeger.

**Comment by dmathieu** [comment]
You're using OTLP here, and service name is properly propagated with that export method and other services. Could this be a jaeger issue?

**Comment by dmathieu** [comment]
I've just tried booting the jaeger-all-in-one docker container on my machine, and running the otel-collector example: https://github.com/open-telemetry/opentelemetry-go/tree/main/example/otel-collector

I am properly getting the service name.
![Screenshot 2023-09-08 at 14 14 51](https://github.com/open-telemetry/opentelemetry-go/assets/9347/c43b8407-c8a5-40a3-bdbf-701b9ec00eba)

**Comment by marcmolla** [comment]
Yes, Otel-collector example also works for me
![Captura de pantalla 2023-09-08 a las 15 10 52](https://github.com/open-telemetry/opentelemetry-go/assets/3853921/0c04e77b-4fcb-42f6-8b02-0c0f14087900)

I will try to reproduce my issue using the otel-collector example as base....

thanks
Marc

**Comment by dmathieu** [comment]
If this is an issue between the collector and jaeger, shouldn't it be in the opentelemetry-collector repository ?

**Comment by dmathieu** [comment]
From your original example, it's possible/likely you have a resource merge error, giving you an empty resource.

Try the following:
```golang
r, err := resource.Merge(
	resource.Default(),
	resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceName("my_service"),
		semconv.ServiceVersion("v0.1"),
	),
)
if err != nil {
	log.Fatal(err)
}
```

Resource merges being problematic is a known issue. See https://github.com/open-telemetry/opentelemetry-go/issues/2341

With the example above, I'm getting resource merge errors if I use the latest library with semconv < 1.21.0.
It works fine if I use semconv 1.21.0.

**Comment by marcmolla** [comment]
yes, that is the issue:
```bash
2023/09/12 09:33:16 cannot merge resource due to conflicting Schema URL
```

The way of creating the resource is in the Getting Started doc, maybe it can be updated for avoiding this error:
https://opentelemetry.io/docs/instrumentation/go/getting-started/

thanks for your support!

**Comment by dmathieu** [comment]
The getting started doc documents the proper way of doing it. The problem here is the larger issue of resource versions which are hard to tackle/upgrade.
I'll close this issue. The broader problem is already tracked in #2341.

**Comment by pellared** [comment]
> The way of creating the resource is in the Getting Started doc, maybe it can be updated for avoiding this error:
https://opentelemetry.io/docs/instrumentation/go/getting-started/

Already part of https://github.com/open-telemetry/opentelemetry.io/pull/3235
