### ISSUE TITLE
Release v1.18.0/v0.41.0/v0.0.6Checklist

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#4488]
- [x] Complete [Milestone](https://github.com/open-telemetry/opentelemetry-go/milestone/50)
  - Blocked by https://github.com/open-telemetry/opentelemetry-go/pull/4487
- [x] Update contrib codebase to support changes about to be released (use a git sha version)
- [x] [Pre-release](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#pre-release)
  - https://github.com/open-telemetry/opentelemetry-go/pull/4489
- [x] [Tag](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#tag)
- [x] [Release](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#release)
- [x] [Check examples](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#verify-examples)
- [x] [Sync with Contrib](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/RELEASING.md#upgrade-goopentelemetryiootel-packages)
- [x] [Release contrib](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/RELEASING.md#release-process)
- [x] [Sync website docs](https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md#website-documentation)
- [x] Close the milestone

**Comment by pellared** [comment]
How about including https://github.com/open-telemetry/opentelemetry-go/pull/4483?

**Comment by MrAlias** [comment]
done
