### ISSUE TITLE
Verify metric OTLP exporters compliance with metric specification

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#4511]
Specification: https://github.com/open-telemetry/opentelemetry-specification/blob/v1.25.0/specification/metrics/sdk_exporters/otlp.md

Create issues for anything not compliant.

**Comment by MadVikingGod** [comment]
# [General](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.25.0/specification/metrics/sdk_exporters/otlp.md#general)

- [ ] *Non Normative* OTLP Metrics Exporter is a Push Metric Exporter which sends metrics via the OpenTelemetry Protocol.
- [ ] OTLP Metrics Exporter MUST support both Cumulative and Delta Aggregation Temporality.
- [ ] The exporter MUST provide configuration according to the [OpenTelemetry Protocol Exporter](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.25.0/specification/metrics/sdk_exporters/otlp.md#general) specification. Note This is covered by #4512.
- [ ] If a language provides a mechanism to automatically configure a MetricReader to pair with the associated Exporter (e.g., using the OTEL_METRICS_EXPORTER environment variable), then by default:
    - [ ] The exporter MUST be paired with a periodic exporting MetricReader.
    - [ ] The exporter MUST configure the default aggregation temporality on the basis of instrument kind using the OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE variable as described below.
    - [ ] The exporter MUST configure the default aggregation on the basis of instrument kind using the OTEL_EXPORTER_OTLP_METRICS_DEFAULT_HISTOGRAM_AGGREGATION variable as described below if it is implemented.

# [Additional Configuration](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.25.0/specification/metrics/sdk_exporters/otlp.md#general)

- [ ] env vars:
    - [ ] OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE 
        - [ ] Default cumulative
        - [ ] Allowed values:
            - [ ] Cumulative
            - [ ] Delta
            - [ ] LowMemory
    - [ ] OTEL_EXPORTER_OTLP_METRICS_DEFAULT_HISTOGRAM_AGGREGATION
        - [ ] Default explicit_bucket_histogram
        - [ ] Allowed values:
            - [ ] explicit_bucket_histogram
            - [ ] base2_exponential_bucket_histogram

**Comment by pellared** [comment]
https://github.com/open-telemetry/opentelemetry-go/tree/16643aea3063604eab37e435ac63e94dda413bbe is compliant with https://github.com/open-telemetry/opentelemetry-specification/blob/v1.26.0/specification/metrics/sdk_exporters/otlp.md.
