### ISSUE TITLE
otlptracehttp: Update the example

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go#4564]
Can we just use [`otlptracehttp.New`](https://pkg.go.dev/go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp#New) here instead?

_Originally posted by @MrAlias in https://github.com/open-telemetry/opentelemetry.io/pull/3320#discussion_r1338747720_

**Comment by with-shrey** [comment]
Hey @pellared 
I'd like to take this.

I believe the change would be [here](https://github.com/open-telemetry/opentelemetry-go/blob/e3d6c8eec242f7641a58e3a73e37d0738f6e1084/exporters/otlp/otlptrace/otlptracehttp/example_test.go#L70)

```diff
- exporter, err := otlptrace.New(ctx, client)
+ exporter, err := otlptracehttp.New(ctx, client)
```

Are there any another changes like CHANGELOG expected as part of the PR ?
