### ISSUE TITLE
sdk/trace: ParentBased is a decorator

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go#4565]
From https://github.com/open-telemetry/opentelemetry.io/commit/5847bd3c89b4a36feb7f6046856cc645a2cbf6fe#r128534150

Update the docs and describe ParentBased sampler as a decorator (not composite).

**Comment by pellared** [comment]
We should update the specification first https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#parentbased

**Comment by pellared** [comment]
I created https://github.com/open-telemetry/opentelemetry-specification/pull/3706

**Comment by MrAlias** [comment]
Huh? It is literally a decision hierarchy tree that determines what sampler to use.

Also Go is not an object-oriented language, I do not support including object-oriented terms in our descriptions.

**Comment by pellared** [comment]
>  I do not support including object-oriented terms in our descriptions

Even though GoF design patterns are coming from object-oriented languages (C++ and Smalltalk), Go is quite close to these languages (at least a lot closer than to functional languages). Even though there are key differences they are not related to the GoF design patterns which can be applied.

PS. I would prefer using a more Go idiomatic term instead but I am not aware if such exist.
PS2. https://go.dev/doc/faq#Is_Go_an_object-oriented_language
