### ISSUE TITLE
Configurable metric push period

### ISSUE THREAD

**Issue by cirocosta** [open-telemetry/opentelemetry-go#458]
Hi!

First of all, thanks you very much for the work you've been doing! 

<br />

I noticed that the `dogstatsd` metric exporter is currently configured with a
push frequency of one hour:

https://github.com/open-telemetry/opentelemetry-go/blob/405a92ab3ed715c5aa0bf10c47e4b2d8e071861c/exporter/metric/dogstatsd/dogstatsd.go#L101

https://github.com/open-telemetry/opentelemetry-go/blob/405a92ab3ed715c5aa0bf10c47e4b2d8e071861c/sdk/metric/controller/push/push.go#L76-L92

**Do you envision that being configurable?** I noticed that that's not someething
that's currently configurable in `stdout` either:

https://github.com/open-telemetry/opentelemetry-go/blob/405a92ab3ed715c5aa0bf10c47e4b2d8e071861c/exporter/metric/stdout/stdout.go#L134

(please let me know if I got something wrong - have been trying the sdk out
today for the first time)

Thank you!

**Comment by MrAlias** [comment]
This is probably something that we should add to the `Config`s for each exporter.

**Comment by matej-g** [comment]
Is `Config` the right place though? To me it seems that `Config` is something that is tightly related to the actual exporter, while the parameter in question is related to a component further down the pipeline (controller). Maybe the frequency could be passed to the method initializing new pipeline (`NewExportPipeline`)?

**Comment by MrAlias** [comment]
@matej-g that is a good point. I agree, let's add a new parameter to the `NewExportPipeline` function.

**Comment by matej-g** [comment]
Great, if there are no takers, happy to take this one 🙂

**Comment by wingyplus** [comment]
Is `NewExportPipeline` function that living inside in each `export/metric` providers?

**Comment by lizthegrey** [comment]
are you still working on this @matej-g? Otherwise I might toss this onto @rebeccajae's plate.

**Comment by matej-g** [comment]
Unfortunately didn't get a chance to start yet and, as I'll be going on a short hiatus later this week, I'm happy to pass this onto someone else :)

**Comment by rghetia** [comment]
@rebeccajae will you be able to take this?

**Comment by rebeccajae** [comment]
Yeah, I can take a look!
