### ISSUE TITLE
Use gosec via golangci-lint

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go#4597]
### Problem Statement

The https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/.github/workflows/gosec.yml is failing.
See: https://github.com/open-telemetry/opentelemetry-go-contrib/actions/workflows/gosec.yml

### Proposed Solution

Add `gosec` linter to `.golangci.yml` (see: https://golangci-lint.run/usage/linters/#gosec)

This reduces the number linters, GitHub workflows. Also we could use `.golangci.yml` to configure the `gosec` linter and use the `//nolint` comments to silence some false postivies.

This issue applies to both repositories:
- https://github.com/open-telemetry/opentelemetry-go
- https://github.com/open-telemetry/opentelemetry-go-contrib

**Comment by sakshi-1505** [comment]
@pellared Can you assign this to me?

**Comment by pellared** [comment]
@sakshi-1505 Done
