### ISSUE TITLE
Better attributes for ignored parents

### ISSUE THREAD

**Issue by krnowak** [open-telemetry/opentelemetry-go#461]
When #451 gets merged, we will get the `WithNewRoot()` option, that will ignore local and remote parents in the context and create a span with a new trace ID. The ignored parents will end up as links with a string attribute being `"ignored-on-demand": "local"` or `"ignored-on-demand": "remote"` for local and remote parents, respectively.

This needs a better name and likely some piece of specification in SDK.

**Comment by jmacd** [comment]
I agree that the spec should discuss this. Does the spec describe `WithNewRoot()`?

**Comment by krnowak** [comment]
Not outright, no. There is a confusing sentence in https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-tracing.md#span-creation (in the the second bullet point): API MAY also have an option for implicit parenting from the current context as a default behavior. So we introduce an option for "explicit non-parenting". ;)

So not sure about the way forward with it - OTEP or a PR to spec?

**Comment by jmacd** [comment]
I think a PR to the spec would be appropriate.

**Comment by krnowak** [comment]
So, went through the spec and found a sentence in a paragraph after the bullet points: "Implementations MUST provide an option to create a `Span` as a root span, and MUST generate a new `TraceId` for each root span created.".

So I think the `WithNewRoot` as an option is already covered, but added some wording for adding the parents as links, please see the PR here: https://github.com/open-telemetry/opentelemetry-specification/pull/436.

**Comment by MrAlias** [comment]
Given the specification has deferred this decision we should back out the attributes that we are setting. This will ensure we are able to add them back in in a compatible manner after GA.

**Comment by MrAlias** [comment]
We need to remove the links (so we do not have to introduce breaking changes), document how users can add their own links if they want them, and wait for the specification to come to a consensus on this (https://github.com/open-telemetry/opentelemetry-specification/issues/1188).
