### ISSUE TITLE
Starting span with fresh SpanContext together with WithTraceID and WithSpanID creates a nonRecordingSpan

### ISSUE THREAD

**Issue by renta** [open-telemetry/opentelemetry-go#4621]
### Description

This is not a bug but a description of some weird behavior of Opentelemetry-Go library. When we create a fresh span from a Start method - it produces a normal recordingSpan. But if we want to bypass a tracing info (for example from a 3-rd party system which does not have Otel integration) with this code:

```golang
traceID, err := trc.TraceIDFromHex("965b5a5c2dc31e184315335ad7c09b77")
if err != nil {
	t.Fatalf(err.Error())
}
spanID, err := trc.SpanIDFromHex("c383b44aa60317c2")
if err != nil {
	t.Fatalf(err.Error())
}

ctx, span := tracer.Start(trc.ContextWithSpanContext(
	ctx, trc.SpanContext{}.WithTraceID(traceID).WithSpanID(spanID)),
	"test",
)
``` 
a newly created span would be a nonRecordingSpan. This could create problems with other subsystems: for ex. logger could enrich every log record with trace and span ids but do it only if `span.IsRecording()` and `spanContext.IsValid()`. In case of nonRecordingSpan a `IsRecording()` will return false. This issue could be overcome with https://github.com/renta/diff-traces/blob/master/main_test.go#L85 `trace.WithSampler(trace.AlwaysSample())` in the tracer provider, but I suppose that all the spans should be recorded out-of-a-box, and if the system is facing some resources troubles then provider samplers must be used by a developer. Not the opposite way.

### Environment

- OS: Linux
- Architecture: amd64
- Go Version: 1.19
- opentelemetry-go version: v1.19.0

### Steps To Reproduce

See unit-tests https://github.com/renta/diff-traces for an illustration.

### Expected behavior

I suppose that all the newly created span should be recorded.

**Comment by MrAlias** [comment]
> ### Expected behavior
> I suppose that all the newly created span should be recorded.

This would be behavior contrary to the specification: https://github.com/open-telemetry/opentelemetry-specification/blob/eda62e4baf906ac8225a9ee69fa97ff7f48dbccc/specification/trace/api.md#wrapping-a-spancontext-in-a-span

The current behavior seems to conform to the specification as your example demonstrates.

**Comment by renta** [comment]
Ok, thank you for the reply. What is a convenient way to bypass a tracing info? Do the spec force developers to create propagators https://github.com/open-telemetry/opentelemetry-specification/blob/eda62e4baf906ac8225a9ee69fa97ff7f48dbccc/specification/context/api-propagators.md#propagators-api ? Manual context creation (with `SpanContext{}.WithTraceID(traceID).WithSpanID(spanID))`) looks easy and clear for me.

**Comment by pellared** [comment]
From the description, I think you want to create a propagator as then you could then integrate it with instrumentation libraries.

> Manual context creation (with SpanContext{}.WithTraceID(traceID).WithSpanID(spanID))) looks easy and clear for me.

Look at https://pkg.go.dev/go.opentelemetry.io/otel/trace#NewSpanContext. You would probably need it even if you decide to implement a propagator. Example propagator:  https://github.com/open-telemetry/opentelemetry-go/blob/main/propagation/trace_context.go

**Comment by pellared** [comment]
@renta Is there anything that we should address as part of this issue or can we close it?

**Comment by renta** [comment]
@pellared Thank you for the answers. I suppose this issue could be closed.
