### ISSUE TITLE
Remove Gauge Instrument

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#463]
As per https://github.com/open-telemetry/oteps/pull/80 and https://github.com/open-telemetry/opentelemetry-specification/pull/430, the Gauge instrument needs to be removed.

A solution for this issue should wait for #423 to be addressed first as this introduces the replacement we decided is needed for this instrument.

**Comment by paivagustavo** [comment]
Fixed by #537
