### ISSUE TITLE
Use tilde range to specify Go version in CI

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go#4639]
> > When `check-latest: true` is used we can change the `go-version` values to `"1.20"` and `"1.21"`. Can I do this (upvote) or do you prefer to still keep the explicit minimal patch version (downvote)?
> 
> I would rather keep the minimums pegged above versions with CVEs. This will help ensure no issues are re-introduced.

@MrAlias, what do you mean by re-introducing? A regression bug that we remove `check-latest: true`? If this would happen we would simply add it back.

Is your intention that we bump the version each time a Go patch is released? If so then why maybe we should be pinning to the Go version instead e.g. `go-version: "1.21.3"? This would give the advantage of having more reproducible builds. But then we should also probably consistently pin other things e.g. the GitHub Action versions.

_Originally posted by @pellared in https://github.com/open-telemetry/opentelemetry-go/issues/4617#issuecomment-1762631915_

**Comment by pellared** [comment]
> we should pin the minimum version allowed

Feels YAGNI as `check-latest: true` ensures that the latest released version is used.

**Comment by MrAlias** [comment]
If there are security fixes, I would agree that we should ensure the project is not using these versions through all means possible.

**Comment by pellared** [comment]
I will create a PR on Wednesday.
