### ISSUE TITLE
otlptrace: Support OTEL_EXPORTER_OTLP_PROTOCOL and OTEL_EXPORTER_OTLP_TRACES_PROTOCOL environmental variables

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go#4642]
Reference https://github.com/open-telemetry/opentelemetry-specification/issues/3721#issuecomment-1761995814

Design described [here](https://github.com/open-telemetry/opentelemetry-go/issues/4641#issuecomment-1764204979)

**Comment by cbandy** [comment]
Related: #4641

**Comment by pellared** [comment]
On hold. See https://github.com/open-telemetry/opentelemetry-specification/issues/3721#issuecomment-1771553380

**Comment by pellared** [comment]
Closing per https://github.com/open-telemetry/opentelemetry-specification/pull/3730
