### ISSUE TITLE
otlptracegrpc otlpconfig adds DialOptions to DialOptions if has DialOptions

### ISSUE THREAD

**Issue by rackerWard** [open-telemetry/opentelemetry-go#4665]
### Description

It is not clear what is the intent of the following code https://github.com/open-telemetry/opentelemetry-go/blob/main/exporters/otlp/otlptrace/otlptracegrpc/internal/otlpconfig/options.go#L144

```
	if len(cfg.DialOptions) != 0 {
		cfg.DialOptions = append(cfg.DialOptions, cfg.DialOptions...)
	}
```

### Environment

- Architecture: [e.g. x86, i386]
- Go Version: [e.g. 1.15]
- opentelemetry-go version: [e.g. v0.14.0, 3c7face]

### Steps To Reproduce

1. Use the configuration '...'
2. Run '...'
3. See error

**Comment by pellared** [comment]
Thank you for reporting. I created https://github.com/open-telemetry/opentelemetry-go/pull/4684
