### ISSUE TITLE
sdk/metric does not respect metric.WithInstrumentationAttributes

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go#4687]
### Description

The metrics SDK does not add attributes added using [metric.WithInstrumentationAttributes](https://pkg.go.dev/go.opentelemetry.io/otel/metric#WithInstrumentationAttributes)

Reported via Gophers Slack: https://gophers.slack.com/archives/CK623313R/p1698843326696549

### Environment

- OS: any
- Architecture: any
- Go Version: 1.21
- opentelemetry-go version: v1.19.0

### Steps To Reproduce

https://go.dev/play/p/eoD76GfYWnz

```go
package main

import (
	"context"
	"log"

	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/exporters/stdout/stdoutmetric"
	metricapi "go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/sdk/metric"
	"go.opentelemetry.io/otel/sdk/resource"
)

func main() {
	metricExporter, err := stdoutmetric.New()
	if err != nil {
		log.Fatalln(err)
	}
	reader := metric.NewPeriodicReader(metricExporter)

	meterProvider := metric.NewMeterProvider(
		metric.WithResource(resource.Empty()),
		metric.WithReader(reader),
	)

	m := meterProvider.Meter("my-package", metricapi.WithInstrumentationAttributes(attribute.Key("foo").Int(42)))
	cnt, _ := m.Int64Counter("count")
	cnt.Add(context.Background(), 1)

	err = meterProvider.Shutdown(context.Background())
	if err != nil {
		log.Fatalln(err)
	}
}
```

Output:

```
{"Resource":null,"ScopeMetrics":[{"Scope":{"Name":"my-package","Version":"","SchemaURL":""},"Metrics":[{"Name":"count","Description":"","Unit":"","Data":{"DataPoints":[{"Attributes":[],"StartTime":"2009-11-10T23:00:00Z","Time":"2009-11-10T23:00:00Z","Value":1}],"Temporality":"CumulativeTemporality","IsMonotonic":true}}]}]}
```

### Expected behavior

The data points for `count` has `foo` attribute with value `42` .

**Comment by MrAlias** [comment]
> The data points for `count` has `foo` attribute with value `42` .

Instrumentation attributes would be added to the scope, not the instrument. 


They are currently dropped because we do not have a resolution to https://github.com/open-telemetry/opentelemetry-go/issues/3368. Namely, have the specification define a way to export these.

**Comment by pellared** [comment]
Duplicate of https://github.com/open-telemetry/opentelemetry-go/issues/3368
