### ISSUE TITLE
Instrument OpenTelemetry for multiple pkgs under same project

### ISSUE THREAD

**Issue by lesscodingmorehappiness** [open-telemetry/opentelemetry-go#4689]
Hi,

I'm trying to instrument OpenTelemetry Audit for my project. My case is: my go codes will be built as docker images and pushed to AKS pods; The application has multiple parts, so it has several different images, which means on source code side there are multiple go pkgs, each has its own main function.

I want to confirm that:
I think I need to instrument OpenTelemetry separately for every package? e.g. I need to initialize the OpenTelemetry SDK (create otel.go) in every pkg?

Thanks

**Comment by MrAlias** [comment]
1. You will need an instantiated `TracerProvider`/`MeterProvider` per process. This usually breaks down to one per `main` func.
2. Use one `Tracer`/`Meter` per package, roughly.

**Comment by pellared** [comment]
@lesscodingmorehappiness does it answer your question? Can we close the issue?
