### ISSUE TITLE
Use url.PathUnescape rather than url.QueryUnescape when parsing OTLP headers and resource attributes env vars

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go#4698]
I noticed that the enhancement done in https://github.com/open-telemetry/opentelemetry-go/pull/4667 is probably also worth doing for:
- parsing the `OTEL_EXPORTER_OTLP_HEADERS`, `OTEL_EXPORTER_OTLP_TRACES_HEADERS`, `OTEL_EXPORTER_OTLP_METRICS_HEADERS` env vars
- parsing `OTEL_RESOURCE_ATTRIBUTES` env var

**Comment by mikeblum** [comment]
👋 happy to take this issue on for contribfest - otel at kubecon NA '23

**Comment by pellared** [comment]
Fixed by https://github.com/open-telemetry/opentelemetry-go/pull/4699
