### ISSUE TITLE
Provide standard Tracer interface for all exporters

### ISSUE THREAD

**Issue by zetaab** [open-telemetry/opentelemetry-go#4700]
### Problem Statement

With opentracing there was interface `opentracing.Tracer` (https://github.com/opentracing/opentracing-go/blob/master/tracer.go#L7) that all different exporters implemented somehow. This did it quite easy to implement application to support many different tracers. Example from traefik/traefik: it supports opentelemetry, zipkin, jaeger, instana, haystack, elastic and datadog. All through this interface.

However, now with opentelemetry there is no such interface. If I try to use `trace.Tracer` (https://github.com/open-telemetry/opentelemetry-go/blob/main/trace/trace.go#L504) Any of these [exporters](https://github.com/open-telemetry/opentelemetry-go/tree/main/exporters) are not working with the interface implementation. So it is really difficult to make any interface implementations with opentelemetry. Or is there something that I am missing here?

### Proposed Solution

Make it clear that there is interface x that every trace exporter should implement. Otherwise opentelemetry is just big mess to implement to applications.

**Comment by pellared** [comment]
Are you looking for https://pkg.go.dev/go.opentelemetry.io/otel/sdk/trace#SpanExporter?

**Comment by zetaab** [comment]
yeah well `tracerProvider.Tracer(serviceName)` was basically what I was looking for
