### ISSUE TITLE
Document PR commits preference in CONTRIBUTING.md

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go#4701]
Checked `CONTRIBUTING.md` but I wasn't sure if squashing was enabled or not for PRs so I did it manually. Thanks for pushing up your suggestions!

_Originally posted by @mikeblum in https://github.com/open-telemetry/opentelemetry-go/issues/4699#issuecomment-1803850919_

I think we should document that we prefer if people just add commits, including merge commits and avoid force pushes. Rewriting history makes reviewing harder.  We can even say that we do "squash merge".

**Comment by mikeblum** [comment]
🤚 I'll update the docs
