### ISSUE TITLE
make precommit: emit a non-zero error code for golangci-lint fixes

### ISSUE THREAD

**Issue by mikeblum** [open-telemetry/opentelemetry-go#4703]
### Problem Statement

As a new contributor to the `opentelemetry-go` project; I was caught off-guard by `make precommit` making "silent" changes to my PR. Unless I ran `git status` after running `make precommit` I was unaware that `golangci-lint --fix` had made any changes and as such failed to push those changes up to my PR.

https://github.com/open-telemetry/opentelemetry-go/pull/4699#issuecomment-1802770553

### Proposed Solution

To give contributors a signal that they need to commit changes made by `make precommit` I propose we capture the exit code of `golangci-lint` before we invoke `--fix` and pass that error code / diff to stdout/err for visibility that changes were made.

#### Alternatives

Ideally we should only run `golangci-lint` once. But unfortunately the `golangci-lint` API only emits error codes for issues found, not fixes:

https://golangci-lint.run/usage/configuration/#command-line-options

We already have:

```
--issues-exit-code int           Exit code when issues were found (default 1)
```

set explicitly here: https://github.com/open-telemetry/opentelemetry-go/blob/main/.golangci.yml#L3

Alternatively we could open an issue with the upstream `golangci-lint` project to add a:

```
--fixes-exit-code int           Exit code when fixes were made (default 0)
```

#### Prior Art

???

### Additional Context

???

**Comment by pellared** [comment]
The `CONTRIBUTING.md` says that `git status` has to be run.

https://github.com/open-telemetry/opentelemetry-go/blob/main/CONTRIBUTING.md?plain=1#L36-L38

There are other targets (code generation) which would have the same problem.

If exit code would be different than 0 then the make execution would be interrupted which I find inconvenient during development.

**Comment by mikeblum** [comment]
That's a good point that altering the exit code would interrupt other downstream `make` steps. 🤔Could we add a `git status` call after `golangci-lint --fix` so we get the visual indication without breaking workflows? Or would that get too noisy?

**Comment by pellared** [comment]
There is a `make ci` for that.

**Comment by mikeblum** [comment]
Fair enough - I guess my question is why does `git status` need to be run manually after invoking `make precommit`?

**Comment by pellared** [comment]
`precommit` name suggests that you use the target before committing so you expect to have some local changes.
