### ISSUE TITLE
Tracing broken after version bump

### ISSUE THREAD

**Issue by memeToasty** [open-telemetry/opentelemetry-go#4713]
### Description

The `SetTracerProvider` method of `go.opentelemetry.io/otel` is now incompatible with `TracerProvider`'s built from `go.opentelemetry.io/otel/sdk/trace`.
I have read the notification about the breaking change, but given the short description, it is unclear to me how I should fix this now.

### Environment

- OS: WSL
- Architecture: x86
- Go Version: 1.21.3
- opentelemetry-go version: v1.20.0

### Steps To Reproduce

```go
import(
    "go.opentelemetry.io/otel"
    "go.opentelemetry.io/otel/sdk/trace"
)

provider := trace.NewTracerProvider()
otel.SetTracerProvider(provider)
```
This results in:
```
cannot use provider (variable of type *"go.opentelemetry.io/otel/sdk/trace".TracerProvider) as "go.opentelemetry.io/otel/trace".TracerProvider value in argument to otel.SetTracerProvider: *"go.opentelemetry.io/otel/sdk/trace".TracerProvider does not implement "go.opentelemetry.io/otel/trace".TracerProvider (missing method tracerProvider)compiler[InvalidIfaceAssign](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#InvalidIfaceAssign)
```
### Expected behavior

No compilation errors

**Comment by dmathieu** [comment]
Have you upgraded both the API and the SDK?

**Comment by memeToasty** [comment]
I am sorry, after `go get -u ./...` everything seems to compile again

**Comment by gaby** [comment]
@memeToasty Is that really the fix? I updated all my packages and I'm unable to build/run tests after v1.20.x

**Comment by memeToasty** [comment]
At least for me this was the fix, I dont know about your particular setup
