### ISSUE TITLE
new trace.Tracer interface is impractical

### ISSUE THREAD

**Issue by Malufasu** [open-telemetry/opentelemetry-go#4714]
### Problem Statement

The new trace.Tracer interface (v1.20.0 exposes a private func: tracer().
This stops users from wrapping it easily, as in this use case that does not implement the interface anymore:
```Go
type wrapedTracer struct{
   trace.Tracer
}

func (wp *wrappedTracer) Start(ctx context.Context, spanName string, opts ...trace.SpanStartOption) (context.Context, trace.Span){
  spanCtx,span := wp.tracer.Start(ctx,spanName,opts...)
  // log the span ID or anything else
}
```

### Proposed Solution

Remove the tracer() func from the exposed interface (if need be, use another interface internally for the lib)

**Comment by pellared** [comment]
This interface does not conforms the Go API stability policy as it was noted for a long time here: https://github.com/open-telemetry/opentelemetry-go/blob/v1.19.0/trace/trace.go#L489.

We have a need to add new functionality to the trace API interfaces therefore we decided to go with the "embeded" design (that is also used in metrics API) to break the compilation only once instead of doing it each time we want to add a new feature. We totally understand the inconvenience but we have not found any other way to add new functionality exposed by OTel APIs.

Related issues:
- https://github.com/open-telemetry/opentelemetry-go/issues/4160
- https://github.com/open-telemetry/opentelemetry-go/issues/3920
- https://github.com/open-telemetry/opentelemetry-go/issues/3919

**Comment by pellared** [comment]
FYI @EdSchouten @micronull

**Comment by Malufasu** [comment]
@dashpole @MrAlias  the fib example indeed works but I do something a bit different:

```Go
type wrappedTracer struct{
   trace.Tracer
}

func (wp *wrappedTracer) Start(ctx context.Context, spanName string, opts ...trace.SpanStartOption) (context.Context, trace.Span){
  spanCtx,span := wp.tracer.Start(ctx,spanName,opts...)
  // log the span ID or anything else
}

func newWrappedTracer(name string) *wrappedTracer {
	return &wrappedTracer{Tracer: otel.Tracer(name)}
}

func someHandlingFunc (ctx context.Context, tracer trace.Tracer) error {
  _, span := tracer.Start(ctx, "Handling")
  // ...
  return span.End()
}

type duplicateTracer interface{
  Start(ctx context.Context, spanName string, opts ...trace.SpanStartOption) (context.Context, trace.Span)
}

func someFixedHandlingFunc (ctx context.Context, tracer duplicateTracer) error {
  _, span := tracer.Start(ctx, "Handling")
  // ...
  return span.End()
}

func main() {
  tracer := newWrappedTracer("myProgram")
  runCtx, runSpan := tracer.Start(context.Background(), "Run") // This works
  someHandlingFunc(runCtx, tracer)                             // This does not since *wrappedTracer does not implement the private func
  someFixedHandlingFunc(runCtx, tracer)                        // This works again with a workaround
  runSpan.End()
}
```

Since my use case does not need to modify the trace.Tracer interface, I had first settled on using it in my internal functions signature, which cannot be done anymore.

This is a bit specific of a use case since wrapping functions this way is not the preferred way of doing things in golang, though (as far as I am aware)

**Comment by Malufasu** [comment]
just to clarify my understanding: is calling `otel.Tracer(name)` at every `Start()` what you mean by "using the API" ?

> @Malufasu I think your code should work if you are using the API:
> 
> I modified the fib example to wrap the Tracer from otel: [main...dashpole:opentelemetry-go:example_demonstration_wrapper](https://github.com/open-telemetry/opentelemetry-go/compare/main...dashpole:opentelemetry-go:example_demonstration_wrapper)
> 
> It compiles and runs without any issues.

**Comment by dashpole** [comment]
I just meant that `tracer.Tracer` is from the trace API package (go.opentelemetry.io/otel/trace.Tracer), since you didn't list the import.  Sorry for the confusion.

See https://pkg.go.dev/go.opentelemetry.io/otel/trace#hdr-API_Implementations for the guidance around this.  We would recommend:

```golang
type duplicateTracer interface{
  noop.Tracer
  Start(ctx context.Context, spanName string, opts ...trace.SpanStartOption) (context.Context, trace.Span)
}
```

**Comment by Malufasu** [comment]
Noted,
thank you for your answers, this implementation indeed fixes the issue :)

```Go
// This type will satisfy trace.Tracer interface
// and allow overriding what we want
type wrappedTracer struct{
   // embedded tracer (default behaviour)
   noop.Tracer
   // the tracer that will get wrapped
   wrapped trace.Tracer
}

func (wp *wrappedTracer) Start(ctx context.Context, spanName string, opts ...trace.SpanStartOption) (context.Context, trace.Span){
  spanCtx,span := wp.wrapped.Start(ctx,spanName,opts...)
  // log the span ID or anything else
}
```

**Comment by Malufasu** [comment]
Should I close this issue ?
