### ISSUE TITLE
Prevent a span from being recorded

### ISSUE THREAD

**Issue by dlsniper** [open-telemetry/opentelemetry-go#4718]
### Problem Statement

I'm using AWS SDK v2 for Go and the SQS ReceiveMessage method.
I want to instrument that call.
However, the API can return an error if there's nothing to receive after a certain period, specifically, a maximum of 20 seconds.
So, I want to prevent a started span from being recorded when the timeout error is encountered.

Here's what the code looks like:

```go
func receiveMessage(ctx context.Context, queueURL string) (*sqs.ReceiveMessageOutput, error) {
	ctx, span := tracing.NewSpan(ctx, "sqs.ReceiveMessage")
	defer span.End()

	params := sqs.ReceiveMessageInput{
		QueueUrl:              ptr.String(queueURL),
		MaxNumberOfMessages:   10,
		VisibilityTimeout:     60,
		WaitTimeSeconds:       20
	}
	return awsSQS.ReceiveMessage(ctx, &params)
}
```

### Proposed Solution

I want to call a method like `Drop()` that allows the current span to be omitted.
The rest of the operations on the span should still be performed, e.g., setting attributes, but when calling the `End` method, it should not record the span.

```go
span.Drop()
```

#### Alternatives

```go
span.Delete()
span.SetRecording(false)
```

#### Prior Art

I have yet to research this.

### Additional Context

-

**Comment by dmathieu** [comment]
Introducing a new span method your mean going through a specification update (then, every language would have to implement it).

However, you can already achieve this with a custom exporter which would skip spans if you detect they match a drop value (an attribute for example) and pass all the other ones to the struct doing the actual export.

**Comment by dlsniper** [comment]
@dmathieu for those of us who haven't a clue where to start doing this, can you please point me in the direction of where I learn more about doing this?

**Comment by dmathieu** [comment]
There is a [SpanExporter](https://pkg.go.dev/go.opentelemetry.io/otel/sdk/trace#SpanExporter) interface, which you can implement. The `ExportSpans` method takes a slice of read-only spans.

When you initialise the SDK, you can pass an exporter with the [WithBatcher](https://pkg.go.dev/go.opentelemetry.io/otel/sdk/trace#WithBatcher) method.

The idea here is to implement your own SpanExporter, and provide it with a child exporter (which will be an [otlp exporter](https://pkg.go.dev/go.opentelemetry.io/otel/exporters/otlp/otlptrace) for example).
When `ExportSpans` is called, the exporter would do any filtering you need, before calling `ExportSpans` with the new slice of spans.

**Comment by dlsniper** [comment]
Thank you!

**Comment by pellared** [comment]
@dlsniper Can we close this issue or do you have any other questions?

**Comment by dlsniper** [comment]
I guess we can close it.
