### ISSUE TITLE
uploadTrace by grpc has something wrong

### ISSUE THREAD

**Issue by bai-ming** [open-telemetry/opentelemetry-go#4728]
### Description

I send the trace to tempo, the code works without any error, but I can't find the trace in tempo.

### Environment

- Go Version: 1.19
- opentelemetry-go version: v1.14.0

### Steps To Reproduce
I set tp with code below
```go
func InitTracerProvider() error {
	exp, err := newExporter(utils.OsSignalHandler.SubContext())
	// exp, err := newStdOutExporter()
	if err != nil {
		return errors.Wrap(err, "")
	}
	tp = sdk.NewTracerProvider(
		sdk.WithBatcher(exp),
		sdk.WithIDGenerator(newTempIDGenerator()),
		sdk.WithResource(newResource()),
	)
	otel.SetTracerProvider(tp)
	return nil
}

func newExporter(ctx context.Context) (*otlptrace.Exporter, error) {
		tempo := "localhost:4317"
		exp, err := otlptracegrpc.New(ctx, otlptracegrpc.WithInsecure(), otlptracegrpc.WithEndpoint(tempo))
		return exp, errors.Wrap(err, "exporter init failed")
}
```
when I use v1.14.0
![image](https://github.com/open-telemetry/opentelemetry-go/assets/85221235/cff193f8-77a0-4151-a9cb-bedbe6d77f8d)
It works well, It sends message without error and I can find the trace in tempo which I send.
![image](https://github.com/open-telemetry/opentelemetry-go/assets/85221235/8b7af34c-6e2b-4bb9-8cc6-fc2ed5b45ea3)
![image](https://github.com/open-telemetry/opentelemetry-go/assets/85221235/3eed2697-eb7d-4f23-b124-289cd5acde72)
But when I use v1.21.0,
![image](https://github.com/open-telemetry/opentelemetry-go/assets/85221235/3ee6a284-6f7e-4ef0-8ab0-dc6f4338720a)
It still sends message without any error but I can't find it in tempo.
![image](https://github.com/open-telemetry/opentelemetry-go/assets/85221235/d3a2fbf8-e900-472f-87c1-080492880aae)
![image](https://github.com/open-telemetry/opentelemetry-go/assets/85221235/2ffd22fa-3fa9-4e79-958b-a21aee32a1ea)
And tempo dose not have any error log.

the difference about two version mod is the picture below
![image](https://github.com/open-telemetry/opentelemetry-go/assets/85221235/c9201412-9d71-4c16-b212-bb2f998fc7d7)

So perhaps It has something about the package?

**Comment by pellared** [comment]
From the description I do not see any proof that something is wrong with the exporter.
Also the reproduction steps are not precise (not working code, missing info about Grafana Tempo version and its configuration). Please provide [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

However, I personally suggest creating an issue in https://github.com/grafana/tempo. If there is a bug in our exporter, their maintainers should be able to locate the problem.

**Comment by Tsuribori** [comment]
I have run into the same issue when going from `v1.16.0` library versions to `v1.19.0`, and the issue persists in `v1.21.0`. It doesn't seem to be a Tempo issue as it affects also Jaeger. I tested with Tempo 2.1.1, Tempo 2.3.1 and Jager `jaegertracing/all-in-one:1.52` and the issue is present in all of them, they can't show traces correctly after the upgrade.

With `v1.16.0` in Jaeger:
![working](https://github.com/open-telemetry/opentelemetry-go/assets/30933799/26a32784-c093-4e7e-995b-7c7ac313d9ab)

With `v1.21.0` in Jaeger:
![not_working](https://github.com/open-telemetry/opentelemetry-go/assets/30933799/913328c1-ae17-4482-9d36-ef436af361bd)

Something funky seem to be going on...

The tracing setup code used is as following (with the `grpc` path):
```go
func Initialize() error {
	if !config.GetTracingEnabled() {
		return nil
	}

	insecure := config.GetTracingInsecureTransport()

	var tpo trace.TracerProviderOption
	switch config.GetTracingTransport() {
	case "grpc":
		opts := []otlptracegrpc.Option{
			otlptracegrpc.WithEndpoint(config.GetTracingEndpoint()),
		}
		if insecure {
			opts = append(opts, otlptracegrpc.WithInsecure())
		}
		exp, err := otlptracegrpc.New(context.Background(), opts...)
		if err != nil {
			return fmt.Errorf("building tracing exporter: %w", err)
		}
		tpo = trace.WithBatcher(exp)
	case "http":
		opts := []otlptracehttp.Option{
			otlptracehttp.WithEndpoint(config.GetTracingEndpoint()),
		}
		if insecure {
			opts = append(opts, otlptracehttp.WithInsecure())
		}
		exp, err := otlptracehttp.New(context.Background(), opts...)
		if err != nil {
			return fmt.Errorf("building tracing exporter: %w", err)
		}
		tpo = trace.WithBatcher(exp)
	default:
		return fmt.Errorf("invalid tracing transport: %s", config.GetTracingTransport())
	}
	r, _ := resource.Merge(
		resource.Default(),
		resource.NewWithAttributes(
			semconv.SchemaURL,
			semconv.ServiceName("GoToSocial"),
		),
	)

	tp := trace.NewTracerProvider(
		tpo,
		trace.WithResource(r),
	)
	otel.SetTracerProvider(tp)
	propagator := propagation.NewCompositeTextMapPropagator(
		propagation.TraceContext{},
		propagation.Baggage{},
	)
	otel.SetTextMapPropagator(propagator)
	log.Hook(func(ctx context.Context, kvs []kv.Field) []kv.Field {
		span := oteltrace.SpanFromContext(ctx)
		if span != nil && span.SpanContext().HasTraceID() {
			return append(kvs, kv.Field{K: "traceID", V: span.SpanContext().TraceID().String()})
		}
		return kvs
	})
	return nil
}
```

OpenTelemetry libraries used:
```
	go.opentelemetry.io/otel v1.21.0
	go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc v1.21.0
	go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp v1.21.0
	go.opentelemetry.io/otel/exporters/prometheus v0.44.0
	go.opentelemetry.io/otel/sdk v1.21.0
	go.opentelemetry.io/otel/sdk/metric v1.21.0
	go.opentelemetry.io/otel/trace v1.21.0
	github.com/uptrace/opentelemetry-go-extra/otelsql v0.2.2 // indirect
	go.opentelemetry.io/otel/exporters/otlp/otlptrace v1.21.0 // indirect
	go.opentelemetry.io/otel/metric v1.21.0 // indirect
	go.opentelemetry.io/proto/otlp v1.0.0 // indirect
```

Go version used is `1.21`

**Comment by pellared** [comment]
You miss error handling for `r, _ := resource.Merge`

My guess is that you have forgotten to bump the `semconv` in your import path to `semconv "go.opentelemetry.io/otel/semconv/v1.21.0"` when bumping OTel Go.

We are perfectly aware that this issue is annoying.

Reference: https://github.com/open-telemetry/opentelemetry-go/issues/2341

**Comment by Tsuribori** [comment]
> You miss error handling for `r, _ := resource.Merge`
> 
> My guess is that you have forgotten to bump the `semconv` in your import path to `semconv "go.opentelemetry.io/otel/semconv/v1.21.0"` when bumping OTel Go.
> 
> We are perfectly aware that this issue is annoying. Already tracked under: #2341

Ah! That was the problem, thank you.
