### ISSUE TITLE
Decompose opencensus

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go#4729]
I am not sure if we want the "Trace Bridge" and "OpenCensus-Metrics-Shim" to be contained in a single Go module.
The components have different dependencies (mainly OTel Trace API vs OTel Metrics SDK).

Maybe we should provide `opencensustrace` (or `octrace`)  and (or `ocmetric`) Go modules in subdirectories? I am leaning towards `oc*` package naming as `opensensus` will be already in the import path. Therefore, I propose `go.opentelemetry.io/otel/bridge/opencensus/octrace` and `go.opentelemetry.io/otel/bridge/opencensus/ocmetric`.

The current approach seems compliant with [the OTel Specification](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.27.0/specification/compatibility/opencensus.md). However, it does not follow the way we structure Go modules.

**Comment by dashpole** [comment]
Some counter points, although i'm not entirely against the idea:

* OpenCensus has traces and metrics in a single module. Using the bridge at least isn't a regression from that state.
* The bridge is a temporary crutch, which makes it more reasonable to have as a single module.
* One module is simpler for users.
* Java also has the trace and metrics bridge in the same thing (package?): https://github.com/open-telemetry/opentelemetry-java/tree/e6c7a0f264569a514df3caba0b7f59f80c4ba3d2/opencensus-shim/src/main/java/io/opentelemetry/opencensusshim

Curious what others think.

**Comment by MrAlias** [comment]
SIG meeting notes:

- There doesn't seem to be a strong desire for this refactor
- There isn't a strong opposition to the change either
- There are already about ~20 public packages that depend on this module structure: https://pkg.go.dev/go.opentelemetry.io/otel/bridge/opencensus?tab=importedby
  - This kind of a breaking change will affect these 20 known projects adversely
- This will require 3 releases to complete and then stabilize the OC bridge
  1. Split into new modules and deprecate the old
  2. Remove the old module
  3. Make an RC
- Given the lack of motivation by most contributors for this change (and slight apprehension). There needs to be a leader with a strong desire to make this change that will put in the effort to achieve this.
