### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#476]
- [ ] Drop the `go get` instructions in favor of `git clone`.
- [ ] Add paragraph explaining how to add OTel-go as a dependency to some project. I.e. user should use `go.opentelemetry.io/otel`, not `github.com/open-telemetry/opentelemetry-go`.

_Originally posted by @krnowak in https://github.com/open-telemetry/opentelemetry-go/pull/382#issuecomment-584818035_

**Comment by andrewhsu** [comment]
I'll take this one.

**Comment by rghetia** [comment]
@andrewhsu are you working on this?

**Comment by MikeGoldsmith** [comment]
I've provided a PR as @andrewhsu is fairly busy.
