### ISSUE TITLE
Unclear usage of semconv MessagingSystemKey

### ISSUE THREAD

**Issue by joreetz-otto** [open-telemetry/opentelemetry-go#4817]
### Problem Statement

Documentation about semconv MessagingSystemKey seem not clear to me. I cant tell if this field should be used for destination or source messaging system. The name of the field MessagingDestinationKey is clear in this case.

### Proposed Solution

Enhance the documentation about the purpose of the field.

**Comment by dmathieu** [comment]
Would the semantic conventions doc be more helpful there?
https://github.com/open-telemetry/semantic-conventions/blob/75f9d428a45f9e779b72c34d9ac3c00625b7472a/docs/attributes-registry/messaging.md

Improved documentation is always welcome though. Do you want to open a PR?

**Comment by joreetz-otto** [comment]
Thanks for this super fast reply. 
This documentation is also not clear in this case for me.

> An identifier for the messaging system being used. See below for a list of well-known identifiers.

I will for sure update the docs when i know the answer to this

I will open an issue in the linked repo.

**Comment by dmathieu** [comment]
I'm not sure I understand the source/destination messaging system there.
If you have a span reading from Kafka, that's what its messaging system is. If it's writing to RabbitMQ, that's what its messaging system is.

If you have a span both reading and writing, maybe there should be two spans to properly observe what's happening?

**Comment by pellared** [comment]
The docs are generated from https://github.com/open-telemetry/semantic-conventions/blob/v1.24.0/model/registry/messaging.yaml#L210-L245

Do you find these not good enough?
- https://github.com/open-telemetry/opentelemetry-go/blob/6ead8d80e8d27082face6ee11fe9b11844fa797f/semconv/v1.24.0/attribute_group.go#L2727-L2735
- https://github.com/open-telemetry/opentelemetry-go/blob/6ead8d80e8d27082face6ee11fe9b11844fa797f/semconv/v1.24.0/attribute_group.go#L2767-L2788

**Comment by joreetz-otto** [comment]
@dmathieu yes I think you are right that one should have a separate span for receive and send but even though you want to give some metadata about what happens inside the span and thats what these attributes are for in my opinion.
@pellared I cant answer my question from this documentation, so...

I just saw that there is the `MessagingOperationKey` which should resolve my issue.
