### ISSUE TITLE
Replace ensureAttributesCapacity with slices.Grow

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go#4819]
Replace ensureAttributesCapacity with slices.Grow once we drop support for Go 1.20.

> How about inlining the `slices.Grow` implementation instead of referencing `golang.org/x/exp`?

_Originally posted by @pellared in https://github.com/open-telemetry/opentelemetry-go/pull/4818#discussion_r1446458963_

**Comment by lizthegrey** [comment]
You also will, while you're in the same code, also want to change the `if x > y { foo(x) } else { foo(y) }` added in #4818 to a `min()` per go1.21.

**Comment by sumit1606** [comment]
@pellared Mind if I take a stab at it ?

**Comment by lizthegrey** [comment]
> @pellared Mind if I take a stab at it ?

go1.22 is not yet out, so go1.20 is still supported. Feel free to prepare, but do not land, a PR that does the cleanup I suggested.
