### ISSUE TITLE
The default endpoint should use HTTP, not HTTPS

### ISSUE THREAD

**Issue by edigaryev** [open-telemetry/opentelemetry-go#4834]
Here's an excerpt from the  [OpenTelemetry's mission statement](https://opentelemetry.io/community/mission/#we-value-_compatibility_):

>OpenTelemetry strives to be standards-compliant, vendor-neutral, and **consistent across languages and components**.

Now take a look at the following table:

| Language                                                                | Uses `http://localhost:PORT` endpoint by default                                                                                                                                                                                      |
|-------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| [C++](https://github.com/open-telemetry/opentelemetry-cpp)              | [Yes](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/exporters/otlp/README.md#configuration-options--otlp-http-exporter-)                                                                                              |
| [.NET](https://github.com/open-telemetry/opentelemetry-dotnet)          | [Yes](https://github.com/open-telemetry/opentelemetry-dotnet/blob/45cf7c3a25f768eca0a1b944120a4d28ae6ae33f/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpExporterOptions.cs#L37-L38)                                           |
| [Erlang/Elixir](https://github.com/open-telemetry/opentelemetry-erlang) | [Yes](https://github.com/open-telemetry/opentelemetry-erlang/blob/99e3eec90a287b0476f68c2f2289bd91c63b63c8/apps/opentelemetry_exporter/src/opentelemetry_exporter.erl#L113-L123)                                                      |
| [Go](https://github.com/open-telemetry/opentelemetry-go)                | [**No**](https://github.com/open-telemetry/opentelemetry-go/blob/33f5cf460bc0a2e4648e5f3fd8f2e4faa79ddb0e/exporters/otlp/otlpmetric/otlpmetrichttp/doc.go#L23)                                                                        |
| [Java](https://github.com/open-telemetry/opentelemetry-java)            | [Yes](https://github.com/open-telemetry/opentelemetry-java/blob/ede6a81a17298938ac8d7b4d836c17a7f4dec268/exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporterBuilder.java#L34-L35)              |
| [JavaScript](https://github.com/open-telemetry/opentelemetry-js)        | [Yes](https://github.com/open-telemetry/opentelemetry-js/blob/main/experimental/packages/exporter-logs-otlp-http/README.md#environment-variable-configuration)                                                                        |
| [PHP](https://github.com/open-telemetry/opentelemetry-php)              | [Yes](https://github.com/open-telemetry/opentelemetry-php/blob/1af83342f7c5827b282b311f0bd1e2e96ed71870/src/SDK/Common/Configuration/Defaults.php#L63)                                                                                |
| [Python](https://github.com/open-telemetry/opentelemetry-python)        | [Yes](https://github.com/open-telemetry/opentelemetry-python/blob/975733c71473cddddd0859c6fcbd2b02405f7e12/exporter/opentelemetry-exporter-otlp-proto-http/src/opentelemetry/exporter/otlp/proto/http/trace_exporter/__init__.py#L55) |
| [Ruby](https://github.com/open-telemetry/opentelemetry-ruby)            | [Yes](https://github.com/open-telemetry/opentelemetry-ruby/blob/main/exporter/otlp-http/README.md#how-can-i-configure-the-otlp-exporter)                                                                                              |
| [Rust](https://github.com/open-telemetry/opentelemetry-rust)            | [Yes](https://github.com/open-telemetry/opentelemetry-rust/blob/27d338dd954ef7681242ead47a8a61c964dcc428/opentelemetry-otlp/src/exporter/mod.rs#L55-L56)                                                                              |
| [Swift](https://github.com/open-telemetry/opentelemetry-swift)          | [Yes](https://github.com/open-telemetry/opentelemetry-swift/blob/be46a97818a74f9227fdac192e9f176b716e7435/Sources/Exporters/OpenTelemetryProtocolHttp/metric/OltpHTTPMetricExporter.swift#L11)                                        |

I've searched for the issues a bit and found https://github.com/open-telemetry/opentelemetry-go/issues/4147#issuecomment-1770564661, which argues against the change, saying that:

>One significant concern is that changing the default would break most code that is using secure HTTPS endpoints. Presently, the `otlptracehttp` lacks a `WithSecure` method, offering only an option for insecure connections.

However, I believe it is based on a false premise that we need treat all `OTEL_EXPORTER_OTLP_ENDPOINT`'s as HTTP by default.

What we need instead is to simply change the default `OTEL_EXPORTER_OTLP_ENDPOINT` value from `https://localhost:PORT` to `http://localhost:PORT`.

Moreover, I'd strongly argue that most people won't notice this change at all, because [almost everyone seems to run the OpenTelemetry Collector with the TLS disabled](https://github.com/search?q=receivers%3A+otlp%3A&type=code).

Cc: @pellared

**Comment by pellared** [comment]
Almost none is not nobody and it would be a breaking change for them. This issue was already discussed at least 2 times during SIG meetings and nobody was supporting such change.

**Comment by edigaryev** [comment]
>Most people is not everyone. For some it would be a breaking change for them.

Is there a policy for making breaking changes?

It seems that when a single component in a whole ecosystem deviates from the rest of that ecosystem, by making it conform, we will benefit not just this single component, but the whole ecosystem and its users in the long run, even if it involves making a breaking change.

>There is a more detailed explanation in the issue that you mentioned.

I've read it all, but I believe it is based on a false premise, which I've explained in https://github.com/open-telemetry/opentelemetry-go/issues/4834#issue-2090953051.

Could you please clarify this?

**Comment by pellared** [comment]
https://github.com/open-telemetry/opentelemetry-go/blob/main/VERSIONING.md

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/versioning-and-stability.md

**Comment by edigaryev** [comment]
Thanks!

So according to [VERSIONING.md](https://github.com/open-telemetry/opentelemetry-go/blob/main/VERSIONING.md), it seems that the change proposed here falls under the following statement:

>In addition to public APIs, telemetry produced by stable instrumentation will remain stable and backwards compatible. This is to avoid breaking alerts and dashboard.

Could this change be scheduled for `v2` (perhaps added to a milestone or a roadmap)?

**Comment by pellared** [comment]
> SDK stability, as defined above, will be maintained for a minimum of one year after the release of the next major SDK version.

Right now, I do not see any `v2` label/milestone and we have more TODO than we are able to handle 😢 I am not sure if we want (or be able) to ever release a v2. I will discuss it during SIG meeting.

**Comment by pellared** [comment]
Closing as, according to my knowledge, the SIG is against creating a `v2` until necessary. This proposal is not strong enough to create a `v2`. At last, I am not sure if we would even agree that this change is good as we preferred to be "secure by default" .

**Comment by tmc** [comment]
This seems to put the go sdk out of compliance with the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md). 

If this isn't reverted I encourage documentation at https://github.com/open-telemetry/opentelemetry-go/blob/main/exporters/otlp/otlptrace/otlptracehttp/doc.go#L12 to be updated to point out that the default value for the go SDK is non-standard.

**Comment by dmathieu** [comment]
The default value is already documented on your link.

**Comment by tmc** [comment]
> The default value is already documented on your link.

Do you acknowledge that this diverges from the spec and that is harms developer experience?

**Comment by dmathieu** [comment]
This does diverge from the spec.
However, changing it on our end would be a breaking change, and I don't think the developer experience inconvenience here is worth doing a major release.
