### ISSUE TITLE
Prometheus exporter panics due to race condition 

### ISSUE THREAD

**Issue by neetle** [open-telemetry/opentelemetry-go#485]
I'm starting up a service with a handful of `latency`/`error`/`traffic` metrics, but no values are recorded against these for the first 1-2 seconds of the service. Whenever I hit the prometheus endpoint before any of the values are recorded, I'm getting the attached stack trace. 

I believe it's due to the gauge impl returning ErrNoLastValue and prometheus's NewRawExporter not setting the error handler.  

While I think that the gauge _should_ have a default value set by the user, I don't believe the library should panic with a nil pointer deref. 

Stack:
```
go.opentelemetry.io/otel/exporter/metric/prometheus.(*collector).exportGauge(0xc0000a0130, 0xc0000a89c0, 0x1f85658, 0xc000020c80, 0xc000020c00, 0xc00037e1c0, 0x1b73460, 0x0, 0x0)
        $GOMOD/go.opentelemetry.io/otel/exporter/metric/prometheus@v0.2.1/prometheus.go:228 +0x194
go.opentelemetry.io/otel/exporter/metric/prometheus.(*collector).Collect.func1(0xc0000728a0, 0x1b73460, 0x0, 0x0, 0x0, 0x0, 0x174d760, 0xc0001f3740, 0x1758160, 0xc000020c80)
        $GOMOD/go.opentelemetry.io/otel/exporter/metric/prometheus@v0.2.1/prometheus.go:220 +0x32c
go.opentelemetry.io/otel/sdk/metric/batcher/defaultkeys.(*checkpointSet).ForEach(0xc00025ad60, 0xc00025ae40)
        $GOMOD/go.opentelemetry.io/otel@v0.2.1/sdk/metric/batcher/defaultkeys/defaultkeys.go:158 +0xd7
go.opentelemetry.io/otel/sdk/metric/controller/push.syncCheckpointSet.ForEach(0xc00020a388, 0x174d780, 0xc00025ad60, 0xc00025ae40)
        $GOMOD/go.opentelemetry.io/otel@v0.2.1/sdk/metric/controller/push/push.go:196 +0x81
go.opentelemetry.io/otel/exporter/metric/prometheus.(*collector).Collect(0xc0000a0130, 0xc0000a89c0)
        $GOMOD/go.opentelemetry.io/otel/exporter/metric/prometheus@v0.2.1/prometheus.go:198 +0x88
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
        $GOMOD/github.com/prometheus/client_golang@v1.4.1/prometheus/registry.go:445 +0x164
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        $GOMOD/github.com/prometheus/client_golang@v1.4.1/prometheus/registry.go:535 +0xe12
exit status 2
```

**Comment by paivagustavo** [comment]
Hey @neetle, Thanks for filling this issue. 

You're correct when saying that the lib shouldn't panic because of such an error. The problem was that the `onError(err error)` method of the exporter was not being correctly initialized, causing a `nil pointer dereference` when some error occur. The "correct" default behavior is just print that no value was set and you can override this by changing the defining another `onError` function. 

This will be fixed on #486
