### ISSUE TITLE
Document experimental feature

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#4875]
I am afraid that having the docs for experimental features in `sdk/metric/EXPERIMENTAL.md` makes it not discoverable. Especially that we are not even referencing it in GoDocs. Maybe we should move this to `doc.go`?

This can be done as a separate PR.

_Originally posted by @pellared in https://github.com/open-telemetry/opentelemetry-go/pull/4871#discussion_r1472463374_

EDIT: SIG meeting:
Let's put the experimental docs in: https://pkg.go.dev/go.opentelemetry.io/otel/sdk/metric/internal/x

**Comment by Sanket-0510** [comment]
hey @pellared can I address this ?
