### ISSUE TITLE
Only last registered callback is called from observable instrument 

### ISSUE THREAD

**Issue by nikki-dzhurov** [open-telemetry/opentelemetry-go#4884]
---
name: Bug report
about: Observable metrics
title:  'Only last callback is called from observable instrument'
labels: bug
assignees: ''

---

### Description

It appears that since v1.22 the observable instruments started to invoke only the last registered callback. After short lookup at the code - it looks like there is a loop-var scope problem in `int64ObservableInstrument` func => https://github.com/open-telemetry/opentelemetry-go/blob/main/sdk/metric/meter.go#L149-L152 . 

The solution should be as simple as adding `cback := cback` at the beginning of the loop. I can try to resolve it myself but I have to get familiar with the contributing guidelines and the test setup of the project first

### Environment

- OS: linux
- Architecture: x86
- Go Version: 1.21
- opentelemetry-go version: v1.22.0

### Steps To Reproduce

1. Setup a meter - `meter = otel.Meter("")`
2. Create new Gauge for it with multiple callbacks - `meter.Int64ObservableGauge(name, cb1, cb2... cbN)`
3. Observe which callback are invoked during the collection

Sorry for the incomplete steps, in case it is not clear enough - I will try to provide more details. 

### Expected behavior

All registered callbacks to be invoked

**Comment by MrAlias** [comment]
Thank you for the feedback. The issue you describe is not entirely clear. We test to ensure multiple callbacks are handled:

https://github.com/open-telemetry/opentelemetry-go/blob/e3eb3f7538e790a853c3ce210cf48123ddd5ca20/sdk/metric/meter_test.go#L238-L262

Please provide a complete run-able example that exemplifies your bug and include the seen behavior of that example and what you expect.

**Comment by MrAlias** [comment]
One thing to note is that multiple observations of the same attribute set will overwrite values within a collections cycle, regardless of the callback that is making the observation. If you are making the same observation of the same metric stream in multiple callbacks, it is up to you to coordinate the value you record in your code.

Not sure if this applicable given the uncertainty in the issue.

**Comment by nikki-dzhurov** [comment]
Thanks for looking into the issue. 
The test you pointed out registers single callback during the creation of the `Int64ObservableGauge` and another one through the metric. That is different from what I pointed in the 2nd step (in `Steps To Reproduce` section)

About the note -  the attribute sets are not in focus here (as the callbacks are not invoked regardless the behavior), but for sake of the completeness - I use callbacks which make observations on different attribute sets.

I imagine a test that would look like(sorry for the formatting, just using the browser):
```
		{
			name: "ObservableInt64Gauge - multiple callbacks",
			fn: func(t *testing.T, m metric.Meter) {
				cback := 
				gauge, err := m.Int64ObservableGauge(
                                 	"agauge",
                                 	metric.WithInt64Callback(func(_ context.Context, o metric.Int64Observer) error {
						o.Observe(4, attrSet1)
					 	return nil
				         }),
				         metric.WithInt64Callback(func(_ context.Context, o metric.Int64Observer) error {
					 	o.Observe(5, attrSet2)
					 	return nil
				         }),
				)
				assert.NoError(t, err)

			},
			want: metricdata.Metrics{
				Name: "agauge",
				Data: metricdata.Gauge[int64]{
					DataPoints: []metricdata.DataPoint[int64]{
						{Attributes: attrSet1, Value: 4},
						{Attributes: attrSet2, Value: 5},
					},
				},
			},
		},
```

**Comment by MrAlias** [comment]
Thanks. That's helpful. I think I found the issue:

https://github.com/open-telemetry/opentelemetry-go/blob/e3eb3f7538e790a853c3ce210cf48123ddd5ca20/sdk/metric/meter.go#L149-L152

**Comment by nikki-dzhurov** [comment]
Yes, the same as the one , pointed in the description :)  BTW I think the same thing is valid for `float64ObservableInstrument`:
https://github.com/open-telemetry/opentelemetry-go/blob/e3eb3f7538e790a853c3ce210cf48123ddd5ca20/sdk/metric/meter.go#L282-L285
