### ISSUE TITLE
Logs SDK design

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go#4896]
Create a design for Logs SDK similarly to https://github.com/open-telemetry/opentelemetry-go/pull/4809.

Prior art: https://github.com/open-telemetry/opentelemetry-go/pull/3606

**Comment by MrAlias** [comment]
Talking with @pellared offline, we likely want to try and use the OTLP proto as our data model if we can for the SDK:

- it is the only expected output format
- it will help preserve the optimizations we how to provide by default

We will need to look into if this is feasible. Namely, if it can be done without taking a dependency on gRPC.

**Comment by pellared** [comment]
> We will need to look into if this is feasible. Namely, if it can be done without taking a dependency on gRPC.

Related issues:
- https://github.com/open-telemetry/opentelemetry-proto-go/issues/100
- https://github.com/open-telemetry/opentelemetry-go/issues/2579

**Comment by pellared** [comment]
SIG meeting: 
Depending on OTLP Go-proto as our data model may lead to issues as there are no guarantee that `protoc-gen-go` will always generate backwards-compatible code. It would be safer if SDK defines the data model unless the benchmarks will show significant  differences to favor Go-proto code.
