### ISSUE TITLE
Implement the `Value` and `KeyValue` types

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#4914]
reference: https://github.com/open-telemetry/opentelemetry-go/pull/4725/files#diff-6176e76e800e6ce0edb44f3d31adaca4602b7cc03cbe54f5ea233a7f2edd17a0

- [ ] `Value` type
  - [ ] `Kind` method
  - [ ] `AsAny` method
  - [ ] `AsString` method
  - [ ] `AsInt64` method
  - [ ] `AsBool` method
  - [ ] `AsFloat64` method
  - [ ] `AsBytes` method
  - [ ] `AsSlice` method
  - [ ] `AsMap` method
  - [ ] `Empty` method
  - [ ] `Equal` method
  - [ ] `StringValue` function
  - [ ] `IntValue` function
  - [ ] `Int64Value` function
  - [ ] `Float64Value` function
  - [ ] `BoolValue` function
  - [ ] `BytesValue` function
  - [ ] `SliceValue` function
  - [ ] `MapValue` function
- [ ] `KeyValue` type
  - [ ] `Equal` method
- [ ] `String` function
- [ ] `Int64` function
- [ ] `Int` function
- [ ] `Float64` function
- [ ] `Bool` function
- [ ] `Bytes` function
- [ ] `Slice` function
- [ ] `Map` function
- [ ] Add tests to cover all added functionality

**Comment by MrAlias** [comment]
The reference implementation includes panics in many of the `Value` methods:

* https://github.com/open-telemetry/opentelemetry-go/pull/4725/files#diff-6176e76e800e6ce0edb44f3d31adaca4602b7cc03cbe54f5ea233a7f2edd17a0R151
* https://github.com/open-telemetry/opentelemetry-go/pull/4725/files#diff-6176e76e800e6ce0edb44f3d31adaca4602b7cc03cbe54f5ea233a7f2edd17a0R162
* https://github.com/open-telemetry/opentelemetry-go/pull/4725/files#diff-6176e76e800e6ce0edb44f3d31adaca4602b7cc03cbe54f5ea233a7f2edd17a0R171
* https://github.com/open-telemetry/opentelemetry-go/pull/4725/files#diff-6176e76e800e6ce0edb44f3d31adaca4602b7cc03cbe54f5ea233a7f2edd17a0R184
* https://github.com/open-telemetry/opentelemetry-go/pull/4725/files#diff-6176e76e800e6ce0edb44f3d31adaca4602b7cc03cbe54f5ea233a7f2edd17a0R200
* https://github.com/open-telemetry/opentelemetry-go/pull/4725/files#diff-6176e76e800e6ce0edb44f3d31adaca4602b7cc03cbe54f5ea233a7f2edd17a0R213
* https://github.com/open-telemetry/opentelemetry-go/pull/4725/files#diff-6176e76e800e6ce0edb44f3d31adaca4602b7cc03cbe54f5ea233a7f2edd17a0R226
* https://github.com/open-telemetry/opentelemetry-go/pull/4725/files#diff-6176e76e800e6ce0edb44f3d31adaca4602b7cc03cbe54f5ea233a7f2edd17a0R261
* https://github.com/open-telemetry/opentelemetry-go/pull/4725/files#diff-6176e76e800e6ce0edb44f3d31adaca4602b7cc03cbe54f5ea233a7f2edd17a0R287

Do we want to panic in these cases? This could cause runtime panics for users using OTel and it seems like it might be violating the [OTel exception policy](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/error-handling.md#basic-error-handling-principles).

**Comment by MrAlias** [comment]
Instead of panicking we could log an error and return a zero value?

Maybe also return a default value in the case of something like `func (*Value) String() string` which could just use `fmt.Sprint`?

**Comment by MrAlias** [comment]
For reference, the existing attribute package does not panic: https://github.com/open-telemetry/opentelemetry-go/blob/main/attribute/value.go

**Comment by pellared** [comment]
Given the OTel Spec says

> API methods MUST NOT throw unhandled exceptions when used incorrectly by end users. 

and what the existing attribute package does

I support @MrAlias the proposal:

> Instead of panicking we could log an error and return a zero value

**Comment by pellared** [comment]
I updated the prototype (reference implementation): 147762ff
