### ISSUE TITLE
Go semver seems not be consistant with otel semver spec

### ISSUE THREAD

**Issue by aygalinc** [open-telemetry/opentelemetry-go#4922]
Hi! 

It seems that go semver is not consistent with the otel semver spécification.
As example, semver in version 1.21.0 does not contain the breaking change on http label due to the alignement with ECS spec. 
It is a problem because exporter in otel contrib lib rely on this so actually on our system the exporter IS not able to do the mapping btw appinsight field and otel label.

**Comment by aygalinc** [comment]
Discover with : https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31255

**Comment by MrAlias** [comment]
Can you please provide specifics of your issue? What semantic conventions are you missing?

We generated [v1.21.0](https://pkg.go.dev/go.opentelemetry.io/otel@v1.23.1/semconv/v1.21.0) using the [v1.21.0 version of semantic conventions](https://github.com/open-telemetry/semantic-conventions/tree/v1.21.0). There shouldn't be anything missing.

**Comment by aygalinc** [comment]
By semantic conv i refer to : https://opentelemetry.io/docs/specs/semconv/http/http-spans/ .
It seems thatsome part of the info can be fined inl : https://github.com/open-telemetry/semantic-conventions/blob/main/model/http-common.yaml (the http.response.status_code for example) and specific tracing part in https://github.com/open-telemetry/semantic-conventions/blob/main/model/trace/http.yaml .

If i look the several code generation at some point the directory http and net start to deasepear in the opentelemtry-go repo. 
Maybe reference model used by your generator have been moved. 

I am not a go developer but happy to help if i can do something to restore this.

**Comment by MrAlias** [comment]
The evolution of semantic conventions is managed here: https://github.com/open-telemetry/semantic-conventions

They have made breaking changes in many of their subsequent releases. We package release version within their own Go package. Please refer to the appropriate [`semconv` package ](https://pkg.go.dev/go.opentelemetry.io/otel/semconv)that contains the things you need.

**Comment by MrAlias** [comment]
I'm going to close this as it seems like the issue here is a misunderstanding about the upstream semantic convention stability policy and how that is implemented in the Go project.

If you find an issue where one of our `semconv` packages does not contain a semconv value from the upstream repository please open a new issue targeted at that value.

**Comment by MrAlias** [comment]
@aygalinc heads up. The semconv package linked from https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31255 is not the same as https://pkg.go.dev/go.opentelemetry.io/otel/semconv

**Comment by aygalinc** [comment]
Oh sorry i Mixed the packagé when i navigate
