### ISSUE TITLE
Create Logs Bridge SDK Design Proposal

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#4950]
- [ ] Review the specification for what will be required by our implementation
  - [ ] Correct or clarify any issues found in the specification
- [ ] Add a design document to the project describing how we will implement the SDK

**Comment by MrAlias** [comment]
Talking with @pellared offline, we likely want to try and use the OTLP proto as our data model if we can for the SDK:

- it is the only expected output format
- it will help preserve the optimizations we how to provide by default

We will need to look into if this is feasible. Namely, if it can be done without taking a dependency on gRPC.

**Comment by pellared** [comment]
Is it not a duplicate of https://github.com/open-telemetry/opentelemetry-go/issues/4896?

**Comment by MrAlias** [comment]
> Is it not a duplicate of #4896?
