### ISSUE TITLE
log: Implement Stringer for Value and KeyValue

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go#4952]
The failure messages from assertions like this one (I changed the test to fail) convinced me to implement `Stringer`.

```
        	Error Trace:	/home/rpajak/repos/opentelemetry-go/log/keyvalue_test.go:81
        	Error:      	Not equal: 
        	            	expected: false
        	            	actual  : true
        	Test:       	TestValueEqual
        	Messages:   	{[] 2 0xc0001a4410}.Equal({[] 2 0xc0001a4410})
```

Reference: https://github.com/open-telemetry/opentelemetry-go/pull/4809#discussion_r1482157185

_Originally posted by @pellared in https://github.com/open-telemetry/opentelemetry-go/pull/4949#discussion_r1496608650_

**Comment by pellared** [comment]
I would like to have consensus if we want to have it in initial stable release.

@MrAlias, do I remember correctly that you suggested removing this issue from the Logs RC project? If so I am even leaning to closing this issue.

**Comment by MrAlias** [comment]
I'm not opposed to adding this. There are two issues though:

- The `attribute` package has a lot more configuration for string output with its encoders. Are we going to hit an issue if we make a single choice for how `KeyValue` are printed here?
- Will the comparable string be used as a comparison for equality checks or maps? Whether we want to or now users would then have a way to compare two `Value` outside of `Equal`. If we want this an encoder might be a better approach.

**Comment by pellared** [comment]
> The `attribute package has a lot more configuration for string output with its encoders. [...] If we want this an encoder might be a better approach.

Cannot the user create its own encoding (and even decoding) API that takes `log.Value` and `log.KeyValue`? What is the use case of allowing a user-defined Encoder? Is there a place in e.g. Go standard library that allows custom encoding? I think that we can provide our opinionated encoding like e.g. https://pkg.go.dev/time. 

> Whether we want to or now users would then have a way to compare two Value outside of Equal.

I think it would be a user error. 

We could add a doc comment like (inspired by https://pkg.go.dev/time#Time.String):

```
The returned string is meant for debugging; the representation is not stable.
```
