### ISSUE TITLE
Conflicting schema with stdouttrace

### ISSUE THREAD

**Issue by udf2457** [open-telemetry/opentelemetry-go#4959]
Attempting to implement a simple test in-line with the example code in the docs, I receive a conflicting schema error.

> panic: conflicting Schema URL: https://opentelemetry.io/schemas/1.24.0 and https://opentelemetry.io/schemas/1.17.0

The code I'm using is basically a copy/paste from the docs:

```go
func newExporter() (trace.SpanExporter, error) {
	return stdouttrace.New()
}

func newTraceProvider(exp sdktrace.SpanExporter) *sdktrace.TracerProvider {
	// Ensure default SDK resources and the required service name are set.
	r, err := resource.Merge(
		resource.Default(),
		resource.NewWithAttributes(
			semconv.SchemaURL,
			semconv.ServiceName("TestRetryClient"),
		),
	)

	if err != nil {
		panic(err)
	}

	return sdktrace.NewTracerProvider(
		sdktrace.WithBatcher(exp),
		sdktrace.WithResource(r),
	)
}
func main() {
	ctx := context.Background()
	exp, err := newExporter()
	if err != nil {
		fmt.printLn(err.Error())
	}
	tp := newTraceProvider(exp)
	defer func() { _ = tp.Shutdown(ctx) }()
	otel.SetTracerProvider(tp)
}
```

**Comment by pellared** [comment]
> with the example code in the docs

What docs are you referring to?

>  I receive a conflicting schema error.

This is not a bug. This is correct behavior. Please see: https://pkg.go.dev/go.opentelemetry.io/otel/sdk/resource#Merge

You can also take a look at https://opentelemetry.io/docs/languages/go/resources/

**Comment by udf2457** [comment]
> What docs are you referring to?

Your very own docs.  The code I posted is effectively a line-for-line paste from the docs.
https://opentelemetry.io/docs/languages/go/instrumentation/

But never mind, I'll close this issue.
