### ISSUE TITLE
 provide an option to filter certain end-points or urls

### ISSUE THREAD

**Issue by rghetia** [open-telemetry/opentelemetry-go#496]
Often there is a need to exclude certain endpoints or urls from tracing, for example, health check. This can be achieved either in
## Sampler
Sampler can either use never-sampler or probability sampler based on the name of the span or attributes of the span. Whoever starts a span has to set the name or attribute appropriately. Typically, plugins like http-plugin or grpc-plugin would start the span so plugins should set the name or attribute accordingly.
## plugins
Plugins should take an option of list of urls/endpoints to filter. Plugin then either skips or creates a span for request that matches the criteria.

Plugin is probably best place to do this kind of filtering.

**Comment by Aneurysm9** [comment]
I'll work on this after I get a PR up for #519.
