### ISSUE TITLE
Support making the parent/linking decision after span creation

### ISSUE THREAD

**Issue by dashpole** [open-telemetry/opentelemetry-go#4993]
### Problem Statement

Context: https://github.com/kubernetes/kubernetes/issues/103186

My use-case is that I would like to avoid using WithPublicEndpoint on a public endpoint because it breaks context propagation for valid users.  In an ideal world, requests that turn out to not be properly authenticated would behave as-if I have WithPublicEndpoint set, and requests that are authenticated would be have as-if I don't have WithPublicEndpoint set. I've tried to come up with solutions, and am looking for opinions or ideas.

### Potential Solutions

* Solution 1: otelhttp supports a context-based start time.  An "early" handler in the handler chain records the start time in the context, and a post-authentication handler uses otelhttp to record telemetry with that start time.
    * Cons: Metrics recorded by otelhttp won't include unauthenticated requests. I can't get any spans for unauthenticated requests, even linked.
* Solution 2: Support adding links and making the span a new root after span creation. This would allow the span to be changed to non-trusted (linked, and new root) if the request was not properly authenticated after-the-fact.
    * Add Link is already experimental: https://github.com/open-telemetry/opentelemetry-specification/blob/7eea730b0e976f1e65cc4b65aa2f17baa556e935/specification/trace/api.md?plain=1#L544
    * NewRoot would need to be added.  It would also mean that child spans of the original context would still use the "untrusted" original context if that context was propagated.

The fallback is to simply place the instrumentation after the authentication handler, but that will miss latency from authentication.

**Comment by dmathieu** [comment]
Should this be a specification change/otep?

**Comment by dashpole** [comment]
It might become one if we think solution 2 is the right way to go.  Solution 1 wouldn't require any spec changes or oteps, so i'm partially checking to see what people thought of it.  I'm also looking for ideas in-case others have solved this issue in a way I haven't thought of.

**Comment by dashpole** [comment]
I also realized solution 2 would break exemplars, since the exemplars on metrics would reference a span that no longer exists after NewRoot is called on the span.

**Comment by dashpole** [comment]
Based on discussions with the k8s instrumentation SIG, i'm going to pursue option 1.  I'll open a separate issue to track.
