### ISSUE TITLE
Add an `Enabled` method to Logger

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#4995]
While building out the [`slog` bridge](https://github.com/open-telemetry/opentelemetry-go-contrib/issues/5138#top), it seems like having an `Enabled` method will be needed (originally proposed by @jba in https://github.com/open-telemetry/opentelemetry-go/pull/4809#discussion_r1476091628).

From the bridge point of view if the log API requires it to respond to users with if the logging handler is going to actually log something for a context and severity level it needs to know what the implementation of the `Logger` will do.

It is not sufficient to track this in the bridge. If the bridge accepts some sort of minimum level things will be logged at it can be different than what the `LoggerProvider` that bridge also accepts is configured to minimally log. This is not a sufficient solution when the bridge needs to provide this information.

Additionally, when a bridge doesn't need to provide this information to the log API, it may still optimize its operation internally by checking if a log record is going to be recorded before calling `Logger.Emit`. This may be decent optimization for many bridges.

**Comment by pellared** [comment]
I have put the issue to RC project. This invalidates this rejected proposal https://github.com/open-telemetry/opentelemetry-go/blob/main/log/DESIGN.md#add-xyz-method-to-logger.

**Comment by pellared** [comment]
This will be probably also handy for following bridges:
- logr - https://pkg.go.dev/github.com/go-logr/logr#LogSink
- zap - https://pkg.go.dev/go.uber.org/zap/zapcore#LevelEnabler

**Comment by MrAlias** [comment]
https://github.com/open-telemetry/opentelemetry-specification/issues/3917

**Comment by MrAlias** [comment]
> This will be probably also handy for implementing following bridges:
> 
> * logr - see: https://pkg.go.dev/github.com/go-logr/logr#LogSink
> * zap - see: https://pkg.go.dev/go.uber.org/zap/zapcore#LevelEnabler

Also `logrus`: https://pkg.go.dev/github.com/sirupsen/logrus#Logger.IsLevelEnabled

**Comment by pellared** [comment]
> If the bridge accepts some sort of minimum level things will be logged at

This was the idea

> it can be different than what the LoggerProvider that bridge also accepts is configured to minimally log

As far as I remember, the logger provider configuration does not accept a severity level. Same for logger method. I think that any of it adding Enabled would not make much sense.

**Comment by pellared** [comment]
For logrus I think the bridge would implement https://pkg.go.dev/github.com/sirupsen/logrus#Hook

**Comment by MrAlias** [comment]
What about No-Op `Logger`s?

**Comment by MrAlias** [comment]
I also think it should be added to the pipeline. If an exporter is only configured to export at a min level there needs to be a way to tell the SDK and use not to do things.

**Comment by MrAlias** [comment]
Use cases from other languages

              otel-rust added a similar method under feature flag - https://github.com/open-telemetry/opentelemetry-rust/pull/1147
otel-cpp also has a similar approach - https://github.com/open-telemetry/opentelemetry-cpp/blob/07f6cb54ece56691dbd2a94b0cbeec722ff6a631/api/include/opentelemetry/logs/logger.h#L259

_Originally posted by @lalitb in https://github.com/open-telemetry/opentelemetry-specification/issues/3917#issuecomment-1972080176_
