### ISSUE TITLE
API: Tracer

### ISSUE THREAD

**Issue by tedsuo** [open-telemetry/opentelemetry-go#5]
Reference:
- [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/tracing-api.md#tracer)(Still WIP)
- [OpenCensus Tracer API](https://github.com/census-instrumentation/opencensus-go/tree/master/trace)
- [OpenTracing Tracer API](https://github.com/opentracing/opentracing-go/blob/master/tracer.go)

**Comment by jmacd** [comment]
We've reached the initial milestone, will open new issues for future related API concerns.
