### ISSUE TITLE
ExtractHTTP should stop after extracting first valid trace context

### ISSUE THREAD

**Issue by rghetia** [open-telemetry/opentelemetry-go#501]
There is an [issue](https://github.com/open-telemetry/opentelemetry-specification/issues/496) opened on spec to clarify the behavior. There are two problems highlighted in the current implementation.

1. The Last trace context is invalid and the first trace context is valid - Even though the first context is valid it will not use it.
2. Both of them are valid - The last context will be used but that may not be counter intuitive to the user. Also it involves unnecessary processing. Extracting is not cheap.

**Comment by MrAlias** [comment]
https://github.com/open-telemetry/opentelemetry-specification/pull/671 merged with the added clarification:

> If a value can not be parsed from the carrier for a cross-cutting concern, ￼the implementation MUST NOT throw an exception __and MUST NOT store a new value in the `Context`__, in order to preserve any previously existing valid value.

This clarifies `1` directly.

As for `2`, it seems implied that extracting both, though not optimal, is what the specification assumes to be done.

**Comment by Aneurysm9** [comment]
It seems that the [correlation context propagator](https://github.com/open-telemetry/opentelemetry-go/blob/master/api/correlation/correlation_context_propagator.go#L68) may be the only implementation that needs to change.  Both the [B3](https://github.com/open-telemetry/opentelemetry-go/blob/master/api/trace/b3_propagator.go#L87-L89) and [W3C](https://github.com/open-telemetry/opentelemetry-go/blob/master/api/trace/trace_context_propagator.go#L76-L78) trace context propagators return the input `context` unmodified if unable to extract a valid `SpanContext`.  Are there other `Propagator` implementations I'm missing?

**Comment by MrAlias** [comment]
> Are there other `Propagator` implementations I'm missing?

No, this should be all.

Did you want to take this issue @Aneurysm9?
