### ISSUE TITLE
log/sdk: Add benchmarks

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go#5054]

**Comment by MrAlias** [comment]
From SIG meeting: this looks almost complete. @dmathieu plans to another audit and review all coverage.

**Comment by dmathieu** [comment]
From the [public SDK methods](https://pkg.go.dev/go.opentelemetry.io/otel/sdk/log), we are now benchmarking:

* `Record.WalkAttributes()`
* `Record.SetAttributes`
* `Record.AddAttributes`
* `LoggerProvider.Logger`
* `logger.newRecord`
* `SimpleProcessor.OnEmit`
* `BatchProcessor.OnEmit`
* Create a record, with body, severity, attributes, and run `SimpleProcessor.OnEmit`
* Create a record, with body, severity, attributes, and run `BatchProcessor.OnEmit`
* Create a record, with body, severity, attributes, modify the observed timestamp and run `SimpleProcessor.OnEmit`
* Create a record, with body, severity, attributes, modify the observed timestamp and run `BatchProcessor.OnEmit`

At this stage, all hot public APIs appear to be benchmarked in the log SDK. I believe this issue can be closed.

**Comment by pellared** [comment]
We can always add more benchmarks later. Great job.
