### ISSUE TITLE
Add stdoutlog exporter

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go#5055]
Create a `go.opentelemetry.io/otel/exporters/stdout/stdoutlog` module providing a logs console exporter.

The exporter should have options `WithWriter`, `WithPrettyPrint` and `WithoutTimestamps` like https://pkg.go.dev/go.opentelemetry.io/otel/exporters/stdout/stdouttrace.

We may want to add JSON marshaling to the `go.opentelemetry.io/otel/sdk/log.Record` type.

- [x] https://github.com/open-telemetry/opentelemetry-go/pull/5158
- [x] https://github.com/open-telemetry/opentelemetry-go/pull/5172
- [x] https://github.com/open-telemetry/opentelemetry-go/issues/5174
- [x] https://github.com/open-telemetry/opentelemetry-go/issues/5175
- [x] #5211
- [x] #5212
- [x] #5242

**Comment by MrAlias** [comment]
Are we planning to just follow the metric STDOUT exporter here and accept some kind of encoder?

**Comment by MrAlias** [comment]
Can you fill out the description of this issue with what is needed in the initial version? It's pretty blank currently :wink:

**Comment by XSAM** [comment]
> I am against having an encoder interface like in stdoutmetric which **does not even take the io.Writer into consideration.**
>
> We could accept an interface like type Handler interface { Handle(w io.Writer, r log.Record) } but it doesn't need to be added in the initial version.

I wonder what is the reason for having a `io.Writer` in the `Handler` interface. The `io.Writer` can be part of the implementation of a handler and might not be necessary in the interface.

**Comment by pellared** [comment]
I think that the main idea of using stdout exporter is to have it working with io.Writer that can set via WithWriter. **Personally, I do not see a good reason to provide such customization. One can always create its own exporter.**

Can we start with an implantation that only has WithWriter, WithPrettyPrint and WithoutTimestamps like https://pkg.go.dev/go.opentelemetry.io/otel/exporters/stdout/stdouttrace?

**Comment by XSAM** [comment]
I feel like we only treat the `stdoutlog` exporter as a debug tool.

Do you think we might end up having a full-function logging exporter, like the [slog](https://pkg.go.dev/golang.org/x/exp/slog#Handler)? So, we can provide native OTel logging without importing contrib libs (or other third-party libs). We can also reduce the log model transform at least once, as our logging implementation uses our own log model.

**Comment by pellared** [comment]
> I feel like we only treat the `stdoutlog` exporter as a debug tool.

This is indeed one of its main use cases.

> Do you think we might end up having a full-function logging exporter, like the [slog](https://pkg.go.dev/golang.org/x/exp/slog#Handler)? 

Can please you elaborate? The SDK allows adding a custom logging exporter. Am I missing something?

> So, we can provide native OTel logging without importing contrib libs (or other third-party libs).

Just for reference, [Logs Bridge API](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/bridge-api.md) should not be used directly.

> Note: this document defines a log backend API. The API is not intended to be called by application developers directly. It is provided for logging library authors to build [log appenders](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/supplementary-guidelines.md#how-to-create-a-log4j-log-appender), which use this API to bridge between existing logging libraries and the OpenTelemetry log data model.

> The Logs Bridge API is not intended to be called by application developers directly, and SHOULD include documentation that discourages direct use.

> We can also reduce the log model transform at least once, as our logging implementation uses our own log model.

However, in future, one could use [Events API](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/event-api.md) to emit events without importing third-party libs

This is why I e.g. propose adding JSON marshaling to the `go.opentelemetry.io/otel/sdk/log.Record` type (to reduce the amount of object transformations).
