### ISSUE TITLE
Add otlploggrpc exporter

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go#5056]
- [x] #5246
  - [x] #5273 
- [x] Add `otlploggrpc` gRPC client
  - [x] #5523
  - [x] #5572
- [x] Implement `Option`s
  - [x] #5313
  - [x] #5383
- [x] Implement the `Exporter`
  - [x] #5553
  - [x] #5582
  - [x] #5614
- [x] #5615
- [ ] ~Make reused codes as shared templates (optional)~
  - [ ] ~internal/conf~
  - [ ] ~TLS certificate methods~
- [x] #5622
- [ ] #5629

prototype: #5522

**Comment by XSAM** [comment]
I like to work on this one.

**Comment by arukiidou** [comment]
add to README has been postponed.
- https://github.com/open-telemetry/opentelemetry-go/pull/5274#discussion_r1582743911
