### ISSUE TITLE
Add otlploghttp exporter

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go#5057]
- [x] https://github.com/open-telemetry/opentelemetry-go/pull/5138
- [x] https://github.com/open-telemetry/opentelemetry-go/pull/5224
- [x] Implement `Option`s
  - [x] #5165 
  - [x] #5167 
  - [x] https://github.com/open-telemetry/opentelemetry-go/pull/5223
- [x] https://github.com/open-telemetry/opentelemetry-go/pull/5150
- [x] Implement the `Exporter`
  - [x] #5182
  - [x] #5163 
  - [x] #5164 
- [x] Implement OTLP transforms
  - [x] Blocked by https://github.com/open-telemetry/opentelemetry-go/issues/5187
  - [x] https://github.com/open-telemetry/opentelemetry-go/pull/5191
- [x] https://github.com/open-telemetry/opentelemetry-go/pull/5150
- [x] https://github.com/open-telemetry/opentelemetry-go/pull/5235

**Comment by MrAlias** [comment]
> @pellared, @MrAlias the newExporter function which is used by New still has TODO. Is it complete? Just tried to deploy a microservice with Logger, SimpleProcessor and the http exporter but still don't see any logs in the collector.

@Laxi-luke the exporter should be working. It has been verified locally. Please open an issue with details about your setup if the error persists.
