### ISSUE TITLE
Update dice example to use logs

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go#5058]
Update https://opentelemetry.io/docs/languages/go/getting-started/ and https://github.com/open-telemetry/opentelemetry-go/tree/main/example/dice to use logs signal.

**Comment by Enzujp** [comment]
Hello there @pellared , if this is still unattended, I'd like to fix it!

**Comment by pellared** [comment]
@open-telemetry/go-maintainers and @open-telemetry/docs-maintainers: Is it OK to do it before having a stable release of OTel Go Logs?

**Comment by svrnm** [comment]
From a docs perspective, that's OK, we had that for other languages in the past as well, you might want to add a disclaimer that things are still in beta.

**Comment by MrAlias** [comment]
Code update: https://github.com/open-telemetry/opentelemetry-go/pull/5349
