### ISSUE TITLE
log/sdk: Implement Logger

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go#5061]

**Comment by XSAM** [comment]
Blocked by https://github.com/open-telemetry/opentelemetry-go/issues/5060

**Comment by MrAlias** [comment]
@XSAM does https://github.com/open-telemetry/opentelemetry-go/pull/5074 help unblock this? Or is there more needed?

**Comment by XSAM** [comment]
Yes, #5074 helps unblock this.
