### ISSUE TITLE
log/sdk: Implement BatchingProcessor

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go#5063]
- [x] https://github.com/open-telemetry/opentelemetry-go/pull/5104
- [x] https://github.com/open-telemetry/opentelemetry-go/pull/5106
- [x] https://github.com/open-telemetry/opentelemetry-go/pull/5118
- [x] https://github.com/open-telemetry/opentelemetry-go/pull/5119
- [x] https://github.com/open-telemetry/opentelemetry-go/pull/5131
- [x] https://github.com/open-telemetry/opentelemetry-go/pull/5093
- [x] https://github.com/open-telemetry/opentelemetry-go/pull/5237
- [x] https://github.com/open-telemetry/opentelemetry-go/pull/5239

**Comment by MrAlias** [comment]
Quick look at pooling export payloads didn't show large improvements in performance. Going to remove from this issue as a task. We can address later if more time is found to dedicate into the investigation.
