### ISSUE TITLE
sdk/log: Add minimum level enabled processor

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#5078]
Add a processor users can wrap other processors in that will only log records at or above a provided minimum severity level.

https://github.com/open-telemetry/opentelemetry-go/blob/65e032dd16b20e376eae5a7a5956fa811783389b/sdk/log/min_sev.go

**Comment by pellared** [comment]
I think we should first add the processor to the specification before introducing it to the SDK. Alternatively we could add it to contrib. For now I decided to use it as an example.

**Comment by MrAlias** [comment]
User feedback requesting this feature: https://cloud-native.slack.com/archives/C01NPAXACKT/p1719249110767979
