### ISSUE TITLE
Try to drop length-fixed attributes in the record of the log SDK

### ISSUE THREAD

**Issue by XSAM** [open-telemetry/opentelemetry-go#5082]
> 
> Should we use a normal array here? Like `attributes []log.KeyValue`

I think that's worth exploring, but I would do so in a follow up PR.

_Originally posted by @MrAlias in https://github.com/open-telemetry/opentelemetry-go/pull/5081#discussion_r1527528639_

**Comment by XSAM** [comment]
If we use a regular array that has a flexible length, it would require at least an allocation in the heap. This is not an idea, as the original implementation had zero allocation when the length of attributes was lower than or equal to 5.

Though we can optimize the allocation when we have attributes that are more than 5, it might not be worth the investment, as 95% of the code uses up to 5 attributes. https://github.com/open-telemetry/opentelemetry-go/pull/5101#discussion_r1537658837

Closing this

**Comment by pellared** [comment]
@XSAM, I did my best to document it here: https://github.com/open-telemetry/opentelemetry-go/blob/main/sdk/log/DESIGN.md?plain=1#L82-L83. If you feel that it is not clear - feel free to clarify it. The design doc is also for us 😉
