### ISSUE TITLE
sdk/log: Drop duplicated KeyValues

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go#5086]
## Why

From 
https://opentelemetry.io/docs/specs/otel/logs/data-model/#type-mapstring-any:

> The keys in the map are unique (duplicate keys are not allowed).

Also: https://github.com/open-telemetry/opentelemetry-specification/issues/3931#issuecomment-2045536584

_Adding an option to avoid deduplication (and allow duplicated keys) is tracked as a separate issue. https://github.com/open-telemetry/opentelemetry-go/issues/5133_

## What

Drop duplicated KeyValues in simple and batch processor OR record.

More:
- https://github.com/open-telemetry/opentelemetry-go/issues/5086#issuecomment-2039344160
- https://github.com/open-telemetry/opentelemetry-go/issues/5086#issuecomment-2042756351
- Prototype (for logger, not processor): https://github.com/pellared/opentelemetry-go/pull/10

**Comment by pellared** [comment]
There is a similar issue that indicates that users may want to have an option to avoid deduplication: https://github.com/open-telemetry/opentelemetry-go/issues/5130

**Comment by pellared** [comment]
The problem of dropping duplicates in the logger is that they can be passed not only by the Bridge API but also by the processor (which allows adding/setting of attributes and setting body). Therefore the duplicates should be deduplicated as far int the pipeline as possible.

Therefore, my proposal is **the OTLP exporters handle deduplication**. _We can have an option in the OTLP exporters to disable the deduplication to improve the OTLP exporter's performance._

This is looks to be acceptable:
- https://github.com/open-telemetry/opentelemetry-specification/pull/3938/files#r1526685159
- https://github.com/open-telemetry/opentelemetry-specification/pull/3938/files#r1525101870

I will try to make a second try and update the specification to make it more clear. I plan to add something more or less like:

> The SDKs MAY allow duplicates (represent this type as a list of key-values) as long as the OTLP exporters by default handle deduplication.

@open-telemetry/go-approvers Please leave 👍 if you agree, if so I will close the issue and update the description of:
- https://github.com/open-telemetry/opentelemetry-go/issues/5057
- https://github.com/open-telemetry/opentelemetry-go/issues/5056

**Comment by pellared** [comment]
The alternative, could be creating a processor which would handle deduplication. However, I am not sure if this would be spec-compliant as it would have to be an opt-in functionality.

**Comment by pellared** [comment]
Another alternative, could be **adding deduplication to the simple and batch processor**.

It is the best place to add if we would like to "enable deduplication be default". I assume most people would use the batch processor in production. We could still  implement via a `DedupDecorator` which would be applied by default, but we could add options to not have them decorated.

**Comment by dashpole** [comment]
> I think it is fine to do the deduplication anywhere you want as long as externally observable data complies with this document.

This makes it sound like the data passed to an exporter must already be deduplicated.

> I think it is fair to provide non-default options like this, with a clear warning that the caller is responsible for ensuring there are no duplicates, assuming there is a need for such high performance.

Is tigran saying this can't be the default?

**Comment by pellared** [comment]
> Is tigran saying this can't be the default

I am not sure if it is a suggestion or a requirement. Personally, I would start with no deduplication. We could introduce this behavior later (https://github.com/open-telemetry/opentelemetry-go/issues/5086#issuecomment-2039344160) if needed. I have not heard about any problems  (other than spec compliance) caused by lack of deduplication in .NET.

**Comment by MrAlias** [comment]
> The alternative, could be **creating a processor which would handle deduplication**.
> 
> I am leaning to this approach as I find that it would be more-performant by default. It follows the behavior of all popular Go logging libraries. At last, even if we would do it by default - the user would be able to by-pass and duplicates at some point (e.g. by implementing a custom processor).
> 
> Please leave 👍 if you agree, if so if so I will close this issue and create a new one to add `DedupProcessor`.
> 
> I propose [open-telemetry/opentelemetry-specification#3987](https://github.com/open-telemetry/opentelemetry-specification/pull/3987) to allow flexibility.

I think we could add this afterwards. Given the OTLP seems to be the only place that de-duplication needs to be done we could start there and if a general processor is needed we could add that later.

**Comment by pellared** [comment]
@MrAlias this is exactly what I mean here:

> Personally, I would start with no deduplication by default. We could introduce this behavior as default to the batch processor later (#5086 (comment)) if needed.

**Comment by pellared** [comment]
> if a general processor is needed we could add that later.

I think we should add options (even though there is none) to `SimpleProcessor` so that we can and a `WithoutDeduplication` option later if needed. If we don't do it now, then later it would be a breaking change. WDYT?

**Comment by pellared** [comment]
The alternative, could be **adding a exporter decorator which would handle deduplication**.

**Comment by pellared** [comment]
Based on https://github.com/open-telemetry/opentelemetry-specification/issues/3931#issuecomment-2045536584 it looks like it it looks my guts (previous comment) were right.

**Comment by MrAlias** [comment]
Partial implementation of attribute de-duplication: https://github.com/open-telemetry/opentelemetry-go/pull/5190

**Comment by MrAlias** [comment]
Resolved by https://github.com/open-telemetry/opentelemetry-go/pull/5230
