### ISSUE TITLE
TraceID and SpanID the String method to return an "00000000..." string when the TraceID or SpanID is invalid.

### ISSUE THREAD

**Issue by FarmerChillax** [open-telemetry/opentelemetry-go#5095]
### Description

TraceID and SpanID the String method to return an "00000000..." string when the TraceID or SpanID is invalid.

### Environment

- OS: MacOS 13.1
- Architecture: M2
- Go Version:  go1.21.0 darwin/arm64
- opentelemetry-go version: v1.24.0

### Steps To Reproduce

1. Use the configuration
```go
package main

import (
	"context"
	"fmt"

	"go.opentelemetry.io/otel/trace"
)

func main() {
	ctx := context.Background()
	span := trace.SpanFromContext(ctx)
	fmt.Printf("TraceID: %s\n", span.SpanContext().TraceID().String())
	fmt.Printf("SpanID: %s\n", span.SpanContext().SpanID().String())
}
```

2. Run
```
➜ go run main.go 
TraceID: 00000000000000000000000000000000
SpanID: 0000000000000000
```

### Expected behavior
output an empty string

**Comment by FarmerChillax** [comment]
i wanna solve in #5094

**Comment by dmathieu** [comment]
From the specification:
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#retrieving-the-traceid-and-spanid

> The API MUST allow retrieving the TraceId and SpanId in the following forms:
>
> * Hex - returns the lowercase [hex encoded](https://tools.ietf.org/html/rfc4648#section-8) TraceId (result MUST be a 32-hex-character lowercase string) or SpanId (result MUST be a 16-hex-character lowercase string).
> * Binary - returns the binary representation of the TraceId (result MUST be a 16-byte array) or SpanId (result MUST be an 8-byte array).

Returning an empty string would therefore be against the specification, as the ID wouldn't be a 32 or 16 hex-character lowercase string.

If you're looking to know whether the trace or span ID is invalid, you should use the `IsValid` method,

**Comment by dmathieu** [comment]
As a side note, this would also be a breaking change that we therefore cannot introduce unless we go to v2.

**Comment by FarmerChillax** [comment]
It feels not natural enough to return content when the verification fails, but for now it seems that we can only focus on standards.

**Comment by dmathieu** [comment]
As a side note, this is also what the trace context specification qualifies as invalid data.
https://w3c.github.io/trace-context/#trace-id
