### ISSUE TITLE
Document/automate release process

### ISSUE THREAD

**Issue by krnowak** [open-telemetry/opentelemetry-go#510]
There is a couple of steps to be done when doing a release, so it would be nice to have it documented and possibly automated. Steps that come to my mind are:

- bumping version of the `go.opentelemetry.io/otel` dependency in exporters and examples to `${NEW_VERSION}`
- updating the version string in `""go.opentelemetry.io/otel/sdk".Version()` function to `"${NEW_VERSION}"` (I discovered this function by accident yesterday and it still says "0.1.0"…)
- commit the changes
- file a PR with the changes
- after PR is merged, create git tags for otel-go and its submodules (`tag_latest_modules.sh` script does some of the work) and push them
  - alternatively, the commit with the changes and the created tags could be pushed directly to master as a single action if it's allowed
- update the github releases page

**Comment by lizthegrey** [comment]
https://github.com/open-telemetry/opentelemetry-go/pull/512 doing this hopefully for the last time by hand.
