### ISSUE TITLE
Default SDK support for resources (Metrics)

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-go#515]
There is  interest in specifying a standard environment variable for passing resources in the default SDKs. See https://github.com/open-telemetry/opentelemetry-specification/issues/501. Although we do not have a specification for a particular environment variable name, we can assume that there will be resources configured in the SDKs and that exporters will have access to them.

Resource support should be added in the Metric SDK.

**Comment by rghetia** [comment]
@MrAlias do you have bandwidth to take this?

**Comment by MrAlias** [comment]
@rghetia: yeah, sounds good.

**Comment by rghetia** [comment]
> @rghetia: yeah, sounds good.

Thanks a lot.
