### ISSUE TITLE
Remove context check on stdout exporters

### ISSUE THREAD

**Issue by XSAM** [open-telemetry/opentelemetry-go#5173]
There's no work being done. We recently decided we don't want to return an error in these situations.

_Originally posted by @MrAlias in https://github.com/open-telemetry/opentelemetry-go/pull/5172#discussion_r1554989264_

---

stdouttrace and stdoutmetric exporters still have similar logic.

**Comment by prasad-shirodkar** [comment]
I am interested to work on this. Please feel free to assign to myself.
