### ISSUE TITLE
stdoutlog: Do not print timestamps when `WithoutTimestamps` is set

### ISSUE THREAD

**Issue by XSAM** [open-telemetry/opentelemetry-go#5175]
Shouldn't these be

```suggestion
	Timestamp                 *time.Time
	ObservedTimestamp         *time.Time
```

To nicely handle `WithoutTimestamps`?

Here is why: https://go.dev/play/p/-a5jI4jOXSK

~~AFAIK this would be a different behaviour that we have for `stdoutmetric` and `stdouttrace`.~~

We can handle it via a separate issue and PR as we may have different opinions.

_Originally posted by @pellared in https://github.com/open-telemetry/opentelemetry-go/pull/5172#discussion_r1555029175_

**Comment by pellared** [comment]
I have forgotten to mention that `omitempty` should be added e.g.

```
Timestamp                 *time.Time `json:",omitempty"`
ObservedTimestamp         *time.Time `json:",omitempty"`
```

**Comment by XSAM** [comment]
I am hesitant to implement this, as the data has been used in the `stdoutmetric` and `stdouttrace` is exported structure. Changing this structure would bring break changes.

https://github.com/open-telemetry/opentelemetry-go/blob/1ff2e71e7d43c652f505b0680f8550ef0c863233/sdk/metric/metricdata/data.go#L78-L81
https://github.com/open-telemetry/opentelemetry-go/blob/1ff2e71e7d43c652f505b0680f8550ef0c863233/sdk/trace/tracetest/span.go#L52-L53

If we only implement this only for `stdoutlog`, then the behavior is different what we have for `stdoutmetric` and `stdouttrace`, which is strange.

**Comment by pellared** [comment]
> Changing these structures would bring break changes.

From https://pkg.go.dev/go.opentelemetry.io/otel/exporters/stdout/stdoutmetric:

> The exporter is intended to be used for testing and debugging, it is not meant for production use. Additionally, it does not provide an interchange format for OpenTelemetry that is supported with any stability or compatibility guarantees. 

I would not consider it breaking.

But I also to not have a strong opinion to have this issue addressed.

It would be good to have other opinions and maybe discuss it during SIG meeting.
