### ISSUE TITLE
Dropped attribute count is not recorded by log record

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#5186]
[OTLP tracks this value](https://github.com/open-telemetry/opentelemetry-proto-go/blob/31ff7ed1b8447762ecf3fdc203417c5083daa02f/otlp/logs/v1/logs.pb.go#L460) and we should be able to determine its value given the SDK configured limits.

We should provide this information for completeness.

**Comment by pellared** [comment]
This is needed also for non-OTLP exporters (e.g. `stdoutlog`). 

See: [OpenTelemetry Transformation to non-OTLP Formats](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/mapping-to-non-otlp.md#dropped-attributes-count)

CC @XSAM 

I think that the exporter could be responsible for dropping attributes based on the limits. Doing it e.g. in processor would involve  additional transformations.

**Comment by pellared** [comment]
I think this

https://github.com/open-telemetry/opentelemetry-go/blob/727f03e2204a4203dda75df0c719e792b66bd5df/sdk/log/record.go#L209-L227

should be replaced with

```
func (r *Record) DroppedAttributesCount() int
```

**Comment by MrAlias** [comment]
I'm working on the implementation of this. I'm going to follow the pattern of the trace SDK where we de-duplicate and prune attributes if a limit is hit.

I'm not planning to add deduplication for non-overflown attributes. That can be a follow up PR.

**Comment by pellared** [comment]
> Do we also want to remove the other limit method?

Yes. All of them 💥
