### ISSUE TITLE
Restructure log SDK data model

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#5187]
The current data-model of the log SDK is a [`Record`](https://github.com/open-telemetry/opentelemetry-go/blob/648b40eae1587acced249aea1998312d075447bf/sdk/log/record.go#L23). Exporters are handed a slice of these values:

https://github.com/open-telemetry/opentelemetry-go/blob/648b40eae1587acced249aea1998312d075447bf/sdk/log/exporter.go#L37

This is not ideal since all should share the same resource and many will share the same scope information. All exporters need to parse each record and handle multiple resources. They also need to parse all records and partition around scope information.

This is inefficient. The SDK can and should solve this for all exporters.

### Proposal

A `ResourceLogs` type can be introduced. This type is passed to exporters. This will remove the error of an exporters receiving multiple resources per record batch.

Within the `ResourceLogs`, a new `ScopeLogs` can be introduced. Providing this from the SDK will mean the exporters will not have to partition all scopes out of the passed logs.

```go
type ResourceLogs struct {
	Resource resource.Resource
	ScopeLogs ScopeLogs
}

type ScopeLogs struct {
	Scope instrumentation.Scope
	Records []Record
}
```

These could be added to `sdk/log` or a new module `sdk/log/logdata`. If the latter, `Record` should be moved to that module.

**Comment by pellared** [comment]
I prefer to have them added to `sdk/log`
