### ISSUE TITLE
Sampler API must accept Attributes and Links and return Attributes

### ISSUE THREAD

**Issue by Aneurysm9** [open-telemetry/opentelemetry-go#519]
While looking at options for addressing #496 I found that the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/sdk-tracing.md#sampling) already requires that samplers receive the initial set of Attributes and Links attached to a span.  It also requires that the `SamplingResult` include a property for Attributes related to the sampling decision and that the `Decision` be one of three options in an Enum and not a bool.  The current Go API and SDK trace packages are non-conformant to varying degrees.

**Comment by Aneurysm9** [comment]
I'll take this issue.

**Comment by rghetia** [comment]
> I'll take this issue.

Thanks @Aneurysm9

**Comment by jmacd** [comment]
(Ugh. I thought we had decided to keep Sampler output in the propagated `tracestate`, not pollute the user's attributes.)

**Comment by Aneurysm9** [comment]
None of the default Samplers add any attributes, so I think it would be user-defined Samplers doing any polluting and that's on the user at that point.
