### ISSUE TITLE
log/logtest: Add `log.Record` initializer

### ISSUE THREAD

**Issue by dmathieu** [open-telemetry/opentelemetry-go#5195]
### Problem Statement

Right now, creating and filling data for a `log.Record` requires calling method independently, and cannot be chained.

eg:

```golang
var record log.Record
record.SetTimestamp(e.Time)
record.SetBody(log.StringValue(e.Message))
record.SetSeverity(severity)
record.AddAttributes(data...)
```

This is a bit tedious, especially in test environments, where we end up having to setup methods to build records such as this one in the logrus bridge PR:

```golang
func buildRecord(body log.Value, timestamp time.Time, severity log.Severity, attrs []log.KeyValue) log.Record {
	var record log.Record
	record.SetBody(body)
	record.SetTimestamp(timestamp)
	record.SetSeverity(severity)
	record.AddAttributes(attrs...)

	return record
}
```

### Proposed Solution

Add a `NewRecord()` helper method with optional arguments to create a new record.
The example above would become:

```golang
record := NewRecord(
    WithTimestamp(e.Time),
    WithBody(message),
    WithSeverity(severity),
    WithAttributes(data),
)
```

### Alternative

I could change my `buildRecord` in logrus to use functional arguments, but that would have to be repeated across all bridges.

**Comment by pellared** [comment]
The functional options introduce heap allocations. I do not support the proposal as we would then provide inefficient API that developers might use and then compliant that the API is not performant. More: https://github.com/open-telemetry/opentelemetry-go/blob/main/log/DESIGN.md#options-as-parameter-to-loggeremit.

**Comment by dmathieu** [comment]
What if we add it to the `logtest` package?
Then writing tests for bridges/implementations becomes easier, and there's a clear indication that it shouldn't be used at runtime?

**Comment by pellared** [comment]
> What if we add it to the `logtest` package? Then writing tests for bridges/implementations becomes easier, and there's a clear indication that it shouldn't be used at runtime?

That makes a lot of sense. 

I would also consider implementing it as a "builder" to not "spam" the package with options. So that the user could do something like:

```go
record := logtest.NewRecordBuilder()
  .SetBody(log.StringValue("message"),
  .SetTimestamp(timestamp)
  .SetSeverity(severity)
  .AddAttributes(data)
  .Build()
```

**Comment by pellared** [comment]
Do you think we can do something like https://github.com/open-telemetry/opentelemetry-go/pull/5234 for this issue as well?

**Comment by pellared** [comment]
@dmathieu, do you think we can do something like https://github.com/open-telemetry/opentelemetry-go/pull/5234 for this issue as well?

**Comment by dmathieu** [comment]
Yes, definitely. I'll wait for your PR to be approved before I start doing something similar for the API record.
