### ISSUE TITLE
log.BatchingProcessor is inconsistent with trace.BatchSpanProcessor

### ISSUE THREAD

**Issue by dashpole** [open-telemetry/opentelemetry-go#5198]
### Description

https://github.com/open-telemetry/opentelemetry-go/pull/5093#discussion_r1561409361

The spec for logs refers to this as a "Batching Processor" or a "Batching Log Record Processor": https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/sdk.md

The spec for traces refers to this as a "Batching Processor" or a "Batching Span Processor": https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md

We named the trace one a "BatchSpanProcessor", and currently have named the logging one the log.BatchingProcessor.

I propose we keep the naming consistent, and use "log.BatchRecordProcessor" (given it is batching `Record`s).  Other potential options that are more aligned with the tracing name we chose include:

* log.BatchProcessor
* log.BatchLogRecordProcessor

**Comment by pellared** [comment]
`log.BatchProcessor` looks nice for me. I like shorter names when I think that they are enough precise enough. 

I also prefer to have the interface named `Processor` rather than `RecordProcessor`.

The type documentation could say something like

>BatchProcessor represents a batching log record processor.

**Comment by MrAlias** [comment]
SIG notes:

- Let's go with `BatchProcessor`
