### ISSUE TITLE
sdk/log: Record.Resource to return a pointer

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go#5232]
Currently we have

```go
func (r *Record) Resource() resource.Resource {
```

Should we not return a pointer instead as usually Resource is passed and returned by pointer?

```go
func (r *Record) Resource() *resource.Resource {
```

**Comment by MrAlias** [comment]
This will allow the caller to modify the resource of the record if we do this unless we make a copy of the pointer stored in the Resource. This means we will need to incur another allocation if we want safety around the returned type.

**Comment by pellared** [comment]
> This will allow the caller to modify the resource of the record 

You are right. I have forgotten about that 👍 Closing.
