### ISSUE TITLE
Not possible to use both otelmetrichttp and otelmetricgrpc

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go#5251]
FYI. it looks like its no longer possible to have both otelmetrichttp and otelmetricgrpc in the same binary.  I'm not sure how common this is, but go.opentelemetry.io/contrib/exporters/autoexport is an example.

```
$ git clone https://github.com/open-telemetry/opentelemetry-go-contrib.git
$ cd opentelemetry-go-contrib/exporters/autoexport/
$ go get go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp@main
go: upgraded go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp v1.25.0 => v1.25.1-0.20240422142149-b34cfc47c4e0
go: added go.opentelemetry.io/proto/slim/otlp v1.2.0
$ go get go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc@main
go: downloading go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc v1.25.1-0.20240422142149-b34cfc47c4e0
go: upgraded go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc v1.25.0 => v1.25.1-0.20240422142149-b34cfc47c4e0
$ go test ./...
panic: proto: file "opentelemetry/proto/common/v1/common.proto" is already registered
	previously from: "go.opentelemetry.io/proto/otlp/common/v1"
	currently from:  "go.opentelemetry.io/proto/slim/otlp/common/v1"
See https://protobuf.dev/reference/go/faq#namespace-conflict
```

_Originally posted by @gregoryfranklin in https://github.com/open-telemetry/opentelemetry-go/issues/2579#issuecomment-2070160288_

**Comment by pellared** [comment]
This should be double-check before making a new release as it can be a blocker.

**Comment by MrAlias** [comment]
Please coordinate with @XSAM who is working on https://github.com/open-telemetry/opentelemetry-go/issues/5250

**Comment by pellared** [comment]
Most probably we will have to revert these two PRs:

- https://github.com/open-telemetry/opentelemetry-go/pull/5222
- https://github.com/open-telemetry/opentelemetry-go/pull/5216

@gregoryfranklin, thanks for reporting the issue ❤️

**Comment by XSAM** [comment]
I have checked the protobuf codes regarding this behavior. It means we cannot import `go.opentelemetry.io/proto/otlp` and `go.opentelemetry.io/proto/slim` at the same time.

https://github.com/protocolbuffers/protobuf-go/blob/e4ad8f9dfc8bc3184ebb70c296bd63955343e903/reflect/protoregistry/registry.go#L126-L133

Though we could use `go build -ldflags "-X google.golang.org/protobuf/reflect/protoregistry.conflictPolicy=warn"` to change the conflict policy and probably pass this check, it requires our end-users to do this, which is not acceptable.

## Plan for the release

Rollback these two PRs:
- https://github.com/open-telemetry/opentelemetry-go/pull/5222
- https://github.com/open-telemetry/opentelemetry-go/pull/5216

## After the release

We might need to deprecate package `go.opentelemetry.io/proto/slim`, as it is not compatible with `go.opentelemetry.io/proto/otlp`, which provides grpc support.
