### ISSUE TITLE
Switching dependency bot to renovate

### ISSUE THREAD

**Issue by XSAM** [open-telemetry/opentelemetry-go#5271]
### Problem Statement

- An update for a single dependency across our go submodules would occur in multiple PRs. It is annoying.
- GitHub's dependabot doesn't support docker-compose files. https://github.com/dependabot/dependabot-core/issues/390

### Proposed Solution

Switch to renovate

### Additional Context

https://github.com/open-telemetry/opentelemetry-go/pull/5244#discussion_r1574257115

### Tasks

- [x] #5346
- [ ] Remove dependabot version updates in the contrib repo. https://github.com/open-telemetry/opentelemetry-go-contrib/pull/5577

**Comment by MrAlias** [comment]
This should be unblocked: https://github.com/open-telemetry/community/issues/2090#issuecomment-2096396445

**Comment by XSAM** [comment]
I don't know why this repo didn't receive any PR Configure Renovate

**Comment by XSAM** [comment]
FYI, the default config file looks like this

```json
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "config:recommended"
  ]
}
```

**Comment by pellared** [comment]
> FYI, the default config file looks like this
> 
> ```json
> {
>   "$schema": "https://docs.renovatebot.com/renovate-schema.json",
>   "extends": [
>     "config:recommended"
>   ]
> }
> ```

I know but I want to at least make sure that [`go mod tidy`](https://docs.renovatebot.com/golang/#module-tidying) is run and [`test` Go modules are not ignored](https://github.com/renovatebot/renovate/discussions/12755).

**Comment by XSAM** [comment]
The renovate bot failed to create Renovate PR because it got a 422 Error from GitHub. https://developer.mend.io/github/open-telemetry/opentelemetry-go/-/job/817ca928-01ff-4038-a171-0296c06ab5ad

**Comment by pellared** [comment]
It fails because we are probably missing this rule in this repo: https://github.com/open-telemetry/community/blob/main/docs/how-to-configure-new-repository.md#branch-protection-rule-renovate

**Comment by MrAlias** [comment]
To resolve this, is the plan to rip out all the dependabot tooling and disable the bot on the repo?

**Comment by XSAM** [comment]
> To resolve this, is the plan to rip out all the dependabot tooling and disable the bot on the repo?

Recap the discussion at the meeting, we will disable dependabot for version updates, but keep the vulnerability alerts.

**Comment by MrAlias** [comment]
Are there any more tasks for this? Can this be closed?

**Comment by XSAM** [comment]
I will prepare a PR for contrib.
