### ISSUE TITLE
Record links with empty span context

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#5308]
Links with invalid span context are [now](https://github.com/open-telemetry/opentelemetry-specification/pull/3928) recommended to be recorded by the specification if they have non-empty attributes or trace state.

> Implementations SHOULD record links containing `SpanContext` with empty `TraceId` or `SpanId` (all zeros) as long as either the attribute set or `TraceState` is non-empty.

Our implementation does not currently follow this behavior:

https://github.com/open-telemetry/opentelemetry-go/blob/0fc35e0e93ca2f8b0b5b1a44b2d388bc19169083/sdk/trace/span.go#L632-L653

The implementation needs to be updated and tests added to prevent regression.

**Comment by amanakin** [comment]
Hi! I'd like to take that one
