### ISSUE TITLE
confused about apidesign Start(ctx context.Context, spanName string, opts ...SpanStartOption) (context.Context, Span)

### ISSUE THREAD

**Issue by someview** [open-telemetry/opentelemetry-go#5316]
### Description
type Tracer interface {
	// Users of the interface can ignore this. This embedded type is only used
	// by implementations of this interface. See the "API Implementations"
	// section of the package documentation for more information.
	embedded.Tracer

	// Start creates a span and a context.Context containing the newly-created span.
	//
	// If the context.Context provided in `ctx` contains a Span then the newly-created
	// Span will be a child of that span, otherwise it will be a root span. This behavior
	// can be overridden by providing `WithNewRoot()` as a SpanOption, causing the
	// newly-created Span to be a root span even if `ctx` contains a Span.
	//
	// When creating a Span it is recommended to provide all known span attributes using
	// the `WithAttributes()` SpanOption as samplers will only have access to the
	// attributes provided when a Span is created.
	//
	// Any Span that is created MUST also be ended. This is the responsibility of the user.
	// Implementations of this API may leak memory or other resources if Spans are not ended.
	Start(ctx context.Context, spanName string, opts ...SpanStartOption) (context.Context, Span)
}

Why not put start end end method together.eg:
```
Start(ctx context.Context, operationName string) context.Context
End(ctx context.Context)
```
It's very clear. `Start(ctx context.Context, spanName string, opts ...SpanStartOption) (context.Context, Span)` seperate Start and End method.

**Comment by pellared** [comment]
Ending a span is a Span-level operation and it is required by the specification: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#end
