### ISSUE TITLE
sdk/log: Log when an attribute was discarded or truncated due to limits

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go#5317]
From https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/sdk.md#logrecord-limits:

> There SHOULD be a message printed in the SDK's log to indicate to the user that an attribute was discarded due to such a limit. To prevent excessive logging, the message MUST be printed at most once per `LogRecord` (i.e., not per discarded attribute).

**Comment by MrAlias** [comment]
We should check if this is also needed for the attributes in trace/metric pipelines.
