### ISSUE TITLE
sdk/log: Define in DESIGN.md how Processor and Exporter interfaces can be extended 

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go#5318]
We should consider creating `embedded` interfaces as well as no-op implementations for `Processor` and `Exporter`. This could make extending these abstractions easier and less frustrating for the users.

This idea came up when I was reviewing https://github.com/open-telemetry/opentelemetry-specification/pull/4030 and https://github.com/open-telemetry/opentelemetry-specification/pull/4024.

Reference: https://pkg.go.dev/go.opentelemetry.io/otel/metric#hdr-API_Implementations

**Comment by MrAlias** [comment]
SDK interfaces are implemented by end-users, not SDK authors. Extending these interfaces will break them and we should not do that.

**Comment by pellared** [comment]
@MrAlias, would you rather prefer adding new interfaces and options that would support them?

**Comment by pellared** [comment]
I think we can refer to https://go.dev/blog/module-compatibility#working-with-interfaces in the `DESIGN.md` as a way to add new features to `Processor` and `Exporter`.
