### ISSUE TITLE
sdk/trace: Log when an attribute/event/link is discarded due to limits

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go#5343]
From https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#span-limits:

> There SHOULD be a message printed in the SDK's log to indicate to the user that an attribute was discarded due to such a limit. To prevent excessive logging, the message MUST be printed at most once per span (i.e., not per discarded attribute, event, or link).

**Comment by MrAlias** [comment]
Updating the title. There is not recommendation that truncated attributes be logged.

**Comment by MrAlias** [comment]
There is specification ambiguity about discarded events and links being logged. I'm going to assume https://github.com/open-telemetry/opentelemetry-specification/pull/4064 lands and log for all.
