### ISSUE TITLE
log: Logger should be indentified also by SchemeURL

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go#5366]
From spec https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/bridge-api.md#get-a-logger:

> Loggers are identified by name, version, and schema_url fields. 

In code:

https://github.com/open-telemetry/opentelemetry-go/blob/bf06b80a777c1d6b4740486e3bfa31dcf9048300/log/internal/global/log.go#L40-L54

We are missing `SchemeURL` in the key.

Side note: There may be the same bug for other signals.

**Comment by pellared** [comment]
It looks like the same issue is for tracing and metrics: https://github.com/open-telemetry/opentelemetry-go/blob/bf06b80a777c1d6b4740486e3bfa31dcf9048300/internal/global/trace.go#L104-L107

**Comment by MrAlias** [comment]
> It looks like the same issue is for `Tracer` and `Meter`:
> 
> https://github.com/open-telemetry/opentelemetry-go/blob/bf06b80a777c1d6b4740486e3bfa31dcf9048300/internal/global/trace.go#L104-L107

Please open issues to track these needed changes.
