### ISSUE TITLE
Audit the addition of the synchronous gauge

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#5369]
https://github.com/open-telemetry/opentelemetry-go/pull/5304

Added to the spec [here](https://github.com/open-telemetry/opentelemetry-specification/pull/3540)

**Comment by MrAlias** [comment]
> There MUST NOT be any API for creating a Gauge other than with a [Meter](https://github.com/open-telemetry/opentelemetry-specification/diffs/1?base_sha=f20566d6651941a10188c3eb2c0ea4519d5d7be0&branch=b376646d3e01b24dd71a057231a7b25f3a1312f0&commentable=true&head_user=jack-berg&name=b376646d3e01b24dd71a057231a7b25f3a1312f0&pull_number=3540&qualified_name=b376646d3e01b24dd71a057231a7b25f3a1312f0&sha1=f20566d6651941a10188c3eb2c0ea4519d5d7be0&sha2=b376646d3e01b24dd71a057231a7b25f3a1312f0&short_path=0556612&unchanged=expanded&w=false#meter).

From the exported API, the only way to create a (non-trivial `nil`) `Gauge` is via the `Meter` API:

https://github.com/open-telemetry/opentelemetry-go/blob/ebd0adee357f3539d7b19488eef9cf7bcd8aa0da/metric/meter.go#L61-L64

https://github.com/open-telemetry/opentelemetry-go/blob/ebd0adee357f3539d7b19488eef9cf7bcd8aa0da/metric/meter.go#L111-L114

**Comment by MrAlias** [comment]
> This MAY be called CreateGauge. If strong type is desired, [OpenTelemetry API](https://github.com/open-telemetry/opentelemetry-specification/blob/b376646d3e01b24dd71a057231a7b25f3a1312f0/specification/overview.md#api) authors MAY decide the language idiomatic name(s), for example CreateUInt64Gauge, CreateDoubleGauge, CreateGauge<UInt64>, CreateGauge<double>.

We do not follow this optional. Our names are `Int64Gauge` and `Float64Gauge`.

Given the optional nature, we remain compliant.

**Comment by MrAlias** [comment]
> This API SHOULD NOT return a value (it MAY return a dummy value if required by certain programming languages or systems, for example null, undefined).

Our interface type declarations require the type to not return a value:

https://github.com/open-telemetry/opentelemetry-go/blob/ebd0adee357f3539d7b19488eef9cf7bcd8aa0da/metric/syncfloat64.go#L187-L191

https://github.com/open-telemetry/opentelemetry-go/blob/ebd0adee357f3539d7b19488eef9cf7bcd8aa0da/metric/syncint64.go#L187-L191

**Comment by MrAlias** [comment]
> This API MUST accept the following parameter:
> 
> - A numeric value. The current absolute value.
> 
>   The value needs to be provided by a user. If possible, this API SHOULD be structured so a user is obligated to provide this parameter. If it is not possible to structurally enforce this obligation, this API MUST be documented in a way to communicate to users that this parameter is needed.
> 
> - [Attributes](https://github.com/open-telemetry/opentelemetry-specification/blob/b376646d3e01b24dd71a057231a7b25f3a1312f0/specification/common/README.md#attribute) to associate with the value.
> 
>   Users can provide attributes to associate with the value, but it is up to their discretion. Therefore, this API MUST be structured to accept a variable number of attributes, including none.

Our interface type declarations require a value parameter and can accept options:

https://github.com/open-telemetry/opentelemetry-go/blob/ebd0adee357f3539d7b19488eef9cf7bcd8aa0da/metric/syncfloat64.go#L187-L191

https://github.com/open-telemetry/opentelemetry-go/blob/ebd0adee357f3539d7b19488eef9cf7bcd8aa0da/metric/syncint64.go#L187-L191

The `WithAttributeSet` and `WithAttributes` both return a `MeasurmentOption`:

https://github.com/open-telemetry/opentelemetry-go/blob/ebd0adee357f3539d7b19488eef9cf7bcd8aa0da/metric/instrument.go#L339-L347

[`RecordOption`](https://github.com/open-telemetry/opentelemetry-go/blob/ebd0adee357f3539d7b19488eef9cf7bcd8aa0da/metric/instrument.go#L349-L368)

These `MeasurmentOption`s can be used as a `RecordOption`:

https://github.com/open-telemetry/opentelemetry-go/blob/ebd0adee357f3539d7b19488eef9cf7bcd8aa0da/metric/instrument.go#L283-L288

We comply with this requirement from the specification.

**Comment by MrAlias** [comment]
> The [OpenTelemetry API](https://github.com/open-telemetry/opentelemetry-specification/blob/b376646d3e01b24dd71a057231a7b25f3a1312f0/specification/overview.md#api) authors MAY decide to allow flexible [attributes](https://github.com/open-telemetry/opentelemetry-specification/blob/b376646d3e01b24dd71a057231a7b25f3a1312f0/specification/common/README.md#attribute) to be passed in as arguments. If the attribute names and types are provided during the [gauge creation](https://github.com/open-telemetry/opentelemetry-specification/diffs/1?base_sha=f20566d6651941a10188c3eb2c0ea4519d5d7be0&branch=b376646d3e01b24dd71a057231a7b25f3a1312f0&commentable=true&head_user=jack-berg&name=b376646d3e01b24dd71a057231a7b25f3a1312f0&pull_number=3540&qualified_name=b376646d3e01b24dd71a057231a7b25f3a1312f0&sha1=f20566d6651941a10188c3eb2c0ea4519d5d7be0&sha2=b376646d3e01b24dd71a057231a7b25f3a1312f0&short_path=0556612&unchanged=expanded&w=false#gauge-creation), the [OpenTelemetry API](https://github.com/open-telemetry/opentelemetry-specification/blob/b376646d3e01b24dd71a057231a7b25f3a1312f0/specification/overview.md#api) authors MAY allow attribute values to be passed in using a more efficient way (e.g. strong typed struct allocated on the callstack, tuple). The API MUST allow callers to provide flexible attributes at invocation time rather than having to register all the possible attribute names during the instrument creation.

We do not provide the optional ability to accept 'flexible attributes' during the gauge creation. We do comply with the requirement to accept attributes at "invocation time" as outlined [here](https://github.com/open-telemetry/opentelemetry-go/issues/5369#issuecomment-2118246668).

**Comment by MrAlias** [comment]
See the [general requirements for synchronous instruments](https://github.com/open-telemetry/opentelemetry-specification/diffs/1?base_sha=f20566d6651941a10188c3eb2c0ea4519d5d7be0&branch=b376646d3e01b24dd71a057231a7b25f3a1312f0&commentable=true&head_user=jack-berg&name=b376646d3e01b24dd71a057231a7b25f3a1312f0&pull_number=3540&qualified_name=b376646d3e01b24dd71a057231a7b25f3a1312f0&sha1=f20566d6651941a10188c3eb2c0ea4519d5d7be0&sha2=b376646d3e01b24dd71a057231a7b25f3a1312f0&short_path=0556612&unchanged=expanded&w=false#synchronous-instrument-api).

https://opentelemetry.io/docs/specs/otel/metrics/api/#synchronous-instrument-api

> The API to construct synchronous instruments MUST accept the following parameters:
> 
> - A name of the Instrument.
> 
>   The name needs to be provided by a user. If possible, the API SHOULD be structured so a user is obligated to provide this parameter. If it is not possible to structurally enforce this obligation, the API MUST be documented in a way to communicate to users that this parameter is needed.
>   The API SHOULD be documented in a way to communicate to users that the name parameter needs to conform to the [instrument name syntax](https://opentelemetry.io/docs/specs/otel/metrics/api/#instrument-name-syntax). The API SHOULD NOT validate the name; that is left to implementations of the API.

https://github.com/open-telemetry/opentelemetry-go/blob/ebd0adee357f3539d7b19488eef9cf7bcd8aa0da/metric/meter.go#L61-L64

https://github.com/open-telemetry/opentelemetry-go/blob/ebd0adee357f3539d7b19488eef9cf7bcd8aa0da/metric/meter.go#L111-L114

We comply with the required structure of accepting a `name`.

The recommendation to document what the name should be is not present. Nor is is present on any other method.

We need to track this as a fix for all methods. It is not blocking for this issue.

We do not validate the name in the API.

> - A unit of measure.
> 
>   Users can provide a unit, but it is up to their discretion. Therefore, this API needs to be structured to accept a unit, but MUST NOT obligate a user to provide one.
> 
>   The unit parameter needs to support the [instrument unit rule](https://opentelemetry.io/docs/specs/otel/metrics/api/#instrument-unit). Meaning, the API MUST accept a case-sensitive string that supports ASCII character encoding and can hold at least 63 characters. The API SHOULD NOT validate the unit.

[`WithUnit`](https://github.com/open-telemetry/opentelemetry-go/blob/ebd0adee357f3539d7b19488eef9cf7bcd8aa0da/metric/instrument.go#L186-L189) can be used to pass an [`InstrumentOption`](https://github.com/open-telemetry/opentelemetry-go/blob/ebd0adee357f3539d7b19488eef9cf7bcd8aa0da/metric/instrument.go#L14-L31). The user is not obligated to do this.

We do not validate the unit.

> - A description describing the Instrument in human-readable terms.
> 
>   Users can provide a description, but it is up to their discretion. Therefore, this API needs to be structured to accept a description, but MUST NOT obligate a user to provide one.
> 
>   The description needs to support the [instrument description rule](https://opentelemetry.io/docs/specs/otel/metrics/api/#instrument-description). Meaning, the API MUST accept a string that supports at least [BMP (Unicode Plane 0)](https://en.wikipedia.org/wiki/Plane_%28Unicode%29#Basic_Multilingual_Plane) encoded characters and hold at least 1023 characters.

[`WithDescription`](https://github.com/open-telemetry/opentelemetry-go/blob/ebd0adee357f3539d7b19488eef9cf7bcd8aa0da/metric/instrument.go#L111-L112) can be used to pass an [`InstrumentOption`](https://github.com/open-telemetry/opentelemetry-go/blob/ebd0adee357f3539d7b19488eef9cf7bcd8aa0da/metric/instrument.go#L14-L31). The user is not obligated to do this.

> - advisory parameters associated with the instrument kind.
> 
>   Users can provide advisory parameters, but its up to their discretion. Therefore, this API needs to be structured to accept advisory parameters, but MUST NOT obligate the user to provide it.
> 
>   advisory parameters need to be structured as described in [instrument advisory parameters](https://opentelemetry.io/docs/specs/otel/metrics/api/#instrument-advisory-parameters), with parameters that are general and specific to a particular instrument kind. The API SHOULD NOT validate advisory parameters.

There are no stable advisory parameters that apply to this instrument kind: https://opentelemetry.io/docs/specs/otel/metrics/api/#instrument-advisory-parameters

When applicable advisory parameters are added or stabilized they can be added as options.

**Comment by MrAlias** [comment]
> For synchronous instruments with Cumulative aggregation temporality, MetricReader.Collect MUST receive data points exposed in previous collections regardless of whether new measurements have been recorded.
> For synchronous instruments with Delta aggregation temporality, MetricReader.Collect MUST only receive data points with measurements recorded since the previous collection.

The aggregation selection in the SDK:

https://github.com/open-telemetry/opentelemetry-go/blob/ebd0adee357f3539d7b19488eef9cf7bcd8aa0da/sdk/metric/pipeline.go#L449-L452

For delta temporality:

https://github.com/open-telemetry/opentelemetry-go/blob/ebd0adee357f3539d7b19488eef9cf7bcd8aa0da/sdk/metric/internal/aggregate/aggregate.go#L80-L81

For cumulative temporality:

https://github.com/open-telemetry/opentelemetry-go/blob/ebd0adee357f3539d7b19488eef9cf7bcd8aa0da/sdk/metric/internal/aggregate/aggregate.go#L82-L83

We comply with this requirement.

**Comment by MrAlias** [comment]
> The MetricReader selection of temporality as a function of instrument kind influences the starting timestamp (i.e. StartTimeUnixNano) of metrics data points received by [MetricReader.Collect](https://github.com/open-telemetry/opentelemetry-specification/diffs/2?base_sha=f20566d6651941a10188c3eb2c0ea4519d5d7be0&branch=b376646d3e01b24dd71a057231a7b25f3a1312f0&commentable=true&head_user=jack-berg&name=b376646d3e01b24dd71a057231a7b25f3a1312f0&pull_number=3540&qualified_name=b376646d3e01b24dd71a057231a7b25f3a1312f0&sha1=f20566d6651941a10188c3eb2c0ea4519d5d7be0&sha2=b376646d3e01b24dd71a057231a7b25f3a1312f0&short_path=32d5f28&unchanged=expanded&w=false#collect). For instruments with Cumulative aggregation temporality, successive data points received by successive calls to [MetricReader.Collect](https://github.com/open-telemetry/opentelemetry-specification/diffs/2?base_sha=f20566d6651941a10188c3eb2c0ea4519d5d7be0&branch=b376646d3e01b24dd71a057231a7b25f3a1312f0&commentable=true&head_user=jack-berg&name=b376646d3e01b24dd71a057231a7b25f3a1312f0&pull_number=3540&qualified_name=b376646d3e01b24dd71a057231a7b25f3a1312f0&sha1=f20566d6651941a10188c3eb2c0ea4519d5d7be0&sha2=b376646d3e01b24dd71a057231a7b25f3a1312f0&short_path=32d5f28&unchanged=expanded&w=false#collect) MUST repeat the same starting timestamps (e.g. (T0, T1], (T0, T2], (T0, T3]). For instruments with Delta aggregation temporality, successive data points received by successive calls to [MetricReader.Collect](https://github.com/open-telemetry/opentelemetry-specification/diffs/2?base_sha=f20566d6651941a10188c3eb2c0ea4519d5d7be0&branch=b376646d3e01b24dd71a057231a7b25f3a1312f0&commentable=true&head_user=jack-berg&name=b376646d3e01b24dd71a057231a7b25f3a1312f0&pull_number=3540&qualified_name=b376646d3e01b24dd71a057231a7b25f3a1312f0&sha1=f20566d6651941a10188c3eb2c0ea4519d5d7be0&sha2=b376646d3e01b24dd71a057231a7b25f3a1312f0&short_path=32d5f28&unchanged=expanded&w=false#collect) MUST advance the starting timestamp ( e.g. (T0, T1], (T1, T2], (T2, T3]). The ending timestamp (i.e. TimeUnixNano) MUST always be equal to time the metric data point took effect, which is equal to when [MetricReader.Collect](https://github.com/open-telemetry/opentelemetry-specification/diffs/2?base_sha=f20566d6651941a10188c3eb2c0ea4519d5d7be0&branch=b376646d3e01b24dd71a057231a7b25f3a1312f0&commentable=true&head_user=jack-berg&name=b376646d3e01b24dd71a057231a7b25f3a1312f0&pull_number=3540&qualified_name=b376646d3e01b24dd71a057231a7b25f3a1312f0&sha1=f20566d6651941a10188c3eb2c0ea4519d5d7be0&sha2=b376646d3e01b24dd71a057231a7b25f3a1312f0&short_path=32d5f28&unchanged=expanded&w=false#collect) was invoked. These rules apply to all metrics, not just those whose [point kinds](https://github.com/open-telemetry/opentelemetry-specification/blob/b376646d3e01b24dd71a057231a7b25f3a1312f0/specification/metrics/data-model.md#point-kinds) includes an aggregation temporality field.

delta:

https://github.com/open-telemetry/opentelemetry-go/blob/ebd0adee357f3539d7b19488eef9cf7bcd8aa0da/sdk/metric/internal/aggregate/lastvalue.go#L63-L80

cumulative:

https://github.com/open-telemetry/opentelemetry-go/blob/ebd0adee357f3539d7b19488eef9cf7bcd8aa0da/sdk/metric/internal/aggregate/lastvalue.go#L82-L98

With `start` being set on creation:

https://github.com/open-telemetry/opentelemetry-go/blob/ebd0adee357f3539d7b19488eef9cf7bcd8aa0da/sdk/metric/internal/aggregate/lastvalue.go#L24-L31

**Comment by MrAlias** [comment]
@dashpole (and all other @open-telemetry/go-approvers) I believe I've completed the audit. We you concur, please go ahead and close this issue.

**Comment by MrAlias** [comment]
From https://github.com/open-telemetry/opentelemetry-go/issues/5369#issuecomment-2118274205

> The recommendation to document what the name should be is not present. Nor is is present on any other method.
> 
> We need to track this as a fix for all methods. It is not blocking for this issue.

Tracking in https://github.com/open-telemetry/opentelemetry-go/issues/5377

**Comment by dashpole** [comment]
Thanks @MrAlias.  LGTM
