### ISSUE TITLE
Consider using go module paths for scope name in demos

### ISSUE THREAD

**Issue by dashpole** [open-telemetry/opentelemetry-go#5412]
### Problem Statement

I noticed the rolldice example has a single-word name for the meter and tracer:

https://github.com/open-telemetry/opentelemetry-go/blob/ca93aae3e9f6922f623d193fac84b13f26dfc0b3/example/dice/rolldice.go#L12-L17

I haven't checked other examples, but IMO we should consider doing this across all of them.

### Proposed Solution

Since many users will use this as a starting point for their code, would it make more sense to use a "real" scope name?  E.g. `go.opentelemetry.io/otel/example/dice`?

#### Alternatives

Keep simpler names for samples

**Comment by dashpole** [comment]
Also, should we document the convention that the go import path of the library producing the telemetry should be used as the scope name?

**Comment by MrAlias** [comment]
To complete this, the docs site will need to be updated as well.

**Comment by MrAlias** [comment]
> Also, should we document the convention that the go import path of the library producing the telemetry should be used as the scope name?

We already document this directly for the Meter and Tracer:

- https://github.com/open-telemetry/opentelemetry-go/blob/d595dab76fd30a34ef8c739effc7c845c24dd21f/trace/trace.go#L548-L551
- https://github.com/open-telemetry/opentelemetry-go/blob/d595dab76fd30a34ef8c739effc7c845c24dd21f/metric/meter.go#L26-L29

We should add this to the LoggerProvider: https://github.com/open-telemetry/opentelemetry-go/blob/d595dab76fd30a34ef8c739effc7c845c24dd21f/log/provider.go#L19-L25

@dashpole do you think this is adequate documentation?

**Comment by MrAlias** [comment]
> We should add this to the LoggerProvider:

#5613

**Comment by dashpole** [comment]
> @dashpole do you think this is adequate documentation?

yes, thank you!
