### ISSUE TITLE
metric: Add example and documentation for synchronous gauge

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go#5414]
Follows https://github.com/open-telemetry/opentelemetry-go/pull/5304

- [ ] Add an example for sync gauge here: https://github.com/open-telemetry/opentelemetry-go/blob/main/metric/example_test.go
- [ ] Add a new section for sync gauge here: https://opentelemetry.io/docs/languages/go/instrumentation/#metrics

**Comment by bagmeg** [comment]
Hi! I'm interested in this issue. Can I work on it?

**Comment by bagmeg** [comment]
hi @pellared. Both issue for checklist are merged.
