### ISSUE TITLE
Extend plugin/othttp handler to collect metrics as well as traces

### ISSUE THREAD

**Issue by evantorrie** [open-telemetry/opentelemetry-go#542]
The `plugin/othttp` middleware currently extracts trace ids and context from an incoming HTTP request, creates a new Otel span and augments it with [attributes culled from the request and response](https://github.com/open-telemetry/opentelemetry-go/blob/master/plugin/othttp/handler.go#L31-L41 ).

Many systems, including the [Opencensus http plugin](https://github.com/census-instrumentation/opencensus-go/tree/master/plugin/ochttp), also produce [corresponding metrics](https://github.com/census-instrumentation/opencensus-go/blob/master/plugin/ochttp/server.go#L149-L167) such as
  * server requests
  * server latency
  * bytes read
  * bytes written

tagged with very similar attributes as collected in our Otel http plugin.

As OpenTelemetry combines tracing and metrics, it would seem we should be able to optionally produce similar metrics in an automated fashion using `plugin/othttp`.

**Comment by evantorrie** [comment]
See some related discussion to this in https://github.com/open-telemetry/opentelemetry-specification/issues/381

**Comment by rghetia** [comment]
It would be good to have standard metrics defined for http for plugins in the spec.

**Comment by AndrewGrachov** [comment]
Hi, we are adapting the opentelemetry now(our stack is both Golang and Nodejs), 
so would like to contribute and take this
