### ISSUE TITLE
Internal logger.Emit delegate never gets loaded

### ISSUE THREAD

**Issue by zergeborg** [open-telemetry/opentelemetry-go#5439]
I raised this issue with the [otelzap](https://github.com/uptrace/opentelemetry-go-extra/issues/128) library maintainers too, but it seems the delegate that the logger holds in the `logger.Emit` method never gets loaded.

The maintainer in that repository suggested:

> You probably don't have tracing configured and/or span created. For some reason, OpenTelemetry logger ignores the log record if the context does not contain a valid span/trace id

Although I am not sure if that is indeed the culprit. I can successfully create the tracer and send the spans to GCP, and they show up just fine in the Trace Explorer.

The only thing which is not working is the delegate loading mechanism (which my code has no control of, because it's controlled by `otelzap` and `otel/log`).

https://github.com/open-telemetry/opentelemetry-go/blob/982e96dd9bd4b9751ac5b8f4a68ff7085775c260/log/internal/global/log.go#L85

**Comment by MrAlias** [comment]
Can you provide a minimal example to reproduce the issue?

**Comment by pellared** [comment]
You have forgotten to set the https://pkg.go.dev/github.com/uptrace/opentelemetry-go-extra/otelzap#WithLoggerProvider option.

**Comment by zergeborg** [comment]
@pellared Thank you for your quick response.

I tried your suggestion, but it didn't change anything. Now my code creates the zap logger as follows:
```golang
	otellogger = otelzap.New(logger,
		otelzap.WithMinLevel(zap.DebugLevel),
		otelzap.WithErrorStatusLevel(zap.ErrorLevel),
		otelzap.WithLoggerProvider(global.GetLoggerProvider()),
	)
```

But the bug remains the same. The delegate stays unloaded and the logger never emits

**Comment by dmathieu** [comment]
> otelzap.WithLoggerProvider(global.GetLoggerProvider())

This does nothing. It uses the global logger provided, which is not set.
Also, if you look at the doc for [WithLoggerProvider](https://pkg.go.dev/github.com/uptrace/opentelemetry-go-extra/otelzap#WithLoggerProvider), you will see that this option defaults to the global logger provider already.

You need to create and configure a logger provider.
https://github.com/open-telemetry/opentelemetry-go/blob/91a8c5fee4edcf1ef9a676bc37b980d8cfdebf7d/example/dice/otel.go#L114-L124

The provider is this example is configured to send its data to stdout, but you will be able to configure the otlp exporter once it is available if you wish.

And then, either set it as global, or pass it to otelzap with `WithLoggerProvider`.
https://github.com/open-telemetry/opentelemetry-go/blob/91a8c5fee4edcf1ef9a676bc37b980d8cfdebf7d/example/dice/otel.go#L73

**Comment by zergeborg** [comment]
Thank you @dmathieu Indeed that was the problem. After I applied your suggestion, the logs started working, I can see the output in stdout, so I will close the issue.
