### ISSUE TITLE
IDGenerator may generate zero TraceId / SpanId

### ISSUE THREAD

**Issue by vijayaggarwal** [open-telemetry/opentelemetry-go#5462]
### Description

The spec (https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md) mentions that TraceId and SpanId must have at least one non-zero byte. However, the default id generator doesn't ensure that (https://github.com/open-telemetry/opentelemetry-go/blob/main/sdk/trace/id_generator.go#L44). The generator simply uses rand.Read() which does not guarantee non-zero output.

### Environment

All environments

### Steps To Reproduce

Difficult to give exact steps to reproduce, as random number generation is involved.

### Expected behavior

Generated TraceId and SpanId must always be non-zero as per spec.

**Comment by Charlie-lizhihan** [comment]
Hi there, I think this one is the same issue as [RandomIdGenerator can generate invalid Span/Trace Ids #3921](https://github.com/open-telemetry/opentelemetry-python/issues/3921)

And I'm working on solve this one, thanks for raising it!
