### ISSUE TITLE
Build Error: nonRecordingSpan and recordingSpan do not implement trace.Span due to missing AddLink method

### ISSUE THREAD

**Issue by mtmibjas** [open-telemetry/opentelemetry-go#5465]
### Description
I am encountering build issues when working with the OpenTelemetry Go SDK version v1.21.0. Specifically, the nonRecordingSpan and recordingSpan types do not seem to fully implement the trace.Span interface due to a missing AddLink method. Below are the details of the errors encountered:

```
/Users/meta/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.21.0/trace/tracer.go:120:10: cannot use tr.newNonRecordingSpan(sc) (value of type nonRecordingSpan) as "go.opentelemetry.io/otel/trace".Span value in return statement: nonRecordingSpan does not implement "go.opentelemetry.io/otel/trace".Span (missing method AddLink)
/Users/meta/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.21.0/trace/tracer.go:122:9: cannot use tr.newRecordingSpan(psc, sc, name, samplingResult, config) (value of type *recordingSpan) as "go.opentelemetry.io/otel/trace".Span value in return statement: *recordingSpan does not implement "go.opentelemetry.io/otel/trace".Span (missing method AddLink)
have addLink("go.opentelemetry.io/otel/trace".Link)
want AddLink("go.opentelemetry.io/otel/trace".Link)
```
**Steps to Reproduce:**

1. Use OpenTelemetry Go SDK version v1.21.0.
2. Attempt to build the project with the following command: go build.

### Environment

- Go Version: 1.21.4
go.opentelemetry.io/otel v1.27.0
go.opentelemetry.io/otel/sdk v1.21.0
go.opentelemetry.io/otel/trace v1.27.0

**Expected Behavior:**

The project should build successfully without any errors.

**Actual Behavior:**

The build process fails due to the nonRecordingSpan and recordingSpan types not implementing the trace.Span interface correctly, as they lack the AddLink method.

Thank you for your assistance in resolving this issue.

**Comment by pellared** [comment]
Bump go.opentelemetry.io/otel/trace to v1.27.0

**Comment by mtmibjas** [comment]
@pellared I did not get your point.. what is wrong here?

**Comment by dmathieu** [comment]
> go.opentelemetry.io/otel/sdk v1.21.0

This needs to be 1.27.0. The SDK and API versions need to match.
