### ISSUE TITLE
The codespell GitHub workflow doesn't work as expected

### ISSUE THREAD

**Issue by rockdaboot** [open-telemetry/opentelemetry-go#5467]
### Description

Running `make codespell` locally finds and fixes several typos, while the GH workflow `codespell.yaml` doesn't report anything.

### Steps To Reproduce

See no reporting in the codespell action output, e.g. in https://github.com/open-telemetry/opentelemetry-go/actions/runs/9347103111/job/25723365608 .

Run `make codespell` locally and check with `git diff`.

### Expected behavior

The codespell GH workflow should detect spelling errors and report by failing (and thus failing the CI).

**Comment by pellared** [comment]
I cannot reproduce it on `main`.

**Comment by rockdaboot** [comment]
Sorry, `main` was outdated here.
