### ISSUE TITLE
baggage.New panics on members with values including 0x80 char

### ISSUE THREAD

**Issue by fabiobozzo** [open-telemetry/opentelemetry-go#5495]
### Description

The validation rule for baggage key/values chars has a N+1 problem with the unicode value: 0x80.  
For instance, baggage.NewMemberRaw could be called with a string value including the rune 128 and return no error, but panic.

=== RUN   TestValidateValueChar
--- FAIL: TestValidateValueChar (0.00s)
panic: runtime error: index out of range [128] with length 128 [recovered]
	panic: runtime error: index out of range [128] with length 128

**Solution in**: https://github.com/open-telemetry/opentelemetry-go/pull/5494 👈 

### Environment

- OS: any
- Architecture: any
- Go Version: 1.21+
- opentelemetry-go version: [v1.26.0, 59bbe11]

### Steps To Reproduce

1. Call `baggage.NewMemberRaw` with a string (value, or key) including the `0x80` rune.
2. The new member is returned with no errors.
3. Call `baggage.New` with that member
4. `validateValueChar` in the downstream call stack panics because of an unsafe slice boundary check

### Expected behavior

The creation of a baggage member having strings including the `0x80` char fails with an error, instead of panicking.

**Comment by MrAlias** [comment]
Closed by #5494
