### ISSUE TITLE
Baggage propagation - replace invalid percent-encoded octet sequnces with replacement char

### ISSUE THREAD

**Issue by lachmatt** [open-telemetry/opentelemetry-go#5519]
[W3C baggage spec](https://github.com/w3c/baggage/blob/8c215efbeebd3fa4b1aceb937a747e56444f22f3/baggage/HTTP_HEADER_FORMAT.md?plain=1#L69) requires:

> When decoding the value, percent-encoded octet sequences that do not match the UTF-8 encoding scheme MUST be replaced with the replacement code point (`U+FFFD`).

This situation is currently not handled correctly - see [playground](https://go.dev/play/p/Ga5oBeTL3B2) for sample:

```go
package main

import (
	"fmt"
	"log"
	"unicode/utf8"

	"go.opentelemetry.io/otel/baggage"
)

func main() {
	kv := "k=aa%ffcc"

	b, err := baggage.Parse(kv)
	if err != nil {
		log.Fatal(err)
	}
	val := b.Members()[0].Value()

	fmt.Println(val)
	fmt.Println(len(val))
	fmt.Println(utf8.ValidString(val))

	validStringWithReplacements := "aa�cc"
	fmt.Println(len(validStringWithReplacements))
	fmt.Println(utf8.ValidString(validStringWithReplacements))
}
```

**Comment by santileira** [comment]
hey @lachmatt what is the expected behavior? 

that code should return 7 and true, right?
```
fmt.Println(len(val))
fmt.Println(utf8.ValidString(val))
```

**Comment by pellared** [comment]
> that code should return 7 and true

This is correct.

**Comment by pellared** [comment]
> that code should return 7 and true

This is correct.

Reference: https://www.compart.com/en/unicode/U+FFFD

**Comment by santileira** [comment]
@pellared I could fix it, could you assign me this issue?

**Comment by santileira** [comment]
@pellared / @dmathieu We already merged the code to solve this issue, should we close the issue? Thanks

**Comment by dmathieu** [comment]
Fixed in https://github.com/open-telemetry/opentelemetry-go/pull/5528.
