### ISSUE TITLE
OTLP exporter does not comply with throttling and retrying specification

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-go#561]
OTLP requires clients to honor server-requested throttling and retry logic. See protocol specification: 
 - Result code - https://github.com/open-telemetry/oteps/blob/master/text/0035-opentelemetry-protocol.md#result-code
- Throttling - https://github.com/open-telemetry/oteps/blob/master/text/0035-opentelemetry-protocol.md#throttling

We also have an ongoing PR that changes how exactly this information is conveyed in the response: https://github.com/open-telemetry/oteps/pull/65

I do not see this handled anywhere in the exporter code. If it is handled please point me to the appropriate place in the code and close this issue.

**Comment by tigrannajaryan** [comment]
https://github.com/open-telemetry/oteps/pull/65 is now merged.

**Comment by MrAlias** [comment]
Going to setup a ServiceConfig for the trace and metric services with a retry policy something like this:

```
{
   "methodConfig":[
      {
         "name":[
            {
               "service":"opentelemetry.proto.collector.metrics.v1.MetricsService"
            },
            {
               "service":"opentelemetry.proto.collector.trace.v1.TraceService"
            }
         ],
         "retryPolicy":{
            "MaxAttempts":4,
            "InitialBackoff":".01s",
            "MaxBackoff":".01s",
            "BackoffMultiplier":1.0,
            "RetryableStatusCodes":[
               "UNAVAILABLE",
               "CANCELED",
               "DEADLINE_EXCEEDED",
               "RESOURCE_EXHAUSTED",
               "ABORTED",
               "OUT_OF_RANGE",
               "UNAVAILABLE",
               "DATA_LOSS"
            ]
         }
      }
   ]
}

```

From reading [the docs](https://github.com/grpc/proposal/blob/master/A6-client-retries.md) it sounds like this will achieve both exponential backoff and support pushback (called throttling in the OTEP).

**Comment by tigrannajaryan** [comment]
>"BackoffMultiplier":1.0,
I think this will not result in exponential backoff. I believe it needs to be higher than 1.0 for exponential. I think we need something like 2.0 here.

>"MaxBackoff":"1.0s",
This is the maximum interval between retries, right? This looks too low to me. Perhaps go a bit higher to avoid overloading already strained recipients. (e.g. in the scenario when thousands of senders send to a single Collector).

**Comment by MrAlias** [comment]
> > "BackoffMultiplier":1.0,
> 
> I think this will not result in exponential backoff. I believe it needs to be higher than 1.0 for exponential. I think we need something like 2.0 here.
>
> > "MaxBackoff":"1.0s",
> 
> This is the maximum interval between retries, right? This looks too low to me. Perhaps go a bit higher to avoid overloading already strained recipients. (e.g. in the scenario when thousands of senders send to a single Collector).

Agreed, these were more placeholders.

I was able to setup some test framework to try this out, but discovered that you can only enable retries by setting the `GRPC_GO_RETRY=on` environment variable at runtime. Not a big deal when actually running the exporter, but it makes this un-testable without updating the Makefile to include this var. Still thinking about this.

As for the config. I'm planning to go with numbers closer to this:

```
{
	"methodConfig":[{
		"name":[
			{ "service":"opentelemetry.proto.collector.metrics.v1.MetricsService" },
			{ "service":"opentelemetry.proto.collector.trace.v1.TraceService" }
		],
		"waitForReady": true,
		"retryPolicy":{
			"MaxAttempts":5,
			"InitialBackoff":"0.3s",
			"MaxBackoff":"5s",
			"BackoffMultiplier":2,
			"RetryableStatusCodes":[
				"UNAVAILABLE",
				"CANCELLED",
				"DEADLINE_EXCEEDED",
				"RESOURCE_EXHAUSTED",
				"ABORTED",
				"OUT_OF_RANGE",
				"UNAVAILABLE",
				"DATA_LOSS"
			]
		}
	}]
}
```

With this back-off structure, at worst (given the random jitter gRPC adds) the retries would look like:

| Request | Max Wait Before Retry [Seconds] |
| ------- | ------- |
| 0 (initial) | 0.000 |
| 1 | 0.300 |
| 2 | 0.900 |
| 3 | 2.100 |
| 4 | 4.500 |

@tigrannajaryan what do you think about this schedule? We could also be more aggressive in the initial delay or exponential factor.

It was interesting to discover that increasing the `MaxAttempts` past `5` has no effect. That is the maximum the gRPC library allows. Seems like a decent amount of retries, but interesting nonetheless.

**Comment by tigrannajaryan** [comment]
> I was able to setup some test framework to try this out, but discovered that you can only enable retries by setting the `GRPC_GO_RETRY=on` environment variable at runtime.

Ahh, pity. I am guessing most people won't benefit from this since they won't be bothered to find and enable this setting. Perhaps worth doing regardless.

Alternatively, borrow the implementation from the Collector: https://github.com/open-telemetry/opentelemetry-collector/blob/87af38a2467650e2e96b0f393fb69b974d467d62/exporter/otlpexporter/exporter.go#L87

>what do you think about this schedule? We could also be more aggressive in the initial delay or exponential factor.

The schedule looks good to me except the limitation of 5 total retries.

>Seems like a decent amount of retries, but interesting nonetheless.

5 retries over a total period of less than 10 seconds looks a bit low to me, but probably acceptable. I'd prefer to have a more stubborn exporter, one that can survive a crash/restart/redeployment of the Collector, which arguably could take a bit more than 10 seconds. I'd be happier with something around 30 seconds or 1 min.
