### ISSUE TITLE
OLTP exporter should check return value from checkpointSet ForEach()

### ISSUE THREAD

**Issue by evantorrie** [open-telemetry/opentelemetry-go#562]
#557 changed the `CheckpointSet.ForEach()` interface to 
  
   * return an error from `ForEach`
   * allow the function passed to `ForEach()` to also return an error

The OLTP `ForEach()` code should be modified to reflect this change in error reporting behavior.  Currently it ignores any error returned from `ForEach()` (it could for example, return `ctx.Err()` from the record function handler in order to abort the current checkpoint set).

**Comment by MrAlias** [comment]
Fixed in https://github.com/open-telemetry/opentelemetry-go/pull/626
