### ISSUE TITLE
Example run error

### ISSUE THREAD

**Issue by onenewcode** [open-telemetry/opentelemetry-go#5652]
### Description

example/namedtracer/main.go  

An error in the file regarding the usage of baggage

The following code in the example does not create a new object and returns an error.
```go
fooKey     = attribute.Key("ex.com/foo")
m0, _ := baggage.NewMemberRaw(string(fooKey), "foo1")
```

Because when the validateKeyChar method in baggage checks for '/', it returns an error.

Because safeKeyCharset  in baggage doesn't contain '/'。

### Expected behavior

Example  run

**Comment by pellared** [comment]
This is may be fixed by https://github.com/open-telemetry/opentelemetry-go/pull/5132

However, notice that W3C baggage propagator would not handle such keys.

**Comment by onenewcode** [comment]
> This is may be fixed by #5132
> 
> However, notice that W3C baggage propagator would not handle such keys.

I see

**Comment by pellared** [comment]
What do you expect?

**Comment by onenewcode** [comment]
As a new user of the framework, I had little knowledge of the w3c specification. I just want the functionality shown by example to work. Just example/namedtracer/main. go show usage is not correct. That bothers me

**Comment by dmathieu** [comment]
With #5132 being merged, this issue appear to be solved.

```golang
package main

import (
	"fmt"
	"os"

	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/baggage"
)

func main() {
	fooKey := attribute.Key("ex.com/foo")
	m0, _ := baggage.NewMemberRaw(string(fooKey), "foo1")
	fmt.Fprintf(os.Stdout, "%#v", m0)
}
```

> go run main.go
baggage.Member{key:"ex.com/foo", value:"foo1", properties:baggage.properties(nil), hasData:true}%
