### ISSUE TITLE
Allow passing of logr.Logger for otlpgrpcexporter implementation

### ISSUE THREAD

**Issue by IgorEulalio** [open-telemetry/opentelemetry-go#5663]
### Problem Statement

A clear and concise description of what the problem is.
Currently the OTLP trace exporter doesn't allow the passing of a logger instance that will be used to log, instead it uses logs from standard package in some places that can't be disabled/customized:
https://github.com/open-telemetry/opentelemetry-go/blob/7dea232a465bd84ebfc835c5a639265da00984da/exporters/otlp/otlptrace/exporter.go#L38

Error above is moved until it reaches Otel.Handler and is simply printed out:
https://github.com/open-telemetry/opentelemetry-go/blob/35c957097431cf87d5257de6ae950af132f01f2b/internal/global/handler.go#L30

### Proposed Solution

Similar as we have with Zipkin exporter implementation, adding another item in the option pattern for the exporter receiving a logr.Logger would satisfy the requirement:
https://github.com/open-telemetry/opentelemetry-go/blob/7dea232a465bd84ebfc835c5a639265da00984da/exporters/zipkin/zipkin.go#L66
### Additional Context

We are implementing OTEL collector in a OSS project https://github.com/falco-talon/falco-talon/ and we need to configure OTEL to respect the same log format that we have in Talon.

**Comment by MrAlias** [comment]
Thank you for your interest in the project. Use [`SetErrorHandler`](https://pkg.go.dev/go.opentelemetry.io/otel#SetErrorHandler) if you would like to change the behavior of the default. For example:

https://github.com/open-telemetry/opentelemetry-go/blob/e2b0751cd197c2bf7406b40ba449ba227e057a50/sdk/log/batch_test.go#L57-L59

**Comment by IgorEulalio** [comment]
Thanks for the quick reply @MrAlias, much appreciated!

**Comment by dmathieu** [comment]
Does this answer your question? Can the issue be closed?

**Comment by IgorEulalio** [comment]
Yes we can, thanks @dmathieu
