### ISSUE TITLE
Audit Compliance: Logs Bridge API Logger Provider

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#5678]
1. Review the [`LoggerProvider` section of the Logs Bridge API specification](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.35.0/specification/logs/bridge-api.md#loggerprovider) for all normative statements
1. Audit the [logs bridge API package](https://pkg.go.dev/go.opentelemetry.io/otel/log) for compliance with the specified normative statements.
1. Identify existing issues or create new issues to track any work needed to make the [logs bridge API package](https://pkg.go.dev/go.opentelemetry.io/otel/log) compliant with the specification.

**Comment by dashpole** [comment]
> the API SHOULD provide a way to set/register and access a global default LoggerProvider.

https://github.com/open-telemetry/opentelemetry-go/blob/6731dc70900c4e5e47e00eb0340865189a5d1a76/log/global/log.go#L35-L44

We are compliant.

**Comment by dashpole** [comment]
> The LoggerProvider MUST provide the following functions: Get a Logger

https://github.com/open-telemetry/opentelemetry-go/blob/6731dc70900c4e5e47e00eb0340865189a5d1a76/log/provider.go#L36

We are compliant

**Comment by dashpole** [comment]
This API MUST accept the following [instrumentation scope](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.35.0/specification/logs/data-model.md#field-instrumentationscope) parameters:
* name

https://github.com/open-telemetry/opentelemetry-go/blob/6731dc70900c4e5e47e00eb0340865189a5d1a76/log/provider.go#L36

Name is a required parameter

* version (optional)

https://github.com/open-telemetry/opentelemetry-go/blob/6731dc70900c4e5e47e00eb0340865189a5d1a76/log/logger.go#L106
* schema_url (optional).
* attributes (optional) This API MUST be structured to accept a variable number of attributes, including none.

**Comment by dashpole** [comment]
> The effect of associating a Schema URL with a Logger MUST be that the telemetry emitted using the Logger will be associated with the Schema URL, provided that the emitted data format is capable of representing such association.

I'm not entirely sure what this means in the context of the API.  In the API, the schema URL can be obtained from the configuration: https://github.com/open-telemetry/opentelemetry-go/blob/6731dc70900c4e5e47e00eb0340865189a5d1a76/log/logger.go#L94.  It is up to implementations to properly associate the schemaURL of the logger with log data.

Our SDK does construct an instrumentation.Scope using the schema URL provided via API configuration: https://github.com/open-telemetry/opentelemetry-go/blob/6731dc70900c4e5e47e00eb0340865189a5d1a76/sdk/log/provider.go#L126-L130.  This scope is provided to processors with the Record on emit: https://github.com/open-telemetry/opentelemetry-go/blob/6731dc70900c4e5e47e00eb0340865189a5d1a76/sdk/log/logger.go#L87


We are compliant.

**Comment by dashpole** [comment]
@MrAlias @pellared I believe we are fully compliant with this part of the specification.  Feel free to double-check, and then close.
