### ISSUE TITLE
Audit Compliance: Logs Bridge API Concurrency Requirements

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#5680]
1. Review the [`Concurrency requirements` section of the Logs Bridge API specification](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.35.0/specification/logs/bridge-api.md#concurrency-requirements) for all normative statements
1. Audit the [logs bridge API package](https://pkg.go.dev/go.opentelemetry.io/otel/log) for compliance with the specified normative statements.
1. Identify existing issues or create new issues to track any work needed to make the [logs bridge API package](https://pkg.go.dev/go.opentelemetry.io/otel/log) compliant with the specification.

**Comment by XSAM** [comment]
Normative statements:
- LoggerProvider - all methods are safe to be called concurrently.
- Logger - all methods are safe to be called concurrently.

**Comment by XSAM** [comment]
@open-telemetry/go-maintainers I believe we comply with this part of the specification. Feel free to double-check and close this issue.
