### ISSUE TITLE
Audit Compliance: Logs Bridge API Artifact Naming

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#5681]
1. Review the [`Artifact Naming` section of the Logs Bridge API specification](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.35.0/specification/logs/bridge-api.md#artifact-naming) for all normative statements
1. Audit the [logs bridge API package](https://pkg.go.dev/go.opentelemetry.io/otel/log) for compliance with the specified normative statements.
1. Identify existing issues or create new issues to track any work needed to make the [logs bridge API package](https://pkg.go.dev/go.opentelemetry.io/otel/log) compliant with the specification.

**Comment by dashpole** [comment]
> The Logs Bridge API ... SHOULD include documentation that discourages direct use.

Our current statement is "It is not designed to be a logging API itself.", which I think could be a bit unclear for users.  As a uninitiated users, i'm not sure what it would mean for a package providing logging-related interfaces to not be an API...

> Log Bridge API artifact, package, and class names MUST NOT include the terms "bridge", "appender", or any other qualifier that would prevent evolution into a user facing API.

Our implementation is compliant with this requirement.
