### ISSUE TITLE
SetAttributes/AddAttributes truncate strings down to 0-length

### ISSUE THREAD

**Issue by gquintard** [open-telemetry/opentelemetry-go#5691]
### Description

`otel/sdk/log.SetAttributes` and `otel/sdk/log.AddAttributes` (what's the difference between the two, by the way?) are essentially useless when give a string because `Record.attributeValueLengthLimit` default to 0 and isn't public. So all strings used as attributes are truncated down to the empty string.

### Environment

- OS: BTW I use Arch
- Architecture: linux/amd64
- Go Version: 1.22.3
- opentelemetry-go version: https://pkg.go.dev/go.opentelemetry.io/otel/sdk/log@v0.4.0

### Steps To Reproduce

```
         record := sdklog.Record{}
          record.SetAttributes(apilog.String("foo", "bar")) 
          record.WalkAttributes( func(kv apilog.KeyValue) bool { 
                          fmt.Printf("%+v: %+v\n",kv.Key, kv.Value) 
                          return true
                  })
```

You'll see a sad `foo: ` with no `bar` in sight

### Expected behavior

Having a sensible default for the string limit and/or a way to set it would be nice

**Comment by pellared** [comment]
You are not supposed to create `sdklog.Record{}` by yourself. Why would you do it?

**Comment by gquintard** [comment]
ah, might be pebcak then. In short, I didn't see anything to create them in https://pkg.go.dev/go.opentelemetry.io/otel/sdk/log@v0.4.0

The long version is that I'm writing an exporter for `varnish` logs, meaning I ingest logs from `stdin` (or from a file) and push them to `otel`, so the `Logger` seemed overkill and just creating a `Record` to feed to the `Exporter` seemed a lot simpler?

**Comment by pellared** [comment]
> The long version is that I'm writing an exporter for `varnish` logs, meaning I ingest logs from `stdin` (or from a file) and push them to `otel`

You should supposed to create a "log bridge" that uses https://pkg.go.dev/go.opentelemetry.io/otel/log to push logs to `otel`. You can take a look at e.g. [otellogrus](https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/bridges/otellogrus) for reference.

Related issue: https://github.com/open-telemetry/opentelemetry-go-contrib/issues/5947

**Comment by pavel-raykov** [comment]
Sorry, there is another case where a separate  could be useful:

By default, the logs are emitted with the Emit method which does not return any status, i.e., the caller does not have any feedback on whether the log has been delivered or not. There is alternative method https://pkg.go.dev/go.opentelemetry.io/otel/exporters/otlp/otlplog/otlploghttp#Exporter.Export which actually takes sdklog.Record as input, so it would be useful if it were possible to construct sdklog.Record with custom attributeValueLengthLimit and pass it to the Export function.

Could you please comment if this makes sense?
