### ISSUE TITLE
Otlp: `too many colons in address` when export env: `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT`

### ISSUE THREAD

**Issue by afifurrohman-id** [open-telemetry/opentelemetry-go#5706]
### Environment

- OS: `Linux 👍 #23~22.04.1-Ubuntu SMP Thu May  9 17:59:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`
- Architecture: `x86_64`
- Go Version: `go version go1.22.3 linux/amd64`
- opentelemetry-go version: `v1.28.0`

### Steps To Reproduce
- export trace endpoint env
```sh
export OTEL_EXPORTER_OTLP_TRACES_ENDPOINT='http://127.0.0.1:4317'
```

- Create init trace fn
```go
func NewOtlpTracerProvider(svcName string, ctx context.Context, otlpEndpoint string) (*sdktrace.TracerProvider, error) {
	exporter, err := otlptrace.New(
		ctx,
		otlptracegrpc.NewClient(otlptracegrpc.WithInsecure(), otlptracegrpc.WithEndpoint(otlpEndpoint)),
		// otlptracehttp.NewClient(otlptracehttp.WithInsecure(), otlptracehttp.WithEndpoint(otlpEndpoint)),
	)

	if err != nil {
		return nil, fmt.Errorf("unable to initialize exporter due: %w", err)
	}

	tp := sdktrace.NewTracerProvider(
		sdktrace.WithSampler(sdktrace.AlwaysSample()),
		sdktrace.WithBatcher(exporter),
		sdktrace.WithResource(resource.NewWithAttributes(
			semconv.SchemaURL,
			semconv.ServiceNameKey.String(svcName),
		)),
	)

	otel.SetTracerProvider(tp)
	otel.SetTextMapPropagator(propagation.NewCompositeTextMapPropagator(propagation.TraceContext{}, propagation.Baggage{}))
	return tp, nil
}
```
- Call trace init fn in main and add trace
```go
func main() {
    ctx := context.Background()
     tp, _ = NewOtlpTracerProvider("foo", ctx,"http://127.0.0.1:4317") 
    defer tp.Shutdown(ctx)

    tracer := tp.Tracer("test")

    _, span := tracer.Start(ctx, thisFnName)
    defer span.End()

}
```

- You got log:
```
traces export: failed to exit idle mode: invalid target address http://127.0.0.1:4317, error info: address http://127.0.0.1:4317:443: too many colons in address
```

### Expected behavior

Should work! and not append `:443` at end of endpoint

**Comment by amanakin** [comment]
I suppose when you call NewOtlpTracerProvider, you should provide a domain name or IP address, instead of URL (remove _http://_).

**Comment by MrAlias** [comment]
> ```go
> 		otlptracegrpc.NewClient(otlptracegrpc.WithInsecure(), otlptracegrpc.WithEndpoint
> ```

:point_up: 

> WithEndpoint sets the target endpoint (host and port) the Exporter will connect to. The provided endpoint should resemble "example.com:4317" (no scheme or path).

https://pkg.go.dev/go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc#WithEndpoint

**Comment by afifurrohman-id** [comment]
> > I suppose when you call NewOtlpTracerProvider, you should provide a domain name or IP address, instead of URL (remove http://).
> 
> ☝️
> 
> > WithEndpoint sets the target endpoint (host and port) the Exporter will connect to. The provided endpoint should resemble "example.com:4317" (no scheme or path).
> 
> https://pkg.go.dev/go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc#WithEndpoint

Okay, i still have confusion here.

Does it means wen we set env should prefix with `http://` or `https://` ?
But if we pass parameter should ip or domain `example.com` `192.168.10.1` ?

**Comment by MrAlias** [comment]
> Does it means wen we set env should prefix with `http://` or `https://` ?
> But if we pass parameter should ip or domain `example.com` `192.168.10.1` ?
> And if we set both env and parameter to that fn, otel package should use the parameter instead env?

If I understand these questions correctly, the answer is yes to all of them.

**Comment by HartBlanc** [comment]
Why are they different? This is very confusing
If you provide both it also produces noisy logs saying that the URL can't be parsed.
