### ISSUE TITLE
[new feature] metrics: support prometheus remote write exporter.

### ISSUE THREAD

**Issue by liguozhong** [open-telemetry/opentelemetry-go#5707]
### Problem Statement

We have some agent-type applications deployed in a large number of ecs linux and k8s. We use otel for metrics monitoring and hope to push them directly to prometheus for agent observability.

We often change the cloud provider of Hosted Prometheus, but currently not all Chinese cloud providers host OTLP Collector, but Chinese Prometheus providers all host Prometheus's remote write protocol.

### Proposed Solution
implemented prometheus remote write exporter . 
![image](https://github.com/user-attachments/assets/19320d09-7b58-4926-bbb5-ab02a8c9d191)
```go
        import  "go.opentelemetry.io/oetl-metrics-exporter-remotewrite-go/exporter/remotewrite"

	exp, err := remotewrite.NewExporter(remotewriteUrl, username, password)

	meterProvider := metric.NewMeterProvider(
		metric.WithReader(
			metric.NewPeriodicReader(
				exp,
				metric.WithTimeout(time.Second*30),
				metric.WithInterval(time.Second*5),
			)),
		metric.WithResource(res),
	)
	otel.SetMeterProvider(meterProvider)
```

#### Alternatives
In the early versions of otel, we used the exporter written by cortex, but this is no longer available in the latest version of otel. However, we strongly need this feature, so we also implemented a new prometheus remote write exporter. 

cortex  remote write exporter. 
[A clear and concise description of what you want to happen.
](https://pkg.go.dev/go.opentelemetry.io/contrib/exporters/metric/cortex#section-readme)
⚠️ This project is deprecated. Use the go.opentelemetry.io/otel/exporters/otlp/otlpmetric exporter as a replacement to send data to a collector which can then export with its PRW exporter.

### Additional Context
We have implemented a new prometheus remote write exporter. We hope to host it in otel's github repository like cortex's implementation. If the community accepts it. Which project should this plugin be written in?

**Comment by dmathieu** [comment]
The latest versions of Prometheus can ingest data from OTLP.
See https://prometheus.io/blog/2024/03/14/commitment-to-opentelemetry/

Using that would be easier and more generic than setting up a protocol specific to prometheus.

**Comment by liguozhong** [comment]
The OTLP collector component will distract our SRE team, it is complex and consumes machine resources. 
![image](https://github.com/user-attachments/assets/1d9c234b-1832-49da-ae8d-211f5e36ae3f)

![image](https://github.com/user-attachments/assets/98cf0daf-cf11-4def-acd5-77c522788df0)

We are looking for an APM hosted prometheus provider like Datadog to host the observability infrastructure, as shown below. 
![image](https://github.com/user-attachments/assets/5642dc4a-94d4-428a-8a72-3a79994c2b60)

However, most of the current APM vendors only provide the Prometheus remote write protocol, which makes it difficult to upgrade from the Prometheus client instrument to the Otel instrument.

**Comment by dmathieu** [comment]
Note that the exporter interface is public, so anybody can write their own exporter.
It seems unlikely we will write a prometheus push exporter. Nothing prevents you from doing so, and using that within your repositories though.

**Comment by liguozhong** [comment]
Thanks for your reply. Our team will be responsible for maintaining this otel prometheus remote write exporter .
