### ISSUE TITLE
Consider TraceId/SpanId to implement Stringer interface?

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-go#577]
Currently we use `SpanIdString()` https://github.com/open-telemetry/opentelemetry-go/blob/master/api/core/span_context.go#L174, but if we rename that to just `String` fmt will print that nicer :)

**Comment by rghetia** [comment]
Make sure that structure for print is inline with logging efforts.

**Comment by MrAlias** [comment]
From our SIG meeting: the ask is to possibly add a separate method `String` instead of replacing this method. The point being that this method might produce the string in a protocol format.

Ideally the `String` method will conform to the function @rghetia describes.

**Comment by Oncilla** [comment]
@rghetia can you point me to what the logging efforts are?

**Comment by rghetia** [comment]
> @rghetia can you point me to what the logging efforts are?

Log SIG recently started and is looking into supporting logs in OpenTelemetry. This [doc](https://docs.google.com/document/d/1cX5fWXyWqVVzYHSFUymYUfWxUK5hT97gc23w595LmdM/edit#heading=h.lro8kgalys10) has some relevant links.

**Comment by shouri007** [comment]
@MrAlias I'd like to take this up.

**Comment by MrAlias** [comment]
All yours @shouri007 :smile:

**Comment by shouri007** [comment]
@MrAlias Can we close this issue as it's resolved now?
