### ISSUE TITLE
Make LogRecord immutable, simplifies concurrency

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-go#5779]
### Problem Statement

I would propose to separate LogRecord struct into mutable vs immutable and pass immutable to Emit to avoid having to deal with concurrency issues.

### Proposed Solution

We can achieve this without any heap allocations (interfaces) by having something like:

```golang
type LogRecord struct {
  timestamp time.Time
}

func (lr LogRecord) getTimestamp() time.Time {
  return lr.timestamp
}

func (lr LogRecord) toMutable() MutableLogRecord {
  // Here we can to a clone of the non immutable fields.
}

type MutableLogRecord struct {
  LogRecord
}

func (mlr MutableLogRecord) setTimestamp(t time.Time) {
  mlr.timestamp = t
}

func (mlr MutableLogRecord) asImmutable(t time.Time) LogRecord {
  return mlr.LogRecord
}

```

**Comment by MrAlias** [comment]
The specification has explicitly stated that the records passed to `Emit` need to be mutable so the following processors will see all changes made to them:

- https://github.com/open-telemetry/opentelemetry-specification/pull/4067
- https://github.com/open-telemetry/opentelemetry-specification/issues/4010

We originally designed the SDK the way you propose, however, it was not compliant with the specification and there was no desire at the specification level to support the change to make it allowed.

**Comment by Ali-Alnosairi** [comment]
@pellared ,
Does this issue needs to make changes to the specification  to support immutable?

**Comment by pellared** [comment]
@Ali-Alnosairi, as noted before

> We originally designed the SDK the way you propose, however, it was not compliant with the specification and there was no desire at the specification level to support the change to make it allowed.

Yes. However, the proposal was already rejected after a few months of discussions. You can read the Specification SIG meeting notes, watch the recording, check the issues and PRs.
