### ISSUE TITLE
go: download go1.22 for darwin/arm64: toolchain not available

### ISSUE THREAD

**Issue by zhihali** [open-telemetry/opentelemetry-go#5786]
### Description

This are all happened under exporters/otlp folder, but I believe in other folder I will face the same issue.
When I try to develop the code and fix a bug. and run `go mod tidy`or `go version` , `go test`. I will get this output

```
go: downloading go1.22 (darwin/arm64)
go: download go1.22 for darwin/arm64: toolchain not available
```
in go.mod, I can see 
https://github.com/open-telemetry/opentelemetry-go/blob/8d7dfcdc68431d956bb822c7af18e0db6a9cd72b/exporters/otlp/otlplog/otlploggrpc/go.mod#L3

from this issue https://github.com/golang/go/issues/65568, I can know the solution is change 1.22 to 1.22.0
so if I change this line to
```
go 1.22.0
```
problem will be solved.

So I'm just wondering, is this only happen on my laptop? Shall we update 1.22 to 1.22.0?
I'm confused because previously I run the go mod tidy or develop something, everything works well, but just after 2 weeks I restarted my work and find this error.

### Environment

- OS: Macbook 
- Architecture: apple M2 pro
- Go Version: 1.22.0
- opentelemetry-go version: newest

### Steps To Reproduce

```
go mod tidy
```

### Expected behavior

```
go: downloading go1.22.0 (darwin/arm64)
go: downloading google.golang.org/grpc v1.66.0
go: downloading google.golang.org/genproto/googleapis/rpc v0.0.0-20240903143218-8af14fe29dc1
go: downloading golang.org/x/sys v0.25.0
go: downloading gopkg.in/check.v1 v1.0.0-20201130134442-10cb98267c6c
go: downloading google.golang.org/genproto/googleapis/api v0.0.0-20240903143218-8af14fe29dc1
go: downloading github.com/kr/pretty v0.3.1
go: downloading github.com/kr/text v0.2.0
go: downloading github.com/rogpeppe/go-internal v1.12.0
go: downloading golang.org/x/text v0.18.0
```

**Comment by pellared** [comment]
I see it more like a bug of how `go` behaves. Maybe one is already reported?

See: https://github.com/golang/go/issues/68971#issuecomment-2299062164

What is your currently installed Go version? Are you sure that it is Go 1.20?

**Comment by zhihali** [comment]
yeah, I'm sure I'm using 1.20, so basically I can just temporarily change go 1.20 to go 1.20.0 then do the dev work, but when I run pre commit, it still will raise this problem, quite annoying
