### ISSUE TITLE
Move examples to contrib

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go#5801]
~~A follow-up after https://github.com/open-telemetry/opentelemetry-go/pull/5791 in contrib is required and afterwards here we need to fix the `example/dice`.~~

- [x] Copy all example(s) to contrib
   - We should not version the copied examples. They can just be git hash referenced.
   - https://github.com/open-telemetry/opentelemetry-go-contrib/pull/6158
   - https://github.com/open-telemetry/opentelemetry-go-contrib/pull/6160
- [x] Revert `example/dice` changes from https://github.com/open-telemetry/opentelemetry-go/pull/5791 so that it uses `otelslog`.
   - https://github.com/open-telemetry/opentelemetry-go-contrib/pull/6162 
- [x] Deprecate the examples in core repo
   - https://github.com/open-telemetry/opentelemetry-go/pull/5854
- [x] RELEASE
   - https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.31.0
- [x] Remove the examples from core repo
   - https://github.com/open-telemetry/opentelemetry-go/pull/5930

**Comment by MrAlias** [comment]
This round-about dependency seems like something we should address. Should this example be moved to contrib? Should all examples?

**Comment by pellared** [comment]
> This round-about dependency seems like something we should address. Should this example be moved to contrib? 

It makes sense also because this example also uses `go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp`

> Should all examples?

It may be indeed easier to keep all examples in contrib.

**Comment by dashpole** [comment]
I'm OK with moving examples to contrib
