### ISSUE TITLE
Document how files are generated and maybe automate it

### ISSUE THREAD

**Issue by krnowak** [open-telemetry/opentelemetry-go#583]
We have some generated files in the repo. Some of them are generated during `make precommit` (like `api/core/numberkind_string.go` by the stringer utility). But some of them were generated just once and just lay there:

- example/grpc/api/hello-service.pb.go
  - documented in example/grpc/README.md, seems to work, but I had to build `protoc-gen-go` first myself.
- exporters/trace/jaeger/internal/gen-go/*
  - not documented

Would be nice to document it and add some `make` target (like `make generate-misc`) so it regenerates the files above. It's something maybe we could do as a part of a release process.

**Comment by ilyakaznacheev** [comment]
What about proto generation? How do you fix all the versions of protoc and plugins?

**Comment by MadVikingGod** [comment]
The current state of affairs is:
* There are a number of stringers run by `make precommit`
* Semconv is made via the semconv tool, and is documented int the RELEASING.md
* The only outstanding one is the thrift code in jaeger.  I couldn't find the history of how we adopted this code.

**Comment by MrAlias** [comment]
> * The only outstanding one is the thrift code in jaeger.  I couldn't find the history of how we adopted this code.

IIRC, that was a manual copy paste.

**Comment by pellared** [comment]
AFAIK all code generation is now automated.
