### ISSUE TITLE
Add a script that bumps the version deps in go.mod files

### ISSUE THREAD

**Issue by krnowak** [open-telemetry/opentelemetry-go#584]
Would be nice if we could automatically update the direct dependencies in all go.mod files. I imagine it as:

- `bump-deps.sh` to find all the direct deps in all go.mod files and bump them to the latest release
- `bump-deps.sh google.golang.org/grpc` to bump the grpc dependency in all go.mod files to its latest release
- `bump-deps.sh google.golang.org/grpc:v1.28` to bump the grpc dependency in all go.mod files to the specified version

Maybe `make bump-deps` would run the first variant.

**Comment by MrAlias** [comment]
I think [the `pre_release.sh` script](https://github.com/open-telemetry/opentelemetry-go/blob/c85f46389fc89e0c92a4b1a1e0174045ce955ddb/pre_release.sh) accomplishes this. Albeit with a different call pattern, but I think it's good enough to close this.
