### ISSUE TITLE
Multiple periodic readers increment the counter abnormaly

### ISSUE THREAD

**Issue by dashpole** [open-telemetry/opentelemetry-go#5866]
### Description

When multiple (periodic) readers are present, metrics increase abnormally.

Originally reported here: https://github.com/open-telemetry/opentelemetry-collector/issues/11327

### Steps To Reproduce

Run the OpenTelemetry collector with the configuration provided in the bug above.

### Expected behavior

Metrics should not increase abnormally.

**Comment by dashpole** [comment]
We should try to create a simpler reproduction (not using the collector) to make this easier to root-cause

**Comment by pree-dew** [comment]
@dashpole Can I pick this task?

**Comment by dashpole** [comment]
@pree-dew feel free to work on this.  It is likely going to be tricky to root-cause, but any help is appreciated

**Comment by pree-dew** [comment]
Able to reproduce the issue by providing multiple periodic reader in telemetry

![Screenshot 2024-10-04 at 2 37 07 PM](https://github.com/user-attachments/assets/4b9b8a40-8d64-4149-9830-56c0257bcd64)

Will try to find a way to reproduce outside of otel-collector

**Comment by pree-dew** [comment]
Able to reproduce this with sdk

```
========== Reader1=================
{
        "Resource": [
                {
                        "Key": "service.name",
                        "Value": {
                                "Type": "STRING",
                                "Value": "myapp"
                        }
                }
        ],
        "ScopeMetrics": [
                {
                        "Scope": {
                                "Name": "http",
                                "Version": "",
                                "SchemaURL": ""
                        },
                        "Metrics": [
                                {
                                        "Name": "http_requests_total",
                                        "Description": "TODO",
                                        "Unit": "count",
                                        "Data": {
                                                "DataPoints": [
                                                        {
                                                                "Attributes": [],
                                                                "StartTime": "2024-10-07T16:10:11.277202+05:30",
                                                                "Time": "2024-10-07T16:19:41.280994+05:30",
                                                                "Value": 4
                                                        }
                                                ],
                                                "Temporality": "CumulativeTemporality",
                                                "IsMonotonic": true
                                        }
                                }
                        ]
                }
        ]
}
======= Reader 2 ===================
{
	"Resource": [
		{
			"Key": "service.name",
			"Value": {
				"Type": "STRING",
				"Value": "myapp"
			}
		}
	],
	"ScopeMetrics": [
		{
			"Scope": {
				"Name": "http",
				"Version": "",
				"SchemaURL": ""
			},
			"Metrics": [
				{
					"Name": "http_requests_total",
					"Description": "TODO",
					"Unit": "count",
					"Data": {
						"DataPoints": [
							{
								"Attributes": [],
								"StartTime": "2024-10-07T16:10:11.277205+05:30",
								"Time": "2024-10-07T16:19:41.281038+05:30",
								"Value": 12
							}
						],
						"Temporality": "CumulativeTemporality",
						"IsMonotonic": true
					}
				}
			]
		}
	]
}

```

Same time, same metric is showing values as 4, 12 while the correct value is 3.

So far the observation is that it is happening with `ObservableCounter` but will give it one more shot to be sure.

**Comment by pree-dew** [comment]
@dashpole I have added a test case to reproduce the behaviour. 

Debugged the issue, this is my understanding of the issue:

**Step 1** 
Say the value of the metric is 1:

**Step2**
Pipeline 1 starts-> calls the registered callback -> calls the measure function -> sets the value to `1` as the previous value initially is 0 [ref](https://github.com/open-telemetry/opentelemetry-go/blob/2578accaa8484f942f457462e24fedffe1ad6acc/sdk/metric/internal/aggregate/sum.go#L37)

**Step3**
Pipeline 2 starts -> calls the registered callback -> calls the measure function -> picks the value set by pipeline1 as `1` and then add the value to it, making it `2`

**Step4**
When the method **.Collect** will be called instead of value `1`, it will get `2`, Since it is PreComputedSum, expected value is `1` **not 2 [Bug!!!]**

This is happening as the instrument is same for both pipelines and before the previous value gets cleared [here](https://github.com/open-telemetry/opentelemetry-go/blob/2578accaa8484f942f457462e24fedffe1ad6acc/sdk/metric/internal/aggregate/sum.go#L231), next pipeline picks the previous value set by pipeline1 and add the value, thereby making the value **incorrect**.

With above understanding, I have able to reproduce the issue.

**Let me know what do you think about this?**

**Comment by dashpole** [comment]
I believe the issue is that somehow pipelines are not properly isolated.  They should not be sharing the aggregation, but seem to be? A meter has a single resolver for int64:

https://github.com/open-telemetry/opentelemetry-go/blob/1a964cc449d302a787c2a80a02a3731af12ab981/sdk/metric/meter.go#L59

The resolver has a list of pipelines: https://github.com/open-telemetry/opentelemetry-go/blob/1a964cc449d302a787c2a80a02a3731af12ab981/sdk/metric/pipeline.go#L600-L604

There is one pipeline for each reader: https://github.com/open-telemetry/opentelemetry-go/blob/1a964cc449d302a787c2a80a02a3731af12ab981/sdk/metric/pipeline.go#L562-L569

The callback is registered separately with each pipeline: https://github.com/open-telemetry/opentelemetry-go/blob/1a964cc449d302a787c2a80a02a3731af12ab981/sdk/metric/pipeline.go#L572-L577

During Collect, produce() should iterate over each callback on the pipeline: https://github.com/open-telemetry/opentelemetry-go/blob/1a964cc449d302a787c2a80a02a3731af12ab981/sdk/metric/pipeline.go#L123-L128

Some things to check:

* Are aggregations being shared between readers when they shouldn't be?
* Are callbacks being registered multiple times with the same reader?
* Is Collect() for one reader invoking callbacks on other readers?

**Comment by pree-dew** [comment]
@dashpole Sure, I will check these points. So far I have observed is that the instance(`in`) returned at this line https://github.com/open-telemetry/opentelemetry-go/blob/1a964cc449d302a787c2a80a02a3731af12ab981/sdk/metric/pipeline.go#L368
 
 is same for both readers, even when there are 2 separate pipelines which internally is calling the measure function for both pipelines.

**Comment by dashpole** [comment]
Added some printing in the sum aggregation:

```
measure s: 0xc0000aa740, v.n += value: 0 += 1
measure s: 0xc0000aa760, v.n += value: 0 += 1
cumulative s: 0xc0000cb830, i: 1/1, val: 1
measure s: 0xc0000aa740, v.n += value: 0 += 1
measure s: 0xc0000aa760, v.n += value: 1 += 1
cumulative s: 0xc0000cb8f0, i: 1/1, val: 2
--- FAIL: TestPipelineWithMultipleReaders (0.00s)
```

measure is being called for both pipelines when only one pipeline is collected.

**Comment by dashpole** [comment]
I did some more digging.  The issue is that the Instrument we return to users from `Int64ObservableCounter` contains the measure functions for that instrument from all pipelines (readers).  Here, we get the measure function, `in`, for each inserter (which is 1:1 with a reader), and call instrument.appendMeasures on each `measure` function: https://github.com/open-telemetry/opentelemetry-go/blob/97f8401153a431c5c91b93741f394d932d2b1a03/sdk/metric/meter.go#L139-L160

Then, each time ObserveInt64 is called from our callback, it calls observe on the instrument provided by the user (which is our `Int64ObservableCounter`: https://github.com/open-telemetry/opentelemetry-go/blob/97f8401153a431c5c91b93741f394d932d2b1a03/sdk/metric/meter.go#L558

Observe iterates over all of the measure functions: https://github.com/open-telemetry/opentelemetry-go/blob/97f8401153a431c5c91b93741f394d932d2b1a03/sdk/metric/instrument.go#L328-L330

**Comment by dashpole** [comment]
I actually fixed a very similar bug if callbacks were registered using WithCallback() in https://github.com/open-telemetry/opentelemetry-go/pull/4742

**Comment by pree-dew** [comment]
This issue https://github.com/open-telemetry/opentelemetry-go/pull/4742 looks similar. So, since we are appending measure function for all pipelines, it is getting called even if 1 pipeline collect is getting called. 

So, we essentially have to append the measure function corresponding to the pipeline's reader as a solution. Is my understanding correct?

**Comment by dashpole** [comment]
To fix it, we need to ensure that only callbacks associated with the pipeline are called during the pipeline's Collect() function.  In https://github.com/open-telemetry/opentelemetry-go/pull/4742 this was done by passing an instrument to the callback that contained only the measure functions for that pipeline: https://github.com/open-telemetry/opentelemetry-go/pull/4742/files#diff-e6ec718e2bb8f9b29cbab6b14b62ddae15faa6192d82b927b0e7b7f1b4167cc7R124

But here, the instrument comes from the user and must be useable for callbacks for any pipeline, so we can't do that.

The only other option, which is accessible from `ObserveInt64` is to have a different `observer` for each pipeline, which is currently created here: https://github.com/open-telemetry/opentelemetry-go/blob/97f8401153a431c5c91b93741f394d932d2b1a03/sdk/metric/meter.go#L444

We might need to split the observer so that we can validate instruments once without using an observer, and then create an observer for each pipeline.

The observer will need to be able to look up the `measure` function for a given instrument (probably by `observableID`).  That map[observableID]aggregate.Measure probably needs to be stored on the `pipeline`, and recorded here: https://github.com/open-telemetry/opentelemetry-go/blob/97f8401153a431c5c91b93741f394d932d2b1a03/sdk/metric/meter.go#L152

And the observer needs to keep a reference to the pipeline.

**Comment by dashpole** [comment]
It is probably easiest if observer has a reference to its pipeline, and the map[observableID]measure is on the pipeline.

We probably need to leave appendMeasure alone for now, since the measures on the instrument is used for validation.  But right next to where we call appendMeasure, you should update the map[observableID]measure on the pipeline.

During `ObserveInt64`, we need to stop calling observe() on the observer provided by the user.  Instead, we need to look up the measure function that we stored on the pipeline, and use that.

**Comment by pree-dew** [comment]
Got it and makes sense. I will make changes accordingly.

**Comment by pree-dew** [comment]
@dashpole I have taken first attempt at making changes and pushed the code. Let me know your review on that, happy to accomodate feedback.
