### ISSUE TITLE
trace.WithAttributes does not satisfy SpanEndOption

### ISSUE THREAD

**Issue by petenewcomb** [open-telemetry/opentelemetry-go#5921]
### Description

The documentation of [`trace.WithAttributes`](https://github.com/open-telemetry/opentelemetry-go/blob/bc2fe88756962b76eb43ea2fd92ed3f5b6491cc0/trace/config.go#L214-L225) states:

> These attributes are used to describe the work a Span represents when this option is provided to a Span's start or end events.

However, it returns a `SpanStartEventOption` instead of a `SpanEventOption` and `SpanStartEventOption` satisfies only `SpanStartOption` and `EventOption`, not `SpanEndOption`.

Either the code or the documentation is incorrect.  I expect that it's the code that's incorrect, because it's often the case that useful span attribute values are not known before a span's operation has started.  This can still be done using `Span.SetAttributes`, but the text for `trace.WithAttributes` quoted above implies that the option it produces can be passed to `Span.End`.  The wording is also a bit confusing because it refers to what must be calls to `Tracer.Start` and `Span.End` as "events", using that word in a different sense than the "span events" for which this function can be used to supply attributes.

### Environment

- OS: N/A
- Architecture: N/A
- Go Version: N/A
- opentelemetry-go version: 1.31

### Steps To Reproduce

```go
func foo(ctx context.Context, tracer trace.Tracer) {
	ctx, span := tracer.Start(ctx, "myop")
	span.End(trace.WithAttributes())
}
```

> ./prog.go:13:11: cannot use trace.WithAttributes() (value of type trace.SpanStartEventOption) as trace.SpanEndOption value in argument to span.End: trace.SpanStartEventOption does not implement trace.SpanEndOption (missing method applySpanEnd)

(Complete example at https://go.dev/play/p/QpkKDVYmnxp)

### Expected behavior

The above code should compile cleanly and behave as already described, or the documentation for `trace.WithAttributes` should not imply that it can be used with `Span.End`.  In the former case, it would also be good to include text that follows the [instructions in the specification](https://opentelemetry.io/docs/specs/otel/trace/api/#span):

> The API documentation MUST state that adding attributes at span creation is preferred to calling `SetAttribute` later, as samplers can only consider information already present during span creation.

**Comment by dmathieu** [comment]
The specification only allows setting the end timestamp, not attributes when calling `End()`.
So this rather looks like a documentation issue.

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#end

**Comment by petenewcomb** [comment]
My read of the specification was that one can set the end timestamp when calling `End`, not that it allows only the timestamp to be set at `End`.  If one takes the narrower view, then at least on the surface, the Go implementation should not also allow [`WithStackTrace`](https://pkg.go.dev/go.opentelemetry.io/otel/trace#WithStackTrace) to be passed to `End`, instead forcing it to be used only with `Span.AddEvent` or `Span.RecordError`.

Digging in a bit further, I can see that the reason that `WithStackTrace` is accepted by `Span.End` is to [enable or disable capturing a stack trace from a panic](https://github.com/open-telemetry/opentelemetry-go/blob/664a075380b9eb155512adb1213ca688bd1ed611/sdk/trace/span.go#L420-L437).  This behavior is not called out by the documentation, and it's also surprising to me that passing `WithStackTrace(true)` to `Span.End` will record a stack trace only if the goroutine is currently panicking -- and assuming, of course, that it was called from `defer`.  Usage of `defer` is suggested by the examples, but like panicking to begin with, it is never noted as being required for this functionality.

Also surprising is that [passing `WithStackTrace` to `Span.AddEvent` is a no-op](https://github.com/open-telemetry/opentelemetry-go/blob/664a075380b9eb155512adb1213ca688bd1ed611/sdk/trace/span.go#L519-L554).  Perhaps there should be an "ErrorOption" interface that `WithStackTrace` returns, that is accepted only by `RecordError` and `End`?  Or, to avoid breaking the existing API, `Span.AddEvent` could simply add a stack trace based on the `WithStackTrace` flag as would be expected, re-using the capturing and recording mechanisms employed by `Span.RecordError` and `Span.End`.

With the possible exception of the issues around `AddEvent`, I'm fine with just fixing the documentation.  I acknowledge that the API as it stands appears to be close to minimal in the sense that once a span has been created, one must use the methods on the created span to do anything other than setting the end timestamp or trigger the panic-related functionality.

Once there's alignment on a general path forward I'll be happy to take a stab at implementing any changes (likely mostly documentation) and raise a PR for further review.

**Comment by dmathieu** [comment]
I don't know whether we should allow setting attributes while we call `End`. Setting attributes isn't really related to finishing a span.

Setting the end timestamp is related to finishing the span, since that value is set during that call.
I agree that the stacktrace option is a grey area.

It looks to me like the specification needs to be clarified before we make changes to the API.

**Comment by MrAlias** [comment]
```go
span.SetAttributes(/*...*/)
span.End()
```

This is how you set attributes at span end.

**Comment by petenewcomb** [comment]
Agreed, and as I stated above I'm fine with that.  Mostly I'm trying to make sure the community of developers I support are able to understand and use this API correctly and effectively, hence the desire to make the documentation unambiguous and consistent with the code.  If you feel the specification should also be more explicit in this area, I'm happy to help with that too.

Meanwhile, making the documentation for the existing API and its behavior more complete and correct seems like an orthogonal issue to improving the specification.  If the specification ends up changing such that it requires modifications to the API, that should be taken on separately.

BTW, the documentation for the _implementation_ of `Span.End` [does mention the panic behavior](https://github.com/open-telemetry/opentelemetry-go/blob/664a075380b9eb155512adb1213ca688bd1ed611/sdk/trace/span.go#L396-L400):

```go
// The only SpanOption currently supported is WithTimestamp which will set the
// end time for a Span's life-cycle.
//
// If this method is called while panicking an error event is added to the
// Span before ending it and the panic is continued.
```

This of course doesn't get propagated to the [published documentation](https://pkg.go.dev/go.opentelemetry.io/otel/trace). 
 It also doesn't mention `WithStackTrace`, does not call out the requirement to use `defer`, and should reference `SpanEndOption` rather than `SpanOption`.

**Comment by dmathieu** [comment]
> BTW, the documentation for the implementation of Span.End [does mention the panic behavior](https://github.com/open-telemetry/opentelemetry-go/blob/664a075380b9eb155512adb1213ca688bd1ed611/sdk/trace/span.go#L396-L400):
> [...]
> This of course doesn't get propagated to the [published documentation](https://pkg.go.dev/go.opentelemetry.io/otel/trace).

This is because you're looking at two different documentations. The SDK (the first link) is the implementation, while the API (the second link) is the interfaces.
While we provide an official SDK, anybody could make their own implementation. The options you mention are only part of our own SDK, not the API.

Our SDK does defer handling, but that behavior is not required by the specification, so other SDKs could do things differently.

The fact that the `End()` method is not documented in `pkg.go.dev` is problematic, I agree. That's because the struct is private. There isn't much we can do about that though.

> should reference SpanEndOption rather than SpanOption.

This is probably an oversight. I've opened https://github.com/open-telemetry/opentelemetry-go/pull/6006

**Comment by petenewcomb** [comment]
OK, I understand the intent for the panic behavior to be an SDK-specific detail, but it does leak into the API as [`WithStackTrace`](https://pkg.go.dev/go.opentelemetry.io/otel/trace#WithStackTrace), which would be a good place to add the documentation about the need to use `defer`.

Also related is what I mentioned earlier about `WithStackTrace` not being implemented by SDK's `AddEvent`.  (See [stackTraceOption.applyEvent](https://github.com/open-telemetry/opentelemetry-go/blob/652588ddd9f5bc7eaa15ace2b03b393bd8d039c1/trace/config.go#L256-L259) and then [recordingSpan.AddEvent](https://github.com/open-telemetry/opentelemetry-go/blob/664a075380b9eb155512adb1213ca688bd1ed611/sdk/trace/span.go#L519-L554) which never uses the flag nor records a stack trace.)

I realize that these concerns are not directly related to the original topic of this issue, and would be happy to follow up with a new issue focused on `WithStackTrace`.

As for the original topic, the only remaining discrepancy is that allowing `WithStackTrace` to be passed to `Span.End` may be in a gray area of the specification (as @dmathieu points out).  The relation to the original topic is that `WithStackTrace` is tantamount to a conditional call to `RecordError`, which itself is tantamount to a call to `SetAttributes`.  If `WithStackTrace` can be passed to `Span.End`, why not `WithAttributes`?

That said, I do understand the idiomatic value of using `defer` with `Span.End` as a mechanism to capture panics in Go -- I do not want to compromise that ability, nor do I require that `WithAttributes` be usable with `Span.End`.  This is really just about clarity -- my minimum ask for this issue is that the documentation for [`WithAttributes`](https://pkg.go.dev/go.opentelemetry.io/otel/trace#WithAttributes) be changed to remove [the reference to its use with `Span.End`](https://github.com/open-telemetry/opentelemetry-go/blob/bc2fe88756962b76eb43ea2fd92ed3f5b6491cc0/trace/config.go#L216):
> These attributes are used to describe the work a Span represents when this option is provided to a Span's start or end events.

**Comment by dmathieu** [comment]
I have updated the doc in my other PR.

**Comment by dmathieu** [comment]
> Also related is what I mentioned earlier about WithStackTrace not being implemented by SDK's AddEvent. (See [stackTraceOption.applyEvent](https://github.com/open-telemetry/opentelemetry-go/blob/652588ddd9f5bc7eaa15ace2b03b393bd8d039c1/trace/config.go#L256-L259) and then [recordingSpan.AddEvent](https://github.com/open-telemetry/opentelemetry-go/blob/664a075380b9eb155512adb1213ca688bd1ed611/sdk/trace/span.go#L519-L554) which never uses the flag nor records a stack trace.)

What would `AddEvent` do for `WithStackTrace`?
I feel like this isn't really an issue either, and documenting it should be enough of a solution.

**Comment by petenewcomb** [comment]
I suspect that the idea was that given `WithStackTrace(true)`, `AddEvent` would add a `semconv.ExceptionStacktrace` attribute to the event like [`RecordError` does](https://github.com/open-telemetry/opentelemetry-go/blob/664a075380b9eb155512adb1213ca688bd1ed611/sdk/trace/span.go#L494-L498) and [`Span.End` does](https://github.com/open-telemetry/opentelemetry-go/blob/664a075380b9eb155512adb1213ca688bd1ed611/sdk/trace/span.go#L430-L434).

Poking around some more reveals that this is a known issue that has been closed pending further clarity: https://github.com/open-telemetry/opentelemetry-go/pull/2336

 I'll pursue my remaining concerns there.  Thanks for listening and engaging with me here, @dmathieu, and for making those small fixes in the docs.
