### ISSUE TITLE
Safely dereference pointers when attaching additional attributes to span

### ISSUE THREAD

**Issue by Bakhtiyar-Garashov** [open-telemetry/opentelemetry-go#5968]
### Problem Statement

When attaching additional attributes to already existing span like below I need safely dereference pointers. I can implement a workaround myself, but asking here if it is possible to consider this in attribute module.

```
span.SetAttributes(
		attribute.Int64("username", *query.UserName),
		attribute.String("surname", *query.UserSurname)
	)

```

**Comment by dmathieu** [comment]
Those parameters don't take pointers, but values. You will need to turn those pointers into their values.
