### ISSUE TITLE
OTEL log sample for GO SDK

### ISSUE THREAD

**Issue by alexFilichkin** [open-telemetry/opentelemetry-go#5980]
I need to write logs from a Golang app to OTEL Collector. I cannot find an example of using the OTEL SDK for Go for logging. I know it's in beta, but we should have some samples anyway.

**Comment by pellared** [comment]
> I cannot find an example of using the OTEL SDK for Go for logging.

How long have you been trying? I hope that they are pretty accessible in multiple places.

From https://github.com/open-telemetry/opentelemetry-go:

> The [examples](https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/examples) are a good way to see some practical uses of this process.

You can there find:
- https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/examples/dice

Under https://opentelemetry.io/docs/languages/go/ we have:

- https://opentelemetry.io/docs/languages/go/getting-started/
- https://opentelemetry.io/docs/languages/go/instrumentation/#direct-to-collector

We have also an example in Go Logs SDK package docs:

- https://pkg.go.dev/go.opentelemetry.io/otel/sdk/log#example-package
