### ISSUE TITLE
API: Span

### ISSUE THREAD

**Issue by tedsuo** [open-telemetry/opentelemetry-go#6]

**Comment by rghetia** [comment]
span spec is at https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/tracing-api.md#span

Ref java implmentation :  https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/tracing-api.md#span

Opencensus [span](https://github.com/census-instrumentation/opencensus-go/blob/f6172e422374225c6748bd2a9c872e88c2eb43d4/trace/trace.go#L36)

Opentracing [span](https://github.com/opentracing/opentracing-go/blob/659c90643e714681897ec2521c60567dd21da733/span.go#L27)

**Comment by jmacd** [comment]
We've reached the initial milestone, will open new issues for future related API concerns.
