### ISSUE TITLE
Previously-closed sibling spans influence nesting behavior of new spans due to the context.

### ISSUE THREAD

**Issue by gannett-ggreer** [open-telemetry/opentelemetry-go#6033]
### Description

Previously-closed sibling spans influence nesting behavior of new spans due to the context.  The `trace` documentation always refers to `defer span.End()` but sometimes we want sibling spans in the same function.

### Environment

- OS: Linux
- Architecture: x86_64
- Go Version: 1.23.4
- opentelemetry-go version: v1.32.0

### Steps To Reproduce

When exporting to Grafana OTLP (have not tried other destinations), this code has different behavior:
```
import "go.opentelemetry.io/otel/trace"
tr := trace.SpanFromContext(ctx).TracerProvider().Tracer(tracerName)

ctx, span := tr.Start(ctx, "a")
...
span.End()

ctx, span = tr.Start(ctx, "b")
...
span.End()
```

than this code:
```
import "go.opentelemetry.io/otel/trace"
tr := trace.SpanFromContext(ctx).TracerProvider().Tracer(tracerName)
{
  ctx, span := tr.Start(ctx, "a")
  ...
  span.End()
}
{
  ctx, span := tr.Start(ctx, "b")
  ...
  span.End()
}
```

in the resulting span tree.  "b" will end up a child of "a" in the first case but a sibling in the second case.  

### Expected behavior

To me, if a span is closed then it should be ignored for purposes of finding the parent span so both code samples above should produce the same span tree.

**Comment by MrAlias** [comment]
That is because you are overwriting `ctx` and context is what defines the hierarchy.

```go
import "go.opentelemetry.io/otel/trace"
tr := trace.SpanFromContext(ctx).TracerProvider().Tracer(tracerName)

_, span := tr.Start(ctx, "a")
...
span.End()

_, span = tr.Start(ctx, "b")
...
span.End()
```

That will have the behavior your desire: both will be children of the span found in `ctx`.

**Comment by dmathieu** [comment]
Also, the [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#span-creation) states that on span creation, the specified context is the parent span's one.

> The parent Context or an indication that the new Span should be a root Span.

Picking the grandparent when the span has ended would have a big performance impact, as we would have to keep the entire stack of spans within the context (the grandparent can be ended too, in which case we'd have to fallback to the great grand parent), and have even more implications with distributed tracing (we can't know whether the distributed trace is finished or not).

You may also want to have a span as the child of another, even though it has already been closed. If you run something in a goroutine, the parent span may have been ended. The new one is still a child of that one.
