### ISSUE TITLE
Starting a new span from a context.Context is too laborious

### ISSUE THREAD

**Issue by seh** [open-telemetry/opentelemetry-go#609]
After using the _opentelemetry-go_ library for a few days, I find it to be tediously verbose compared to my touchstone: [Honeycomb's _beeline-go_ library](https://github.com/honeycombio/beeline-go). My focus is on the task I perform most frequently in my code: **starting a new span from a `context.Context`**.

In _opentelemetry-go_ today, the call sequence looks approximately like either
```go
trace.SpanFromContext(ctx).Tracer().Start(ctx, ...
```
or
```go
trace.SpanFromContext(ctx).Tracer().WithSpan(ctx, ...
```
This winds up performing the exact same `context.Context` lookup three times—extract a `Span` to get the current `Tracer`, then use that `Tracer` to start a new `Span`, which in turn tries to find the current `Span` in that same `context.Context` twice (the extra lookup buried in `parent.GetSpanContextAndLinks`). The result induces no change to the `Tracer` in use.

By contrast, _beeline-go_ offers [the `StartSpan` function](https://godoc.org/github.com/honeycombio/beeline-go#StartSpan). It wraps up that first call sequence above more concisely and more efficiently. It's true that there's no notion of an active `Tracer` whose implementation could vary, but in most cases that possibility is not relevant in the application or library code being instrumented. Looking around in _opentelemetry-go_, I know that there's also [`global.Tracer(string)`](https://godoc.org/go.opentelemetry.io/otel/api/global#Tracer), which could cut down on the search for the current `Tracer`, but that forces a map lookup and risks pulling in the wrong `Tracer`.

Was there ever a function considered for this library like _beeline-go_'s `StartSpan`? For an API that aspires to only publish interfaces, I can see how offering a concrete function like that is an odd duck, but it could live in the SDK.

**Comment by seh** [comment]
For those with access to the "Honeycomb Pollinators" Slack team, we discussed this topic over the last few days [in the "discuss-opentelemetry-beta" channel](https://honeycombpollinators.slack.com/archives/CNQ943Q75/p1585502985026000).

**Comment by rghetia** [comment]
The intention was to have tracer work like a logger in each component. 

```go
var (
   tr = global.Tracer("example.com/componentA")
)

func DoWork(ctx context.Context) {
    ctx, span := tr.Start(ctx, "Some work")
}
```

**Comment by seh** [comment]
Thank you for the suggestion, @rghetia, and for the follow-on discussion on today's SIG call. I'll try using this pattern and report back here shortly.

**Comment by seh** [comment]
The pattern that @rghetia has been working well for me. Thank you for the advice.

For now, I don't see the `Tracer`'s name emitted in any span attributes. Is there any plan to do so?

**Comment by Aneurysm9** [comment]
> For now, I don't see the `Tracer`'s name emitted in any span attributes. Is there any plan to do so?

I'm not aware of any current plans, nor am I aware of any reason not to do so.  If you'd like to open a new issue with a proposal we can discuss at a future SIG meeting.

I'm going to close this issue as it appears to have been addressed.
