### ISSUE TITLE
othttp: Allow dynamic span name based on URL Path or a functional option

### ISSUE THREAD

**Issue by marwan-at-work** [open-telemetry/opentelemetry-go#616]
Hi there :wave: 

I'm starting to replace OpenCensus Tracing with OpenTelemetry Tracing now that OT is in beta. 

The first problem I'm running into is migrating [ochttp](https://pkg.go.dev/go.opencensus.io@v0.22.3/plugin/ochttp?tab=doc) into [othttp](https://pkg.go.dev/go.opentelemetry.io/otel/plugin/othttp?tab=doc)

One thing I found a bit difficult to replicate is that othttp.NewHandler takes an operation argument which becomes the span name. In ochttp, the span name, by default, is the URL Path for every incoming request, or you can pass an option that formats the span name for every request [here](https://github.com/census-instrumentation/opencensus-go/blob/v0.22.3/plugin/ochttp/server.go#L72)

However, for othttp, we don't have either of those options except the `operation string` argument which means for every route, I have to statically provide the span name for it. 

This is mostly problematic when a user does not have control over http paths such as when using [Twirp](github.com/twitcht/twirp) 

Therefore, I see two solutions:

1. A quick solution is to make it so that if a user passes an empty string such as `othttp.NewHandler(myHandler, "")` then the othttp Handler will default to taking the URL Path for each request as the Span Name. 

2. More ideally, I'd rather have the user provide a span formatter based on each request, similar to ochttp's FormatSpanName that was linked above. In othttp's use case, you can provide this as an option such as `othttp.WithSpanName(func(r *http.Request) string)`, which might also prompt the removal of the `operation string` argument entirely.

**Comment by marwan-at-work** [comment]
For reference, I have two branches ready for a PR for both options: 

1. Option 1 PR https://github.com/marwan-at-work/opentelemetry-go/pull/new/616-1
2. Option 2 PR https://github.com/marwan-at-work/opentelemetry-go/pull/new/616-2

**Comment by Aneurysm9** [comment]
+1 for https://github.com/marwan-at-work/opentelemetry-go/pull/new/616-3

**Comment by marwan-at-work** [comment]
Great, I opened a PR for it and I'm happy to adjust.
