### ISSUE TITLE
Small inconsistencies in Resource API

### ISSUE THREAD

**Issue by vmihailenco** [open-telemetry/opentelemetry-go#620]
`resource.New` returns `*Resource` but `metric.WithResource` accepts `Resource` so it is not possible to do `metric.WithResource(resource.New(...))` which is strange. `Resource.Equal` also expects `Resource`. `trace.Config` has `Resource *resource.Resource`.

Also perhaps `trace.WithResourceAttributes` should be replaced with `trace.WithResource` to be consistent with `metric.WithResource`?

And finally `metric.WithResource` lives in API but `trace.WithResourceAttributes` lives in SDK. I guess both should be in SDK?

**Comment by shouri007** [comment]
@MrAlias I'd like to take this up, if that's ok.

**Comment by MrAlias** [comment]
@shouri007 : https://github.com/open-telemetry/opentelemetry-go/pull/640 addresses this issue (not sure @jmacd realized it). I'm not sure if you already started this work, but you'll probably want to coordinate with @jmacd .

**Comment by MrAlias** [comment]
@shouri007 : looks like #640 was closed. This is all yours.

**Comment by shouri007** [comment]
Alright, thanks! Will start working on it.

**Comment by jmacd** [comment]
I believe this was done in #651, which factored the metric label set code out and used it to implement resources. Sorry for the confusion.

**Comment by vmihailenco** [comment]
Thanks!
