### ISSUE TITLE
[Jaeger exporter] BufferMaxCount inconsistency - is actually about bytes

### ISSUE THREAD

**Issue by hypnoglow** [open-telemetry/opentelemetry-go#624]
[BufferMaxCount](https://github.com/open-telemetry/opentelemetry-go/blob/master/exporters/trace/jaeger/jaeger.go#L47) documentation says that it defines the total number of traces that can be buffered in memory, but it is assigned to [bundler.BufferedByteLimit](https://github.com/open-telemetry/opentelemetry-go/blob/master/exporters/trace/jaeger/jaeger.go#L143) which is about a number of bytes:

> // The maximum number of bytes that the Bundler will keep in memory before
	// returning ErrOverflow. The default is DefaultBufferedByteLimit.

**Comment by Aneurysm9** [comment]
I don't think this is incorrect.  The exporter is using the bundler package in perhaps a slightly unorthodox way, but it [documents this where the bundler is constructed](https://github.com/open-telemetry/opentelemetry-go/blob/master/exporters/trace/jaeger/jaeger.go#L139-L144)

> 	// Set BufferedByteLimit with the total number of spans that are permissible to be held in memory.
> 	// This needs to be done since the size of messages is always set to 1. Failing to set this would allow
> 	// 1G messages to be held in memory since that is the default value of BufferedByteLimit.
> 

And when a [span is added to the bundle](https://github.com/open-telemetry/opentelemetry-go/blob/master/exporters/trace/jaeger/jaeger.go#L194) it size is explicitly stated to be `1`.  This results in the bundler counting items and not bytes.

**Comment by MrAlias** [comment]
Closing as this sounds like expected behavior.
