### ISSUE TITLE
Simple way to trace with HTTP client in Go

### ISSUE THREAD

**Issue by Zwiefront** [open-telemetry/opentelemetry-go#637]
To trace with http client in OpenCensus:

```go
import "go.opencensus.io/plugin/ochttp"
// ... 
client := http.Client{Transport: &ochttp.Transport{}}
```

As per OpenTelemetry demo code in [the workshop materials](https://glitch.com/edit/#!/opentelemetry-instructor?path=src/main.go:1:0):

```go
import "go.opentelemetry.io/otel/plugin/httptrace"
// ...
client := http.DefaultClient
// ...
req, _ := http.NewRequestWithContext(ictx, "GET", url, nil)
ictx, req = httptrace.W3C(ictx, req)
httptrace.Inject(ictx, req)
res, err := client.Do(req)
```

It's kinda complicated, and every request should be injected like this.

Can you please provide any compatible ways like the old `ochttp.Transport`?

**Comment by Aneurysm9** [comment]
I've started work on an `http.Transport` implementation in the `othttp` package.  I hope to have a PR up with a first pass by next week.

**Comment by jmacd** [comment]
We agree this will be good to improve on.
