### ISSUE TITLE
Per-instrument metric resources: OK or non-standard?

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-go#638]
I was reflecting on how we handle Resources in the metrics pipelines and we haven't added support in the exporters yet. I noticed that we support resources on a per-instrument basis or fall-back to the SDK's resources. I wonder if this is "off spec"? I would note that Prometheus supports "constant labels" which is roughly the same, so maybe it's fine.

The question came about because I'm trying to figure out how to cache the encoding of a resource value in an exporter.

**Comment by jmacd** [comment]
One of the glaring points is that the `api/metric` package is importing the `sdk/resource` package. The API shouldn't have this dependency, so either we move Resource into the API or remove per-instrument resources. I think the spec would say we shouldn't have resources in the API.

**Comment by jmacd** [comment]
@bogdandrutu Please review.

**Comment by bogdandrutu** [comment]
Currently based on the specs there is one resource per SDK instance (metric provider), see here https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/resource/sdk.md#resource-sdk.

**Comment by jmacd** [comment]
This will happen after #640 is re-done following #651.

**Comment by jmacd** [comment]
The same has been done in the OTLP protocol.
