### ISSUE TITLE
Golang Lint tool corrupts files in `--fix` mode on unused types

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-go#665]
Sample input:
```
// COPYRIGHT

package anything

type (
	unused struct{}
)

func X() {}
```

Command used: `golangci-lint run --fix file.go`

Contents of file after running the above command:
```
// COPYRIGHT

package metric

type (
// COPYRIGHT

package metric

type (
	unused struct{}
)

func X() {}
```

**Comment by krnowak** [comment]
Filed an issue to upstream (https://github.com/golangci/golangci-lint/issues/1048) and worked the bug around in #666.

**Comment by ernado** [comment]
Please try golangci-lint [v1.25.1](https://github.com/golangci/golangci-lint/releases/tag/v1.25.1).
I've fixed invalid `--fix` suggestions from `unused` and added a warning.

```console
$ GO111MODULE=on go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.25.1
```

**Comment by krnowak** [comment]
@ernado : We now use 1.25.1 and it seems to work. Thanks!
