### ISSUE TITLE
Fix Flaky CircleCI Builds

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#685]
The Circle CI build system randomly fails to build packages. For example:

- https://circleci.com/gh/open-telemetry/opentelemetry-go/2145
- https://circleci.com/gh/open-telemetry/opentelemetry-go/2133
- https://circleci.com/gh/open-telemetry/opentelemetry-go/2130

The package that fails to build is not consistent, meaning it is not always the same package that fails. An example failure message:

```
...
FAIL	go.opentelemetry.io/otel/sdk/metric/aggregator/lastvalue [build failed]
...
```

I have not been able to reproduce this locally, but it definitely needs to be tracked down.

**Comment by evantorrie** [comment]
Looks like the Go linker is being randomly killed due to OOM. Since OOM killer is inherently a "random" selector, it would explain why this is flaky. Is it possible to upgrade to a bigger docker container to see if that does indeed "fix" the issue?

**Comment by MrAlias** [comment]
> Looks like the Go linker is being randomly killed due to OOM. Since OOM killer is inherently a "random" selector, it would explain why this is flaky. Is it possible to upgrade to a bigger docker container to see if that does indeed "fix" the issue?

@lizthegrey would you know if upgrading our testing instance size is okay?  Seems like it is a simple addition of the [resource_class](https://circleci.com/docs/2.0/configuration-reference/#available-machine-images) property?
