### ISSUE TITLE
B3 Propagator doesn't handle 64-bit TraceIDs

### ISSUE THREAD

**Issue by Aneurysm9** [open-telemetry/opentelemetry-go#686]
The [B3 spec](https://github.com/openzipkin/b3-propagation#traceid-1) allows for both 64-bit and 128-bit `TraceID`s, but does not specify how to handle interop between systems that produce/expect different length IDs.  

The [Otel-Go B3 propagator](https://github.com/open-telemetry/opentelemetry-go/blob/master/api/trace/b3_propagator.go#L92) uses [`core.TraceIDFromHex()`](https://github.com/open-telemetry/opentelemetry-go/blob/d7b3c3d7e7a7c56e9bfa6aa40d03d75e78e3dd3f/api/core/span_context.go#L98) which requires a hex-encoded `TraceID` be 32 hex digits.

Should we left-pad incoming `TraceID` values in the B3 propagator prior to decoding, or should we take another approach?

**Comment by jmacd** [comment]
@MikeGoldsmith @codeboten would you comment? I believe you've studied this.

**Comment by lizthegrey** [comment]
Please escalate this to the Spec SIG, as we need to consistently handle this across all of OTel.

**Comment by Aneurysm9** [comment]
I actually think that the spec provides enough to consistently handle the issue, so I'll not open an issue against the spec repo, but I will add it to the agenda for the next Spec SIG meeting so we can discuss.

I think that between [the trace API spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#spancontext) declaring that "[t]he OpenTelemetry `SpanContext` representation conforms to the [w3c TraceContext specification](https://www.w3.org/TR/trace-context/)" and the [w3c interop guidance](https://www.w3.org/TR/trace-context/#interoperating-with-existing-systems-which-use-shorter-identifiers) stating that "[s]horter identifiers SHOULD be left padded with zeros when converted to 16 bytes `trace-id`", the correct approach is clear.

After surveying the other OTel implementations, I found the following that exhibit the same issue when receiving 64-bit B3 `TraceID` values:

* [opentelemetry-js](https://github.com/open-telemetry/opentelemetry-js/blob/master/packages/opentelemetry-core/src/context/propagation/B3Propagator.ts#L86)
* [opentelemetry-swift](https://github.com/open-telemetry/opentelemetry-swift/blob/f973691012ef0baebe2156b245e777c16857a64c/Sources/OpenTelemetryApi/Trace/TraceId.swift#L129) ([invoked here](https://github.com/open-telemetry/opentelemetry-swift/blob/f973691012ef0baebe2156b245e777c16857a64c/Sources/OpenTelemetryApi/Trace/Propagation/B3Propagator.swift#L132)) appears to expect the `TraceID` to be 128 bits.

The following implementations left-pad the `TraceID`:

* [opentelemetry-java (contrib)](https://github.com/open-telemetry/opentelemetry-java/blob/8a0ec1d42dbb39e24507b75c629ce44f6dfd9ba5/contrib/trace_propagators/src/main/java/io/opentelemetry/contrib/trace/propagation/B3Propagator.java#L214)
* [opentelemetry-dotnet](https://github.com/open-telemetry/opentelemetry-dotnet/blob/e5822871979d24fd0948db002dd03e53e7ef2693/src/OpenTelemetry/Context/Propagation/B3Format.cs#L156) and [the single header version](https://github.com/open-telemetry/opentelemetry-dotnet/blob/e5822871979d24fd0948db002dd03e53e7ef2693/src/OpenTelemetry/Context/Propagation/B3Format.cs#L218)

The following implementations do not validate the `TraceID` length and parse as received from hex to integers:

* [opentelemetry-rust](https://github.com/open-telemetry/opentelemetry-rust/blob/master/src/api/trace/b3_propagator.rs#L39)
* [opentelemetry-python](https://github.com/open-telemetry/opentelemetry-python/blob/c772bb7deb659fd3ba27a235b77c31ddea23169d/opentelemetry-sdk/src/opentelemetry/sdk/trace/propagation/b3_format.py#L113)

The [opentelemetry-erlang implementation](https://github.com/open-telemetry/opentelemetry-erlang/blob/806aa1132288ea393188644eb0cead2940eaede3/src/ot_propagation_http_b3.erl#L56) converts from hex to integer [after validating the incoming hex is 16 or 32 digits](https://github.com/open-telemetry/opentelemetry-erlang/blob/806aa1132288ea393188644eb0cead2940eaede3/src/ot_propagation_http_b3.erl#L73).

The remaining implementations (PHP, Ruby, C++) do not appear to provide B3 propagators.

**Comment by SergeyKanzhelev** [comment]
Some relevant discussion: https://github.com/w3c/trace-context/issues/349 I agree, we need consistency on whether short Trace-ID should be accepted

**Comment by tedsuo** [comment]
+1 for left padding with zeros
