### ISSUE TITLE
Move Number from core package into api/metric package

### ISSUE THREAD

**Issue by tensorchen** [open-telemetry/opentelemetry-go#703]

**Comment by MrAlias** [comment]
@tensorchen can you provide some context around what you are trying to achieve and what is motivating this?

**Comment by tensorchen** [comment]
Consider splitting package `api/core` in more meaningful packages. Package names are very important to readability, and core isn't great.

Finally, the core package is expected to be eliminated. Part of the job is move Number from core package into api/metric package

This relates to #261
