### ISSUE TITLE
Move KeyValue from core package into key and rename key to kv

### ISSUE THREAD

**Issue by tensorchen** [open-telemetry/opentelemetry-go#704]

**Comment by MrAlias** [comment]
@tensorchen can you provide some context around what you are trying to achieve and what is motivating this?

**Comment by tensorchen** [comment]
Consider splitting package api/core in more meaningful packages. Package names are very important to readability, and core isn't great.

Finally, the core package is expected to be eliminated. Part of the job is move `KeyValue` from `core` package into `key` and rename key to `kv`

This relates to #261
