### ISSUE TITLE
Unify Meter registry in registry package.

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#714]
Currently the Meter keeps its own registry to track uniqueness. This functionality should be unified in the `registry` package.

_Originally posted by @MrAlias in https://github.com/open-telemetry/opentelemetry-go/pull/709/files_

**Comment by jmacd** [comment]
IOW we should create a simple implementation of `metric.Provider` in the `api/metric/registry` package. It should contain a `map[string]MeterImpl` and a `sync.Mutex` and the code in `api/global/internal/meter.go` should use it.
