### ISSUE TITLE
0.5.0 release?

### ISSUE THREAD

**Issue by lizthegrey** [open-telemetry/opentelemetry-go#715]
we've gone 17 days without a release, we should probably push something out.

**Comment by Aneurysm9** [comment]
I think #720 should land before we ship 0.5.0 so that we've got the core package elimination complete.  @jmacd are there any metrics PRs that should really land before the next release is cut?

**Comment by jmacd** [comment]
Since you ask, it would be nice to land #717 which has one approval already.

**Comment by jmacd** [comment]
We are ready to make a release.

**Comment by MrAlias** [comment]
We haven't hit all the milestone items set for v0.5.0 yet.

I'm going release v0.4.4 instead. Unless there are objections?

**Comment by MrAlias** [comment]
To better mark the breaking changes, switching back to v0.5.0. I'll rename the milestone after the release.

**Comment by MrAlias** [comment]
https://github.com/open-telemetry/opentelemetry-go/releases/tag/v0.5.0
