### ISSUE TITLE
Move all Meter methods to `sdk.go`

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#716]
Currently there are methods for the Meter declared in `sdkhelpers.go`. Move these to `sdk.go`.

_Originally posted by @MrAlias in https://github.com/open-telemetry/opentelemetry-go/pull/709_

**Comment by jmacd** [comment]
Ohhh. I think you mean to move these into a new file in the same `api/metric` package? Sounds good.

**Comment by jmacd** [comment]
Actually, if that's what you mean, I suggest `meter.go`
