### ISSUE TITLE
Support for array of span attributes

### ISSUE THREAD

**Issue by dackroyd** [open-telemetry/opentelemetry-go#718]
Support for attribute arrays does not appear to be implemented (yet?), but is covered by the spec:

https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#set-attributes

> An Attribute is defined by the following properties:
> * (Required) The attribute key, which MUST be a non-null and non-empty string.
> * (Required) The attribute value, which is either:
>   * A primitive type: string, boolean or numeric.
>   * **An array of primitive type values. The array MUST be homogeneous, i.e. it MUST NOT contain values of different types.**

I'd imagine the API for this looking something like the following for each primitive type:

```
func Strings(k, v ...string) core.KeyValue {
	return New(k).Strings(v...)
}
...
func (k Key) Strings(v ...string) KeyValue {
	return KeyValue{
		Key:   k,
		Value: <slice>
	}
}
```

**Comment by stefanprisca** [comment]
Is this what you are looking for?
https://github.com/open-telemetry/opentelemetry-go/blob/88100f0fc752e57cc52e16ef2b4f3d520f0abc74/sdk/trace/provider.go#L200

**Comment by dackroyd** [comment]
I don't believe so? `provider.WithResourceAttributes` (like `span.SetAttributes`) allows multiple _distinct_ key/values to be set, with values being overridden if there is a clash.

What I'm understanding for the 'array' support in the spec is that it should be possible for the values to accept primitive arrays for a **single** key, e.g:

```
val := []string{"bar1", "bar2", "bar3"}
span.SetAttributes(key.Strings("foo", val...))
```

https://github.com/open-telemetry/opentelemetry-specification/pull/368

> Array values are useful for representing attributes that can have
multiple values (e.g. representing a Memcached get that can be
over multiple keys and making the keys a span attribute).
>
> This change allows homogeneous array values for span attributes
and specifies that array values should be JSON encoded string when
exporting using protocols that do not natively support array values.

This was added to the DotNet implementation back in February: https://github.com/open-telemetry/opentelemetry-dotnet/pull/500

**Comment by MrAlias** [comment]
The ask from the SIG meeting today was to make this more universal:

- Allow `nil`, nulls.
- Allow all "primitive" types.
- Allow maps, slices, and maybe structs.

This might need to update the specification to be in compliance if the above are included.

**Comment by mujtaba-ahmed12** [comment]
@MrAlias I would like to work on this issue.

**Comment by mujtaba-ahmed12** [comment]
@MrAlias I am thinking of two ways of doing this.
1. Create generic method for array and check if its homogeneous array as done here in .NET implementation https://github.com/open-telemetry/opentelemetry-dotnet/pull/500/files#diff-61ad2bb28c6f75dcacf313e09a9b6488R840 and determine type at runtime.

```
// Array creates array Value of homogeneous type
func Array(collection []interface{}) Value {
	foreach := func(collection []interface{}) bool {
		for _, item := range collection {
			if reflect.TypeOf(collection[0]) != reflect.TypeOf(item) {
				return false
			}
		}
		return true
	}

	// Check if array is homogeneous or not
	if !foreach(collection) {
		return Value{
			vtype:   ARRAY,
			numbers: nil,
			strings: nil,
		}
	}

	if reflect.TypeOf(collection[0]).Kind() == reflect.String {
		return Value{
			vtype:   ARRAY,
			// Strings assignment
		}
	}

	return Value{
		vtype: ARRAY,
		// Numeric Assignment
	}

}
```

2. Create separate method for each type.

**Comment by MrAlias** [comment]
@mujtaba-ahmed12:

I think you could try to leverage the Go type system a bit more which already guarantees slice/array homogeneity. I haven't worked through the full example, but I imagine something like this would suffice:

```
// Array creates array Value of homogeneous type
func Array(collection interface{}) Value {
	rt := reflect.TypeOf(v)
	switch rt.Kind() {
	case reflect.Slice, reflect.Array:
		// TODO: marshal slice/array
		// TODO: figure out what to do with multi-level values
	default:
		// TODO: return [Value] (?)
	}
	// ...
}
```

I would probably support multi-level slices/arrays here because the spec is a bit vague about this (primitive type is not well defined (is it language specific?)) and our value functions here are not setup for returning errors here.
