### ISSUE TITLE
Panic in gRPC StreamClientInterceptor

### ISSUE THREAD

**Issue by realdave** [open-telemetry/opentelemetry-go#748]
Calling [`StreamClientInterceptor.CloseSend`](https://github.com/open-telemetry/opentelemetry-go/blob/c5f2252c4861ddcbc1bc56d4c53ce4c5e40e2d24/plugin/grpctrace/interceptor.go#L186) after the stream is finished results in a `send on closed channel` panic. I'm not certain if there is a legitimate reason for CloseSend to be called on the stream more than once, but believe the interceptor should avoid a panic if possible.

Test to illustrate the panic: https://github.com/realdave/opentelemetry-go/blob/09960a756f61d86b94b2c14ddcdb0125df491649/plugin/grpctrace/interceptor_test.go#L381

I'd be happy to submit a PR to address this, but wanted to check with you first to confirm that this is a bug, and if so, to see if you had any guidance on a fix. One option:

1. Add an additional "finished signal" channel on `clientStream` that is closed when sending a message to the existing `finished` channel ([1](https://github.com/open-telemetry/opentelemetry-go/blob/c5f2252c4861ddcbc1bc56d4c53ce4c5e40e2d24/plugin/grpctrace/interceptor.go#L218), [2](https://github.com/open-telemetry/opentelemetry-go/blob/c5f2252c4861ddcbc1bc56d4c53ce4c5e40e2d24/plugin/grpctrace/interceptor.go#L223))
1. Update `CloseSend` to validate that the new "finished signal" channel is not closed before [sending to `events`](https://github.com/open-telemetry/opentelemetry-go/blob/c5f2252c4861ddcbc1bc56d4c53ce4c5e40e2d24/plugin/grpctrace/interceptor.go#L190)

**Comment by MrAlias** [comment]
Avoiding panics sounds like a good idea :+1:.

I think the strategy you outlined sounds reasonable with the current design. I look forward to you PR :smile:.
