### ISSUE TITLE
API: Convert Event interface to concrete type

### ISSUE THREAD

**Issue by rghetia** [open-telemetry/opentelemetry-go#76]
see this [comment](https://github.com/open-telemetry/opentelemetry-go/pull/65/files#r310237999)

Event is currently an interface. It is desirable that this be converted to a concrete Event type with support for lazy loading.

**Comment by agneum** [comment]
Hi! Is this issue actual? Can I take it to fix?

**Comment by rghetia** [comment]
> Hi! Is this issue actual? Can I take it to fix?

yes and yes. Thanks for helping out.
