### ISSUE TITLE
Add option to put proto payloads in span for certain methods.

### ISSUE THREAD

**Issue by jackskj** [open-telemetry/opentelemetry-go#763]
Suggestions: 
- Dump the entire proto message in the spawn (not just size).

- Trace fields with a particular option set to true. Example:
```
syntax = "proto3";
import "google/protobuf/descriptor.proto";
package opentelemetry;
extend google.protobuf.FieldOptions {
    bool trace = 50000;
}

message MyMessage {
    string stuff = 1 [(opentelemetry.trace) = true];
}
```

**Comment by MadVikingGod** [comment]
I'm not sure I understand the ask of this.  Would it be possible to give an example of how we would interact with this protobuf flag?  Would this be part of the grpc instrumentation?

**Comment by MrAlias** [comment]
Closing due to lack of response. Please reopen if you are able to provide the needed information. Thanks!
