### ISSUE TITLE
Use lowercase B3 header names and correct single header name

### ISSUE THREAD

**Issue by morlay** [open-telemetry/opentelemetry-go#765]
for now trace.B3SingleHeader is a const value `X-B3`

but for some system, it need to be `b3` which following `https://github.com/openzipkin/b3-propagation`

![image](https://user-images.githubusercontent.com/1667873/82718767-1f954780-9cd7-11ea-8685-b0fc6abcdff6.png)
https://istio.io/faq/distributed-tracing/

**Comment by MrAlias** [comment]
[From the B3 specification](https://github.com/openzipkin/b3-propagation#multiple-headers):

> Note: Http headers are case-insensitive, but sometimes this encoding is used for other transports. When encoding in case-sensitive transports, prefer lowercase keys or the single header header encoding which is explicitly lowercase.

We should use the lowercase form of the headers to ensure compatibility. Similar to[ what the zipkin library does](https://github.com/openzipkin/zipkin-go/blob/master/propagation/b3/shared.go#L36-L44).

We might want to look into just using that library to support the B3 spec.

**Comment by MrAlias** [comment]
Also, we definitely need to fix the single header name (`X-B3` -> `b3`).
