### ISSUE TITLE
Standard resource values needed

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-go#767]
There was a TODO in the -contrib repository about adding the Go version as a label on the runtime metrics. This seems like a label that should be applied on the resource. 

For this ticket: identify resources that should be considered standard and provide helpers in the `/sdk/resource` package to build the standard resource values.

**Comment by MrAlias** [comment]
Likely duplicated by https://github.com/open-telemetry/opentelemetry-go/issues/785

**Comment by MrAlias** [comment]
Closing based on the detectors that were added in the linked issue.
