### ISSUE TITLE
Update contrib repo needs to be included in a release

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#772]
When a new release is made here it needs to be propagated to the relevant https://github.com/open-telemetry/opentelemetry-go-contrib repository. Guidelines for this need to be added to the RELEASING.md.

Relates to https://github.com/open-telemetry/opentelemetry-go-contrib/issues/45

**Comment by evantorrie** [comment]
Also see https://github.com/open-telemetry/opentelemetry-go-contrib/pull/52 and https://github.com/open-telemetry/opentelemetry-go-contrib/pull/60
