### ISSUE TITLE
Go should automatically detect GKE resource labels and send them to Stackdriver

### ISSUE THREAD

**Issue by dukeng** [open-telemetry/opentelemetry-go#773]
OpenTelemetry should detect GKE openCensus resources and send those resources to Stackdriver as span attributes.

Similarly, there has been a [mapping in OC](https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/blob/master/RESOURCE.md#k8s_container) for this feature.

Related issue:
https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/issues/261

**Comment by MrAlias** [comment]
OpenTelemetry provides a vendor agnostic approach in the core libraries it offeres. This seems like an issue better suited for [the Google Stackdriver exporter](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go).
