### ISSUE TITLE
Remove `trace.WithRecord()` trace start option

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-go#787]
The spec: 
https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#isrecording

Some history:
https://github.com/open-telemetry/opentelemetry-go/pull/223
#188 
https://github.com/open-telemetry/opentelemetry-go/issues/192

The task is to implement `Span.IsRecording() bool` which returns true if the span is not a no-op.

**Comment by evantorrie** [comment]
@jmacd Can you clarify this a little? I thought #188 did change/add the `IsRecording() bool` function to the Span interface and all implementations.

**Comment by jmacd** [comment]
I realize that `IsRecording()` is implemented. I thought it had been removed.

**Comment by jmacd** [comment]
Ah, the spec does not support a `WithRecord()` function that we currently have. It's the sampler's responsibility for deciding if a span records.

**Comment by MrAlias** [comment]
I think this has become a duplicate of #192, going to close this and consolidate the conversation there.
