### ISSUE TITLE
Switch to gRPC retry middleware for retries in OTLP exporter

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#789]
Instead of using the gRPC service config, evaluate using the gRPC ecosystem middleware: https://github.com/grpc-ecosystem/go-grpc-middleware/tree/master/retry

_Originally posted by @nilebox in https://github.com/open-telemetry/opentelemetry-go/pull/777_

**Comment by evantorrie** [comment]
The grpc-middleware retry interceptor does not provide the backoff function any information about the kind of error which the request received. According to the OTLP spec, the collector will send back throttling information in the grpc Status encapsulated in the error.

Not having this available to the backoff function would mean an inability to strictly comply with the OTLP spec.

However, I see in #777 that the implemented default service configuration does invoke a throttled response based on a token bucket model, which may in turn out to be a better implementation that the proposed throttling mechanism from https://github.com/open-telemetry/oteps/blob/master/text/0035-opentelemetry-protocol.md#throttling.

**Comment by MrAlias** [comment]
> The grpc-middleware retry interceptor does not provide the backoff function any information about the kind of error which the request received. According to the OTLP spec, the collector will send back throttling information in the grpc Status encapsulated in the error.
> 
> Not having this available to the backoff function would mean an inability to strictly comply with the OTLP spec.
> 
> However, I see in #777 that the implemented default service configuration does invoke a throttled response based on a token bucket model, which may in turn out to be a better implementation that the proposed throttling mechanism from https://github.com/open-telemetry/oteps/blob/master/text/0035-opentelemetry-protocol.md#throttling.

Good point. Closing.
