### ISSUE TITLE
Consider generating Go types for OTLP in this repo

### ISSUE THREAD

**Issue by nilebox** [open-telemetry/opentelemetry-go#793]
This will allow us to delete Go code from the `opentelemetry-proto` and make that repo cleaner in general.

See https://github.com/open-telemetry/opentelemetry-proto/issues/79#issuecomment-637881895 and the rest of the thread there.

**Comment by MrAlias** [comment]
Notes from last week's SIG meeting:

> Notes from Steve: Consider the experience for people using our Go module with Bazel and Gazelle.
> Do they need to work around our choice to generate the Go code from the Protocol Buffer IDL files?
> Is it easier for them to have Bazel generate that code “automatically”?
> Using a Git submodule for storing the generate code will cause problems for people using Gazelle.

Current thinking is to build a generation pipeline to take the proto code and check the generated output into a sub-(go-)module.
