### ISSUE TITLE
Merge the otel-collector and OTLP example

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#795]
The OTLP example includes examples of exporting metrics and the otel-collector example includes a full setup pipeline. They both exemplify how to export with the OTLP and could be merged into a unified example.

_Originally posted by @wtong98 in https://github.com/open-telemetry/opentelemetry-go/pull/790#issuecomment-638477641_

**Comment by wtong98** [comment]
Sorry about the delay! I can go ahead and start putting this together

**Comment by MrAlias** [comment]
closed by #841
