### ISSUE TITLE
Merge http example README

### ISSUE THREAD

**Issue by jan25** [open-telemetry/opentelemetry-go#797]
There are couple of http example README which can be merged:
1. https://github.com/jan25/opentelemetry-go/tree/master/example#example - Looks outdated, probably can be dropped as it talks about setting up GOPATH
2. https://github.com/jan25/opentelemetry-go/tree/master/example/http#http-client-server-example - This needs additional run instructions on how to run outside without docker-compose

**Comment by MrAlias** [comment]
This looks stale. Please reopen if things remain to be addressed.
