### ISSUE TITLE
API: Inject/Extract

### ISSUE THREAD

**Issue by tedsuo** [open-telemetry/opentelemetry-go#8]

**Comment by jmacd** [comment]
Related: https://github.com/opentracing/opentracing-go/issues/127

**Comment by jmacd** [comment]
And https://opentracing.io/docs/overview/inject-extract/

**Comment by rghetia** [comment]
Waiting for clarity in specs.
AI[@rghetia ]:  add a link to spec repo.

**Comment by rghetia** [comment]
spec for propagation
- [GetBinaryFormat](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-tracing.md#getbinaryformat)
- [GetHttpTextFormat](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-tracing.md#gethttptextformat)
