### ISSUE TITLE
Inconsistency between trace and metric exporter helpers

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-go#800]
The metric exporters include functions named: "NewRawExporter" (except prometheus, since it doesn't implement the Exporter interface), "NewExportPipeline", and "InstallNewPipeline".

The Jaeger exporter has "NewRawExporter" and "NewExportPipeline" but not "InstallNewPipeline", instead it uses a boolean `RegisterGlobal` to indicate whether the pipeline should be installed as the global. 

The Zipkin exporter has none of these functions.

I would prefer if we added InstallNewPipeline to Jaeger and all three of these functions to Zipkin, to bring about consistency. This came up in #796 because the JAEGER_DISABLED environment variable should probably cause "InstallExportPipeline" to install a No-op SDK, not to install a real SDK with a disabled exporter.

**Comment by matej-g** [comment]
I'd like to start working on this one
