### ISSUE TITLE
Examples with Jaeger as the Exporter

### ISSUE THREAD

**Issue by jon-whit** [open-telemetry/opentelemetry-go#813]
Are there any good examples of using the Jaeger exporter? It looks like the Jaeger exporter doesn't implement the `trace.SpanBatcher` interface's `ExportSpans` method. The Jaeger exporter only implements the `ExportSpan` method.

If not, does anyone have a good workaround in the meantime? I'm trying to write a blog post that demonstrates how to use OpenTelemetry in Go.

**Comment by MrAlias** [comment]
The example code for Jaeger is located here: https://github.com/open-telemetry/opentelemetry-go/tree/master/example/jaeger

Your observation about the lack of implementation of the `SpanBatcher` is correct. I'm not sure if there is a way to optimize the batching with Jaeger more than doing [something similar to what was done with the OTLP](https://github.com/open-telemetry/opentelemetry-go/blob/master/exporters/otlp/otlp.go#L268-L274), but feel free to submit a change if you really need to use the exporter as a batcher.

**Comment by jon-whit** [comment]
@MrAlias awesome! Thanks for the reference.
