### ISSUE TITLE
Clarify how AWS CloudWatch integrates with opentelemetry-go

### ISSUE THREAD

**Issue by cep21** [open-telemetry/opentelemetry-go#83]
Hi,

I tried writing a cloudwatch exporter for open census and the API there is not rich enough to do CloudWatch metrics well.  I document some of the reasons on the README.md at https://github.com/cep21/cwopencensusexporter

I see open telemetry is based upon open census.  Will it have the same problems, or will it work well with CloudWatch?

I've looked over a few metrics APIs and it seems like segment.io's handler is expressive enough for cloudwatch metrics because it lets me handle measures higher up the API stack at https://github.com/segmentio/stats/blob/master/handler.go#L15.  Will open telemetry allow the same?

Thanks!

**Comment by rghetia** [comment]
@cep21 thanks for opening this issue. There are two distinct requirements here.

1. Fixed (but configurable) Reporting Interval.
2. Report min/max over Reporting Interval instead of life of the metric. This is dependent on the first requirement.

First requirement is strictly how SDK implements it. While the second would require changes to [metrics proto](https://github.com/open-telemetry/opentelemetry-proto/blob/master/src/opentelemetry/proto/metrics/v1/metrics.proto) to accommodate min/max.

**Comment by cep21** [comment]
> 1. Fixed (but configurable) Reporting Interval.

It's a bit more complicated than that.  A fixed reporting interval is something that will kind of work but not strictly work. To strictly support CloudWatch with as much accuracy as possible, I would need to ensure a datapoint received at 59.999 goes to window 0 and a datapoint received at 60.0001 goes to window 1.  This is possible with APIs similar to segment's, but use of open telemetry would sacrifice strict correctness, which is a difficult ask for people that are looking for a metrics abstraction: comparing "good enough" metrics with "strictly correct" metrics.

We need to aggregate by when the metrics come in, not when the code happens to aggregate them.

> two distinct requirements

There's another part about preventing pre aggregation with types like `metricdata.Summary`.  I cannot provide a good user experience for this.  With an API like segment's I can ignore `metricdata.Summary` by aggregating on ingestion.

**Comment by rghetia** [comment]
Thanks for clarifying. It is 'Fixed Aggregation Interval' rather than 'Fixed Reporting Interval'.

Regarding Summary - can you clarify what do you mean by 'ignore metricdata.Summary by aggregating on ingestion.' ?

**Comment by cep21** [comment]
> can you clarify what do you mean by 'ignore metricdata.Summary by aggregating on ingestion

`metricdata.Summary` is a lossy aggregation for CloudWatch.  A CloudWatch user would never want to aggregate like that.  They would prefer aggregating into a distribution so real percentiles can be calculated on the fly.  One way to do this is to simply not allow data to ever get into a `metricdata.Summary` type and to aggregate it on ingestion into a distribution.

**Comment by rghetia** [comment]
stale issue.
