### ISSUE TITLE
Rename structs

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#842]
- `Integrator` -> `Processor` (related to https://github.com/open-telemetry/opentelemetry-specification/issues/659).
- `SynchronizedCopy` -> `SynchronizedMove` (a reset happens after the checkpoint is returned).
- `AggregationSelector` -> `AggregatorSelector`

**Comment by jmacd** [comment]
"Simple" integrator -> "Basic" integrator too.
