### ISSUE TITLE
use otlp push metric message to collector, message is that grpc: error unmarshalling request: proto: wrong wireType = 2 for field Temporality

### ISSUE THREAD

**Issue by gunsluo** [open-telemetry/opentelemetry-go#845]
Additional context

The reason for the problem is that the client and server use different pb.go generation files.

grpc server of the collector(v0.4.0) use this file https://github.com/open-telemetry/opentelemetry-collector/blob/v0.4.0/internal/data/opentelemetry-proto-gen/collector/metrics/v1/metrics_service.pb.go

grpc client() use the file https://github.com/open-telemetry/opentelemetry-proto/blob/v0.3.0/gen/go/collector/metrics/v1/metrics_service.pb.go

**Incompatible pb files are the cause of the problem.**

more detail: 
https://github.com/open-telemetry/opentelemetry-collector/issues/1154

Are there any plans to update the client's pb.go

**Comment by Darrenzzy** [comment]
汉语表述一遍： 就是grpc的server 和client 两端用的pb文件 中二进制码对不上导致的 这个问题。

所以解决方案：是重新梳理下server端的proto 在 client端重新生成pb文件，然后就可以正常调用了。
