### ISSUE TITLE
Consider upgrading github.com/golang/protobuf to google.golang.org/protobuf 

### ISSUE THREAD

**Issue by evantorrie** [open-telemetry/opentelemetry-go#849]
`github.com/golang/protobuf` which is used in most of the exporters has been superseded by `github.com/golang/protobuf`. However, there are some breaking API changes - which require us to go through and see what needs to be changed in our code to move to the new API.

**Comment by lizthegrey** [comment]
notably, grpc will always depend upon github.com/golang/protobuf and won't be migrating to google.golang.org/protobuf any time soon, is my understanding.

**Comment by codeanyway11** [comment]
Hi, you guys are right. We can't exactly get rid of `github.com/golang/protobuf` since `grpc` is using it, but should we still go ahead and make changes in the exporters? I am planning to work on this issue :smile:

**Comment by lizthegrey** [comment]
That's correct, we can choose to make those changes in exporters.

**Comment by MrAlias** [comment]
> We can't exactly get rid of `github.com/golang/protobuf` since `grpc` is using it, but should we still go ahead and make changes in the exporters?

Yes, removing it from our use will help us be ready when upstream is able to make the switch as well. :+1:

**Comment by MrAlias** [comment]
@codeanyway11 are you still working on this or should I unassign you?

**Comment by MrAlias** [comment]
We no longer depend on "github.com/golang/protobuf" directly as far as I can tell.
