### ISSUE TITLE
Support export telemetry through OTLP/HTTP protocol

### ISSUE THREAD

**Issue by tensorchen** [open-telemetry/opentelemetry-go#860]
See https://github.com/open-telemetry/oteps/blob/master/text/0099-otlp-http.md.

In some special environments, we can only use the http protocol. For example, the external network connects to the internal network.

That would be great if this feature is supported.

**Comment by nilebox** [comment]
Implementation on the collector side for reference: https://github.com/open-telemetry/opentelemetry-collector/pull/1021

**Comment by tensorchen** [comment]
May I work on this?

**Comment by MrAlias** [comment]
It looks like I duplicated this with #1122 mistakenly. I'm going to close this as there doesn't seem to be movement here. Please reopen if that was a mistake.
