### ISSUE TITLE
Investigate Refactor of simple Integrator Process function

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#862]
TODO: as seen in lengthy comments below, both the `current` and `delta` fields have multiple uses depending on the specific configuration of instrument, exporter, and accumulator.  It is possible to simplify this situation by declaring explicit fields that are not used with a dual purpose.  Improve this situation?

1. "delta" is used to combine deltas from multiple accumulators, and it is also used to store the output of subtraction when computing deltas of PrecomputedSum instruments.
2. "current" either refers to the Aggregator passed to Process() by a single accumulator (when either there is just one Accumulator, or the instrument is Asynchronous), or it refers to "delta", depending on configuration.

_Originally posted by @jmacd in https://github.com/open-telemetry/opentelemetry-go/pull/856#issuecomment-648328618_

**Comment by jmacd** [comment]
Note also this related comment:
```
		// TODO: This code is organized to support multiple
		// accumulators which could theoretically produce the
		// data for the same instrument with the same
		// resources, and this code has logic to combine data
		// properly from multiple accumulators.  However, the
		// use of *metric.Descriptor in the stateKey makes
		// such combination impossible, because each
		// accumulator allocates its own instruments.  This
		// can be fixed by using the instrument name and kind
		// instead of the descriptor pointer.
```
