### ISSUE TITLE
Add array support to OTLP exported attributes

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#869]
There are also now array and key-value map types in OTLP: https://github.com/open-telemetry/opentelemetry-proto/blob/e43e1abc40428a6ee98e3bfd79bec1dfa2ed18cd/opentelemetry/proto/common/v1/common.proto#L35-L36

_Originally posted by @nilebox in https://github.com/_render_node/MDExOlB1bGxSZXF1ZXN0NDM4ODYyNDEx/pull_requests/unread_timeline_

**Comment by stefanprisca** [comment]
I would like to work on this.
@MrAlias has it been decided to export the map structure as well as array values? It seems to have been an open discussion: https://github.com/open-telemetry/opentelemetry-go/pull/866#discussion_r444977290

**Comment by MrAlias** [comment]
@stefanprisca the array values definitely need to be incorporated. The map type is not a supported part of the specification and I think there is consensus there to not add it (at least currently) so this could be changed to just include the array kv type.

**Comment by stefanprisca** [comment]
Can this issue be closed?

**Comment by Aneurysm9** [comment]
> Can this issue be closed?

Yup.  You can mark a PR to automatically close an issue by using the magic words "Fixes #<issue number>" in the PR description.
