### ISSUE TITLE
Improve metric test helpers for instrumentation

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-go#872]
There is a test helper in `internal/metric` used by a few of the tests in this repository. They're not great tests from a readability standpoint, but this is the only facility provided to test instrumentation with a mock Meter. 

There is a better test helper used internally in a number of tests, `sdk/metric/processor/test.Output`, which makes for reasonably concise and readable tests. Something similar should be provided for testing metrics, probably outside of the `internal` directory so that it can be used for testing external code.

As part of this ticket, improve the testing in `instrumentation/othttp/handler_test.go` as discussed [here](https://github.com/open-telemetry/opentelemetry-go/pull/861#discussion_r445308696).

**Comment by AndrewGrachov** [comment]
Will take it

**Comment by AndrewGrachov** [comment]
Found quite nice test implemetations here, so it could be just moving things around and small  tests refactor.

https://github.com/open-telemetry/opentelemetry-go/blob/master/api/global/internal/meter_test.go#L116

What you would say @jmacd @Aneurysm9 ?

**Comment by MrAlias** [comment]
@AndrewGrachov are you still working on this?

**Comment by AndrewGrachov** [comment]
Got stuck.

Really dont see a good way to implement it via sdk/test.Output - its heavily dependent on counter names, e.g. using suffixes to do aggregation checks, which irrelevant when testing instrumentation

So I guess we could just expose test helpers from mock meter, which do assertion, and re-use them.

Will send a PR today/tomorrow, for that I have clear view

**Comment by AndrewGrachov** [comment]
left a concept here

https://github.com/open-telemetry/opentelemetry-go/pull/1040/files

**Comment by jmacd** [comment]
Re-opening this issue for its original purpose, to remove the two TODOs marked #872.
