### ISSUE TITLE
Extend semantic conventions for RPC in `api/standard` package

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#893]
| Attribute name |                          Notes and examples                            | Required? |
| -------------- | ---------------------------------------------------------------------- | --------- |
| `rpc.system`   | A string identifying the remoting system, e.g., `"grpc"`, `"java_rmi"` or `"wcf"`.       | Yes |
| `rpc.service`  | The full name of the service being called, including its package name, if applicable.    | No, but recommended |
| `rpc.method`   | The name of the method being called, must be equal to the $method part in the span name. | No, but recommended |

Related to https://github.com/open-telemetry/opentelemetry-specification/pull/604

**Comment by matej-g** [comment]
I took the liberty of opening a PR for this - https://github.com/open-telemetry/opentelemetry-go/pull/900 - hopefully that's OK
