### ISSUE TITLE
`go get -u` depending upon otel-go fails

### ISSUE THREAD

**Issue by lizthegrey** [open-telemetry/opentelemetry-go#90]
```
$ go get -u
github.com/open-telemetry/opentelemetry-go@v0.0.0-20190812224656-6c2b769f8cb6: parsing go.mod: unexpected module path "go.opentelemetry.io"
```

is this a breaking change that I missed at some point, or is it a more structural problem?

**Comment by bogdandrutu** [comment]
Try `go get -u go.opentelemetry.io`

**Comment by lizthegrey** [comment]
```
go get go.opentelemetry.io: unrecognized import path "go.opentelemetry.io" (https fetch: Get https://go.opentelemetry.io?go-get=1: dial tcp: lookup go.opentelemetry.io on 10.10.0.2:53: no such host)
```

**Comment by bogdandrutu** [comment]
Fixed. The domain was moved to be owned by cncf and the DNS rules were removed somehow. Retry the command (you may need to clear your dns entries).

**Comment by lizthegrey** [comment]
bingo. Thank you! Glad it wasn't just a phantom after all.

**Comment by lizthegrey** [comment]
Confirmed that I'm back compiling, thanks!

**Comment by chriswhiteoco** [comment]
I am currently  getting the error as well:

go: github.com/open-telemetry/opentelemetry-go@v1.14.0: parsing go.mod:
        module declares its path as: go.opentelemetry.io/otel
                but was required as: github.com/open-telemetry/opentelemetry-go

**go version:**
go version go1.20.1 windows/amd64
 
**go.mod:**

go 1.20

require (
	github.com/jackc/pgconn v1.14.0
	github.com/jackc/pgx/v4 v4.18.0
	github.com/jackc/pgx/v5 v5.3.1
	github.com/open-telemetry/opentelemetry-go v1.14.0
)

**Comment by dmathieu** [comment]
`go.opentelemetry.io` should never be required itself, as that package doesn't hold any code. Everything is in subpackages.
You should include `go.opentelemetry.io/otel` for the SDK.
See https://pkg.go.dev/go.opentelemetry.io

Similarly, `github.com` should never be used in imports. You should use `go.opentelemetry.io`.
So your issues aren't because of problems in the repository, but with your imports.
