### ISSUE TITLE
Ability to Flush / Shutdown span batcher on app exit

### ISSUE THREAD

**Issue by vmihailenco** [open-telemetry/opentelemetry-go#902]
Is there any way to Shutdown the SpanBatchProcessor on app exit to ensure that queued spans are properly sent?

**Comment by nilebox** [comment]
@vmihailenco As a workaround, you may call `UnregisterSpanProcessor` on the app exit which does call `Shutdown`, see https://github.com/open-telemetry/opentelemetry-go/blob/a98bb979df54b9045ff51f3e2aa5da8e733a38ff/sdk/trace/provider.go#L148

But it would be more idiomatic to pass a `context.Context` parameter in the provider constructor to let it gracefully shut down itself: https://github.com/open-telemetry/opentelemetry-go/blob/a98bb979df54b9045ff51f3e2aa5da8e733a38ff/sdk/trace/provider.go#L59

**Comment by MrAlias** [comment]
Work to directly add this functionality is being tracked in https://github.com/open-telemetry/opentelemetry-go/issues/1072

Going to close in favor of that issue.
