### ISSUE TITLE
Fix api/global test flake

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-go#907]
--- FAIL: TestHandlerTestSuite (0.03s)
    --- FAIL: TestHandlerTestSuite/TestNoDropsOnDelegate (0.02s)
        handler_test.go:129: 
            	Error Trace:	handler_test.go:129
            	Error:      	Received unexpected error:
            	            	no errors sent in 10ms
            	Test:       	TestHandlerTestSuite/TestNoDropsOnDelegate
            	Messages:   	switched to new Handler
FAIL
FAIL	go.opentelemetry.io/otel/api/global	0.082s

**Comment by MrAlias** [comment]
I think we may need to bump our CI instance size again. I've noticed that error when I run tests locally limiting to a single core.

Also, I've seen [this](https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-go/2705/workflows/c013cb58-9305-444b-9045-ea88cee9c504/jobs/3646/steps) failure under those conditions as well:

```
--- FAIL: TestNewExporter_collectorConnectionDiesThenReconnects (0.51s)
    otlp_integration_test.go:349: Round #1: Connected collector: spans: got 0 want 10
FAIL
FAIL	go.opentelemetry.io/otel/exporters/otlp	1.556s
ok  	go.opentelemetry.io/otel/exporters/otlp/internal/transform	1.069s
FAIL
Makefile:96: recipe for target 'test' failed
make: *** [test] Error 1
```

**Comment by MrAlias** [comment]
also, [this](https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-go/2705/workflows/357d0044-1d80-4920-a16a-118b668204fc/jobs/3648/steps)

```
--- FAIL: TestHandlerTestSuite (0.05s)
    --- FAIL: TestHandlerTestSuite/TestNoDropsOnDelegate (0.01s)
        handler_test.go:121: 
            	Error Trace:	handler_test.go:121
            	Error:      	Received unexpected error:
            	            	no errors sent in 10ms
            	Test:       	TestHandlerTestSuite/TestNoDropsOnDelegate
            	Messages:   	starting error stream
FAIL
coverage: 1.5% of statements in ./...
FAIL	go.opentelemetry.io/otel/api/global	0.172s
```

**Comment by MrAlias** [comment]
Oof, also, [this](https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-go/2705/workflows/b7fd3897-968a-47b3-a21c-5095afad853f/jobs/3650/steps)

```
ok  	go.opentelemetry.io/otel/sdk/metric/controller/pull	1.156s	coverage: 9.4% of statements in ./...
--- FAIL: TestPushExportError (0.01s)
    --- FAIL: TestPushExportError/errNone (0.00s)
        push_test.go:255: 
            	Error Trace:	push_test.go:255
            	Error:      	Not equal: 
            	            	expected: 1
            	            	actual  : 0
            	Test:       	TestPushExportError/errNone
FAIL
coverage: 10.0% of statements in ./...
FAIL	go.opentelemetry.io/otel/sdk/metric/controller/push	0.104s
```

**Comment by Aneurysm9** [comment]
Would this issue be fixed more durably by using GitHub Actions, as proposed in #880?
