### ISSUE TITLE
automated advisory on CHANGELOG.md requirement

### ISSUE THREAD

**Issue by lizthegrey** [open-telemetry/opentelemetry-go#932]
We should use GitHub Actions to put up a yellow warning if there's no CHANGELOG.md associated with a PR

**Comment by lizthegrey** [comment]
alternatively, https://github.com/marketplace/actions/generate-changelog might allow generating the changelog automatically

**Comment by Aneurysm9** [comment]
Definitely in favor of using Actions to flag a warning if there is no changelog entry.  Not sure about attempting to automate it.  The changelog on this project reads more like product release notes than a list of PR titles, which I appreciate and don't believe would be achieved through automation.
