### ISSUE TITLE
Add Histogram Support to STDOUT Exporter

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#954]
The aggregation should be output with the bucket/count pairs being displayed to the user.

**Comment by mujtaba-ahmed12** [comment]
@MrAlias I would like to take this issue.

**Comment by jmacd** [comment]
This could use the format embraced by Prometheus for the boundaries as "le" labels.

The upper boundary at 1 is encoded as a label "le=1" in this scheme.

**Comment by MrAlias** [comment]
> This could use the format embraced by Prometheus for the boundaries as "le" labels.
> 
> The upper boundary at 1 is encoded as a label "le=1" in this scheme.

Given our existing JSON structure here I had originally though something like:

```
type expoLine struct {
	Name      string      `json:"name"`
...
	Histogram []bucket    `json:"histogram,omitempty"`
}

type boundary struct {
	Min float64 `json:"min"`
	Max float64 `json:"max"`
}

type bucket struct {
	boundary `json:"bounds"`
	Count    float64 `json:"count"`
}
```

But, I wonder if we couldn't also have a form of the exporter export prometheus metrics. They are text based and well known.

Maybe add as option like `PrettyPrint`?

**Comment by MrAlias** [comment]
Resolved by https://github.com/open-telemetry/opentelemetry-go/pull/3175
