### ISSUE TITLE
Unify metric and trace the STDOUT exporters

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#955]
Similar to the OTLP exporter, we should unify the STDOUT exporters that exist in the trace and metric directories.

**Comment by mujtaba-ahmed12** [comment]
@MrAlias I would like to take this issue.

**Comment by MrAlias** [comment]
@mujtaba-ahmed12 I have put together #956 to resolve this already. Sorry if that caused wasted effort.
