### ISSUE TITLE
Move OpenTelemetry API to top level go.opentelemetry.io/otel package

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#964]
In a recent review of the project, one of the things identified that we can do to ease discoverability instrumentation structures and ease adoption of the project for new users is to move relevant instrumentation structures and interfaces in the top level package. 

This means taking tracing and metric APIs and moving them to the `go.opentelemetry.io/otel` package. Namely:

- `go.opentelemetry.io/otel/api/trace`
   - `Provider`
      - Rename to `TraceProvider`
   - `Span`
   - `Tracer`
- `go.opentelemetry.io/otel/api/metric`
   - `BatchObserver`
   - `BatchObserverCallback`
   - `BoundFloat64Counter`
   - `BoundFloat64UpDownCounter`
   - `BoundFloat64ValueRecorder`
   - `BoundInt64Counter`
   - `BoundInt64UpDownCounter`
   - `BoundInt64ValueRecorder`
   - `Float64Counter`
   - `Float64ObserverCallback`
   - `Float64ObserverResult`
   - `Float64SumObserver`
   - `Float64UpDownCounter`
   - `Float64UpDownSumObserver`
   - `Float64ValueObserver`
   - `Float64ValueRecorder`
   - `Int64Counter`
   - `Int64ObserverCallback`
   - `Int64ObserverResult`
   - `Int64SumObserver`
   - `Int64UpDownCounter`
   - `Int64UpDownSumObserver`
   - `Int64ValueObserver`
   - `Int64ValueRecorder`
   - `Meter`
   - `Observation`
   - `Provider`
      - Rename to `MeterProvider`

This is not a comprehensive list. There are likely other elements of the API that need to be moved or re-engineered in the move.

**Comment by lizthegrey** [comment]
May relate to #940 to separate API package from SDK packages to minimize dependency set for using OTel API only.

**Comment by MrAlias** [comment]
Investigation of how we want to position the `global` package will have to be included in this work.

**Comment by MrAlias** [comment]
Related issues:

* https://github.com/open-telemetry/opentelemetry-go/issues/1012
* https://github.com/open-telemetry/opentelemetry-go/issues/1052
* https://github.com/open-telemetry/opentelemetry-go/issues/1009

**Comment by MrAlias** [comment]
This should resolve #448
