### ISSUE TITLE
Merge HTTP instrumentation

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go#974]
The existing `othttp` and `httptrace` instrumentation need to be merged into a generalized instrumentation package to work with the standard library's `net/http` package.

- [ ] supports propagation of context.
- [ ] includes an `http.Handler` wrapper that will create spans and metric events for received requests.
   - https://github.com/open-telemetry/opentelemetry-specification/pull/739
- [ ] well documented.
- [ ] is a versioned module.
- [ ] likely needs to follow [the naming scheme outline in the contrib repo](https://github.com/open-telemetry/opentelemetry-go-contrib/tree/master/instrumentation#packaging): `go.opentelemetry.io/otel/instrumentation/net/http`

**Comment by MrAlias** [comment]
Relates to #940 (breaking into own module).

**Comment by MrAlias** [comment]
It seems to follow that this should be moved to the contrib repository. We have opensource libraries as well as stdlib library instrumentation support there. It seems like a good idea to consolidate everything into a single location.

**Comment by Aneurysm9** [comment]
I've created https://github.com/open-telemetry/opentelemetry-go-contrib/issues/158 to relocate this instrumentation.  The naming convention in contrib would lead me to think that the `net/http` and `net/httptrace` instrumentations should remain separate.  Thoughts?

**Comment by MrAlias** [comment]
> I've created [open-telemetry/opentelemetry-go-contrib#158](https://github.com/open-telemetry/opentelemetry-go-contrib/issues/158) to relocate this instrumentation. The naming convention in contrib would lead me to think that the `net/http` and `net/httptrace` instrumentations should remain separate. Thoughts?

The [`httptrace` package](https://golang.org/pkg/net/http/httptrace/) in stdlib is a subpackage to `net/http`. Should we follow that structure as well? Not sure if there are implementation specific details that would prevent that structure, but it seems like it would be a decent approach to follow.

**Comment by MrAlias** [comment]
closing in favor of https://github.com/open-telemetry/opentelemetry-go-contrib/issues/158
