### ISSUE TITLE
otel-collector example uses old 'jaeger_grpc' exporter name

### ISSUE THREAD

**Issue by stefanprisca** [open-telemetry/opentelemetry-go#991]
The otel collector jaeger grpc exporter has been renamed from "jaeger_grpc" to "jaeger" (see [760](https://github.com/open-telemetry/opentelemetry-collector/issues/760)). However the otel exporter example still uses the old name, and fails for version 0.5.0 of the collector.

**Comment by stefanprisca** [comment]
The fix for this is simple, but I ended up getting a grpc error when connecting to the collector. I would like to look more into it, and see what the problems are.

**Comment by MrAlias** [comment]
@stefanprisca lmk if this shouldn't be assigned to you.

**Comment by stefanprisca** [comment]
Can this issue be closed?
